* cobradores
** eventos
| [2018-10-02 mar] | 808 | no cobro nada | 815 refirio que sufrio ataque nervio, llanto y tuvo que llamarla |
| [2018-10-02 mar] | 809 | falto         |                                                                  |
| [2018-10-03 mié] | 809 | falto         |                                                                  |
| [2018-10-04 jue] | 809 | falto         |                                                                  |
** bitacora
*** [2018-10-03 mié] 
**** 815/808 cagada a pedo respecto a 808 que anda mal y no se presenta
le dije que no acepta venir y que no le gusta rendir cuentas. Que
siempre viene apurada como si estacionara en doble fila, e incluso se
quejo de que yo hablara con los otros. Que era una parte necesaria del
negocio. Que EFlores andaba mal. Que pienso que le tiene miedo al
barrio. Que no me explico como no lo hace el. Que son marido y mujer
no dos extraños. Que ella ya se sentia mal con la division de las
zonas. Que no hacia falta que viniera todos los dias aunque podia ser
dos veces por semana. (Notar que el 802 cuando salio dijo que se iba
rapido pq tenia que hablar afuera con Graciela...)
**** 802/815 respecto al comentario sobre el choreo del 801
A ambos por separado les hice un comentario velado a lo Pablo Escobar
que una vez que se solucionara lo de la moto le iba a "mandar mis
muchachos" a ajustar cuentas con el viejo de mierda ese.
*** [2018-10-04 jue]
**** curso al 817 de 16.30 a 17.45hs, 
enviado a Sargento, que es su barrio y se le asignaria yofre sur,
fragueiro y marques. No se si esta tan interesado, no lo manifiesta
pero puede ser un buen elemento vamos a ver. 
**** encuentro del Fede con 808/815
los encontro juntos en zona y le dijeron que estan separados, pero
juntos trabajan mejor, que el tipo vive en italia, y ella vive en
Platanos. Habria que ver que para con una unificacion de zona. 
**** 802 toma conocimiento que 809 no viene
y queda en llamarlo para ver que le pasa y comenta que no puede estar
en connivencia con 801 pq se habia manifestado con bronca con lo que
el otro habia hecho.
** estrategia
*** [2018-10-03 mié]
mañana tengo entrevista con el 817 Fernando para la zona Sargento,
Fragueiro, Marques, Panamericano y Yofre2, pienso dejarle Yofre1 al
815 y al 802 acomodarle Mosconi, Corina, Bustos Talleres Pueyrredon y
al 800 Patricios y Llanos, y el sabado tengo 816 Fabian para darle
todo Olmedo o bien si se confirma la huida del 809 le doy la ruta ag a
Fabian y parte de hernandez y olmedo se lo doy al nuevo que tengo
mañana que casualmente vive en la ruta 9. 
Y No citaria a la Doña Ximena pq primero no tendria zona con estos dos
grandes que contrataria y segundo pq por mas que me impresiono bien,
se cayo un poco la indisponibilidad de la postulante. Es decir, citada
a un horario, me llega tarde, y luego de un rato de entrevista, le
llaman por telefono, pq tiene que retirar los chicos del colegio, o
sea para alguien que no dispone sino de un par de horas no
da. Mostraste la hilacha. 
**** la estrategia es tener dos supercobradores-vendedores
o sea dos cobradores de confianza diferenciados que accedan a deposito
y tengan la posibilidad de vender. Esa posibilidad de vender va a ser
muy importante a largo plazo. 
** recibos faltantes
|fecha|rbo|cobr| 

* tareas
** DONE traer los docs "a devolver de la oficina"
- State "DONE"       from "TODO"       [2018-10-04 jue 18:38]
y encarpetarlos en un nepako y tenerlos en dpto


 no tiene sentido tener esos documentos en la oficina pq no fueron
 reclamados y se van a terminar perdiendo. Ya los nepakie y los voy a
 llevar al dpto.
