* cobradores
** eventos
| [2018-10-02 mar] | 808 | no cobro nada | 815 refirio que sufrio ataque nervio, llanto y tuvo que llamarla |
| [2018-10-02 mar] | 809 | falto         |                                                                  |
| [2018-10-03 mié] | 809 | falto         |                                                                  |
| [2018-10-04 jue] | 809 | falto         |                                                                  |
** bitacora
*** [2018-10-03 mié] 
**** 815/808 cagada a pedo respecto a 808 que anda mal y no se presenta
le dije que no acepta venir y que no le gusta rendir cuentas. Que
siempre viene apurada como si estacionara en doble fila, e incluso se
quejo de que yo hablara con los otros. Que era una parte necesaria del
negocio. Que EFlores andaba mal. Que pienso que le tiene miedo al
barrio. Que no me explico como no lo hace el. Que son marido y mujer
no dos extraños. Que ella ya se sentia mal con la division de las
zonas. Que no hacia falta que viniera todos los dias aunque podia ser
dos veces por semana. (Notar que el 802 cuando salio dijo que se iba
rapido pq tenia que hablar afuera con Graciela...)
**** 802/815 respecto al comentario sobre el choreo del 801
A ambos por separado les hice un comentario velado a lo Pablo Escobar
que una vez que se solucionara lo de la moto le iba a "mandar mis
muchachos" a ajustar cuentas con el viejo de mierda ese.
*** [2018-10-04 jue]
**** curso al 817 de 16.30 a 17.45hs, 
enviado a Sargento, que es su barrio y se le asignaria yofre sur,
fragueiro y marques. No se si esta tan interesado, no lo manifiesta
pero puede ser un buen elemento vamos a ver. 
**** encuentro del Fede con 808/815
los encontro juntos en zona y le dijeron que estan separados, pero
juntos trabajan mejor, que el tipo vive en italia, y ella vive en
Platanos. Habria que ver que para con una unificacion de zona. 
**** 802 toma conocimiento que 809 no viene
y queda en llamarlo para ver que le pasa y comenta que no puede estar
en connivencia con 801 pq se habia manifestado con bronca con lo que
el otro habia hecho.
*** [2018-10-05 vie]
**** curso a Fabian (816) a las 16hs
muy bien se presento puntual aunque tuvo que dejar el auto lejos. De
lo que hablamos me planteo que tiene unos 300 de gasto por dia para ir
y venir y que yo le pague el gas de la ciudad segun los km que haga. 
Lo cual el calcula que serian 150 por 70km. Le dije que no habia
problema. Tiene algunos clientes el viernes que le dije que puede
mixturar con el trabajo del viernes, y que tiene que venir todos los
dias. Esta dispuesto a trabajar todo el dia digamos desde las 10 hasta
las 17hs que tiene que ir cortando para venir a rendir aca. Rendiria
primero a las 18hs para ir volviendo temprano a AG. 
**** 809 clava el visto al 802 preguntando sobre el trabajo
el Leo le mando a preguntar sobre la familia y el le contesto esta
bien gracias. y le pregunto pq no va a trabajar y le clavo el visto.
** estrategia
*** [2018-10-03 mié]
mañana tengo entrevista con el 817 Fernando para la zona Sargento,
Fragueiro, Marques, Panamericano y Yofre2, pienso dejarle Yofre1 al
815 y al 802 acomodarle Mosconi, Corina, Bustos Talleres Pueyrredon y
al 800 Patricios y Llanos, y el sabado tengo 816 Fabian para darle
todo Olmedo o bien si se confirma la huida del 809 le doy la ruta ag a
Fabian y parte de hernandez y olmedo se lo doy al nuevo que tengo
mañana que casualmente vive en la ruta 9. 
Y No citaria a la Doña Ximena pq primero no tendria zona con estos dos
grandes que contrataria y segundo pq por mas que me impresiono bien,
se cayo un poco la indisponibilidad de la postulante. Es decir, citada
a un horario, me llega tarde, y luego de un rato de entrevista, le
llaman por telefono, pq tiene que retirar los chicos del colegio, o
sea para alguien que no dispone sino de un par de horas no
da. Mostraste la hilacha. 
**** la estrategia es tener dos supercobradores-vendedores
o sea dos cobradores de confianza diferenciados que accedan a deposito
y tengan la posibilidad de vender. Esa posibilidad de vender va a ser
muy importante a largo plazo. 
*** [2018-10-05 vie]
**** ¿Cual es la verdadera necesidad estrategica? Realidad/Fantasia
Cuando pense en llamar a Fabian y despues se sumo el Fernando (yo
pensaba en el Ariel en un principio) yo pensaba solo en la cobranza o
sea en el no poder tener gente que se aboque al tema de la cobranza
como lo hace el 802 (o lo hizo el 801 esos pocos dias que funciono
antes de irse, idem el 744) o sea que funcione bien con pocas
fichas. Pero posiblemente chocaremos con una realidad, y es que lo
mismo no podran hacer milagros y tendran que facturar igual, y en el
caso de Fabian mas, pq viene de lejos. Y con visitar morosos no se
factura y no se gana plata, entonces que haran?. En el caso de estos
dos lo que tienen de estrategico es que les tenemos confianza y tienen
auto como para visitar clientes, entonces podemos activar la visita de
clientes que tenemos descuidada. Entonces podemos hacer un mix de
visita cliente/cobranza, o quizas ir derivando en un futuro visita de
clientes unicamente.
Ya que en realidad la fantasia es que alguien te vaya a decir que lo
incobrable sea cobrable. 
Creo que hay que cambiar otras cosas.
**** [#A] estrategias de cambio mas realistas respecto a la cobranza
***** mejores notificaciones
tengo una carta light y obsoleta, podria tener otra mas agresiva y/o
dos o mas cartas.
a su vez ir convenciendo a los cobradores que tienen que insistir con
las notificaciones.
***** busqueda de abogado para enviar cartas de abogado
pero que podamos enviarlas nosotros
***** incorporacion de mas cobradores 
habilitando entrevistas y cursos a las 16hs/17hs podremos tener mas
cobradores disponibles.
***** asertividad en el manejo de cobradores
estar dispuesto a la perdida y asumirla como parte del negocio
***** asertividad en el manejo de los incobrables
con el manejo de los cajones de mudados/gestion/incobrables y un mejor
manejo de cartas y la division de zonas manejar el todo con
asertividad sin involucramiento.
***** manejar la division de zonas
para no estar preso de la gestion de las individualidades.
**** Pasos a seguir
esperando los resultados, el proximo es reducirle la zona a 750,
creando el 819, que podria ser el jaled, o podria ser el padre del
802, o podria ser el padre del 816 ver.  
*** [2018-10-07 dom]
**** venta por cobradores Fabian y Fernando:
hablamos con Fede que ibamos a vender todo por 4 incluso las sabanas
salvo las cortinas que las dejabamos al precio superior a delta4. Todo
en 6 cuotas. Que el les daba stock, anotando un remito de salida que
me mandaba en foto. Yo iba a programar un stock individual. Le ibamos
a pagar el 10% sobre la venta en forma mensual simpre que se pague la
primer cuota de lo vendido, para evitar las devoluciones y los
incobrables como son ellos mismos los que cobran. Entonces yo mismo
iba a administrar todo eso.
**** sobre el colgar el diploma de la Romi adelante
que era inconveniente a pesar que a mi me gustaba, pq iba a hacer
cascara con la profesion de mi hija, pero era verdad el riesgo de
ensuciarla definitivamente con la escoria que la pudiera salpicar era
grande y muy dificil de limpiar, entonces decidimos sacarlo.
** recibos faltantes
| fecha            |    rbo | cobr |
| [2018-10-04 jue] | 274849 | 800  |
|                  |        |      |
** planillas robadas
se indica el dia de procesamiento en el pasado de Recibos
*** 731 [2018-06-11 lun]
*** 812 [2018-06-22 vie]
*** 744 [2018-09-03 lun]
*** 813 [2018-09-13 jue] 2846
*** 801 [2018-09-21 vie]
*** 809 [2018-10-02 mar] 2934
* tareas
** DONE traer los docs "a devolver de la oficina"
- State "DONE"       from "TODO"       [2018-10-04 jue 18:38]
y encarpetarlos en un nepako y tenerlos en dpto


 no tiene sentido tener esos documentos en la oficina pq no fueron
 reclamados y se van a terminar perdiendo. Ya los nepakie y los voy a
 llevar al dpto.
* ventas
** devoluciones
| fecha            | prom | zona     |      DNI | direccion        | articulos    | estado   | cobr | multa | t/p | excusa                      |
| [2018-10-04 jue] |  792 | YofreSur |  4132831 | Alsina 1352      | indu1/cocina | 9 puntos |  802 | no    | t   | viaje pq operaban a alguien |
| [2018-10-05 vie] |  768 | Coops    | 25267386 | Mna 36-23        | cor/coc/man  | 7 puntos |  802 | no    | t   | no expresa                  |
| [2018-10-05 vie] |  796 | Revol    |  4707724 | Necochea 2748    | cor/coc      | 9 puntos |  802 | no    | t   | no expresa                  |
| [2018-10-05 vie] |  811 | Flores   | 22772903 | Mna 40-7 Aspasia | cor          | 8 puntos |  808 | no    | p   | incobrabilidad              |
|                  |      |          |          |                  |              |          |      |       |     |                             |
** condonados
| cuenta | excta | actu | seven | fecha seven      | flag | comentarios                                                                   |
|  70063 | 59372 | 1031 | seven | [2017-04-20 jue] | NVM  |                                                                               |
|  69969 | 58334 | 2526 |       |                  |      | No vender mas. Insolvente, irresponsable. Dice que devolvio la cortina a 747. |
|  69933 | 41164 | 2310 |       |                  |      | ninguno: pero no habia pagado nunca de 13 cuotas pago una.                    |
|        |       |      |       |                  |      |                                                                               |
