#+TAGS: INICIO MEDIO ALTO
#+TAGS: EMACS ORG ELIPS TCL TABLELIST SQLITE PYTHON UBUNTU LINUX VIM PRINT SOLUS
* Documentacion general
que es la teoria? es el lugar donde acumularemos todo lo que sea
aprendizaje o documentacion. en vez de tener uno por tema aca vendran
todos juntos
* emacs
* org-mode
** Solucion al no funcionamiento de los Capture Template               :ORG:
[2018-10-09 mar 19:44]

Capture Template programados en otra maquina y que funcionaban bien en
la oficina no funcionaban o lo hacian parcialmente, en especial no
andaba el de jornal que tenia datatree+olp.
La version que tenia de org era la 8.algo que incluso actualizandola
via apt no obtuve gran diferencia, cosa que si habia logrado en el
dpto pq ese xubuntu es 2018 y el de aca es 2016. Entonces se me
ocurrio hacer un package-list y buscar org directamente e instalar
desde alli, y lo instalo de una y ahora la version indica 9.1.14 y ese
parece ser el problema de que no funcione el template.
* tcl
* tablelist
* sqlite
* python
** comandos interesantes pycharm                                    :PYTHON:
[2018-10-10 mié 18:33]
| S-F6  | refactorizar-rename | rename all ocurrences symbol |
| C-F12 | buscar symbol       |                              |
| C-F11 | add-bookmark        | numero o letra               |
| S-F11 | ir a bookmark       |                              |
| F11   | toggle bookmark     |                              |
|       |                     |                              |

* instalacion ubuntu
* vim
* linux
** crear un usb con una distro con dd                                :LINUX:
[2018-10-10 mié 21:18]
con lsblk averiguamos la letra de asignada al usb.
No desmontar como dicen por ahi
sudo dd if=/home/... ubic del iso of=/dev/sdb bs=1M

* SOLUS
** instalacion de TCL en solus                                       :SOLUS:
[2018-10-10 mié 23:14]
ningun archivo de tcl esta. 
Entonces instale ActiveState en un directorio de Home para luego
borrarlo y fui moviendo subdirectorios a pedido de acuerdo a lo que
demandaban los programas.
*** pdf4tcl
que lo instale desde el backup mio
*** tablelist 
que baje la ultima version
*** tcllib1.18
pq F13.tcl me pedia snit para que funcionara pdf4tcl
*** bwidget
*** Img
*** itcl y itk
alli vino el problema pq me daba un error que yo asumi que era una
gran incompatibilidad y luego cuando lei bien decia algo como que: 
Error in startup script: Can't find a usable itk.tcl in the following directories:
    /usr/lib64/itk4.1.0 /usr/bin/../lib/itk4.1.0 /usr/bin/../library /usr/bin/../../library /usr/bin/../../itk/library
This probably means that Itcl/Itk weren't installed properly.
o sea que no encontraba el directorio de itk directamente en /usr/lib
no dentro de tcl8.6 como estan todos, entonces lo copie directo a
/usr/lib  y anduvo perfecto.
*** directorio en solus para tcl /usr/lib/tcl8.6/
** problema con los modulos python                                   :SOLUS:
[2018-10-10 mié 23:51]
no tiene pip3, entonces se instalan con pip, de una, y hay que hacerlo
con sudo.
y luego hay que copiarlos de la ubicacion del modulo en python2.7 a
3.6
hero@hero /usr/lib64/python2.7/site-packages $ sudo cp -r pypercl*
/usr/lib64/python3.6/site-packages/
Uso asteriscos porque pueden ser varias cosas y uso -r pq pueden ser
directorios con dateutils paso asi.

No obstante se me trabo fastnumbers que no anda y parece un bug que
hasta esta en la web, asi que voy a ver si lo desinstalo.




** instalacion de hp1102 en solus                                    :SOLUS:
[2018-10-11 jue 15:00]
1) instalar en solus HPLIP
2) en un terminal poner hp-setup y seguir las indicaciones
3) desde configuracion de impresion hacerla predeterminada
nada mas que eso. Y se soluciono el problema de la cola de impresion,
que tenia un dia atras en xubuntu aparentemente, pq anda bien, lo
unico que con otras fuentes se imprimen los listados
* impresoras
** impresora hp no anda luego de cambio toner
[2018-10-10 mié 16:01]
da retenido y no arranca, resetie maquina y nada, cambie usb de lugar
y nada, borre impresora y nada, cuando prendia no se instalaba sola
como acostumbraba.
Luego la instalo desde el menu que te ofrece y tampoco andaba.
la borro, insisto pero esta vez la instalo como impresora usb y
anduvo.
Pero no quedo como antes, sino que cuando le mando varios trabajos no
los hace. incluso si es muy grande no lo procesa y a la segunda vez
que se lo mando lo procesa. 
es como si estuviera rota la cola de impresion.

* Refile
** problema con hibernacion :SOLUS:
[2018-10-11 jue 15:04]
tuve dos casos de que luego de equis minutos la maquina no respondia,
y tuve que resetearla, pienso que es pq la configuracion de energia
esta para entrar en hibernacion y esta maquina de escritorio queda en
estado loco. Lo desactive. veremos que pasa. 
