#+TAGS: INICIO MEDIO ALTO
#+TAGS: EMACS ORG ELIPS TCL TABLELIST SQLITE PYTHON UBUNTU LINUX VIM PRINT
* Documentacion general
que es la teoria? es el lugar donde acumularemos todo lo que sea
aprendizaje o documentacion. en vez de tener uno por tema aca vendran
todos juntos
* emacs
* org-mode
* tcl
* tablelist
* sqlite
* python
* instalacion ubuntu
* vim
 * impresoras
** impresora hp no anda luego de cambio toner
[2018-10-10 mié 16:01]
da retenido y no arranca, resetie maquina y nada, cambie usb de lugar
y nada, borre impresora y nada, cuando prendia no se instalaba sola
como acostumbraba.
Luego la instalo desde el menu que te ofrece y tampoco andaba.
la borro, insisto pero esta vez la instalo como impresora usb y
anduvo.
Pero no quedo como antes, sino que cuando le mando varios trabajos no
los hace. incluso si es muy grande no lo procesa y a la segunda vez
que se lo mando lo procesa. 
es como si estuviera rota la cola de impresion.

* Refile
** Solucion al no funcionamiento de los Capture Template               :ORG:
[2018-10-09 mar 19:44]

Capture Template programados en otra maquina y que funcionaban bien en
la oficina no funcionaban o lo hacian parcialmente, en especial no
andaba el de jornal que tenia datatree+olp.
La version que tenia de org era la 8.algo que incluso actualizandola
via apt no obtuve gran diferencia, cosa que si habia logrado en el
dpto pq ese xubuntu es 2018 y el de aca es 2016. Entonces se me
ocurrio hacer un package-list y buscar org directamente e instalar
desde alli, y lo instalo de una y ahora la version indica 9.1.14 y ese
parece ser el problema de que no funcione el template.
