#+title:      focus
#+date:       [2022-11-19 Sat 16:48]
#+filetags:   :resaltados:
#+identifier: 20221119T164809

Focus ───────────────

▪ bien podríamos considerar la atención como un músculo, que se
desarrolla en la medida en que se ejercita y que, en caso contrario,
acaba marchitándose.

▪ Veremos el modo en que la práctica inteligente puede contribuir a
desarrollar y perfeccionar el músculo de nuestra atención, o
rehabilitarlo en aquellos casos en que se encuentre infradesarrollado.

▪ la tecnología entorpece nuestras relaciones.

▪ Los niños de hoy en día crecen en una nueva realidad, una realidad
en la que están muy desconectados de sus semejantes y mucho más
conectados que nunca, por el contrario, con las máquinas, una
situación que, por razones muy diversas, resulta inquietante

▪ Una maestra de segundo de ESO me dijo que, durante muchos años,
había estado leyendo el libro Mithology, de Edith Hamilton, a
sucesivas generaciones de alumnos. Se trataba de un libro que les
gustaba mucho, hasta hace cinco años, en que, según me dijo: «Empecé a
ver que no les gustaba tanto, ni siquiera a quienes mejores notas
sacaban. Dicen que la lectura es demasiado difícil, que las frases son
muy complicadas y que, para leer una página, necesitan mucho tiempo»

▪ En torno al 8% de los jugadores estadounidenses de entre 8 y

▪ 18 años parece satisfacer los criterios diagnósticos establecidos
por la psiquiatría para diagnosticar la adicción. Y la investigación
cerebral realizada mientras juegan ha puesto de relieve la existencia
de cambios en su sistema neuronal de recompensa semejantes a los que
presentan los alcohólicos y los drogadictos[

▪ Existen, en este sentido, anécdotas que nos hablan de adictos a los
videojuegos que se pasan el día durmiendo y la noche jugando, sin
comer ni lavarse siquiera, y se muestran agresivos cuando algún
familiar tiene la osadía de interrumpirlos.

▪ El representante de una gran cadena de radiodifusión mexicana se
quejaba diciendo que: «Hace unos años, podíamos hacer un vídeo de
cinco minutos para presentarlo a una agencia de publicidad. Hoy no
podemos pasarnos del minuto y medio. Si, durante ese tiempo, no hemos
logrado captar su atención, todo el mundo echa mano a su teléfono para
ver si ha recibido un nuevo mensaje».

▪ Una ejecutiva del mundo editorial me confesó sentirse desbordada, al
cabo de un rato de no comprobar el estado de su teléfono móvil, por
«una sensación de discordancia. Echas de menos el impacto que acompaña
a la recepción de un mensaje

▪ Nuestra actuación será peor cuantas más interferencias obstaculicen
nuestra atención

▪ La atención concentrada mejora el aprendizaje. Cuando nos
concentramos en lo que estamos aprendiendo, el cerebro relaciona la
nueva información con la que ya conocemos y establece nuevas
conexiones neuronales.

▪ La pregunta más importante es: ¿Es usted feliz cuando se levanta
para ir a trabajar?

▪ Fantasean, pierden el tiempo navegando por la web o YouTube y se
limitan a hacer lo imprescindible. Su atención, dicho de otro modo, se
halla muy dispersa.

▪ Otro grupo considerable, por el contrario, se halla atrapado en un
estado que los neurobiólogos denominan «agotamiento extremo», en el
que el estrés continuo inunda su sistema nervioso con oleadas de
cortisol y adrenalina. De ese modo, su atención no se centra tanto en
su trabajo, sino que se fija obsesivamente en sus preocupaciones, un
estado que suele desembocar en el llamado burnout [quemado].

▪ La expresión «ascendente» [o «de abajo arriba»] ha acabado
convirtiéndose en la habitualmente utilizada por la ciencia cognitiva
para referirse a las operaciones llevadas a cabo por la maquinaria
neuronal propia del cerebro inferior

▪ la expresión «descendente» [o «de arriba abajo»] se refiere a la
actividad mental (de origen principalmente neocortical)

▪ La atención voluntaria, la voluntad y la decisión intencional
emplean los circuitos de arriba abajo, mientras que la atención
reflexiva, el impulso y los hábitos rutinarios lo hacen, por su parte,
de abajo arriba

▪ El ojo de nuestra mente ejecuta una danza continua entre la
modalidad de atención ascendente (atrapada por los estímulos) y la
modalidad descendente (voluntariamente dirigida).

▪ Resulta muy curioso que, en una especie de ilusión óptica, nuestra

▪ mente acabe equiparando lo que ocupa el centro de la conciencia con
la totalidad de nuestras operaciones mentales. Pero lo cierto es que
la inmensa mayoría de estas no ocupan el centro del escenario,

▪ Gran parte de aquello en lo que la mente descendente cree decidir
concentrarse, pensar y planear voluntariamente —si no todo, en opinión
de algunos— discurre, de hecho, por los circuitos ascendentes. Si se
tratara de una película, comenta irónicamente al respecto el psicólogo
Daniel Kahneman, la mente descendente sería «un personaje secundario
que se toma por el protagonista»

▪ El cerebro humano forma parte de un diseño evolutivo que, pese a ser
bastante bueno, no es perfecto[34]. El sistema ascendente más antiguo
funcionó bastante bien durante la mayor parte de la prehistoria, pero
son varios los problemas que actualmente nos provoca su diseño. Se
trata de un sistema que sigue siendo dominante y suele funcionar bien,
pero hay casos, como indican, por ejemplo, las adicciones, las compras
compulsivas y los adelantamientos imprudentes, en los que las cosas
parecen salirse de madre.

▪ Los investigadores han descubierto que la prevalencia de la obesidad
en los Estados Unidos durante los últimos 30 años mantiene una elevada
correlación (nada accidental, por otra parte) con el efecto que ha
tenido en la vida de las personas la explosión de los ordenadores y de
los dispositivos tecnológicos.

▪ La vida inmersa en distracciones digitales genera una sobrecarga
cognitiva casi constante, que desborda nuestra capacidad de
autocontrol… en cuyo caso olvidamos nuestra dieta y, sumidos en el
mundo digital, echamos inadvertidamente mano a la bolsa de patatas
fritas.

▪ Al cerebro le resulta imposible ignorar los rostros emocionalmente
cargados, en especial los enfadados[47]. Estos tienen mayor
relevancia, porque el cerebro ascendente escruta de continuo, en busca
de amenazas, lo que sucede más allá del campo de la atención
consciente. Por ello se muestra tan hábil en detectar, en medio de una
multitud, un semblante enfadado. La velocidad del cerebro inferior
para identificar una caricatura con las cejas en forma de V (como los
niños de South Park, por ejemplo) es mucho mayor que la que emplea en
descubrir un rostro feliz.

▪ El impulso interior que nos lleva a alejarnos del esfuerzo
concentrado es tan intenso que los científicos cognitivos han acabado
considerando la mente errante como la modalidad «por defecto» del
cerebro, el sistema que opera siempre que no nos hallamos sumidos en
ninguna tarea mental.

▪ Hay un cuento persa que nos habla de tres príncipes de Serendip,
«cuya inteligencia y sagacidad les llevaba a descubrir siempre cosas
que no estaban buscando»[56]. Pero así es como suele operar
naturalmente la creatividad

▪ Un modelo clásico de los estadios de la creatividad señala la
existencia de tres modalidades de atención diferentes: la orientación
(en la que buscamos y nos sumergimos en todo tipo de datos), la
atención selectiva a los retos creativos concretos, y la conciencia
abierta (en la que nos entregamos a la asociación libre hasta dar con
la solución).

▪ el 10% de los niños padecen TDAH [una modalidad de TDA combinada con
hiperactividad]. En el caso de los adultos, la hiperactividad acaba
desvaneciéndose, quedando solo el TDA, un problema que afecta a cerca
del 4% de los adultos

▪ «La mente creativa es un don sagrado y la mente racional un
sirviente fiel —dijo, en cierta ocasión, Albert Einstein—. Por ello
resulta muy curioso que hayamos creado una sociedad que, olvidando el
don, haya acabado honrando al sirviente»

▪ Para muchos de nosotros es un lujo contar, durante el día, con un
tiempo propio en el que podamos tumbarnos y reflexionar. Esos son, por
lo que respecta a la creatividad, algunos de los momentos más valiosos
de nuestra jornada.

▪ Pero, si queremos que esas asociaciones rindan un fruto provechoso,
necesitamos contar con algo más, el clima apropiado. Necesitamos
dedicar un tiempo también a la conciencia abierta.

▪ El tiempo libre posibilita el florecimiento del espíritu creativo,
mientras que las agendas demasiado estrictas, por el contrario, lo
sofocan.

▪ Las intuiciones no suelen presentarse como descubrimientos
sorprendentes ni como grandes victorias. La clave suele girar en torno
a pequeños avances (pequeñas innovaciones y soluciones a problemas
preocupantes), pasos concretos que nos acercan a un objetivo
mayor. Las intuiciones creativas florecen mejor cuando las personas
tienen objetivos claros y libertad también en el modo de
alcanzarlos. Y, lo más importante todavía, tienen suficiente tiempo
libre para pensar. Ese es el entorno más favorable para incubar la
creatividad.

▪ El estado de ánimo de las personas cuando su mente divaga tiende,
hablando en términos generales, hacia lo displacentero, hasta el punto
de que pensamientos con un contenido aparentemente neutro se ven
ensombrecidos por una carga emocional negativa. Pareciera como si la
mente errante fuese, en parte o casi totalmente, una de las causas de
la infelicidad.

▪ la mente errante tiende a centrarse en el yo y en sus preocupaciones

▪ El distractor más poderoso no es la charla interpersonal, sino la
incesante cháchara intrapersonal que se da en el escenario de nuestra
mente. La verdadera concentración exige acallar esa voz interior. Una
resta en la que, partiendo de 100, vamos sustrayendo sucesivamente 7
acabará aquietando, si nos concentramos en esa tarea, ese diálogo
interno.

▪ «Si la absorción total y el flujo reflejan el abandono del estado
errante de la mente y el centrarse por completo en una actividad, es
muy probable que desactiven los circuitos por defecto. No puedes,
mientras estás absorto en una tarea difícil, seguir dando vueltas en
torno a tu persona

▪ La mente errante y la conciencia perceptual tienden, desde un punto
de vista neuronal, a inhibirse. Atender, pues, al tren de nuestros
pensamientos desconecta los sentidos, mientras que permanecer atentos
a la belleza de una puesta de sol sosiega nuestra mente[69]. Y esta
desconexión puede llegar a ser total como sucede, por ejemplo, cuando
estamos completamente absortos en lo que estamos haciendo.

▪ Obviamente, esa falta parcial de sintonía no deja de tener sus
riesgos. Un estudio sobre 1000 conductores implicados en accidentes
puso de relieve que cerca del 50% afirmaba haber tenido el accidente
mientras estaban distraídos y que la probabilidad de sufrir un
accidente aumenta en función de la intensidad de los pensamientos
interferentes

▪ Detectar el momento preciso en que nuestra mente empieza a errar
resulta bastante difícil.

▪ Pero nuestra atención no tiene que estar a merced del modo en que el
mundo que nos rodea enmarca los objetos. De nosotros depende dirigir
nuestra atención hacia la aspiradora oculta entre las sombras o hacia
la que se encuentra iluminada. Mantener el rumbo de nuestra atención
refleja una modalidad mental en la que simplemente advertimos lo que
aflora en nuestra conciencia sin necesidad de aferrarnos ni rechazar
nada en particular.

▪ Esta apertura puede verse en aquellos momentos de la vida cotidiana
en los que nos descubrimos, por ejemplo, esperando nuestro turno
detrás de un comprador que está tardando mucho y, en lugar de
lamentarnos por perder el tiempo, dejamos sencillamente a un lado la
reactividad emocional y nos centramos en disfrutar, pongamos por caso,
de la música ambiental.

▪ La reactividad emocional se centra en una modalidad diferente de
atención en la que nuestro mundo se contrae y fija en lo que nos
molesta. Quienes tienen dificultades en mantener una conciencia
abierta suelen quedar atrapados por detalles irritantes, como esa
persona de la cola de la línea de seguridad del aeropuerto que se toma
todo el tiempo del mundo en colocar sus pertenencias metálicas en la
bandeja del escáner y todavía sigue pensando en ello mientras esperan
la llegada de su avión. Pero la conciencia abierta, por su parte, no
se deja secuestrar por la emoción, sino que disfruta, por el
contrario, de la riqueza del momento

▪ Como el músculo sometido a un sobreesfuerzo, la atención
intensamente focalizada también se fatiga, llegando incluso al punto
del agotamiento cognitivo. Los signos de fatiga mental afectan a la
eficacia y aumentan la distracción y la irritabilidad, lo que
significa que el esfuerzo mental necesario para mantener el foco ha
agotado la glucosa que precisa la energía neuronal.

▪ Son muchas las exigencias que impone a nuestra atención pasear por
la calle de una ciudad, dice Kaplan, porque nos obliga a movernos en
medio de la muchedumbre, esquivar coches e ignorar los bocinazos y el
sonido del ruido de fondo.

▪ Un paseo por un parque o por un bosque resulta, por el contrario,
mucho menos exigente. Podemos recuperarnos pasando un tiempo en la
naturaleza, para lo cual basta con un paseo de pocos minutos por un
parque o un lugar rico en maravillas,

▪ En lugar de «vender» su control creativo, mi amigo invirtió las
ganancias de su primer proyecto en el segundo. Y, cuando estaba casi
terminado, se le acabó el dinero. Banco tras banco, le negaron un
préstamo hasta que, al llamar a la puerta del décimo, obtuvo el
crédito que acabó salvando el proyecto. La película en cuestión se
titulaba La guerra de las galaxias.

▪ Las reglas de decisión derivadas de nuestra experiencia vital se
basan en las redes neuronales subcorticales que recopilan, almacenan y
aplican algoritmos a cada uno de los acontecimientos vitales y
establecen el rumbo de nuestro timón interior[82]. En esas regiones
subcorticales, escasamente conectadas con las áreas verbales del
neocórtex, aunque mucho más con las vísceras, guarda el cerebro
nuestras sensaciones más profundas de propósito y significado

▪ Demasiado a menudo «perdemos el control» e incurrimos
inconscientemente en conductas menos que deseables. Y, si nadie nos
advierte de ello, seguimos actuando del mismo modo.

▪ la autoconciencia disminuye cuanto más elevado es el rango que uno
ocupa en la jerarquía de la organización.

▪ ¡Ah, si nos fuera dado el poder de vernos como los demás nos ven! De
cuántos disparates y necedades nos libraríamos.

▪ Una visión más irónica es la ofrecida por W.H. Auden al observar
que, para poder amarnos a nosotros mismos, creamos una imagen mental
positiva descartando selectivamente lo que menos halagador resulta y
acentuando, por el contrario, lo más admirable.

▪ el filósofo George Santayana cerró el círculo diciendo que, poco
importaría lo que los demás pensaran de nosotros… de no ser porque,
una vez lo sabemos, ese conocimiento «tiñe profundamente la visión que
tenemos de nosotros». Los filósofos sociales han denominado «yo que se
mira en el espejo» a este efecto que refleja cómo imaginamos que los
demás nos ven.

▪ los demás actúan como espejos que nos reflejan. Esta idea se ha
visto resumida en la frase: «Soy lo que creo que tú crees que soy».

▪ La revista Surgery presentó un estudio en el que se valoró el tono
de voz de los cirujanos basándose en grabaciones de 10 segundos
registradas durante las entrevistas con sus pacientes[92]. Las voces
de los cirujanos que se habían visto demandados por mala práctica (la
mitad de los participantes en el experimento) fueron evaluadas como
dominantes y descuidadas, cosa que no sucedió con la otra mitad.

▪ Cuando escuchamos la explicación que da el cirujano sobre los
detalles técnicos y posibles riesgos de la intervención, se activa el
radar empleado por el cerebro para detectar los peligros, en busca de
indicios que pongan en peligro la seguridad. Esa intensificación de la
sensibilidad puede ser una de las causas por las cuales el grado de
empatía y preocupación transmitido por la voz del cirujano —o su
ausencia, mejor dicho— constituye un excelente predictor de si, en el
caso de que las cosas vayan mal, acabará siendo denunciado.

▪ el tono de nuestra voz tiene gran importancia en el impacto que
provocamos.

▪ La investigación realizada al respecto ha puesto de relieve que,
cuando las personas reciben, en un tono de voz amable y cordial, un
mindfulness negativo sobre su trabajo, se quedan, a pesar de ello, con
un sentimiento positivo. Y, de manera parecida, las buenas noticias
transmitidas con un tono distante y frío dejan en el paciente un mal
sabor de boca[93

▪ Una empresa dedicada a la gestión de inversiones de personas muy
ricas proporcionó a Daniel Kahneman un auténtico tesoro, que consistió
en los resultados de las inversiones realizadas, durante 8 años, por
25 de sus asesores financieros.

▪ Esa investigación llevó a Kahneman a advertir que no existía
relación alguna entre el éxito obtenido año tras año por un
determinado asesor o, dicho en otras palabras, que ningún asesor
gestionaba mejor que los demás el dinero de sus clientes.

▪ Su conclusión fue que sus resultados no demostraban ser mejores que
los debidos al azar.

▪ Lo curioso era que todo el mundo, a pesar de ello, se comportaba
como si tuviese una habilidad especial y los que mejor desempeñaban
ese papel eran los que obtenían, cada año, dividendos más
sustanciosos.

▪ Cuando la ilusión de habilidad, profundamente inserta en la cultura
del mundo financiero, se pone en cuestión, «datos que desafían
creencias arraigadas y amenazan, por tanto, el sustento y la
autoestima de la gente, se ven sencillamente soslayados».

▪ El autoengaño parece un rasgo fundamental de la atención. Las tres
cuartas partes de los conductores, por ejemplo, piensan que sus
habilidades al volante son «mejores que las del promedio».

▪ Otro antídoto del pensamiento grupal consiste en ampliar nuestro
círculo de contactos más allá de nuestra zona de confort y contar con
información fiel que, vacunándonos contra el aislamiento en el
interior del grupo, nos proteja del autoengaño.

▪ La diversificación inteligente va más allá de equilibrar el género y
el grupo étnico hasta llegar a incluir un amplio elenco de edades,
clientes o consumidores… y a todos aquellos que puedan ofrecernos una
nueva perspectiva.

▪ La autoconciencia cumple con la doble función, en el diseño de la
mente, de regular nuestras emociones y permitirnos sentir lo que otros
puedan estar sintiendo.

▪ Según la epigenética, es decir, la ciencia que explica el modo en
que el entorno impacta en nuestra herencia genética, no basta con
heredar una determinada secuencia genética para que esos genes, en sí
mismos, resulten determinantes. Los genes parecen tener lo que
podríamos considerar una especie de interruptor bioquímico. Por eso,
si nunca se activan, es como si careciésemos de ellos. Y son muchas
las cosas que propician la activación de ese interruptor, como el tipo
de alimentación, la danza de reacciones químicas que se desencadena
dentro de nuestro cuerpo y el aprendizaje.

▪ También hay que señalar el llamado «test de las golosinas», un
estudio ya clásico llevado a cabo, durante la década de los setenta,
por el psicólogo Walter Mischel de la Universidad de Stanford. Durante
esa prueba, Mischel invitaba a pasar, uno tras otro, a niños de cuatro
años a la «sala de juegos» de la Bing Nursery School [Guardería Bing]
del campus de Stanford donde, después de mostrarles una bandeja con
golosinas y dulces, les pedía que eligiesen el que más les gustara.

▪ cada niño, también se le dijo: «Si quieres puedes tener tu golosina
ahora mismo, pero, si no te la comes hasta que vuelva de dar un paseo,
te daré dos».

▪ Ese grado de autocontrol era, en las terribles condiciones, para un
niño de cuatro años, en que el experimento se llevó a cabo (una
habitación vacía de juguetes, libros y pinturas, es decir, sin posible
distracción), una auténtica proeza. El experimento demostró que un
tercio de los niños tomó la golosina de inmediato, mientras que otro
tercio esperó el interminable cuarto de hora hasta recibir la doble
recompensa (y el último tercio se situó en algún punto entre ambas
alternativas). Lo más significativo fue que los niños que resistieron
la tentación de comerse la golosina de inmediato mostraron una
puntuación más elevada en medidas de control ejecutivo, concretamente
de reasignación de la atención.

▪ Los niños que esperaron los 15 minutos lo hicieron apelando a
estrategias de distracción, como los juegos ficticios, cantar o
taparse los ojos. El que miraba la golosina acababa perdiendo (o,
dicho con más precisión, era la golosina la que acababa ganando).

▪ Lo más sorprendente es que el análisis estadístico demostró que el
nivel de autocontrol de un niño demuestra ser un predictor tan
poderoso de su éxito financiero adulto, de su salud y de su historial
delictivo como la clase social, la riqueza de la familia de origen o
el CI.

▪ Solo 2 de cada 5 hijos de padres ubicados en el 20% superior de la
riqueza acaban, en los Estados Unidos, en ese mismo estatus
privilegiado, y cerca del 6% descienden al nivel de ingresos propio
del 20% inferior

▪ Una red de expertos académicos revisa el contenido del programa,
mientras que los auténticos expertos (los preescolares) se encargan de
garantizar que la audiencia entenderá el mensaje. Y cada programa
tiene un enfoque específico, como si de un concepto matemático se
tratara, cuyo impacto educativo se verá corroborado posteriormente por
lo que los preescolares acaben realmente aprendiendo.

▪ «Los maestros de los primeros cursos nos dicen que necesitan que los
niños puedan permanecer sentados, concentrarse, gestionar sus
emociones, escuchar sus indicaciones, colaborar y hacer amigos
—explicó Rosemarie Truglio—. Solo entonces pueden enseñarles las
letras y los números».

▪ «Enseñar estas habilidades de autorregulación —concluyó— puede
requerir, en el caso de los niños, en este sentido,
infradesarrollados, un recableado de diferentes partes del cerebro».

▪ la atención tiene, según la ciencia cognitiva, una capacidad
limitada, razón por la cual la memoria operativa obra como una especie
de cuello de botella. Y, si nuestras preocupaciones interfieren con
esa capacidad, los pensamientos irrelevantes acaban reduciendo el
ancho de banda de atención que queda libre, pongamos por caso, para
las matemáticas.

▪ Como bien sabe el equipo de Barrio Sésamo, los maestros quieren
alumnos con una buena función ejecutiva, lo que significa
autodisciplina, control de la atención y capacidad de resistirse a las
tentaciones. Esas funciones ejecutiva

▪ predicen, además del CI, los buenos resultados obtenidos por el niño
en los campos de las matemáticas y la lectura[110]

▪ Y es evidente que esta ventaja no queda limitada a los niños. La
capacidad de dirigir nuestra atención a una cosa ignorando el resto
yace en el núcleo mismo de la voluntad.

▪ En la India del siglo V, se alentaba a los monjes a contemplar «las
32 partes del cuerpo», una lista de aspectos poco atractivos de la
biología humana, como las heces, la bilis, la flema, el pus, la
sangre, la grasa, las mucosidades, etcétera. Esa atención a los
aspectos desagradables estaba destinada a promover la
desidentificación del cuerpo y a ayudar a los monjes a rechazar los
deseos o, dicho en otras palabras, a fortalecer la voluntad

▪ La investigación realizada en este sentido sugiere que la epidemia
de obesidad que aqueja a los países desarrollados puede deberse
parcialmente a nuestra mayor susceptibilidad, mientras estamos
distraídos, a caer en un funcionamiento automático y tomar alimentos
azucarados y ricos en grasas. Los estudios de imagen cerebral
realizados sobre las personas que más éxito han tenido en perder peso
y mantenerlo demuestran ser los que poseen, cuando se ven enfrentados
a alimentos ricos en calorías, un mayor control cognitivo[

▪ «Los gestos siempre ocurren poco antes de la parte más enfatizada de
lo que uno está diciendo —me confesó Cassell—. Una de las razones por
las que algunos políticos parecen poco sinceros es que, pese a que han
aprendido a realizar determinados gestos, no saben muy bien el momento
en que deben realizarlos. De ahí se deriva, precisamente, la sensación
de falsedad que transmiten cuando, en lugar de

▪ preceder a la palabra, esos gestos la suceden».

▪ Mientras tomábamos un café en una de las pausas de un congreso,
Cassell me explicó que, después de varios centenares de horas de
análisis de los mensajes no verbales, su sensibilidad había mejorado
mucho.

▪ La empatía cognitiva nos permite, teniendo en cuenta la forma de ver
y de pensar de otra persona, entender su perspectiva. Ver a través de
los ojos de alguien nos ayuda a entender las cosas que se pregunta y a
elegir el lenguaje que más se adapte a su tipo de comprensión.

▪ La empatía cognitiva, que nos lleva a aprender de todo el mundo, se
ve alentada por una naturaleza inquisitiva que amplía nuestra
comprensión del mundo de los demás. Esta es una actitud a la que un
ejecutivo exitoso se refiere con las siguientes palabras: «Siempre he
querido saberlo todo, entender todo lo que me rodea, por qué los demás
piensan de tal modo, por qué hacen lo que hacen y qué es lo que les
sirve y lo que no»[121].

▪ «Si queremos entender los sentimientos de los demás, debemos antes
entender los nuestros»,

▪ La sociopatía, según se dice, afecta a cerca del 1% de la población,
en cuyo caso el mundo del trabajo alberga a millones de personas, lo
que los clínicos denominan «sociópatas exitosos» (uno de ellos es
Bernie Madoff, hoy en día en prisión). Los sociópatas son, como sus
primos hermanos, las «personalidades maquiavélicas», capaces de leer
las emociones de los demás, aunque registran las expresiones faciales
en una parte del cerebro distinta a la del resto.

▪ Ellos hablan de emociones, pero, a diferencia de lo que sucede con
los demás, no las sienten directamente o, dicho de otro modo, en lugar
de experimentar las reacciones emocionales normales de abajo arriba,
los sociópatas las «sienten» de arriba abajo

▪ Esto resulta sorprendentemente cierto en el caso del miedo, porque
los sociópatas no parecen experimentar miedo alguno al castigo a causa
de los delitos que han cometido. Quizás adolezcan, como afirma cierta
teoría, de una carencia concreta en el control cognitivo de sus
impulsos, lo que conduce a un déficit de atención que les lleva a
centrarse en las emociones que experimentan y les ciega a las
consecuencias de sus acciones

▪ la empatía emocional se «encarna», porque nos permite sentir, en
nuestro cuerpo, lo que está ocurriendo en el cuerpo de otra persona.

▪ Un aspecto muy interesante es que, mientras que las neuronas espejo
y otros circuitos sociales recrean, en nuestro cerebro y en nuestro
cuerpo, lo que sucede en otra persona, nuestra ínsula resume todo
eso. Por eso sentimos lo que está ocurriendo dentro de otra persona
conectando con nuestra propia ínsula o, dicho en otras palabras,
entendemos lo que sucede en otra persona conectando con nosotros
mismos.

▪ La empatía siempre entraña un acto de autoconciencia.

▪ La parábola bíblica del buen samaritano nos habla de un hombre que
se detuvo para ayudar a un extraño, tendido al borde del camino, al
que habían golpeado y robado. Otras dos personas habían pasado por
allí, pero asustados ante el posible peligro, habían acelerado
simplemente el paso sin brindarle ayuda. Martin Luther King Jr. dijo,
a propósito de esta parábola que, mientras que estos se preguntaron
«¿Qué me pasará si me detengo y ayudo a este hombre?», la pregunta que
el buen samaritano se hizo fue,

▪ por el contrario, «¿Qué le sucederá a él, si no le ayudó?».

▪ La compasión se erige sobre la empatía que, a su vez, requiere
prestar atención a los demás. Si estamos absortos en nosotros, no nos
daremos cuenta de los demás y seguiremos nuestro camino, indiferentes
a su sufrimiento. Cuando, sin embargo, nos damos cuenta de su
presencia, podemos conectar con ellos, sentir sus sentimientos y
necesidades y mostrar nuestra preocupación empática.

▪ La preocupación empática emerge muy temprano en la infancia. Cuando
un bebé llora, otro empieza también a llorar

▪ La excesiva activación de los sentimientos de simpatía puede llegar
a provocar, en los profesionales de la asistencia, una fatiga de la
compasión

▪ Y quienes, por su parte, se protegen demasiado de la ansiedad
generada por la simpatía, amortiguando sus sentimientos, pueden acabar
perdiendo el contacto con la empatía.

▪ Hay quienes afirman que uno de los costes de la frenética búsqueda
de distracciones a la que hoy en día nos enfrentamos consiste en la
erosión de la empatía y la compasión[137]. Cuanto más distraídos
estamos, menor es nuestra capacidad para cultivar formas sutiles de
empatía y compasión.

▪ La contemplación del dolor ajeno moviliza de manera refleja nuestra
atención, porque la expresión del dolor es una señal biológica que
cumple con la función esencial de pedir ayuda. Hasta los monos rhesus
son incapaces de tirar de una cadena para obtener una banana si ello
va acompañado de una descarga eléctrica sobre otro mono, lo que quizás
indique un rudimento de compasión.

▪ Por una parte, la empatía al dolor concluye cuando no nos gusta la
persona que está experimentando dolor, como cuando forma parte, por
ejemplo, de un grupo que nos desagrada[138], en cuyo caso puede
convertirse fácilmente en su opuesto, la llamada Schadenfreude [que
literalmente significa «regodearse con el sufrimiento ajeno».][1

▪ Otra excepción es también la escasez de recursos. Y es que la
necesidad de competir por los recursos, cuando estos son
insuficientes, puede llegar, en ocasiones, a sofocar la preocupación
empática, pues la competición (ya sea por alimento, pareja, poder… o
por una cita con el médico) forma parte, en casi todos los grupos
sociales, de la vida.

▪ «Permítame ver si he entendido bien…»], una frase constructora de
empatía que es toda una declaración de principios, esboza la hipótesis
de que el establecimiento de la conexión emocional requiere tomarse el
tiempo necesario para prestar atención al modo en que el paciente se
siente con su enfermedad.

▪ Los médicos más demandados por mala praxis en los Estados Unidos no
son, curiosamente, los que más errores cometen. La investigación
realizada ha puesto de relieve que la motivación principal gira, por
el contrario, en torno a una serie de variables ligadas al tipo de
relación que el médico establece con su paciente. Los más demandados
muestran menos indicios de compenetración emocional, llevan a cabo
visitas más cortas, no se interesan por las preocupaciones de sus
pacientes, ni se aseguran de que sus preguntas se vean respondidas, y
mantienen una mayor distancia emocional, con pocas o ninguna sonrisa,
por ejemplo

▪ Pero esta reacción de atenuación de la empatía emocional puede
llegar, en los casos más extremos, a bloquear completamente la
empatía. El reto al que, durante su práctica cotidiana, se enfrenta el
médico consiste en mantener la atención fría sin dejar, por ello, de
permanecer abierto a los sentimientos y experiencias del paciente y
hacerle saber que lo entiende y lo cuida.

▪ La atención médica fracasa cuando el paciente no sigue las
indicaciones de su médico y no toma los medicamentos prescritos, cosa
que sucede cerca del 50% de las veces

▪ Y el predictor más claro en este sentido es la preocupación sincera
mostrada por el médico

▪ Independientemente de que se trate de un intercambio rutinario de
saludos o de una tensa negociación, todas nuestras interacciones van
acompañadas de una continua corriente de información no verbal que
discurre en ambas direcciones. Y los mensajes transmitidos por esa
información son tanto o más importantes incluso que lo que podamos
estar diciendo

▪ Las patas de gallo en torno a los ojos, por ejemplo, son claros
indicadores de que la persona en cuestión se siente sinceramente
feliz, mientras que su ausencia, por el contrario, es indicio de que
la sonrisa es fingida. Son muchas las cosas que los niños aprenden
sobre las emociones mirando a los ojos de las personas, un aprendizaje
inaccesible a los autistas, que evitan mirar a los ojos.

▪ escuchando al director general de una empresa de refrescos de ámbito
mundial —conocida por haber reducido los sueldos de sus trabajadores—
alabar el modo en que su compañía contribuía a la salud de los niños

▪ Durante el tiempo dedicado a las preguntas que siguió a la charla,
Blair formuló una pregunta deliberadamente provocadora: «¿Cómo puede
hablar de niños sanos sin pagar salarios sanos a sus padres?». Cuando
el director general, ignorando la pregunta, pasó a la siguiente, Blair
experimentó súbitamente en sus propias carnes lo que era ser un paria.

▪ La capacidad de los poderosos de ningunear a las personas (y las
verdades) incómodas y de no prestarles atención ha acabado
convirtiéndose en un tema de interés de los psicólogos sociales, que
están estudiando las relaciones entre el poder y la gente a la que
prestamos más y menos atención

▪ Los individuos con un estatus más elevado tienden a centrar menos la
mirada en la persona con la que se relacionan, con el consiguiente
aumento de la probabilidad de que interrumpan y monopolicen la
conversación, signos evidentes de desatención.

▪ Las personas pertenecientes a un estatus social inferior, por su
parte, se desenvuelven mejor en pruebas de exactitud empática, como
leer, por ejemplo, las emociones de otra persona en su rostro o hasta
en los músculos que rodean sus ojos.

▪ la atención que prestamos a los demás parece depender del lugar que
creemos ocupar en la escala social, siendo mayor la vigilancia cuanto
más subordinados nos creemos y menor, por el contrario, cuando nos
sentimos superiores. El corolario de todo ello es que, cuanto más nos
importa algo, más atención le prestamos y más, en consecuencia, lo
cuidamos. Y esta conclusión muestra la profunda relación que existe
entre la atención y el amor.

▪ Aunque los sistemas resulten, a simple vista, casi invisibles, su
funcionamiento puede comprobarse acopiando los datos suficientes para
poner de manifiesto su dinámica. Cuantos más datos tengamos, más claro
resultará el mapa. Estamos adentrándonos en la época de los grandes
archivos de datos.

▪ Esa aplicación identificaba a los «líderes tribales», es decir, los
individuos que establecen el mayor número de conexiones con un pequeño
grupo de afines. La compañía descubrió que es muy probable que, si el
líder adopta un nuevo servicio telefónico, también lo hagan los
miembros de su tribu. Y, si el líder cambia de servidor, el resto de
la tribu también suele seguirle

▪ En teoría, la persona que cuida la información se centra en lo que
importa y se olvida del resto estableciendo, de ese modo, el contexto
para entender el significado del dato y hacerlo de un modo que muestre
por qué es vital

▪ Los mejores líderes no se limitan a poner los datos en un contexto
significativo, sino que también formulan las preguntas adecuadas.

▪ alienta a quienes gestionan proyectos de grandes bases de datos a
formular este tipo de preguntas: «¿Estamos definiendo bien el
problema? ¿Contamos con los datos adecuados? ¿Cuáles son las creencias
que hay detrás del algoritmo que nos proporciona los datos? ¿Establece
ese modelo algún mapa de creencias sobre la realidad?»[1

▪ «Cuando íbamos al bosque a buscar plantas medicinales o flores para
hacer guirnaldas, mis mayores me enseñaron a recoger solo unas pocas
flores u hojas de cada rama de modo que no quedase, en el bosque,
huella alguna de nuestro paso. Pero los muchachos de hoy en día no
tienen empacho alguno en romper ramas y dejarlo todo lleno de bolsas
de basura».

▪ «Buscamos problemas sistémicos —me dijo Ellison— que ninguna
persona, gobierno ni empresa aislada es capaz de resolver». El primer
gran paso adelante en la resolución del problema de las revistas fue
simplemente el de reunir a todos los participantes y empezar, de ese
modo, a tener en cuenta los sistemas mayores[

▪ «La ceguera sistémica es el mayor de los problemas al que, en
nuestro trabajo, nos enfrentamos»

▪ «Ese tipo de abordajes es engañoso —afirma Sterman—. Es cierto que,
considerado a corto plazo, se obtiene una solución… pero, a medio
plazo, el problema reaparece, a menudo multiplicado».

▪ »La gente suele atribuir lo que le sucede —prosigue Sterman— a
acontecimientos cercanos en el espacio y el tiempo, cuando, en
realidad, se trata del simple fruto de la dinámica del sistema mayor
en que se hallan inmersos».

▪ Creemos que estamos parados porque se ha producido un atasco, sin
darnos cuenta de que ese atasco es una consecuencia de la dinámica
sistémica de las redes viarias. La desconexión entre tales sistemas y
el modo en que nos relaciona

▪ mos con ellos se deriva de una distorsión de nuestros modelos
mentales. Culpamos a los demás conductores de entorpecer el tráfico
sin darnos cuenta de la dinámica sistémica que nos ha llevado hasta
allí.

▪ Estamos muy conectados con el crujido de una rama, que puede
advertirnos de la proximidad de un tigre, pero carecemos de aparato
perceptual que nos permita detectar el adelgazamiento de la capa de
ozono atmosférica o los agentes cancerígenos contenidos en las
partículas que respiramos en un entorno urbano contaminado.

▪ aunque estas amenazas pueden acabar siendo tan letales como aquella,
nuestro cerebro carece de radar que nos permita identificarlas
directamente.

▪ No recibimos, cuando estamos comiéndonos un postre muy apetitoso,
señal alguna que nos diga: “Si sigues así, morirás dentro de tres
años”. Y tampoco hay nada que nos indique, cuando nos decidimos a
comprar un segundo coche: “Esta es una decisión de la que te
arrepentirás cuando seas un anciano desvalido”».

▪ Resulta mucho mejor centrarse, en medio de un aluvión de datos, en
un pequeño número de pautas significativas, ignorando simultáneamente
el resto. Nuestro neocórtex incluye un detector de pautas destinado a
simplificar la complejidad ateniéndonos a reglas de decisión
manejables

▪ La «regla de las 10 000 horas» [equivalente a 3 horas de
entrenamiento diario durante 10 años]

▪ Ericsson afirma que el secreto de la victoria radica en la «práctica
deliberada», en la que un entrenador experimentado (precisamente lo
que Susan Butcher, una veterinaria experta, era para sus perros) nos
dirige, durante meses o años, a través de un entrenamiento

▪ bien diseñado al que nos entregamos plenamente

▪ La cosa no se limita, pues, a las horas de ejercicio, sino que
también son importantes el feedback y la concentración.

▪ Mejorar una habilidad requiere de la participación de un foco
descendente. La neuroplasticidad, el fortalecimiento de los circuitos
cerebrales más antiguos y el establecimiento de nuevas conexiones para
ejercitar la habilidad que estemos practicando, requiere
atención. Cuando, por el contrario, la práctica discurre mientras nos
ocupamos de otra cosa, nuestro cerebro no reconstruye los circuitos
relevantes para esa rutina concreta.

▪ La ensoñación cotidiana arruina la práctica

▪ La atención plena parece alentar la velocidad de procesamiento
mental, fortalecer las conexiones sinápticas y establecer o expandir
redes neuronales ligadas a lo que estamos ejercitando

▪ Al cabo de unas 50 horas aproximadas de entrenamiento (ya sea
esquiando o conduciendo, por ejemplo), las personas logran un nivel de
rendimiento «relativamente aceptable», que les permite realizar los
movimientos casi sin esfuerzo. Ya no tienen necesidad entonces de
concentrarse en el ejercicio, sino que se limitan a dejarse
llevar. Independientemente, sin embargo, del tiempo que dediquen a la
práctica de esta modalidad ascendente, su mejora será imperceptible

▪ Los expertos, por su parte, nunca dejan de prestar una atención
descendente, contrarrestando deliberadamente, de ese modo, la
tendencia del cerebro a automatizar rutinas. Se concentran activamente
en los movimientos que todavía deben perfeccionar, corrigiendo lo que
no funciona y ajustando, en consecuencia, sus modelos mentales.

▪ «El experto —afirma Ericsson— contrarresta activamente la tendencia
a la automaticidad elaborando y seleccionando de forma deliberada un
entrenamiento cuyo objetivo exceda su nivel actual de
desempeño. Cuanto más tiempo dediquen los expertos —añade— a la
práctica deliberada con plena concentración, más desarrollada y
perfecta será su ejecución[190]»

▪ constató que los competidores de talla mundial —independientemente
de que se trate de levantadores de pesas, pianistas o perros de un
equipo de trineo— suelen limitar la práctica más exigente a unas 4
horas diarias. Y es que, para ellos, el descanso y la recuperación
física y mental forman parte integral de su régimen de entrenamiento.

▪ «Cada experto ha adquirido, de algún modo, esta capacidad de
memoria» dentro de su especialidad. «La memoria es como un índice y
los expertos son aquellos capaces de gestionar unos 50 000 fragmentos
de unidades de información que, en el caso de los médicos, por
ejemplo, suelen ser síntomas[192]

▪ Pensemos en la atención como un músculo mental que se fortalece a
medida que se ejercita.

▪ Los ejercicios de memorización desarrollan ese músculo y también lo
hace la concentración.

▪ Advertir el momento en que nuestra mente empieza a divagar y
llevarla una y otra vez hacia nuestro objetivo constituye el
equivalente mental al levantamiento repetido de pesas.

▪ Como sucede con cualquier otro entrenamiento, el fortalecimiento del
músculo de la atención depende de su ejercicio.

▪ Una regla general de la terapia cognitiva afirma que la mejor receta
para la depresión consiste en centrar la atención en los aspectos
negativos de la experiencia.

▪ Las emociones positivas abren el foco de nuestra atención,
permitiéndonos captarlo todo.

▪ la positividad reporta, a su vez, grandes beneficios desde el punto
de vista del rendimiento, proporcionándonos la energía necesaria para
poder centrarnos, pensar con más flexibilidad, perseverar y conectar
mejor con las personas que nos rodean.

▪ Formulémonos ahora la siguiente pregunta: «¿Qué estaremos haciendo,
si todo va bien, dentro de 10 años?».

▪ Esa pregunta nos invita a soñar un poco, a ver las cosas que
realmente nos importan y cómo eso podría dirigir nuestra vida.

▪ Centrarnos en nuestras fortalezas —argumenta Boyatzis— nos alienta a
avanzar en pos del futuro anhelado, al tiempo que moviliza la apertura
a nuevas ideas, personas y planes, mientras que hacerlo, por el
contrario, en nuestras debilidades, moviliza un sentimiento defensivo
de obligación y culpa, que acaba encerrándonos en nosotros mismos.

▪ Una conversación que parta de los sueños y expectativas de la
persona puede conducir a un «camino» de aprendizaje que desemboque en
esa visión. Esa conversación podría resumir algunos objetivos
concretos de la visión general y considerar luego las implicaciones
del logro de dichas metas y las capacidades que, para alcanzarlas,
necesitamos desarrollar.

▪ Independientemente de que se trate de desarrollar una habilidad
deportiva o musical, de fortalecer nuestra memoria o de escuchar a los
demás, las claves de la práctica inteligente son siempre las mismas,
una combinación agradable, en términos ideales, de alegría, estrategia
inteligente y concentración.

▪ El cerebro es plástico y continuamente va remodelando, a lo largo de
nuestra vida, sus circuitos. Con independencia de lo que hagamos,
nuestro cerebro siempre está fortaleciendo, cuando hacemos algo, unos
circuitos en detrimento de otros.

▪ «La mayor parte de nuestra socialización se produce a través de
aparatos —

▪ Un seguimiento de dos años, efectuado sobre 3034 niños y
adolescentes de Singapur, puso de relieve que los que acabaron
convirtiéndose en grandes jugadores mostraron un aumento de la
ansiedad, la depresión y la fobia social, así como un descenso también
de su rendimiento escolar.

▪ Pero todos esos proble

▪ mas se desvanecieron apenas detuvieron su hábito de juego[2

▪ El cerebro aprende y recuerda mejor cuanto más intensa es la
concentración

▪ En el mejor de los casos, los «videojuegos son regímenes de
entrenamiento controlado, administrados de forma muy motivadora, que
acaban provocando un remodelado estructural y funcional permanente del
cerebro»,

▪ «Ese tipo de juegos —me dice— podrían desacelerar la pérdida de
funciones cognitivas que acompañan al envejecimiento».

▪ identificar claramente los objetivos de niveles cada vez más
difíciles; adaptarse al ritmo concreto de cada alumno; feedback
inmediato y retos prácticos graduales que permitan el logro de la
maestría, y ejercitar la misma habilidad en contextos diferentes para
favorecer, de ese modo, su transferencia.

▪ En una época en que los mensajes instantáneos y las compras en línea
alientan la gratificación inmediata, los niños necesitan más ayuda con
ese hábito.

▪ porque otra de las conclusiones alcanzadas por los economistas
implicados en el estudio de Dunedin es la de que enseñar a todos los
niños este tipo de habilidades podría elevar unos cuantos puntos la
renta per cápita del país, reducir la tasa de delincuencia y mejorar
la salud.

▪ e pedí a Richard Davidson, de Wisconsin, decano de la neurociencia
contemplativa, que resumiera y ordenase claramente las ventajas que,
para la atención, tiene la práctica de mindfulness,

▪ «Mindfulness —me dijo Davidson— estimula la red clásica de la
atención, situada en la región frontoparietal del cerebro, que cumple
con la función de dirigir la atención. Estos circuitos resultan
esenciales para el movimiento básico de la atención, que consiste en
desconectar nuestra atención de una cosa, dirigirla hacia otra y
mantenerla en ese nuevo objeto».

▪ La otra clave tiene que ver con una mejora de la atención selectiva
debida a la inhibición del poder de las distracciones, que nos permite
dejar a un lado las distracciones que se producen a nuestro alrededor
y centrarnos en lo que nos importa

▪ Uno de los principales beneficios para los estudiantes radica en la
comprensión. Las mentes errantes dan palos al aire por lo que respecta
a la comprensión. El antídoto para la divagación mental es la
metaconciencia, es decir, la atención a la atención misma, la
capacidad de darnos cuenta de que no estamos dándonos cuenta de lo que
deberíamos y corregir, en consecuencia, nuestro foco.

▪ la práctica de mindfulness va acompañada de una reducción de los
síntomas ligados a un amplio rango de trastornos fisiológicos, desde
los temblores hasta la hipertensión y el dolor crónico.

▪ «Parte de los principales efectos del mindfulness son biológicos —me
explica Davidson— lo que, tratándose de un ejercicio de la atención,
no deja de resultar sorprendente».

▪ el hecho de prestar atención a nuestro estado interior nos permite
ver también lo que necesitamos cambiar en nuestra vida.

▪ Casi cualquier forma de meditación reeduca, en esencia, nuestros
hábitos de la atención y, muy en especial, la caída rutinaria en la
distracción

▪ Si queremos centrar la atención en nuestra experiencia aquí y ahora
(en la tarea que estamos llevando a cabo, la conversación que estamos
manteniendo o la búsqueda de consenso en una reunión), debemos atenuar
el ruido mental, ligado al yo y pensamientos asociados, que genera un
mosaico mental de cuestiones irrelevantes para la tarea que, en el
presente, estemos llevando a cabo[236

▪ El entrenamiento en mindfulness reduce la actividad de los llamados
circuitos del yo, ubicados en la corteza prefrontal medial, de modo
que, cuanto menos diálogo interno, mejor podremos experimentar el
presente

▪ El fortalecimiento del control ejecutivo resulta especialmente
importante para las personas a las que el menor contratiempo, daño o
decepción las sumerge en una cavilación interminable

▪ Al cambiar la relación que mantenemos con el pensamiento, el
mindfulness nos permite romper la cadena de pensamientos que, de otro
modo, acabaría revolcándonos en el sufrimiento

▪ En lugar, pues, de vernos arrastrados por su corriente, podemos
entonces hacer una pausa y, dándonos cuenta de que son meros
pensamientos, decidir actuar o no a partir de ellos.

▪ basta con 20 minutos de práctica diaria durante 4 días para empezar
a disfrutar de todos esos beneficios (aunque, cuanto más
entrenamiento, más duraderos serán, obviamente, sus efectos

▪ recuperar la plena concentración requiere entre 10 y 15 minutos.

▪ «La mayoría de líderes no llevan a cabo pausa alguna —me confesó un
curtido coach del liderazgo—, pero lo cierto es que uno necesita
tiempo para reflexionar».

▪ Limitarse, en su opinión, a ayudar a los pobres a sobrevivir no hace
sino acentuar la pobreza intergeneracional

▪ Lo que necesitamos es impulsar, durante una generación, en los
ámbitos educativo y sanitario, a los niños más pobres, para que puedan
enfrentarse a la vida desde un nivel de capacidades más elevado y no
se vean así condenados, como sus familias, a sobrevivir a base de
subsidios.

▪ Una estrategia concreta se basa en decisiones que contribuyen a
discernir qué hay que ignorar y a qué hay que prestar atención (¿la
cuota de mercado o los beneficios?, ¿los competidores actuales o los
nuevos?, ¿qué nuevas tecnologías, en concreto?).

▪ como dijo, en cierta ocasión Arthur Schopenhauer, «el genio es el
que acierta en una diana invisible para otros»

▪ Jobs se dio cuenta de que «tan importante es decidir qué no hacer
como decidir qué hacer»[248].

▪ La estrategia se centra en el modo de emplear los propios recursos,
mientras que la táctica se ocupa del modo de luchar en la batalla

▪ Algunas personas (y algunas empresas, como RIM) tienen éxito al
aplicar una estrategia de explotación, que consiste en perfeccionar y
aprender a mejorar una determinada capacidad, tecnología o modelo
empresarial. Otras, sin embargo, encuentran su camino hacia el éxito a
través de la exploración, probando alternativas innovadoras a las que
actualmente emplean.

▪ La exploración nos aleja del foco actual para abrirnos a nuevos
horizontes y posibilitar la flexibilidad, el descubrimiento y la
innovación. La explotación, por su parte, requiere la concentración en
lo que estamos haciendo para perfeccionar, de ese modo, su eficacia y
mejorar el rendimiento.

▪ Quienes mejores decisiones toman son, en este sentido, ambidiestros
y saben perfectamente cuándo deben pasar de una modalidad a
otra. Pueden dirigir organizaciones alternando ambas estrategias,
alentando el crecimiento mediante la innovación y la contención de
costes, dos operaciones muy distintas.

▪ ¿Qué es lo que impide que las personas lleven a cabo este pequeño
esfuerzo neuronal? Hay que empezar diciendo, en primer lugar, que la
sobrecarga mental, el estrés y la falta de sueño (por no mencionar el
alcohol) afectan a los circuitos ejecutivos necesarios para ejecutar
ese cambio cognitivo, circunscribiéndonos a los límites establecidos
por nuestros hábitos mentales. Y a ello hay que agregar, en segundo
lugar, el estrés de la sobrecarga, la falta de sueño y la dependencia
de tranquilizantes, lamentablemente demasiado frecuente entre quienes
desempeñan tareas muy exigentes.

▪ Cuando solo tenía 11 años, Steve Tuttleman empezó a leer con su
abuelo el Wall Street Journal, un hábito que, cuatro décadas después,
ha crecido hasta llevarle a consultar diariamente, en su tablet, cerca
de 20 páginas web, así como multitud de datos y opiniones
proporcionadas por un lector RSS.

▪ «Se trata, sin la menor duda, de un volumen de lectura impresionante
—me dice Tuttleman—. A veces creo que me consume demasiado tiempo,
pero lo cierto es que siempre estoy estableciendo conexiones y lo que
leo me proporciona una base segura para las decisiones que tomo».

▪ Los emprendedores más exitosos recopilan, a la hora de adoptar una
decisión clave, muchos más datos, procedentes de una serie mucho más
amplia de fuentes de lo que la mayoría de la gente juzgaría pertinente

▪ No pasan por alto, por ejemplo, a la hora de tomar una decisión
importante, los datos proporcionados por las sensaciones viscerales.

▪ Una revisión académica de las intuiciones viscerales concluye que el
uso de la información que nos brindan las sensaciones no es, como
podrían argumentar las personas hiperracionales, una fuente constante
de errores, sino una «estrategia de valoración habitualmente acertada»

▪ Si quieres, pues, sacar lo mejor de las personas, tienes que
escucharlas para que tengan la impresión de haber sido realmente
escuchados.

▪ Me hallaba en Carolina del Norte trabajando con un equipo y el
recurso que utilizamos entonces para ayudarles a plantear cuestiones
emocionalmente muy cargadas fue un gran elefante de cerámica —me dijo
Druskat—. Todos accedieron a cumplir una norma que decía que
cualquiera, en cualquier momento, podía coger el elefante y decir
“quiero levantar el elefante”, para sacar a relucir algo que le
molestaba. »Súbitamente uno de los presentes —y hay que decir que
todos ellos eran altos ejecutivos— levantó el elefante. Empezó
entonces a hablar sobre lo ocupado que estaba y de cómo nadie parecía
darse cuenta de su situación y de que sus de

▪ mandas le robaban demasiado tiempo. Cuando les dijo: “Debéis
entender que estoy saturado de trabajo”, sus colegas le respondieron
que no tenían la menor idea y que habían estado preguntándose por qué
se mostraba tan insensible. Algunos habían interpretado su actitud
reticente como algo personal y otros abrieron su corazón tratando de
aclarar las cosas. Al cabo de una hora, parecía tratarse de un equipo
completamente diferente».

▪ Y la mayoría de nosotros, como los políticos y las personas que se
dedican a los negocios, también nos inclinamos por el éxito a corto
plazo. Los psicólogos cognitivos han constatado que las personas
tendemos a favorecer el momento presente en las decisiones de todo
tipo, como: «Me comeré el pastel de crema ahora y luego ya me pondré a
dieta».

▪ Todos, de un modo u otro, somos líderes, ya sea en nuestra familia,
en los medios de comunicación, en una organización o en la sociedad en
su conjunto.

▪ Si nuestro foco de atención solo sirve a nuestras metas personales
(es decir, a nuestro interés personal o a la recompensa inmediata de
nuestro pequeño grupo), estaremos condenando, a largo plazo, a toda
nuestra especie.

▪ En el extremo mayor de su apertura, nuestro foco de atención abarca
también los sistemas globales, tiene en cuenta las necesidades de los
más pobres y desfavorecidos y atisba un futuro muy lejano.
