#+title:      El instituto Tavistock
#+date:       [2022-11-19 Sat 16:39]
#+filetags:   :resaltados:
#+identifier: 20221119T163941

"El siniestro movimiento ecologista, con su visión inhumana del
hombre, afirma de modo explícito este mismo hecho en su despreciable
propaganda. “Salvemos a los animalitos. Matemos a las personas”.   " -
cf Noah que deja la sensación de que la humanidad debe morir

"Tener a la mayoría en un estado continuo de ansiedad interior
funciona, porque se obliga a las personas a que estén demasiado
ocupadas en asegurarse su propia supervivencia o a competir por ella
para colaborar en la construcción de una reacción eficaz"

"Una vez que se ha inducido dicho entorno, un terapeuta puede
manipular a un miembro del grupo, no mediante un ataque directo, sino
por medio de una sutil manipulación de los demás miembros del grupo;
por ejemplo, empleando la sugestión. Si la victima ha sido llevada a
creer que el grupo es algo que la ayuda (maternal), cuando dicho
entorno haya sido manipulado y se vuelva contra ella, tendera a
ejercer el mismo impacto que el profundo rechazo de una madre.»

"

"De hecho, es posible que sea más cómodo y quizá mas barato mantener
al creciente número de “usuarios crónicos de drogas” (sobre todo de
las alucinógenas) bastante aislados y también fuera del mercado de
trabajo, con los millones de para- dos. Para la sociedad, los
habitantes de las comunas y las drogas alucinógenas probablemente
resulten menos molestos —y menos caros— apartados, que dejar que
expresen su alienación a través de protestas y disensiones políticas
activas, organizadas y enérgicas.»"

"El mundo ha sido siempre así, por supuesto. Siempre ha estado
dirigido por personas: supersticiosas, religiosas, temerosas,
paranoicas, inquietantes, odiosas, asesinas"

"LA gran mayoría de la pob1ación mundial escucha música, pero solo una
minoría muy pequeña entiende de verdad lo que quiere decir la letra en
realidad y el efecto que tiene en quien la escucha"

"Muchas de ellas contienen referencias al satanismo o a lo oculto y a
otras temáticas espirituales en forma de letras, simbolismos y demás
referencias que por lo general se ignoran"

"¿Por qué razón iban todos estos raperos, supuestamente incultos,
estos cantantes de música country y rockeros a nombrar en sus
canciones a los Illuminati, el Nuevo Orden Mundial, Rain Man y
Umbrella"

"Algo murió en el pueblo estadounidense aquel 22 de noviembre de 1963,
llámese idealismo, inocencia o búsqueda de la excelencia moral. El
auténtico motivo y la razón del asesinato de Kennedy fue la
transformación de los seres humanos.  "

"Un programa de propaganda, de traumatización colectiva, de culto a
los famosos y al asesinato..., reconstituyendo nuestros arquetipos
culturales en forma de huellas maleables, un viaje esotérico que nos
lleve más allá de esta indolente contemplación de sombras chinescas,
mientras aguardamos nerviosos el siguiente sobresalto"

"Existe un memorándum interno del FBI, que data de 1968, donde se
menciona que se empleó a Grateful Dead “para canalizar la protesta y
la rebeldía de la juventud hacia direcciones más benignas e
inofensivas”. Prestaron un servicio de importancia vital desviando a
muchos jóvenes hacia las drogas y el misticismo, en vez de hacia la
política"

"FUE lord Russell quien propuso que se drogase masivamente a la
población como método de control social, mediante la despenalización
de la marihuana y otras peligrosas drogas psicotrópicas y la
modificación del uso del idioma a fin de obtener métodos para la
manipulación social (y lingüística) de las masas. "

"Recuérdese que el objetivo de Wells, Russell, Huxley y compañía es la
destrucción del poder soberano del estado-nación y acabar con una
tradición filosófica, cultural y religiosa que tiene más de 2.500 años
de antigüedad.   "

"El objetivo inmediato era evitar que los partidos socialistas ya
establecidos captasen la agitación social que había surgido a partir
de 1958 y que se había hecho visible alrededor de la revolución cubana
y del movimiento por los derechos civiles hasta mediados de 1961"

"Según el perfil que hace Tavistock de los terroristas, “la persona es
capaz de realizar funciones que atañen a sí misma y a su entorno
inmediato. Es capaz de funcionar. Donde se revela más claramente la
psicosis es en su incapacidad para hacer frente con cordura a las
abstracciones que conciernen al mundo en general. En otras palabras:
«como mejor vive la persona es dentro de un mundo muy pequeño, un
mundo definido por un tramo muy corto de distancia social alrededor de
ella”"

"Pero si dicha persona aceptó en una ocasión que las personas «malas»
debían morir «para que no pudieran hacer daño a las personas buenas»,
y si además alguien se dedica a matar a las personas «malas», basta
—para abreviar la explicación— con poner una cara, un nombre y demás
en el lugar del símbolo «malo» y decirle que «debemos matar a esa mala
persona», y tenemos lo esencial"

"El elemento crucial para ayudar a que entren en acción esos zombis
terroristas son determinadas «frases en clave». Por ejemplo, la “frase
en clave” utilizada cuando la Baader—Meinhof organizo en 1977 el
asesinato de Jürgen Ponto, presidente del Dresden Bank, fue el
apelativo de «comunista nazi».   "

"LA guerra cultural no declarada contra la juventud estadounidense
comenzó en serio en 1967, cuando Tavistock empezó a servirse de los
conciertos de rock al aire libre para atraer a más de cuatro millones
de jóvenes a los denominados “Festivales”.

"

"Al poco tiempo, más de cincuenta millones de asistentes, que entonces
tenían entre diez y veinticinco años, al regresar a su casa se
convirtieron en mensajeros y promotores de la nueva cultura de las
drogas, o lo que se llamó el movimiento “New Age”.

"

"Lo que llevaban no era solamente “flores en el pelo”, sino también un
cerebro hecho papilla y una dependencia total de los narcóticos, una
esperanza de vida más corta, un estilo de vida degradado que tendía a
hundirse cada vez más en el lodo"

"el hombre, cuando forma parte de una muchedumbre, regresa a un estado
mental primitivo. “Entre la muchedumbre, las personas desinhiben y
olvidan las normas morales, y se vuelven sumamente emocionales"

"Las masas nunca han tenido sed de la verdad”, escribió Freud,
refiriéndose a las masas de mente primaria que se mueven en función de
las necesidades elementales. «Exigen ilusiones y no saben prescindir
de ellas. Constantemente dan prioridad a lo irreal sobre lo real;
están influidas por lo falso casi con la misma intensidad que por lo
verdadero. Tienen una evidente tendencia a no distinguir entre ambas
cosas"

"«Sugerimos que la televisión evoca la premisa básica de la
dependencia. Y debe de evocarla porque es esencialmente una actividad
emocional e irracional. [...] La televisión es el líder constante que
proporciona alimento y protección"

"«La televisión tenía un efecto disociativo sobre las capacidades
mentales y hacia que la gente fuera menos capaz de pensar de forma
racional. Los espectadores, conforme van habituándose a ver seis horas
o más de televisión al día, ceden el poder de razonar a las imágenes y
los sonidos que salen del televisor.»"

"las personas terminarían disociándose, pues intentarían huir del
terror causado por una realidad tan apabullante; se encerrarían en un
estado de negación y se refugiarían en diversiones y entretenimientos
populares, y mostrarían cierta tendencia a sufrir accesos de cólera”.
 "

"lo largo de estos últimos cincuenta años, las investigaciones
llevadas a cabo en los campos de la psicología, la sociología y la
psiquiatría han demostrado que existen límites claramente marcados
para el número de cambios que puede soportar la mente y para la índole
de los mismos"

"Es más, los adultos disociados no son capaces de ejercer una
autoridad moral sobre sus hijos, ya que están demasiado ensimismados
en sus propias fantasías infantiles, provocadas por la televisión"

"Empiezan a rechazar la realidad, a negar la existencia de la misma y
a construir fantasías cada vez más infantiles que les permitan seguir
adelante. En caso de «turbulencia social» cada vez más intensa, la
gente cambia de valores y se rinde ante otros nuevos y degradados;
valores menos humanos y más animales"

"todos los grupos étnicos, raciales y sexuales luchan unos contra
otros. Las naciones se desintegran en grupos regionales, y a su vez
esas áreas más pequeñas se dividen en otras menores, según la etnia»"

"tercera situación posible es la más tensa, pues supone un retroceso y
replegarse hacia «el mundo privado y apartarse de los vínculos
sociales que podrían implicar verse envuelto en los asuntos de los
demás»"

"Para sobrevivir en semejante estado, la gente necesitará crear una
re1igión nueva. Wolfe afirma que «las antiguas formas religiosas,
sobre todo el cristianismo occidental, exigen al hombre que se
responsabilice de su prójimo. Las nuevas formas religiosas serán una
modalidad de anarquismo místico, una experiencia religiosa muy similar
a las practicas satánicas de los nazis o a las ideas de Carl
Jung». Esta"

"La mayoría de los estadounidenses y de los europeos se informa de lo
que ocurre en el mundo a través de la televisión controlada por el
Estado, con la idea errónea de que los reporteros tienen la misión de
servir al público"

"Teniendo en cuenta la manera en que se dan las noticias, ¿usted
consigue alguna vez reflexionar detenidamente acerca de alguna de
ellas"

"Lonnie Wolfe, en su trabajo de investigación emitido por televisión,
explica que este tipo de lavado de cerebro se llama “retención
selectiva”. La televisión hace que la gente deje de ser crítica porque
la combinación de imágenes y de sonidos la sitúa en un estado como de
ensoñación, que limita su capacidad cognitiva.›"

"La televisión, con la abrumadora presencia que tiene en nuestra vida,
crea la opinión pública y al mismo tiempo la valida. ¿Cómo se hace
eso, exactamente? Se debe a que nuestra identidad, gracias a la
televisión, se modela según lo que piensan los demás: «un deseo
constante e infinito de actuar como creemos que quieren que actuemos
los demás»"

"«Creer que la opinión pública puede ser un factor determinante de la
verdad es filosóficamente una locura. Excluye la idea de la mente
racional del individuo. Toda mente contiene la chispa divina de la
razón, y por lo tanto es capaz de hacer descubrimientos científicos y
de entender los descubrimientos de otros. Por consiguiente, la mente
de cada individuo es una de las pocas cosas que no pueden
“promediarse"

"«Si queremos que la gente crea algo, lo único que tenemos que hacer
es organizar una encuesta que diga que ta1 cosa es así, y después
darle publicidad, preferiblemente por televisión"

"La televisión no se ocupa de la «verdad», sino de crear una realidad"

"cuanta más televisión ve una persona, menos entiende, mas acepta, más
se disocia de su propio proceso de pensamiento [...] La televisión es
mucho más mágica que ningún otro producto de consumo, porque vuelve
normales las cosas y empaqueta y homogeniza aspectos parciales de la
realidad. Construye una realidad aceptable (el mito) juntando
ingredientes en gran medida inaceptables. Enfrentarse al mito
equivaldría a reconocer que somos ineficaces e incapaces, que estamos
aislados [...] Las imágenes de la televisión terminan siendo la
verdad”.   "

"la programación de la televisión contiene mensajes claros, definidos
por el argumento, los personajes, etcétera, y un mensaje oculto”, que
resulta mucho menos obvio. A través de esos mensajes ocultos se
pretende hacer el lavado de cerebro, «el mensaje a las claras, como el
argumento, es el portador a través del cual se pretende hacer el
lavado de cerebro».   "

"OTRA área clave del lavado de cerebro es la creación de una identidad
entre el hombre y el animal. Desde los dibujos animados para niños
hasta las series de televisión y las películas de la pantalla grande,
todos retratan animales que actúan como si fueran seres humanos"

"los niños fueron perdiendo la capacidad de diferenciar a los animales
y a los hombres"

"Otro mensaje oculto es el de que la “única” solución correcta, sea
cual sea el problema, es la del compromiso, aprender a ser tolerante"

"Postmam, profesor de la Universidad de Nueva York, en su libro
Divertirse hasta morir, “si algo hay que reprochar a Barrio Sésamo es
fingir que es un aliado del aula del colegio [...] Barrio Sésamo no
estimula a los niños a que les guste la escuela ni nada que tenga que
ver con ella. Los estimula a que les guste la televisión"

"llama una “visión retrospectiva controlada” para hijos del Baby boom
«de lo que ahora les gustaría creer que fueron los años sesenta. De
esta forma, los productores nos han puesto en contacto con las
emociones más infantiles y banales y nos han provocado nostalgia por
aquellos años. El"

"La gente ya lleva más de cincuenta y cinco años viendo anuncios
publicitarios que, mediante un inteligente uso de imágenes y de
música, intentan manipular los impulsos subconscientes y los instintos
para vender productos. La mayoría dura menos de un minuto, pero
contienen numerosas imágenes y a menudo una música repetitiva y
pegadiza"

"Los anuncios publicitarios cargados de imágenes repletas de valores
que no guardan relación con el producto pueden alejarnos de los mismos
valores que están explotando, confundirnos acerca de cómo hay que
alcanzar dichos valores, y abrir la puerta a la desesperanza, el
resentimiento y la apatía"

"Vista como religión, la publicidad estimula a la gente a que crea que
los ideales más vívidos y más atrayentes de nuestra cultura son
fáciles de alcanzar, solo con que demos con el producto adecuado y,
por extensión, acertemos con el sabor, la filosofía, la iglesia, el
gurú, la secta y hasta los fármacos que mejoran el rendimiento"

"La publicidad fomenta la desesperación. En primer lugar, rodeándonos
de imágenes de una perfección inalcanzable, y en segundo, diciendo de
forma implícita que ese producto va a proporcionarnos el ideal, cuando
en realidad no puede hacer tal cosa. La gente no necesita un automóvil
nuevo cada tres años, la televisión de plasma aporta poca riqueza a la
experiencia humana, un vestido largo no repercute en la expansión del
conocimiento, ni incrementa la capacidad de amar"

"el primer requisito previo para entender cuál es el lugar que nos
corresponde por derecho en el universo es que usted, lector, apague el
televisor y, lo que es más importante, lo mantenga apagado, a la luz
de las pruebas aportadas sobre las diabólicas y perversas intenciones
de Tavistock"

"El propósito de dicho experimento era poner fin al optimismo
descontrolado de una población que acababa de ganar una guerra mundial
y había empezado a reconstruir el mundo, y a reconducir esa energía
hacia dentro, hacia sí misma"

"Tres de las fases de ese experimento tuvieron tanto éxito que, hoy en
día, la mayoría de la gente piensa que se trata de una evolución
“natural’ de la sociedad occidental, y no de una deformación
antinatural impuesta desde fuera. La"

"Surgieron términos nuevos, como transhumanismo, control demográfico,
sostenibilidad, conservación, bioética y defensa del medio ambiente,
que sustituyeron a otros ya desfasados, como higiene racial y
darwinismo social. Y entretanto prepararon a la opinión pública, a la
formación de médicos y a las políticas gubernamentales para que
desecharan la noción de que la vida humana era sagrada.   "

"La idea general del transhumanismo es conseguir que las personas vean
los objetos inanimados y la tecnología al mismo nivel que un ser
humano"

"El transhumanismo no pretende mejorar la especie humana, sino
manipular la conciencia de la persona para que los seres humanos ya no
se consideren seres humanos, sino más bien un objeto tecnológico. Al
deshumanizar a nuestra especie, nos convertimos en el enemigo"

"Sin embargo, a principios del siglo pasado, grandes poblaciones,
sobre todo en Estados Unidos, un país sólido desde el punto de vista
tecnológico, ya no podían ser subyugadas apelando al misticismo
religioso. Tal como señaló Carl Jung, “se precisaba una base
seudocientífica para crear una secta”.   "

"Entra en escena H.G. Wells. A partir de 1894, Wells escribió decenas
de novelas de ciencia ficción y más de setenta cuentos"

"Los patrocinadores de la ciencia ficción dejaban bien claras sus
intenciones: los hombres eran bestias, la tecnología resultaba
impotente y el producto más acabado de la larga lucha librada por el
hombre para gobernar sus asuntos según la ley del progreso, el
soberano estado-nación, iba a ser sustituido por un orden universal
feudalista"

"En 1980 se estrenó en la televisión pública la serie Cosmos, que iba
a ser todo un referente. Desde entonces, se calcula que la han visto
más de mil millones de personas de todo el planeta. Cosmos hace una
crónica de la"

"lo que promueve la serie Cosmos no es ciencia pura. Desde los
delfines saltarines que interpretan la coreografía de las valkirias de
Wagner hasta las galaxias fruto de la psicodelia y de los dibujos
futuristas, desde las ballenas que cantan y los dioses hindúes, en el
Cosmos de Sagan hay un cambio de dialéctica que se aparta de la
verdadera ciencia y que nos adentra en el mundo del misticismo. En vez
de auténtica ciencia, expresión del empeño moral de la humanidad por
conseguir el progreso a través del control del universo natural,
Cosmos propone una versión acuariodionisiaca de la ciencia basada en
un irracionalismo existencialista, sentimentalista y ecologista, donde
todos participarían de una conciencia cósmica común"

"Entre las personas asociadas al WWF se encuentra el famoso director
del zoo de Fráncfort, conocido internacionalmente, un hombre que en
cierta ocasión dijo que la Tierra sería un lugar encantador si su
población no superase los veinte millones de personas"

"La fusión de temas populares americanos y música “seria”, que lanzó
Gershwin durante los años veinte, constituyo el decisivo punto de
inflexión que situó a toda la música, no solo a la de Estados Unidos,
sino a la del mundo entero, dentro de un marco filosófico y social
estrictamente aristotélico. Porque, a resultas de que se aceptase la
fusión del jazz y de los clásicos, rápidamente quedo eliminado de la
música cualquier objetivo intelectual y moral. La preferencia de la
música de Beethoven a la de Jerome Kern se consideraba ahora una
cuestión de «gustos», como sugirió Aristóteles dos mil quinientos años
antes. El adolescente drogado de hoy, que, en un acto de rabia
infantil y antisocial, afirma que tiene derecho a exhibir su propio
gusto musical poniendo música de rock a todo volumen en un estéreo
portátil para que se oiga a varias calles de distancia, en su legítimo
derecho, no está haciendo otra cosa que llevar el legado de Gershwin
hasta las últimas consecuencias"

"lo largo de la historia, esta facción y sus ancestrales homólogos se
han valido de diversas formas de arte para reforzar el pensamiento
mágico, la superstición y las concepciones propias de las personas
incultas, con el fin de inducir a un irracionalismo paranoico e
infantil en las poblaciones que pretenden controlar. Dichos
movimientos culturales se"

"lo que se promovía como blues y jazz era, muchas veces, más
degradante que la música que se tocaba en los burdeles de la época"

"Se comercializaron centenares de grabaciones, todas provistas del
mismo formato: una letra cantada en una jerga y un acento de los
negros del sur más un basto acompañamiento basado únicamente en tres
acordes; una receta musical tan empobrecida que solo resulta
comparable con la música de los locales de opio y prostitución de
Extremo Oriente"

"En Man and His World [El hombre y su mundo], un libro de texto que
escribió en 1948, Herskovits acuñó el término «relativismo cultural»
para describir la nefasta moral y el afán de describir a la población
que han caracterizado a la aristocracia al abordar la manipulación
social desde la época de Aristóteles"

"Herskovits desarrollo la tesis de que al hacer un estudio
antropológico de las diferentes sociedades y culturas hay que dejar a
un lado los principios universales; antes bien, «las evaluaciones han
de tener en cuenta la cultura de la que surgen»"

"El jazz] podría atribuirse en parte a los negros. Pero ha sido
desarrollado, desde el punto de vista comercial y artístico, por los
judíos"

"Los músicos consolidados como “reyes del jazz” eran seleccionados,
coronados y bautizados por los círculos de la sociedad judía que
rodeaban a Gershwin..., bajo la atenta mirada de sus amos de sangre
azul.   "

"Durante los años treinta, algunos artistas negros, como Richard
Wright, fueron seleccionados por Carl van Vechten y enviados a Stein
para que esta se los presentara al experto en técnicas de control de
la mente y terrorista Jean-Paul Sartre"

"Los textos escritos por el propio Adorno en esta época hacen hincapié
en la conocida conexión que existía entre el «gusto por el jazz» y las
tendencias latentes de rabia homicida y las fantasías de violacion
homosexual"

"¿Debe sorprendernos que Herbert Marcuse, el gurú de la Escuela de
Fráncfort, defendiera más tarde el jazz diciendo que era la música
apropiada para la Nueva Izquierda?   "

"En esa misma entrevista, Shepp decía que Jean-Paul Sartre, el
patrocinador de la obra Los condenados de la tierra, del terrorista
Franz Fanon, era el principal mentor de la “furia negra"

"Mediante este grotesco baile de las razas, un baile en el que han
participado con gran entusiasmo innumerables prostitutos negros,
judíos y también latinoamericanos, la nobleza británica logro volver
loco a todo el mundo de la música que participaba del intelecto
creativo. Dentro de este demencial mundo del espectáculo, las
consideraciones basadas en la razón quedaron invalidadas
automáticamente. El “gusto” irracional por la música de Stravinski,
Stockhausen o Cage compite con el gusto igualmente irracional por el
funk o el soul; razón por la cual, el público, cada vez menor, que se
identificaba con el repertorio clásico de los siglos XVIII y XIX, ya
no sabe muy bien con qué argumentos defender sus propios “gustos”
musicales.   "

"De este modo quedo despejado el camino para la indiscutible hegemonía
de la salsa, el rock, el soul y la disco, músicas de las masas
dementes... ya fueran rojas, blancas o negras. Esa es la música
fomentada por los oligarcas británicos por considerarla apropiada para
una masa excesivamente abundante y excesivamente culta, de “borregos”
de todos los colores, que pueblan Estados Unidos.   "

"Una vez más, los mismos personajes desempeñaron los mismos papeles:
Aldous Huxley, que, junto con Stravinski, se había mudado a
California; Margaret Mead y su marido Gregory Bateson, de la división
de la guerra psicológica del Instituto Tavistock; y Carl Jung, que,
para entonces, ya era consejero en temas de psiquiatría de Allen
Dulles, de la Inteligencia de las Fuerzas Aéreas y Jefe de agentes del
programa MK—ULTRA"

(El Instituto Tavistock(v.1))
