#+title:      estudio rx columna lumbar
#+date:       [2022-11-20 Sun 18:14]
#+filetags:   :estudio:
#+identifier: 20221120T181455

Informe: RADIOLOGIA GENERAL
Fecha: 25/10/2017
Descripción 	Valor 	Unidad
Motivo de Consulta 	cervicalgia lumbalgia
Informe 	COLUMNA LUMBAR (FYP).

Correcta alineación de muros posteriores.

Disminución del espacio L5/S1.


COLUMNNA CERVICAL (FYP):

Signos incipientes de uncoartrosis bilateral.

Disminución del espacio C4/C5 y C5/C6 asociado a osteofitosis marginal anterior.


                                     Atentamente.



La uncoartrosis es una condición que a su vez es el resultado de
alteraciones causadas por una artrosis en la columna cervical, en la
que los discos intervertebrales van perdiendo su elasticidad debido a
la pérdida de agua y nutrientes, tornándose cada vez más finos y menos
resistentes a los movimientos, lo que facilita su ruptura.

Estas alteraciones que surgen en los discos intervertebrales provocan
reacciones óseas en las vértebras adyacentes, ocasionando la formación
de picos de loro, que es una especie de defensa del organismo, la cual
promueve el crecimiento del hueso con el objetivo de volver la columna
vertebral más resistente.

Este hueso "extra" tiende a fusionar las vértebras, presionando
regiones delicadas de la columna, como la médula espinal y los
nervios, causando hipertrofia de los ligamentos y de otras
articulaciones de la columna vertebral.

Principales síntomas

Los síntomas más comunes que pueden manifestarse en personas con
uncoartrosis cervical son:

* Dolor en la zona del cuello;
* Sensación de hormigueo en los brazos;
* Debilidad muscular;
* Temblores en los brazos o manos.

Además, puede haber dificultad para mover el cuello debido a la
pérdida de elasticidad de los discos intervertebrales en la región
cervical.

Posibles causas

Entre las causas que pueden originar la uncoartrosis cervical están:
factores genéticos y hereditarios, lesiones en la región, uso del
cigarro, envejecimiento, tener alguna ocupación o hobbie que implique
movimientos repetitivos o trabajos pesados, o exceso de peso; lo cual
puede ejercer presión extra en la columna, dando como resultado el
desgaste precoz.

Cómo se diagnostica la uncoartrosis cervical

Para realizar el diagnóstico de la enfermedad, el médico puede llevar
a cabo un examen físico y hacer ciertas preguntas a la persona para
entender cuáles son los signos y síntomas que siente.

Asimismo, puede incluso recurrir a exámenes como radiografía,
tomografía computarizada, resonancia magnética o electromiografía, por
ejemplo.

Cómo se realiza el tratamiento

Generalmente, el tratamiento es realizado con medicamentos
analgésicos, antiinflamatorios y relajantes musculares, pudiendo
incluso complementarse con suplementos de sulfato de glucosamina y
sulfato de condroitina, los cuales ayudan a fortalecer las
articulaciones. Conozca cómo funciona la glucosamina y la condroitina
y cómo tomarlas.

Además de eso, la persona debe permanecer en reposo el mayor tiempo
posible y el médico puede incluso recomendar sesiones de osteopatía o
fisioterapia. Asimismo, la práctica de ejercicio físico moderado
también puede ser beneficiosa, siempre que sea realizada bajo
orientación de un profesional calificado, como fisioterapeuta,
profesor de educación física o fisiatra.

En casos más graves, en los que hay compresión sobre la médula o
raíces nerviosas, el médico puede recomendar la realización de una
cirugía con el objetivo de liberar estas estructuras nerviosas y
estabilizar la columna vertebral.
