#+title:      Las puertas de la percepcion
#+date:       [2022-11-19 Sat 16:40]
#+filetags:   :resaltados:
#+identifier: 20221119T164023

"Cada individuo se convierte, enseguida en el beneficiario y la
víctima de la tradición lingüística en la que ha nacido: el
beneficiario en cuanto al lenguaje procura acceso a las acumuladas
constancias de la experiencia ajena"

"la víctima en cuanto a que la confirma en la creencia de que ese
reducido conocimiento es el único conocimiento y en cuanto deja
hechizado su sentido de la realidad en forma que cada cual se inclina
demasiado a tomar sus conceptos por datos y sus palabras por cosas
reales"

"La mayoría de las personas solo llegan a conocer, la mayor parte del
tiempo, lo que pasa por la válvula reductora y está consagrado como
genuinamente real por el lenguaje del lugar"

"Las impresiones visuales se intensifican mucho y el ojo recobra parte
de esa inocencia perceptiva de la infancia, cuando el sentido no está
inmediata y automáticamente subordinado al concepto. El interés por el
espacio disminuye y el interés por el tiempo casi se reduce a cero"

"El muy desarrollado sentido del color que tiene el hombre es un lujo
biológico, precioso para él como ser intelectual y espiritual, pero
innecesario para su supervivencia como animal"

"No gran cosa, Dios lo sabe, en comparación con la realidad, pero lo
bastante para deleitar a generación tras generación de espectadores,
lo bastante para hacerles comprender, un poco por lo menos del
verdadero significado de lo que, en nuestra patética imbecilidad,
llamamos "meras cosas" y desdeñamos en favor de la televisión"

"El esquizofrénico es un alma, no solamente no regenerada, sino además
desesperadamente enferma. Su enfermedad consiste en su incapacidad
para escapar de la realidad interior y exterior y, refugiarse -como lo
hace habitualmente la persona sana- en el universo de fabricación
casera del sentido común, en el mundo estrictamente humano de las
nociones útiles, los símbolos compartidos y las convenciones
socialmente aceptables. El esquizofrénico es como un hombre que está
permanentemente bajo la influencia de la mescalina y que, por tanto,
no puede rechazar la experiencia de una realidad con la que no puede
convivir"

"La firme convicción de la realidad material del Infierno nunca
impidió a los cristianos medievales hacer lo que su ambición, su
lujuria o su codicia les reclamaba. El cáncer del pulmón, los
accidentes del tránsito y los millones de alcohólicos miserables y
transmisores de miseria son hechos todavía más ciertos de lo que era
en tiempos de Dante el hecho del infierno. Pero todos ellos son hechos
remotos e insustanciales al lado del hecho próximo y muy sentido del
ansia, aquí, ahora, de un alivio, de un sedante, de un trago o un
cigarrillo"

"Los problemas planteados por el alcohol y el tabaco no pueden ser
resueltos, sobra decirlo, por la prohibición. El afán universal y
permanente de autotrascendencia no puede ser abolido cerrando de golpe
las más populares Puertas del Muro. La única acción razonables es
abrir puertas Mejores, con la esperanza de que hombres y mujeres
cambien sus viejas malas costumbres por hábitos nuevos y. menos
dañosos"

"Cuando, por una razón cualquiera, los hombres y las mujeres no logran
trascender de sí mismos por medio del culto, las buenas obras y los
ejercicios espirituales, se sienten inclinados a recurrir a los
sustitutivos químicos de la religión: el alcohol y las "píldoras" en
el moderno Occidente, el alcohol y el opio en el Este, el hachís en el
mundo mahometano, el alcohol y la marihuana en América Central. el
alcohol y la coca en los Andes y el alcohol y los barbitúricos en las
regiones más al día de la América del Sur"

"Ser arrancados de raíz de la percepción ordinaria y ver durante unas
horas sin tiempo el mundo exterior e interior, no como aparece a un
animal obsesionado por la supervivencia o a un ser humano obsesionado
por palabras y nociones, sino como es percibido, directa e
incondicionalmente, porla Inteligencia Libre, es un experiencia de
inestimable valorpara cualquiera y especialmente para el intelectual"

"Goethe no se muestra siempre de acuerdo con sus propias valoración de
la palabra. En la madurez de su vida, escribió: "Hablamos
demasiado. Deberíamos hablar menos y dibujarmás. A mí, personalmente,
megustaría renunciar totalmente a lapalabray, corno la Naturaleza
orgánica, comunicar cuando tenga que decir por medio de dibujos. Esa
higuera, esa lombriz, ese capullo en el alféizar de mi ventana a la
serena espera de su futuro, son firmas trascendentales. Una persona
capaz de descifrar bien su significado podría dispensarsetotalmente de
la palabra escrita o hablada. Cuanto más pienso en ello, más me
convenzo de que hay algo inútil, mediocre"

"hasta -siento la tentación de decirlo- afectado en la palabra. En
cambio, ¡cómo impresiona la gravedad y el silencio de la Naturaleza,
cuando se está cara a cara con ella, sin nada que nos distraiga, ante
unas desnudas alturas o la desolación de unos viejos montes"

(Las Puertas De La Percepción)
