#+title:      nueva visita a un mundo feliz
#+date:       [2022-11-19 Sat 16:42]
#+filetags:   :resaltados:
#+identifier: 20221119T164250

"los promedios de mortalidad han disminuido en estos últimos años con
una brusquedad impresionante. En cambio, los promedios de natalidad
han permanecido en su antiguo alto nivel o, si han bajado, han bajado
muy poco y muy lentamente. En consecuencia, el número de humanos está
aumentando ahora más rápidamente que en cualquier otro momento de la
historia de la especie"

"Parodiando la frase de Winston Churchill, podríamos decir que nunca
tantos han sido tan manipulados por tan pocos"

"Y su corazón es puro porque son hombres de ciencia y han dedicado
seis mil horas a los estudios sociales"

"Hace cincuenta años, cuando yo era un chico, parecía de una evidencia
completa que los malos tiempos habían terminado, que la tortura, la
matanza, la esclavitud y la persecución de herejes eran cosas del
pasado. Entre personas que llevaban sombreros de copa, viajaban en
trenes y se bañaban todas las mañanas, horrores así parecían
inimaginables. Al fin y al cabo, estábamos viviendo en el siglo XX."

"Unos cuantos años después, estas personas que se bañaban a diario e
iban a la iglesia con sombrero de copa estaban cometiendo atrocidades
en una escala no soñada por los descarriados africanos y asiáticos"

"Jefferson, es cierto, era un realista además de un optimista. Sabía
por amarga experiencia que se podía abusar vergonzosamente de la
libertad de prensa. "No puede creerse actualmente nada de lo que
aparece en un periódico", dijo"

"Hitler tenía un profundo respeto por la Iglesia Católica y la orden
de los jesuitas; no a causa de su doctrina cristiana, sino a causa de
la 'maquinaria' que habían elaborado y dirigían, de su sistema
jerárquico, de sus tácticas en extremo inteligentes, de su
conocimiento de la naturaleza humana y de su sabio empleo de las
debilidades humanas para gobernar a los creyentes"

"La fuerza impulsora que ha provocado las más tremendas revoluciones
en el mundo nunca ha sido un cuerpo de doctrina científica que haya
conquistado a las masas, sino, invariablemente, una devoción que las
ha inspirado y, con frecuencia, una especie de histeria que las ha
arrastrado a la acción. Quien desee conquistar a las masas debe saber
dónde está la llave que ha de abrir la puerta de sus corazones." En la
jerga posfreudiana, la puerta de su inconsciente"

"Para hacerlos más masa todavía, más homogéneamente subhumanos, los
reunía, por miles y decenas de miles, en vastos locales y estadios,
donde el individuo podía perder su identidad personal y hasta su
humanidad elemental y quedar fusionado con la multitud"

"Reunidas en una multitud, las personas pierden su poder de
razonamiento y su capacidad de opción moral. Se hacen más
sugestionables, hasta el punto de que dejan de pensar o querer por
propia cuenta. Se excitan muchísimo, pierden todo sentido de la
responsabilidad individual o colectiva y suelen tener repentinos
accesos de rabia, entusiasmo y pánico. En pocas palabras, un hombre en
una multitud se comporta como si hubiese ingerido una fuerte dosis de
algún poderoso tóxico. Es víctima de lo que yo he denominado
"envenenamiento de rebaño"."

"como Bertrand Russell ha señalado, "los sistemas dogmáticos sin
cimientos empíricos, como el escolasticismo, el marxismo y el
fascismo, tienen la ventaja de producir una considerable cohesión
social entre sus discípulos""

"Cualquier disparate que sería vergonzoso que un ser razonable
escribiera, dijera o escuchara, puede ser cantado u oído por ese mismo
ser razonable con placer y hasta con una especie de convicción
intelectual"

"Cualquier disparate que sería vergonzoso que un ser razonable
escribiera, dijera o escuchara, puede ser cantado u oído por ese mismo
ser razonable con placer y hasta con una especie de convicción
intelectual. ¿Aprenderemos a separar el placer de cantar o de escuchar
una canción de esa tan humana tendencia a creer en la propaganda que
la canción formula?"

"Se hacen "entrevistas en profundidad" a muestras cuidadosamente
seleccionadas del cuerpo electoral. Estos entrevistadores en
profundidad sacan a la superficie los temores y deseos inconscientes
que más prevalecen en una sociedad dada en el momento de la
elección. Luego, se eligen por medio de peritos, se prueban en
lectores y públicos y se cambian o mejoran en vista de la información
así obtenida series de frases e imágenes destinadas a disipar o, en
caso necesario, fomentar esos temores y a satisfacer esos deseos,"

" Todo lo que actualmente se necesita es dinero y un candidato que
pueda ser enseñado a parecer "sincero". Conforme al nuevo sistema, los
principios políticos y los planes de acción específica han perdido la
mayor parte de su importancia. Las cosas que realmente importan son la
personalidad del candidato y la manera en que el candidato es
proyectado por los peritos publicitarios"

"Conforme al nuevo sistema, los principios políticos y los planes de
acción específica han perdido la mayor parte de su importancia. Las
cosas que realmente importan son la personalidad del candidato y la
manera en que el candidato es proyectado por los peritos
publicitarios"

"Todos los discursos del candidato-animador deben ser, pues, breves y
tajantes. Los grandes problemas del momento deben ser zanjados en
cinco minutos a lo sumo y preferiblemente (pues el público querrá
pasar a algo más entretenido que la inflación o la bomba de hidrógeno)
en sesenta segundos netos"

"Los métodos que actualmente se utilizan para colocar en el mercado a
un candidato político como si fuera un desodorante garantizan de modo
muy positivo el cuerpo electoral contra toda posibilidad de que
escuche la verdad acerca de nada"

"Pavlov hubiera estado de acuerdo con él; el cansancio aumenta la
impresionabilidad. (Tal es la razón, entre otras, de que los
patrocinadores comerciales de los programas de televisión prefieran
las horas de la noche y estén dispuestos a apoyar esta preferencia con
dinero efectivo.)"

"Si se adoctrina en la forma adecuada y durante la conveniente fase de
agotamiento nervioso, se obtendrán los resultados que se buscan. En
condiciones favorables, no hay prácticamente nadie que no pueda ser
convertido a cualquier cosa"

"la gente ve y oye realmente mucho más de lo que conscientemente sabe
que ve y oye, así como lo visto y oído sin saberlo queda registrado en
el subconsciente y puede influir en su pensar, sentir y obrar
conscientes"

"En la vida real, no existe eso que se llama el hombre medio. Sólo
existen hombres, mujeres y niños particulares, cada uno de ellos con
sus idiosincrasias natas de mente y de cuerpo, y todos ellos dedicados
(u obligados) a comprimir sus diversidades biológicas en la
uniformidad de tal o cual molde cultural."

"La resistencia extrema a la sugestión es muy rara. Por
fortuna. Porque, si todos fueran tan poco sugestionables como lo son
algunos, la vida social sería imposible. Las sociedades pueden
funcionar con cierto grado de eficiencia porque, en grados diversos,
la mayoría de la gente es bastante sugestionable"

"Los clérigos se pronunciaban contra el análisis de la propaganda
alegando que un análisis así socavaría la fe y disminuiría la
asistencia a la iglesia; los anunciantes adoptaron la misma actitud
por entender que tal análisis socavaría la lealtad a las marcas y
reduciría las ventas"

"Un escrutinio demasiado a fondo por parte de demasiada gente del
común de lo que dicen sus pastores y maestros puede resultar
profundamente subversivo."

"debería haber leyes que impidieran a los candidatos políticos, no
solamente gastar más que determinada cantidad en sus campañas
electorales, sino también recurrir a esa especie de propaganda
antirracional que convierte en disparate todo el procedimiento
democrático"

"para la mayoría, la vida en la enorme ciudad moderna es anónima,
atómica, menos que plenamente humana"
