#+title:      El psicoanalisis vaya timo
#+date:       [2022-11-19 Sat 16:35]
#+filetags:   :resaltados:
#+identifier: 20221119T163518

"Es importante tener presente que el psicoanálisis surgió a partir de
una teoría de la histeria, es decir, a partir de una explicación sobre
una enfermedad mental, y además, sobre una enfermedad mental ligada al
sexo.

Posteriormente, Freud cambio su método y su objeto de estudio. Sus"

"los actos fallidos y los lapsus lingüísticos nos podrán dar idea de
qué es lo que afecta realmente al paciente"

"Si los niños empiezan a cumplir las normas cuando nadie los mira, es
por la presencia del Superyó dentro de ellos.

"

"Freud ni sus seguidores demostraron jamás ese tipo de afirmaciones,
ni con pruebas extraordinarias ni con indicios relativamente
razonables. El psicoanálisis ha lanzado al mundo las ideas tal vez más
sorprendentes sobre la psicología humana, pero no lo ha hecho tras
considerarlas probadas"

"El psicoanálisis no exhibe la valentía que debe caracterizar a las
teorías científicas, que deben estar dispuestas siempre a que los
datos las contradigan. El psicoanálisis se escuda, por el contrario,
en tal cantidad de principios que evita la posibilidad de definir el
conjunto de observaciones que demostraría su falsedad"

"vía elegida por Freud fue mucho más rápida y efectiva para sus
intereses. Bastaba con enunciar sus ideas tal como se le ocurrían o,
en el mejor de los casos, fundamentarlas en observaciones clínicas de
adultos. Freud jamás observó la retención anal o el complejo de Edipo:
los infirió del análisis de los pacientes que acudían ya crecidos a su
consulta"

"En primer lugar, es evidente que los pacientes que acuden
voluntariamente —y pagando— a la consulta de un analista no son una
muestra representativa de la población"

"Si el método científico ha surgido especialmente para evitar la
propensión humana a dejarse llevar por ciertos engaños e ideas
previas, el método psicoanalítico parece haber surgido para fomentar
dicha tendencia.

"

"En psicología se conoce este fenómeno como efecto Barnum y es el que
explica, por ejemplo, que las descripciones vagas y ambiguas que suele
hacer la astrología nos parezcan, a veces, descripciones exactas de
nuestra personalidad"

"Una vez medidas independientemente ambas cosas podrá determinar si
existe o no la relación predicha. Pero un psicoanalista enfrentado al
mismo problema analizará generalmente sólo a una de las partes (por
ejemplo, al hijo) e inferirá del mismo conjunto de observaciones tanto
los problemas del hijo como el presunto autoritarismo paterno. Esta
forma de proceder conduce continuamente a la circularidad"

"palabras, "la riqueza de las observaciones sólidas sobre las cuales
descansan mis afirmaciones las hacen independientes de la verificación
experimental". Es como si alguien nos dijese que sus sólidas
observaciones le hacen concluir que un kilo de madera pesa menos que
un kilo de hierro, lo que hace su afirmación independiente de la
báscula"

"Al recordarlos, les aportamos una coherencia de la que probablemente
carecían en origen. Y al referirlos al analista, volvemos sobre este
proceso de elaboración. Hay que tener en cuenta, por otra parte, que
la mayoría de los pacientes que acuden a las sesiones de psicoanálisis
ha leído algo sobre teoría freudiana, lo que les llevará a seleccionar
unos materiales oníricos y no otros en función de las expectativas
atribuidas al analista.

"

"Evidentemente, una persona soltera, por más harta que esté de su
soltería, no dirá que su estado civil es "cansado" en lugar de
"soltero". El parecido entre el sonido de las palabras tiene una gran
relevancia en los lapsus lingüísticos y así se ha demostrado en
numerosos estudios (eso sí, estudios que emplean un adecuado control
experimental y que no se basan en meras intuiciones realizadas en un
despacho o junto a un diván).

"

"En efecto, varios países se apresuraron a desarrollar una legislación
sobre publicidad subliminal. No podía consentirse que los consumidores
fueran marionetas en manos de aquellos publicistas capaces de hurgar
directamente en su inconsciente. Los resultados no pudieron
reproducirse nunca y el propio autor del estudio afirmó que la
difusión de aquellos resultados no era sino una campaña publicitaria
de la propia bebida que se anunciaba, pero no por esto se detuvieron
los planteamientos conspiranoicos sobre cómo podíamos ser manipulados
por gobiernos, sectas y multinacionales mediante la publicidad
subliminal.

"

"según el psicoanálisis, debemos suponer que una persona que acude a
un profesional para dejar de fumar y lo consigue no se ha curado
(puesto que simplemente se ha librado de uno de sus síntomas),
mientras que otro que sigue fumando tras dos años de análisis está,
tal vez, en vías de resolver sus conflictos. Parece a veces que todo
el edificio del psicoanálisis está construido para evitar que alguien
pueda poner a prueba sus afirmaciones de forma objetiva.

"

"Asociación Americana de Psicología evaluó la eficacia de distintos
tipos de tratamiento psicológico"

"no se ha demostrado con rigor la eficacia del psicoanálisis"

"No debe extrañarnos que, para ciertas personas y en ciertas
situaciones, hablar de sus problemas con un psicoanalista sea mejor
que no hacerlo con nadie"

"El efecto Westermarck consiste en que, si dos personas permanecen
mucho tiempo juntas durante la infancia de cualquiera de ellas o de
las dos, es muy improbable que posteriormente se observe deseo sexual
entre ellas. Dicho de otra forma, si hemos conocido desde pequeña a
otra persona es menos probable que cuando llegue a la edad adulta nos
sintamos atraídos por ella, y recíprocamente, aquella persona tampoco
se sentirá atraída por nosotros"

"Si Freud había atribuido el tabú del incesto a una reacción contra el
complejo de Edipo, Westermarck lo consideró una mera consecuencia de
cierta tendencia innata: una tendencia implantada por la selección
natural para evitar los indeseables efectos de la consanguinidad"

"La segunda razón por la que es difícil que las primeras experiencias
sexuales determinen nuestra personalidad es que, aunque tales hechos
hubiesen sucedido, sería muy improbable que los recordáramos, aun en
la forma oculta que propone el psicoanálisis"

"el psicólogo Hans Eysenck: de lo que dijo Freud, algunas cosas han
sido confirmadas por la investigación científica, precisamente las que
no eran originales de Freud. Sus aportaciones personales siguen
distribuyéndose en dos categorías: o son indemostrables o son falsas"

"Cada cual se entretiene como puede"

"la práctica psicoanalítica puede implantar y fomentar los falsos
recuerdos en las personas, que pasarán a creer, por ejemplo, que
miembros de su familia han tenido un comportamiento horrible con
ellos"

"La represión es el más importante de los mecanismos de defensa del
Yo. Para Freud y la mayor parte de los psicoanalistas, los recuerdos
demasiado dolorosos son simplemente olvidados; no obstante, permanecen
en nuestro inconsciente de forma que pueden aflorar en los sueños, los
lapsus, etc. Esta idea de represión está directamente relacionada con
el concepto de trauma: las experiencias traumáticas son
reprimidas. Curiosamente, este binomio trauma-represión planteado por
el psicoanálisis ha tenido un fuerte arraigo popular. A la mayoría de
las personas les resulta hoy muy razonable pensar que una experiencia
traumática tiende a enterrarse en alguna profunda caverna de la mente
sin que sea fácil hacerla aflorar de nuevo.

"

"Normalmente, las personas que han tenido la desgracia de experimentar
situaciones particularmente desagradables indican precisamente lo
contrario de lo que dice el psicoanálisis. Por ejemplo, los
supervivientes de los campos de concentración tienden a decir que
jamás podrán olvidar lo que allí vivieron. A"

"Es posible que algunas personas olviden ciertos hechos traumáticos,
pero la pauta general es precisamente la contraria a la predicha por
el psicoanálisis. La profesora Loftus, una de las"

"la represión como principal mecanismo de defensa del Yo resulta ser
también el mecanismo de defensa fundamental del psicoanálisis. Si
alguien no recuerda haber recorrido las etapas evolutivas planteadas
por Freud, o si no es consciente de haber sufrido abusos sexuales
durante la infancia pese a la opinión del analista, el error no está
ni en la teoría freudiana ni en las interpretaciones del terapeuta
sino que es fruto de la represión del propio paciente.

"

"hay cosas que recordamos y que nunca nos han sucedido, o al menos no
de la manera en que las recordamos. La razón es que recordar es un
proceso constructivo. Cada vez que rememoramos un hecho lo alteramos
de alguna manera. La forma en que lo alteremos depende de diversas
causas"

"Las investigaciones sobre falsos recuerdos parecen indicar que
algunas de las cosas que los pacientes sometidos a psicoanálisis creen
recordar podrían al menos haber sido implantadas durante el
tratamiento y no ser genuinas recuperaciones de hechos olvidados"

"En varios países existen asociaciones de víctimas de falsos
recuerdos, integradas por personas que han sido acusadas de varios
tipos de delitos —especialmente, de abusos sexuales— fundamentados en
recuerdos ocultos "recuperados" en sesiones de psicoterapia. No sólo
las personas falsamente acusadas pueden llegar a convertirse en
víctimas de los falsos recuerdos"

"Curiosamente, ellas no recuerdan tales abusos pero el terapeuta
insiste en que el hecho de que no los recuerden es síntoma de la
virulencia que tuvieron. El propio Freud hacía hincapié en que había
que mostrarse inalterable ante la resistencia del paciente a reconocer
este tipo de hechos. El terapeuta debía insistir, y hoy sabemos que,
si lo hacía durante varias sesiones, era muy probable que el recuerdo
llegara a implantarse en el paciente aunque no respondiese a la
realidad"

"En el campo de la crítica literaria el psicoanálisis ha influido
enormemente a través de la hermenéutica o arte de la interpretación de
los textos, aunque también puede interpretar otros materiales"

"Bien parece —respondió don Quijote— que no estás cursado en esto de
las aventuras: ellos son gigantes; y si tienes miedo, quítate de ahí,
y ponte en oración en el espacio que yo voy a entrar con ellos en
fiera y desigual batalla". Parece que no estamos cursados en esto del
psicoanálisis y nos cuesta entender las complejas razones que pueblan
los textos de crítica psicoanalítica"

"esos trabajos el crítico psicoanalista practica algo que el propio
Freud había indicado como algo que se debía evitar en la práctica del
psicoanálisis: la contratransferencia, que consiste en verter los
propios conflictos en el análisis. Curiosamente, en una profunda
contradicción, fue el propio Freud quien les enseñó a hacer crítica de
esa manera"

"un estudio llevado a cabo sobre 129 sociedades distintas, de
distintas épocas y ubicadas en diferentes lugares, se halló que la
mayoría de ellas no prohibían o regulaban en forma alguna el incesto
entre miembros de la familia nuclear (padres, hijos y hermanos)
mientras que casi todas lo hacían para evitar relaciones con miembros
de la familia política o primos. Por ejemplo, es frecuente encontrar
culturas en las que la mujer se traslada a vivir con la familia de su
marido. En tales culturas suele haber leyes que castigan, a veces con
extrema dureza, las relaciones de la mujer con los hermanos de su
marido. De esta forma evitan la duda sobre la paternidad de los hijos"

"En la propia sociedad occidental, las relaciones sexuales entre
padres adoptivos y padrastros y los menores con que conviven se dan
mucho más frecuentemente que con padres biológicos y ocurren sobre
todo cuando estas personas no han convivido con los menores en sus
primeros años de vida. Es decir, exactamente lo contrario de lo que
afirma el psicoanálisis y precisamente lo indicado por la teoría
evolucionista"

"Sokal se dedicó posteriormente a desenmascarar las "imposturas
intelectuales" de algunos de los más reputados gurús del
posmodernismo, entre ellos el psicoanalista Jacques Lacan, cuya
influencia destacamos en el capítulo 1. Lacan intelectualizó,
supuestamente, el psicoanálisis y desarrolló la hermenéutica
psicoanalítica; para él, el inconsciente está estructurado como un
lenguaje. Lacan utilizó ideas provenientes de la lingüística
estructural, las ciencias y las matemáticas, y con todo ello compuso
numerosos escritos, muchos de los cuales son incomprensibles. Según el
prestigioso lingüista Noam Chomsky, Lacan es un charlatán
perfectamente consciente de serlo"

"Curiosamente, y en contraste con lo anterior, los niños que afirman
haber sido objeto de abusos sexuales por parte de sus progenitores
pueden encontrar que el psicoanálisis desestima la veracidad de sus
recuerdos. Puesto que los niños desean supuestamente mantener este
tipo de relaciones, según el psicoanálisis, no sería raro que las
inventasen como fantasía sexual"

"las inocentes madres de niños que padecen un trastorno como el
autismo, de más que probable origen innato, pueden verse acusadas,
mientras que los padres que abusan de sus hijos pueden verse eximidos"

"psicoanálisis, partiendo de datos empíricos escasísimos, y a menudo
falseados, produce de nuevo ideas dañinas para la sociedad: las madres
de los autistas y homosexuales, y éstos mismos, así como las mujeres
en general, han sido víctimas de"

"Siguiendo el símil periodístico, el psicoanálisis vendría a ser algo
así como "psicología amarilla": la narración de explicaciones
arbitrarias sin base real"

"Nadie sale de la universidad con un título de psicoanalista: el
interesado deberá formarse en los ámbitos que las sociedades
psicoanalíticas estipulen"

"Para muchos psicoanalistas, las obras de Freud constituyen un libro
sagrado"

"Como la astrología, el psicoanálisis nos dice cosas relevantes sobre
nosotros mismos apelando a ideas presuntamente científicas que
estarían detrás de sus afirmaciones"

"El hecho de que el psicoanálisis empezara a aludir continuamente al
sexo en una época de honda represión sexual fue, tal vez, su mejor
elemento de propaganda"

"Breuer, coautor junto con Freud de su primer libro sobre la histeria,
llegó a decir que el principal objetivo del desmedido énfasis de Freud
en la sexualidad había sido épater le bourgeois (es decir, provocar a
los burgueses"

"psicoanálisis se atreve, además, a abordar la explicación de
cualquier fenómeno, lo que evita que los clientes se sientan
desilusionados por lo que reciben a cambio de su dinero"

"A una persona adicta al alcohol que acuda a una consulta ordinaria se
le darán explicaciones simples y un tratamiento en el que participará
en gran medida gracias a su propia voluntad. Si acude a un
psicoanalista, oirá posiblemente que el origen de su problema está en
un lejano conflicto de la infancia, que una vez superado hará
desaparecer su alcoholismo. El segundo método es mucho más atractivo
que el primero y, además, en la mayoría de los casos, tendrá como
consecuencia que el paciente podrá seguir bebiendo.

"

"Freud construyó una especie de religión laica para los nuevos tiempos
y un mito del que, como predecía Ludwig Wittgenstein ya en la primera
mitad del siglo XX, nos será muy difícil desembarazarnos: el mito del"

(El Psicoanálisis ¡vaya Timo!)
