#+title:      El retorno de los Dioses
#+date:       [2022-11-19 Sat 16:34]
#+filetags:   :resaltados:
#+identifier: 20221119T163428

"Esos «textos originales», que son un rico filón para las
especulaciones teológicas, no existen en realidad. ¿Qué es lo que
tenemos verdaderamente? Unas copias que, sin excepción, se realizaron
entre los siglos iv y x después de Cristo"

"Los propios Padres de la Iglesia de los primeros siglos estaban de
acuerdo (aunque disintiesen entre ellos en muchas otras cosas) en que
los textos originales habían sido alterados. Hablaron muy claramente
de la «adición, profanación, supresión, alteración y destrucción
generalizada» de los textos."

"El cielo es el objeto de todos los anhelos y de todos los sueños, el
cumplimiento de todas las esperanzas. Pero ¡un momento! Aquí falla
algo. Ya había mucha envidia, conflictos y guerras a muerte en el
cielo antes de que fueran creados siquiera los seres humanos. ¿Es que
hemos entendido mal en algún momento el concepto de lo que es el
cielo?"

"Los antiguos escritores e historiadores describieron a estas
criaturas y afirmaron, además, que habían sido creadas por los dioses.

• Los escultures y estuquistas de hace millares de años
preservaronpara la eternidad a estos seres híbridos"

"Los teólogos pueden creer en las revelaciones, pero nunca conseguirán
hacer racional lo que es irracional por naturaleza"

"Tienen fe en que los textos sagrados y no tan sagrados salieron una
vez de la boca de Dios, en que él los dictó o se los reveló a los
pocos escogidos. Pero ¿qué queda de estos textos cuando se elimina el
elemento de la fe?"

"Cuando nos quitamos de encima la creencia en el carácter sagrado de
estos textos es cuando podemos empezar verdaderamente a
estudiarlos. Es, en efecto, nuestra idea de su carácter sagrado lo que
nos impide realizar un análisis moderno de su significado.

"

"¡Ojalá se hubieran limitado a copiar los antiguos textos sin
alterarlos! Pero esto es casi imposible para una persona que
piensa. Ni siquiera hoy día somos capaces de hacer tal cosa. Ya
tenemos versiones del Nuevo Testamento en cómic y otras adulteraciones
todavía peores, con las que supuestamente se pretende adaptar a
nuestros tiempos el texto sagrado. Pero «con medios impuros se
consiguen resultados impuros» (Mahatma Gandhi, 1869-1948)."

"Pero siempre que Abraham (o quien fuera, el nombre es lo de menos)
empieza a hablar en primera persona, yo aguzo el oído. Saco el máximo
partido de estos pasajes, sobre todo cuando describen algún episodio
asombroso relacionado con el espacio, que no podían inventarse los
redactores posteriores porque no tenían acceso a un conocimiento tan
detallado"

"describe a dos seres celestiales que bajan a la Tierra[31]. Estos dos
seres celestiales subieron a Abraham a las alturas, pues el «altísimo»
quería conversar con él. Abraham cuenta que no eran humanos y que le
produjeron mucho miedo. Dice que tenían el cuerpo brillante «como un
zafiro»; lo hicieron subir entre humo y fuego, «como con la fuerza de
muchos vientos». Cuando llegó a las alturas, vio «una luz gloriosa e
indescriptible» y unas figuras grandes que se gritaban entre sí unas
palabras «que yo no entendí»"

"Existen dos libros que no están incluidos en el Antiguo Testamento
pero que se cuentan entre los textos apócrifos. Los Padres de la
Iglesia que recopilaron la Biblia no supieron qué hacer con los textos
de Enoc. Los excluyeron porque no los comprendían"

"Nadie nos engaña nunca, somos nosotros quienes nos engañamos"

"resulta útil saber que el alefato hebreo en que están escritos los
textos proféticos sólo contiene las consonantes y no puede reflejar el
futuro gramatical"

"El judaísmo, el islam y el cristianismo basan sus exégesis en unos
mismos profetas antiguos. ¿Cómo puede decirse, pues, que la exégesis
es una ciencia exacta?"

"Y yo creo, personalmente, que es una tontería decir que diversos
pueblos de todo el mundo aprendieran a esperar a sus dioses después de
escuchar a los misioneros cristianos"

"En ambos casos somos considerados la forma de vida más elevada, única
en el universo. ¿Para qué queremos extraterrestres, aunque todos los
libros sagrados del mundo nos proporcionen pruebas de su existencia?
"

"¿No es posible que el mensaje codificado haya sido activado en él con
cierto adelanto? Sabemos por experiencia que los genes humanos sólo
liberan determinados mensajes después de cierto tiempo"

"En el libro de Enoc (39, 1) se lee:

En esos días bajarán de los altos cielos los hijos elegidos y santos,
y su raza se unirá a la de los hijos de los hombres.

¿Está indicando Enoc la segunda posibilidad de la lista citada? En tal
caso, ¿cómo lo sabía? ¿Se lo dijeron los «guardianes del cielo»? ¿Se
lo dijo alguien más? "

"El habla humana apareció hace unos 30.000 años, como primer medio de
comunicación. Las primeras pinturas o grabados rupestres, primera
forma visual de comunicación, tienen unos 13.000 años de
antigüedad. Las primeras formas de escritura sólo tienen 5.000 años; y
hace 3.000 años surgieron los primeros medios de comunicación a larga
distancia, en forma de señales de humo y de señales con espejos. La
imprenta se inventó hace 500 años, y la comunicación telegráfica
surgió en el siglo pasado. Sólo hace cien años que tenemos la
cinematografía, y los ordenadores están al alcance de todos desde hace
treinta años.

"

"De modo que parece que a los egiptólogos no les interesan los
resultados que no les convienen, aunque sean resultados científicos y
se hayan obtenido por medios científicos adecuados"

"¡Si de los egiptólogos dependiera, no haría falta realizar nunca
investigaciones, pues ellos ya lo saben todo!"

", si consideramos que los espacios vacíos que conocemos del interior
de la pirámide equivalen a 2.000 metros cúbicos, 1.800 de los cuales
corresponden a la gran galería y el resto a las demás cámaras; pero la
gran galería no se ha de considerar «cámara»."

"La Gran Pirámide es completamente anónima: no sabemos nada del equipo
de arquitectos y de constructores, ni del sacerdote, ni del faraón que
participaron en su construcción. No contiene una sola inscripción que
nos pueda ayudar a resolver una sola pregunta sobre el modo en que se
construyó"

"Todas las paredes, galerías y cámaras de la pirámide de Kéops están
lisas: no están ni han estado nunca decoradas con una sola palabra. Un
anonimato perfecto"

(El Retorno De Los Dioses(c.1))
