#+title:      nutricion energetica
#+date:       [2022-11-19 Sat 16:44]
#+filetags:   :resaltados:
#+identifier: 20221119T164441

Williams, John - Stoner [11580] (r1.1).epub (Resaltar: 58; Nota: 1)

-------------

"No debe tomarse crudo ni debe combinarse con el arroz u otro cereal,
pues puede producir demasiada contracción pancreática, lo que se puede
traducir en un hambre insaciable. Combina bien con verduras,
legumbres, salsas y con todo tipo de proteínas en general. Es un buen
alcalinizante. Si se toma crudo, hay que mezclarlo con limón o aceite
u otros alimentos yin para suavizarlo" (salsa soja)

"La esencia es un elemento desconocido para la medicina occidental y,
sin embargo, resulta indispensable tenerla en cuenta para entender el
funcionamiento bioenergético del cuerpo humano. Los alimentos que la
restituyen son, sobre todo, los granos —semillas, legumbres, cereales
en grano—, así como los frutos secos, los aceites de primera presión
en frío y el pescado. De ahí la importancia que deben tener en nuestra
dieta"

"Aún hoy, un grano de arroz integral se emplea como cargador de
energía; se usa, por ejemplo, en acupuntura, para tonificar
determinados puntos energéticos"

"Los granos son la fuente primordial de energía
electromagnética. Cuando se ingiere grano, su energía pasa al
organismo y carga enormemente el cuerpo"

"el consumo de cereales integrales, en grano preferentemente, aporte
mucha más energía que el consumo de verduras y todavía mucha más que
el de fruta"

"Si en general los animales, que grosso modo son yang, se alimentan de
vegetales, que son básicamente yin, el hombre, que es el animal más
cargado de energía celeste, debe tender a alimentarse del vegetal con
más carga energética terrestre, que no es otro que el cereal"

"Cuando los cereales constituyen parte fundamental de nuestra dieta,
atraemos y retenemos más energía celeste, esa energía yang que nos
aportará más inspiración, más capacidad mental y de trabajo, más
concentración, más resistencia"

"No en vano, los cereales han sido el alimento básico en todas las
grandes civilizaciones en su camino hacia el esplendor"

"En muchos casos, asimismo, las personas más evolucionadas
espiritualmente se han alimentado mayoritariamente de granos y
verduras"

"Resulta básico, por ejemplo, que nuestra alimentación se base en
productos de la zona en que vivimos y dé la estación en que
estemos. Cuando tomemos alimentos de otros lugares del mundo, debemos
procurar siempre que sean propios de zonas pertenecientes a nuestro
hemisferio y que cuenten con un clima similar al de la región donde
nosotros vivimos"

"Lo normal cuando se abusa de los crudos es que el nivel de energía
digestiva baje considerablemente: de hecho, cuando se toma ensalada
muy a menudo, es frecuente que la barriga se hinche, que algunos
alimentos repitan —el pepino, la cebolla, el pimiento, etc.—y que se
sufra de flatulencias, sensación de cansancio o digestiones pesadas"

"una media de un 15% diario de proteínas es necesaria. No basta,
además, con tomar proteína de vez en cuando. Lo recomendable es
tomarla en, al menos, dos de las comidas diarias"

"¿Qué fuentes proteicas son las más recomendables? En primer lugar,
una gran olvidada en la cocina moderna, no así en la tradicional: la
legumbre"

"Si el plato se completa con algo de sésamo, que le aportará
minerales, ácidos grasos, tríptófanos y lisina, la combinación es
perfecta, y mucho más saludable, proteica y equilibrada que un bistec
con patatas. La legumbre, además, es excelente para el trabajo
intelectual. Resulta ideal, por ejemplo, si uno tiene que estudiar"

"Para su óptimo aprovechamiento, tanto las legumbres como los cereales
timen que estar bien cocinados. El arroz al dente o las lentejas duras
son indigestos, y, en general, las legumbres poco hechas producen
fermentaciones y gases"

"El miso es un fermento de alto valor energético y nutritivo que
atesora grandes propiedades depurativas, regula la flora intestinal,
alcaliniza, tonifica los riñones y remineraliza. En resumen, una
maravilla. Es efectivo, incluso, contra la radiactividad. Cuando se
produjo el bombardeo de Hiroshima, había en un hospital de la ciudad
un médico que conocía muy bien la dualidad yin/yang. Sabía, por lo
tanto, que la radiactividad es muy yin, muy desintegradora. Él, su
equipo y sus pacientes empezaron a comer una estricta dieta a base de
arroz integral, algas y sopas de miso a diario. De ese modo,
consiguieron librarse de padecer leucemia, cáncer de piel y otras
enfermedades generadas por la radiactividad. Asimismo, tras el
accidente de la central nuclear de Chernóbil, la venta de miso se
disparó en el norte de Europa"

"El miso es en realidad una pasta que habitualmente se toma disuelta
en las sopas —media cuchara dita de té por cada taza o plato —pero—; y
que se añade al final de la cocción para evitar que pierda sus
fermentos vivos"

"Cereal integral + legumbre = bistec

Cereal integral + legumbre + sésamo triturado > bistec

Cereal integral + legumbre + sésamo triturado + quínoa o amaranto»
bistec  "

"los niños alimentados con leche de vaca crecen más rápidamente, se
desarrollan estructuralmente más deprisa, pero no sucede lo mismo a
nivel cerebral ni en lo que respecta al sistema nervioso"

"Ocasionalmente se puede tomar leche sin hervir, pero, incluso si uno
cuenta con una buena capacidad digestiva, el consumo regular de leche
cruda, aunque sea vegetal, le puede acabar afectando a medio plazo"

"El pollo y los huevos comerciales son poco recomendables"

"Los huevos de granjas de producción intensiva están contaminados con
salmonela y parasalmonelas, bacterias que pueden producir salmonelosis
si el huevo no se cocina bien"

"aceite de oliva, se trata de un aceite monoinsaturado en cuya
composición los ácidos grasos esenciales alcanzan una proporción muy
baja —entre el 8% y el 10%—. No es, pues, un aceite especialmente
nutritivo. Sin embargo, es sabroso, combate el colesterol y contribuye
a hacer más apetecibles los vegetales, virtud no desdeñable en
absoluto"

"si tomamos aceite de oliva, debemos complementarlo tomando también
aceites de las gamas omega 3 y omega 6. De lo contrario, no
tonificaremos la esencia y nuestros tejidos envejecerán más
rápidamente"

"el aceite de oliva que tomemos sea siempre de primera presión en frío
y de la menor acidez"

" si uno tiene una salud estable y la piel bien lubricada, lo mejor es
reducir el consumo de aceite y tomar directamente semillas, semillas
tostadas, granos y legumbres. Cuando se toman regularmente, se puede
disminuir el consumo de aceite sin mayor problema. Caso distinto es
cuando se tienen deficiencias cutáneas, por ejemplo por estar en
contacto habitualmente con detergentes"

"si uno sigue una dieta limpia y rica en alimentos que contienen agua,
como las verduras y otros vegetales, no es necesario beber tanto. Sí
lo hacemos, el exceso de líquido generará cansancio en el riñón"

"¿Cómo podemos saber si estamos mal hidratados y necesitamos beber?
Muy fácilmente; reparando en si la lengua se nos pega al paladar"

"café le quita energía al cuerpo para llenar la cabeza con ella"

"Cada vez que uno toma café, consume esencia prenatal del corazón y el
riñón, con lo que sufre un acceso de envejecimiento prematuro similar
al que provocan las drogas"

"Aunque tomemos apenas una o dos tazas al día, él café sube el
colesterol y aumenta el riesgo de sufrir cáncer de páncreas, infartos
de miocardio y cáncer de mama o vejiga en el caso de mujeres cuya
alimentación sea rica en carnes y grasas"

"Cuando estemos sentados a la mesa, conviene que nuestra atención se
centre en la comida, pues de lo contrario la digestión se resentirá"

"La energía que los dientes desprenden revitaliza la comida,
facilitando su transformación en sustancias nutritivas, útiles y
metabolizables por el organismo. Por otra parte, una masticación
concienzuda puede insuflar vitalidad incluso a alimentos recolectados
hace tiempo, congelados o excesivamente yin"

"está demostrado que una masticación adecuada produce una suerte de
masaje en el cráneo que ayuda al funcionamiento cerebral. Y no hay que
olvidar que una digestión óptima es el mejor tónico de las funciones
cerebrales que existe. Asimismo, conviene recordar que cuanto más
arriba está un animal en la pirámide evolutiva, más mastica"

"las personas vegetarianas puras que no quieran interferir en la
producción de vitamina Bi2 por el organismo no deben consumir
productos que puedan destruir la flora: azúcar, productos
quimicalizados, farináceos de mala calidad, etc.   "

"En Oriente, donde existe una gran tradición vegetariana, no se
consumen verduras crudas. Las verduras se cocinan —aunque poco, pues
de lo contrario perderían vitaminas— para que no resulten tan frías"

"Una buena manera de empezar el día en el caso de que estemos faltos
de energía digestiva —de lo cual son síntomas las digestiones lentas,
la acidez de estómago, la hinchazón de barriga, los gases, el hecho de
que nos sintamos incómodos después de comer...—es tomar como desayuno
una crema de mijo, quínoa o arroz, unos cereales calientes bien
cocinados o unos copos de avena, según la fuerza digestiva de que
dispongamos. Si ésta es muy escasa, lo más indicado es optar por el
mijo. En el caso opuesto, lo ideal son unos copos de avena bien
hervidos. Es muy importante que ya de buena mañana tonifiquemos el
bazo, pues de ese modo estará en buenas condiciones durante todo"

"el azúcar blanco ejerce un efecto muy acidificante en la sangre a
pesar de ser un producto alcalino"

"Los tejidos y la sangre deben de tener un nivel de
acidez/alcalinidad, llamado también pH, ligeramente alcalino, para
compensar la acidez o pérdida de electrones que causan las fundones
vitales, la actividad diaria y el estrés"

"Cuando tomamos alimentos acidificantes —carne, lácteos, la mayoría de
los cereales (especialmente los refinados), legumbres, pescado,
azúcar, drogas, productos químicos, muchos medicamentos, grasas y en
algunos casos las frutas—, cuando sufrimos de estrés, cuando
realizamos demasiada actividad física o cuando respiramos aire
contaminado, nuestra sangre se acidifica en demasía, con lo que
podemos contraer enfermedades con"

"Cuando tomamos alimentos acidificantes —carne, lácteos, la mayoría de
los cereales (especialmente los refinados), legumbres, pescado,
azúcar, drogas, productos químicos, muchos medicamentos, grasas y en
algunos casos las frutas—, cuando sufrimos de estrés, cuando
realizamos demasiada actividad física o cuando respiramos aire
contaminado, nuestra sangre se acidifica en demasía, con lo que
podemos contraer enfermedades con facilidad."

"una práctica dietética tradicional, basada en el consumo de cereales
integrales, verduras cocidas, legumbres, algas y otros alimentos
naturales, condimentados todos ellos con sal de mar o alguno de sus
derivados y acompañados de bebidas no estimulantes, tiende a generar
más alcalinidad en el cuerpo y en la sangre"

"los cereales en grano son ligeramente acidificantes, salvo el mijo y
el trigo sarraceno tostado (kasha). Para alcalinizarlos pueden
cocinarse con alga kombu o sal, o dejarse en remojo entre 8 y 12
horas, pues de ese modo germinan, lo cual los vuelve más
alcalinos. Huelga decir que los condimentos salados —hechos con sal
marina o algas— que se echan encima del cereal son alcalinizantes,
pues son ricos en sales minerales"

"si tomamos cereales y proteína, deberemos tomar verdura o emplear
condimentos alcalinizantes y bebemos un té o un café de cereales; si
tomamos legumbre, deberemos aliñarla con un poco de salsa de soja y
cocinarla con alga kombu."

"los condimentos son alcalinizantes, con lo que dan un plus de energía
a corto y largo plazo. Son ricos en minerales y es muy recomendable
consumirlos poniéndolos sobre el cereal"

"Es alcalinizante y mineralizante y combate las parasitosis
intestinales. Su efecto más peculiar es su poder antirradiactivo, y
combate el exceso de contaminación electromagnética, por lo que
conviene tomarlo regularmente. Ayuda, además, a regular la flora
intestinal"

"Las semillas de sésamo, como ya hemos visto, poseen un altísimo valor
nutricional: son ricas en calcio, magnesio y manganeso, así como en
triptófano, un aminoácido esencial presente de manera muy escasa en
otras fuentes proteicas y que tiene efectos muy positivos sobre el
estado mental, causando sensación de bienestar. Gracias a su alto
contenido en nutrientes, el sésamo tostado es un excelente complemento
de los granos y las legumbres. "

"las algas son una magnífica fuente de nutrientes para los humanos"

"mijo combinado con quínoa y amaranto, se llenan de energía y se
reconstruyen interiormente"

"El arroz integral es un cereal básico, el más equilibrado de todos"

"Cuando empezamos a alimentarnos de manera limpia, comenzamos a
descargar, en orden inverso al de su formación, las acumulaciones que
nuestro cuerpo ha ido forjando desde el embarazo de nuestra
madre. Paralelamente a esta descarga, se desarrolla un cambio
perceptual, con la consiguiente mejora del bienestar personal y un
cambio cuantitativo y cualitativo del nivel de conciencia"

"La avena requiere para su cocción del uso de sal, pues es
acidificante y la sal la neutraliza"

"Sí tomamos mucha legumbre sin justificación, sentiremos cansancio y
el cuerpo nos pedirá alimentos muy yang, pues tomar demasiada yiniza
en exceso"

"es importante acompañarla con sésamo tostado, que aporta triptófano,
y con algas, que aportan oligoelementos como el yodo. La mezcla de
alga y legumbre ejerce un efecto regulador sobre las glándulas
endocrinas, especialmente sobre la tiroides, y ayuda a que los niños
crezcan más armónicamente"

"añadimos al plato algún carminativo, como el laurel, el comino o el
cardamomo, mejor que mejor"

"Los pickles proporcionan concentración, despejan la mente, quitan el
sueño y fortalecen los ojos. Son ideales en caso de vista cansada, ya
que el ojo, desde el punto de vista energético, depende del hígado y
su meridiano, y, como hemos visto, los pickles son excelentes
tonificadores de la energía de ese órgano"

"La ciruela umeboshi sacia y da vigor; de ahí que una forma
tradicional de hacer snacks en Japón sea introducir ciruelas umeboshi
en bolas de arroz integral recubiertas con alga nori"

"Es bueno que le echemos a la fruta una pizca de sal. De este modo la
haremos más dulce, compensaremos el yin, combatiremos su acidez, la
polarizaremos y nos sentará mejor.

"

"Melón

Es la fruta más nutritiva, pero resulta indigesto, por lo que no debe
combinarse con otros alimentos, hay que tomarlo entre comidas y
evitarlo por la noche. Tonifica el yin del bazo y un poco el del
estómago. De temperatura fresca, ayuda a nutrir e hidratar el
organismo en los meses de verano"
