#+title:      alguien volo sobre el nido del cuco
#+date:       [2022-11-19 Sat 16:23]
#+filetags:   :resaltados:
#+identifier: 20221119T162326

"Yo aún oigo el sonido de las cascadas en el río Columbia, siempre,
siempre, oiré el aullido de Charley Barriga de Oso cuando ensartó un
gran salmón, y el rumor de los peces en el agua, y las risas de los
niños desnudos en la orilla, y las mujeres junto a los bastidores
donde ponen el pescado a secar... sonidos que me llegan de un tiempo
muy lejano."

"Hay largos períodos —tres días, tres años— en que resulta imposible
ver nada, en que la única referencia respecto al lugar donde nos
encontramos es el altavoz que retumba sobre nuestras cabezas como la
campana de un faro en la niebla. Cuando consigo ver algo, en general
los otros siguen haciendo sus cosas tan tranquilos, como si no
hubieran notado ni la más ligera bruma. Yo creo que la niebla les
afecta la memoria de un modo distinto que a mí"

"Y en cuanto a las imposiciones de la enfermera, a su costumbre de
restregarte tus flaquezas por la cara hasta hacerte perder la poca
dignidad que te queda, pues te obliga a encogerte hasta que estás
aniquilado por tanta humillación, tampoco puedo remediarlo."

"Es como si cada rostro fuese un rótulo, como esos carteles con la
frase «Soy ciego» que se cuelgan al cuello los acordeonistas italianos
en Portland, pero éstos dicen: «Estoy cansado» o «Estoy asustado» o
«Me está matando el rencor» o «Estoy lleno de engranajes y la gente me
empuja de un lado para otro». Puedo leer todos esos rótulos, por
pequeñas que sean las letras. Algunas caras miran a su alrededor y ven
las de los demás y podrían leer en ellas si quisieran, pero ¿para qué?
Las caras pasan flotando en la niebla como confetti"

"Te lo digo en serio, Papá, ese aguardiente de cacto de Sid va a
hacerte envejecer antes de tiempo.

El hombre que empieza a beber el aguardiente de cacto de Sid, hijo, ya
ha envejecido antes de tiempo"

"Si alguien hubiese entrado y echado un vistazo, si alguien hubiera
visto a todos esos hombres mirando un televisor apagado y una mujer
cincuentona gritando y chillando a sus espaldas algo referente a la
disciplina y el orden y las recriminaciones, habría pensado que todos
estábamos más locos que un rebaño de cabras."

"Veía mi rostro en el espejo, fuerte, moreno, con grandes pómulos
salientes, como si el hueso que había debajo hubiese sido tallado con
un hacha, con unos ojos completamente negros y una mirada dura y
amenazadora, igual que los ojos de Papá y los de todos esos valerosos
indios amenazadores que uno ve en la televisión, y pensaba: ése no soy
yo, ésa no es mi cara. Ni siquiera era yo cuando intentaba parecerme a
esa cara. Ni siquiera entonces era realmente yo mismo; no hacía más
que mostrarme tal como los demás me veían, tal como querían
verme. Creo que nunca he sido yo mismo. ¿Cómo puede McMurphy ser como
es?

"

"En las reuniones de grupo salieron a relucir agravios que llevaban
tanto tiempo enterrados que el motivo que los causara ya había
cambiado"

"—Decidme, por qué. Os peleáis, pasáis semanas enteras comentando cuan
intolerable resulta todo esto, que no podéis soportar a la enfermera
ni nada de lo que hace, ¡y no estáis internados! Lo comprendo en el
caso de algunos tipos de la galería. Están locos. Pero vosotros, tal
vez no seáis exactamente tipos corrientes, pero no estáis locos"

"—Sefelt, ¿y tú? Lo único que te pasa es que tienes algún que otro
ataque. Qué diablos, tengo un tío que cogía unas pataletas mucho
peores que las tuyas y veía terribles visiones con demonios y toda la
historia, pero nunca se le ocurrió encerrarse en un manicomio. Podrías
arreglártelas fuera si tuvieras pelotas...

—¡Eso es!

Es Billy, que se ha apartado de la pantalla, con el rostro bañado en
lágrimas.

—¡Eso es! —grita otra vez—. ¡Si tuviéramos pelotas! Podría salir hoy
mi-mismo, si me atreviera"

"—No, no, escucha. No te doman de ese modo; ¡te atacan por donde no
puedes defenderte! ¡Te meten cosas dentro! Te instalan cosas. En
cuanto comprenden que vas a ser un gran tipo se ponen manos a la obra
y te incorporan sus asquerosos mecanismos desde que eres niño, ¡y no
paran hasta que consiguen programarte"

"—No, amigo, no. Somos orates del hospital que hay aquí cerca,
psico-cerámicas, los cacharros rotos de la humanidad. ¿Quiere que le
descifre un Rorschach?"

"Es posible que no comprendiera por qué seguíamos sin poder reír, pero
sabía que es imposible ser fuerte si se es incapaz de ver el lado
cómico de las cosas. De hecho, se esforzaba tanto por encontrarle ese
lado cómico a la vida que empezaba a preguntarme si estaría ciego a su
otro aspecto, si tal vez era incapaz de comprender por qué la risa se
nos atravesaba en el estómago"

"Les expliqué todo lo que sabía y nadie pareció darle importancia al
hecho de que de pronto estuviera hablando con la gente... un tipo al
que habían dado por sordomudo desde que le conocían y ahora hablaba y
escuchaba como todo el mundo"
