#+title:      capitalismo canalla
#+date:       [2022-11-19 Sat 16:47]
#+filetags:   :resaltados:
#+identifier: 20221119T164702

Capitalismo canalla - César Rendueles (Resaltar: 21; Nota: 0)
------------- "La historia de la modernidad es, en primer lugar, la
crónica de la subordinación de toda nuestra vida social a las
relaciones comerciales" "Un amigo psicólogo me contaba que trataba por
ansiedad a varias cajeras de una sucursal de una conocida cadena de
supermercados. Su supervisor no les permitía ir al baño más que una
vez durante su jornada laboral. El miedo a no aguantar y mearse encima
aumentaba su sensación de incontinencia, así que toda la línea de caja
llevaba pañales" "¿Cuándo la competición mercantil empezó a gobernar
nuestros corazones? ¿Cuándo empezamos a buscar un cielo más azul
observando con detenimiento las novedades de la sección de menaje?"
"El americano típico consagra más de 1600 horas por año a su
automóvil: sentado dentro de él, en marcha o parado, trabajando para
pagarlo, para pagar la gasolina, las llantas, los peajes, el seguro,
las infracciones y los impuestos para las carreteras federales y los
estacionamientos comunales. Le consagra cuatro horas al día en las que
se sirve de él, se ocupa de él o trabaja para él. […] Estas 1600 horas
le sirven para hacer unos 10 000 km de camino, o sea, 6 km en una
hora. Es exactamente lo mismo que alcanzan los hombres en los países
que no tienen industria del transporte. " "En la época heroica del
capitalismo, era habitual que la gente trabajara hasta que reunía algo
de dinero para, a continuación, abandonar el empleo hasta que lo
volvía a necesitar. " "«Todo lo que hace aumentar la abundancia de un
país contribuye a abaratar la mano de obra, donde se maneje bien al
pobre, pues lo mismo que se debe evitar que pase hambre, conviene
impedir que reciba nunca lo bastante para poder ahorrar. […] El
interés de todas la naciones ricas consiste en que la mayor parte de
los hombres no pueda estar desocupados casi nunca y que, sin embargo,
gasten continuamente lo que ganen. […] En una nación libre en la que
no se permite la esclavitud, la riqueza más segura consiste en una
multitud de pobres laboriosos»" "En nuestra sociedades, una fuente
fundamental de alienación es la generalización de un tipo de realidad
laboral que en el pasado solo conocían algunos siervos, que los
antiguos concebían literalmente como una condena: permanecer ocho
horas de pie en silencio vigilando la salida de un supermercado, mover
una manivela en una cadena de montaje… El trabajo se ha contraído en
una experiencia quebrada, un eslabón de una cadena cuyo sentido final
somos incapaces de percibir, tal vez porque no existe." "«El mecanismo
de la esclavitud es el siguiente: no se le conchaba jamás al peón sin
anticiparle una cierta suma que el infeliz gasta en el acto o deja a
su familia. Se firma ante el juez un contrato en el cual consta el
monto del anticipo, estipulándose que el patrón será reembolsado en
trabajo. Una vez arreado a la selva, el peón queda prisionero los doce
o quince años que, como máximo, resistirá a las labores y a las
penalidades que le aguardan. Es un esclavo que se vendió a sí
mismo. Nada le salvará. Se ha calculado de tal modo el anticipo, con
relación a los salarios y a los precios de los víveres y de las ropas
en el yerbal, que el peón, aunque reviente, será siempre deudor de los
patrones. Si trata de huir se le caza. Si no se logra traerle vivo, se
le mata». " "En nuestra sociedad el trabajo es una maldición. La
sociedad, como el Dios del Génesis, castiga con el trabajo, ¿a quién?
A los pobres, porque el único delito social es la miseria. La miseria
se castiga con trabajos forzados. El taller es el presidio. Las
máquinas son los instrumentos de tortura de la inquisición
democrática" "Para mi profundo desagrado, he sido testigo de la más
terrible derrota de la razón y del más enfervorizado triunfo de la
brutalidad de cuantos caben en la crónica del tiempo; nunca, jamás (y
no lo digo con orgullo sino con vergüenza) sufrió una generación tal
hecatombe moral, y desde tamaña altura espiritual, como la que ha
vivido la nuestra" "Por supuesto hay quien sucumbe al nihilismo, como
el Moro, un veronés septuagenario, compañero de Levi en la enfermería
de un campo de refugiados en la Polonia liberada: «En el pecho del
Moro, esquelético y sin embargo potente, bullía sin tregua una cólera
gigantesca e indefinida: una cólera insensata contra todos y contra
todo, contra los rusos y los alemanes, contra Italia y los italianos,
contra Dios y los hombres, contra sí mismo y contra nosotros, contra
el día cuando era día y contra la noche cuando era noche, contra su
destino y todos los destinos»" "La normalidad consumista de la clase
media que surgió al calor del crecimiento económico de la posguerra es
el exoesqueleto de un magma de experiencias turbadoras, algunas
perniciosas, otras esperanzadoras. Las contiene impidiéndonos
afrontarlas y así nos condena a llevar vidas falsas y pequeñas." "«El
consumismo ha destruido cínicamente un mundo “real” transformándolo en
una irrealidad total, en la que ya no hay elección posible entre el
bien y el mal»[129]. " "Por eso cuando en los años setenta el Estado
de bienestar basado en la paz social entre la burguesía y las clases
trabajadoras adictas al consumo se enfrentó a límites económicos,
sociales y organizativos, el neoliberalismo tenía una oferta que mucha
gente no estaba dispuesta a rechazar. Así fue como ocurrió algo
absurdo. Desde 1973 millones de personas de clase trabajadora —primero
en Inglaterra y Estados Unidos, luego en el resto del mundo—
comenzaron a apoyar proyectos de sumisión a las élites económicas que
atentaban contra sus intereses materiales más inmediatos. El
consumismo borró de la memoria colectiva las consecuencias que había
tenido el capitalismo desbocado, la miseria y las decenas de millones
de muertos que dejó a su paso" " «La celda uno» es una historia sobre
el crecimiento moral de un adolescente que reniega del sistema de
corrupción, autoritarismo, consumismo y violencia que domina su país y
del que él mismo, comprende, formaba parte. El maltrato a un honesto
funcionario jubilado le hace comprender la naturaleza de la sumisión
colectiva a la degradación social, política e institucional. Nnamabia
pertenece a una clase media que, como le recuerda el policía a su
madre, ha tratado inútilmente de fingir que sus sueños de prosperidad
se podían preservar en un invernadero universitario mientras todo se
desmoronaba a su alrededor" "Carlos Wieder, el piloto-poeta del
ejército chileno que aparece en Estrella distante, la novela de
Roberto Bolaño. Tras el golpe de Estado del general Pinochet, en 1973,
Wieder organiza una exposición artística con fotografías de los
detenidos a los que ha asesinado. Los militares a los que invita a la
muestra se escandalizan. Pero si un orden social monstruoso te anima a
torturar, matar y hacer desaparecer a miles de jóvenes, ¿a qué tanto
alboroto por ponderar los aspectos estéticos de la represión extrema?"
"Tom Rodgers, fundador del seminario, comienza su exposición mostrando
un bol lleno de avena: «Sencilla, nutritiva y barata. Esto representa
vuestra alma en su estado puro. Vuestra alma el día que
nacisteis. Erais perfectos. Erais felices. Erais buenos». A
continuación, continúa la metáfora: Ahora entra el Concepto Número
Dos: mierda. No os preocupéis, amigos, no utilizo aquí mierda de
verdad. Solo mierda imaginaria. Tendréis que ponerla vosotros,
utilizando la mente. Ahora bien, si llegara alguien y os echara mierda
en vuestra cálida y agradable avena ¿qué diríais? ¿Diríais: «Ah,
genial, gracias, sigue cagándote en mi avena, por favor»? ¿Os parece
que digo una tontería? Un poco sí. Pero ¿sabéis una cosa?, en la vida
real la gente va y se os caga todo el rato en vuestra avena (amigos,
compañeros de trabajo, seres queridos, incluso vuestros hijos, ¡sobre
todo vuestros hijos" "Nuestras almas rejuvenecen ante el
escaparate. Como escribió Nicanor Parra: «Qué le dijo Milton Friedman
/ a los pobrecitos alacalufes? / A comprar a comprar / quel mundo se
vacabar!». " "Nos definimos por la lista de la compra. Todo a nuestro
alrededor está diseñado para que nuestros gustos mediados por el
mercado sean nuestras principales señas de identidad: la tecnología,
la música, la ropa, los viajes, la comida… Nos concebimos como
agregados de preferencias cuyo único fundamento es que han sido
elegidas por nosotros" "Es cierto, la desregulación capitalista que
comenzó en los años ochenta era una bomba de relojería, el equivalente
económico de un proceso tumoral acelerado con anabolizantes
financieros. La cuestión nunca fue si la economía global iba a
implosionar, sino cuándo iba a hacerlo" "Cuidar de los demás no te
hace necesariamente mejor persona, es cierto. Pero nos ayudó a ver que
buena parte de nuestra vida estaba basada en mentiras. No teníamos una
carrera laboral, sino una mierda de trabajo. No vivíamos en un mundo
repleto de excitantes innovaciones culturales, sino que éramos zombis
del mercado del entretenimiento. Los coches, la ropa, los smartphones,
las series, las videoconsolas… no eran más que basura
inminente. Exactamente igual que nuestros contratos"
