#+title:      El arte de ver
#+date:       [2022-11-19 Sat 16:37]
#+filetags:   :resaltados:
#+identifier: 20221119T163700

"Según el eminente físico francés Francoise Arago: "para ver objetos
poco iluminados, se necesita no mirarlos". Por ello, cuando intentamos
encontrar nuestro camino en la oscuridad, no hay que mirar de frente,
pues no se percibirán los objetos oscuros ubicados delante de
nosotros. Pero si llevamos la cabeza primero hacia un lado, y luego
hacia el otro, podrá verse lo que está directamente frente a nosotros,
a través del ángulo de nuestros ojos"

"En cambio, es importante que se realice deliberadamente la sensación
y la percepción sucesiva de las partes más importantes de que el
objeto está compuesto"

"Capacita al observador a formar claros conceptos mentales de lo
visto. En vez de fijar la mirada y quedarse con una vaga imagen"

"El examen analítico puede ser convenientemente aplicado a objetos muy
familiares, como las letras, los números, los anuncios y los rostros
de parientes y amigos."

"La costumbre del desplazamiento constante en pequeña escala, debe ser
cultivada a propósito en todas las ocasiones durante las actividades
diarias cuando es necesaria una visión prolongada y concentrada, tanto
en los objetos vecinos como en los alejados"

"Nuestro objetivo es ver lo más claro posible, y lo lograremos si la
pretensión de contar las características estimula a los ojos y a la
atención para realizar desplazamientos veloces en pequeña escala,
obligando la sucesiva fijación central."

"llegar a ser totalmente conscientes de que vemos mejor sólo una
pequeña porción de lo que estamos observando. "

"Mientras más perfecta sea la visión, más pequeña será la zona que
puede ser vista con máxima claridad"

"Una vez que nos convencemos de estos hechos, y que ha quedado
comprendido que la buena visión sólo es posible cuando los ojos y la
mente hacen incontables actos sucesivos de fijación central, dejaremos
la costumbre de fijar la mirada y de realizar esfuerzos en el intento
de ver"

"No es exageración cuando se dice que "está ciega de rabia"; cuando
por el terror ven "todo negro" o se "les nublan los ojos". En fin, la
zozobra puede alterar de tal modo, que el individuo ya no puede ver ni
oír, exponiéndose a graves accidentes."

"capacidad de la percepción depende de la cantidad y naturaleza de las
experiencias pasadas, así como de nuestra posibilidad de asimilarlas"

"parecer, la memoria trabaja mejor cuando la mente se encuentra en un
estado de relajación dinámica.

"

" El valor de lo que nombramos "mirada analítica", puede aumentarse
añadiendo a estos mecanismos actos deliberados de la memoria. Ver los
objetos como señalamos en un capítulo anterior, desplazando
rápidamente la atención de un punto a otro, siguiendo los contornos y
contando los rasgos más sobresalientes de lo que estamos viendo;
después cerrar los ojos, "dejarse llevar", y evocar las imágenes
mnemónicas de lo que hemos visto. Reabrir los ojos, comparar esta
imagen con la realidad, y repetir el procedimiento. Después de algunas
repeticiones, se producirá una mejoría en la claridad y precisión,
tanto de la imagen mnemónica, como de la imagen visual captada cuando
los ojos están abiertos"

"disociación de la mente y los ojos, frecuentemente causa alteraciones
en la visión, especialmente cuando la persona que medita permanece con
los ojos abiertos, fijando la mirada sin parpadear en ningún momento"

"Si deseadnos meditar y soñar despiertos, debemos cerrar los ojos, y
con esa visión interna seguir conscientemente los episodios inventados
por la imaginación"

"cuando nos entregamos al pensamiento lógico no debemos fijar la
mirada sobre ningún objeto exterior que no tenga relación con el
problema que se intenta evaluar"

"hay que evitar las disociaciones entre la mente y el aparato
sensorial. Si los ojos están abiertos, se debe ser consciente de lo
que se ve. Cuando no se desea ver, sino soñar o pensar, hay que
establecer una relación de los ojos con nuestros sueños o
pensamientos"

"sólo nos ponemos a pensar en el daño que los ojos pueden infligir a
la mente, y la mente a los ojos, cuando la visión es confusa, por el
esfuerzo y los vicios de refracción, y nunca pensamos en las ilusiones
visuales provocadas por la imaginación, ni en los malestares
temporales de la visión causados por inadvertidas explosiones de rabia
o de dolor, ni en las enfermedades de los ojos motivadas por emociones
negativas crónicas.

"

(El Arte De Ver(c.1))
