#+title:      Tropico de Cancer
#+date:       [2022-11-19 Sat 16:38]
#+filetags:   :resaltados:
#+identifier: 20221119T163840

"Siempre tomábamos Pernod, bebida que ponía de buen humor a Collins" -
y en un pernod  mezcló París con Puente Alsina...

"Hay personas que no pueden resistir el deseo de meterse en una jaula
con fieras y dejarse despedazar. Se meten en ella hasta sin revólver
ni látigo. El temor las vuelve temerarias... Para el judío el mundo es
una jaula llena de fieras. La puerta está cerrada y él está dentro sin
látigo ni revólver. Su valor es tan grande, que ni siquiera huele los
excrementos en el rincón. Los espectadores aplauden, pero él no
oye. Según cree, el drama está ocurriendo dentro de la jaula. Piensa
que la jaula es el mundo. Al encontrarse de pie ahí, solo e indefenso,
y con la puerta cerrada, descubre que los leones no entienden su
lengua. Ningún león ha oído hablar nunca de Spinoza. ¿Spinoza? Pero si
ni siquiera pueden hincarle el diente. «¡Dadnos carne!», rugen,
mientras él permanece allí petrificado, con sus ideas congeladas, con
su Weltanschauung, que no es sino un trapecio inalcanzable. Un simple
zarpazo del león y su cosmogonía quedará destrozada.

"

"Dondequiera que voy las personas están echando a perder sus
vidas. Cada cual tiene su tragedia privada. La lleva ya en la sangre:
infortunio, hastío, aflicción, suicidio. La atmósfera está saturada de
desastre, frustración, futilidad. Rascarse y rascarse... hasta que no
quede piel. "

"Pensar que puede acostarse junto a esa brasa que he avivado para él y
no hace otra cosa que orinarse. Hombre, por Dios, deberías
arrodillarte y darme las gracias. ¿Es que no ves que ahora tienes una
mujer en tu casa? ¿Es que no ves que está a punto de estallar? Y tú
diciéndome con esas adenoides tuyas estranguladas: «Bueno, mira, en mi
opinión... hay dos modos de considerar eso...». ¡A tomar por culo con
tus modos de considerar las cosas! "

"«Soy un hombre libre... y necesito mi libertad. Necesito estar
solo. Necesito meditar sobre mi vergüenza y mi desesperación en
soledad; necesito el sol y los adoquines de las calles sin compañía,
sin conversación, cara a cara conmigo mismo, con la compañía exclusiva
de la música de mi corazón. "

"«La vida —dijo Emerson— consiste en lo que un hombre piensa todo el
día»"

"A veces, cuando estoy tomando una taza de té claro en el que ha
echado un pétalo de rosa, se me acerca y se tira un sonoro pedo, en
mis propias narices. Nunca dice: «¡Perdón!». Esa palabra no debe de
figurar en su diccionario gujarati"

"Mientras me pongo los pantalones, oigo de repente una conmoción en la
habitación de al lado. La chica está dando gritos y llamándole cerdo,
cerdo asqueroso. No puedo imaginar lo que ha hecho para merecer
semejante explosión de ira. Me quedo parado, con un pie dentro del
pantalón"

"La patrona está parada junto al bidet, echando chispas. Las chicas
están allí paradas también, con toallas en las manos. Los cinco
estamos allí parados mirando el bidet. Dos enormes chorizos flotan en
el agua. La patrona se inclina y los cubre con una toalla"

"En cierto modo la comprensión de que no había nada que esperar tuvo
un efecto saludable para mí. Durante semanas y meses, durante años,
durante toda mi vida, de hecho, había estado esperando que algo
ocurriera, algún acontecimiento intrínseco que transformase mi vida, y
en aquel momento, inspirado por la desesperanza de todo, sentí como si
me hubieran quitado un gran peso de encima"

"¿Ves ese culo? Danés. ¡Cuánto le gusta el asunto a esa mujer!
Sencillamente, me lo suplica. Ven aquí... mírala ahora, de lado. Mira
ese culo, hazme el favor. Es enorme. Te aseguro que, cuando se me sube
encima, apenas puedo abarcarlo con los brazos. Tapa el mundo
entero. Me hace sentir como una pequeña chinche que se arrastra por su
interior. No sé por qué me gusta tanto... supongo que por ese culo. Es
tan incongruente. ¡Y los pliegues que tiene! No puedes olvidar un culo
así. Es una realidad... es una realidad sólida. Las otras, pueden
aburrirte o pueden darte ilusión por un momento, pero ésta... ¡con su
culo!... ¡hostias!, no puedes olvidarla... es como irse a la cama con
un monumento encima»"

"La visión de los dos acoplados como una pareja de cabras sin la menor
chispa de pasión, moviendo y moviendo las caderas sin otra razón que
los quince francos, borra en mí cualquier vestigio de sentimiento
excepto el inhumano de satisfacer mi curiosidad"

"Nunca he visto un lugar como París en lo que a variedad de viandas
sexuales se refiere. En cuanto una mujer pierde un diente o un ojo o
una pierna, se hace de la vida. En América se moriría de hambre, si no
tuviera otra cosa que ofrecer que una mutilación. Aquí es
diferente. La falta de un diente o la nariz consumida o la matriz
caída, cualquier desgracia que agrave la fealdad natural de la mujer,
parece estar considerada como un atractivo suplementario, un
estimulante para el apetito ahíto del hombre"

"El empapelado con que los hombres de ciencia han cubierto el mundo de
la realidad se cae a jirones"

"Caminas por las calles sabiendo que estás loco, poseído, porque es
más que evidente que esas caras frías, indiferentes, son los rostros
de tus carceleros. Aquí todos los límites se desvanecen y el mundo se
manifiesta como el matadero demencial que es. La noria se extiende
hasta el infinito, las compuertas están cerradas herméticamente, la
lógica corre desenfrenada con su cuchilla ensangrentada y
fulgurante. El aire es frío y está paralizado, el lenguaje es
apocalíptico. No hay indicación de salida en ninguna parte; no hay
otra alternativa que la muerte. Un callejón sin salida en cuyo extremo
hay un patíbulo"

"En todas las estaciones de metro hay calaveras que hacen muecas y te
saludan con un «Défendez-vous contre la syphilis"

"Dondequiera que haya paredes, hay carteles con cangrejos brillantes y
malignos que anuncian la proximidad del cáncer"

"«El hombre que está parado ahí, en la puerta, está a punto de irse a
mear. No va a poder encontrar el camino de vuelta porque tiene la
cabeza mal colocada... Ahora, mirad ese desnudo de ahí... Estaba bien
hasta que empezó a pintar el coño. No sé en qué estaría pensando, pero
lo hizo tan grande, que se le coló el pincel dentro y no pudo volver a
sacarlo»"

"El conductor la llevó a casa así, medio desnuda, y cuando Jimmie la
vio en aquel estado, se puso tan furioso con ella, que cogió el
asentador de la navaja de afeitar y le dio una azotaina que la dejó
baldada, y aquello le gustó, a la muy puta. «¡Dame más!», le
suplicaba, arrodillada como estaba y abrazada a sus piernas. Pero
Jimmie ya estaba harto. «¡Eres una guarra asquerosa!», le dijo y le
dio un puntapié en el vientre que le cortó el aliento... y también sus
desatinos sexuales"

"París es como una puta. Desde lejos parece cautivadora, no puedes
esperar hasta tenerla en los brazos. Y cinco minutos después te
sientes vacío, asqueado de ti mismo. Te sientes burlado"

"Recuerdo que solía decir, refiriéndose a Jackie: «Todo habría ido
bien, si me hubiera ofrecido el coño de vez en cuando»"

"¿Son hombres y mujeres, me pregunto, o son sombras, sombras de
marionetas pendientes de cuerdas invisibles"

"Cuando me asomo a ese coño exhausto de una puta, siento el mundo
entero debajo de mí, un mundo que se tambalea y se desmorona, un mundo
usado y pulido como el cráneo de un leproso"

"Soy uno que se perdió entre la multitud, a quien las luces
chisporroteantes aturdieron, un cero a la izquierda que vio todo lo
que le rodeaba reducido a objeto de burla"

"En un tiempo pensaba que ser humano era el objetivo más alto que
podía tener un hombre, pero ahora veo que estaba destinado a
destruirme. Hoy me siento orgulloso al decir que soy inhumano, que no
pertenezco a los hombres ni a los gobiernos, que no tengo nada que ver
con credos ni principios. No tengo nada que ver con la maquinaria
crujiente de la humanidad: ¡pertenezco a la tierra"

"Si soy inhumano es porque mi mundo ha sobrepasado sus límites
humanos, porque ser humano parece algo pobre, lastimoso, miserable,
limitado por los sentidos, restringido por preceptos morales y
códigos, definido por trivialidades e ismos. Estoy echándome el jugo
de la uva por el gaznate y descubro la sabiduría en él, pero mi
sabiduría no procede de la uva, mi embriaguez no debe nada al vino...

"

"un mundo que produzca éxtasis y no pedos secos"

"amo las palabras de los histéricos y las oraciones que fluyen como la
disentería y reflejan todas las imágenes morbosas del alma"

"me dirigí al despacho del rabino y solicité una entrevista con él. Me
recibió bastante atentamente... hasta que le hice saber el objeto de
mi visita. Entonces se alarmó tremendamente. Sólo le había pedido una
ayudita para mi amigo Joe y para mí. Por la mirada que me echó,
parecía como si le hubiera pedido que me alquilase la sinagoga para
poner una bolera. Para remate, de repente me preguntó a quemarropa si
era judío o no. Cuando respondí que no, pareció profundamente
ultrajado. ¿Por qué —hiciera el favor de decirle— había acudido a un
pastor judío en busca de ayuda? Le dije ingenuamente que siempre había
tenido más fe en los judíos que en los gentiles. Lo dije modestamente,
como si fuera uno de mis defectos particulares. Y, además, era
verdad. Pero no le halagó lo más mínimo. No, señor. Estaba
horrorizado. Para librarse de mí, escribió una nota para los del
Ejército de Salvación. «Ése es el lugar al que debe dirigirse», dijo,
y bruscamente se dio la vuelta para ocuparse de su rebaño"

"Hay algo obsceno en ese amor del pasado que acaba en colas de parados
esperando recibir comida gratis y en refugios subterráneos. Algo
obsceno en esa estafa espiritual que permite a un idiota espolvorear
agua bendita sobre los Grandes Berthas y acorazados y explosivos
instantáneos"

"Cuando mira a su alrededor, después de haber bebido, y nos sonríe, el
mundo parece caerse en pedazos. Es una sonrisa desde el otro lado de
un abismo"

"El fuego se ha apagado. Un silencio tan intenso, que me suena como
las cataratas del Niágara en los oídos"

(Trópico de Cáncer(c.1))
