#+title:      El retorno de los brujos
#+date:       [2022-11-19 Sat 16:37]
#+filetags:   :resaltados:
#+identifier: 20221119T163734

"Es el acto de la recepción del fonógrafo en la Academia de Ciencias
de París: «En cuanto la máquina empieza a emitir algunas palabras, el
señor Secretario Perpetuo se lanza sobre el impostor y le aprieta la
garganta con puño de

hierro. ¡Véanlo ustedes!, les dice a sus colegas. No obstante, para
general asombro, la máquina sigue emitiendo sonidos.»"

"Un inmenso foso separa al hombre de la aventura de la Humanidad, a
nuestras sociedades de nuestra civilización. Vivimos sobre unas ideas,
una moral, una sociología, una filosofía y una psicología que
pertenecen al siglo XIX. Somos nuestros propios bisabuelos"

"La idea de una sociedad internacional y secreta de hombres
intelectualmente muy avanzados, transformados espiritualmente por la
intensidad de su saber, deseosos de defender sus descubrimientos
científicos contra los poderes organizados, contra la curiosidad y la
codicia de otros hombres -reservando para el momento oportuno la
utilización de sus descubrimientos, o enterrándolos por varios años, o
poniendo sólo una pequeña parte en circulación-, esta idea, digo, es a
la vez muy antigua y ultramoderna. "

"buscamos la realidad sin dejarnos dominar por el reflejo condicionado
del hombre moderno (a nuestros ojos retardatario), que vuelve la
espalda en cuanto esta realidad adquiere un aspecto fantástico"

"En nuestro campo, todavía no se acepta lo que se ha acabado por
aceptar de los pintores, de los poetas, de los cineastas, de los
decoradores, etc. La ciencia, la psicología, la sociología, son
bosques tabú"

"Es posible que lo que llamamos esoterismo, cimiento de las sociedades
secretas y de las religiones, sea

el residuo difícilmente comprensible y manejable de un conocimiento
muy antiguo, de naturaleza técnica, que

se aplica a la vez a la materia y al espíritu"

"La ciencia coloca barreras de imposibilidad. El ingeniero, al igual
que el mago ante los ojos del explorador cartesiano, pasa a través de
las barreras, por un fenómeno análogo a lo que los físicos llaman «el
efecto túnel»."

"No existe un solo servicio de investigación científica enfocado hacia
el pasado. Los libros antiguos, si son leídos alguna vez, lo son por
escasos eruditos de formación puramente literaria o histórica. Lo que
contienen de ciencia y de técnica, escapa, pues, a la atención"

"No sabemos nada o casi nada del pasado. Muchos tesoros duermen en las
bibliotecas."

"idea de que ha habido, de pronto, un «siglo délas luces», idea que
hemos aceptado con desconcertante ingenuidad, ha sumido en la
oscuridad"

"según decía Atterbury, contemporáneo de Newton, «que hay más obras
antiguas perdidas que conservadas».

"

"Las democracias modernas se prestan a mil interpretaciones
«esotéricas». Hay pensadores que aseguran que América obedece
únicamente a algunos jefes de la industria, Inglaterra a los banqueros
de la City, Francia a los francmasones, etc. Con los Gobiernos
surgidos de la guerra revolucionaria, el poder se

oculta casi completamente"

"»1.° Quien siente la necesidad de enseñar no vive enteramente su
doctrina y no ha llegado a la cima de la iniciación"

""Hay un camino en la soledad, hay ríos en el desierto." No hay camino
ni ríos en el hombre que se mezcla con los otros."

""Hay un camino en la soledad, hay ríos en el desierto." "

"«Pienso que existieron en el pasado civilizaciones que conocieron la
energía del átomo y que fueron totalmente destruidas por el mal uso de
esta energía.»

"

" El secreto de la alquimia es éste: existe un medio de manipular la
materia y la energía de manera que se produzca lo que los científicos
contemporáneos llamarían un campo de fuerza. Este campo de fuerza
actúa sobre el observador y le coloca en una situación privilegiada
frente al Universo. Desde este punto privilegiado tiene acceso a
realidades que el espacio y el tiempo, la materia y la energía suelen
ocultarnos. Es lo que nosotros llamamos la Gran Obra"

"«Si tienes la desgracia de introducirte cerca de los príncipes y de
los reyes, no cesarán de preguntarte: "Y bien, maestro, ¿cómo va la
Obra? ¿Cuándo veremos por fin algo hueno?" Y, en su impaciencia, te
llamarán pillo y tramposo y te producirán toda suerte de molestias. Y
si no llegas a buen fin, sentirás todo el peso de su cólera. Si, por
el contrario, tienes éxito, te guardarán con ellos en perpetuo
cautiverio, con la intención de hacerte trabajar en su provecho.»"

"un alquimista chino había escrito:

«Sería un terrible pecado revelar a los soldados el secreto de tu
arte. ¡Atención! ¡Que no haya siquiera un insecto en el cuarto en que
trabajas"

"«Está fuera de duda -escribe René Alleau- que las manipulaciones de
la alquimia sirven de soporte a un ascetismo interior"

"La mezcla se coloca en un recipiente transparente, de cristal de
roca, cerrado de una manera especial. No se sabe gran cosa de esta
forma de cierre, llamado de Hermes, o hermético"

"Todo nuestro conocimiento del átomo y del núcleo se basa en el modelo
«saturnino» de Nagaoka y Rutherford: el núcleo y su anillo de
electrones. No es imposible que, en el porvenir, otra teoría nos
conduzca a realizar cambios de estado y separaciones de elementos
químicos inconcebibles en este momento"

"El contacto con los neutrones vuelve radiactivos a todos los
elementos. Las explosiones nucleares experimentales envenenan la
atmósfera del planeta. Este envenenamiento, que progresa en proporción
geométrica, aumentará extraordinariamente el número de niños nacidos
muertos, de cánceres y de leucemias, estropeará las plantas,
trastornará los climas, producirá monstruos, nos romperá los nervios y
nos ahogará. Los Gobiernos, sean totalitarios o demócratas, no
renunciarán. Y no renunciarán, por dos razones. La primera es que la
opinión pública no ha alcanzado el nivel de conciencia planetaria que
se necesita para reaccionar. La segunda es que no hay Gobiernos, sino
sociedades anónimas del capital humano, encargadas, no de hacer
Historia, sino de expresar aspectos diversos de la fatalidad
histórica"

"El conocimiento científico no es objetivo. Es, como la civilización,
una conjuración. Se rechaza un gran número de hechos porque
trastocarían los razonamientos establecidos. Vivimos bajo un régimen
inquisitorial, cuya arma más empleada contra la realidad disconforme
es el desprecio acompañado de risas."

"Habrá, pues, que pedir una adición a las libertades garantizadas por
la Constitución: la libertad de dudar de la ciencia. Libertad de dudar
de la evolución"

"La foca tímida del Bronx se impuso el deber de aprender, en ocho
años, todas las artes y todas las ciencias… y de inventar media docena
para su uso personal. Arrastrado por un delirio enciclopédico, se
entrega a este trabajo gigantesco, que consiste menos en aprender que
en tener conciencia de la totalidad de lo viviente"

"Cuarenta mil notas, distribuidas en mil trescientas secciones,
escritas a lápiz, en cartoncitos minúsculos y en un lenguaje
taquigráfico de su invención. Sobre esta empresa de locura resplandece
el don de considerar cada tema desde el punto de vista de una
inteligencia superior que acaba de enterarse de su existencia"

"Según el método clásico, hay dos clases de hechos: los condenados y
los otros. Por ejemplo, las descripciones de ingenios volantes en
textos antiquísimos, el empleo de fuerzas parapsicológicas entre los
«primitivos» o la presencia de níquel en monedas del año 235
a.C. [32], son hechos condenados. Excluidos. Estudio negado"

"Estamos persuadidos de que, en el estudio de las civilizaciones
pasadas, hay numerosas denegaciones de prueba, exclusiones a priori,
ejecuciones inquisitoriales. Las ciencias humanas han progresado menos
que las ciencias físicas y químicas, y el espíritu positivista del
siglo XIX impera aún como dueño, tanto más exigente cuanto que siente
acercarse la muerte.

"

"La antropología espera su Copérnico"

"lenguaje de los indios hopis de la América Central. Su lengua se
presta más que la nuestra a las ciencias exactas. No se compone de
palabras-verbos y de palabras-nombres, sino de
palabras-acontecimientos, las cuales se adaptan así más estrechamente
al continuo de espacio-tiempo en que sabemos ahora que vivimos. Más
aún, la palabra acontecimiento tiene tres modos: certidumbre,
probabilidad, imaginación"

"es altamente probable que algunos textos considerados como puramente
folklóricos o mitológicos descansasen sobre hechos reales mal
interpretados y mezclados con otros hechos, éstos imaginarios"

"admite la hipótesis de una antigua visita de viajeros
interplanetarios, encuentra, entre los primeros textos introducidos en
la Biblia por los sacerdotes judíos, recuerdos de seres venidos de
fuera, que, como Enoc desaparecían para remontar el cielo en arcos
misteriosos"

"pocos arqueólogos tienen conocimientos científicos y técnicos"

"Copiados indefinidamente, iluminados, alterados, interpretados, no en
función de los conocimientos antiguos, más elevados y completos, sino
del escaso saber de la edad siguiente"

"¿Por qué habría de tenerla Historia el privilegio, sobre todas las
otras ciencias modernas, de poder explicar todos los fenómenos de
manera satisfactoria para la razón?

"

"«La cuestión que se plantea es saber cómo todo esto fue posible en
pleno siglo xx, y en regiones que pasan por ser las más civilizadas
del Universo.»"

(EL RETORNO DE LOS BRUJOS)
