#+title:      Recuerdos del pasado
#+date:       [2022-11-19 Sat 16:38]
#+filetags:   :resaltados:
#+identifier: 20221119T163808

"Hace quinientos años un científico gritó en una corte legal, «El
sentido común debe decirle a cualquiera que la tierra no puede ser una
pelota, si no la gente en la mitad inferior caerían al vacío»"

" «En ningún lugar de la Biblia» afirmó otro, «dice que la Tierra gira
alrededor del Sol. Por lo tanto, esa afirmación ¡es un trabajo del
diablo!»"

"Incluso si los hechos del Antiguo Testamento pudieran ser probados
arqueológicamente en Mesopotamia, esos hechos verificados no serían
prueba de la religión que les concierne. Si las antiguas ciudades,
villas, e inscripciones son encontradas en una región en particular,
se demuestra que la historia de los pueblos que vivieron allí es un
hecho real. Pero no se prueba que el dios de ese pueblo era el único
dios (y no un viajero espacial"

"Si los industriosos trabajadores hubieran alcanzado la extraordinaria
tasa de diez bloques apilados por día, uno arriba de otro, hubieran
armado los 2 600 000 bloques en la magnífica pirámide en alrededor de
250 000 días, 664 años. "

". Nuestro procedimiento de carbono 14 llega hasta 5000 años y más
allá es cada vez menos seguro. Sería deseable un nuevo método basado
en aparatos más modernos"

"¿Por qué los mayas construyeron sus ciudades más antiguas en la
jungla, y no en un río o al lado del mar?"

(Recuerdos del futuro)
