#+title:      cosmos
#+date:       [2022-11-19 Sat 16:33]
#+filetags:   :resaltados:
#+identifier: 20221119T163343

"El cielo nocturno es interesante. Contiene ciertas formas. Podemos
imaginar casi involuntariamente que son figuras"

"Esas figuras no son, por supuesto, una realidad del cielo nocturno;
las ponemos allí nosotros mismos. Cuando éramos un pueblo cazador
veíamos cazadores y perros, osos y mujeres jóvenes"

"Venus tiene casi la misma masa, 20 el mismo tamaño y la misma
densidad que la Tierra. Al ser el planeta más próximo a nosotros,
durante siglos se le ha considerado como hermano de la Tierra. ¿Cómo
es en realidad nuestro planeta hermano? ¿Puede que al estar algo más
cerca del Sol sea un planeta suave, veraniego, un poco más cálido que
la Tierra? ¿Posee cráteres de impacto, o los eliminó a todos la
erosión? ¿Hay volcanes? ¿Montañas? ¿Océanos? ¿Vida?   "

"Cuando contemplamos el planeta en el cielo matutino o vespertino,
estamos viendo la luz del Sol reflejada en las nubes de Venus. "

"La guerra de los mundos de H. G. Wells, escrita en 1897, todavía hoy
conservan su obsesivo poder"

"Percival Lowell fundó un importante observatorio de donde salieron
las más elaboradas declaraciones a favor de la existencia de vida en
Marte"

"astrónomo italiano, Giovanni Schiaparelli, afirmando la existencia de
canali en Marte le conmovió profundamente. Schiaparelli había
informado durante una aproximación máxima de Marte a la Tierra sobre
la presencia de una intrincada red de líneas rectas, sencillas y
dobles, que cruzaban las zonas brillantes del planeta"

"Las observaciones de este tipo no son fáciles. Uno se pasa largas
horas en el telescopio aguantando el frío del alba. Con frecuencia la
visión es pobre y la imagen de Marte se hace borrosa y
distorsionada. Entonces uno debe ignorar lo que ha visto. En ocasiones
la imagen se estabiliza y los rasgos del planeta destellan
momentáneamente, maravillosamente. Hay que recordar entonces lo que se
ha tenido la fortuna de ver y hay que anotarlo cuidadosamente en un
papel. Hay que dejar de lado las ideas preconcebidas y dejar
constancia con una mente abierta de las maravillas de Marte.   "

"Lowell creía que estaba viendo una red, extendida por todo el globo,
de grandes acequias de riego que conducían agua desde los casquetes
polares en fusión a los sedientos habitantes de las ciudades
ecuatoriales"

"El Marte de Lowell tenía muchos rasgos en común con el suroeste de
los Estados Unidos, donde estaba situado el observatorio de Lowell"

"Wallace demostró que Lowell se había equivocado al calcular las
temperaturas medias de Marte; no eran tan suaves como las temperaturas
del Sur de Inglaterra sino que, en todas partes y con poquísimas
excepciones, eran inferiores al punto de congelación del agua. Tenía
que haber un permafrost, una subsuperficie perpetuamente congelada. El
aire era mucho más enrarecido que lo que Lowell había calculado. Los
cráteres debían de ser tan abundantes como en la Luna. Y en cuanto al
agua de los canales:

Cualquier intento de transportar este escaso excedente [de agua] por
medio de canales de gravedad hasta el ecuador y el hemisferio opuesto,
a través de regiones desérticas terribles y expuesta a cielos tan
despejados como los que describe el señor Lowell, tendría que ser obra
de un equipo de locos y no de seres inteligentes. Puede afirmarse con
seguridad que ni una gota de agua escaparía a la evaporación o a la
filtración a menos de cien millas de su lugar de procedencia.

Este análisis físico devastador y en gran parte correcto fue escrito
por Wallace a los ochenta y cuatro años. Su conclusión fue que en
Marte la vida es decir, la existencia de ingenieros civiles
interesados en hidráulica era imposible. No dijo nada sobre los
microorganismos."

"A pesar de la crítica de Wallace, a pesar de que otros astrónomos con
telescopios y lugares de observación tan buenos como los de Lowell no
pudieran encontrar señal alguna de los fabulados canales, la idea que
Lowell tenía de Marte tuvo gran aceptación popular"

"Parece que los canales de Marte se deben a un funcionamiento
defectuoso de la combinación humana mano/ojo/cerebro en condiciones
difíciles de visión (por lo menos de la combinación de algunos
hombres, porque muchos astrónomos observando con instrumentos de igual
calidad en la época de Lowell y después, afirmaron que no había
canales"

"no hay pruebas convincentes para la microbiología en Marte.   "

"¿Estamos basados en el carbono y en el agua porque esos materiales
eran abundantes en la Tierra cuando apareció en ella la vida? ¿Es
posible que la vida en otro lugar en Marte, por ejemplo esté compuesta
de sustancias distintas?   "

"quizás haya cosas vivas que no tienen ningún sistema solvente: una
vida de estado sólido donde en lugar de moléculas flotando hay señales
eléctricas que se propagan.   "

"La exploración de Marte por el Viking constituye una misión de la
mayor importancia histórica; es la primera búsqueda seria de otros
posibles tipos de vida, la primera supervivencia de una nave espacial
funcionando durante más de una hora en cualquier otro planeta"

"el efecto de invernadero y en el albedo"

"si alguna vez se terraforma aquel planeta, será una obra realizada
por hombres cuya residencia permanente y su afiliación planetaria será
Marte. Los marcianos seremos nosotros"

"En los siglos diecisiete y dieciocho se podía viajar de Holanda a
China en un año o dos, el tiempo que se ha tardado en viajar de la
Tierra a Júpiter. 31 Los costes anuales eran, en comparación, más
altos que ahora, pero en ambos casos inferiores al uno por ciento del
correspondiente producto nacional bruto"

"Como bien sabe vuestra Serena Majestad, hace algunos años descubrí en
los cielos muchas cosas que no se habían visto antes de nuestra
época. La novedad de estas cosas, y algunas consecuencias que de ellas
se derivaban en contradicción con las nociones físicas comúnmente
sostenidas por los filósofos académicos, han excitado contra mí a un
no pequeño número de profesores (muchos de ellos eclesiásticos), como
si yo hubiese colocado con mis propias manos esas cosas en el cielo a
fin de trastocar la Naturaleza y de trastocar las ciencias. Parecen
olvidar que el incremento en las verdades estimula la investigación,
la fundación y el desarrollo"

"En la Edad Media, los filósofos cristianos solían decir con gusto que
los cielos difícilmente podían ser infinitos puesto que daban una
vuelta a la tierra cada día, por lo tanto un número infinito de
mundos, o incluso un gran número de ellos (o incluso otro mundo más),
era algo imposible"

"los dos más interiores, lo y Europa, tienen una densidad elevada como
la roca. Los otros dos, Ganímedes y Calisto, tienen una densidad muy
inferior, intermedia entre la roca y el hielo"

"El planeta mayor es una estrella fracasada. Incluso así, sus
temperaturas interiores son lo bastante elevadas para emitir casi el
doble de la energía que recibe del Sol. En la parte infrarrojo del
espectro, podría incluso ser correcta la afirmación de que Júpiter es
una estrella."

"Júpiter y sus lunas son una especie de sistema solar en miniatura
compuesto por mundos diversos y exquisitos que tienen mucho que
enseñarnos.   "

"La materia de todos los satélites y de los mismos planetas pudo estar
al principio distribuida en forma de anillos, que se condensaron y
acumularon formando las actuales lunas y planetas"

"la nave espacial Voyager continuará adelante, penetrará en la
heliopausa a mitades del siglo veintiuno y entrará surcando el océano
del espacio, sin que vuelva a entrar más en otro sistema solar,
destinado a errar por toda la eternidad lejos de las islas estelares y
a completar su primera circunnavegación del centro masivo de la Vía
Láctea dentro de unos cuantos centenares de millones de años."

"la palabra dioses se ha utilizado casi siempre para expresar las
causas ocultas, remotas, desconocidas, de los efectos que presenciaba;
que aplica este término cuando la fuente de lo natural, la fuente de
las causas conocidas, deja de ser visible: tan pronto como pierde el
hilo de estas causas, o tan pronto como su mente se ve incapaz de
seguir la cadena, resuelve la dificultad, da por terminada su
investigación, y lo atribuye a sus dioses…"

"Le llaman el espinazo de la noche, como si el cielo fuera un gran
animal dentro del cual vivimos nosotros. Su explicación hace que la
Vía Láctea sea útil y al mismo tiempo comprensible. Los Kung creen que
la Vía Láctea sostiene la noche; que a no ser por la Vía Láctea,
trozos de oscuridad caerían, rompiéndose, a nuestros pies. Es una idea
elegante.   "

"La religión griega explicaba aquella banda difusa de luz en el cielo
nocturno diciendo que era la leche de Hera que le salió a chorro de su
pecho y atravesó el cielo, leyenda que originó el nombre que los
occidentales utilizamos todavía: la Vía Láctea"

"Casi todos nosotros descendemos de pueblos que respondieron a los
peligros de la existencia inventando historias sobre deidades
impredecibles o malhumoradas"

"fue Jonia el lugar donde nació la ciencia"

"Lo importante no es que la conclusión de Tales fuera correcta o no,
sino el método utilizado: El mundo no fue hecho por los dioses, sino
por la labor de fuerzas materiales en interacción dentro de la
naturaleza. Tales trajo de Babilonia y de Egipto las semillas de las
nuevas ciencias de la astronomía y la geometría, ciencias que
brotarían y crecerían en el suelo fértil de Jonia"

"Resulta que por algún motivo el conocimiento de un sólido llamado
dodecaedro, que tiene por lados a doce pentágonos, pareció peligroso a
los pitagóricos. El sólido estaba relacionado místicamente con el
Cosmos. Los cuatro sólidos regulares restantes fueron identificados de
algún modo con los cuatro “elementos” que en aquel entonces se suponía
que constituían el mundo: tierra, fuego, aire y agua. Pensaron pues
que el quinto sólido regular sólo podía corresponder a la sustancia de
los cuerpos celestiales (este concepto de una quinta esencia ha dado
origen a la palabra quintaesencia)."

"Quizás la ciencia nació muerta en las civilizaciones india, maya y
azteca por motivos idénticos a los de su decadencia en Jonia, la
omnipresencia de la economía esclavista"

"Pitágoras y Platón, al reconocer que el Cosmos es cognoscible y que
hay una estructura matemática subyacente en la naturaleza, hicieron
avanzar mucho la causa de la ciencia. Pero al suprimir los hechos
inquietantes, al creer que había que reservar la ciencia para una
pequeña elite, al expresar su desagrado por la experimentación, al
abrazar el misticismo y aceptar fácilmente las sociedades esclavistas,
hicieron retroceder la empresa del hombre"

"Aristarco fue la primera persona que afirmó que el centro del sistema
planetario está en el Sol y no en la Tierra, que todos los planetas"

"Ésta es la misma idea que asociamos con el nombre de Copérnico, a
quien Galileo llamó restaurador y confirmador, no inventor, de la
hipótesis heliocéntrica"

". La resistencia contra Aristarco y Copérnico, una especie de
egocentrismo en la vida diaria, continúa vivo entre nosotros: todavía
decimos que el Sol se levanta y que el Sol, se pone. Han pasado 2200
años desde Aristarco y nuestro lenguaje todavía pretende que la Tierra
no gira."

"el número total de estrellas en el universo es mayor que todos los
granos de arena de todas las playas del planeta Tierra"

"El zodíaco es una faja de doce constelaciones que parece envolver el
cielo en la zona que recorre aparentemente el Sol a lo largo del
año. La raíz de la palabra es la misma que la de zoo, porque a las
constelaciones zodiacales, como Leo, se han atribuido principalmente
nombres de animales"

"Las dos naves espaciales interestelares Voyager, las máquinas más
rápidas que se hayan lanzado nunca desde la Tierra, se están
desplazando ahora a una diez milésima parte de la velocidad de la
luz. Necesitarían 40.000 años para situarse a la distancia de la
estrella más próxima"

"En un universo lleno de estrellas que salían proyectadas en todas
direcciones no había lugar alguno que estuviera en reposo, ninguna
estructura desde la cual contemplar el universo que fuera superior a
otra estructura cualquiera. Éste es el significado de la palabra
relatividad"

"Los átomos son en su mayor parte espacio vacío. La materia se compone
principalmente de nada"

"El matemático norteamericano Edward Kasner pidió en una ocasión a su
sobrino de nueve años que inventara un nombre para un número muy
grande: diez elevado a cien (10100), un uno seguido por cien ceros. El
niño le llamó un gugol"

"Los físicos proponen actualmente que las llamadas partículas
elementales como los protones y los neutrones están compuestas en
realidad por partículas más elementales, llamadas quarks, que se
presentan en una variedad de colores y de sabores, tal como se han
denominado sus propiedades en un conmovedor intento por hacer algo más
familiar el mundo subnuclear"

"¿Llegaremos alguna vez al final en nuestra comprensión de la
naturaleza de la materia, o hay una regresión infinita hacia
partículas cada vez más fundamentales? Éste es uno de los grandes
problemas sin resolver de la ciencia"

"El fuego no está compuesto en absoluto de elementos químicos. Es un
plasma radiante en el cual la alta temperatura ha arrancado algunos de
los electrones de sus núcleos"

"Ninguno de los cuatro antiguos elementos jonios y alquímicos es un
elemento en el sentido moderno: uno es una molécula, dos son mezclas
de moléculas, y el último es un plasma.   "

"El neutrón no se descubrió hasta 1932. La física y la química
modernas han reducido la complejidad del mundo sensible a una
simplicidad asombrosa: tres unidades reunidas de maneras distintas lo
forman esencialmente todo"

"El Sol no es exactamente una piedra al rojo vivo, como pensó
Anaxágoras, sino una gran bola gaseosa de hidrógeno y de helio, que
brilla por su elevada temperatura, del mismo modo que un atizador
brilla si se le pone al rojo"

"el interior oculto del Sol donde se genera la luz solar está a 40
millones de grados"

"Cuando este Sol rubicundo e hinchado se haya convertido en un gigante
rojo envolverá y devorará a los planetas Mercurio y Venus, y
probablemente también a la Tierra. El sistema solar interior residirá
entonces dentro el Sol"

" El nitrógeno de nuestro ADN, el calcio de nuestros dientes, el
hierro de nuestra sangre, el carbono de nuestras tartas de manzana se
hicieron en los interiores de estrellas en proceso de colapso. Estamos
hechos, pues, de sustancia estelar"

"Algunos necios declaran que un Creador hizo el mundo. La doctrina de
que el mundo fue creado es equivocada y hay que rechazarla.

Si Dios creó el mundo, ¿dónde estaba Él antes de la creación?… ¿Cómo
pudo haber hecho Dios el mundo sin materiales? Si dices que los hizo
primero y luego hizo el mundo te enfrentas con una regresión infinita…


Has de saber que el mundo es increado, como el mismo tiempo, sin
principio ni fin. Y que se basa en los principios…

Mahapurana (La Gran Leyenda), Jinasena,

India, siglo noveno  "

"Nuestra idea de las galaxias como cuerpos rígidos y pesados está
equivocada. Son estructuras fluidas con 100.000 millones de
componentes estelares."

"En cada explosión de quasar pueden quedar totalmente destruidos
millones de mundos, algunos con vida y con inteligencia para
comprender lo que está sucediendo. El estudio de las galaxias revela
un orden y una belleza universales. También nos muestra una violencia
caótica a una escala hasta ahora insospechada"

"Un objeto que se nos acerca a velocidades muy altas se nos presenta
con el color de sus líneas espectrales desplazadas hacia el azul. Un
objeto que se aleja a velocidades muy altas tiene sus líneas
espectrales desplazadas hacia el rojo. 65 Este desplazamiento hacia el
rojo, observado en las líneas espectrales de galaxias distantes e
interpretado de acuerdo con el efecto Doppler, es la clave de la
cosmología"

" Hay en esta religión el concepto profundo y atrayente de que el
universo no es más que el sueño de un dios que después de cien años de
Brahma se disuelve en un sueño sin sueños. El universo se disuelve con
él hasta que después de otro siglo de Brahma, se remueve, se recompone
y empieza de nuevo a soñar el gran sueño cósmico. Mientras tanto, y en
otras partes, hay un número infinito de otros universos, cada uno con
su propio dios soñando el sueño cósmico. Estas grandes ideas están
atemperadas por otra quizás más grande todavía. Se dice que quizás los
hombres no son los sueños de los dioses, sino que los dioses son los
sueños de los hombres"

"Si hay menos de una cierta cantidad crítica de materia en el
universo, la gravitación de las galaxias en recesión será insuficiente
para detener la expansión, y el universo continuará su fuga para
siempre. Pero si hay más materia de la que podemos ver escondida por
ejemplo en agujeros negros o en gas caliente pero invisible entre las
galaxias el universo se mantendrá unido gravitatoriamente y sufrirá
una sucesión muy india de ciclos, una expansión seguida por una
contracción, universo sobre universos, Cosmos sin fin. Si vivimos en
un universo oscilatorio de este tipo, el big bang"

"Cada uno de nosotros tiene quizás un centenar de miles de millones de
neuronas, cifra comparable al número de estrellas en la galaxia Vía
Láctea. Muchas neuronas tienen miles de conexiones con sus
vecinas. Hay aproximadamente cien billones, 1014, de estas conexiones
en la corteza del cerebro humano"

"Un libro se hace a partir de un árbol. Es un conjunto de partes
planas y flexibles (llamadas todavía hojas ) impresas con signos de
pigmentación oscura. Basta echarle un vistazo para oír la voz de otra
persona que quizás murió hace miles de años. El autor habla a través
de los milenios de modo claro y silencioso, dentro de nuestra cabeza,
directamente a nosotros"

"Utilizamos una aritmética de base diez únicamente porque tenemos diez
dedos en nuestras manos"

"Mientras nuestros estudios se limiten a una o dos líneas evolutivas
en un único planeta, continuaremos ignorando la gama y esplendor
posibles de otras inteligencias y de otras civilizaciones"

"Hoy en día hay un vasto tráfico de comunicaciones internacionales por
radio, televisión y radar. En algunas frecuencias de radio la Tierra
se ha convertido con mucho en el objeto más brillante, la fuente de
radio más potente del sistema solar, más brillante que Júpiter, más
brillante que el Sol"

"En general la fuente más difundida y perceptible de transmisiones de
radio procedentes de la Tierra son nuestros programas de
televisión. Puesto que la Tierra gira, algunas emisoras de televisión"

"Es imposible hacer regresar estos programas de televisión"

"La transmisión en gran escala de programas de televisión en el
planeta Tierra no se inició hasta fines de los años 1940. Por lo tanto
hay un frente de onda esférico centrado en la Tierra que se expande a
la velocidad de la luz "

"el disco Voyager está viajando hacia el exterior del sistema
solar. La erosión en el espacio interestelar debida principalmente a
rayos cósmicos y a los impactos de granos de polvo es tan lenta que la
información en el disco durará mil millones de años"

"Una transmisión de televisión que acaba de estar ahora mismo en el
aire, en unas cuantas horas dará alcance a la nave espacial Voyager en
la región de Saturno,"

"En nuestra existencia sobre este planeta hemos acumulado un peligroso
equipaje evolutivo, propensiones hereditarias a la agresión y al
ritual, sumisión a los líderes y hostilidad hacia los forasteros, un
equipaje que plantea algunas dudas sobre nuestra supervivencia"

"Pero nuestras energías se dirigen mucho más hacia la guerra. Las
naciones, hipnotizadas por la desconfianza mutua, sin casi nunca
preocuparse por la especie o por el planeta, se preparan para la
muerte. Y lo que hacemos es tan horroroso que tendemos a no pensar
mucho en ello. Pero es imposible que resolvamos algo que no tomamos en
consideración"

"En un intercambio nuclear completo, en el paroxismo de la guerra
termonuclear, caerían en todo el mundo el equivalente a un millón de
bombas de Hiroshima"

"Prescott cree que las culturas con predisposición a la violencia
están compuestas por individuos a los que se ha privado de los
placeres del cuerpo durante por lo menos una de las dos fases críticas
de la vida, la infancia y la adolescencia. Allí donde se fomenta el
cariño fisico, son apenas visibles el robo, la religión organizada y
las ostentaciones envidiosas de riqueza; donde se castiga fisicamente
a los niños tiende a haber esclavitud, homicidios frecuentes, torturas
y mutilaciones de los enemigos, cultivo de la inferioridad de la
mujer, y la creencia en uno o más seres sobrenaturales que intervienen
en la vida diaria"

"Los mismos cohetes impulsores utilizados para lanzar sondas a los
planetas están instalados y a punto para enviar cabezas de guerra
nucleares a las naciones"

(Cosmos)
