#+title:      viejo muere el cisne
#+date:       [2022-11-19 Sat 16:46]
#+filetags:   :resaltados:
#+identifier: 20221119T164634

Williams, John - Stoner [11580] (r1.1).epub (Resaltar: 34; Nota: 0)

-------------

"Admonitorio tal vez, o tal vez, y era lo más probable, puramente sin
sentido, mera retahíla narrada por un idiota"

"¡Y qué de hechos raros, de hechos esencialmente excéntricos! ¿Qué
era, por ejemplo, lo que hacia a una chicharra vivir tanto como un
toro, o un canario sobrevivir a tres generaciones de ovejas? ¿Por qué
los perros habían de hallarse en la edad senil a los catorce años y
los loros a los ciento en la flor de la edad? ¿Por qué las hembras
humanas eran estériles a los cuarenta y los cocodrilos hembras
continuaban poniendo huevos a los tres siglos? Por qué, en nombre del
cielo, a un sollo le era dable vivir doscientos años sin mostrar
señales de senilidad, mientras que el pobre Jo Stoyte"

"La pobreza y el sufrimiento ennoblecen sólo cuando son
voluntarios. La pobreza y el sufrimiento involuntarios hacen a los
hombres peores. Más fácil es a un camello pasar por el ojo de una
aguja que al hombre involuntariamente pobre entrar en el reino de los
cielos"

"A la gente gorda se la suele suponer tan feliz."

"y una semana sí y otra no, entre las cinco y seis y media de la
tarde, horita y media con Maruja o Dorita en su pisito de Maida Vale"

"Cuanto más largamente se vive, tanto más en contacto con el mal se
pone uno, automáticamente. Nadie se pone automáticamente en contacto
con el bien. El hombre no logra mayor bien meramente por el hecho de
durar más"

"incluso las aplicaciones de la ciencia menos destructivas, no son
mucho más satisfactorias en este sentido. Porque, ¿a qué conducen
tales aplicaciones? A la multiplicación de objetos poseíbles; a la
invención de nuevos instrumentos de estímulo; a la diseminación de
nuevas necesidades por medios de propaganda que sólo tienen por objeto
equiparar las posesiones con el bienestar y el incesante estímulo con
la felicidad. Pero he ahí que el incesante estímulo exterior es una de
las causas de esclavitud; y asimismo lo es la preocupación por
adquirir posesiones. Y ahora nos amenaza usted con prolongarnos la
vida para que sigamos sintiéndonos estimulados, deseando posesiones,
ondeando banderas"

"Cínico, ha de ser uno cínico, Pedro. Cínico especialmente acerca de
toda acción o sentimiento que se nos ha enseñado a considerar como
bueno. La"

"Los escribas y fariseos, en último análisis, no son en nada mejores
que los publicanos y pecadores. A menudo son en realidad mucho
peores. Y esto por diversas razones. Gozando de la buena opinión de
los demás, adquieren una buena opinión de sí mismos, y nada hay que
confirme tan eficazmente el egotismo como la propia buena opinión"

"En el nivel inferior existe el bien en el adecuado funcionamiento del
organismo de acuerdo con las leyes de su propia experiencia. En el
nivel superior existe en la forma de un conocimiento del mundo carente
de deseos y aversiones; existe en la experiencia de la eternidad, en
la trascendencia de la personalidad, en la extensión de la conciencia
allende los límites impuestos por el ego. La actividad estrictamente
humana es la actividad que impide la manifestación del bien en los
otros dos planos o niveles"

"Obsesos con el tiempo y nuestro ego vivimos en constante ansia y
preocupación"

"Ora directa, ora indirectamente, la mayoría de nuestras dolencias e
impedimentos físicos se deben a nuestras inquietudes y ansiedades"

"Nos inquietamos y ansiamos hasta aumentar la presión sanguínea,
enfermar del corazón, contraer tuberculosis, adquirir úlcera gástrica,
perder la resistencia contra las infecciones o caer en la neurastenia,
la aberración sexual, la locura, el suicidio"

"0, yéndose más por lo bajo, se puede vivir en el idiótico mundo del
homme moyen sensuel; el mundo cuyas incoherencias estriban en
periódicos y fútbol, sexo y preocupaciones, anuncios y dinero,
halitosis y mantener las relaciones con los Jones"

"Luego de un tiempo se cansan de su mundo sin tema. Sienten la
necesidad de concentrarse en algo y orientarse hacia algo. Desean dar
sentido a su vida. Entonces es cuando se convierten al comunismo, o
ingresan en la iglesia apostólica romana, o se unen al movimiento de
Oxford. Cualquier cosa con tal de tener un tema"

"El sufrimiento mental, la negra noche del alma: se regodea en ello
realmente"

"En la página primera me encuentro con esto: «Lord Chesterfield
escribe a su hijo que un caballero jamás habla a su lacayo, ni
siquiera a un mendigo en la calle, d'un ton brusque, sino que "corrige
al uno fríamente y aparta al otro con humanidad...". Su señoría
debiera haber agregado que existe un arte mediante el cual tal
frialdad se torna más formidable que la cólera y tal humanidad más
ofensiva que el insulto"

"Los hombres y las mujeres tratan de continuo de perder la vida, vida
gastada, improductiva y carente de sentido de su ordinaria
personalidad. Siempre están procurando perderla, y en millares de
diferentes formas. En los frenesíes del juego y la predicación
religiosa; en las monomanías de la avaricia y la perversión, de la
investigación, del sectarismo y de la ambición; en las locuras
compensadoras del alcohol, de la lectura, del soñar despierto, de la
morfina; en las alucinaciones del opio, del cinematógrafo y del rito
en las salvajes epilepsias del entusiasmo político y del placer
erótico; en el estupor del veronal y de la enervación. Escapar;
olvidar la vieja y tediosa identidad; convertirse en algún otro, en
algo mejor, en alguna otra cosa: mero cuerpo extrañamente adormecido o
hiperestésico; o bien tan sólo entrar en un estado de mente
impersonal, en una a modo de conciencia no individualizada"

"Julio de 1780", leyó. "La sensualidad va íntimamente aliada con el
pesar, y sucede a veces que, a consecuencia de la mismísima sinceridad
de su aflicción, la contristada viuda se ve traicionada por sus
sentimientos y es incapaz de resistir a las importunidades del huésped
funeral, que conoce el arte de pasar imperceptiblemente de la
condolencia a la familiaridad. Yo mismo he hecho cornudos póstumamente
a un duque y dos vizcondes"

"11 de enero de 1788. Tal día como hoy, hace cincuenta años, vine al
mundo. De la soledad uterina surgimos a la soledad entre nuestros
semejantes, para volver luego a la soledad de la tumba. Pasamos la
vida esforzándonos por mitigar tal soledad. Pero propincuidad no
significa nunca fusión. La ciudad más populosa no es sino una
aglomeración de soledades. Intercambiamos palabras, pero las
intercambiamos de prisión a prisión, y sin que tengamos la esperanza
de que signifiquen para los demás lo que para nosotros significan. Nos
casamos para tener en casa dos soledades en vez de una; engendramos
hijos y las soledades aumentan de número. Reiteramos el acto amoroso;
pero aquí una vez más, propincuidad jamás significa fusión. El más
íntimo de los contactos sólo lo es de superficies, y copulamos del
mismo modo que he visto copular con las rameras a los condenados
prisioneros en Newgate, por entre los barrotes de nuestras
prisiones. "

"La verdad de la soledad es la misma en todos los hombres, sin posible
mitigación que no sea por el olvido, la estupidez o la ilusión; pero
la sensación de soledad de un hombre es proporcional a la sensación y
realidad de su poder"

"Por cada riesgo a que se expone el general, el soldado raso se expone
a ciento; y por cada guinea que gana el último, gana el primero un
centenar"

"En tercer lugar puede elegir el camino del hombre sensato, el cual,
conociendo su innata bajeza aprende por ello a emplearla, y por el
conocimiento se eleva sobre ella y sobre sus más insensatos
semejantes. Por mi parte he preferido ser un hombre de sentido"

"El mundo es un espejo que refleja la imagen de quien lo contempla"

"de los enormes defectos de que adolece la llamada buena literatura;
acepta la escala convencional de valores; respeta el poder y la
posición social; rinde admiración al éxito; trata como cosa razonable
las principales monomanías de estadistas, amantes, negociantes,
oportunistas sociales y padres de familia. En una palabra, toma con la
misma seriedad las causas del sufrimiento que el sufrimiento
mismo. Ayuda a perpetuar la miseria con la aprobación explícita o
implícita de pensamientos, sentimientas y prácticas que no pueden por
menos de abocar en la miseria. Y esta aprobación se ofrece en el más
magnífico y persuasivo de los lenguajes"

"Todo lo demás deja de ser instintivo y se produce en el nivel
estrictamente humano de la conciencia de sí. Incluso cuando los
hombres se imaginan ser sexualmente de lo más exclusivamente animal,
siguen manteniéndose en el nivel humano. Lo que equivale a decir que
son aún conscientes de sí y se mantienen bajo el influjo de las
palabras; que donde existen las palabras, existen por necesidad
recuerdos y deseos, juicios e imaginaciones. Existen inevitablemente
lo pasado y lo futuro, lo actual y lo fantástico; pesar y expectación;
lo fidedigno y lo ignominioso; la fealdad y la belleza. Aun los actos
de erotismo más bestiales en apariencia entre los hombres y las
mujeres se encuentran asociados con algunos de esos factores no
animales, o con todos ellos; factores que han sido inyectados en toda
situación humana por la existencia del lenguaje"

"El hombre no vive sólo de pan; pero si se empeña en nutrirse la mente
con un mal género de alimento espiritual, no logrará ni siquiera
pan. No lo logrará, porque se encontrará atareado en matar a sus"

"Se construirán un bello mundo verbal en el que todas sus villanías
aparezcan como justas y razonables"

"Las elecciones no son otra cosa que una representación de títeres
gratuita, ofrecida por los que gobiernan a los gobernados, con el fin
de distraer su atención"

"La humanidad de las personas es inversamente proporcional a su
número. Una muchedumbre no tiene de humano más de lo que tiene un alud
o un ciclón. Una chusma formada por seres humanos se halla situada en
un lugar de la escala intelectual y moral inferior al de una piara de
puercos o una manada de chacales"

"La locura estriba, por ejemplo, en creerse a sí mismo un alma, una
entidad humana coherente y permanente"

"Mas entre el animal que se extiende por debajo y el espíritu que se
extiende por encima, en el nivel humano nada hay más que un enjambre
de constelados impulsos, sentimientos y nociones; enjambre compuesto
de pensamientos y deseos incongruentes y, a menudo,
contradictorios. La memoria y el cuerpo lentamente cambiante
constituyen una especie de jaula, espacio temporal en que el enjambre
se encuentra encerrado. Considerarlo como si fuera un "alma" coherente
y permanente es una locura"

"Nuestras "almas" tienen tan poco de "nosotros" que ni siquiera nos es
posible formar la más remota idea de cómo "nosotros" reaccionaríamos
ante el universo si no conociéramos idioma alguno, o incluso, si sólo
desconociéramos el nuestro propio y particular"

"Dejad que la eternidad se ofrezca en la experiencia, permitid que
Dios se manifieste lo bastante a menudo en ausencia de deseos,
sentimientos y preocupaciones humanas: el resultado será la
transformación de la vida que es menester vivir en los intervalos, en
el nivel humano"
