#+title:      confianza total
#+date:       [2022-11-19 Sat 16:44]
#+filetags:   :resaltados:
#+identifier: 20221119T164404

"La postura de la víctima socava nuestra confianza y nuestra capacidad
para enfrentar desafíos y resolver problemas. Al ser «víctimas» de
circunstancias que no podemos cambiar, nos restamos poder, pues si no
somos parte del problema, tampoco podemos ser parte de la solución. Y
si no somos capaces de crear una solución, podemos perpetuar el
problema durante años" (negocio en casa - víctima - catarsis

2/ mi aporte al fracaso del negocio)

"«las personas podrán olvidar lo que les dijimos, podrán olvidar lo
que les hicimos… pero jamás olvidarán cómo las hicimos sentir»" (venta
ih)

"La confianza es lo que tenemos —o nos falta— cuando las cosas salen
mal, cuando el plan falla, cuando nuestra barca se sacude en la
tempestad. La confianza, ese tesoro con el que todos queremos contar
para alcanzar nuestros sueños, se construye desde el paradigma del
amor y se destruye desde el paradigma del miedo"

"de poner los ojos en la meta y no en los obstáculos. Hablamos de
perseverar. Hablamos de poner amor en nuestras acciones, en nuestras
intenciones, en nuestro trabajo, en nuestros vínculos. Cuando hablamos
del amor, hablamos de salud y de vida"

"El miedo está siempre dispuesto a ver las cosas peores de lo que son.

TITO LIVIO"

"Posibilita que prioricemos las relaciones, al recordar que no hay una
sola verdad, sino diferentes miradas y desde allí hallar un punto de
encuentro."

"la rigidez nos hace juzgar con dureza excesiva a los demás y a
nosotros mismos, nos obstruye la comprensión, nos hace ver la vida
desde una dimensión pequeña, donde la única verdad que existe es la
nuestra. Nos convierte en dogmáticos pregonando verdades absolutas,
nos acerca a la arrogancia y nos aleja de los demás"

"La desmotivación es un área bien compleja con muchas variables pero,
indudablemente, nos trae esa falta de energía que disminuye nuestra
capacidad para tomar riesgos o de enfrentar desafíos"

"nivel de motivación está directamente relacionado con el nivel de
expectativas que una persona tiene. Si las expectativas son altas, el
nivel de motivación es alto. A expectativas bajas, motivación baja"

"nosotros podemos motivarnos o desmotivarnos con nuestra conversación
interna. Las palabras tienen poder, sobre todo las que nos decimos a
nosotros mismos"

"«burnout laboral», que es el estado de agotamiento o fatiga que
atraviesan generalmente las personas más comprometidas con el trabajo,
como consecuencia de un exceso de responsabilidades laborales y falta
de equilibrio con otras áreas de la vida"

"Epicteto, el renombrado filósofo greco-romano que vivió en el siglo
I, dijo: «No podemos elegir nuestras circunstancias, pero siempre
podemos elegir la forma en que respondemos ante ellas»"

"H (hecho) = R (reacción)

Éste es un modelo de estímulo-respuesta que no sirve para analizar el
comportamiento humano, pues deja fuera de la ecuación el elemento más
importante: la capacidad del hombre de elegir cómo responder, es
decir, qué pensar y qué sentir frente a cada cosa que le sucede. ¿Qué
tal, entonces, si reformulamos la ecuación anterior?

H (Hecho) + R (respuesta/interpretación) = R (resultado)"

"el problema es que nosotros, como primates muy sofisticados que
somos, podemos iniciar exactamente el mismo proceso de respuesta al
estrés a raíz de un estado psicológico, de un recuerdo, una
experiencia, una emoción, pensando en algo que puede ocurrir dentro de
treinta años o que tal vez no ocurra nunca, pero iniciamos la misma
respuesta al estrés. El meollo de la cuestión es que desencadenar este
proceso durante tres minutos para salvar la vida es perfecto, pero si
lo haces de forma sistemática, por razones psicológicas, aumenta las
posibilidades de enfermar»"

"Para contrarrestar el miedo, podemos usar una estrategia poderosa,
llamada visualización"

"Jean Claude Killy, varias veces campeón olímpico, fue un esquiador
muy famoso en la década del sesenta. En una oportunidad se lastimó una
pierna justo antes de una carrera muy importante que le impidió
practicar en la pista. Sin embargo, llegó el día de la carrera y, sin
entrenamiento físico previo, Killy ganó. Cuando le preguntaron cómo lo
había logrado, él respondió que, como no le quedaba otra opción, lo
único que hizo fue visualizar con detalle cada centímetro de la
bajada. De esa manera ensayó cada uno de movimientos en su mente, una
y otra vez… ¡Y ganó la competencia"

"Visualizar la situación deseada en lugar de la temida es un excelente
ejercicio para hacer antes de tener una conversación difícil con
alguien; previo a una negociación; antes de una reunión, de un examen,
de una competencia… Antes de cualquier situación que plantee algún
tipo de desafío"

"Cuando le preguntaron cómo había logrado ganar si no había tocado el
piano en los últimos siete años, Liu respondió que durante todo el
tiempo que estuvo, cada uno de los días, practicó en su mente todos
los temas que alguna vez había tocado en su piano"

"Para nuestra mente no existen diferencias sustanciales entre algo
real y algo imaginado vívidamente, por eso la visualización
correctamente realizada —con detalles, incluyendo emociones— es tan
efectiva"

"Si mi mente está centrada en comprar un coche nuevo, es muy posible
que, cuando salga a la calle, de pronto aparezcan en mi campo visual
muchos coches de la marca que estoy buscando. Si nuestra mente está
cargada de las imágenes del resultado deseado, es muy posible que lo
alcancemos, pues aparecerán a nuestro alrededor muchas posibilidades
que no serían percibidas de otra forma"

"Si las imágenes que comienzan a aparecer son negativas,
cancélalas. Puedes trazar una cruz en esa imagen, y comenzar de nuevo,
hasta lograr la imagen deseada…"

"Empieza por hacer lo necesario, luego haz lo posible y de pronto
estarás logrando lo imposible"

"Muchas veces confundimos lo que somos con lo que hacemos o
tenemos. Es fácil caer en la trampa de creer: «Yo soy mi profesión»,
«Yo soy mi casa», «Yo soy mi empresa»"

"a medida que logramos liberarnos de las identificaciones que nos
limitan, nos damos permiso para responder a cada momento
existencial. Dejamos de creer que «somos» nuestras posesiones,
nuestros logros, nuestros roles, y descubrimos el «Yo soy yo». Nos
movemos espiritualmente a medida que soltamos ese apego a lo que
pensamos que somos. Al soltar, trascendemos nuestro ego, descubrimos
nuestro ser"

"en la mente los miedos se acrecientan, pero cuando son expresados
oralmente, automáticamente disminuyen"

"Hasta que no nos comprometemos, hay vacilación; existe la posibilidad
de retroceder; nos domina la inefectividad. Muchas veces la ayuda
vendrá de lo inesperado, pero sólo si estamos comprometidos."

"Si queremos formar emprendedores de verdad, necesitamos desarrollar
en nuestras escuelas y universidades programas que involucren la
educación emocional de los alumnos; que fomenten la cooperación, la
conciencia social, el compromiso y la perseverancia"

"Vivir sin miedo no se trata de no sentir temores, sino de sentirlos
sin permitir que nos detengan"

"La música barroca es ideal para el aprendizaje. Lo favorece y
acelera. Buscando crear una forma matemática ideal y armónica,
compositores barrocos como Albinoni, Haendel, Vivaldi, Corelli,
Telemann, Pachelbel, produjeron la frecuencia exacta que armoniza el
cerebro para alcanzar un estado de «alerta relajado»"

"Numerosas investigaciones, como las de Alfred Tomatis, dan cuenta de
los efectos positivos de la música de Mozart. Se ha comprobado que las
pulsaciones por minuto que tiene la música de Mozart cambian el estado
del cerebro haciéndolo más receptivo. Se dice que alcanza con escuchar
10 minutos de su música para producir un cambio"

"Entre ellos, en ese momento, algo se quebró: la confianza"

"La confianza entre las personas se sustenta a partir del cumplimiento
de las promesas"

"La confianza entre las personas se sustenta a partir del cumplimiento
de las promesas, del soporte de la integridad individual y del nivel
de responsabilidad con el que se asumen los vínculos."

"No hay ningún misterio en cómo se crea la confianza. Es una cuestión
de congruencia entre palabras y actos. Una persona dice la
verdad. Mantiene sus promesas. Respeta los compromisos. Actúa de
acuerdo con los valores que profesa."

"Hemos visto que hasta una persona de 89 años puede crear nuevos
hábitos para vivir mejor"

"Covey presenta un estudio que indica que sólo un 8% de las personas
cumple con sus «resoluciones de año nuevo»"

"Cuando alguien vive, trabaja y se relaciona con los demás desde una
postura de responsabilidad, más allá de su desempeño o de los
resultados que logre, los demás le creen y lo respetan"

"La integridad es la coherencia entre pensar, decir y hacer"

"La integridad es un pilar fundamental de la confianza. Es muy
importante descartar como recurso las mentiras, por más pequeñas que
sean e inofensivas que parezcan"

"La confianza es la convicción de que seremos capaces de enfrentar los
retos que nos plantee la vida"

"En general, solemos dar por sentado nuestros logros y nos dedicamos
especialmente a observar y criticar lo que hacemos mal"

"Porque tendemos a ver nuestras partes oscuras y a olvidar nuestras
zonas de esplendor"

"arribó a la conclusión de que el indicador que anticipa con mayor
seguridad el nivel de satisfacción de la vida de una persona es su
nivel de satisfacción consigo misma"

"a la hora de averiguar si una persona es dichosa, no ayuda conocer su
estado civil, su nivel de ingresos, si es bella o si tiene título
universitario. La mejor pista para saber si es feliz es descubrir «en
qué medida goza de una alta, saludable y constructiva autovaloración
de sí misma»"

"En su dibujo inicial, que mostramos en nuestra película Confianza
Total, Emilio se dibujó completamente tapado, con una máscara, casco,
guantes, su cuerpo bajo el agua y sin colores. El comentario que
escribió sobre su persona fue: «Estoy en el mar». Menos de 3 meses
después, me estremecí al ver su dibujo final: esta vez tenía la cara
descubierta y sonriente, los ojos vivaces, ropa de colores y los
brazos abiertos… Han pasado veinte años de ese momento y aún recuerdo
las lágrimas corriendo por mi rostro al leer la frase que Emilio
escribió sobre su persona al final del proyecto: «Descubrí que soy
normal, aprendí que soy único»"

"La autoestima, ese sentimiento de valoración que hacemos sobre
nosotros mismos, impacta en todos los órdenes de nuestra vida"

"Nuestra autoestima comienza el día en que decidimos aceptarnos tal
cual somos, cuando elegimos ser nosotros mismos con el propósito de
tomar nuestra vida en nuestras manos"

"Cuando entendemos que nunca existió y nunca habrá de existir nadie
igual a mí, dejo de compararme con los demás, dejo de querer ser otra,
y estoy lista para emprender la verdadera aventura: descubrir quién
soy yo"

"conocernos en profundidad"

"puedo descartar lo inapropiado, conservar lo bueno e inventar algo
nuevo que supla lo descartado"

" si yo tengo una imagen de mí pobre como deportista pero el deporte
no me resulta algo importante, esto no va a afectar demasiado mi
autoestima global. En cambio, si para mí el ser una buena madre es
algo valioso, tener una imagen negativa de mí misma como madre sí va
afectar mi autoestima global"

"los niños reciben, como término promedio, 460 comentarios negativos o
críticos al día y solamente 75 positivos"

"los niños reciben, como término promedio, 460 comentarios negativos o
críticos al día y solamente 75 positivos.

Estos comentarios, por lo general, provienen primero de los padres;
luego, al iniciarse la escolaridad, de los maestros, y finalmente de
los pares en la adolescencia: los tres espejos en los cuales nos
miramos en la infancia y en la juventud para ir formando la imagen de
quiénes somos."

"Las frases repetidas con insistencia por aquellas personas que son
significativas en la vida de un niño o de un joven ayudarán a modelar
la representación interna que tiene de sí"

"Si los comentarios de los padres son mayormente descalificadores, el
niño comenzará a internalizar que es alguien que no tiene valor. En
cambio, si las palabras son de aliento y motivación, el niño sentirá y
creerá que es valioso y merecedor de amor. Y como explicamos antes,
esta imagen interna es uno de los mayores determinantes de la
confianza duradera, del éxito y de la felicidad"

"—¿Alguna vez les han dicho: «Eres un inútil», «Eres un idiota», «No
sirves para nada»?

Casi al instante se levantaron todas las manos de los integrantes de
«la barra brava». Los miré y le indiqué a uno de ellos que hablara…
Entonces él me respondió:

—Todos los días, nos dicen eso y mucho más… Nos dicen que somos unos
infradotados. Que somos basura"

"Lo primero que les expliqué es que estoy convencida de que la mayoría
de los padres queremos lo mejor para nuestros hijos y que nos guían
las mejores intenciones. Sin embargo, eso no es suficiente para no
caer en graves errores; los padres nos equivocamos, y muchas veces
repetimos faltas que fueron cometidas por nuestros propios padres"

"Lo primero que les expliqué es que estoy convencida de que la mayoría
de los padres queremos lo mejor para nuestros hijos y que nos guían
las mejores intenciones. Sin embargo, eso no es suficiente para no
caer en graves errores; los padres nos equivocamos, y muchas veces
repetimos faltas que fueron cometidas por nuestros propios
padres. Esto suele suceder cuando hay presión y, en ese estado, se nos
disparan reacciones en automático."

"A veces no somos conscientes del poder que tienen las palabras, de lo
contrario creo que no se dirían las barbaridades que a veces se dicen
en la intimidad de la familia"

"«¿Es usted capaz de comportarse con sus hijos y su pareja durante un
día como si un vecino lo estuviese escuchando todo el tiempo? ¿No
decir nada a su hijo o pareja que el vecino no pudiera escuchar?
Muchos padres me confiesan que es muy difícil. Y yo les digo que
cuando consigan hacerlo durante todo un día, tienen que intentar
hacerlo durante un día a la semana"

"Si no cuidamos nuestras palabras, podemos dañar la imagen de sí mismo
de alguien a quien queremos mucho, ya sea nuestros hijos, nuestros
alumnos o nuestros amigos… Como hemos dicho, esa imagen se puede
reparar, ¡pero cuánto mejor sería no tener que hacerlo!"

"No hay que decirles que son malos, sino que han hecho algo que está
mal; tampoco decirles que son unos genios, sino que han hecho algo
genial"

"«Autoestima verdadera es lo que sentimos por nosotros mismos cuando
todo anda mal»"

"James explicó que nuestra autoestima equivale a la distancia que
existe entre aquello que queremos ser (el ideal) y lo que creemos ser
(la imagen que tenemos de nosotros mismos). Lo que sentimos con
respecto a esa distancia determina nuestra autoestima."

"Distancia va a existir siempre, pero si llega a ser un abismo,
estamos en problemas con nuestra autoestima. Para remediarlo, según
James, podemos hacer dos cosas: ubicar al «ser ideal» en una medida
más realista, es decir, bajar el ideal que nos proponemos alcanzar y,
simultáneamente, trabajar para desarrollar nuestras habilidades de
manera que podamos elevar la imagen que tenemos de nosotros mismos"

"a través de las interacciones con los seres significativos, desde
pequeños vamos recogiendo información con respecto a nuestro propio
valor. Si la imagen que se refleja es pobre y negativa, el niño se
verá desvalorizado y actuará en consecuencia con esa imagen en su vida
futura"

"Lamentablemente tendemos a señalar el comportamiento negativo de
nuestros hijos, alumnos, colegas y hasta amigos, sin darnos cuenta de
que al hacerlo estamos reforzando justamente el comportamiento que
queremos cambiar"

"¿Me pongo metas profesionales y personales que sean responsables,
específicas, medibles y alcanzables"

"singularmente esa emoción terrible de nuestro tiempo: la impaciencia,
la prisa desordenada de llegar"

"ensayos autobiográficos"

"El estudio reveló que las monjas que tenían más habilidad lingüística
—es decir, quienes habían cultivado más el hábito de leer y escribir—
eran menos proclives a contraer el mal de Alzheimer"

"aquellas monjas que eran más optimistas desde su juventud resultaron
ser las más longevas"

"«No pienses mal, no hagas el mal, no escuches el mal», escribió en su
diario la hermana Esther Boor, de 106 años"

"«son las emociones negativas como la cólera, la ansiedad, la tristeza
e incluso las preocupaciones banales las que más hacen caer la
frecuencia cardíaca, y siembran el caos en nuestra fisiología»"

"sin emociones no hay preferencias, y sin preferencias no hay
decisiones"

"muchas veces olvidamos el papel preponderante que tienen nuestras
emociones a la hora de tomar decisiones"

"cómo nos sentimos con respecto a esa situación/decisión y cuál es
nuestra sensación más visceral, también llamada intuición"

"«La llave que favorece la toma de decisiones es permanecer en
contacto con nuestras propias emociones»"

"Review, la inteligencia emocional es dos veces más importante que las
destrezas técnicas o el coeficiente intelectual para determinar el
desempeño de la alta gerencia. Por su parte, Daniel Goleman asegura
que las personas son contratadas por sus habilidades técnicas y
despedidas por su falta de habilidades emocionales"

"un circuito cerebral que está preparado para emitir nuestras
emociones y captar las de quienes nos rodean. ¡Por eso las emociones
se contagian! Y la más contagiosa es la alegría y su expresión más
estridente: la risa. ¿Será por eso que se dice que la risa es la
distancia más corta entre dos personas"

"sucede tanto en circunstancias agradables como en las conflictivas,
que es inevitable y que ocurre aun cuando nadie diga ni una sola
palabra"

"Quienes más contagian a los demás son las personas emocionalmente más
expresivas y los líderes, aun cuando, como dijimos, no digan ni una
sola palabra"

"cuán importante es trabajar sobre nuestras emociones para poder
contagiarlas positivamente a los demás. Tomemos conciencia de cómo nos
sentimos antes de ir a una reunión, antes de dar una clase, antes de
hablar con nuestro equipo de trabajo, antes de sentarnos a la mesa con
nuestra familia, sabiendo que vamos a contagiar a los demás nuestra
emoción"

"«Las válvulas del corazón, los esfínteres del aparato digestivo que
se abren y cierran, la propia digestión, todo está regido por las
moléculas de la emoción, que tienen una acción física. Si reprimimos
la expresión de las emociones, también reprimimos nuestras funciones
orgánicas, lo que a la larga produce enfermedades o malestar, ya que
se trata de una parte intrínseca del funcionamiento de nuestro cuerpo"

"Las emociones dejan de ser sanas cuando se apoderan de nosotros:
cuando las magnificamos y también cuando las ignoramos; es decir,
cuando no las escuchamos"

"«El pesar nos envejece prematuramente. Cuando estás en deuda
emocional, eres pesimista con respecto al futuro, y aun en tus años de
plenitud ansías volver al pasado para remediar las carencias de amor y
oportunidad que sufriste. A veces ansías más atención, pasar más
tiempo con alguien que ya no está, tener la oportunidad de hablar
francamente y desprenderte de tu carga emocional»"

"Tal vez creemos que no hace falta detenerse a celebrar cuando ocurre
algo bueno, porque pensamos que es una pérdida de tiempo, o porque ya
estamos mirando la próxima meta a alcanzar"

"¿Cuál es el costo de no responder? Cuando no nos permitimos celebrar,
podemos volvernos estoicos o insensibles y empezar a vivir nuestras
experiencias con menos intensidad. Y si somos parte de un equipo de
trabajo, la falta de celebración puede traer desmotivación
generalizada"

"La tristeza nos guía incluso físicamente, para atravesar el dolor,
pues esta emoción genera una disminución de nuestra energía y hace más
lento nuestro metabolismo. Nos da un mensaje bien concreto: «Éste no
es momento de redoblar los esfuerzos, de trabajar más duro, o de
buscar cosas para mantenernos desconectados de lo que sentimos»"

"El miedo nos invita a prepararnos, a usar nuestra energía para
proteger aquello que valoramos o que queremos lograr. Nos impulsa a
cuidar lo que queremos, a tomar precauciones"

"¿Cuál es el beneficio por responder? Cuando buscamos hacer algo para
modificar ese sentimiento de insatisfacción, podemos recuperar algo
tan preciado como el interés por la vida.

¿Cuál es el costo por no responder? Si no respondemos, podemos caer en
estados de ánimo negativos como el hastío y la apatía, y hasta sentir
una profunda desconexión con la vida"

"Es importante recordar que para que una disculpa sea efectiva
necesita, además del pedido de perdón, una acción reparatoria"

"Al hacer un reclamo, uno muestra respeto por uno mismo, por sus
valores y sus límites. Por eso reclamar es una manera de construir
nuestra autoestima"

"¿Cuál es el costo de no responder al enojo? El enojo no expresado
puede derivar en resentimiento, rencor y en una pérdida de confianza,
pues empezamos a tenerle miedo a las situaciones en las que alguien
traspasa un límite importante para nosotros, ya que no sabemos cómo
manejar este tipo de situaciones. Así podemos reaccionar de manera
negativa ante cualquier dificultad que surja, alternando entre
explotar de ira (hiriendo a otros) o, de manera sumisa, guardando todo
el enojo en nuestro interior (dañando nuestra autoestima y nuestra
salud)."

"«La gratitud no es sólo la mayor de las virtudes, sino la madre de
todas las demás», dijo Cicerón"

"En palabras de Meister Eckhart: «Si la única plegaria que dices en tu
vida es gracias, será suficiente»"

"Una de las funciones de la amígdala consiste en escudriñar las
percepciones en busca de alguna clase de amenaza"

"la amígdala se convierte en un importante vigía de la vida mental,
una especie de centinela psicológico que afronta toda situación, toda
percepción, considerando una sola cuestión, la más primitiva de todas:
«¿Es algo que odio? ¿Que me pueda herir? ¿A lo que temo?»"

"Si el estímulo es vivido como una amenaza, la amígdala dispara una
alarma. Entonces el cerebro cierra todos sus circuitos neuronales no
necesarios para la supervivencia"

"Goleman llama a estas situaciones, en las que se nos dispara la
alarma aun frente a algo que no amenaza nuestra vida, «secuestro
emocional». En esos momentos dejamos de pensar, se nos dilatan las
pupilas, el corazón nos galopa en el pecho, aparece el sudor en
nuestras manos, el rostro se nos pone pálido de miedo o rojo de furia,
la sangre fluye a los músculos de nuestras extremidades y segregamos
dosis masivas de adrenalina y noradrenalina"

"Esta relación instantánea y automática entre el tálamo y los centros
emocionales es la que origina el «secuestro emocional» o «estallido
emocional», y el resultado es que actuamos antes de pensar, a veces
para beneficio nuestro y otras para perjuicio"

"cualquier situación en la que otra persona quiera —consciente o
inconscientemente— controlarme, puede hacer que yo entre en secuestro
emocional"

"Desde conductas que me hagan avergonzarme o sentirme humillado y/o
desacreditado, hasta cosas más sutiles como una mirada de
desaprobación, una opinión expresada como verdad o un pedido hecho en
forma de orden pueden ser interpretados como una amenaza por nuestra
amígdala"

"La amígdala también es un reservorio de memoria emocional, con lo
cual dependiendo de las experiencias pasadas de cada persona, habrá
diferentes estímulos que puedan desencadenar el fenómeno del secuestro
emocional. Por ejemplo, si una persona se ha sentido muy juzgada por
sus seres significativos en la infancia, tenderá a percibir
comentarios sobre su persona que no sean claramente positivos como
descalificadores y esto puede llegar a desencadenar un secuestro
emocional"

"«Querer controlar» a otra persona se podría traducir en cualquier
conducta, gesto, palabra que van desde dar órdenes hasta mirar con
desaprobación a alguien, avergonzar, humillar, culpar, juzgar,
desacreditar, denigrar"

"«Yo quiero tener la razón», entonces tú estás equivocado. Procuro que
te sientas menos, para fortalecer mi posición"

"Es el momento en el cual la otra persona puede reaccionar en «modo
supervivencia», y la situación, agravarse"

"Cuando miramos con desaprobación a alguien, podemos activarle
recuerdos dolorosos relacionados con su baja autoestima"

"Cuando usamos gritos y palabras amenazantes, aun bien
intencionadamente para «estimular» a nuestros alumnos, colaboradores,
hijos, ¡tengamos cuidado! Podemos estar activando la alarma que
produce un secuestro emocional sin darnos cuenta"

"El ciclo de la emoción violenta-respuesta violenta tarda 6 segundos
en desactivarse"

"En esos 6 segundos podemos hacer varias cosas más. La sabiduría
popular habla de «contar hasta 10». Entonces, antes de mandar ese
correo electrónico cargado de enojo, de pegar un grito, de golpear la
puerta con furia, de insultar a alguien, de lastimar verbal y
emocionalmente a un ser querido, hagamos «la pausa de los seis
segundos»"

"La ciencia ha comprobado que el amor es una necesidad biológica que
todos tenemos, que expresar emociones positivas puede extender nuestra
vida y que tenemos el cerebro diseñado para contagiar nuestras
emociones a quienes nos rodean"

"Pero a veces las emociones nos toman por asalto y nos conducen a caer
en secuestros emocionales. Cuando eso ocurre, si nos detenemos aunque
sólo sea 6 segundos, podemos frenar a tiempo el estallido"

"Las emociones son, en esencia, el puente entre nuestra mente y
nuestro cuerpo, las responsables de nuestra salud"

"¿Sabías que el número de neuronas que tenemos es similar a las
estrellas que hay en la Vía Láctea? ¡Cien mil millones de neuronas y
cien trillones de conexiones en paralelo! Imagínate cuántos
pensamientos podemos producir por día… ¡Más de 50.000 pensamientos
diarios! Sorprendente, ¿verdad? Pero eso no es todo: el 80 por ciento
son acerca de nosotros mismos… ¡y la mayoría son negativos!"

"apreciando lo que ya tenemos y centrándonos en lo bueno, en lo que
queremos, en lo que deseamos. Así nos sentiremos creativos, fluirán
las ideas, abundarán los proyectos"

"Abundancia que puede comprender bienes materiales, pero no sólo eso,
sino también abundancia de ideas, de amistades, de proyectos, de días
alegres"

"El mayor descubrimiento de esta generación es que los seres humanos
pueden cambiar su vida modificando sus actitudes mentales.

"

"aprendiendo a aquietar la mente, y a limpiarla, como cuando limpiamos
el filtro de la piscina o del aire acondicionado"

"Despertando al testigo de mis pensamientos, que mira sin juzgar tanto
lo que pienso como lo que siento, sin permitir que el miedo se apodere
de mí. Observo para detener o desechar mis pensamientos extremistas,
de todo o nada; mis generalizaciones de siempre o nunca; mi tendencia
al tremendismo o la exageración ante un obstáculo"

"Teniendo en cuenta que cada célula de nuestro cuerpo tiene miles de
receptores abiertos a tales neuropéptidos, eso explica por qué los
pensamientos y las emociones afectan nuestro cuerpo. Por eso, si
pienso bien, me siento bien. Si pienso mal, me siento mal"

"La doctora Pert asegura que «lo que pensamos tiene una enorme
influencia sobre nuestra salud. La mente, las ideas y las emociones
afectan a nuestras moléculas, a nuestra salud física, mucho más de lo
que se creía»"

"en el campo de la mente todos los pensamientos, ya sean positivos o
negativos, se magnifican; así que, en esencia, nada puede ser tan malo
o tan bueno"

"Esto ocurre porque todos los pensamientos, al hacer su transición
hacia la expresión, se reducen en intensidad"

"No revises ningún problema de manera constante en tu mente. Deja
descansar el problema y quizá se resuelva por sí sólo"

"Él tenía conocimiento de que la costumbre de dar rienda suelta a los
pensamientos negativos puede tener consecuencias mucho más drásticas
que una noche de insomnio: es posible que afecte la memoria y la
capacidad de aprendizaje severamente, ya que el estrés prolongado
inhibe las células cerebrales del hipocampo, que juega a su vez un
papel importante en la memoria y en el aprendizaje."

"pensamientos afectan la inmunología: a mayor cantidad de pensamientos
negativos, menor cantidad de defensas produce el cuerpo, ya que el
exceso de cortisol, otra hormona del estrés, disminuye los glóbulos
blancos encargados de atacar las enfermedades"

"La negatividad, aun cuando no lo manifestemos de manera explícita, no
queda sólo en nosotros: el otro la percibe y el ambiente,
inevitablemente, se contamina de ella"

"¿Has observado alguna vez que la gente casi siempre se queja a
alguien equivocado, a personas que no pueden hacer nada sobre su
motivo de queja? Van al trabajo y se quejan de su pareja; llegan a la
casa y se quejan a su pareja de la gente del trabajo. ¿Por qué? Porque
es más fácil, menos arriesgado. Para pedir un cambio de actitud hay
que tener valor.

"

"Porque puede estar faltando el ingrediente menos evidente: el
sentirnos capaces de lograrlo y merecedores de ese éxito. Por eso, al
proponernos objetivos, metas, sueños, recordemos usar el poder de
nuestros pensamientos y emociones, y también preguntarnos:

¿Me lo merezco?

"

"En coaching decimos que las palabras crean realidades. Sin embargo,
lo que antecede a la palabra es el pensamiento, por ende el
pensamiento también crea realidades. Por eso es fundamental revisar a
conciencia nuestro diálogo interno"

"Si los pensamientos que tenemos nos están limitando, difícilmente
podremos alcanzar nuestro objetivo"

"Cuando la NASA se puso la meta de llevar al hombre a la Luna, tenían
una foto gigante de la superficie lunar cubriendo toda la pared, de
piso a techo, de la sala de trabajo"

"Hay psicólogos que aseguran que una hora de visualización equivale a
siete horas de esfuerzo"

"Se trata de dedicar un momento al día para revisar los objetivos y
así inundar la mente a nivel subconsciente con palabras de afirmación
de lo que queremos lograr"

"El nuevo paradigma, sobre el que se fundamenta el coaching, postula
que los seres humanos no somos de determinada manera, sino que estamos
siendo, y que siempre podemos cambiar"

"muchos seguimos con patrones de pensamiento y una visión del ser y
del lenguaje de la época cartesiana. Por eso muchas veces creemos que
existe una sola verdad frente a los acontecimientos, que las cosas son
de determinada manera y que cada ser humano es de una forma inmutable"

"asegura Alvin Toffler, «los analfabetos del futuro no serán los que
no sepan leer y escribir, sino los que no sepan aprender, desaprender
y reaprender»"

"Un joven discípulo llegó a la casa de su maestro, un sabio filósofo,
y le dijo:

—Vengo a decirte algo importante, que no puedo callar, pues un amigo
estuvo hablando de ti con malevolencia…

—¡Espera! —lo interrumpió el filósofo—. ¿Hiciste pasar por las tres
rejas lo que vas a contarme?

—¿Las tres rejas? —preguntó el discípulo.

—Sí. La primera es la verdad. ¿Estás seguro de que lo que quieres
contarme es absolutamente cierto?

—No. Lo oí comentar a unos vecinos…

—Al menos lo habrás hecho pasar por la segunda reja, la bondad. Eso
que deseas decirme, ¿es bueno para alguien?

—No, en realidad no. Al contrario…

—La última reja es la necesidad. ¿Es necesario hacerme saber esto que
tanto te inquieta?

—A decir verdad, no.

—Entonces —dijo el sabio con una sonrisa franca—, si no es verdad, ni
es bueno, ni es necesario, sepultémoslo en el olvido"

"solemos expresar nuestras opiniones como si fuesen descripciones de
la realidad, dando por sentado que los demás ven lo mismo que nosotros
y anulando la posibilidad de que opinen diferente"

"diferencia de un hecho, una opinión no puede ser verdadera o falsa,
sino fundada o infundada. Y de acuerdo con la intención con la que se
dice, también puede ser constructiva o destructiva"

"Aprender a expresar una opinión como tal, en lugar de verbalizarla
como si fuera un hecho, es una habilidad clave para una comunicación
efectiva"

"Cuando hables, procura que tus palabras sean mejores que el silencio.

"

"Las palabras de reconocimiento tienen un impacto altamente positivo
en las personas; sin embargo, muchas veces desconocemos cuán poderoso
es detenerse a reconocer a los demás."

"«Gracias por invitarnos a comer anoche, la comida fue exquisita y nos
hiciste pasar un muy lindo momento».

• Por creer que no es algo muy importante o necesario y que, de todas
maneras, la otra persona ya lo sabe"

"Porque el escuchar es un acto donde interviene la interpretación,
escuchamos lo que, de alguna manera, estamos predispuestos a escuchar,
y esto es personal"

"«En pocas palabras, el estado emocional y las acciones de los líderes
influyen muy directamente en el modo en que se sienten los empleados
y, en consecuencia, determinan su rendimiento. El modo, por tanto, en
que el líder gestiona sus estados de ánimo no es una cuestión
estrictamente privada, puesto que su influencia directa en el estado
de ánimo de sus subordinados lo convierte en un factor esencial del
funcionamiento de una empresa», explican los autores de El líder
resonante crea más"

"El síndrome del sacrificio se interrumpe con una renovación verdadera
que involucre al cuerpo, a la mente y al espíritu"

"la productividad empieza con la satisfacción y la fidelidad de las
personas que integran la empresa"

"Cuando las personas que conforman una empresa se sienten queridas y
valoradas, esto repercute en el cliente y en los resultados: «Un
aumento del 1% en el clima laboral va acompañado de un aumento del 2%
en los ingresos»"

"recuerden el mensaje que se les da a los padres al subir al avión:
«En caso de emergencia, primero colóquese la máscara usted y luego
colóquela a su hijo». Si yo no me cuido a mí mismo, no podré cuidar a
nadie"

"es importante darnos permiso para nuestro restablecimiento físico,
mental, emocional y espiritual"

"Él afirma: «Cuando usted crea que algo que quiere hacer es imposible,
mírese las manos, y piense que todo se puede»"

"Hay una estadística reveladora: el 94 por ciento de los vendedores
dejan de llamar después de la cuarta llamada… ¡Y el 60 por ciento de
las ventas se concreta justo después de la cuarta llamada!"

"En los inicios de esta empresa, cuando todavía era una firma chica y
casi desconocida, Bulova —una organización mucho más grande por
entonces— les encargó la producción de 100.000 radios a transistores,
lo cual seguramente habrá sido una gran noticia para ellos. Sin
embargo, decidieron rechazar esa gran orden de compra. ¿Por qué?
Porque Bulova les ponía, como condición de compra, que las radios
llevaran el nombre de su empresa, y no el de SONY. Al conocer esto,
Akio Morita rechazó la compra con el siguiente argumento: «Dentro de
50 años, le prometo que nuestro nombre será tan famoso como el de su
empresa»"

"Todo comienza con la fuerza de una visión, con descubrir aquello que
te hace sentir vivo, feliz, apasionado. Todo empieza en el instante en
que decides poner detalle y color a aquello que más anhelas conseguir.

"

"Que podemos dejar de ver las buenas oportunidades como aquello que le
sucede a otros y que la felicidad empieza cuando empezamos a
querernos, a darnos cuenta de que podemos cambiar esos patrones de
conducta que no nos gustan y reemplazarlos por otros nuevos. Que para
hacerlo es bueno aprender y desaprender lo que haga falta, cuantas
veces sea necesario.

"

"Cree en las mariposas. Si ellas pueden volar 1.000 millas, piensa en
lo que tú puedes hacer. Estás vivo: celebra cada instante. Descubre lo
que el mundo necesita, aquello que tú crees con todo tu corazón. Un
servicio que verdaderamente haces bien y que te encanta. Haz
eso. ¡Zambúllete!
