#+title:      Martin Fierro
#+date:       [2022-11-19 Sat 16:41]
#+filetags:   :resaltados:
#+identifier: 20221119T164144

"Hace cuarenta o cincuenta años, los muchachos leían el Martín Fierro
como ahora leen a Van Dine o a Emilio Salgari; a veces clandestina y
siempre furtiva, esa lectura era un placer y no el cumplimiento de una
obligación pedagógica. Ahora, el Martín Fierro es un libro clásico y
ese calificativo se oye como sinónimo de tedio. Por su mero volumen,
las ediciones eruditas contribuyen a la difusión de ese error; la
indudable extensión del doctor Tiscornia ha sido atribuida al poeta
comentado por él. Lo cierto es que el Martín Fierro abarca unas
ochenta páginas y podemos empezarlo y concluirlo, sin exceso de
velocidad, en un solo día. En cuanto a su vocabulario, ya veremos que
es menos regional que el de Estanislao del Campo o el de Lussich"

"las guerras que unieron o desgarraron estas regiones. En la guerra de
la Independencia, en la guerra con el Brasil y en las guerras civiles,
hombres de la ciudad convivieron con hombres de la campaña, se
identificaron con ellos y pudieron concebir y ejecutar, sin
falsificación, la admirable poesía gauchesca"

"Bartolomé Hidalgo pertenece a la historia de la literatura; Ascasubi,
a la literatura y aun a la poesía. En El payador, Lugones sacrifica a
los dos a la mayor gloria del Martin Fierro. Este sacrificio deriva de
la costumbre de reducir a todos los poetas gauchescos a meros
precursores de Hernández"

"Mi coronel Marcelino

valeroso guerrillero,

oriental pecho de acero

y corazón diamantino;

todo invasor asesino,

todo traidor detestable

y el rosín más indomable

rinden su vida ominosa,

donde se presenta Sosa

¡y a los filos de su sable"

"Sacó luego a su aparcera

la Juana Rosa a bailar

y entraron a menudiar

media caña y caña entera.

¡Ah, china!, si la cadera

del cuerpo se le cortaba,

pues tanto lo mezquinaba

en cada dengue que hacía,

que medio se le perdía

cuando Lucero le entraba"

"Dirá Hernández:


Ansí es que al venir la noche

iba a buscar mi guarida,

pues ande el tigre se anida

también el hombre lo pasa,

y no quería que en las casas

me rodiara la partida.


Había dicho Lussich:


Y ha de sobrar monte o sierra

que me abrigue en su guarida,

que ande la fiera se anida

también el hombre se encierra"

"Lussich prefigura a Hernández, pero si Hernández no hubiera escrito
el Martín Fierro, inspirado por él, la obra de Lussich sería del todo
insignificante y apenas merecería una pasajera mención en las
historias de la literatura uruguaya"

"«Hernández ignoró siempre su importancia y no tuvo genio sino en
aquella ocasión... El poema compone toda su vida, y fuera de él, no
queda sino el hombre enteramente común, con las ideas medianas de la
época"

"Conferenció sobre política en el teatro Variedades, con una poderosa
voz de órgano, que sus amigos elogiaban.» Carlos Olivera confirma: «Su
elocuencia era como un ariete. Tenía, más o menos, el cuerpo de dos
hombres; su voz era pura y potente; parecía un órgano de catedral. ¡Y
cómo le salían las palabras!»"

"pondera su admirable memoria: «Se le dictaban hasta 100 palabras,
arbitrarias, que se escribían fuera de su vista, e inmediatamente las
repetía al revés, al derecho, salteadas y hasta improvisando versos y
discursos, sobre temas propuestos, haciéndolas entrar en el orden que
habían sido dictadas. Éste era uno de sus entretenimientos favoritos
en sociedad.»"

"«Veinte años dominó Rosas esta tierra; veinte años sus amigos le
pedían que diera a la República una constitución; veinte años negó
Rosas la oportunidad de constituir la República; veinte años tiranizó,
despotizó y ensangrentó al país...»"

"Hernández era federal, pero no rosista.

"

"como todas las obras destinadas a la inmortalidad, tiene raíces
hondas e inaccesibles a las intenciones conscientes del hacedor. El
Quijote se ejecutó para reducir al absurdo las novelas de caballería,
pero es fama que excede infinitamente ese propósito paródico,
Hernández escribió para denunciar injusticias locales y temporales,
pero en su obra entraron el mal, el destino y la desventura, que son
eternos"

"El ejército cumplía entonces una función penal; la tropa se componía,
en gran parte, de malhechores o de gauchos arbitrariamente arreados
por las partidas policiales. Esta conscripción ilegal, como la ha
llamado Lugones, no tenía un término fijo; Hernández escribió el
Martín Fierro para denunciar ese régimen"

"Se propuso evidenciar que esas levas eran la ruina de la gente de la
campaña. El protagonista, al principio, es impersonal; es un gaucho
cualquiera o, de algún modo, es todos los gauchos. Después, a medida
que Hernández fue imaginándolo con más precisión, éste llegó a ser
Martín Fierro, el individuo Martín Fierro, que conocemos íntimamente
como acaso no nos conozcamos a nosotros mismos"

"Hernández no juega a ser un gaucho para divertir o para divertirse;
Hernández, en la primera estrofa, ya es naturalmente un gaucho"

"Cruz y Fierro de una estancia

una tropilla se arriaron;

por delante se la echaron

como criollos entendidos,

y pronto sin ser sentidos

por la frontera cruzaron.


Y cuando la habían pasao,

una madrugada clara,

le dijo Cruz que mirara

las últimas poblaciones,

y a Fierro dos lagrimones

le rodaron por la cara.


Estas dos lágrimas silenciosas lloradas en el alba, al emprender la
travesía del desierto, impresionaron"

"Vizcacha es, después de Martín Fierro, el personaje más famoso de la
obra. En la imaginación popular, es también «el Sancho de nuestra
campaña», como lo define Lugones, que asimismo dice de él: «Es nuestro
tipo proverbial por excelencia. No es el caso de transcribir su
retrato y sus consejos, que todos sabemos de memoria». Habría que
agregar que los consejos son parte del retrato y no deberían ser otra
cosa;"

"Hacéte amigo del juez,

no le des de qué quejarse;

y cuando quiera enojarse,

vos te debes encoger,

pues siempre es güeno

tener palenque ande ir a rascarse.


Es lamentable que estos consejos agoten el poema para mucha gente y
borren tantas otras páginas nobles"

"En una advertencia editorial de la edición de 1894, se habla de
«sesenta y cuatro mil ejemplares desparramados por todos los ámbitos
de la campaña», y se comunica que «en algunos lugares de reunión, se
creó el tipo del lector, en torno del cual se congregaban gentes de
ambos sexos"

"Lugones reclama para el Martín Fierro el título de libro nacional de
los argentinos"

"En sus páginas elocuentes, Lugones exige para el Martín Fierro el
nombre de epopeya; su escritura probaría nuestra ascendencia
grecolatina, a pesar de la larga interrupción que obró el
cristianismo, que es una «religión oriental»"

"Carlyle escribió que Italia se cifraba en la Divina Comedia y España
en el Quijote y agregó que la casi infinita Rusia era muda, porque aún
no se había manifestado en un libro. Lugones declaró que los
argentinos ya poseíamos ese libro canónico y que éste,
previsiblemente, era el Martín Fierro"

"«Fundar ciudades que han comenzado siendo fortines; expandir su
acción sobre el desierto en radio progresivo; luchar con la tierra
virgen y con el auca batallador; padecer las injusticias de la
organización social rudimentaria; sobrellevar heroicamente entre esas
fuerzas fatales la fe en sí mismos, en la humanidad, en la justicia;
he ahí la vida del gaucho Martín Fierro; he ahí la vida de todo el
pueblo argentino»"

"Oyuela, con mejor acierto, escribió: «El asunto del Martín Fierro no
es propiamente nacional ni menos de raza ni se relaciona en modo
alguno con nuestros orígenes como pueblo ni como nación políticamente
constituida. Trátase en él de las dolorosas vicisitudes de la vida de
un gaucho en el último tercio del siglo anterior, en la época de la
decadencia y próxima desaparición de ese tipo local y transitorio
nuestro ante una organización social que lo aniquila»"

"En cenáculos europeos y americanos he sido muchas veces interrogado
sobre literatura argentina e invariablemente he respondido que esa
literatura (tan desdeñada por quienes la ignoran) existe y que
comprende, por lo menos, un libro, que es el Martín Fierro"

"Una simplificación simbólica podría reducirlos a dos: el de Lugones,
para quien el Martín Fierro es una epopeya de los orígenes argentinos;
el de Calixto Oyuela, para quien el poema sólo registra un caso
individual"

"«Justiciero y libertador» es la definición del protagonista que ha
estampado Lugones; «hombre con visible declinación hacia el tipo
moreiresco de gaucho malo, agresivo, matón y peleador con la policía»"

"Shakespeare será ambiguo, pero es menos ambiguo que Dios. No acabamos
de saber quién es Hamlet o quién es Martín Fierro, pero tampoco nos ha
sido otorgado saber quiénes realmente somos o quién es la persona que
más queremos"

"Martín Fierro, porque su ética fue la del coraje y no la del
perdón. Pero Fierro, que ignoró la piedad, quería que los otros fueran
rectos y piadosos con él y a lo largo de su historia se queja, casi
infinitamente"
