#+title:      el aleph
#+date:       [2022-11-19 Sat 16:42]
#+filetags:   :resaltados:
#+identifier: 20221119T164216

"En Roma, conversé con filósofos que sintieron que dilatar la vida de
los hombres era dilatar su agonía y multiplicar el número de sus
muertes"

"Algunos temerarios durmieron con la cara expuesta a la luna; la
fiebre los ardió; en el agua depravada de las cisternas otros bebieron
la locura y la muerte"

"Ese olvido, ahora insuperable, fue quizá voluntario; quizá las
circunstancias de mi evasión fueron tan ingratas que, en algún día no
menos olvidado también, he jurado olvidarlas"

"tan grande era el alivio que me inundaba (o tan grande y medrosa mi
soledad) que di en pensar que ese rudimental troglodita, que me miraba
desde el suelo de la caverna, había estado esperándome"

"Aquella fundación fue el último símbolo a que condescendieron los
Inmortales; marca una etapa en que, juzgando que toda empresa es vana,
determinaron vivir en el pensamiento, en la pura
especulación. Erigieron la fábrica, la olvidaron y fueron a morar en
las cuevas. Absortos, casi no percibían el mundo físico"

"Ser inmortal es baladí; menos el hombre, todas las criaturas lo son,
pues ignoran la muerte; lo divino, lo terrible, lo incomprensible, es
saberse inmortal"

"El cuerpo era un sumiso animal doméstico y le bastaba, cada mes, la
limosna de unas horas de sueño, de un poco de agua y de una piltrafa
de carne. Que nadie quiera rebajarnos a ascetas. No hay placer más
complejo que el pensamiento y a él nos entregábamos. A veces, un
estímulo extraordinario nos restituía al mundo físico"

"La muerte (o su alusión) hace preciosos y patéticos a los
hombres. Éstos conmueven por su condición de fantasmas; cada acto que
ejecutan puede ser último; no hay rostro que no esté por desdibujarse
como el rostro de un sueño. Todo, entre los mortales, tiene el valor
de lo irrecuperable y de lo azaroso"

"Lo elegíaco, lo grave, lo ceremonial, no rigen para los
Inmortales. Homero y yo nos separamos en las puertas de Tánger; creo
que no nos dijimos adiós"

"Cuando se acerca el fin, escribió Cartaphilus, ya no quedan imágenes
del recuerdo; sólo quedan palabras. Palabras, palabras desplazadas y
mutiladas, palabras de otros, fue la pobre limosna que le dejaron las
horas y los siglos"

"Agrega una circunstancia brutal. La mujer quiere resistir, pero dos
hombres la han tomado del brazo y la echan sobre Otálora. Arrasada en
lágrimas, le besa la cara y el pecho. Ulpiano Suárez ha empuñado el
revólver. Otálora comprende, antes de morir, que desde el principio lo
han traicionado, que ha sido condenado a muerte, que le han permitido
el amor, el mando y el triunfo, porque ya lo daban por muerto, porque
para Bandeira ya estaba muerto.

Suárez, casi con desdén, hace fuego.

"

"solecismo"

"óbolo"

"I'm looking for the face I had

Before the world was made"

"Cualquier destino, por largo y complicado que sea, consta en realidad
de un solo momento: el momento en que el hombre sabe para siempre
quién es"

"Las enojosas y triviales minucias no tienen cabida en mi espíritu,
que está capacitado para lo grande"

"En la Suma Teológica se niega que Dios pueda hacer que lo pasado no
haya sido, pero nada se dice de la intrincada concatenación de causas
y efectos, que es tan vasta y tan íntima que acaso no cabría anular un
solo hecho remoto, por insignificante que fuera, sin invalidar el
presente"

"Modificar el pasado no es modificar un solo hecho; es anular sus
consecuencias, que tienden a ser infinitas. Dicho sea con otras
palabras; es crear dos historias universales"

"interpretar sus libros como los ulemas interpretan el Alcorán era el
arduo propósito de Averroes. Pocas cosas más bellas y más patéticas
registrará la historia que esa consagración de un médico árabe a los
pensamientos de un hombre de quien lo separaban catorce siglos; a las
dificultades intrínsecas debemos añadir que Averroes, ignorante del
siríaco y del griego, trabajaba sobre la traducción de una traducción"

"Dijo Tennyson que si pudiéramos comprender una sola flor sabríamos
quiénes somos y qué es el mundo. Tal vez quiso decir que no hay hecho,
por humilde que sea, que no implique la historia universal y su
infinita concatenación de efectos y causas"

"-Es fama que no hay generación que no incluya cuatro hombres rectos
que secretamente apuntalan el universo y lo justifican ante el Señor:
uno de esos varones hubiera sido el juez más cabal. ¿Pero dónde
encontrarlos, si andan perdidos por el mundo y anónimos y no se
reconocen cuando se ven y ni ellos mismos saben el alto ministerio que
cumplen"

"Beatriz era alta, frágil, muy ligeramente inclinada; había en su
andar (si el oxímoron es tolerable) una como graciosa torpeza, un
principio de éxtasis"

"Lo evoco -dijo con una animación algo inexplicable- en su gabinete de
estudio, como si dijéramos en la torre albarrana de una ciudad,
provisto de teléfonos, de telégrafos, de fonógrafos, de aparatos de
radiotelefonía, de cinematógrafos, de linternas mágicas, de glosarios,
de horarios, de prontuarios, de boletines…

Observó que para un hombre así facultado el acto de viajar era inútil;
nuestro siglo XX había transformado la fábula de Mahoma y de la
montaña; las montañas, ahora, convergían sobre el moderno Mahoma"
