* Ideas
** tema pmovto/triggers/paso a TCL
Hoy [2018-02-22 jue] corrijo el ultimo trigger de pagos y ventas upd
para tener todo pmovto con TCL de nuevo, eso rompe la funcionalidad de
python, en el pasado de ventas y recibos.
Lo cual hace obsoleto muchas cosas. pero por lo menos comienzo a
corregir algo.
Con los tests y las correcciones a la base de datos, luego la
depuracion que seria el borrado de lo que no voy a usar o sea las
tablas que no se usan y son obsoletas.
Y la entrada de datos con verificacion para que no haya errores.
** Correccion de datos/Auditoria/Reformulacion de la Base de datos
*** Test.tcl
**** script para correr y dejar asentadas pruebas
un monton de pruebas acumulables que permiten verificar cosas en la
base de datos y emitir resultados, los cuales a medida que se corrijan
tienen que desaparecer.
Incluso se pueden poner alli algunos scripts para corregir si hace
falta.
**** mantencion de sqlite
***** vacuum
achica a casi la mitad la base de datos
***** pragma integrity_check
** Verificacion de entrada de datos en la Venta
*** Verificacion visual de datos corregidos
hacer un tbs donde se vean los campos aclaracion/horario/msgcobr etc
que puedan haberse corregido y se pueda editar alli mismo.
**** TODO corregir bug de borrar datos
no se pq en la edicion me da error si borro datos
cuando en viejas interfaces tcl anda bien
*** TODO ver si hay deudas viejas para condonar
la idea es que al visualizar las ventas pasadas me resalte solo si el
cliente tiene deudas viejas condonables y desaparezca cuando haya sido
condonado
*** TODO linkear los tab con idvta a dobleclick vision ficha con zathura
cosa de poder inspeccionar rapido si todo esta bien en la ficha.
** Nueva ficha
*** mejoras con pdf4tcl lo unico que hay
**** encapsulamiento de cell
empaquete una class emulando el cell del fpdf de python, o sea con
cell [unique] $pdf x text
tengo la celda en la coordenada x y e el valor actual para las y que
lo averigua solo y luego posisiona solo para el siguiente comando, el
texto que se le indica y averigua el ancho y hace el rectangulo de
acuerdo al alto que da la letra.
**** nuevos comandos a usar
$pdf moveTextPosition x y para reposicionar los siguiente comandos de
textos y no depender del flujo de la variable y, y del incr. 
En caso de que no pagine solo, tendria que encapsularlo a este comando
y hacer que compare el valor obtenido de y en cada momento y pagine
correcta y automaticamente.
getTextPosition es util al respecto como tupla de x y para saber la
posicion
*** idea de nueva ficha
creo que se podria hacer la nueva ficha con un encabezado grande de la
operacion, con el valor de la compra.
Restar los pagos realizados y obtener el saldo de la cuenta, y a
continuacion las cuotas a pagar. Alli se deberia ver el tema del vto
para no confundir, o sea con los casos de vencimientos ya vencidos.
** Bugs e ideas
*** TODO bug de busqueda padron femenino por dni
buscar p.e. 5359959 vega maria o buscar por dni a savid silvia
argentina y no las encuentra pero si por nombre.
*** TODO idea poner en la tabla de revision de ventas la zona pq puede ser un error 
que cometa la cami de interpretacion
*** TODO hacer que en el listado de revision de ventas marque los que tengan deudas condonables
para que no nos traguemos deudas condonables
*** TODO  pensar todos los test que se pueden agregar que descubririan errores de pasado
