Agenda de programacion clockeada.
#+BEGIN: clocktable :maxlevel 2 :scope file
#+CAPTION: Clock summary at [2016-10-28 vie 12:28]
| Headline                                    | Time   |      |
|---------------------------------------------+--------+------|
| *Total time*                                | *3:17* |      |
|---------------------------------------------+--------+------|
| Tab pedidos                                 | 3:17   |      |
| \emsp haciendo subtab pasar clientes nuevos |        | 1:16 |
| \emsp bosquejamos el pasado de pedido       |        | 0:36 |
#+END:

* Tab pedidos                                                       :urgente:
CLOCK: [2016-10-25 mar 12:16]--[2016-10-25 mar 12:31] =>  0:15
CLOCK: [2016-10-24 lun 21:59]--[2016-10-24 lun 22:22] =>  0:23
CLOCK: [2016-10-24 lun 19:45]--[2016-10-24 lun 20:32] =>  0:47
** hice una subclase de Buscar que se llama BuscarConPadron
que hereda de Buscar y redefine el metodo show, para permitir filtrar
si el usuario ingreso un dni con prefijo f/F/m/M y busca en el padron
femenino o masculino el numero, y ello sin importar si el cliente ya
existe en Romitex. (cosa que no se podia en las busqueda
semiautomaticas de dni.tcl)
** Inicie el tab y puse el cuadro de Buscar en un frame
** Le agregue funcionalidad de busqueda por nombre pf'Filippi Ana'
*** ojo con el elif                                                 :pitfall:
agrego un branch mas a un if elif else y no actualizo bien. y queda 
if
if
elif
else
y produce errores raros, y es que el flujo va dos veces por un if que
pretende ser excluyente.
** Arregle toque final class Buscar/BuscarConPadron


Agregue o bien mejore y estableci el metodo colsel del tablelist que
te permite poner las columnas ya de entrada en la definicion del tbls
con el select que vamos a usar y no dejar que se cargue automaticamente.
** haciendo subtab pasar clientes nuevos
CLOCK: [2016-10-25 mar 19:01]--[2016-10-25 mar 19:15] =>  0:14
CLOCK: [2016-10-25 mar 13:06]--[2016-10-25 mar 13:30] =>  0:24
CLOCK: [2016-10-25 mar 13:47]--[2016-10-25 mar 14:25] =>  0:38
ya esta casi listo.  Falta corregir el metodo clear de los combos de
bwidget que no andan. para el boton limpiar. Lo hice asi separado, pq
en este pasador nuevo quiero seguir el zen de python explicito mejor
que implicito.
pasado de cliente nuevo en tab aparte, que quede ahi los datos hasta
qu expresamente los limpie, etc.
Era un bug en bwidget.py, ya lo arregle pero lo mismo no limpia.
** bosquejamos el pasado de pedido
dejo para despues cuando tenga mas concentracion.
Pasado de pedido: Encabezo el subtab con id y nombre del que compra y
luego vamos con los datos del pedido en si.
CLOCK: [2016-10-28 vie 11:51]--[2016-10-28 vie 12:27] =>  0:36
Done: Tanto buscando en el cuadro buscar como creando un cliente nuevo
se termina en subtab pedido con un encabezado en label rojo con el id
y nombre del cliente a procesar.
