* alimentacion
** teoria
[2019-02-08 vie] de acuerdo a las ultimas lecturas, que no vienen mal
pq vienen a retomar el tema y a advertir sobre la caca institucional
que es el sistema en eso de envenenarnos y naturalizar soretes para
comer hay que hacer eje principal en el alimento, luego en el
ejercicio.
** licuados
ese tiene que ser el eje principal. Ahi se puede vehiculizar el 80% de
las necesidades de nutricion y saciedad del dia. La potencia del
licuado esta en que permite reemplazar basura. Tengo que buscar la perfeccion en
eso, hay muchas ideas que puedo desarrollar:
*** buscar avena organica
*** probar multiples semillas
*** probar multiples complementos
*** variar frutas
*** hacer variantes no tan fuertes o mas tipo leche
*** ver de hacer dos tandas por dia pero distintas
*** ir variando para no cansarse
*** hacer "premezclas" para un licuado en una bolsita
en caso ir al marques p.e. no es lo mismo no tener nada o llevar
frascos que llevar una bolsita, activar y licuar.
** ensaladas
otro item totalmente descuidado y dejado de lado historicamente de la
dieta y no porque sea feo, es la ensalada, que puede ser tambien
variada hasta el infinito y pasar de ser un minicomplemento hasta un
plato semiprincipal. 
desde un poquito de repollo, unos rabanitos, lechiguita, zanahoria
rallada, etc, etc, es infinito y se le puede agregar tambien de todo.
** pastas bases
arroz bien cocido y mijo.
tanto para una opcion dulce para una merienda, p.e. con una porcion de
arroz una manzana o pera rallada y una leche simple, como la misma
pasta base con una ensalada de cualquier cosa para un almuerzo. 
** evitar los venenos
*** hay que estar mas atento 
la lectura concientiza: hoy comia unas rodajas del pan fargo ese que
tenemos ahi, con queso. La verdad, repugnante, y ahi caigo en la
cuenta como hemos naturalizado eso de la fecha de vencimiento, como
algo valido que "valida" un producto hasta esa fecha mas alla si es
viable que un equis producto dure o como hace para durar hasta esa
fecha, no ya tan solo en conservantes como para que no se eche a
perder sino en alteradores de su intrinseca naturaleza para que se
mantenga en este caso el pan esponjoso tantos dias. O sea que estas
consumiento vaya a saber que cocktail de quimicos. Pero en realidad
somos nosotros lo que descuidadamente consumimos un producto que no es
para durar como durable.
* transicion
[2019-02-12 mar] anoche me quede con bastante buen resultado pq
significo muchas horas de tranquilidad. A pesar de la mala experiencia
en el medio de la prueba con las redes que me canso y estreso (aunque
termino bien pq se termina con una situacion ssh en vez de la anterior
y es mas rapida)
La comida fue mejor, mucho mas tranquila y las horas que se pudo pasar
descansando fueron mas. Hoy compre algunas cosas mas en alimentos y me
decido a no reparar en gastos en ningun sentido, ni en comida ni en el
dpto ni en ropa.
[2019-02-11 lun] la transicion esta vez se torna alarmante. Debo
buscar la forma de soportar hasta que llegue el momento del despegue
de la situacion.
Lo cual lo veo lejano en el momento actual. Porque a la oficina le
quedan un numero indeterminado de dias para poder irnos. (Pero al
menos ya hemos firmado y estamos dentro). Y tambien se exacerba con la
situacion en la casa de dormir poco y mal porque la Cami se levanta
muy temprano. No puedo ir haciendo nada por aca pq estamos limitados.

Lo que se me ocurre es irme quedando aca, hacer la base basica de
licuado comprando chia, pasas uva almendra, avena y peras, cosa de
poder hacer el licuado a la mañana, y quien dice que tambien pueda
hervir el yamani a la noche y tener para comer a la noche y hasta el
mediodia empezando a transicionar. Incluso se me facilitaria estos
dias quedarme pq puedo dormir mas, prepararme mejor la ropa y evitar
el estres de la ida y la vuelta.
y ya puedo ir ganando tiempo haciendo cosas por mi.
** el problema aca
[2019-02-11 lun] a hoy es el bajon o parate programatico que hace que
uno no aproveche el tiempo, o que cuando se sienta cansado no pueda
descansar y tenga que seguir en actividad y compartir la oficina. Pero
creo que pueda llegar a cambiar cuando recupere el dpto. 
** [2019-02-13 mié] 
hoy me mude definitivamente al dpto en forma anticipada, traje lo que
pude en los dos bolsos y seguramente olvide algunas otras cosas, y ya
la Romi me pidio el placard. No es mi voluntad volver pero debo tomar
nota de como son las cosas. 
Hoy cuando venia con el Fede le comentaba el estado de mi salud a
proposito del turno del neurologo (que al final es el miercoles que
viene y me fui al vicio al hp) y se crea una situacion complicada pq
no se aisla la parte medica de la parte familiar, como pasa con el
trabajo. 
Por eso como le decia esta mañana a ih me siento en soledad absoluta,
no solo para enfrentar el momento delicado actual sino para poder
comunicar lo mal que me encuentro. 
Para hacerla breve y quitarle el melodrama, creo que el problema es
viejo y es el mismo de siempre, basta con leer la cronica de cualquier
epoca, lo que cambio y lo que me falta es que por primera vez en
muchos años (hay que volver al breve e ingrato tiempo de herrera y
guzman del 2011/2 y luego al 2004) que me encuentro sin sitio
propio. Malo o bueno, el sitio propio me permitia aislarme, tener
privacidad, comodidad y poder programar y acomodar las cosas
necesarias para la vida (p.e. la ropa que necesito para trabajar) y la
posibilidad de hacer un shock inmediato de comida sana para mejorarme.
Increible como suena en este mes y medio, ih nunca proveyo
espontaneamente a una camisa planchada para que vaya a trabajar,
llegando a tener que repetirme hasta cinco dias seguidos con la misma
camisa cosa que nunca en la vida habia hecho, todo no pq no lo
quisiera hacer yo, sino pq no lleve la tabla de planchar alla y por la
incomodidad que en general hay alla para todo.
Ahora el lema es TODOPASA y falta poco. Aguantar que se traslade la
oficina, aguantar que Fabian empiece a venir con la chata y eso haga
que se pueda desocupar antes el dpto.
Y soportar sin quejarse la falta de aire, la molestia del humo, y
todos los etc. hasta que nos rehagamos.
En el medio de una migraña feroz desatada creo por los triggers de
luz, aire, comida, stresores, etc. me tomo un segundo migral y un
segundo corticoide y en el medio como digo, me pongo en el plan
acondicionamiento de la oficina, o sea ponerse manos a la obra para
tener todo listo cosa de poder mudarse cuanto antes. Una vez que
tengamos eso vamos a estar bien, pq no tendremos mas los estresores.
** evitar la queja - evitar la traicion - cuidar lo que se dice
ayer [2019-02-12 mar] cuando volvia a pesar de gloriosamente estar sin
dolor de cabeza, sufri bastante estres en el transito, lo que pasa que
Fede manejando con una mano, pq alternativamente fuma o usa el celular
y distraido hablando y emocionalmente experimentando picos de
optimismo termino siendo un combo estresor, y cuando llegue ya tenia
activada la bomba quejosa a punto de tirar queja sobre lo desdichado
que era o bien "opinando" sobre lo mal que maneja el Fede haciendolo
quedar mal y eso lo escucha la Cami que luego lo cita fuera de
contexto y me hace quedar mal a mi. 
Entonces pense en el momento y me dije, lo que diga va a ser
perjudicial, lo va a afectar al Fede, y me va a terminar afectando a
mi, entonces no voy a decir nada, me voy a guardar el tema, si al
final ya lo resolvi, pq ya estoy decidido mañana a irme, y asi lo hice
y estoy contento de haberlo hecho.

Hoy paso otra situacion parecida: pensaba que el no movia nada para
que organizaramos la mudanza, y metido como estaba en el dolor, me
levante igual, y le dije sin pelear ni confrontar sino con todo el
espiritu japones de hacer las cosas que teniamos que apurar las
decisiones, y ahi nomas empezamos a movilizar las cosas.
Y al final el mismo me dijo que habia dejado las cosas en standby pq
no queria ponerme nervioso pq pensaba que yo queria esperar. O sea un
mal entendido.

O sea moraleja: resolver las cosas internamente y no quejarse afuera,
ni dar material para la citadora fuera de contexto.
** migraña fuerte N8 cursando con actividad
podria haberme tumbado a las 16hs cuando me tome el corticoide, pero
como comente me puse proactivo con lo de la oficina, y luego que se
fue Fede no me acoste de inmediato a pesar de que luego de unos
momentos empezo un destornillador clavado en mollera izquierda, sino
que me dije voy a hacer el licuado, luego lave la licuadora, luego me
anime, y lave las dos camisas, y el destornillador no cede aun.
Y van tres horas de segundo migral, creo que si me hubiera acostado
sin haber hablado lo de la oficina, hubiera maquinado mal estas tres
horas y gran parte del dolor lo hubiera achacado al Fede, y ahora
vuelvo a estar enchufado, o sea que me parece que no debo en lo
posible quedarme y no debo rumiar.
Luego me puse y planche dos camisas, y recien ahi me acoste a ver el
anteultimo capitulo de la serie (malisimo) y como se me acabo la
bateria termine prendiendo un rato la netbook, luego de comer un breve
arroz muy bien hecho con amaranto en la olla horno.
** evitar el utilitarismo y evitar el desgaste extremo
lo que estoy viendo justo en este preciso instante es que estar
acostado y tener la netbook no es compatible.
si quizas cuando uno no este muy cansado aun o un finde semana, pero
cuando uno esta reventado no vale la pena prenderla, salvo para un
breve post que realmente sea necesario sino no.
lo que vi hoy es que la prioridad es comer bien, descansar, prepararse
la ropa y disponerse a dormir.
** [2019-02-14 jue] 
hoy me levante esplendido, anoche dormi muy bien a pesar de que el
nivel de ruido era muy fuerte y del feo dia que habia tenido ayer. A
pesar de que desayune un migral hasta el momento (10.30hs) curso con
total normalidad y optimismo, unicamente empieza a molestarme un poco
la claridad excesiva y el humo del cigarrillo.
Ayer hice cosas en la casa, hoy me levante y acomode la oficina.
Hasta el momento (13hs) sigo bien, solo me pica la garganta el humo,
aunque hoy pude un poco evitar el exceso de claridad. Noto que llega
la hora de la comida y no esta la posibilidad de comer tranquilo de
forma tal que uno se relaje (pienso que al tener el dpto separado
podre venirme a comer y luego volver tranquilo a trabajar)
De golpe a pesar de que almorce perfecto, comi una compotera de arroz
bien tranquilo, bien masticado, gustosa mezclada con pasta de aceituna
y queso, y luego no tuve ningun estresor que detonara nada, es mas
durante el almuerzo el fede se fue pq tuvo que recibir los muebles, y
luego se fue a comprar el aire y yo me quede practicamente solo en el
dpto sin ninguna presion, atendiendo las llamadas, me bajo la migraña
de golpe, me tomo el segundo pero ya creo que era tarde, ya han pasado
30 minutos y parece que no hace ninguna mella. Felizmente ya no
tenemos el tema de la vuelta pq Fabian no vuelve, o sea que quizas se
corte antes. 
Solo sali un momento para una tarea minima exigencia, ir a la oficina
nueva, encontrarlo al fede, entrar el aire, volver anticipado, en el
momento pensaba, porque me vuelvo si en el trajin te parece que no
estas mal, pero si estas mal, y cuando llegas todo explota, me tomo un
cuarto de B40 o sea 10mg de cortipyren y tengo no un destornillador
sino una sensacion que me hubieran retirado parte de la mollera en
ambos lados, es algo que supera lo que yo puedo.
No sera excesivo?
Desperte a las 7 me levante a las 7.10 y desde alli estuve en tension
pq estoy "viviendo en la oficina"... y luego supongamos que cuente
desde las 7.30, son casi 7 horas al momento actual, entonces es un
tiron largo para el verano, mas que todo a nivel cabeza, tensional,
hombros, cuello, ojos, etc, lo que son los estresores, o sea que lo
tendriamos que agregar a la lista.
O sea que si sumo, una jornada larguisima sin posibilidad de relajarse
en el medio en forma real, una falta de regularidad en el almuerzo y
una falta directa de almuerzo correcto, exceso de luminosidad, humo y
no olvidarse que cuando uno esta en ese estado tambien molestan los
ruidos intensos como el telefono del fede. Todos configuran estresores que disparan el proceso migrañoso
continuamente. 
Lamentablemente estoy roto, completamente acabado, a 1.35hs de tomado
el segundo migral tengo una migraña espantosa y solo aspiro a poder
retirarme al dormitorio, poner el aire que se vaya el humo el dpto y
que se me vaya el dolor, quitandome lo que resta del dia. 
Aunque por ahi pierdo el control y quisiera autoperjudicarme, como por
ejemplo tomar migral hasta reventar, o algo asi, pienso que habiendo
detectado todos los estresores que tengo y estando tan cerca de la
liberacion seria ridiculo si no esperara y probara que pasa si me
ayudo un poco en un nuevo tipo de jornada que sea mas corta y me
permita ese mediodia relajante.
Yo propongo ir temprano tipo 8.30 hasta las 12/12.30 y luego volver
tipo 15.30 hasta la hora que quiera. Eso tambien limitara las horas de
convivencia con el Fede y facilitara las cosas en ese sentido.
** [2019-02-15 vie]
desde ayer a las 18.30 entramos en emergencia, felizmente ya habia
salido de la fase aguda de la migraña y solo quedaba resto, lo que
paso fue que la Cami habia ido al hp por sintomas de apendicitis,
luego se fue al hp central, ya tipo 21hs la Romi se viene para el dpto
y con la Cami con posibilidades de ser operada esa misma noche, me voy
al hp, y permanezco alli hasta las 0.30hs sin sintomas, sin hambre y
sin problemas. Luego pude dormir bien pero poco, me levanto y la
mañana cursa con estresores fuertes, ya que el delay de salida, de una
hora y media sin evacuacion suficiente, y el transito. 
Me tomo un B8 a las 9hs para ir previniendo un dia que sera dificil. 
Transcurre la mañana bastante bien, hasta que tipo 11.30hs tomo un te
con galletas y queso preventivamente para cubrir hambre, pq no tengo
otras alternativas, ya consumido el licuado y las galletas, y con
nerviosismo en aumento, en una situacion de tension y atrapado, pq me
gustaria estar en el hospital, pero ih esta durmiendo aca y es
hipernecesario que se recupere pq puede tener que quedarse a cuidarla
si se queda internada un dia mas, y a la vez el Fede tiene que
quedarse en la nueva oficina a esperar que le coloquen el aire
acondicionado.
A todo esto tomo un migral casi preventivo del rebote, y me preparo
con dosis para la tarde. 
Se que debo estar tranquilo pq mi mal es menor en estos momentos y
debe quedar a un lado de cosas mas importantes y agudas. Ojala se
terminen por resolver de la mejor manera.
Como dice el marco de este tree esto es una transicion, transicion de
recupero de mi espacio, y estabamos entrando en lo mas algido del
asunto, en el cambio en si, con una migraña atomica a diario, y sobre
esa situacion cae como una bomba esta situacion.
La tarde en el hp curso bastante bien sin rebote, solo con un segundo
tomado en el momento justo pero sin consecuencias tipicas del segundo
migral, o sea la migraña catastrofica.
luego llego al marques y comemos con la romi un lomito y duermo
bastante mal, pero sin dolor y el sabado comienzo otro dia de hp.
** emacs -nw equis.org
esta nueva forma de acceder a emacs con consola, y buscando el archivo
a editar por linea de comando es mas agil que buscarlo internamente, y
a la vez mas rapido, y tiene la ventaja que cuando salis podes hacer
el comit particular ahi mismo. Son pocas las cosas que no podes hacer
en modo texto, y las que vas necesitando las tenes que ir aprendiendo.
** [2019-03-16 sáb]
como pintaba a ser otro dia de hp, me tomo otro 8mg de preventivo al
comenzar la mañana y al rato un migral y todo fue muy bien, tanto en
el manejo por circunvalacion, como con la suerte del alta nos vinimos,
el sabado con el corticoide de la mañana y un solo migral anduvimos bien.
** [2019-02-17 dom]
el domingo ya no tome corticoide y se plantio la idea de no tomar
corticoides en el dia a dia, y tratar de no encarar el withdrall con
corticoides.
Y ahi me puse a leer formas de mejorar no farmacologicas, como tomar
mas agua, ser regular en comidas y sueño y otras cosas. 
Asimismo aunque no tome corticoide el domingo me tome el segundo
migral y observe como me habia pasado el miercoles y jueves que el
segundo migral fue catastrofico, o sea fue generador de dolor y fue
como si no hubiese tomado nada, o sea que para que tomar un segundo
migral, al menos estaria bueno poder permitirse la licencia de no
tener-que tomarse un segundo, ni un corticoide por "motivos de
urgencia" llamese trabajo o como viernes y sabado hospital.
Entonces ya hoy [2019-02-18 lun] me planteo que podria manejarme con
un sistema de un solo migral por dia a rajatabla, tomado mas o menos a
las 24 horas del anterior minimo, y evitando el segundo migral. En lo
posible evitar medicamentos, pero se puede probar con un ibu segun los
casos.
P.e. hoy y en medio de un dia muy complicado me tome un ibu y anduve
bien, cumpli con todo y rendi en forma sobresaliente. 
Este sistema de poder cumplirse bajaria el consumo a 30M mas ibus con
el aguante de las migrañas que haga falta, mientras voy aplicando las
medidas de cambio.
** primera reunion de socios en Rioja
[2019-02-18 lun] donde se establecio el 50/50 y el reparto de
dividendos mes a mes en forma razonable. Ambas medidas me traen
tranquilidad de espiritu a mi, pq me dejan mas en paz pq se que asi es
mas justa la division de las ganancias. Y a la vez le quita presion al
negocio el sacarle la esfera privada de la acumulacion individual de
cada uno. 
** Rioja primeras impresiones
[2019-02-18 lun] aparentemente el aire no me molesta, a la vez estoy
cerca de la ventana. La luminosidad no molesta pq esa cortina la
filtra.
Es libre de humo y eso es muy importante, extremadamente importante.
Solo por citar las cosas que me molestaron aca. 
Tambien me libero de atender la puerta y de la vista lateral de la
gente.
** distintos archivos org propuestos
*** tcl-teory
para ir volcando todo lo que vaya aprendiendo del libro
*** tcl-practica
para ir poniendo lo que vamos aplicando de lo que vamos aprendiendo.
idem para toda materia que vayamos haciendo.
*** migra
para concentrar el tratamiento cualquiera sea a partir de ahora
** [2019-02-19 mar]
anoche pensaba que tengo que irme del dpto, pero todavia no he tomado
posesion del mismo y estar tan cerca de la oficina es un
activo. Quizas haya que solucionar por el momento lo que se presente.
Pero lo decia por el tema 
** Tratamiento propuesto por William Romero el [2019-02-20 mié]
subir topiramato a 75mg
iniciar flunarizina 10mg
hacer una cortiterapia breve de 12 dias a 20mg bajando luego 3 dias a
10mg
intentar luego de 3 dias cortar el migral, pero no tener problema de
usarlo como rescate si hace falta alguna vez.
comunicarse al wnromero@hotmail.com
** [2019-02-21 jue]
*** De como tendria que haber cortado en Nov o Dic con el migral
ya con un consumo en los 40 tendria que haber hecho el withdrall en
esa epoca, pero mirando para atras es muchisimo lo que cambio. El
panorama abierto hoy no tiene nada que ver con el que se tenia en
noviembre. Pensemos que en noviembre el Fede trabajaba en la calle con
la kangoo y yo atendia la oficina por la tarde. 
Cuando yo pido la licencia por burnout al principio el FEde no sabia
nada que pasaba y medio que yo tampoco. En el fondo pensaba que si
abandonaba el barco en esa situacion podia pasar cualquier cosa, o
bien que se hundiera, o bien que sobreviviera pero sin mi
luego. Muchas veces me paso por la mente resignar mi status o
situacion pero no me cuadraba y visto desde ahora creo que hubiera
sido dificil que el Fede sobreviviera solo en ese momento.
Luego vino el cambio. Primero cuando le presto la oficina a la Romi,
luego cuando el Fede cambia a la mañana, ahi se conjugo en cierta
forma la posibilidad de que se prolongara mi receso, pq la Cami pudo
quedarse en la oficina al amparo de que la Romi estaba luego en la
ofi.Sino no se hubiera podido quedar.
Esa primera parte quizas fue la mas nociva para mi en terminos de
salud pq lo que primero fue una necesidad de tomarme un respiro devino
en una carga enorme presion. Y esa presion fue en aumento, pq en el
medio se ignoro cual habia sido la causa de toda la presion que habia
sentido en los ultimos tres meses anteriores, que era la problematica
laboral que se habia gestado. Y como esa problematica habia llevado al
escape a la tarde como posible solucion transitoria. Pero la trampa de
la tarde, lo que hizo que la tarde fuera tan dificil y me terminara
matando fue la obligatoriedad de mantener el trabajo a la Cami. Y para
hacerlo tuve que habilitar mi dpto como oficina a la mañana. Eso tuvo
el correlato de disminuir mi comodidad inmediatamente. Y como luego de
ese turno de "trabajo" insalubre para mi, pq ahi habia una sola
maquina, un solo escritorio y un aire que no enfria lo suficiente, en
fin un lugar que como oficina no es muy viable que digamos, comia mal
muchas veces pq terminaba teniendo que comer con la Cami comida
chatarra, y no podia sustraerme a tener una propia siesta antes de la
jornada de la tarde pq en cierta forma "estaba a cargo" habia que
atender llamados, pq podia llamar el Fede, los cobradores, y muy
especialmente el Fabian. 
Habria que sumarle en ese momento el problema de una lluvia de CD,
dentro del horario de entrada de cobradores, que me motivo al cambio a
la noche, y la demora en pasar las dos demandas pendientes a su curso
normal de demanda formal, pasando por vericuetos que antes no habiamos
sufrido y por lo tanto causandonos nerviosismo extra.
Haber comprendido en ese momento exactamente el motivo de mi
agotamiento hubiera buscado otra solucion alternativa: p.e. en vez de
no trabajar, que la Cami dejara de venir, y empezar a pasar los
papeles a la noche y quedarme con el dia libre, o sea concentrar mi
jornada de 17 a 21.
Era obvio que poner al FEde en la oficina me iba a causar mas
nerviosismo y ese nerviosismo iba a aumentar a medida que pasaran los
dias. Encima como una broma el primer dia de retiro entran los
albañiles en la casa y eso me produce migraña gigantes por dos o tres
dias. 
Viendo para atras ese aspecto creo que todo el tiempo que estuve
viviendo en el marques desde el retiro y luego obligado por el tema
oficina en dpto ih solo intento sacarme lo maximo que pudiera para
meter en la casa.
Cuando vino providencialmente el embargo a la oficina, nos fuimos de
un dia para el otro, al vicio, exagerado, como siempre pasa en estos
casos, pq en el fondo era improbable que volvieran en esos dias, pero
nos hicieron un maximo favor, pq dejamos esa oficina. Le hicimos un
gran favor a la Romi, que desde alli despego. que ayer facture 9300 en
un solo dia era impensado en ese aciago dia. 
Pero para que eso fuera posible hizo falta el sacrificio del dpto,
tuve que poner el dpto en disposicion para uso publico, irme a vivir
al marques un tiempo hasta que no se pudo mas.
Creo que el hito el antes y despues fue el tema compu. La demostracion
del egoismo, alli me decidi a irme, y a recuperar lo que es mio, ahi
mismo me dije que tenia que alquilar una oficina.
Y aca estamos a solo dos dias de despejar mi dpto del uso oficinal.
*** hermoso concepto de Dario S. contando una experiencia con su sicologa
dice que un dia haciendo terapia iba a contar un sueño y de repente se
le olvida entonces la terapeuta que era una mujer grande de unos 70
años, lo mira y le dice: "Invente"... y dice Dario que hubo un antes y
un despues desde alli que todo cambio
*** Dario S. promociona el clonazepan...
hay una relacion directa entre los videos escuchados en la etapa
previa al crack noviembre (unas veinte horas de video) y la cantidad
de veces que el tipo este nombre y banaliza el clonazepan, y como
desde alli no digo que comence a tomarlo, pero si creo que comence a
tomarlo a la ligera, sin medir las consecuencias, si no fuera por la
palabra justa del dentista a esta hora estaria complicado por ese
tema.
*** hoy surgieron dos ideas impresionantes para el negocio
**** que pongamos un grupo de promocion con Fabian
y que el siga ganando el 4.5% y nosotros arreglamos a los chicos.
la idea surge como consecuencia inmediata de pensar que ya se terminan
la vuelta y ambos dependen unica y exclusivamente de los datos. Y
antes que la pelea por los datos se haga imposible, y baje la venta,
tenemos que ampliar, hacer mas barrios. y no depender de los actuales unicamente. 
**** que hagamos un centro de verificacion con ih
para que no necesitemos que Fabian se autorice en calle y a la vez
podamos centralizar alli toda la autorizacion y de paso hacerlo mas
profesional y no recargarnos nosotros aca que necesitamos llegar a los
2M de facturacion y los 2M de cobranza. 
La idea nace pq primero pienso en una miniaplicacion para que fabian
se pueda autorizar solo en calle y luego pienso que no va a poder como
no podriamos nosotros, es muy dificil.
Yo hice auto-autorizacion pero sin seven, o sea una sola, no se pueden
las dos autorizaciones juntas. para eso hay que estar con maquina.
Y surge la idea de ih pq ella necesita trabajar y es la unica
disponible para hacerlo en forma de teletrabajo.
* nueva etapa
** [2019-02-24 dom]
hoy comienza una nueva etapa aca en el dpto y lo
lindo es tener todo limpito y tener el plan de ir acomodando todo de
nuevo con nuevos paradigmas. El nuevo libro me muestra el cambiar las
formas de pensar, cosas que hacia por repeticion o por compromiso, que
son elecciones sino viejo hardware, entonces ahi uno podria plantearse
si quiere seguir viviendo con esas pautas o quiere cambiar.
Son muchas cosas. Demasiadas.
Impactante ese estudio (en caso de ser cierto) sobre el efecto en la
salud de un grupo de mucamas que realizaban gran trabajo fisico como
es ese trabajo (p.e. atender 15 habitaciones de hotel), cuando se las
interroga sobre si hacen actividad fisica, la mayoria dice que no (o
sea que no consideraban la actividad del trabajo como "actividad
fisica"), y cuando se toma un subgrupo de ellas y se le cambia el
esquema mental para que consideren la gran actividad que hacian como
trabajo fisico valido a los fines de la salud, se vio luego de un
tiempo que su salud mejoro como si esa actividad la hubieran hecho
aparte, o sea, la actividad la hacian los dos grupos pero la mente no
consideraba que esa actividad debia rendir resultados.
Tiene varias aristas cuestionables lo mismo, pero la idea esta buena,
p.e. se me ocurre con respecto a mi, por muchos años cada vez que
tenia que plancharme una camisa la tortura no era en si la molestia
del trabajo fisico en si, sino el choque del modelo mental previo que
yo tenia por medio del cual "yo no-deberia estar planchandome las
camisas", era esa lucha mental lo que me agotaba, lo que me hacia ver
de forma negativa la tarea y la agrandaba a mas no poder. Viendolo en
retrospectiva si hubiera cambiado mi modelo mental por otro, pe. que
yo planchaba mis camisas pq de esa forma cuidaba mejor mis camisas y
me veia mas presentable, nunca hubiera perdido tiempo en otras
disquisiciones, es mas podria haber aprendido con el tiempo a planchar
mejor, me hubiera procurado una mejor plancha, una mejor tabla,
hubiera aprendido a comprar mejor las camisas pensando en los tejidos
en funcion del planchado, incluso hubiera regulado el uso de las
prendas para aprovechar el planchado. Podria incluso haber aprovechado
el tiempo de planchado en forma creativa p.e. por medio de escuchar
musica, o videos, o meditando, incluso conociendo exactamente cuanto
necesito de tiempo de planchado por semana/mes etc. 
Todo si cambiaba el esquema mental, a uno en el cual uno elige lo que
tiene, en vez de eso cada vez que planche me senti infeliz, cada vez
que contrate planchar, tambien me clave pq tuve que esperar que
plancharan, tuve que aguantar que me golpearan la plancha, que me
plancharan mal, aburrirme esperando, que me arruinaran ropa, y tuve
que pagar por planchar. Y hasta el dia de hoy cargo con el estigma de
que use el planchado para acceder a otras cosas cuando en realidad no
fue asi. Lo mismo aplica para el resto de las cosas del hogar. Esta
bien que en un contexto de trabajo a full en el cual uno tiene un
esquema de horarios agobiante no es facil decir que uno va a limpiar
su casa con alegria y va a hacer las compras, cocinar, comer, lavar
platos, lavar ropa, planchar y limpiar sin quejarse.
El tema quizas sea, reevaluar porque uno hace esquemas de trabajo
agobiantes. 
En 2017/Oct teniamos un sistema agobiante pq me habia echado encima
local, pasado de papeles, cobradores, promotores, y pasado de
datos. Pero eso no estaba bien, y luego cambio, pero gran parte del
2018 la cosa cambio, salvo quiza con el error de haber traido trabajo
a casa (en especial cuando trabajo vino con un esquema fijo y otra
persona o sea la Cami a trabajar al dpto). Luego perdi el dpto. 
Pero en un esquema razonable de trabajo se puede hacer las cosas de la
casa si uno cambia el esquema. 
OJO y no que el esquema que propongo sea el mejor, quizas lo mas
logico sea que un gerente se haga limpiar (jaja ahi caemos a otra
regla del sistema, o sea si sos gerente --> te tenes que hacer
limpiar, Como vas a andar limpiando vos la casa! o como vas a comprar
vos las cosas!) Y es justamente la disonancia de este esquema lo que
me hizo mucho daño en el pasado. Desde años lejanos donde no queria
que me vieran con una bolsita del super, o la legendaria sensacion de
looser viniendo con el bolso cargado de frutas frescas del mercado
norte en horario laboral!!!! una tarde. 
Otro esquema descubierto (oculto): no usar la ropa. No solo tengo un
esquema que me problematiza comprar ropa, mayormente por esquema no
gastar en mi, o por esquema de directa baja autoestima en momento de
comprar, o directamente quizas por creencias equivocadas sobre como
deben comportarse hacia mi los empleados de comercio del rubro, lo
cierto es que una vez tenida la ropa, soy reacio a ponermela.
Relato un ejemplo sencillo para comprender hasta donde llega este
esquema a ser dominante. Hoy domingo tenia que ir a farmacity a
comprar shampu y me tenia que vestir. De paso camino un par de cuadras
por la peatonal, no mas que eso pq como se sabe estoy en WD. El
"trabajo de vestirse es igual sea ponerse andrajos de fajina que ropa
decente", no obstante tendi a la fajina... pq supuestamente no estaba
bañado, o porque usar la ropa "de oficina" para ir a hacer una compra
es "un desperdicio". Lo cierto que ese patron se refleja en toda mi
vida y me encuentro que la ropa no la uso pq solo la uso en la
oficina, y luego cuando estoy de fines de semana uso fajina, por eso
no se gasta, y por eso no renuevo nunca. 
Ni hablemos del esquema que me hace dificultoso gastar asi sea en lo
mas basico. Recien ahora pude ir y comprar una pasta dental de 172 pq
el dentista me recomendo, y pq habia probado una que ih compro de
error y vi que era buena, sino sigo comprando la kolinos de 35
pesos. A pesar de que una pasta de esas me puede durar un mes o mas. 
Creo que no es un problema de inflacion de precios sino que cuando no
hay inflacion se disimula mas este esquema que lo tengo desde hace
decadas en las cuales han pasado muchos precios y muchas distintas
situaciones economicas mias. Solo con inflacion alta lo siento mas
urticantemente, pero el problema es el mismo.
Otro ejemplo muy patente de como el esquema te domina, fue con la
comida de hoy. Ayer hice mijo con calabazas, y comi la mitad para
guardar la mitad (ese es otro esquema que debo revisar, pq podria
haber comido mas ayer, pero me hubiera quedado poquito, para
tirar... o no pero no suficiente para un plato, en fin es una mezcla
de esquemas malos, puede estar el terror a tirar comida -por mas que
sea comida ultrabarata... no estamos tirando medio lomo de 300 mangos,
sino quizas dos cucharadasa de mijo y un poquito de calabazas con
costo que a lo mejor no llega a los 10 pesos, o bien quizas el pensar
que guardando me ahorrare una coccion, o sea tendre una comida hecha,
pero en ese caso porque cuando voy a cocinar no pongo mas, si despues
de todo los ingredientes son baratos)
Como sea la solidificacion del mijo con la calabaza adentro produce
una especie de almidon que podria producir cierto rechazo, entonces lo
quite con una cuchara, lo esparci, le puse sal del himalaya y aceite
pero sin exagerar y luego lo comi asi, no le puse queso ni sesamo, y
... me resulto delicioso y eso que estaba frio, y no tenia hambre de
morir o sea estaba normal. Me parecio que se comia solo. Un plato
equilibradisimo.
Tanto al comerlo como luego al padecerlo en el postprandial. Por eso
pienso que uno mismo cae en el gran ESQUEMA ALIMENTARIO que conduce a
la gente a comer pocos alimentos que no saben a nada y tienen que ser
condimentados al maximo para evitar el sabor que el alimento
tiene. Por eso pienso que hay que permitirse comer lo sano de cero.
** [2019-02-25 lun]
hoy inaguramos oficina. Bastante bien. La oficina genial, comoda,
accesible, a pesar de ser planta, los ascensores son comodisimos, la
entrada y salida muy comoda, practicamente no te chocas con nadie. Es
buenisimo que tenga recepcion en cierta forma pq te ayuda con la gente
que anda perdida.
Y el ambiente adentro es muy benigno, tanto en luminosidad, regulable
con la cortina, aunque hoy no fue un dia de sol pleno, y esta todavia
abierto ese ducto lo que no permite ver como enfriara el aire.
la comodidad del sillon es total. 
Y aca en el dpto he logrado unos espacios que antes no tenia.
1) el espacio escritorio, un espacio al lado de la ventana despejado,
   con aire y luz natural, con la comodidad del sillon rojo para usar
   la netbook en el escritorio. La cual la tengo siempre prendida. Y
   para comer!! pq me resulta mucho mas comodo que la mesa.
2) la cocina con el lavatorio que ahora funciona, tenemos una
   facilidad que creiamos perdida para mantener el orden de una, en
   forma mas facil.
3) el acceso a la ventana del dormitorio, espacio de bici, pizarra, o
   sea un espacio muerto dentro del dormitorio que antes se
   desaprovechaba.
4) baño: al no usarlo de lavadero de platos se mantiene mas limpio.
5) en general manteniendo limpio el dpto, pe. encerado y ordenado,
   tiene una atmosfera diferente y te permite otro tipo de vivencia
   hacia el.
*** sobre la duracion de la limpieza general en el dpto 
considerando que aca limpiamos a fondo hace dos meses y en el interin
casi no se limpio, (aunque no se uso tampoco en algunos aspectos) hay
cosas que no se ensucian tanto, p.e. vidrios: siendo que relimpie los
vidrios del living casi al pedo en muy pocos minutos, los del
dormitorio estan impecables y los limpie mucho antes de principio de
año. Quiza el que mas se ensucia es la cocina, y es el mas
chico. Habria que limpiarlo una vez al mes.
El encerado, el living fue muy facil pasar la cera en general, lo cual
era lo "dificil" o sea la "epopeya de comprar la cera y el palo" ahora
ya los tengo y tengo la tecnica adquirida, solo falta repasar y una
vez cada dos meses paso cera nueva un dia que sea adecuado abrir las
ventanas. El barrido ya lo hago siempre, ahora con el piso limpio es
mas facil, el escobillon no es malo, creo que hay que buscar una pala
decente. El tacho de basura ayuda a mantener el orden tambien. El tema
lavado en el marques se vera muy facilitado con lavarropas nuevo, Y
quedara el tema de la plancha.
** [2019-03-03 dom]
estoy metido en el medio de la recuperacion de la migraña y no quiero
quedarme esta vez y tengo muchas cosas por hacer, y si me meto en
obligacion de "hacer un sistema yo de ventas" me voy a sobrecargar de
trabajo.
pq sera un desastre.
o por lo menos sentirme bien y no tan saturado y poder programar lo
que me falta, o sea un buen pasador de pedidos y un impresor de
pedidos nuevos que no tenemos, o sea no ya decir que vamos a pasarnos
a postgres sino que al menos tener todo ok lo que necesitamos en
sqlite funcionando a pleno.
** [2019-03-04 lun]
*** hoy volvi a programar
*** alta escucha de musica clasica
** [2019-03-05 mar]
a pesar de todas las enormes contrariedades de este finde largo que ya
ni las recuerdo (dos noches migrañosas puras sin medicacion, un tercer
dia migrañoso en avance cortado con MIG, atencion del plomero, martes
de falluteo del plomero, ir a easy a comprar caños de 4metros,
desagote de camara y arreglo de patio, termino mas o menos normal con
posibilidades de encarar la semana sin muchas consecuencia negativa
sobre mi persona.)
** [2019-03-06 mié]
no pude empezar la semana corta pq ni bien estaba en oficina me llamo
ih, creo que en el fondo estaba en panico contenido pobre, pero yo me
porte bien y fui, un poco se lo eche en cara luego, pero no tanto
teniendo en cuenta que estoy con corticoides.
Estuvo bien que vaya pq vi lo que estaban haciendo y pude hacer cosas
que no hubieran hecho como que cambien el sifon doble y quizas la
prueba hidraulica, y tambien hable con Andres por la cochera y tambien
hable a los contenedores o sea redondie todo un tema.
*** a la tarde fue otra jornada
llegue a la oficina y es como si se hubiera gestionado otro dia de
trabajo.
ahi nomas mande un par de wapps y resolvimos un par de temas, y ahi
nomas me fui y puse el aviso y me compre el teclado, y me quede un
rato en oficina a la tarde, en otro momento mas relajado esas horas
extra de superficina pueden ser usados para programar mejor que aca,
mucho mejor que aca.
*** anoche me surgio la idea redondita de hacer no un dpto sino un deposito-cochera
con base para un dpto arriba que posiblemente sea de un dormitorio
nomas y sea independiente de la base.
O sea que el lote quedara con casa dos dormitorios entrada auto./
deposito cochera/
depto un ambiente cochera/
dpto un dormitorio arriba
dpto un dormitorio sobre valdivia dos plantas base 15mts
total renta potencial 41k incluyendo la casa.
** [2019-03-15 vie]
el miercoles empece pushup, como rutina dia por medio, que se puede
hacer en cualquier lado como habito, y a pesar que llevo unos 17 dias
de series, me duelen enormemente unos musculos distintos, a nivel
pectoral con solo dos series de 8 cada uno. Pienso que consolidando
este habito en la forma que estan los otros, puedo llegar a fortalecer
estos musculos y luego agregar otros mas en el futuro. dentro de eso. 
** [2019-03-25 lun]
hoy considero que estoy cansado, no tengo ganas de estar levantado, ni
de estar acostado, ni de hacer nada, o sea ni de leer.
creo que me agote con lo que hice hasta ahora eso es lo que pasa, lo
de la oficina, lo del local.
que un dia o unos dias me los tome no viene mal. ya empezare con mas
brios.
de todos modos lo que vengo logrando es gigante.
no debo desecharlo.
** [2019-04-08 lun]
hoy un dia triste. En realidad noto que estoy solo y que pierdo mi
tiempo con ih. Esa seudorelacion que no lleva a ningun lado ni
siquiera sirve para la catarsis pq te trae problemas.
Mi pregunta es en ese punto del viernes o del sabado en que siento esa
desesperacion por irme del dpto que parte es necesidad que no podria
resolver de otra forma y que parte es obligacion y esa dura realidad
de que no puedo no ir, pq no yendo me siento culpabilizado y me siento
mal.
Me parece que esto va a ser un punto de inflexion, un cambio como fue
lo de la notebook, un punto bisagra, que provoco un cambio pq me hizo
darme cuenta de algo. Esto me hace darme cuenta de algo. En realidad
no pierdo nada si no voy mas. Es una situacion de no salida. Es una
situacion de cada vez mas gasto.
Es una situacion muy angustiosa, porque uno procesa el sentirse
solo. Pero mejor estar solo y no que te saquen. 
En lo personal me aferro a los habitos, a seguir haciendo las cosas
bien tratando de que con el tiempo se perciban las mejoras.
Por el momento creo que estoy en un tiempo de transicion.  
** [2019-04-09 mar]
lanzado con todo en la programacion. Te lleva horas y horas, pero a mi
me gusta. Casi 5hs con las pausas necesarias pero muy satisfecho con
el resultado, que no es fantastico pero va avanzando. 
Me preguntaba que pasaria si de pronto viniera un programador a la
empresa e hiciera un superprograma tipo como tienen los de interplan y
toda mi programacion quedara obsoleta y triste. Pero creo que eso debe
costar plata. Una buena cantidad de plata.
** [2019-04-11 jue]
*** habits
muy bueno el control de habitos del celu, mejor que el de emacs pq es
mas portable y es formidable lo que pecha el control de habito en
querer hacer las cosas, no se porque pero funciona, uno hay veces que
piensa en lo desdichado que es pq tiene ciertas obligaciones pero al
fin y al cabo uno mismo se las puso y es para el bien de uno. Y cuando
las hace siente un pechon de energia positiva muy bueno.
*** estudio dirigido / al menos ficha de problemas resueltos al programar
aparte de programar todo tapon o tema que causa que tenga que recurrir
al manual page, lo hago ficha, pq esas fichas van a ser estudiadas y
memorizadas a full para que la programacion sea fluida, y la lectura
concentrada tambien ayuda.
*** relectura de resaltados
cuando estamos varados en la lectura al menos leer los resaltados
ayuda a retomar ritmos que hemos dejado y al menos a cambiar un poco
de aire.
** [2019-04-14 dom]
*** estudio-fichas-noTCL
veo que de la lectura convencional aparecen como fogonazos temas
realmente potentes como el de los POSIBLES ADYACENTES que son lo
suficientemente buenos como para aprenderlos y vale la pena la
relectura y la ficha. Otro que recuerdo es la serenpidia.
*** estudio-fichas-TCL
agregue ficha de DICTS y aunque no esta totalmente completa permite ir
estudiando el 90% del comando y poder aplicarlo
suficientemente. Sumado a el fichaje de todo problema aparecido va a
facilitar la programacion.
*** problema para relacionarme con la familia
hoy cuando agredo innecesariamente a la Romi ventilando asunto privado
como el monto de la deuda y le digo cosas como que quiero cobrar en
cierta fecha lo cual le causa presion, etc. me doy cuenta que no tengo
control que no tengo empatia y que siempre estoy diciendo algo que
causa daño.
** [2019-04-15 lun]
*** nuevo plan
la idea del nuevo plan que nace del adyacente proximo es hacer un
monoarticulo del articulo mas conveniente para nosotros (maximo margen
real || menor incobrabilidad estadistica || menor competencia) en un
plan semanal (que permite una cuota baja|| el menor plazo de recupero)
con las herramientas actuales del wassap tanto para la captacion que
ya lo habiamos experimentado como para la logistica de entrega y
manejo de promotores. 
**** algo mas I: logistica x wassap: 
esta totalmente establecido que si la entrega se realiza dentro de la
media hora de efectuada la venta la efectividad de la venta es
grandisima, pero eso implica el manejo de la gente y la gestion de las
autorizaciones en la misma persona, lo cual a su vez limita la
cantidad de gente y desgasta un monton, haciendo por wassap las dos
cosas podriamos tener la potencia absoluta de tener cantidad de gente
sin necesidad de una persona fisica dedicada.
Se autoriza por wassap directamente y se entrega dentro de la media
hora el mismo dia sin estar uno presente.
**** algo mas II: manejo del grupo x wassap:
se distribuyen las calles y se exige que den el comienzo de jornada
con mensaje y ubicacion y pidan las calles por wassap.
**** numeros del plan semanal
Cantidad de planes hechos en la historia: 10535
Incobrabilidad historica del plan semanal 9.7%
Incobrabilidad historica del plan mensual 10%
Planes semanales por año
| year |  cnt |
| 2002 | 1142 |
| 2003 | 1894 |
| 2004 | 1257 |
| 2005 |  265 |
| 2007 | 2068 |
| 2008 | 1682 |
| 2009 |  508 |
| 2010 |  442 |
| 2011 |  661 |
| 2012 |  216 |
| 2013 |    2 |
| 2014 |    4 |
| 2015 |   54 |
| 2016 |  190 |
| 2017 |    7 |
| 2018 |    2 |
| 2019 |    1 |
Es interesante notar que las etapas conservadoras fueron hechas sin
plan semanal (periodo 2005/2006) y las expansivas con plan semanal.
Se le hecho la culpa al plan semanal de desmadres de cobranza pese a
que los numeros frios dicen lo contrario.
***** etapa 2016
se hizo un interesante episodio de plan semanal que podria haber
resultado, en 12 semanas de 60 cortinas puras, monoarticulo rabioso,
pero falle en dejar la fisura de acompañarlo con un 4 meses de 180, en
vez de dejar un plan puro que se adaptara solo, de todos modos no
habia mucha diferencia entre los 180 y los 240, puse los dos planes, y
el error mayusculo fue a los dos meses sacar el plan semanal y
aumentar el plazo a igualdad de precios bajando la cuota a 5 de 145,
por supuesto la venta siguio en picada, pq ya los elementos estaban
desgastados.
[Puede que haya otros factores en esa etapa como la falta de
cobradores y la falta de oficina y la falta de recambio de promotores
pero creo que el plan estuvo cerca y es una lastima no haber
comprendido en aquella etapa en su momento del error que se estaba
haciendo al dejar escapar la oportunidad de venta.]
*** nuevo plan aspectos negativos
**** volumen aumentado de papeles del plan semanal
**** problemas de provision de mercaderia
**** tentacion a poner otros articulos y traicionar los principios
aunque en el fondo tengo la duda de que lo bueno sea el plan semanal y
el sistema de venta/cobranza y no solo el vender cortinas, pudiendose
vender otras cosas. Pero eso nos quitaria el tema de poder vender en
todos lados sin verificar y los margenes amplisimos de la cortina etc.
Pero el antecedente del 2007 fue varios articulos.
En el pasado de los 10000 planes semanales vendidos la mitad fue
cortinas el resto dividido entre cubrecamas, sabanas y en menor medida
toallones.
Ahora el toallon y el mantel subieron de categoria y pueden igualar la
salida de la cortina quizas.

*** anexo incobrabilidad historica
Acolchado 2 1/2 plazas|9333.0|53572.0|0.17
Cortina especiales 2.10|112927.5|718520.0|0.16
Sabanas Love and Home 2 y media|82872.0|507910.0|0.16
Sabanas Apache 1 pl|4683.0|30772.0|0.15
Sabanas Apache 2 1/2|9679.0|63722.0|0.15
Sabanas Apache dos plazas y media|4621.0|33696.0|0.14
Sabanas Love and Home 1 y media|20970.0|145230.0|0.14
Cubrecamas 2 1/2 plazas con volados y almohadones|8508.0|72483.0|0.12
Pack 4 toallones|3728.0|30720.0|0.12
Sabana Fantasia 2pl 60 40|2597.0|22392.0|0.12
Acolchado 1 Plaza|2713.0|25690.0|0.11
Cortina con volados|1291.0|12214.0|0.11
Cubrecamas RUSTICO 2 plazas|8913.0|84043.0|0.11
Sabana estampada  2 1/2 plazas|46665.5|434815.0|0.11
Cubrecamas Rustico 1 plaza|2793.0|27300.0|0.1
Sabanas Sommier lisas 2 1/2 plazas|5549.0|57072.0|0.1
Cortina 2,10 Colores especiales (B-VM-T)|7432.0|85254.0|0.09
Cortinas de ambiente|303146.0|3432756.0|0.09
Cubrecamas 1pl|2253.0|26086.0|0.09
Cubrecamas con flecos 2 plazas|1662.0|19434.0|0.09
Sabanas Percal 1 1/2|952.0|10220.0|0.09
Triple Pack Toallones|6265.6|70783.0|0.09
Sabana Fantasia 2 pl|17967.0|225594.0|0.08
Sabana estampada 1 plaza|12691.0|159968.0|0.08
Sabanas Prata DOS plazas y media|14508.0|175218.0|0.08
Toalla y toallon Arco Iris Bert 500gr|4160.0|55380.0|0.08
Sabana Kamacolor 2 plazas y media|11349.0|154145.0|0.07
Sabanas Percal 2 1/2|2554.0|35216.0|0.07
Sabanas Prata UNA plaza y media|1400.0|21485.0|0.07
Sabanas Sommier lisas 1 plaza|847.0|11868.0|0.07
Cortina ESTAMPADA|3702.0|61002.0|0.06
Cortinas Cocina especial|2662.0|42418.0|0.06
Cubrecamas 2pl|7552.0|121433.0|0.06
Jgo Toallon y toalla AI 500gr|1040.0|17724.0|0.06
Mantel rect N 2.40|1921.0|30650.0|0.06
Sabanas Pierre Balmain 2 plazas y media|58730.0|1061786.0|0.06
Sabanas Piñata|3210.0|56647.0|0.06
Cortina COCINA|1705.0|31167.0|0.05
Mantel Especial 2,40 mts Rectangular|1292.0|24706.0|0.05
Mantel cuerina rect 240|4383.25|90573.0|0.05
Mantel rectangular 240|604.0|13403.0|0.05
Sabana Kamacolor 1 plaza y media|796.0|15567.0|0.05
Colcha Indu Love and Home 2 y media|1050.0|23730.0|0.04
Cortina MADRAS|744.0|18408.0|0.04
Cortina de GROSS|1238.0|33108.0|0.04
Cortina de LIENZO|1785.0|40902.0|0.04
Frazada rayada|840.0|22410.0|0.04
Pack 2 Toallones|1369.0|31496.0|0.04
Sabana Fantasia 1 pl|7479.0|172682.0|0.04
Sabanas Pierre Balmain 1 plaza y media|6079.0|149056.0|0.04
Acolchado 1 plaza Sorpresa|338.0|12970.0|0.03
Jgo Toallones Franco Valente|539.0|20201.0|0.03
Mantel Rectangular Santista Ouro|391.0|13716.0|0.03
Pack Mantel rectangular 240|393.0|11840.0|0.03
Sabana Apache 2 y media plazas|435.0|14530.0|0.03
Sabanas Pierre Balmain KING|1570.0|54060.0|0.03
Sabanas Prata 2 1/2|457.0|14530.0|0.03
Acolchado Pierre Balmain 2 plazas y media|1080.0|52500.0|0.02
Frazada Piel PB Galant 2 y media|5000.0|314090.0|0.02
Batas Seclair|0.0|12240.0|0.0
Frazada Triple Patagonica 2 y media|0.0|14400.0|0.0
Jgo Toallon y toalla AI 450gr|0.0|11660.0|0.0
Jgo Toallon y toalla Seclair 550gr|0.0|44005.0|0.0
*** nuevo plan articulos anexos 12x100
la idea seria vender toallon que es el articulo mas sensible a 12x100.
y generar una comision generalizada de 100. 
O sea ampliarle a los chicos los articulos a vender llevaran cortinas,
mantel de cuerina, y cortinas de cocina y toallones y darles cuotas
desde cien pesos, y darles una comision de cien por articulo. 
No va a hacer falta mas comision que esa, y a la vez sera una comision
grande pq el plan de cuotas de 100 suena muy groso. Y el plan semanal
absorve a los otros planes. Porque lo que se cambia es la idea de
vender un producto en vez de vender un pack.
** [2019-04-22 lun]
*** el nuevo plan comenzara con los nuevos promotores
solo la sangre nueva va a hacer que el nuevo plan resurja.
Y el entusiasmo del Fede va a hacer que el plan tenga fuerza. Que no
lo boicotee nadie del pasado. Cuando estos chicos nuevos venidos de
otras tierras y generaciones nuevas salgan y vean que pueden vender
30/40 articulos por dia generando para ellos mismos un ingreso genuino
muy interesante y para el reparto otro ingreso interesante. 
El paso siguiente sera tener un local aca en el centro y alli tener la
independencia de gestionar repartidores que nos trabajen libremente
sin tanto problema. 100 articulos por dia no es algo descabellado de
conseguir.
** [2019-04-24 mié]
*** nuevo plan peligros cuando tenga exito
**** mucho movimiento de papeles
**** mucho movimiento de cobradores
**** echarle la culpa de la incobrabilidad
pq es una venta masiva y puede generar ventas que no son aptas o estan
mal hechas. parte pq son chicas.
*** nuevo plan ventajas
**** mucha venta
que david y dario vendan 20 ventas en un dia es algo impresionante
pq te puede dar un nivel de 500k de venta con solo dos promotores.
**** recupero rapido
el plan semanal te da recupero en solo 3 meses 
**** riesgo distribuido
un riesgo atomizado a un huevo en cada canasta pq tiene limites muy
bajos de venta.
**** alto nivel de penetracion de venta nivel zona y nivel promocion
al ser un plan facil se pueden explorar nuevas zonas y se pueden poner
sin pausa promotores nuevos, incluso a comision.
**** venta de manejo virtual
una tipologia de venta que solo requiere reparto, y no requiere manejo
zonal, o sea no es necesario llevar muestras, ni es necesario un jefe
de venta en zona que lleve una linea de trabajo. Eso posibilita un
manejo desde oficina a una cantidad infinita de gente manejada por
wass y repartida por distintos repartidores.
** [2019-04-26 vie]
*** hoy no estoy con ganas de ir
es viernes a la tarde y no me vienen ganas de ir pq la palabra putrido
me resuena fuerte y feo. Es como que me cayera una ficha que no me
habia caido nunca. 
Para que ir, para que ir a sentirse mal, para ir y pelear y discutir,
hacerse mala sangre, estar dolorido de espalda.
Mejor quedarse aca y tomarse un finde de descanso. Nos vendra bien a
todos para reflexionar.
** [2019-04-27 sáb]
*** sensacion de prision autoinfligida
mi primera sensacion estando solo es que estoy preso. Preso de mi
mismo.
Pq no tengo nada que hacer, y no tengo ninguna posibilidad de salirme
del circulo vicioso en el que me encuentro.
El ir al marques es solo un paliativo que disimula, pero al fin y al
cabo es lo mismo, no cambia, disimula nomas. La realidad es que no
salgo pq no tengo donde ir y no tengo donde ir pq no me animo a salir
y pq no tengo a nadie a quien ver.
*** primer sabado solo
fue productivo pero siento mucho el cansancio atros en el cuerpo.
a pesar de que hago las pausas siento el pasar de las horas.
el avance es mucho aunque no se ve el resultado muy espectacular por
ahora pero es postgres puro y duro. y nuevo
dejo pq me dan puntaditas en la cabeza.
** [2019-04-28 dom]
domingo visita corta con la familia, almuerzo y visita breve que
recupero un poco los lazos rotos. No me parece mal. No esta mal que la
visita sea mas corta, pq me permite tambien que destine un poco mas de
tiempo a programar y que valoren un poco mas los vinculos. 
** [2019-05-06 lun]
anoche a las 20hs aproximadamente conecte a nube por primera vez y eso
me emociono por ser un hito en la carrera programatica. Se que falta
un monton para lograr que eso sea operativo pero ya hay un norte que
esta trazado.
** [2019-05-08 mié]
mucha decepcion con todo el sistema, estoy cansado pq no le veo la
solucion a todo por eso pienso que debo descansar un poco y establecer
metas mas realistas pq sino me voy a arruinar yo solo.
** [2019-05-13 lun]
termino hoy de ponerme un sitio de programacion profesional
comprandome un monitor grande y luego me comprare el cpu para
completar la potencia programadora, pero por ahora va esto, y me traje
mi teclado profesional, todo para darme mayor comodidad.
Quiero empezar a programar en serio como un trabajo sin que me afecte
ni los nervios ni la salud.
** [2019-05-19 dom]
*** estudio de ingles
estudiar cualquier aplicacion me aburriria hasta morir, lo que debo
hacer es sacar terminos de los manuales que leo y necesito leer y
crear un anki de terminos que tendria que dominar bien, precisamente
con anki en forma intensiva y luego releer el material hasta
comprenderlo totalmente. cuando llegue a manejar 300/400 terminos mas
que ahora creo que elevare la comprension lectora que tengo ahora en
un 20% mas o mas.
*** programacion primera etapa
con postgres a fondo aseguro lo que estoy haciendo pq la ida y vuelta
de datos a la nube no hubiera ido tan facil sin comprender a fondo
pg_dump por ejemplo, igual podria ser si aprendiera a fondo psql y
otras cosas administrativas de postgres. Y meterle a fondo con la
programacion de tcl. No vendria mal un repaso a fondo de pgtcl para no
andar adivinando cada vez que programamos un toque. 
una vez terminada esa primera etapa podria emprender otra etapa con
otras cosas pero ya tendria funcionando en la nube el sistema.
** [2019-05-26 dom]
*** analisis de conveniencia de cambiar dpto para evitar riesgo embargo
un cambio de dpto a uno infimamente mejor (digamos costo 3k plus por
mes nivel 9000 o 10000 mas expensas) acarrearia los siguientes gastos:
| rescision                  |  7500 |
| mes traslapado             | 12000 |
| comision inmobiliaria      | 13500 |
| coneccion luz y gas        |  6000 |
| verificacion luz           |  4000 |
| retiro y colocacion 2 a.a. | 14000 |
| pintura dpto y mudanza     |  6000 |
| Subtotal                   | 63000 |
| dif alquiler por 12 meses  | 36000 |
| Total                      | 99000 |
Como se observa aunque algunos costos son anticipados a costos que si
o si tendre que hacer, la mayoria se producen por el cambio en si, o
sea que si el cambio lo hago cuando me plazca o cuando sea mas
conveniente para mi no para evadir algo.
El tema es que para evadir un posible embargo de algunos bienes voy a
meterme a gastar platita contante y sonante en la suma de 60 lukitas
ya y me metere en un gasto mas grande que el que estoy y en una vida
peor que la actual, pq no estare en una direccion comoda.
Posibles embargables:
| mesa y sillas    | no se puede |
| mesa tv          |   sin valor |
| escritorio       |        2000 |
| sillon giratorio |        8000 |
| monitor          |        9000 |
| sofa             |       20000 |
| heladera         | no se puede |
| cama             | no se puede |
| bici             |        7000 |
| notebook         |       30000 |
| reloj            |       20000 |
Total sin pequeños objetos: 46000
Total general: 96000
En el peor de los casos que perdiera todos esos objetos la cifra no
justifica la cifra real de la maniobra evasiva, pq si para evitar el
embargo "preventivo" de 96k gasto 60 y luego 30 a lo largo del año
estoy en la misma, maxime siendo que las probabilidades reales que
dicho embargo ocurra son mas bien bajas.
Lo unico que hay que hacer es no tener fondos en efectivo y hay que
estar preparado para guardar ciertas cosas. 

Tendria que aplicar lo que enseña Carnegie aceptar lo peor que pueda
pasar, y desde alli todo lo demas es mejora.
Lo que hace este articulo es poner en verdadera perspectiva cuanto
cuesta el cambio, que no es barato lamentablemente y por otra parte
que no es mucho lo que hay de embargable, pq sacando los pequeños
objetos, no queda nada, lo que es la carcasa del dpto pueden venir a
embargarla diez veces si quieren que no hay nada de valor que sea
relevante lo suficiente como para justificar el salirse de aca. 
*** analisis de irse al marques
la hipotesis no era irse a otro dpto sino irse al marques, pero
nuevamente me encuentro con la traba que no podre adaptarme, mas que
todo por la falta de lugar. 
Y es verdad lo que me advierten es lo que luego me sucedera a mi
mismo. Yo mismo me dare cuenta luego nuevamente que no me siento
comodo.
Que el problema de depresion lo debo resolver solo no tengo pq cargar
a los demas con ese problema.
** [2019-05-27 lun]
*** el vaso medio lleno, depende como miremos las cosas
una venta basica media de guerra es un palo, y eso nos deja minimo el
30, aparte que el fede puso a punto el recupero con tantos cobradores,
lograndose esa pata que siempre quisimos, en este momento la pata
vendedora no es tan rutilante pq la situacion no es la mejor, y quizas
no es tampoco conveniente el vender tanto en estos tiempos.
Ese palo te deja 150 y con eso vivis bien. Incluso podria vivir con
menos. y nos damos el lujo de ahorrar. 
Ya palo y medio de venta y quizas un poco mejor de expectativas tenes
para repartir, 250 cada uno lo cual en estas epocas no esta mal.
por eso pienso que debo tener otra actitud pensar de otra forma creo
que debo cambiar los pensamientos pq los malos pensamientos por ahi
ganan la batalla y me hacen pensar cosas que son muy tontas como
querer dejar el sistema.
Asi como a veces me pasa que quiero dejar kubuntu me pasa que las
otras distros son extremadamente dificiles y serian comparables a una
vida p.e. haciendo un reparto yo en la calle, y todo para que? si con
kubuntu se esta bien y tenes todo. o te pasa por la cabeza encarar
windows pero esa es una vida que ya dejaste y la dejaste para siempre.
y tambien adquiere otra dimension lo que estoy haciendo con el
programa pq estariamos yendo a otra dimension a otros niveles, quizas
con un costo mayor pero con prestaciones que nunca hemos tenido, como
la coneccion desde distintos lugares.
** [2019-05-28 mar]
sigo pensando en positivo sin estar positivo o sea estando en casa en
forma desastrosa en lo personal, pq me siento deprimido, viejo, mal,
sin salida, y demas. Pero dentro de todo eso, lo positivo es que :
**** leo y releo louse hey y me hace bien
**** hoy compre comida y me fui a comprar pan y amaranto
**** a pesar del reniegue la productividad de mi trabajo esta tarde fue positiva
**** genere una nueva idea para mejorar el sistema de venta
** [2019-05-29 mié]
*** remodelacion del grupo de venta
una nueva remodelacion del grupo de venta, un ultimo intento por
salvar el recurso alejandro que me parece estupendo para la labor, y
no esta cuajando el sistema anterior (lamentablemente queda sin
trabajo ih y eso es algo que siento mucho pq le hizo muy bien trabajar
estos dos meses pero ya le encontraremos algo). El problema del grupo
actual de entrega en el dia es que no se logra un volumen aceptable de
entrega que convenga, y a la vez es muy consumidor de tiempo el
reparto. O sea que tenes pocas ventas o sea 20/22 tenes bajas sobre
esas ventas, dejandote no mas de 18 y a veces 15 y la labor te lleva
todo el dia, lo cual no te deja esperanza que se corrija el problema
agregando mas gente.
Por eso digo que esto es el ultimo intento de salvar la situacion o
sea conseguir que el puesto del ale sea rentable y los demas que vayan
tirando. Pq los promotores son recambiables hasta cierto punto pero ya
repartidor no encuentro una solucion facil.
*** estoy tratando de comer mas aunque sea comprado
aunque me caiga mal algunas comidas tengo que comer comidas hechas no
puedo pasar dia completo con arroz solo. Una minima atencion a lo
personal tengo que darme para comer. 
*** no debo reprocharme por no tener resultados un dia
ayer hice una programacion bastante dificil y lo logre en una tarde y
hoy fue un dia destinado al cambio de sistema con la mañana larga
completa en la tediosa labor de pasar los datos de las zonas y luego
la siesta
** [2019-05-30 jue]
todos estos dias me ronda la cabeza el plan cero o sea el como seria
empezar de nuevo, pero no se me escapa que ya es tarde para mi y que
por mas que empezara algo nuevo no saldria de la mierda. 
Tambien pienso que en si el negocio son como piezas que se van armando
y yo debo verlas asi, o sea aprender a delegar. El bloque cobranza el
Fede lo hace mejor que yo y este mes esta logrando record absoluto, el
bloque reventa lo hace Fabian por un precio y lo hace bien, y eso nos
asegura la visita de clientes en tiempo y en forma como siempre
quisimos, y lo que necesitamos es el bloque venta en la calle, o sea
que el grupo funcione bien, que las chicas vendan las tres ventas por
dia y que al ale le convenga la jornada. Si logramos eso tendremos
tres areas delegadas que son importantes y hasta podria en un futuro
delegar el pasado de papeles quizas. O bien podriamos tener otro
sistema de programacion mas avanzado quien sabe.
Eso desde el punto de vista de la faena, y desde la ganancia como puse
en un post anterior, con un palo miserable y un 35 miserable, tenemos
un modico 175 lo cual es bastante y permite incluso ahorrar y cabe la
chance que se de un ingreso mayor en cualquier momento.
* recetas
** mijo con calabazas
** yamani con amaranto y queso
** verduras al vapor todo tipo 
** yamani cocinado con calabazas sin queso
** quinoa con papas y sesamo y chauchas al vapor
receta quinoa coccion perfecta: lavar, poner 1.5 taza por taza de
quina EXACTO cocinar 14 minutos, echar solo hirviendo y bajar el
fuego, poner sal en el agua. no se pega en la olla.
** lentejas semanales
las lentejas remojadas a las 7hs (dejadas la noche anterior en seco
para no olvidarse), y puestas a hervir apenas regrese a casa, en tres
ciclos de 20 min con reloj, en olla horno fuego corona, con laurel y
ajo, quedaron tan exquisitas que me comi un plataso ahi mismo calentitas.
** quinoa coccion perfecta 14 min
1 parte quinoa - 1 1/2 parte agua - 14 min coccion fuego suave
lavar la quinoa!!! y colarla bien pq resume casi media taza de
agua!!!!
media taza sirve para dos porciones 
** fideos italianos con salsa tomate
fideos italianos cocinados segun instrucciones del paquete, lata de
tomates perita, picados en tabla, una cebolla picada dorada en aceite
de oliva abundante, le tiro el tomate, oregano y listo.
muy bueno y sano.
* comprar
ir agregando uno o dos ingredientes de cada tipo ya incorpodado,
p.e. arroz negro, quinoa, girasol, y mas verduras por ahora, y otro
aceite de oliva mas fino. 
* idea estudiar a fondo TCL para acumular capital laboral
la idea nacio primero como reveer a fondo el tolkit y hacerlo con la
compu de "sentado" para hacer los ejercicios, hacer fichas, hacer
resumen en org, y que sirva, pensando que hay bastante para ver:
listas, dict, file i/o, namespaces, etc. Luego se agrega tk, con
canvas, text, grid, pack, etc, y luego puede seguir tablelist, y por
supuesto itcl a fondo. Y todo sin comenzar a desarrollar nada o bien
hacerlo pero sin dejar de estudiar pq la bocha esta en hacer algo
realmente nuevo, algo que cambie lo que venimos haciendo hasta ahora.
** cuanto puedo estudiar por dia
pense que sacandole horas muertas o al vicio del trabajo siendo que
esto tendra implicaciones positivas para el negocio, pero sera a largo
plazo, creo que tres horas por dia.
** no distraerse en los resultados o las practicas
si bien es cierto que hacer cosas son incentivos para aprender, sino
hacemos el esfuerzo por aprender la teoria cruda cruda no vamos a
ningun lado.
** quizas tengamos que imprimir tambien
p.e. el manual lo cual seria muy util para horas de reposo que pueden
sumar y el manual es un buen complemento a todo tipo de aprendizaje.
luego los encarpetamos a todos.

