* alimentacion
** teoria
[2019-02-08 vie] de acuerdo a las ultimas lecturas, que no vienen mal
pq vienen a retomar el tema y a advertir sobre la caca institucional
que es el sistema en eso de envenenarnos y naturalizar soretes para
comer hay que hacer eje principal en el alimento, luego en el
ejercicio.
** licuados
ese tiene que ser el eje principal. Ahi se puede vehiculizar el 80% de
las necesidades de nutricion y saciedad del dia. La potencia del
licuado esta en que permite reemplazar basura. Tengo que buscar la perfeccion en
eso, hay muchas ideas que puedo desarrollar:
*** buscar avena organica
*** probar multiples semillas
*** probar multiples complementos
*** variar frutas
*** hacer variantes no tan fuertes o mas tipo leche
*** ver de hacer dos tandas por dia pero distintas
*** ir variando para no cansarse
*** hacer "premezclas" para un licuado en una bolsita
en caso ir al marques p.e. no es lo mismo no tener nada o llevar
frascos que llevar una bolsita, activar y licuar.
** ensaladas
otro item totalmente descuidado y dejado de lado historicamente de la
dieta y no porque sea feo, es la ensalada, que puede ser tambien
variada hasta el infinito y pasar de ser un minicomplemento hasta un
plato semiprincipal. 
desde un poquito de repollo, unos rabanitos, lechiguita, zanahoria
rallada, etc, etc, es infinito y se le puede agregar tambien de todo.
** pastas bases
arroz bien cocido y mijo.
tanto para una opcion dulce para una merienda, p.e. con una porcion de
arroz una manzana o pera rallada y una leche simple, como la misma
pasta base con una ensalada de cualquier cosa para un almuerzo. 
** evitar los venenos
*** hay que estar mas atento 
la lectura concientiza: hoy comia unas rodajas del pan fargo ese que
tenemos ahi, con queso. La verdad, repugnante, y ahi caigo en la
cuenta como hemos naturalizado eso de la fecha de vencimiento, como
algo valido que "valida" un producto hasta esa fecha mas alla si es
viable que un equis producto dure o como hace para durar hasta esa
fecha, no ya tan solo en conservantes como para que no se eche a
perder sino en alteradores de su intrinseca naturaleza para que se
mantenga en este caso el pan esponjoso tantos dias. O sea que estas
consumiento vaya a saber que cocktail de quimicos. Pero en realidad
somos nosotros lo que descuidadamente consumimos un producto que no es
para durar como durable.
* transicion
[2019-02-12 mar] anoche me quede con bastante buen resultado pq
significo muchas horas de tranquilidad. A pesar de la mala experiencia
en el medio de la prueba con las redes que me canso y estreso (aunque
termino bien pq se termina con una situacion ssh en vez de la anterior
y es mas rapida)
La comida fue mejor, mucho mas tranquila y las horas que se pudo pasar
descansando fueron mas. Hoy compre algunas cosas mas en alimentos y me
decido a no reparar en gastos en ningun sentido, ni en comida ni en el
dpto ni en ropa.
[2019-02-11 lun] la transicion esta vez se torna alarmante. Debo
buscar la forma de soportar hasta que llegue el momento del despegue
de la situacion.
Lo cual lo veo lejano en el momento actual. Porque a la oficina le
quedan un numero indeterminado de dias para poder irnos. (Pero al
menos ya hemos firmado y estamos dentro). Y tambien se exacerba con la
situacion en la casa de dormir poco y mal porque la Cami se levanta
muy temprano. No puedo ir haciendo nada por aca pq estamos limitados.

Lo que se me ocurre es irme quedando aca, hacer la base basica de
licuado comprando chia, pasas uva almendra, avena y peras, cosa de
poder hacer el licuado a la mañana, y quien dice que tambien pueda
hervir el yamani a la noche y tener para comer a la noche y hasta el
mediodia empezando a transicionar. Incluso se me facilitaria estos
dias quedarme pq puedo dormir mas, prepararme mejor la ropa y evitar
el estres de la ida y la vuelta.
y ya puedo ir ganando tiempo haciendo cosas por mi.
** el problema aca
[2019-02-11 lun] a hoy es el bajon o parate programatico que hace que
uno no aproveche el tiempo, o que cuando se sienta cansado no pueda
descansar y tenga que seguir en actividad y compartir la oficina. Pero
creo que pueda llegar a cambiar cuando recupere el dpto. 
** [2019-02-13 mié] 
hoy me mude definitivamente al dpto en forma anticipada, traje lo que
pude en los dos bolsos y seguramente olvide algunas otras cosas, y ya
la Romi me pidio el placard. No es mi voluntad volver pero debo tomar
nota de como son las cosas. 
Hoy cuando venia con el Fede le comentaba el estado de mi salud a
proposito del turno del neurologo (que al final es el miercoles que
viene y me fui al vicio al hp) y se crea una situacion complicada pq
no se aisla la parte medica de la parte familiar, como pasa con el
trabajo. 
Por eso como le decia esta mañana a ih me siento en soledad absoluta,
no solo para enfrentar el momento delicado actual sino para poder
comunicar lo mal que me encuentro. 
Para hacerla breve y quitarle el melodrama, creo que el problema es
viejo y es el mismo de siempre, basta con leer la cronica de cualquier
epoca, lo que cambio y lo que me falta es que por primera vez en
muchos años (hay que volver al breve e ingrato tiempo de herrera y
guzman del 2011/2 y luego al 2004) que me encuentro sin sitio
propio. Malo o bueno, el sitio propio me permitia aislarme, tener
privacidad, comodidad y poder programar y acomodar las cosas
necesarias para la vida (p.e. la ropa que necesito para trabajar) y la
posibilidad de hacer un shock inmediato de comida sana para mejorarme.
Increible como suena en este mes y medio, ih nunca proveyo
espontaneamente a una camisa planchada para que vaya a trabajar,
llegando a tener que repetirme hasta cinco dias seguidos con la misma
camisa cosa que nunca en la vida habia hecho, todo no pq no lo
quisiera hacer yo, sino pq no lleve la tabla de planchar alla y por la
incomodidad que en general hay alla para todo.
Ahora el lema es TODOPASA y falta poco. Aguantar que se traslade la
oficina, aguantar que Fabian empiece a venir con la chata y eso haga
que se pueda desocupar antes el dpto.
Y soportar sin quejarse la falta de aire, la molestia del humo, y
todos los etc. hasta que nos rehagamos.
En el medio de una migraña feroz desatada creo por los triggers de
luz, aire, comida, stresores, etc. me tomo un segundo migral y un
segundo corticoide y en el medio como digo, me pongo en el plan
acondicionamiento de la oficina, o sea ponerse manos a la obra para
tener todo listo cosa de poder mudarse cuanto antes. Una vez que
tengamos eso vamos a estar bien, pq no tendremos mas los estresores.
** evitar la queja - evitar la traicion - cuidar lo que se dice
ayer [2019-02-12 mar] cuando volvia a pesar de gloriosamente estar sin
dolor de cabeza, sufri bastante estres en el transito, lo que pasa que
Fede manejando con una mano, pq alternativamente fuma o usa el celular
y distraido hablando y emocionalmente experimentando picos de
optimismo termino siendo un combo estresor, y cuando llegue ya tenia
activada la bomba quejosa a punto de tirar queja sobre lo desdichado
que era o bien "opinando" sobre lo mal que maneja el Fede haciendolo
quedar mal y eso lo escucha la Cami que luego lo cita fuera de
contexto y me hace quedar mal a mi. 
Entonces pense en el momento y me dije, lo que diga va a ser
perjudicial, lo va a afectar al Fede, y me va a terminar afectando a
mi, entonces no voy a decir nada, me voy a guardar el tema, si al
final ya lo resolvi, pq ya estoy decidido mañana a irme, y asi lo hice
y estoy contento de haberlo hecho.

Hoy paso otra situacion parecida: pensaba que el no movia nada para
que organizaramos la mudanza, y metido como estaba en el dolor, me
levante igual, y le dije sin pelear ni confrontar sino con todo el
espiritu japones de hacer las cosas que teniamos que apurar las
decisiones, y ahi nomas empezamos a movilizar las cosas.
Y al final el mismo me dijo que habia dejado las cosas en standby pq
no queria ponerme nervioso pq pensaba que yo queria esperar. O sea un
mal entendido.

O sea moraleja: resolver las cosas internamente y no quejarse afuera,
ni dar material para la citadora fuera de contexto.
** migraña fuerte N8 cursando con actividad
podria haberme tumbado a las 16hs cuando me tome el corticoide, pero
como comente me puse proactivo con lo de la oficina, y luego que se
fue Fede no me acoste de inmediato a pesar de que luego de unos
momentos empezo un destornillador clavado en mollera izquierda, sino
que me dije voy a hacer el licuado, luego lave la licuadora, luego me
anime, y lave las dos camisas, y el destornillador no cede aun.
Y van tres horas de segundo migral, creo que si me hubiera acostado
sin haber hablado lo de la oficina, hubiera maquinado mal estas tres
horas y gran parte del dolor lo hubiera achacado al Fede, y ahora
vuelvo a estar enchufado, o sea que me parece que no debo en lo
posible quedarme y no debo rumiar.
Luego me puse y planche dos camisas, y recien ahi me acoste a ver el
anteultimo capitulo de la serie (malisimo) y como se me acabo la
bateria termine prendiendo un rato la netbook, luego de comer un breve
arroz muy bien hecho con amaranto en la olla horno.
** evitar el utilitarismo y evitar el desgaste extremo
lo que estoy viendo justo en este preciso instante es que estar
acostado y tener la netbook no es compatible.
si quizas cuando uno no este muy cansado aun o un finde semana, pero
cuando uno esta reventado no vale la pena prenderla, salvo para un
breve post que realmente sea necesario sino no.
lo que vi hoy es que la prioridad es comer bien, descansar, prepararse
la ropa y disponerse a dormir.
** [2019-02-14 jue] 
hoy me levante esplendido, anoche dormi muy bien a pesar de que el
nivel de ruido era muy fuerte y del feo dia que habia tenido ayer. A
pesar de que desayune un migral hasta el momento (10.30hs) curso con
total normalidad y optimismo, unicamente empieza a molestarme un poco
la claridad excesiva y el humo del cigarrillo.
Ayer hice cosas en la casa, hoy me levante y acomode la oficina.
Hasta el momento (13hs) sigo bien, solo me pica la garganta el humo,
aunque hoy pude un poco evitar el exceso de claridad. Noto que llega
la hora de la comida y no esta la posibilidad de comer tranquilo de
forma tal que uno se relaje (pienso que al tener el dpto separado
podre venirme a comer y luego volver tranquilo a trabajar)
De golpe a pesar de que almorce perfecto, comi una compotera de arroz
bien tranquilo, bien masticado, gustosa mezclada con pasta de aceituna
y queso, y luego no tuve ningun estresor que detonara nada, es mas
durante el almuerzo el fede se fue pq tuvo que recibir los muebles, y
luego se fue a comprar el aire y yo me quede practicamente solo en el
dpto sin ninguna presion, atendiendo las llamadas, me bajo la migraña
de golpe, me tomo el segundo pero ya creo que era tarde, ya han pasado
30 minutos y parece que no hace ninguna mella. Felizmente ya no
tenemos el tema de la vuelta pq Fabian no vuelve, o sea que quizas se
corte antes. 
Solo sali un momento para una tarea minima exigencia, ir a la oficina
nueva, encontrarlo al fede, entrar el aire, volver anticipado, en el
momento pensaba, porque me vuelvo si en el trajin te parece que no
estas mal, pero si estas mal, y cuando llegas todo explota, me tomo un
cuarto de B40 o sea 10mg de cortipyren y tengo no un destornillador
sino una sensacion que me hubieran retirado parte de la mollera en
ambos lados, es algo que supera lo que yo puedo.
No sera excesivo?
Desperte a las 7 me levante a las 7.10 y desde alli estuve en tension
pq estoy "viviendo en la oficina"... y luego supongamos que cuente
desde las 7.30, son casi 7 horas al momento actual, entonces es un
tiron largo para el verano, mas que todo a nivel cabeza, tensional,
hombros, cuello, ojos, etc, lo que son los estresores, o sea que lo
tendriamos que agregar a la lista.
O sea que si sumo, una jornada larguisima sin posibilidad de relajarse
en el medio en forma real, una falta de regularidad en el almuerzo y
una falta directa de almuerzo correcto, exceso de luminosidad, humo y
no olvidarse que cuando uno esta en ese estado tambien molestan los
ruidos intensos como el telefono del fede. Todos configuran estresores que disparan el proceso migrañoso
continuamente. 
Lamentablemente estoy roto, completamente acabado, a 1.35hs de tomado
el segundo migral tengo una migraña espantosa y solo aspiro a poder
retirarme al dormitorio, poner el aire que se vaya el humo el dpto y
que se me vaya el dolor, quitandome lo que resta del dia. 
Aunque por ahi pierdo el control y quisiera autoperjudicarme, como por
ejemplo tomar migral hasta reventar, o algo asi, pienso que habiendo
detectado todos los estresores que tengo y estando tan cerca de la
liberacion seria ridiculo si no esperara y probara que pasa si me
ayudo un poco en un nuevo tipo de jornada que sea mas corta y me
permita ese mediodia relajante.
Yo propongo ir temprano tipo 8.30 hasta las 12/12.30 y luego volver
tipo 15.30 hasta la hora que quiera. Eso tambien limitara las horas de
convivencia con el Fede y facilitara las cosas en ese sentido.
** [2019-02-15 vie]
desde ayer a las 18.30 entramos en emergencia, felizmente ya habia
salido de la fase aguda de la migraña y solo quedaba resto, lo que
paso fue que la Cami habia ido al hp por sintomas de apendicitis,
luego se fue al hp central, ya tipo 21hs la Romi se viene para el dpto
y con la Cami con posibilidades de ser operada esa misma noche, me voy
al hp, y permanezco alli hasta las 0.30hs sin sintomas, sin hambre y
sin problemas. Luego pude dormir bien pero poco, me levanto y la
mañana cursa con estresores fuertes, ya que el delay de salida, de una
hora y media sin evacuacion suficiente, y el transito. 
Me tomo un B8 a las 9hs para ir previniendo un dia que sera dificil. 
Transcurre la mañana bastante bien, hasta que tipo 11.30hs tomo un te
con galletas y queso preventivamente para cubrir hambre, pq no tengo
otras alternativas, ya consumido el licuado y las galletas, y con
nerviosismo en aumento, en una situacion de tension y atrapado, pq me
gustaria estar en el hospital, pero ih esta durmiendo aca y es
hipernecesario que se recupere pq puede tener que quedarse a cuidarla
si se queda internada un dia mas, y a la vez el Fede tiene que
quedarse en la nueva oficina a esperar que le coloquen el aire
acondicionado.
A todo esto tomo un migral casi preventivo del rebote, y me preparo
con dosis para la tarde. 
Se que debo estar tranquilo pq mi mal es menor en estos momentos y
debe quedar a un lado de cosas mas importantes y agudas. Ojala se
terminen por resolver de la mejor manera.
Como dice el marco de este tree esto es una transicion, transicion de
recupero de mi espacio, y estabamos entrando en lo mas algido del
asunto, en el cambio en si, con una migraña atomica a diario, y sobre
esa situacion cae como una bomba esta situacion.
La tarde en el hp curso bastante bien sin rebote, solo con un segundo
tomado en el momento justo pero sin consecuencias tipicas del segundo
migral, o sea la migraña catastrofica.
luego llego al marques y comemos con la romi un lomito y duermo
bastante mal, pero sin dolor y el sabado comienzo otro dia de hp.
** emacs -nw equis.org
esta nueva forma de acceder a emacs con consola, y buscando el archivo
a editar por linea de comando es mas agil que buscarlo internamente, y
a la vez mas rapido, y tiene la ventaja que cuando salis podes hacer
el comit particular ahi mismo. Son pocas las cosas que no podes hacer
en modo texto, y las que vas necesitando las tenes que ir aprendiendo.
** [2019-03-16 sáb]
como pintaba a ser otro dia de hp, me tomo otro 8mg de preventivo al
comenzar la mañana y al rato un migral y todo fue muy bien, tanto en
el manejo por circunvalacion, como con la suerte del alta nos vinimos,
el sabado con el corticoide de la mañana y un solo migral anduvimos bien.
** [2019-02-17 dom]
el domingo ya no tome corticoide y se plantio la idea de no tomar
corticoides en el dia a dia, y tratar de no encarar el withdrall con
corticoides.
Y ahi me puse a leer formas de mejorar no farmacologicas, como tomar
mas agua, ser regular en comidas y sueño y otras cosas. 
Asimismo aunque no tome corticoide el domingo me tome el segundo
migral y observe como me habia pasado el miercoles y jueves que el
segundo migral fue catastrofico, o sea fue generador de dolor y fue
como si no hubiese tomado nada, o sea que para que tomar un segundo
migral, al menos estaria bueno poder permitirse la licencia de no
tener-que tomarse un segundo, ni un corticoide por "motivos de
urgencia" llamese trabajo o como viernes y sabado hospital.
Entonces ya hoy [2019-02-18 lun] me planteo que podria manejarme con
un sistema de un solo migral por dia a rajatabla, tomado mas o menos a
las 24 horas del anterior minimo, y evitando el segundo migral. En lo
posible evitar medicamentos, pero se puede probar con un ibu segun los
casos.
P.e. hoy y en medio de un dia muy complicado me tome un ibu y anduve
bien, cumpli con todo y rendi en forma sobresaliente. 
Este sistema de poder cumplirse bajaria el consumo a 30M mas ibus con
el aguante de las migrañas que haga falta, mientras voy aplicando las
medidas de cambio.
** primera reunion de socios en Rioja
[2019-02-18 lun] donde se establecio el 50/50 y el reparto de
dividendos mes a mes en forma razonable. Ambas medidas me traen
tranquilidad de espiritu a mi, pq me dejan mas en paz pq se que asi es
mas justa la division de las ganancias. Y a la vez le quita presion al
negocio el sacarle la esfera privada de la acumulacion individual de
cada uno. 
** Rioja primeras impresiones
[2019-02-18 lun] aparentemente el aire no me molesta, a la vez estoy
cerca de la ventana. La luminosidad no molesta pq esa cortina la
filtra.
Es libre de humo y eso es muy importante, extremadamente importante.
Solo por citar las cosas que me molestaron aca. 
Tambien me libero de atender la puerta y de la vista lateral de la
gente.
** distintos archivos org propuestos
*** tcl-teory
para ir volcando todo lo que vaya aprendiendo del libro
*** tcl-practica
para ir poniendo lo que vamos aplicando de lo que vamos aprendiendo.
idem para toda materia que vayamos haciendo.
*** migra
para concentrar el tratamiento cualquiera sea a partir de ahora
** [2019-02-19 mar]
anoche pensaba que tengo que irme del dpto, pero todavia no he tomado
posesion del mismo y estar tan cerca de la oficina es un
activo. Quizas haya que solucionar por el momento lo que se presente.
Pero lo decia por el tema 
** Tratamiento propuesto por William Romero el [2019-02-20 mié]
subir topiramato a 75mg
iniciar flunarizina 10mg
hacer una cortiterapia breve de 12 dias a 20mg bajando luego 3 dias a
10mg
intentar luego de 3 dias cortar el migral, pero no tener problema de
usarlo como rescate si hace falta alguna vez.
comunicarse al wnromero@hotmail.com
** [2019-02-21 jue]
*** De como tendria que haber cortado en Nov o Dic con el migral
ya con un consumo en los 40 tendria que haber hecho el withdrall en
esa epoca, pero mirando para atras es muchisimo lo que cambio. El
panorama abierto hoy no tiene nada que ver con el que se tenia en
noviembre. Pensemos que en noviembre el Fede trabajaba en la calle con
la kangoo y yo atendia la oficina por la tarde. 
Cuando yo pido la licencia por burnout al principio el FEde no sabia
nada que pasaba y medio que yo tampoco. En el fondo pensaba que si
abandonaba el barco en esa situacion podia pasar cualquier cosa, o
bien que se hundiera, o bien que sobreviviera pero sin mi
luego. Muchas veces me paso por la mente resignar mi status o
situacion pero no me cuadraba y visto desde ahora creo que hubiera
sido dificil que el Fede sobreviviera solo en ese momento.
Luego vino el cambio. Primero cuando le presto la oficina a la Romi,
luego cuando el Fede cambia a la mañana, ahi se conjugo en cierta
forma la posibilidad de que se prolongara mi receso, pq la Cami pudo
quedarse en la oficina al amparo de que la Romi estaba luego en la
ofi.Sino no se hubiera podido quedar.
Esa primera parte quizas fue la mas nociva para mi en terminos de
salud pq lo que primero fue una necesidad de tomarme un respiro devino
en una carga enorme presion. Y esa presion fue en aumento, pq en el
medio se ignoro cual habia sido la causa de toda la presion que habia
sentido en los ultimos tres meses anteriores, que era la problematica
laboral que se habia gestado. Y como esa problematica habia llevado al
escape a la tarde como posible solucion transitoria. Pero la trampa de
la tarde, lo que hizo que la tarde fuera tan dificil y me terminara
matando fue la obligatoriedad de mantener el trabajo a la Cami. Y para
hacerlo tuve que habilitar mi dpto como oficina a la mañana. Eso tuvo
el correlato de disminuir mi comodidad inmediatamente. Y como luego de
ese turno de "trabajo" insalubre para mi, pq ahi habia una sola
maquina, un solo escritorio y un aire que no enfria lo suficiente, en
fin un lugar que como oficina no es muy viable que digamos, comia mal
muchas veces pq terminaba teniendo que comer con la Cami comida
chatarra, y no podia sustraerme a tener una propia siesta antes de la
jornada de la tarde pq en cierta forma "estaba a cargo" habia que
atender llamados, pq podia llamar el Fede, los cobradores, y muy
especialmente el Fabian. 
Habria que sumarle en ese momento el problema de una lluvia de CD,
dentro del horario de entrada de cobradores, que me motivo al cambio a
la noche, y la demora en pasar las dos demandas pendientes a su curso
normal de demanda formal, pasando por vericuetos que antes no habiamos
sufrido y por lo tanto causandonos nerviosismo extra.
Haber comprendido en ese momento exactamente el motivo de mi
agotamiento hubiera buscado otra solucion alternativa: p.e. en vez de
no trabajar, que la Cami dejara de venir, y empezar a pasar los
papeles a la noche y quedarme con el dia libre, o sea concentrar mi
jornada de 17 a 21.
Era obvio que poner al FEde en la oficina me iba a causar mas
nerviosismo y ese nerviosismo iba a aumentar a medida que pasaran los
dias. Encima como una broma el primer dia de retiro entran los
albañiles en la casa y eso me produce migraña gigantes por dos o tres
dias. 
Viendo para atras ese aspecto creo que todo el tiempo que estuve
viviendo en el marques desde el retiro y luego obligado por el tema
oficina en dpto ih solo intento sacarme lo maximo que pudiera para
meter en la casa.
Cuando vino providencialmente el embargo a la oficina, nos fuimos de
un dia para el otro, al vicio, exagerado, como siempre pasa en estos
casos, pq en el fondo era improbable que volvieran en esos dias, pero
nos hicieron un maximo favor, pq dejamos esa oficina. Le hicimos un
gran favor a la Romi, que desde alli despego. que ayer facture 9300 en
un solo dia era impensado en ese aciago dia. 
Pero para que eso fuera posible hizo falta el sacrificio del dpto,
tuve que poner el dpto en disposicion para uso publico, irme a vivir
al marques un tiempo hasta que no se pudo mas.
Creo que el hito el antes y despues fue el tema compu. La demostracion
del egoismo, alli me decidi a irme, y a recuperar lo que es mio, ahi
mismo me dije que tenia que alquilar una oficina.
Y aca estamos a solo dos dias de despejar mi dpto del uso oficinal.
*** hermoso concepto de Dario S. contando una experiencia con su sicologa
dice que un dia haciendo terapia iba a contar un sueño y de repente se
le olvida entonces la terapeuta que era una mujer grande de unos 70
años, lo mira y le dice: "Invente"... y dice Dario que hubo un antes y
un despues desde alli que todo cambio
*** Dario S. promociona el clonazepan...
hay una relacion directa entre los videos escuchados en la etapa
previa al crack noviembre (unas veinte horas de video) y la cantidad
de veces que el tipo este nombre y banaliza el clonazepan, y como
desde alli no digo que comence a tomarlo, pero si creo que comence a
tomarlo a la ligera, sin medir las consecuencias, si no fuera por la
palabra justa del dentista a esta hora estaria complicado por ese
tema.
*** hoy surgieron dos ideas impresionantes para el negocio
**** que pongamos un grupo de promocion con Fabian
y que el siga ganando el 4.5% y nosotros arreglamos a los chicos.
la idea surge como consecuencia inmediata de pensar que ya se terminan
la vuelta y ambos dependen unica y exclusivamente de los datos. Y
antes que la pelea por los datos se haga imposible, y baje la venta,
tenemos que ampliar, hacer mas barrios. y no depender de los actuales unicamente. 
**** que hagamos un centro de verificacion con ih
para que no necesitemos que Fabian se autorice en calle y a la vez
podamos centralizar alli toda la autorizacion y de paso hacerlo mas
profesional y no recargarnos nosotros aca que necesitamos llegar a los
2M de facturacion y los 2M de cobranza. 
La idea nace pq primero pienso en una miniaplicacion para que fabian
se pueda autorizar solo en calle y luego pienso que no va a poder como
no podriamos nosotros, es muy dificil.
Yo hice auto-autorizacion pero sin seven, o sea una sola, no se pueden
las dos autorizaciones juntas. para eso hay que estar con maquina.
Y surge la idea de ih pq ella necesita trabajar y es la unica
disponible para hacerlo en forma de teletrabajo.
* nueva etapa
[2019-02-24 dom] hoy comienza una nueva etapa aca en el dpto y lo
lindo es tener todo limpito y tener el plan de ir acomodando todo de
nuevo con nuevos paradigmas. El nuevo libro me muestra el cambiar las
formas de pensar, cosas que hacia por repeticion o por compromiso, que
son elecciones sino viejo hardware, entonces ahi uno podria plantearse
si quiere seguir viviendo con esas pautas o quiere cambiar.
Son muchas cosas. Demasiadas.
Impactante ese estudio (en caso de ser cierto) sobre el efecto en la
salud de un grupo de mucamas que realizaban gran trabajo fisico como
es ese trabajo (p.e. atender 15 habitaciones de hotel), cuando se las
interroga sobre si hacen actividad fisica, la mayoria dice que no (o
sea que no consideraban la actividad del trabajo como "actividad
fisica"), y cuando se toma un subgrupo de ellas y se le cambia el
esquema mental para que consideren la gran actividad que hacian como
trabajo fisico valido a los fines de la salud, se vio luego de un
tiempo que su salud mejoro como si esa actividad la hubieran hecho
aparte, o sea, la actividad la hacian los dos grupos pero la mente no
consideraba que esa actividad debia rendir resultados.
Tiene varias aristas cuestionables lo mismo, pero la idea esta buena,
p.e. se me ocurre con respecto a mi, por muchos años cada vez que
tenia que plancharme una camisa la tortura no era en si la molestia
del trabajo fisico en si, sino el choque del modelo mental previo que
yo tenia por medio del cual "yo no-deberia estar planchandome las
camisas", era esa lucha mental lo que me agotaba, lo que me hacia ver
de forma negativa la tarea y la agrandaba a mas no poder. Viendolo en
retrospectiva si hubiera cambiado mi modelo mental por otro, pe. que
yo planchaba mis camisas pq de esa forma cuidaba mejor mis camisas y
me veia mas presentable, nunca hubiera perdido tiempo en otras
disquisiciones, es mas podria haber aprendido con el tiempo a planchar
mejor, me hubiera procurado una mejor plancha, una mejor tabla,
hubiera aprendido a comprar mejor las camisas pensando en los tejidos
en funcion del planchado, incluso hubiera regulado el uso de las
prendas para aprovechar el planchado. Podria incluso haber aprovechado
el tiempo de planchado en forma creativa p.e. por medio de escuchar
musica, o videos, o meditando, incluso conociendo exactamente cuanto
necesito de tiempo de planchado por semana/mes etc. 
Todo si cambiaba el esquema mental, a uno en el cual uno elige lo que
tiene, en vez de eso cada vez que planche me senti infeliz, cada vez
que contrate planchar, tambien me clave pq tuve que esperar que
plancharan, tuve que aguantar que me golpearan la plancha, que me
plancharan mal, aburrirme esperando, que me arruinaran ropa, y tuve
que pagar por planchar. Y hasta el dia de hoy cargo con el estigma de
que use el planchado para acceder a otras cosas cuando en realidad no
fue asi. Lo mismo aplica para el resto de las cosas del hogar. Esta
bien que en un contexto de trabajo a full en el cual uno tiene un
esquema de horarios agobiante no es facil decir que uno va a limpiar
su casa con alegria y va a hacer las compras, cocinar, comer, lavar
platos, lavar ropa, planchar y limpiar sin quejarse.
El tema quizas sea, reevaluar porque uno hace esquemas de trabajo
agobiantes. 
En 2017/Oct teniamos un sistema agobiante pq me habia echado encima
local, pasado de papeles, cobradores, promotores, y pasado de
datos. Pero eso no estaba bien, y luego cambio, pero gran parte del
2018 la cosa cambio, salvo quiza con el error de haber traido trabajo
a casa (en especial cuando trabajo vino con un esquema fijo y otra
persona o sea la Cami a trabajar al dpto). Luego perdi el dpto. 
Pero en un esquema razonable de trabajo se puede hacer las cosas de la
casa si uno cambia el esquema. 
OJO y no que el esquema que propongo sea el mejor, quizas lo mas
logico sea que un gerente se haga limpiar (jaja ahi caemos a otra
regla del sistema, o sea si sos gerente --> te tenes que hacer
limpiar, Como vas a andar limpiando vos la casa! o como vas a comprar
vos las cosas!) Y es justamente la disonancia de este esquema lo que
me hizo mucho daño en el pasado. Desde años lejanos donde no queria
que me vieran con una bolsita del super, o la legendaria sensacion de
looser viniendo con el bolso cargado de frutas frescas del mercado
norte en horario laboral!!!! una tarde. 
Otro esquema descubierto (oculto): no usar la ropa. No solo tengo un
esquema que me problematiza comprar ropa, mayormente por esquema no
gastar en mi, o por esquema de directa baja autoestima en momento de
comprar, o directamente quizas por creencias equivocadas sobre como
deben comportarse hacia mi los empleados de comercio del rubro, lo
cierto es que una vez tenida la ropa, soy reacio a ponermela.
Relato un ejemplo sencillo para comprender hasta donde llega este
esquema a ser dominante. Hoy domingo tenia que ir a farmacity a
comprar shampu y me tenia que vestir. De paso camino un par de cuadras
por la peatonal, no mas que eso pq como se sabe estoy en WD. El
"trabajo de vestirse es igual sea ponerse andrajos de fajina que ropa
decente", no obstante tendi a la fajina... pq supuestamente no estaba
bañado, o porque usar la ropa "de oficina" para ir a hacer una compra
es "un desperdicio". Lo cierto que ese patron se refleja en toda mi
vida y me encuentro que la ropa no la uso pq solo la uso en la
oficina, y luego cuando estoy de fines de semana uso fajina, por eso
no se gasta, y por eso no renuevo nunca. 
Ni hablemos del esquema que me hace dificultoso gastar asi sea en lo
mas basico. Recien ahora pude ir y comprar una pasta dental de 172 pq
el dentista me recomendo, y pq habia probado una que ih compro de
error y vi que era buena, sino sigo comprando la kolinos de 35
pesos. A pesar de que una pasta de esas me puede durar un mes o mas. 
Creo que no es un problema de inflacion de precios sino que cuando no
hay inflacion se disimula mas este esquema que lo tengo desde hace
decadas en las cuales han pasado muchos precios y muchas distintas
situaciones economicas mias. Solo con inflacion alta lo siento mas
urticantemente, pero el problema es el mismo.
Otro ejemplo muy patente de como el esquema te domina, fue con la
comida de hoy. Ayer hice mijo con calabazas, y comi la mitad para
guardar la mitad (ese es otro esquema que debo revisar, pq podria
haber comido mas ayer, pero me hubiera quedado poquito, para
tirar... o no pero no suficiente para un plato, en fin es una mezcla
de esquemas malos, puede estar el terror a tirar comida -por mas que
sea comida ultrabarata... no estamos tirando medio lomo de 300 mangos,
sino quizas dos cucharadasa de mijo y un poquito de calabazas con
costo que a lo mejor no llega a los 10 pesos, o bien quizas el pensar
que guardando me ahorrare una coccion, o sea tendre una comida hecha,
pero en ese caso porque cuando voy a cocinar no pongo mas, si despues
de todo los ingredientes son baratos)
Como sea la solidificacion del mijo con la calabaza adentro produce
una especie de almidon que podria producir cierto rechazo, entonces lo
quite con una cuchara, lo esparci, le puse sal del himalaya y aceite
pero sin exagerar y luego lo comi asi, no le puse queso ni sesamo, y
... me resulto delicioso y eso que estaba frio, y no tenia hambre de
morir o sea estaba normal. Me parecio que se comia solo. Un plato
equilibradisimo.
Tanto al comerlo como luego al padecerlo en el postprandial. Por eso
pienso que uno mismo cae en el gran ESQUEMA ALIMENTARIO que conduce a
la gente a comer pocos alimentos que no saben a nada y tienen que ser
condimentados al maximo para evitar el sabor que el alimento
tiene. Por eso pienso que hay que permitirse comer lo sano de cero.
* recetas
** mijo con calabazas
** yamani con amaranto y queso
