* alimentacion
** teoria
[2019-02-08 vie] de acuerdo a las ultimas lecturas, que no vienen mal
pq vienen a retomar el tema y a advertir sobre la caca institucional
que es el sistema en eso de envenenarnos y naturalizar soretes para
comer hay que hacer eje principal en el alimento, luego en el
ejercicio.
** licuados
ese tiene que ser el eje principal. Ahi se puede vehiculizar el 80% de
las necesidades de nutricion y saciedad del dia. La potencia del
licuado esta en que permite reemplazar basura. Tengo que buscar la perfeccion en
eso, hay muchas ideas que puedo desarrollar:
*** buscar avena organica
*** probar multiples semillas
*** probar multiples complementos
*** variar frutas
*** hacer variantes no tan fuertes o mas tipo leche
*** ver de hacer dos tandas por dia pero distintas
*** ir variando para no cansarse
*** hacer "premezclas" para un licuado en una bolsita
en caso ir al marques p.e. no es lo mismo no tener nada o llevar
frascos que llevar una bolsita, activar y licuar.
** ensaladas
otro item totalmente descuidado y dejado de lado historicamente de la
dieta y no porque sea feo, es la ensalada, que puede ser tambien
variada hasta el infinito y pasar de ser un minicomplemento hasta un
plato semiprincipal. 
desde un poquito de repollo, unos rabanitos, lechiguita, zanahoria
rallada, etc, etc, es infinito y se le puede agregar tambien de todo.
** pastas bases
arroz bien cocido y mijo.
tanto para una opcion dulce para una merienda, p.e. con una porcion de
arroz una manzana o pera rallada y una leche simple, como la misma
pasta base con una ensalada de cualquier cosa para un almuerzo. 
** evitar los venenos
*** hay que estar mas atento 
la lectura concientiza: hoy comia unas rodajas del pan fargo ese que
tenemos ahi, con queso. La verdad, repugnante, y ahi caigo en la
cuenta como hemos naturalizado eso de la fecha de vencimiento, como
algo valido que "valida" un producto hasta esa fecha mas alla si es
viable que un equis producto dure o como hace para durar hasta esa
fecha, no ya tan solo en conservantes como para que no se eche a
perder sino en alteradores de su intrinseca naturaleza para que se
mantenga en este caso el pan esponjoso tantos dias. O sea que estas
consumiento vaya a saber que cocktail de quimicos. Pero en realidad
somos nosotros lo que descuidadamente consumimos un producto que no es
para durar como durable.
* transicion
[2019-02-11 lun] la transicion esta vez se torna alarmante. Debo
buscar la forma de soportar hasta que llegue el momento del despegue
de la situacion.
Lo cual lo veo lejano en el momento actual. Porque a la oficina le
quedan un numero indeterminado de dias para poder irnos. (Pero al
menos ya hemos firmado y estamos dentro). Y tambien se exacerba con la
situacion en la casa de dormir poco y mal porque la Cami se levanta
muy temprano. No puedo ir haciendo nada por aca pq estamos limitados.

Lo que se me ocurre es irme quedando aca, hacer la base basica de
licuado comprando chia, pasas uva almendra, avena y peras, cosa de
poder hacer el licuado a la mañana, y quien dice que tambien pueda
hervir el yamani a la noche y tener para comer a la noche y hasta el
mediodia empezando a transicionar. Incluso se me facilitaria estos
dias quedarme pq puedo dormir mas, prepararme mejor la ropa y evitar
el estres de la ida y la vuelta.
y ya puedo ir ganando tiempo haciendo cosas por mi.
