* alimentacion
** teoria
[2019-02-08 vie] de acuerdo a las ultimas lecturas, que no vienen mal
pq vienen a retomar el tema y a advertir sobre la caca institucional
que es el sistema en eso de envenenarnos y naturalizar soretes para
comer hay que hacer eje principal en el alimento, luego en el
ejercicio.
** licuados
ese tiene que ser el eje principal. Ahi se puede vehiculizar el 80% de
las necesidades de nutricion y saciedad del dia. La potencia del
licuado esta en que permite reemplazar basura. Tengo que buscar la perfeccion en
eso, hay muchas ideas que puedo desarrollar:
*** buscar avena organica
*** probar multiples semillas
*** probar multiples complementos
*** variar frutas
*** hacer variantes no tan fuertes o mas tipo leche
*** ver de hacer dos tandas por dia pero distintas
*** ir variando para no cansarse
*** hacer "premezclas" para un licuado en una bolsita
en caso ir al marques p.e. no es lo mismo no tener nada o llevar
frascos que llevar una bolsita, activar y licuar.
** ensaladas
otro item totalmente descuidado y dejado de lado historicamente de la
dieta y no porque sea feo, es la ensalada, que puede ser tambien
variada hasta el infinito y pasar de ser un minicomplemento hasta un
plato semiprincipal. 
desde un poquito de repollo, unos rabanitos, lechiguita, zanahoria
rallada, etc, etc, es infinito y se le puede agregar tambien de todo.
** pastas bases
arroz bien cocido y mijo.
tanto para una opcion dulce para una merienda, p.e. con una porcion de
arroz una manzana o pera rallada y una leche simple, como la misma
pasta base con una ensalada de cualquier cosa para un almuerzo. 
** evitar los venenos
*** hay que estar mas atento 
la lectura concientiza: hoy comia unas rodajas del pan fargo ese que
tenemos ahi, con queso. La verdad, repugnante, y ahi caigo en la
cuenta como hemos naturalizado eso de la fecha de vencimiento, como
algo valido que "valida" un producto hasta esa fecha mas alla si es
viable que un equis producto dure o como hace para durar hasta esa
fecha, no ya tan solo en conservantes como para que no se eche a
perder sino en alteradores de su intrinseca naturaleza para que se
mantenga en este caso el pan esponjoso tantos dias. O sea que estas
consumiento vaya a saber que cocktail de quimicos. Pero en realidad
somos nosotros lo que descuidadamente consumimos un producto que no es
para durar como durable.
* transicion
[2019-02-12 mar] anoche me quede con bastante buen resultado pq
significo muchas horas de tranquilidad. A pesar de la mala experiencia
en el medio de la prueba con las redes que me canso y estreso (aunque
termino bien pq se termina con una situacion ssh en vez de la anterior
y es mas rapida)
La comida fue mejor, mucho mas tranquila y las horas que se pudo pasar
descansando fueron mas. Hoy compre algunas cosas mas en alimentos y me
decido a no reparar en gastos en ningun sentido, ni en comida ni en el
dpto ni en ropa.
[2019-02-11 lun] la transicion esta vez se torna alarmante. Debo
buscar la forma de soportar hasta que llegue el momento del despegue
de la situacion.
Lo cual lo veo lejano en el momento actual. Porque a la oficina le
quedan un numero indeterminado de dias para poder irnos. (Pero al
menos ya hemos firmado y estamos dentro). Y tambien se exacerba con la
situacion en la casa de dormir poco y mal porque la Cami se levanta
muy temprano. No puedo ir haciendo nada por aca pq estamos limitados.

Lo que se me ocurre es irme quedando aca, hacer la base basica de
licuado comprando chia, pasas uva almendra, avena y peras, cosa de
poder hacer el licuado a la mañana, y quien dice que tambien pueda
hervir el yamani a la noche y tener para comer a la noche y hasta el
mediodia empezando a transicionar. Incluso se me facilitaria estos
dias quedarme pq puedo dormir mas, prepararme mejor la ropa y evitar
el estres de la ida y la vuelta.
y ya puedo ir ganando tiempo haciendo cosas por mi.
** el problema aca
[2019-02-11 lun] a hoy es el bajon o parate programatico que hace que
uno no aproveche el tiempo, o que cuando se sienta cansado no pueda
descansar y tenga que seguir en actividad y compartir la oficina. Pero
creo que pueda llegar a cambiar cuando recupere el dpto. 
** [2019-02-13 mié] 
hoy me mude definitivamente al dpto en forma anticipada, traje lo que
pude en los dos bolsos y seguramente olvide algunas otras cosas, y ya
la Romi me pidio el placard. No es mi voluntad volver pero debo tomar
nota de como son las cosas. 
Hoy cuando venia con el Fede le comentaba el estado de mi salud a
proposito del turno del neurologo (que al final es el miercoles que
viene y me fui al vicio al hp) y se crea una situacion complicada pq
no se aisla la parte medica de la parte familiar, como pasa con el
trabajo. 
Por eso como le decia esta mañana a ih me siento en soledad absoluta,
no solo para enfrentar el momento delicado actual sino para poder
comunicar lo mal que me encuentro. 
Para hacerla breve y quitarle el melodrama, creo que el problema es
viejo y es el mismo de siempre, basta con leer la cronica de cualquier
epoca, lo que cambio y lo que me falta es que por primera vez en
muchos años (hay que volver al breve e ingrato tiempo de herrera y
guzman del 2011/2 y luego al 2004) que me encuentro sin sitio
propio. Malo o bueno, el sitio propio me permitia aislarme, tener
privacidad, comodidad y poder programar y acomodar las cosas
necesarias para la vida (p.e. la ropa que necesito para trabajar) y la
posibilidad de hacer un shock inmediato de comida sana para mejorarme.
Increible como suena en este mes y medio, ih nunca proveyo
espontaneamente a una camisa planchada para que vaya a trabajar,
llegando a tener que repetirme hasta cinco dias seguidos con la misma
camisa cosa que nunca en la vida habia hecho, todo no pq no lo
quisiera hacer yo, sino pq no lleve la tabla de planchar alla y por la
incomodidad que en general hay alla para todo.
Ahora el lema es TODOPASA y falta poco. Aguantar que se traslade la
oficina, aguantar que Fabian empiece a venir con la chata y eso haga
que se pueda desocupar antes el dpto.
Y soportar sin quejarse la falta de aire, la molestia del humo, y
todos los etc. hasta que nos rehagamos.
En el medio de una migraña feroz desatada creo por los triggers de
luz, aire, comida, stresores, etc. me tomo un segundo migral y un
segundo corticoide y en el medio como digo, me pongo en el plan
acondicionamiento de la oficina, o sea ponerse manos a la obra para
tener todo listo cosa de poder mudarse cuanto antes. Una vez que
tengamos eso vamos a estar bien, pq no tendremos mas los estresores.
** evitar la queja - evitar la traicion - cuidar lo que se dice
ayer [2019-02-12 mar] cuando volvia a pesar de gloriosamente estar sin
dolor de cabeza, sufri bastante estres en el transito, lo que pasa que
Fede manejando con una mano, pq alternativamente fuma o usa el celular
y distraido hablando y emocionalmente experimentando picos de
optimismo termino siendo un combo estresor, y cuando llegue ya tenia
activada la bomba quejosa a punto de tirar queja sobre lo desdichado
que era o bien "opinando" sobre lo mal que maneja el Fede haciendolo
quedar mal y eso lo escucha la Cami que luego lo cita fuera de
contexto y me hace quedar mal a mi. 
Entonces pense en el momento y me dije, lo que diga va a ser
perjudicial, lo va a afectar al Fede, y me va a terminar afectando a
mi, entonces no voy a decir nada, me voy a guardar el tema, si al
final ya lo resolvi, pq ya estoy decidido mañana a irme, y asi lo hice
y estoy contento de haberlo hecho.

Hoy paso otra situacion parecida: pensaba que el no movia nada para
que organizaramos la mudanza, y metido como estaba en el dolor, me
levante igual, y le dije sin pelear ni confrontar sino con todo el
espiritu japones de hacer las cosas que teniamos que apurar las
decisiones, y ahi nomas empezamos a movilizar las cosas.
Y al final el mismo me dijo que habia dejado las cosas en standby pq
no queria ponerme nervioso pq pensaba que yo queria esperar. O sea un
mal entendido.

O sea moraleja: resolver las cosas internamente y no quejarse afuera,
ni dar material para la citadora fuera de contexto.
** migraña fuerte N8 cursando con actividad
podria haberme tumbado a las 16hs cuando me tome el corticoide, pero
como comente me puse proactivo con lo de la oficina, y luego que se
fue Fede no me acoste de inmediato a pesar de que luego de unos
momentos empezo un destornillador clavado en mollera izquierda, sino
que me dije voy a hacer el licuado, luego lave la licuadora, luego me
anime, y lave las dos camisas, y el destornillador no cede aun.
Y van tres horas de segundo migral, creo que si me hubiera acostado
sin haber hablado lo de la oficina, hubiera maquinado mal estas tres
horas y gran parte del dolor lo hubiera achacado al Fede, y ahora
vuelvo a estar enchufado, o sea que me parece que no debo en lo
posible quedarme y no debo rumiar.
