* alimentacion
** teoria
[2019-02-08 vie] de acuerdo a las ultimas lecturas, que no vienen mal
pq vienen a retomar el tema y a advertir sobre la caca institucional
que es el sistema en eso de envenenarnos y naturalizar soretes para
comer hay que hacer eje principal en el alimento, luego en el
ejercicio.
** licuados
ese tiene que ser el eje principal. Ahi se puede vehiculizar el 80% de
las necesidades de nutricion y saciedad del dia. La potencia del
licuado esta en que permite reemplazar basura. Tengo que buscar la perfeccion en
eso, hay muchas ideas que puedo desarrollar:
*** buscar avena organica
*** probar multiples semillas
*** probar multiples complementos
*** variar frutas
*** hacer variantes no tan fuertes o mas tipo leche
*** ver de hacer dos tandas por dia pero distintas
*** ir variando para no cansarse
*** hacer "premezclas" para un licuado en una bolsita
en caso ir al marques p.e. no es lo mismo no tener nada o llevar
frascos que llevar una bolsita, activar y licuar.
** ensaladas
otro item totalmente descuidado y dejado de lado historicamente de la
dieta y no porque sea feo, es la ensalada, que puede ser tambien
variada hasta el infinito y pasar de ser un minicomplemento hasta un
plato semiprincipal. 
desde un poquito de repollo, unos rabanitos, lechiguita, zanahoria
rallada, etc, etc, es infinito y se le puede agregar tambien de todo.
** pastas bases
arroz bien cocido y mijo.
tanto para una opcion dulce para una merienda, p.e. con una porcion de
arroz una manzana o pera rallada y una leche simple, como la misma
pasta base con una ensalada de cualquier cosa para un almuerzo. 
** evitar los venenos
*** hay que estar mas atento 
la lectura concientiza: hoy comia unas rodajas del pan fargo ese que
tenemos ahi, con queso. La verdad, repugnante, y ahi caigo en la
cuenta como hemos naturalizado eso de la fecha de vencimiento, como
algo valido que "valida" un producto hasta esa fecha mas alla si es
viable que un equis producto dure o como hace para durar hasta esa
fecha, no ya tan solo en conservantes como para que no se eche a
perder sino en alteradores de su intrinseca naturaleza para que se
mantenga en este caso el pan esponjoso tantos dias. O sea que estas
consumiento vaya a saber que cocktail de quimicos. Pero en realidad
somos nosotros lo que descuidadamente consumimos un producto que no es
para durar como durable.
* transicion
[2019-02-12 mar] anoche me quede con bastante buen resultado pq
significo muchas horas de tranquilidad. A pesar de la mala experiencia
en el medio de la prueba con las redes que me canso y estreso (aunque
termino bien pq se termina con una situacion ssh en vez de la anterior
y es mas rapida)
La comida fue mejor, mucho mas tranquila y las horas que se pudo pasar
descansando fueron mas. Hoy compre algunas cosas mas en alimentos y me
decido a no reparar en gastos en ningun sentido, ni en comida ni en el
dpto ni en ropa.
[2019-02-11 lun] la transicion esta vez se torna alarmante. Debo
buscar la forma de soportar hasta que llegue el momento del despegue
de la situacion.
Lo cual lo veo lejano en el momento actual. Porque a la oficina le
quedan un numero indeterminado de dias para poder irnos. (Pero al
menos ya hemos firmado y estamos dentro). Y tambien se exacerba con la
situacion en la casa de dormir poco y mal porque la Cami se levanta
muy temprano. No puedo ir haciendo nada por aca pq estamos limitados.

Lo que se me ocurre es irme quedando aca, hacer la base basica de
licuado comprando chia, pasas uva almendra, avena y peras, cosa de
poder hacer el licuado a la mañana, y quien dice que tambien pueda
hervir el yamani a la noche y tener para comer a la noche y hasta el
mediodia empezando a transicionar. Incluso se me facilitaria estos
dias quedarme pq puedo dormir mas, prepararme mejor la ropa y evitar
el estres de la ida y la vuelta.
y ya puedo ir ganando tiempo haciendo cosas por mi.
** el problema aca
[2019-02-11 lun] a hoy es el bajon o parate programatico que hace que
uno no aproveche el tiempo, o que cuando se sienta cansado no pueda
descansar y tenga que seguir en actividad y compartir la oficina. Pero
creo que pueda llegar a cambiar cuando recupere el dpto. 
** [2019-02-13 mié] 
hoy me mude definitivamente al dpto en forma anticipada, traje lo que
pude en los dos bolsos y seguramente olvide algunas otras cosas, y ya
la Romi me pidio el placard. No es mi voluntad volver pero debo tomar
nota de como son las cosas. 
Hoy cuando venia con el Fede le comentaba el estado de mi salud a
proposito del turno del neurologo (que al final es el miercoles que
viene y me fui al vicio al hp) y se crea una situacion complicada pq
no se aisla la parte medica de la parte familiar, como pasa con el
trabajo. 
Por eso como le decia esta mañana a ih me siento en soledad absoluta,
no solo para enfrentar el momento delicado actual sino para poder
comunicar lo mal que me encuentro. 
Para hacerla breve y quitarle el melodrama, creo que el problema es
viejo y es el mismo de siempre, basta con leer la cronica de cualquier
epoca, lo que cambio y lo que me falta es que por primera vez en
muchos años (hay que volver al breve e ingrato tiempo de herrera y
guzman del 2011/2 y luego al 2004) que me encuentro sin sitio
propio. Malo o bueno, el sitio propio me permitia aislarme, tener
privacidad, comodidad y poder programar y acomodar las cosas
necesarias para la vida (p.e. la ropa que necesito para trabajar) y la
posibilidad de hacer un shock inmediato de comida sana para mejorarme.
Increible como suena en este mes y medio, ih nunca proveyo
espontaneamente a una camisa planchada para que vaya a trabajar,
llegando a tener que repetirme hasta cinco dias seguidos con la misma
camisa cosa que nunca en la vida habia hecho, todo no pq no lo
quisiera hacer yo, sino pq no lleve la tabla de planchar alla y por la
incomodidad que en general hay alla para todo.
Ahora el lema es TODOPASA y falta poco. Aguantar que se traslade la
oficina, aguantar que Fabian empiece a venir con la chata y eso haga
que se pueda desocupar antes el dpto.
Y soportar sin quejarse la falta de aire, la molestia del humo, y
todos los etc. hasta que nos rehagamos.
En el medio de una migraña feroz desatada creo por los triggers de
luz, aire, comida, stresores, etc. me tomo un segundo migral y un
segundo corticoide y en el medio como digo, me pongo en el plan
acondicionamiento de la oficina, o sea ponerse manos a la obra para
tener todo listo cosa de poder mudarse cuanto antes. Una vez que
tengamos eso vamos a estar bien, pq no tendremos mas los estresores.
** evitar la queja - evitar la traicion - cuidar lo que se dice
ayer [2019-02-12 mar] cuando volvia a pesar de gloriosamente estar sin
dolor de cabeza, sufri bastante estres en el transito, lo que pasa que
Fede manejando con una mano, pq alternativamente fuma o usa el celular
y distraido hablando y emocionalmente experimentando picos de
optimismo termino siendo un combo estresor, y cuando llegue ya tenia
activada la bomba quejosa a punto de tirar queja sobre lo desdichado
que era o bien "opinando" sobre lo mal que maneja el Fede haciendolo
quedar mal y eso lo escucha la Cami que luego lo cita fuera de
contexto y me hace quedar mal a mi. 
Entonces pense en el momento y me dije, lo que diga va a ser
perjudicial, lo va a afectar al Fede, y me va a terminar afectando a
mi, entonces no voy a decir nada, me voy a guardar el tema, si al
final ya lo resolvi, pq ya estoy decidido mañana a irme, y asi lo hice
y estoy contento de haberlo hecho.

Hoy paso otra situacion parecida: pensaba que el no movia nada para
que organizaramos la mudanza, y metido como estaba en el dolor, me
levante igual, y le dije sin pelear ni confrontar sino con todo el
espiritu japones de hacer las cosas que teniamos que apurar las
decisiones, y ahi nomas empezamos a movilizar las cosas.
Y al final el mismo me dijo que habia dejado las cosas en standby pq
no queria ponerme nervioso pq pensaba que yo queria esperar. O sea un
mal entendido.

O sea moraleja: resolver las cosas internamente y no quejarse afuera,
ni dar material para la citadora fuera de contexto.
** migraña fuerte N8 cursando con actividad
podria haberme tumbado a las 16hs cuando me tome el corticoide, pero
como comente me puse proactivo con lo de la oficina, y luego que se
fue Fede no me acoste de inmediato a pesar de que luego de unos
momentos empezo un destornillador clavado en mollera izquierda, sino
que me dije voy a hacer el licuado, luego lave la licuadora, luego me
anime, y lave las dos camisas, y el destornillador no cede aun.
Y van tres horas de segundo migral, creo que si me hubiera acostado
sin haber hablado lo de la oficina, hubiera maquinado mal estas tres
horas y gran parte del dolor lo hubiera achacado al Fede, y ahora
vuelvo a estar enchufado, o sea que me parece que no debo en lo
posible quedarme y no debo rumiar.
Luego me puse y planche dos camisas, y recien ahi me acoste a ver el
anteultimo capitulo de la serie (malisimo) y como se me acabo la
bateria termine prendiendo un rato la netbook, luego de comer un breve
arroz muy bien hecho con amaranto en la olla horno.
** evitar el utilitarismo y evitar el desgaste extremo
lo que estoy viendo justo en este preciso instante es que estar
acostado y tener la netbook no es compatible.
si quizas cuando uno no este muy cansado aun o un finde semana, pero
cuando uno esta reventado no vale la pena prenderla, salvo para un
breve post que realmente sea necesario sino no.
lo que vi hoy es que la prioridad es comer bien, descansar, prepararse
la ropa y disponerse a dormir.
** [2019-02-14 jue] 
hoy me levante esplendido, anoche dormi muy bien a pesar de que el
nivel de ruido era muy fuerte y del feo dia que habia tenido ayer. A
pesar de que desayune un migral hasta el momento (10.30hs) curso con
total normalidad y optimismo, unicamente empieza a molestarme un poco
la claridad excesiva y el humo del cigarrillo.
Ayer hice cosas en la casa, hoy me levante y acomode la oficina.
Hasta el momento (13hs) sigo bien, solo me pica la garganta el humo,
aunque hoy pude un poco evitar el exceso de claridad. Noto que llega
la hora de la comida y no esta la posibilidad de comer tranquilo de
forma tal que uno se relaje (pienso que al tener el dpto separado
podre venirme a comer y luego volver tranquilo a trabajar)
De golpe a pesar de que almorce perfecto, comi una compotera de arroz
bien tranquilo, bien masticado, gustosa mezclada con pasta de aceituna
y queso, y luego no tuve ningun estresor que detonara nada, es mas
durante el almuerzo el fede se fue pq tuvo que recibir los muebles, y
luego se fue a comprar el aire y yo me quede practicamente solo en el
dpto sin ninguna presion, atendiendo las llamadas, me bajo la migraña
de golpe, me tomo el segundo pero ya creo que era tarde, ya han pasado
30 minutos y parece que no hace ninguna mella. Felizmente ya no
tenemos el tema de la vuelta pq Fabian no vuelve, o sea que quizas se
corte antes. 
Solo sali un momento para una tarea minima exigencia, ir a la oficina
nueva, encontrarlo al fede, entrar el aire, volver anticipado, en el
momento pensaba, porque me vuelvo si en el trajin te parece que no
estas mal, pero si estas mal, y cuando llegas todo explota, me tomo un
cuarto de B40 o sea 10mg de cortipyren y tengo no un destornillador
sino una sensacion que me hubieran retirado parte de la mollera en
ambos lados, es algo que supera lo que yo puedo.
No sera excesivo?
Desperte a las 7 me levante a las 7.10 y desde alli estuve en tension
pq estoy "viviendo en la oficina"... y luego supongamos que cuente
desde las 7.30, son casi 7 horas al momento actual, entonces es un
tiron largo para el verano, mas que todo a nivel cabeza, tensional,
hombros, cuello, ojos, etc, lo que son los estresores, o sea que lo
tendriamos que agregar a la lista.
O sea que si sumo, una jornada larguisima sin posibilidad de relajarse
en el medio en forma real, una falta de regularidad en el almuerzo y
una falta directa de almuerzo correcto, exceso de luminosidad, humo y
no olvidarse que cuando uno esta en ese estado tambien molestan los
ruidos intensos como el telefono del fede. Todos configuran estresores que disparan el proceso migrañoso
continuamente. 
Lamentablemente estoy roto, completamente acabado, a 1.35hs de tomado
el segundo migral tengo una migraña espantosa y solo aspiro a poder
retirarme al dormitorio, poner el aire que se vaya el humo el dpto y
que se me vaya el dolor, quitandome lo que resta del dia. 
Aunque por ahi pierdo el control y quisiera autoperjudicarme, como por
ejemplo tomar migral hasta reventar, o algo asi, pienso que habiendo
detectado todos los estresores que tengo y estando tan cerca de la
liberacion seria ridiculo si no esperara y probara que pasa si me
ayudo un poco en un nuevo tipo de jornada que sea mas corta y me
permita ese mediodia relajante.
Yo propongo ir temprano tipo 8.30 hasta las 12/12.30 y luego volver
tipo 15.30 hasta la hora que quiera. Eso tambien limitara las horas de
convivencia con el Fede y facilitara las cosas en ese sentido.
** [2019-02-15 vie]
desde ayer a las 18.30 entramos en emergencia, felizmente ya habia
salido de la fase aguda de la migraña y solo quedaba resto, lo que
paso fue que la Cami habia ido al hp por sintomas de apendicitis,
luego se fue al hp central, ya tipo 21hs la Romi se viene para el dpto
y con la Cami con posibilidades de ser operada esa misma noche, me voy
al hp, y permanezco alli hasta las 0.30hs sin sintomas, sin hambre y
sin problemas. Luego pude dormir bien pero poco, me levanto y la
mañana cursa con estresores fuertes, ya que el delay de salida, de una
hora y media sin evacuacion suficiente, y el transito. 
Me tomo un B8 a las 9hs para ir previniendo un dia que sera dificil. 
Transcurre la mañana bastante bien, hasta que tipo 11.30hs tomo un te
con galletas y queso preventivamente para cubrir hambre, pq no tengo
otras alternativas, ya consumido el licuado y las galletas, y con
nerviosismo en aumento, en una situacion de tension y atrapado, pq me
gustaria estar en el hospital, pero ih esta durmiendo aca y es
hipernecesario que se recupere pq puede tener que quedarse a cuidarla
si se queda internada un dia mas, y a la vez el Fede tiene que
quedarse en la nueva oficina a esperar que le coloquen el aire
acondicionado.
A todo esto tomo un migral casi preventivo del rebote, y me preparo
con dosis para la tarde. 
Se que debo estar tranquilo pq mi mal es menor en estos momentos y
debe quedar a un lado de cosas mas importantes y agudas. Ojala se
terminen por resolver de la mejor manera.
Como dice el marco de este tree esto es una transicion, transicion de
recupero de mi espacio, y estabamos entrando en lo mas algido del
asunto, en el cambio en si, con una migraña atomica a diario, y sobre
esa situacion cae como una bomba esta situacion.
La tarde en el hp curso bastante bien sin rebote, solo con un segundo
tomado en el momento justo pero sin consecuencias tipicas del segundo
migral, o sea la migraña catastrofica.
luego llego al marques y comemos con la romi un lomito y duermo
bastante mal, pero sin dolor y el sabado comienzo otro dia de hp.
** emacs -nw equis.org
esta nueva forma de acceder a emacs con consola, y buscando el archivo
a editar por linea de comando es mas agil que buscarlo internamente, y
a la vez mas rapido, y tiene la ventaja que cuando salis podes hacer
el comit particular ahi mismo. Son pocas las cosas que no podes hacer
en modo texto, y las que vas necesitando las tenes que ir aprendiendo.
** [2019-03-16 sáb]
como pintaba a ser otro dia de hp, me tomo otro 8mg de preventivo al
comenzar la mañana y al rato un migral y todo fue muy bien, tanto en
el manejo por circunvalacion, como con la suerte del alta nos vinimos,
el sabado con el corticoide de la mañana y un solo migral anduvimos bien.
** [2019-02-17 dom]
el domingo ya no tome corticoide y se plantio la idea de no tomar
corticoides en el dia a dia, y tratar de no encarar el withdrall con
corticoides.
Y ahi me puse a leer formas de mejorar no farmacologicas, como tomar
mas agua, ser regular en comidas y sueño y otras cosas. 
Asimismo aunque no tome corticoide el domingo me tome el segundo
migral y observe como me habia pasado el miercoles y jueves que el
segundo migral fue catastrofico, o sea fue generador de dolor y fue
como si no hubiese tomado nada, o sea que para que tomar un segundo
migral, al menos estaria bueno poder permitirse la licencia de no
tener-que tomarse un segundo, ni un corticoide por "motivos de
urgencia" llamese trabajo o como viernes y sabado hospital.
Entonces ya hoy [2019-02-18 lun] me planteo que podria manejarme con
un sistema de un solo migral por dia a rajatabla, tomado mas o menos a
las 24 horas del anterior minimo, y evitando el segundo migral. En lo
posible evitar medicamentos, pero se puede probar con un ibu segun los
casos.
P.e. hoy y en medio de un dia muy complicado me tome un ibu y anduve
bien, cumpli con todo y rendi en forma sobresaliente. 
Este sistema de poder cumplirse bajaria el consumo a 30M mas ibus con
el aguante de las migrañas que haga falta, mientras voy aplicando las
medidas de cambio.
** primera reunion de socios en Rioja
[2019-02-18 lun] donde se establecio el 50/50 y el reparto de
dividendos mes a mes en forma razonable. Ambas medidas me traen
tranquilidad de espiritu a mi, pq me dejan mas en paz pq se que asi es
mas justa la division de las ganancias. Y a la vez le quita presion al
negocio el sacarle la esfera privada de la acumulacion individual de
cada uno. 
** Rioja primeras impresiones
[2019-02-18 lun] aparentemente el aire no me molesta, a la vez estoy
cerca de la ventana. La luminosidad no molesta pq esa cortina la
filtra.
Es libre de humo y eso es muy importante, extremadamente importante.
Solo por citar las cosas que me molestaron aca. 
Tambien me libero de atender la puerta y de la vista lateral de la
gente.
** distintos archivos org propuestos
*** tcl-teory
para ir volcando todo lo que vaya aprendiendo del libro
*** tcl-practica
para ir poniendo lo que vamos aplicando de lo que vamos aprendiendo.
idem para toda materia que vayamos haciendo.
*** migra
para concentrar el tratamiento cualquiera sea a partir de ahora

