* Hacia la organizacion de los archivos en orgmode 		   :org:mode:
[2016-10-04 mar]
La idea es establecer un orden basico de tipos de archivos a llevar
segun la funcion
** Esquema de archivos
*** pro proyectos
Posiblemente un archivo por proyecto relevante, con su conteo de
tiempo establecido.
Puede que se haga uno general en el cual se contengan proyectos mas
pequeños o todavia no categorizados
*** art articulos
Seria el espacio para todos aquellos temas o analisis no categorizados
aun en los otros items mas especificos. P.e. aqui puede nacer un
proyecto, o puede nacer una materia de estudio, mientras tanto es un
lugar general.
*** dia diario
Son las bitacoras que se especifican por dia con fecha inactiva. 
*** edu estudio
Son contenedores de un tema lo suficientemente relevante como para
tener su propio archivo, como ha sido hasta ahora emacs y orgmode
*** especificos
Serian los trabajos especificos como el "manual de usuario" que estaba
escribiendo para la aplicacion.

** Justificacion
En un comienzo pense que las posibilidades del outline permitirian
tener un solo archivo general para todo, donde uno trabajaria en la
parte que quisiera y todo estaria junto. Pronto muy pronto se me
complico y los dos archivos que tengo resultaron ilegibles e
intrabajables.

Luego me percato que tengo facilidades globales a disposicion
- agenda de orgmode se fija en todos los archivos del directorio que
  le indiques
- git te actualiza o te puede versionar todo un directorio, solo con
  hacer git add .
- los links internos te pueden permitir referenciar o bien hacer un
  indice general para no perder de vista nada. p.e. en un lugar pueden
  estar indizados todos los proyectos con su link y no tener que
  revisar un dired
Entonces no tiene sentido trabajar sobre un solo archivo.

** Metodos de trabajo
Se pueden ir adoptando metodos de trabajo que sean coherentes.
Por ejemplo:
- Un articulo por encabezado principal
- Fechar el comienzo y quizas tambien las revisiones futuras

** Conceptos relativos a la escritura
*** Concepto mantener la mente libre de cosas
o sea una vez que uno vuelca una idea o proyecto o lista en un archivo
convenientemente ubicado, la mente queda libre de tener la sensacion
que hay cositas que se puedan olvidar o perder
*** Concepto escribir cuando tengamos cosas que decir
No forzarse, sino dejar que fluya. De ultima tener una seccion de
escritos desganados o forzados.



* seguridad en la red 
[2016-10-12 mié]
Objetivo seria salirse de los servicios de google y tratar de tener
los datos mas resguardados.
En realidad hoy vine con la idea de aprender a enviar mail por emacs y
termine con la idea de usar mega/mailencriptado/planilla ods lo cual
aparte de mejorar un poco la seguridad termina por hacer mas fluido el
trabajo.


** mail seguro
hfj000@protonmail.com

** subidas de bd en mega
transferencia via mandar por mail el enlace para que lo baje
directamente Fede en su casa.

** compus en lugares inseguros con el sistema que tengo en la ofi.
es un perno cargar esa clave pero te quedas tranquilo que todo el
disco esta seguro.

** gitlab
esta a nombre de heroasam y hfj024, pero envia y recibe archivos con
ssh y su clave generada en las compus locales. Y aparte cada bajada
tiene una contraseña. 
Y yo soy el unico que tengo ese nivel de manejo y el conocimiento de
la existencia del repositorio.

** planilla de caja en el drive de gruposalvay
era un pain, y pienso que usando una en libreoffice y giteandola en el
mismo repositorio del sistema y luego enviandola por mail tenemos no
solo mas seguridad sino mas agil mi trabajo.


** Consideraciones generales
*** creo que de seguridad no se un pomo
y lo peor es que uno es muy descuidado pq piensa que no es target de
nadie. por eso creo que llego la hora de limpiar un poco

*** Objetivos
1) Eliminar la cuenta gruposalvay
2) limpiar el mail de referencias al negocio
3) aprender un poco mas sobre seguridad
4) TODO hacer un script o un alias para generar el tar automaticamente

#+BEGIN_SRC bash
tar cvfz rx$(date +%F) rx/romitex.db rx/auxiliar.db py1local/pcrx.ods
#+END_SRC

En realidad las funciones repetitivas deberian estar codificadas con
bash.







