* TODO
** DONE generar un modelo en pgmodeler estilizado
- State "DONE"       from "TODO"       [2019-05-08 mié 15:04]
seria primero en 9.6 sin serial ni sequence solo primary key
eliminando los campos que no se usan.
generar el source en sql, editarlo y luego adosarlo en un escript con
pg_execute, para subirlo, con drops antes.
incluir los create functions.
Ya se hizo y funciona rapidamente, borra y recrea las tablas.
** usaremos primarykey unicamente y generaremos el id por tcl
las tablas sin el serial o el sequence permiten el llenado con csv en
el caso de barrios,zonas, en el caso de clientes dio un error ya en
los datos, que fue por datos de tipo money no aceptados en el formato
en que se presentaban.
El escript propio esta corriendo para clientes solo y va muy lento y
todavia no se si va a ser grabado. 
** [2019-05-08 mié] se produjo el pasado a mysql
al final con postgres tuvimos muchos inconvenientes a la hora de subir
los datos a cloud, (y tambien a la hora de pasar los datos de sqlite a
postgres convengamos)
** [2019-05-09 jue] mysql hasta ahora
*** creacion de instancia/usuario/db
*** lectura de dde por script tcl
*** script interno para generar tablas e importar csv (con errores)
*** subida a cloud de generacion de tablas por script tcl
*** importacion por csv (con errores) y por dump.

