* [2020-03-19 jue]
** Ale providencial
comenzo la mañana bien con un ale que vino asustado con una cara
diferente de gran preocupacion personal. En ese momento primaba en
muchos el deseo de seguir trabajando todo lo posible, el Fede, creemos
que Fabian, creiamos que el Ale, el grupo, los cobradores... Yo
personalmente desde ayer ya estaba seguro de que seguir vendiendo en
estas circunstancias era perder plata y ya me habia costado una
discusion con el Fede ayer. Por eso el que el Ale entrara con ese
animo me vino como anillo al dedo. Entonces le pregunto ¿que te
gustaria hacer? ¿queres que paremos hoy? y el dijo que mejor que si
por precaucion, y ahi nomas paramos el grupo, el resto tuvo de acuerdo
menos el Nico que era el mas rebelde pq se negaba a parar pq decia que
no tenia ningun otro ingreso. Por nuestra parte pudimos liquidar a
todos sin tener que dar ni un peso mas en compensacion, ni ninguno nos
pidio nada ni nos recrimino nada ni directa ni indirectamente. Yo lo
mismo hice un par de palabras preventivas en la arenga de grupo que
los ultimos dias habia trabajado a perdida para mantener los puestos
de trabajo pq todo lo vendido habia sido tirar mercaderia a la basura.
El cortar el jueves a la mañana nos dio un poco de tiempo para poder
hacer un par de cosas.
** corte Fabian providencial
a la tarde mientras volviamos de un jueves anticipado, donde todo
indicaba que la cuarentena empezaba esa misma noche, aunque muchos
creian que iba a ser la noche del viernes, le digo al Fede decile al
FAbian que venga hoy mismo a cobrar, y eso tambien fue providencial
para el pq efectivamente todo se corto a las 0hs y no hubiera podido
venir comodamente a cobrar, o sea hubiera podido venir lo mismo pero
arriesgandose.
** concertina providencial
si hay algo de lo que me felicito en esas pocas horas preparatorias
criticas pre-cuarentena fue haber puesto la concertina en el fondo de
la casa. Fue providencial!. Hable por la mañana con un tipo del
marketplace, me agenda por wassapp, luego me manda un mensaje a la
hora preguntandome si puede ir a colocarla a la tarde por las dudas
mañana se cierre todo y todo ok, a la tarde ya estaba colocada. Algo
que nos aumenta la sensacion de seguridad en un 100% fue puesto en el
ultimo segundo y a un costo razonable sin sobreprecio. 
** provision de comida y medicamentos
desde el martes que anticipamos una cuarentena y quisimos con ih tener
al menos una tanda de medicamentos aca, y en dos o tres tandas los
compre, luego abasteci de naturales como para un mes largo (justo
ahora que deje de consumir, pero quedan de reserva ultima familiar pq
como son alimentos menos apetitosos y mas alimentarios pueden servir
de subsistencia basica) tambien ih fue al hiper.
** falta de prevision hacia el jueves a la tarde de Romitex
cuando salimos el jueves a la tarde justo salia el vecino del B. El
sacaba su compu y nosotros nada. Tuve que ir yo el viernes por la
mañana a buscarla. Nos falta anticipacion. Porque? pq somos una
sociedad, uno es demasiado apocaliptico y hubiera evacuado dos dias
antes, y otro un negacionista que no veia la necesidad de irse. El
vecino es uno solo y a lo mejor tiene una vision mas equilibrada...
** el miercoles el Deivi me pedia trabajo y yo anticipaba la cuarentena
ayer el Deivi me manda un audio pidiendo trabajo. El mismo audio que
el martes le habia mandado al Fede. preguntando si nosotros seguiamos
trabajando. No le contesto y a la tarde me manda mensaje pidiendo por
favor que necesitaba mucho el trabajo. y le contesto que yo pensaba
que era evidente que se cortaria la posibilidad de trabajar en forma
inminente lo mas probable a la salida del finde largo. [la realidad se
adelanto y fue un dia antes del findelargo]
** gran angustia por el viaje de las chicas 
en realidad alivio por saber que venian en camino. Pero mucha ansiedad
por la lentitud del viaje. Ver que pasaban las horas y poco
avanzaban. El temor que luego de la medianoche les impidieran seguir
viaje (ya estaba decretada la veda para todo transporte de larga
distancia). 
** expectativa y gran angustia por el decreto de la cuarentena desde 0hs del viernes
no por la cuarentena en si que ya era un hecho sino por el tener que
ir a buscar a las chicas a la terminal. Que pudieramos ir. Que no nos
pararan en el puente y nos hicieran volver. Que las chicas pudieran
volver a la casa. Creo que pense mil cosas y pude dormir.
* [2020-03-20 vie]
** ir a buscar a las chicas
sali agarre el auto y fui por la monseñor semivacia como un domingo a
primera hora o menos, bastante rapidito, llego al puente avellaneda y
nada, paso, ya en el centro joya. paro en la oficina, cargo la compu,
voy al dpto de la romi, no puedo parar en la cuadra pq esta completa,
voy y paro en la otra cuadra y me quedo un rato. luego bajo y voy al
dpto. busco el bolso para cargarlo al saroo y lo cargo en el baul,
pasan dos motopolicias y paran en el semaforo, me quedo en el auto,
espero que se vayan, arranco doy la vuelta por santa rosa y luego por
cañada, y me voy a ir a la tarminal, estaciono, felizmente anda el
estacionamiento, y me voy a la terminal nueva. Da miedo estar ahi,
esta desolada, andan unos negros que me hacen temer por el celular. Me
quedo sin celular en esta cuarentena y puede ser muy molesto. prefiero
caminar de punta a punta, tengo en la otra mano el termo anaranjado
con baggio adentro que puede ser un arma contundente como para
defenderse. lo mismo no paso nada. los minutos no pasaban mas. la cami
me habia mandado una ubicacion en tiempo real, venian por toledo,
luego llegaron a cordoba, luego entraron a la ciudad, luego la
sabatini, cada vez mas lento. hasta que por fin llegaron...
nos vamos solo un cana nos pregunto a donde ibamos, les dije a casa,
pero que colectivo tomaran, no nos vamos en auto, a bueno sigan.
una vez en el auto fuimos al dpto a buscar la plata de la romi y su
compu, y volvimos a casa, ya habia varios controles pero no nos paro
ninguno.
Felizmente las chicas estan en casa.
* [2020-03-21 sáb]
los primeros dias transcurren con mucha tele, mucho noticiero, mucha
paranoia, muchas noticias. 
temo que mas adelante sea dificil conseguir comida, me gustaria
acumular mas comida. 
* [2020-03-22 dom]
empece a ver una serie de Formula 1 como para distraerme de la
psicosis que me esta haciendo mal.
* [2020-03-23 lun]
recien hoy pude relajarme mas. Y ver mas series, vi dos capitulos de
formula 1 y una miniserie de 4 capitulos durante toda la siesta. Y muy
pocos noticieros. La lectura de los diarios quedo relegada a la mañana.
* [2020-03-24 mar]
recien hoy pude sentarme a escribir y poner al dia las bitacoras,
hasta este momento estaba como alejado de esa posibilidad.
Noto que en los ultimos dias aunque no deje de hacerlos nunca, me
cuesta mas hacer los ejercicios a la mañana. El nivel de energia a
decrecido, no se si es la situacion de abulia o es la alimentacion que
ha cambiado, en especial el desayuno y merienda con el
pan-pan-pan. frente al mijo que tenia antes. Me recontracuesta hacer
una leche de avena, o un mijo. Y eso que estoy todo el dia al pedo. Lo
malo es que con todo el tiempo libre podria hacer cosas si tuviera energia.
Es mejor no ponerse a pensar, pq todo es catastrofico. La situacion
economica puede ponerse muy grave y eso derivar en una crisis de
seguridad muy grave.
Esos pensamientos, esos escenarios, esas probabilidades disparan
cortisol en mi, y me ponen mal, y creo que hace que luego me sienta
mal. Encima tengo un tratamiento reciente que hubiera sabido todo esto
no lo hacia. 
Creo que para sobrevivir tendremos que hacer como los que
sobrevivieron de los campos de concentracion nazis o sea vivir dia por dia.
* [2020-03-31 mar]
increible como vuelan los dias, parece que fuera largo pero ya paso
una semana desde que me puse a escribir la ultima vez.
Hay rutinas que ocupan gran parte del tiempo, una es dormir mas a la
mañana, y eso veo que debilita un poco el cuerpo en especial pq me
hace mas dificil el hacer los ejercicios, y ni hablar que deje
totalmente la dieta que tan bien venia, al menos en la crema de mijo y
en la leche de avena ambos productos ahora totalmente apartados de mi,
atiborrado como estoy actualmente de pan, manteca y dulce, y las
comidas, criando un vientre prominente y una debilidad solo paralela a
mi acidez estomacal.
La otra rutina es la lectura excesiva de los diarios, tengo cuatro
diarios, antes tenia cadena3, e infobae, ahora agregue clarin que
compre y lanacion que parece estar liberado, y llegue a la conclusion
que clarin no sirve para nada y tengo que darlo de baja. A lo que se
suma twetter. ESto lleva sus horas en especial a la mañana a veces
antes de levantarse o en una fiaca vespertina. Queda algo de ver tele
lo que va disminuyendo, comparado a los primeros dias que era mucho
mas acentuado.
La otra rutina es ver series que por ahora lo hago desde despues de
comer hasta mas o menos las 19hs, que es mi horario de
privacidad/tranquilidad en donde los otros se van a dormir la siesta y
yo me quedo en el living viendo series que me gustan a mi.
Luego viene la cena.
Otra minirutina que hemos tenido es jugar a las cartas en familia ya
sea algo a la siesta y algo despues de comer a la noche. pero tambien
nos ha ido cansando.
Un poquito cada dia he ido haciendo cosas en la casa de la cami, y eso
tambien ha servido de distraccion. 
Trato de no pensar, de que se pasen los dias, de no ser catastrofico,
de no asustarme, los primeros dias me asustaba mucho lo economico, o
sea pensar que me quedaba definitivamente sin trabajo, despues pienso
que quizas no sea tan asi, sino que posiblemente despues de junio o
julio mas tardar se pueda volver a trabajar y la pandemia quede en el
pasado, O sea se pueda sobrevivir. o sea conservar el trabajo. y surge
el miedo a la enfermedad propiamente, o sea a enfermarse, a que te
falte el aire, a que te internen, o a que se te muera un familiar.
A todo esto el problema de siempre o sea el dolor de cabeza que vuelve
despues del puto tratamiento a resurgir despacito. aunque no le doy
bola pero vuelve y molesta. 
* [2020-04-03 vie]
hoy fue un dia nefasto para el pais pq la cuarentena se fue al carajo
pq salieron 3millones de viejos a la calle a cobrar a los bancos
mientras rifamos la cuarentena de 14 dias como yo rife con 4 migrales
los 20 dias de corticoides, salvando las diferencias.
Tambien lei bien el decreto 320 y me quede mas tranquilo que no
pagaremos ni alquiler ni expensas del local hasta que nos recuperemos
y podamos hacer frente a esos costos, lo mismo arreglaremos con seven
pienso y el FEde podra hacer lo propio con Prades, o sea que se nos
acotan los gastos fijos.
A mi me quedarian luz y gas como mas perentorios, ya decidi dejar de
pagar celular, y ospe esta a un paso de ser dejado, pq se que no me
vale de nada pagarlo ahora ya que por el covid no te atienden. O sea
que mas o menos 12 o 13 mas algo de comida. Y posiblemente el saldo
del placard.
* [2020-04-14 mar]
empezamos a trabajar por suerte. Conseguimos unos permisos de transito
por la web para el Fede y varios cobradores que permiten transitar y
lo mas importante es la repuesta de la gente. Por el momento hay
cobro. el primer dia Nir y Pablo cobraron casi cincuenta recibos cada
uno. Esto alivia un poco el panorama de catastrofe y lo mueve al de
alta crisis.
Cuesta trabajar con parametros de control o de precaucion: barbijo,
alcohol etc. es muy molesto y uno tiende a no darle bola pero hay que
concientizarse que uno se puede enfermar y feo. O puede contagiar a
otro p.e. a ih y ser feo que se enferme peor que uno y que sea por
culpa nuestra. 
* [2020-04-20 lun] pago virtual de boletas
gas 01/2020 4054.7 vto 13/4
agua 1212 03/2020 
luz 8384 3/2020
* [2020-04-22 mié]
a pesar de que esta ultima semana se ha disipado el problema economico
en gran parte pq hemos podido cobrar una buena suma, lo cual despeja
bastante el panorama, pq ambos pagamos las cuentas de abril y tenemos
resto para mayo y perspectivas de seguir cobrando. Y mientras tanto
vamos recuperando. Pero a pesar de eso la cuarentena no ha significado
una posibilidad de mejora en los habitos ni en la salud. He podido
mantener un solo habito que es las series, he abandonado la lectura en
forma total descontando el consumo de basura informativa, hasta he
abandonado el habito de escribir que servia de autoanalisis, de tanto
comer he arruinado un poco la salud y he aumentado de peso. Tengo
graves molestias gastricas. Paso muchas horas viendo tele, pq no paso
muchas horas durmiendo de mas, ahora me levanto ahi nomas  a la
mañana.
Habria que recuperar habitos. tanto positivos como negativos,
p.e. agua, poder anotarla cuando no se tomo ningun contaminante, y
crema mijo cuando tampoco se tomo ningun desayuno merienda
contaminante en el dia. Alli saco dos contaminantes importantes. 
* [2020-04-27 lun]
ayer durante la migraña pensaba una estrategia distinta frente al
tiempo sobrante o mas bien no sobrante sino al tiempo desperdiciado
sentado viendo series. Paso toda la siesta-tarde frente al tele y
sumado a que me levanto tarde y que paso muchas horas leyendo diarios
twetter termino sin nada util y con una sensacion de desperdicio.
Aparte de que considero que todas esas horas mal-sentado en el sillon
son nocivas ergonomicamente.
Se trata de estar sentado cuatro o cinco horas muy mal sentado, y sin
pausas.
viendo esa pantalla 4k y con un material que tiene impacto emocional.
Pero de ahi a hacer posible lo que flashie ayer, o sea hacer eje en
orgblock para pasar toda la tarde??.
* [2020-04-30 jue]
** ruby 
hace dos dias que estoy estudiando furiosamente ruby y eso a opacado
toda otra cosa, no leo diarios ni tw, no veo series, y paso viendo
videos leyendo, instalando y programando. 
lo bueno que de a poco voy aprendiendo y creo que podria entusiasmarme
de nuevo con un lenguaje de programacion otra vez.
