* Diario de migra単as fuertes
** [2016-10-09 dom]
Me tomo el primer migral a las 9hs luego de una noche con molestias y
espera a la ma単ana para tomar el migral.
No considero que haya sido tardio en ese momento pq no me molesto ni
subio en intensidad. Hice un poco de netbook en cama y luego me
levante y trabaje en la terraza (con viento y sol), luego cuando
llegaba la hora de la comida me puse a trabajar en el patio con la
netbook a contrareloj muy presionado por terminar una secuencia antes
que me llamaran a comer, entonces me sente a comer tensionado y con el
clima beligerante de estos dias con las chicas. En ese momento pense
que necesitaba otro migral, pero no quise arruinar el gusto de la
comida, pero no comi tan feliz como en otras ocasiones.
Justo al terminar el almuerzo me tome otro migral y me quede en el
patio en un sitio mas o menos tranquilo tomando un te y el dolor
subia. Pero no era incapacitante todavia.
Me acuesto un rato y luego decido levantarme a tomar un cafe que tome
con mucha torta y mucho dulce de leche. Y luego de una breve pausa
para dormir que no debo haber dormido mas de diez minutos, bajo a
hacerme un segundo cafe, mientras tanto sigo con la maquina y algunas
frustraciones al medio.
Dentro de esas frustraciones me planteaba el no dispersarme tanto y
focalizarme en solo dos temas.
El dolor subio y se mezclo con un bajon animico pronunciado y un
malestar generalizado.
Alli cuando me acuesto tipo 20.30 y empieza una migra単a tipo 8 o 7,
incapacitante hasta para pensar (pero mas por el malestar que por el
dolor punzante). Cuando me lograba dormir me mejoraba un poco, a las
21.30 ih me subio pure de calabazas que pude probar apenas pq estaba
nauseoso. Tome reliveran a las 22.30 y en esas levantadas al ba単o el
dolor por el movimiento era muy importante, igual que la fotofobia.
Cuando hizo efecto el reliveran me tomo el tercer migral y en los
proximos 45 minutos no experimente ninguna mejoria, acostado sobre el
costado derecho me presionaba mucho la zona del higado, y sobre el
costado izquierdo me presionaba la cabeza donde me dolia.
Quizas una hora despues o dos, ya me mejore quedando solo la resaca
que desaparecio durante la noche.


