* Films
** The irrational man  :profesor:filosofia:asesinato:
   [2016-10-13 jue] Cuenta la historia de un profesor de filosofia que
   viene a una facultad y el tipo esta atravesando un bajon
   existencial. La vida no le interesa y atraviesa un gran displacer,
   nada le resulta placentero. Es sombrio, oscuro y practicamente esta
   abandonado. Comienza una amistad con una alumna que intenta sin
   exito sacarlo de ese marasmo. Un dia casualmente escuchan una
   conversacion en un bar sobre un juez que estaba arruinandole la
   vida a una mujer por abuso de poder en su cargo, y repentinamente
   el profesor encuentra en el asesinar a dicho juez su razon de
   vivir. A partir de ese momento su vida renace en todos los sentidos
   que antes estaban bloqueados. Comete el asesinato, pensando que no
   iba a ser descubierto, y al poco tiempo la misma alumna con quien
   ya ha comenzado un affaire lo descubre y confronta. La situacion se
   complica cuando la chica lo obliga a confesar el crimen pq alguien
   inocente va a ser inculpado y el ya no quiere abandonar los
   placeres de esta nueva vida que acaba de conseguir y decide matar a
   la chica para cubrir su crimen, intento que casualmente le falla y
   muere accidentalmente el mismo.
   :Calificacion: 4/5
   :Actor: Joaquin Phoenix

