* 2016
** Setiembre
*** [2016-09-07 mié]
    Pero si recupero la idea de hace solo un mes de hacer un plan de
    estudios creo qu con python avance un monton. Queda mucho por
    aprender todavia.
*** [2016-09-08 jue]
    Hoy establecimos que los patas deben cumplir la norma Raul o sea
    entrar a las 9.30hs y cortar a las 14hs y volver a las 15hs.

    Subi a github pero tengo dudas pq expongo publicamente el codigo
    solo por no usar bien un pendrive. Pero la verdad es que reniego
    mucho con tener sincronizacion en las tres maquinas y con la de
    Fede cuatro. Lo cual es bastante positivo, he perdido mucho codigo
    hasta el dia de hoy y no veo mal esa funcionalidad. Quizas
    cambiando a un nombre mas criptico.

    La programacion por ticket que implemente desde ayer es muy buena
    pq me focaliza a la productividad y me quita la presion de no
    avanzar. Y a la vez me deja tranquilo que no pierdo u olvido
    nada. Y el cuaderno de reflexion (el marron grande) permite
    analizar donde queremos ir, que queremos hacer.
    Igual con relacion a cada desarrollo o modulo o metodo o funcion
    definirla conceptualmente para que sea mas facil de entender.
*** [2016-09-09 vie]
    Hoy un poco trabado el tema con el tabGrupo. Pq cai en un pequeño
    bug de copiar el mismo nombre asignado a data en los pivot y me
    hizo pensar que los nombres de b1/t etc estaban repetidos, pero
    no.
    Igual hice un metodo para asignar tipo a las columnas [-x] o sea
    con un numero negativo seteo todas las columnas menos esa (lo cual
    es util en los pivot mas que todo) Luego el metodo colreset() para
    redefinir las columnas sin tener que determinar el tipo de
    nuevo. Pienso que este finde me termino el recibeador y el tab
    grupos o sea la info.
    Y hay que comenzar el fechador.
    MB mercurial con bitbucket incluido pq no solo organizamos sino
    que tenemos todo disponible.
*** [2016-09-14 mié]
    Falta cronicar que alla el finde sab/dom me sumergi en fossil. Y
    los emboles fueron pq en la netbook no tenia un webbrowser por
    defecto (al haber borrado el palemoon que viene por defecto) y eso
    hacia que cuando ponia fossil ui colapsara la maquina buscando el
    webbrowser por defecto y tenia que resetear (lo hice como diez
    veces)
    Pero fossil me resulto muy funcional y rapido. Funciona localmente
    se puede incluso backupear como un archivo standalone.
    El manejo en la web se hace muy rapido a pesar de que el proveedor
    no es muy que digamos y en cualquier momento desaparece.
    Me gusta lo claro del timeline, los ticket y el diff. Lo he usado
    en las tres maquinas y ha resultado muy eficiente.
    Hoy conoci gitlab que parece ser el google de los git. Una
    programacion de primer nivel gratis de por vida. Con miles de
    proyectos. Nose por ahora sigo y veo. El problema es que no parece
    ser tan agil y rapido. 
    Hoy no fue muy fertil pero lun y mar he pulido lo hecho y no hice
    nada nuevo. Por eso creo que sera mas facil agregar desde aca.
    El curso MB creo que se logran conocimientos que no tenia aun en
    Python que lo manejo mas, y el de html esta interesante
    tambien. Luego vere el que se puede hacer.
    Proximos tickets recibeador y depurar los geolocs.
*** [2016-09-15 jue]
    hoy avance en el curso php primera parte.
    Renegue bastante con poco avance en el programa pq me distraje con
    emacs. Si aunque parezca risueño. Al final obvio termino con
    atom, pero perdi como 2 horas puras hoy en eso. Y asi se va el
    tiempo. Ayer con git hoy con emacs la otra semana con vim. Todo
    instrumental pero nada de avance. Y algunos avances son muy
    escasos.
*** [2016-09-20 mar]
    el viernes pasado programe y avance. El sabado fue emacs puro en
    marques, y el domingo descubri spacemacs y lo saque en el dia y a
    la noche entre en produccion.
    Ayer produje bastante y hoy tambien. Todo en emacs, pero en modo
    vim. Muy rapido. Al lado de gente que lleva años en eso.
    Muy importante: hoy a la tarde hice en el entretiempo de
    programacion una serie basica completa 10/12/10 dos veces y me
    encinte la pared para pintar. Mañana traigo la bandeja y pinto.
    Esa mezcla con la programacion es optima.
*** [2016-09-21 mié] 
    Desde ayer implemento un tip que se me ocurrio y es hacer una serie de ejercicios
    simples (los mismos tres que conozco desde hace casi 30 años) por cada hora o periodo
    de maquina, como pago. Mas 5 sentadillas. Y el resultado ha sido fenomenal, pq me
    saca la contractura y un poco el dolor de espalda (aunque hoy estuve doblado cuando
    fui a trabajar) sino que tiene efectos espectaculares en el animo. Tanto es asi que 
    ayer me puse a encintar toda la pared y hoy la pinte.
    
    Lucho contra la idea de ir y volver respecto a la herramienta. Hoy pensaba volver a
    vim, pq lo veo rapido y expedito, (siendo que tengo aca evil que muchos dicen que es
    mas lindo que vim). Y siendo que descubri org-mode que recien estoy aprendiendo y es
    extraordinario, para irlo conociendo de a poco.
    
    No quiero perder el ritmo de la programacion. Siendo que voy viendo resultados. 

*** [2016-09-22 jue]
    Hoy termine de pintar la pared del living y colgue los cuadros
    cambio muchisimo y no fue gran tarea, sino que fue agradable y
    permite cambiar un poco de actividad

*** [2016-09-25 dom]
**** Ejercicio-movimiento
     Esta ultima semana al menos comence a hacer ejercicio y ahora con
     tomatinho pienso que se facilitara muchisimo comenzar a moverse
     durante la jornada y evitar el anquilosamiento.
     Asimismo pasar de 20 cuadras basicas a 30 o 40 no lo veo dificil ni
     imposible.
**** Implementar cuanto antes el 3x12
**** Alimentos
     Urgente debo volver a una alimentacion mas sana. Hoy comi
     pollo/gaseosa/helado o sea el trio maldito que alguna vez habia
     superado. Mucha manteca, mucho pan. Un desastre. Esta ultima semana no
     hice el muesli ni un dia.

**** Acomodo del dpto
     La semana pasada di un paso gigante que fue la pintada de la pared.
     Debo seguir con ese sistema en lo posible.
*** [2016-09-27 mar]
    Hoy dia defini hacer dos cositas que estaba evitando de una y
    punto.
    Dia que sufri malestar pq surgio un malestar en el ojo izquierdo.
    (Fuerte dolor punzante en el ojo, sin latidos, pero que no tenia
    ninguna relacion con la migraña u otro dolor de cabeza, me calme
    yendome temprano a acostar y haciendo palming en el ojo. Al otro
    dia mejore y no me volvio).
    Orden de ideas pq se traslapan y se rompen:
    1. git -->gitlab
    2. mega
    3. orgmode
    4. emacs
    Seguir programando nomas
*** [2016-09-28 mié]
**** Entre ayer y hoy tome el toro por las astas
     en un par de cosas que estaba demorando como ser comprar la camisa en
     rochas, ir al peluquero, y hoy arreglar los cueritos de las
     canillas. Y los tres asuntos los resolvi expeditamente, o sea creo que
     no hay porque demorar las cosas.

*** [2016-09-29 jue]
    Hoy es un milestone en nuestras vidas. Hoy recibio su diploma de
    Contadora la Rominita. Ha pasado un largo trecho desde aquella noche
    de julio del 91 cuando solo en la oficina escribi un post,
    lamentablemente perdido en DOS-WordStart alusivo al nacimiento de la
    Romi y 25 años despues estoy escribiendo esto en una herramienta que
    no difiere mucho de aquella en cierta forma, y quizas tambien
    destinado a perderse.
    Me alegra que ella haga algo de su vida y haga las cosas bien.
    Fue un dia feliz, aunque no tenemos los musculos de la felicidad muy
    entrenados en la familia, al menos en la modalidad expresividad.

**** Referencia al metodo usado en los ultimos tres dias
     Constructo: Actua como un tipo normal.
     Con relacion al evento (que causo mucha preocupacion anticipatoria e
     innecesaria casi al nivel de la opercion de mi vieja), se planteaban
     un par de todo's necesarios y urgentes que eran los que me causaban
     problema. Necesitaba comprarme una camisa e ir al peluquero. Aunque
     ambos temas son ridiculamente banales, representaban un problema en el
     sentido de que son ambas situaciones que me incomodan, ya sea en el
     sentido de ir y hacerlas y en el sentido de pensar que voy a salir
     defraudado por dichas acciones. Y el constructo usado, me movilizo y
     el martes volvi temprano de la oficina, me bañe rapidamente, me puse
     el saco y fui a comprar la camisa en un proceso directo y normal.
     Luego ayer fui al peluquero, por ahi el problema no era tanto ir a las
     dos opciones, sino el patetico miedo a que no fuera satisfactorio el
     resultado. Y con una ligerisima duda, fui y el resultado me parece
     mejor que la ausencia de resultado, o el demorarse como lo hacia antes
     con el resultado de andar desprolijo  e impresentable.
     Quedaba procesar el evento, y alli el constructo fue dividirlo en dos
     partes, por una parte la ceremonia, y luego el ir al lugar, y eso
     quito un poco de presion, una vez en el lugar el resultado fue
     bastante positivo a pesar de la situacion, (almorzar con niños en un
     sitio asi, y el que Fede pobre estuviera tan dolorido y molesto).
     Creo que como me pasa en la mayoria de las situaciones, alli no fue
     problema de plata, ya estaba jugado, sino el pensar que podia faltarme
     con lo que habia llevado.
     Pero pienso que la experiencia es positiva y tiene un efecto
     liberador.
     Y alienta a en el futuro encarar las cosas con mas asertividad.

*** [2016-09-30 vie]
    Dia

** Octubre
*** [2016-10-10 lun]
Ayer experimente junto con la migraña otra recaida del estado animico,
lo que se manifesto principalmente durante la crisis, en la mañana de
hoy hasta volver de mi vieja y antes de la crisis migrañosa desde el
malestar animico con/contra las chicas desde la pataleta de la Cami,
pasando por la crisis de expansion de herramientas y crisis de
vacuidad o de dificultad para aprehender todo lo que leo, que en el
mismo dia de ayer procese entre dolores entre los dos cafes con la
determinacion de centrarme unicamente en dos cosas (python y orgmode).

Tambien influyen certeramente los sonidos, ya sea los sonidos lejanos
de barrio (que no son los mismos felizmente en el centro) como la
musica, los vecinos escuchando cuarteto, o folklore o simplemente el
ruido de los autos en la circunvalacion.
Todo esto te golpea pq uno esta en un estado de no-felicidad o
no-placer o insensibilidad. Aparte de la circunstancia de sentirse
mal, pq esta uno atrapado en la migraña y no tiene solucion, o no ve
la solucion o no ve que el medicamento te haga efecto, y eso te
distrae de lo que estas haciendo o te hace pensar que no podes o no
podras disfrutar de nada.
Tambien te afecta no tener objetivos o creer no tenerlos. En realidad
cuando estaba dentro de la crisis
[2016-10-08 sáb 15.00]--[2016-10-10 lun 13.00] crei no tener objetivos
o crei que mi vida no tenia sentido. Ahora lo veo distinto asi sea que
los objetivos sean insanos, -que podrian no serlos con algunos habitos
positivos intercalados- o sean atipicos. En realidad tengo un gran
objetivo, que es doble y ha veces hace que me pierda:
- Profesionalizar grandemente el negocio mediante un CMR y un conjunto
  de reglas de negocio, y un gran tablero de control
- Aprender lo que mas pueda de programacion y todos los temas
  relacionados.
Ambos objetivos que estan relacionados son importantes y son utiles.
Pq redundan en menos horas de trabajo, en mas desarrollo mental y en
posibles aplicaciones futuras que ahora desconocemos.

En el medio obviamente uno se pierde a veces.
En el medio puede que uno pierda el foco, o bien se canse y se
distraiga en forma desmedida y no sepa bien para donde ir.
O bien puede ser que los sufrimientos que te da el padecimiento de una
enfermedad (cosa de la cual nadie esta exento y menos yo, no hace
falta que de ejemplos) te hagan desepcionar o desilusionar siendo que
no tendria que ser asi.

Los avances son muchos y no deberian ser desdeñados.

*** [2016-10-11 mar]
Hoy amaneci pensando un par de cosas respecto a como integrar org-mode
con mis problemas actuales.

**** Usar el diario para filosofar e ir acumulando en un solo lado
Me gusto la experiencia de ayer en el sentido de hacer un autoanalisis
-que resulta muy efectivo y barato jeje- como lo hice la ultima vez en
el cuaderno.
Lo unico que org-mode puede precisamente ayudarme a esto a org --
mode. o sea a organizarme mejor. Pq via git lo tengo en todos lados y
via org si o si fechas, y luego tenes la posibilidad de tagear y de
buscar de manera mas eficiente.
Incluso el repositorio de gitlab privado p.e. mantenido en forma
separada al codigo es un buen lugar para acumular los escritos.
**** El sentido de filosofar o la necesidad en este momento
me refiero a filosofar quiza mas en el sentido de Eric Fromm o sea el
de un personal autoanalisis para reponerse y reacomodarse.
Lo sufrido este fin de semana en el perido descripto ayer te da un
poco de miedo, respecto a la debilidad de uno mismo para ser ecuanime
y quizas mantener la cordura o las relaciones intactas. Y como ese
bajon te viene y uno no tiene herramientas para combatirlo.
Hoy (post-hecho) me alegro de haber ido a mi vieja, en vez de quedarme
a lamentarme o ponerme mas oscuro y arruinarle el dia a ih.
Tambien pienso que ponerse a hacer una actividad fisica fuerte en ese
momento de distimia puede ayudar.
**** En si el cambio empezo cuando saque el auto
alli me empezaron los pequeños planes de hacer algo con el auto y no
dejarlo arrumbado ahi, y eso en cierta forma me cambio la mentalidad.
Hay un monton de lados donde uno podria ir a pasar el rato y esa
costumbre de permanecer encerrados y lugubres dentro de esa pieza no
es buena. Pero esto lo veo ahora que estoy aca en la oficina. Hay que
estar alla. 
**** Como enfrentar los miedos
ayer las chicas se fueron a cpaz y obviamente me asaltaron un monton
de miedos y aprensiones, y las espante de forma un poco extrema
diciendome a mi mismo o a los miedos, bueno ya, que pase lo que tenga
que pasar y a la mierda que se vaya todo a la mierda. O sea recuerdo
que me dije a la bosta si las matan a las dos. se va todo a la mierda,
... pero no voy a tener miedo, o sea no voy a permitir que sufra por
anticipado por cosas que quizas no pasen nunca. Y despues recorde que
yo muchas veces habia ido cuando joven y pq ellas no pueden hacer lo
mismo. Y creo que esa es la forma general de enfrentar los miedos sino
vivis una vida patetica de aprensiones de fantasmas que te acechan y
no te dejan vivir en paz.
**** Respecto a org-mode y su aprendizaje:
Pense que ya que tengo un conocimiento basico mas o menos general que
me permite ir produciendo en el, podria comenzar tranqui y en forma
organica y sistematica ir aprendiendo con vias al mastering.
P.e. comenzando un tema, como puede ser las tablas. Y aprender todo
sobre eso y luego ir avanzando capitulo por capitulo de acuerdo al
interes que tenga.

*** [2016-10-12 mié]
**** Crisis de trabajo en el hogar
    creo que el horario reducido me hace mal. Porque me da la
    sensacion de que estoy en falta y no esta bien lo que hago.
    Hoy por ejemplo llegue aca a las 10.30hs tome una segunda leche pq
    la primera fue muy deficiente y no me fui directo a programar ni
    al tema computacion. Sino que me puse a buscar los doc a devolver
    y de paso libere un estante para los docs y puse alli los tocos de
    docs ordenados de a cien (solo faltan 17 que debe ser un toquito
    mesclado con los recibos). Los recibos los apile sin orden de
    fecha, en caso de necesitar tendre que sacar todo. Creo que tendre
    lugar alli para un año. (De todos modos creo que los recibos
    tendria que destruirlos y a la maquina de aca encriptarla).
    [Ampliar tema seguridad]
    Luego conte y revise 4 fajos, cosa que es una tarea de siempre y
    lo mismo se hace hace aca como prolongacion  de la oficina.
    Hasta alli se podria pensar, en una jornada de 9 a 12hs en oficina
    "llenada" con computacion o una jornada adosada terminada aca con
    dos tareas de oficina que son altamente necesarias.
**** Crisis de comida
    Luego me fui a comprar algo de verduras.
    Alli otro tema, es que vengo mal con la comida. Al perder los
    habitos basicos de licuado y muesli quedo bastante
    maltrecho. Porque pierdo energia y nutrientes que tenia con
    seguridad.
    Casi que estoy entrando en una crisis de compras de alimentos, pq
    dos por tres el super me resulta tedioso al tener que hacer cola
    en cualquier horario para traer dos o tres cosas locas. Y al no
    querer destinar ningun horario para eso. Hoy fui a esa
    verduleriita de la vuelta y es muy poco lo que tienen y al haber
    caido en un pozo alimentario no me resulta facil determinar que es
    lo que quiero comprar o comer.
    Luego voy camino a la subalimentacion y al abuso del pan y a la
    falta de fuerza por falta de alimento y a los efectos secundarios
    por falta de nutrientes que se manifiestan sicologicamente y a lo
    peor de todo a la dependencia de ir el fin de semana alla pq
    necesito comer bien.
**** Levantar de a poco los habitos
     podria recuperar de uno a uno los habitos y llevar la cuenta de
     como voy en ellos en un org ad-hoc.
     P.e. el primero que hare ya mismo es el licuado.
**** Analizar (con analista) los problemas (supuestos)
     obvio que todo nace de una BTF gigante. P.e. hoy me amargue con
     el dpto que en general me gusta y al que estoy acomodando para
     que me guste mas, pq no tiene balcon donde desagotar el aire ac.
     Y bueno solucion 1, poner la manguera adentro y soportarla asi,
     de todos modos estoy mejor que los ochenta monos aca adentro que
     no tienen aire por lo visto.
     solucion 2, seguir el caminito del vecino de abajo o sea poner
     una prolongacion de 2 metros y hacerlo caer justo en el mismo
     punto del vecino de abajo, de modo tal que seamos dos
     supuestamente.
     solucion 3 si me voy a poner belico, es reclamar que la falta es
     parangonable con las mascotas que abundan en el edificio.
     solucion 4 (utopica) prolongar mas y hacerlo salir en la
     cocina...

     Una vez analizado un problema pierde su dimension y pasa a ser
     una molestia mas.
     La sensacion que te invade es que si tenes un problemita se te
     viene la maroma o toda una maroma haciendote invivible el sistema
     en general. O sea una generalizacion e intensificacion difusa de
     los problemas. O sea me siento mal pq en general este dpto se
     transformara en una mierda para vivir (o sea asi pensaria frente
     a un problema especifico que requiere TF y no tanta BTF)






* Constructos
** Be normal
** mind sweep

* Temas a pensar y/o articular
** Seguridad en dpto

* temas sueltos
** puntadita en el ojo izquierdo 
[2016-10-12 mié] de nuevo al mediodia dos veces. no tanto como la otra
vez pero molesta.
