* 2016
** Setiembre
*** [2016-09-07 mié]
    Pero si recupero la idea de hace solo un mes de hacer un plan de
    estudios creo qu con python avance un monton. Queda mucho por
    aprender todavia.
*** [2016-09-08 jue]
    Hoy establecimos que los patas deben cumplir la norma Raul o sea
    entrar a las 9.30hs y cortar a las 14hs y volver a las 15hs.

    Subi a github pero tengo dudas pq expongo publicamente el codigo
    solo por no usar bien un pendrive. Pero la verdad es que reniego
    mucho con tener sincronizacion en las tres maquinas y con la de
    Fede cuatro. Lo cual es bastante positivo, he perdido mucho codigo
    hasta el dia de hoy y no veo mal esa funcionalidad. Quizas
    cambiando a un nombre mas criptico.

    La programacion por ticket que implemente desde ayer es muy buena
    pq me focaliza a la productividad y me quita la presion de no
    avanzar. Y a la vez me deja tranquilo que no pierdo u olvido
    nada. Y el cuaderno de reflexion (el marron grande) permite
    analizar donde queremos ir, que queremos hacer.
    Igual con relacion a cada desarrollo o modulo o metodo o funcion
    definirla conceptualmente para que sea mas facil de entender.
*** [2016-09-09 vie]
    Hoy un poco trabado el tema con el tabGrupo. Pq cai en un pequeño
    bug de copiar el mismo nombre asignado a data en los pivot y me
    hizo pensar que los nombres de b1/t etc estaban repetidos, pero
    no.
    Igual hice un metodo para asignar tipo a las columnas [-x] o sea
    con un numero negativo seteo todas las columnas menos esa (lo cual
    es util en los pivot mas que todo) Luego el metodo colreset() para
    redefinir las columnas sin tener que determinar el tipo de
    nuevo. Pienso que este finde me termino el recibeador y el tab
    grupos o sea la info.
    Y hay que comenzar el fechador.
    MB mercurial con bitbucket incluido pq no solo organizamos sino
    que tenemos todo disponible.
*** [2016-09-14 mié]
    Falta cronicar que alla el finde sab/dom me sumergi en fossil. Y
    los emboles fueron pq en la netbook no tenia un webbrowser por
    defecto (al haber borrado el palemoon que viene por defecto) y eso
    hacia que cuando ponia fossil ui colapsara la maquina buscando el
    webbrowser por defecto y tenia que resetear (lo hice como diez
    veces)
    Pero fossil me resulto muy funcional y rapido. Funciona localmente
    se puede incluso backupear como un archivo standalone.
    El manejo en la web se hace muy rapido a pesar de que el proveedor
    no es muy que digamos y en cualquier momento desaparece.
    Me gusta lo claro del timeline, los ticket y el diff. Lo he usado
    en las tres maquinas y ha resultado muy eficiente.
    Hoy conoci gitlab que parece ser el google de los git. Una
    programacion de primer nivel gratis de por vida. Con miles de
    proyectos. Nose por ahora sigo y veo. El problema es que no parece
    ser tan agil y rapido. 
    Hoy no fue muy fertil pero lun y mar he pulido lo hecho y no hice
    nada nuevo. Por eso creo que sera mas facil agregar desde aca.
    El curso MB creo que se logran conocimientos que no tenia aun en
    Python que lo manejo mas, y el de html esta interesante
    tambien. Luego vere el que se puede hacer.
    Proximos tickets recibeador y depurar los geolocs.
*** [2016-09-15 jue]
    hoy avance en el curso php primera parte.
    Renegue bastante con poco avance en el programa pq me distraje con
    emacs. Si aunque parezca risueño. Al final obvio termino con
    atom, pero perdi como 2 horas puras hoy en eso. Y asi se va el
    tiempo. Ayer con git hoy con emacs la otra semana con vim. Todo
    instrumental pero nada de avance. Y algunos avances son muy
    escasos.
*** [2016-09-20 mar]
    el viernes pasado programe y avance. El sabado fue emacs puro en
    marques, y el domingo descubri spacemacs y lo saque en el dia y a
    la noche entre en produccion.
    Ayer produje bastante y hoy tambien. Todo en emacs, pero en modo
    vim. Muy rapido. Al lado de gente que lleva años en eso.
    Muy importante: hoy a la tarde hice en el entretiempo de
    programacion una serie basica completa 10/12/10 dos veces y me
    encinte la pared para pintar. Mañana traigo la bandeja y pinto.
    Esa mezcla con la programacion es optima.
*** [2016-09-21 mié] 
    Desde ayer implemento un tip que se me ocurrio y es hacer una serie de ejercicios
    simples (los mismos tres que conozco desde hace casi 30 años) por cada hora o periodo
    de maquina, como pago. Mas 5 sentadillas. Y el resultado ha sido fenomenal, pq me
    saca la contractura y un poco el dolor de espalda (aunque hoy estuve doblado cuando
    fui a trabajar) sino que tiene efectos espectaculares en el animo. Tanto es asi que 
    ayer me puse a encintar toda la pared y hoy la pinte.
    
    Lucho contra la idea de ir y volver respecto a la herramienta. Hoy pensaba volver a
    vim, pq lo veo rapido y expedito, (siendo que tengo aca evil que muchos dicen que es
    mas lindo que vim). Y siendo que descubri org-mode que recien estoy aprendiendo y es
    extraordinario, para irlo conociendo de a poco.
    
    No quiero perder el ritmo de la programacion. Siendo que voy viendo resultados. 

*** [2016-09-22 jue]
    Hoy termine de pintar la pared del living y colgue los cuadros
    cambio muchisimo y no fue gran tarea, sino que fue agradable y
    permite cambiar un poco de actividad

*** [2016-09-25 dom]
**** Ejercicio-movimiento
     Esta ultima semana al menos comence a hacer ejercicio y ahora con
     tomatinho pienso que se facilitara muchisimo comenzar a moverse
     durante la jornada y evitar el anquilosamiento.
     Asimismo pasar de 20 cuadras basicas a 30 o 40 no lo veo dificil ni
     imposible.
**** Implementar cuanto antes el 3x12
**** Alimentos
     Urgente debo volver a una alimentacion mas sana. Hoy comi
     pollo/gaseosa/helado o sea el trio maldito que alguna vez habia
     superado. Mucha manteca, mucho pan. Un desastre. Esta ultima semana no
     hice el muesli ni un dia.

**** Acomodo del dpto
     La semana pasada di un paso gigante que fue la pintada de la pared.
     Debo seguir con ese sistema en lo posible.
*** [2016-09-27 mar]
    Hoy dia defini hacer dos cositas que estaba evitando de una y
    punto.
    Dia que sufri malestar pq surgio un malestar en el ojo izquierdo.
    (Fuerte dolor punzante en el ojo, sin latidos, pero que no tenia
    ninguna relacion con la migraña u otro dolor de cabeza, me calme
    yendome temprano a acostar y haciendo palming en el ojo. Al otro
    dia mejore y no me volvio).
    Orden de ideas pq se traslapan y se rompen:
    1. git -->gitlab
    2. mega
    3. orgmode
    4. emacs
    Seguir programando nomas
*** [2016-09-28 mié]
**** Entre ayer y hoy tome el toro por las astas
     en un par de cosas que estaba demorando como ser comprar la camisa en
     rochas, ir al peluquero, y hoy arreglar los cueritos de las
     canillas. Y los tres asuntos los resolvi expeditamente, o sea creo que
     no hay porque demorar las cosas.

*** [2016-09-29 jue]
    Hoy es un milestone en nuestras vidas. Hoy recibio su diploma de
    Contadora la Rominita. Ha pasado un largo trecho desde aquella noche
    de julio del 91 cuando solo en la oficina escribi un post,
    lamentablemente perdido en DOS-WordStart alusivo al nacimiento de la
    Romi y 25 años despues estoy escribiendo esto en una herramienta que
    no difiere mucho de aquella en cierta forma, y quizas tambien
    destinado a perderse.
    Me alegra que ella haga algo de su vida y haga las cosas bien.
    Fue un dia feliz, aunque no tenemos los musculos de la felicidad muy
    entrenados en la familia, al menos en la modalidad expresividad.

**** Referencia al metodo usado en los ultimos tres dias
     Constructo: Actua como un tipo normal.
     Con relacion al evento (que causo mucha preocupacion anticipatoria e
     innecesaria casi al nivel de la opercion de mi vieja), se planteaban
     un par de todo's necesarios y urgentes que eran los que me causaban
     problema. Necesitaba comprarme una camisa e ir al peluquero. Aunque
     ambos temas son ridiculamente banales, representaban un problema en el
     sentido de que son ambas situaciones que me incomodan, ya sea en el
     sentido de ir y hacerlas y en el sentido de pensar que voy a salir
     defraudado por dichas acciones. Y el constructo usado, me movilizo y
     el martes volvi temprano de la oficina, me bañe rapidamente, me puse
     el saco y fui a comprar la camisa en un proceso directo y normal.
     Luego ayer fui al peluquero, por ahi el problema no era tanto ir a las
     dos opciones, sino el patetico miedo a que no fuera satisfactorio el
     resultado. Y con una ligerisima duda, fui y el resultado me parece
     mejor que la ausencia de resultado, o el demorarse como lo hacia antes
     con el resultado de andar desprolijo  e impresentable.
     Quedaba procesar el evento, y alli el constructo fue dividirlo en dos
     partes, por una parte la ceremonia, y luego el ir al lugar, y eso
     quito un poco de presion, una vez en el lugar el resultado fue
     bastante positivo a pesar de la situacion, (almorzar con niños en un
     sitio asi, y el que Fede pobre estuviera tan dolorido y molesto).
     Creo que como me pasa en la mayoria de las situaciones, alli no fue
     problema de plata, ya estaba jugado, sino el pensar que podia faltarme
     con lo que habia llevado.
     Pero pienso que la experiencia es positiva y tiene un efecto
     liberador.
     Y alienta a en el futuro encarar las cosas con mas asertividad.

*** [2016-09-30 vie]
    Dia

** Octubre
*** [2016-10-10 lun]
Ayer experimente junto con la migraña otra recaida del estado animico,
lo que se manifesto principalmente durante la crisis, en la mañana de
hoy hasta volver de mi vieja y antes de la crisis migrañosa desde el
malestar animico con/contra las chicas desde la pataleta de la Cami,
pasando por la crisis de expansion de herramientas y crisis de
vacuidad o de dificultad para aprehender todo lo que leo, que en el
mismo dia de ayer procese entre dolores entre los dos cafes con la
determinacion de centrarme unicamente en dos cosas (python y orgmode).

Tambien influyen certeramente los sonidos, ya sea los sonidos lejanos
de barrio (que no son los mismos felizmente en el centro) como la
musica, los vecinos escuchando cuarteto, o folklore o simplemente el
ruido de los autos en la circunvalacion.
Todo esto te golpea pq uno esta en un estado de no-felicidad o
no-placer o insensibilidad. Aparte de la circunstancia de sentirse
mal, pq esta uno atrapado en la migraña y no tiene solucion, o no ve
la solucion o no ve que el medicamento te haga efecto, y eso te
distrae de lo que estas haciendo o te hace pensar que no podes o no
podras disfrutar de nada.
Tambien te afecta no tener objetivos o creer no tenerlos. En realidad
cuando estaba dentro de la crisis
[2016-10-08 sáb 15.00]--[2016-10-10 lun 13.00] crei no tener objetivos
o crei que mi vida no tenia sentido. Ahora lo veo distinto asi sea que
los objetivos sean insanos, -que podrian no serlos con algunos habitos
positivos intercalados- o sean atipicos. En realidad tengo un gran
objetivo, que es doble y ha veces hace que me pierda:
- Profesionalizar grandemente el negocio mediante un CMR y un conjunto
  de reglas de negocio, y un gran tablero de control
- Aprender lo que mas pueda de programacion y todos los temas
  relacionados.
Ambos objetivos que estan relacionados son importantes y son utiles.
Pq redundan en menos horas de trabajo, en mas desarrollo mental y en
posibles aplicaciones futuras que ahora desconocemos.

En el medio obviamente uno se pierde a veces.
En el medio puede que uno pierda el foco, o bien se canse y se
distraiga en forma desmedida y no sepa bien para donde ir.
O bien puede ser que los sufrimientos que te da el padecimiento de una
enfermedad (cosa de la cual nadie esta exento y menos yo, no hace
falta que de ejemplos) te hagan desepcionar o desilusionar siendo que
no tendria que ser asi.

Los avances son muchos y no deberian ser desdeñados.

*** [2016-10-11 mar]
Hoy amaneci pensando un par de cosas respecto a como integrar org-mode
con mis problemas actuales.

**** Usar el diario para filosofar e ir acumulando en un solo lado
Me gusto la experiencia de ayer en el sentido de hacer un autoanalisis
-que resulta muy efectivo y barato jeje- como lo hice la ultima vez en
el cuaderno.
Lo unico que org-mode puede precisamente ayudarme a esto a org --
mode. o sea a organizarme mejor. Pq via git lo tengo en todos lados y
via org si o si fechas, y luego tenes la posibilidad de tagear y de
buscar de manera mas eficiente.
Incluso el repositorio de gitlab privado p.e. mantenido en forma
separada al codigo es un buen lugar para acumular los escritos.
**** El sentido de filosofar o la necesidad en este momento
me refiero a filosofar quiza mas en el sentido de Eric Fromm o sea el
de un personal autoanalisis para reponerse y reacomodarse.
Lo sufrido este fin de semana en el perido descripto ayer te da un
poco de miedo, respecto a la debilidad de uno mismo para ser ecuanime
y quizas mantener la cordura o las relaciones intactas. Y como ese
bajon te viene y uno no tiene herramientas para combatirlo.
Hoy (post-hecho) me alegro de haber ido a mi vieja, en vez de quedarme
a lamentarme o ponerme mas oscuro y arruinarle el dia a ih.
Tambien pienso que ponerse a hacer una actividad fisica fuerte en ese
momento de distimia puede ayudar.
**** En si el cambio empezo cuando saque el auto
alli me empezaron los pequeños planes de hacer algo con el auto y no
dejarlo arrumbado ahi, y eso en cierta forma me cambio la mentalidad.
Hay un monton de lados donde uno podria ir a pasar el rato y esa
costumbre de permanecer encerrados y lugubres dentro de esa pieza no
es buena. Pero esto lo veo ahora que estoy aca en la oficina. Hay que
estar alla. 
**** Como enfrentar los miedos
ayer las chicas se fueron a cpaz y obviamente me asaltaron un monton
de miedos y aprensiones, y las espante de forma un poco extrema
diciendome a mi mismo o a los miedos, bueno ya, que pase lo que tenga
que pasar y a la mierda que se vaya todo a la mierda. O sea recuerdo
que me dije a la bosta si las matan a las dos. se va todo a la mierda,
... pero no voy a tener miedo, o sea no voy a permitir que sufra por
anticipado por cosas que quizas no pasen nunca. Y despues recorde que
yo muchas veces habia ido cuando joven y pq ellas no pueden hacer lo
mismo. Y creo que esa es la forma general de enfrentar los miedos sino
vivis una vida patetica de aprensiones de fantasmas que te acechan y
no te dejan vivir en paz.
**** Respecto a org-mode y su aprendizaje:
Pense que ya que tengo un conocimiento basico mas o menos general que
me permite ir produciendo en el, podria comenzar tranqui y en forma
organica y sistematica ir aprendiendo con vias al mastering.
P.e. comenzando un tema, como puede ser las tablas. Y aprender todo
sobre eso y luego ir avanzando capitulo por capitulo de acuerdo al
interes que tenga.

*** [2016-10-12 mié]
**** Crisis de trabajo en el hogar
    creo que el horario reducido me hace mal. Porque me da la
    sensacion de que estoy en falta y no esta bien lo que hago.
    Hoy por ejemplo llegue aca a las 10.30hs tome una segunda leche pq
    la primera fue muy deficiente y no me fui directo a programar ni
    al tema computacion. Sino que me puse a buscar los doc a devolver
    y de paso libere un estante para los docs y puse alli los tocos de
    docs ordenados de a cien (solo faltan 17 que debe ser un toquito
    mesclado con los recibos). Los recibos los apile sin orden de
    fecha, en caso de necesitar tendre que sacar todo. Creo que tendre
    lugar alli para un año. (De todos modos creo que los recibos
    tendria que destruirlos y a la maquina de aca encriptarla).
    [Ampliar tema seguridad]
    Luego conte y revise 4 fajos, cosa que es una tarea de siempre y
    lo mismo se hace hace aca como prolongacion  de la oficina.
    Hasta alli se podria pensar, en una jornada de 9 a 12hs en oficina
    "llenada" con computacion o una jornada adosada terminada aca con
    dos tareas de oficina que son altamente necesarias.
**** Crisis de comida
    Luego me fui a comprar algo de verduras.
    Alli otro tema, es que vengo mal con la comida. Al perder los
    habitos basicos de licuado y muesli quedo bastante
    maltrecho. Porque pierdo energia y nutrientes que tenia con
    seguridad.
    Casi que estoy entrando en una crisis de compras de alimentos, pq
    dos por tres el super me resulta tedioso al tener que hacer cola
    en cualquier horario para traer dos o tres cosas locas. Y al no
    querer destinar ningun horario para eso. Hoy fui a esa
    verduleriita de la vuelta y es muy poco lo que tienen y al haber
    caido en un pozo alimentario no me resulta facil determinar que es
    lo que quiero comprar o comer.
    Luego voy camino a la subalimentacion y al abuso del pan y a la
    falta de fuerza por falta de alimento y a los efectos secundarios
    por falta de nutrientes que se manifiestan sicologicamente y a lo
    peor de todo a la dependencia de ir el fin de semana alla pq
    necesito comer bien.
**** Levantar de a poco los habitos
     podria recuperar de uno a uno los habitos y llevar la cuenta de
     como voy en ellos en un org ad-hoc.
     P.e. el primero que hare ya mismo es el licuado.
**** Analizar (con analista) los problemas (supuestos)
     obvio que todo nace de una BTF gigante. P.e. hoy me amargue con
     el dpto que en general me gusta y al que estoy acomodando para
     que me guste mas, pq no tiene balcon donde desagotar el aire ac.
     Y bueno solucion 1, poner la manguera adentro y soportarla asi,
     de todos modos estoy mejor que los ochenta monos aca adentro que
     no tienen aire por lo visto.
     solucion 2, seguir el caminito del vecino de abajo o sea poner
     una prolongacion de 2 metros y hacerlo caer justo en el mismo
     punto del vecino de abajo, de modo tal que seamos dos
     supuestamente.
     solucion 3 si me voy a poner belico, es reclamar que la falta es
     parangonable con las mascotas que abundan en el edificio.
     solucion 4 (utopica) prolongar mas y hacerlo salir en la
     cocina...

     Una vez analizado un problema pierde su dimension y pasa a ser
     una molestia mas.
     La sensacion que te invade es que si tenes un problemita se te
     viene la maroma o toda una maroma haciendote invivible el sistema
     en general. O sea una generalizacion e intensificacion difusa de
     los problemas. O sea me siento mal pq en general este dpto se
     transformara en una mierda para vivir (o sea asi pensaria frente
     a un problema especifico que requiere TF y no tanta BTF)
**** Sintoma reaparecido dolor ojo izquierdo
     Comenzo levemente a las 13hs y me recoste despues de almorzar sin
     leer pantallas y tratando de hacerme palming, pero las untaditas
     vienen solas. Me tome la presion dos veces, pero no se si anda la
     bosta esa 12:8 antes de acostarme y 13.7:9 despues.
     Tendria que ir al oculista pq puede ser glaucoma de angulo
     estrecho que te hace perder la vision. Los sintomas pueden venir
     continuos o discontinuos.

**** Hoy nuevamente crisis existencial
     En cierta forma reaparece en forma continua lo que siempre
     aparecio y es el derrotero hacia donde me dirijo y como he jugado
     mal mis cartas. Aunque quizas la forma en que he vivido sea la
     unica forma posible de acuerdo a mi personalidad y que en este
     sentido si hice y hago siempre lo que quiero.
     Desde esa indiferencia hacia el dinero en general, pero esa
     gigante hipersensibilidad a perderlo o a ser exaccionado o bien a
     tributar cualquier tipo de tributo.
     Y la cuenta regresiva cada tanto me marca los años, esta vez 12
     para la edad jubilatoria y en un marco que aunque muy positivo
     desde un punto de vista (vivir en el centro, posibilidad de
     conocer a alguien, pocas responsabilidades horarias y facticas)
     se me plantea como ambiente el dpto dentro de lo lindo y
     agradable como que es un poco insano, y si no el dpto el vivir en
     el centro en general. Pero todo es discutible pq no creo que
     hayan sido mas "sanos" los esquemas anteriores, ya sea cabaña o
     patricios y tampoco resolvieron para nada la crisis existencial.
**** Sobre el valor de lo que estoy haciendo en el contexto actual
     Yo aca tenia o tengo -vale decir- un plan en general y era
     programar el CMR y demas para tener una administracion realmente
     eficiente y a la vez mind-sweeped. [Debo poner un ejemplo: desde
     que tengo el pasador de clientes que quieren comprar me resulta
     altamente facil. Cosa que antes siempre fue un problema] Y asi
     creo que cuando el CMR tenga todos los modulos se puede lograr
     una administracion rapida y eficiente y alli poderme dedicar a
     generar venta extra, sin caer ahora en este momento en un estress
     excesivo y poner en riesgo la continuidad de la programacion.

     Esto puede leerse como una excusa para la vagancia y la evasion
     en el sentido de que mientras siga embarcado en el proyecto de
     programar evito el generar venta extra con lo que eso signifique
     para el momento actual. (Un poco influido por la particular
     situacion de estos tiempos en los cuales estoy acosado
     judicialmente por el fisco cordobes al pedo, pero ya
     irreversiblemente y junte otro frequito juicio justo en el puto
     momento en que la pila de años pasada sobre los juicios viejos te
     hacia pensar que podias safar o que nada iba a pasar. Y es dentro
     de ese contexto en el cual no me quisiera ver con un grupo de
     venta).
     O como una razon valida. Seamos realistas, en esta etapa del
     negocio basada en la venta a los clientes y en una mayor toma de
     riesgo facilitada por el sobrante de capital aparte de una
     gestion uniforme de la cobranza quizas como la que no tuvimos
     nunca estoy desarrollando un sistema de programas no digo como
     los que nunca tuve porque he tenido varios sistemas bastante
     ajustados y a medida, pero si un sistema (en produccion todavia)
     que se ajuste a la realidad actual. Tampoco podemos estar
     vendiendo 500k, cobrando 370k y soñar con aumentar un poco la
     venta, con retazos programaticos de otra epoca que ya no se
     adaptan a lo que hacemos ahora y encima estar alejado de toda
     posibilidad de parchear. Pq es mas dificil parchear que hacer
     algo de nuevo. Y seamos realistas la programacion requiere dos
     pasos, una aprender y la otra hacerlo. No tenemos recursos para
     pagar eso y no lo hariamos, como paso con ollas siljor cuando le
     pidieron una bonita suma de dinero para desarrollar un sistema de
     marketing.
     Nosotros tenemos una aplicacion de celular o sea de calle con
     posibilidad de testear padron y ver la totalidad de las cuentas y
     no creo que otra empresa similar la tenga programada por ellos
     mismos.
     (Ojo que si quizas tengan otras cosas, como un grupo de venta mas
     fuerte o una habilidad mayor para generar y cuidar el dinero)
     
     ¿Se podria programar y a la vez formar un sistema de venta?
     No creo. La programacion si bien es cierto que con varias
     desviaciones instrumentales (vim,emacs,org-mode,etc) me llevo una
     dedicacion full time. Si esa dedicacion no la haces no formas
     masa critica de conocimientos como para arrancar.
***** Bajon en la programacion??
     Hoy y quizas un poco ayer, peligrosamente he frenado la
     programacion, cayendo en un estado como quien diria de falta de
     inspiracion. Y aunque segui avanzando despacito con org-mode,
     incluso centrandome en estos escritos no arranco. Y eso que el
     modulo que tengo entre manos es muy necesario. Y eso que el
     contexto computacional que es el que se me chifla a esta altura
     entro en un punto agradable se puede decir con un vim muy lindo y
     eficiente para trabajar y un orgmode facinante para mis escritos,
     el cual tiene un nivel de usabilidad a hoy lo suficiente como
     para producir y pequeños incrementos diarios de conocimiento que
     no estan trabados ni frustrados. Y con el sistema git/gitlab
     tengo lo que siempre ansie, un sistema de escritos global, pq
     puedo escribir en mi compu, en la netbook, aca en la ofi y todo
     remite a un repositorio en la web que es accesible desde todos
     lados y a la vez puedo leer en formato bastante agradable el
     mismo archivo producido actualizado en el celu. O sea una
     sincronizacion de cuatro maquinas.
**** Despues de todo que se podria estar haciendo en ventas
     Es obvio que todo movimiento en relacion a las ventas tiene que
     tener las siguientes condiciones:
     1. No debe pasar por Fede (o sea p.e. a nivel reparto) pq ya esta
        demostrado en la experiencia de Fede y en la mia que cualquier
        persona extra que se deba atender ya sea conocida
        (Lesta,Franco) o desconocida, te haria perder tiempo, te baja
        la venta y no justifica ni siquiera lo que esas personas agregan
     2. No debe implicar aflojar o cambiar el esquema actual y
        reemplazarlo por un esquema superador (como que Fede se haga
        cargo de "toda" la venta, ¿y como se supone que eso se haria?
        dejando lo que esta haciendo y poniendo una oficina para
        buscar vendedores???)
     Entonces ¿que queda? que yo mismo desde la oficina genere
     vendedores que vendan pero que no tengan que pasar por Fede como
     repartidor, o sea una venta al estilo 2005 entregadas con
     bolsita.
     Pero eso aparte de significar un riesgo (lo cual puede ser
     totalmente calculado) genera una exposicion aca en el local que
     por ahora no creo que quiera o pueda hacerlo.
     
     Y hay que considerar lo que se podria hacer con lo que ya
     tenemos:
     1. comprar la kangoo para que se pueda abastecer mas
        eficientemente la venta
     2. cambiar el vendedor acompañante para que sea mas
        eficiente. Posiblemente Franco ya este quemado y una persona
        con mas espiritu de venta pueda con el mismo recorrido elevar
        un poco la facturacion.
*** [2016-10-13 jue]
    Hoy un moco total pq amanecio lloviendo y eso hizo que no vinieran
    dos chicos, menos mal que salieron un par, para ir avanzando. Pero
    lo mismo yo me clave, fui al banco esto estuvo bueno y lo mismo
    tengo que ir esta tarde por el seven. No me importa mucho eso.
**** apuntes sobre la alimentacion
     lindo: pq ayer a la tarde me tome una jarra de licuado. Bien
     preste atencion a la miel (aunque no parezca factor fundamental
     del licuado), compre y puse maca premium, y el resto lo de
     siempre, almendras pasas de uva, lino molido y chia, avena y
     manzana. Y quedo rico, muy rico y llenador. Y hoy se vio el
     resultado ... un sargento garcia de unos 30cm y varios cabos
     arriba y la sensacion de que habia vaciado el intestino no como
     los ultimos dias que iba en declive.

**** algunos temas en compras que hay que tener en cuenta
     algunos son transicionales y no enteramente ortodoxos pero es
     mejor hacer algo que nada. P.e. las lentejas en lata para
     combinar con el arroz. Le hice el uparsin-tekel-mene-mene a la
     verdu de la cañada pq al final no me cobro mal, y permite
     autoservicio y trae cosas buenas. Creo que tambien las compras
     deben tener el concepto de be-normal pq sino no se puede hacer
     nada. Y tengo que cambiar la alimentacion si o si urgente.
     Comparando el licuado, el cual no hay que abandonarlo y cuidarlo
     para que sea sustentable, con las opciones antiguas como pan
     manteca dulce y cafe, creo que esto gana y a la larga tiene que
     cambiar la bocha.

**** Hoy un tema nuevo para el estudio (que tendra que esperar)
     seguridad informatica. O sea todo un tema. Te agarra la paranoia
     de que la forma de actuar en la red es totalmente despreocupada y
     uno termina completamente expuesto, hasta en la forma mas tonta y
     ridicula.

*** [2016-10-14 vie] 
**** Hoy conoci tox
     que parece ser un protocolo para comunicacion pear to pear con
     clientes en android y en todos los sistemas.
     Para analizar
**** Me gusto la idea de html5 y python para alguna aplicacion
     que reemplace el androwish. 
     como una especie de sitio privado para navegar la info que
     tenemos en la base de datos.
     Pq parece bastante facil de programar la interface. Quedara para
     el futuro
**** Rescato lo que paso ayer o sea descansar y luego programar
     y al final la programacion fue mucho mas fertil e inspirada, que
     obligarse a estar cuando uno esta cansado o dolorido.
**** Experiencia de relax y fluir
   Luego llego a casa en un estado raro, no queria sentarme a
   programar, me sentia saturado, y me hice una merienda frutal con
   manzana, arandanos y frutilla y medio vaso de licuado, previamente
   haberme bañado tranquila y relajadamente, todo esto mientras veia
   la mitad de la pelicula que habia dejado pendiente, y la verdad que
   me relaje bastante, luego me recoste un rato (en realidad el orden
   de estos sucesos ya los olvide pero el resultado grato lo recuerdo)
   la cosa que despues si me sente a programar y la verdad que fue
   altamente productivo el tiempo que estuve, en cierta forma como
   destrabado. Quizas sea que haya aprovechado una base que habia
   hecho en la oficina, pero si me senti como que "fluyo" el trabajo y
   me senti como que podia terminar alli mismo todo el modulo, pero me
   fui a dormir. Esta mañana crei tener un par de puntaditas de nuevo
   en el ojo, aunque no son en el ojo sino en el arco superciliar.

**** el embole de esperar
     a pesar de que achique los horarios a mas no poder, me embola esperar
     y no tener tarea concreta que hacer. Y poder o necesitar hacer muchas
     cosas que no hago como limpiar un poco la oficina y uno tiene que
     esperar. 
     Eso tambien me embola con relacion a la Romi, pq contribuye bastante a
     que la oficina se ensucie y no es capaz de ayudar.
**** me desespera el dolor de cabeza
     me embola el malestar, el dolor, las dolencias y me empiezo a asustar
     y luego recuerdo que yo siempre estuve asi. O sea yo soy cronico. Con
     la diferencia que estos ultimos dos o tres dias he estado comiendo muy
     bien con relacion al 2006 y los emboles que me pego no son tan grandes
     como en el 2006. 
     Me pregunto que voy a hacer si me enfermo, si tengo ya mi edad y no
     tengo nada hecho. Nada organizado pq uno vive siempre en forma
     precaria. Y lo que es peor no tiene entusiasmo por lo que hace y en el
     fondo eso hace que uno no produzca.
**** de vuelta el fin de semana y la incertidumbre de no saber que hacer
     en las ultimas dos semanas he notado beligerancia de parte de las
     chicas, y no la he pasado bien en general. Y me encuentro con que una
     vez que me meto alla no salgo mas o sea me tengo que quedar hasta el
     lunes a la mañana y eso me causa imagenes negativas. Pq me pongo
     negativo y estar alla no me hace bien. 
     Me gustaria llevarme el auto para poder salir mas libremente, y quizas
     ir haciendo alguna cosita nueva. Vivo en forma muy rutinaria, y
     tambien los fines de semana son parte de esa rutina.
     pq en el fondo estoy preso de un circulo vicioso del que me da miedo
     salir.
     La realidad es que el circulo funciona asi:
- cuando estoy en tiempo de salida (el clock empieza el viernes a las
  18 pero se podria dilatar hasta el sabado a la mañana con suerte y
  mucha voluntad) entro en un estres de estar incumpliendo, de estar
  faltando a algo y a la vez comienza el miedo a que si me demoro las
  represalias seran grandes. Y esa incomodidad a la vez hace que no
  disfrute o no me concentre o no pueda hacer cosas positivas o bien
  relajarme y hacer algo no-utilitario para mi mismo.
- entonces voy, muchas veces obligado, y me llevo toda clase de
  elementos para distraerme, en especial la netbook y el celu. Y
  quiero seguir enfrascado en esos temas que son los unicos que me
  distraen y a la vez por falta de oxigenacion en otros temas o de
  disfrutar en otros temas.
- una vez que voy no me puedo volver, o sea quedo totalmente preso sin
  chances de acortar la jornada. (Al menos antes en Patricios el
  domingo a la tarde me iba y eso permitia organizar el comienzo de la
  semana)
- y la situacion ya llega al maltrato o distrato de las chicas y a la
  consiguiente reaccion de parte mia. Haciendose una atmosfera fea
  para estar.
**** hoy decido no someterme mas al chantaje
     quiero cortar el circulo vicioso al medio. Es decir el miedo a no
     ir pq eso significara no poder ir mas o que sea feo ir. Cedo por
     necesidad, quizas la necesidad de creer que voy a necesitar o voy
     a querer ir.
     De pronto las imagenes de mi mismo yendo alla y quedandome y
     siendo relativamente bien atendido, quizas con la libertad de la
     banda ancha etc. son imagenes que me quedaron de la epoca de la
     cabaña cuando realmente vivia en la necesidad, pero ahora no es
     asi. Y si ir alla me va a hacer caer en lo malsano, lo insano
     creo que es mejor no ir. Total un par de semanas que no me vean
     no va a ser nada. Y los tres chicos tienen la total libertad para
     venir, hasta la Cami. Ya no soy yo el que tengo que ir. O sea que
     podria ser una especie de nirvana nuevo.
     Pero el concepto basico es que no me voy a someter al chantaje de
     que tengo que ir todo el periodo o sino no voy a ir.
**** Siempre pense en el pasado que si alguna vez llegaba al punto w
     a nivel soledad me las iba a apañar e iba a empezar a salir de
     nuevo por mis medios. Iba a buscar otra forma de administrar mi
     tiempo que no fuera tan insana. 
*** [2016-10-15 sáb]

    Hoy un dia altamente productivo. O maso, depende como se vea. A
    pesar de haber estado atravesado por el dolor de espalda que se me
    fue y por la migraña y por el golpazo en la frente, me levante
    fui a comprar lo que tenia y limpie la oficina muy bien.
    Hacia falta limpiar la oficina, lo que no entiendo es todo el
    constructo que me hago alrededor o sea todo ese resentimiento
    hacia la familia, en especial la Romi. Pq supuestamente me
    gustaria que me ayuden. Pero no importa lo hice y disfrute
    haciendolo y creo que una limpieza asi cada 3 meses esta bien.
    Luego instale manjaro-Deepin que me parece bastante
    adecuado. Aparte de que tiene varias cositas muy bellas, anda el
    sonido out the box cosa que en i3 no y aparte aproveche para
    encriptar el disco. (Y debo decir que i3 empezo a pitear un monton
    en el arranque con un monton de errores.)
    La instalacion estuvo muy facil, y deje un instructivo en org para
    facilitarme la vida si tengo que instalar de nuevo.
    [[file:doc-deepin.org][Instalar Deepin]] 
    Hay dos cosas que voy incorporando que van a hacer una diferencia:
    - el trabajo con org que recien comienza y puede crecer. No quiero
      pensar la base que tendre en un año.
    - la alimentacion que retorno con fuerza. La fruta, la avena, el
      licuado el muesli, etc. Me hace pensar que puedo volver a un
      sistema fuerte pronto si le agrego ejercicio.

    No puedo olvidar que lo mas importante de este finde es no haber
    ido ayer alla. Fue un dia distinto y como dije productivo. Lo
    unico es que el clima acompaño un monton, no se que hubiera sido
    si el dia no hubiera estado asi.
    Pero lo que comenzo como una rebeldia pasa a ser un arruge pq uno
    no sabe si se bancara el destierro. E ih con sus buenos modos no
    deja de seguir amenazando.

    Hoy decrete el no va mas con relacion al migral. El lunes me
    instalo en el hospital a buscar una solucion. Debo cortar y buscar
    alternativas pq no hay forma de seguir asi.
*** [2016-10-17 lun]
    Hoy es el aniversario de la muerte de mi viejo. Y como siempre
    pasa desapercibido y nunca se hace ni una mencion, ni una
    reflexion. Como asunto olvidado. Quedara en cada uno
    obviamente. Es el ritmo vertiginoso de la vida. Es que uno tiene
    una agenda de carrera o de malos habitos y no se permite tiempo
    para la reflexion y el recuerdo.
**** Ih y los malosentendidos que produce el nirvana
     Com era de esperarse la relacion fue un poco tensa y se lleno de
     malosentendidos. Parte creo pq somos como somos y ya no vamos a
     cambiar. Creo que la gente es como es y generalmente no cambia y
     yo soy asi boludo y tengo esa forma de ser que genera dudas y
     ella que es insegura cae en la inseguridad y ya no puedo arreglar
     nada pq hay una tonelada de pasado que nos aplasta y ya no hay
     vuelta atras. Es como si toda la buena letra de estos ultimos
     meses se fuera al tacho por una escalada de inseguridad que
     produce la situacion que uno haya cambiado la rutina.
     Y el finde fue breve, y llenado con visitas a otros que abarcaron
     la mayoria del tiempo y luego de nuevo el dolor de cabeza y luego
     una tensa charla o monologo disipador de migrañas y de nuevo el
     desencuentro.
     Pero creo que el problema nace de que la falta de ganas de ir
     para alla todo el tiempo. Pq ya las vivencias desagradables
     superan las agradables. Y en esa ecuacion las chicas tienen el 70
     e ih solo el 30. Pero al reducir las horas o cambiar el esquema
     ya creo un ambiente propicio para el desencuentro y la
     desconfianza y ya crece la beligerancia con la propia ih, lo cual
     produce que en general yo quiera directamente no ir.
     Hasta tal punto llegamos que creo que salvo que se produzca una
     gran aflojada de mi parte (cosa bastante probable) o bien un
     intento de acercamiento de ella (cosa probable pero menos) el
     proximo finde directamente no quisiera ir. O no hesitar en
     volverme ahi nomas a las 6 de la tarde.
**** Estoy solo solo
     Como decia Dyer tengo soledad existencial. Y ya no tengo nada
     para esperar de los demas. Incluso creo aparte de lo mas
     inmediato que seria dejar de depender en cosas nimias (suplemento
     de comida los findes, ir a lavar la ropa alla, tener alguien con
     quien hablar,mediacion para tratar con los demas), tengo que empezar a ver por mi mismo y sin la
     intervencion de ih de las cosas importantes para mi como cambiar
     mi forma de vivir, empezar a previsionar para el futuro y ver que
     estrategia de trabajo voy a tener. Y no puedo ser claro y
     eficiente en la determinacion y consecucion de esos objetivos pq
     al no ser una pareja real donde podamos tirar para el mismo lado
     los intereses mios colisionan con los intereses de ella. Y el
     formato de creer que ella comulga con los intereses mios es
     falaz, pq tarde o temprano uno cae en la cuenta que los intereses
     de uno estando con ella no avanzan sino que enferman.
**** Objetivos personales basicos
1. cambiar de forma de vida
2. ver la estrategia de trabajo a seguir
3. previsionar para el futuro
**** Fui al medico
     Y debo decir que fue gracias a que ih llamo. Pq hubiera sido por
     mi no hubiera ido. Y esta bien que haya ido.
     Pero la charla derivo como siempre al tema pareja y me dio unos
     muy buenos tips. En especial lo de hablar y hacerlo con altura. O
     sea quedar de acuerdo con ella para salir y hablar
     independientemente que las chicas quieran o no quieran. Para ver
     si se puede salvar algo o no. Y en su caso dar por terminado pero
     bien.

    
* Constructos
** Be normal
** mind sweep
   

* Temas a pensar y/o articular
** Seguridad en dpto

*** Cuanto tiempo vale la pena guardar los recibos?
    Siendo que no estamos en bco y son un medio de prueba en cierta
    forma de un ingreso percibido, todo al vicio pq no hay ninguna
    utilidad en tenerlos, aparte del lugar que ocupan y luego viene lo
    dificultoso que es ponerse a romper una tonelada.

* tema alimentario (luego trasladar a otro sitio)
** opciones de comidas para considerar
*** Guiso cereal y verduras
    puse una rodaja de calabaza, un poco de sal, un poco de mijo
    lavado y un poco de amaranto y lo hervi. Feo olor, como comida de
    perro pero se deja comer bastante, con oliva y un poquito de queso
    rico
*** Usar la legumbre en latas
    antes que nada es mejor  y permite combinar el cereal.
*** Un tomatito, lentejas, ajito y una ensaladita que acompaña





