* Bitacora general
** [2016-09-21 mié] 
Desde ayer implemento un tip que se me ocurrio y es hacer una serie de ejercicios
simples (los mismos tres que conozco desde hace casi 30 años) por cada hora o periodo
de maquina, como pago. Mas 5 sentadillas. Y el resultado ha sido fenomenal, pq me
saca la contractura y un poco el dolor de espalda (aunque hoy estuve doblado cuando
fui a trabajar) sino que tiene efectos espectaculares en el animo. Tanto es asi que 
ayer me puse a encintar toda la pared y hoy la pinte.

Lucho contra la idea de ir y volver respecto a la herramienta. Hoy pensaba volver a
vim, pq lo veo rapido y expedito, (siendo que tengo aca evil que muchos dicen que es
mas lindo que vim). Y siendo que descubri org-mode que recien estoy aprendiendo y es
extraordinario, para irlo conociendo de a poco.

No quiero perder el ritmo de la programacion. Siendo que voy viendo resultados. 

** [2016-09-22 jue]
Hoy termine de pintar la pared del living y colgue los cuadros
cambio muchisimo y no fue gran tarea, sino que fue agradable y
permite cambiar un poco de actividad

** [2016-09-25 dom]
*** Ejercicio-movimiento
Esta ultima semana al menos comence a hacer ejercicio y ahora con
tomatinho pienso que se facilitara muchisimo comenzar a moverse
durante la jornada y evitar el anquilosamiento.
Asimismo pasar de 20 cuadras basicas a 30 o 40 no lo veo dificil ni
imposible.
*** Implementar cuanto antes el 3x12
*** Alimentos
Urgente debo volver a una alimentacion mas sana. Hoy comi
pollo/gaseosa/helado o sea el trio maldito que alguna vez habia
superado. Mucha manteca, mucho pan. Un desastre. Esta ultima semana no
hice el muesli ni un dia.

*** Acomodo del dpto
La semana pasada di un paso gigante que fue la pintada de la pared.
Debo seguir con ese sistema en lo posible.
** [2016-09-28 mié]
*** Entre ayer y hoy tome el toro por las astas
en un par de cosas que estaba demorando como ser comprar la camisa en
rochas, ir al peluquero, y hoy arreglar los cueritos de las
canillas. Y los tres asuntos los resolvi expeditamente, o sea creo que
no hay porque demorar las cosas.

** [2016-09-29 jue]
Hoy es un milestone en nuestras vidas. Hoy recibio su diploma de
Contadora la Rominita. Ha pasado un largo trecho desde aquella noche
de julio del 91 cuando solo en la oficina escribi un post,
lamentablemente perdido en DOS-WordStart alusivo al nacimiento de la
Romi y 25 años despues estoy escribiendo esto en una herramienta que
no difiere mucho de aquella en cierta forma, y quizas tambien
destinado a perderse.
Me alegra que ella haga algo de su vida y haga las cosas bien.
Fue un dia feliz, aunque no tenemos los musculos de la felicidad muy
entrenados en la familia, al menos en la modalidad expresividad.

*** Referencia al metodo usado en los ultimos tres dias
Constructo: Actua como un tipo normal.
Con relacion al evento (que causo mucha preocupacion anticipatoria e
innecesaria casi al nivel de la opercion de mi vieja), se planteaban
un par de todo's necesarios y urgentes que eran los que me causaban
problema. Necesitaba comprarme una camisa e ir al peluquero. Aunque
ambos temas son ridiculamente banales, representaban un problema en el
sentido de que son ambas situaciones que me incomodan, ya sea en el
sentido de ir y hacerlas y en el sentido de pensar que voy a salir
defraudado por dichas acciones. Y el constructo usado, me movilizo y
el martes volvi temprano de la oficina, me bañe rapidamente, me puse
el saco y fui a comprar la camisa en un proceso directo y normal.
Luego ayer fui al peluquero, por ahi el problema no era tanto ir a las
dos opciones, sino el patetico miedo a que no fuera satisfactorio el
resultado. Y con una ligerisima duda, fui y el resultado me parece
mejor que la ausencia de resultado, o el demorarse como lo hacia antes
con el resultado de andar desprolijo  e impresentable.
Quedaba procesar el evento, y alli el constructo fue dividirlo en dos
partes, por una parte la ceremonia, y luego el ir al lugar, y eso
quito un poco de presion, una vez en el lugar el resultado fue
bastante positivo a pesar de la situacion, (almorzar con niños en un
sitio asi, y el que Fede pobre estuviera tan dolorido y molesto).
Creo que como me pasa en la mayoria de las situaciones, alli no fue
problema de plata, ya estaba jugado, sino el pensar que podia faltarme
con lo que habia llevado.
Pero pienso que la experiencia es positiva y tiene un efecto
liberador.
Y alienta a en el futuro encarar las cosas con mas asertividad.

 
