* Bitacora general
** [2016-09-21 mié] 
Desde ayer implemento un tip que se me ocurrio y es hacer una serie de ejercicios
simples (los mismos tres que conozco desde hace casi 30 años) por cada hora o periodo
de maquina, como pago. Mas 5 sentadillas. Y el resultado ha sido fenomenal, pq me
saca la contractura y un poco el dolor de espalda (aunque hoy estuve doblado cuando
fui a trabajar) sino que tiene efectos espectaculares en el animo. Tanto es asi que 
ayer me puse a encintar toda la pared y hoy la pinte.

Lucho contra la idea de ir y volver respecto a la herramienta. Hoy pensaba volver a
vim, pq lo veo rapido y expedito, (siendo que tengo aca evil que muchos dicen que es
mas lindo que vim). Y siendo que descubri org-mode que recien estoy aprendiendo y es
extraordinario, para irlo conociendo de a poco.

No quiero perder el ritmo de la programacion. Siendo que voy viendo resultados. 

** [2016-09-22 jue]
Hoy termine de pintar la pared del living y colgue los cuadros
cambio muchisimo y no fue gran tarea, sino que fue agradable y
permite cambiar un poco de actividad

** [2016-09-25 dom]
*** Ejercicio-movimiento
Esta ultima semana al menos comence a hacer ejercicio y ahora con
tomatinho pienso que se facilitara muchisimo comenzar a moverse
durante la jornada y evitar el anquilosamiento.
Asimismo pasar de 20 cuadras basicas a 30 o 40 no lo veo dificil ni
imposible.
*** Implementar cuanto antes el 3x12
*** Alimentos
Urgente debo volver a una alimentacion mas sana. Hoy comi
pollo/gaseosa/helado o sea el trio maldito que alguna vez habia
superado. Mucha manteca, mucho pan. Un desastre. Esta ultima semana no
hice el muesli ni un dia.

*** Acomodo del dpto
La semana pasada di un paso gigante que fue la pintada de la pared.
Debo seguir con ese sistema en lo posible.
** [2016-09-28 mié]
*** Entre ayer y hoy tome el toro por las astas
en un par de cosas que estaba demorando como ser comprar la camisa en
rochas, ir al peluquero, y hoy arreglar los cueritos de las
canillas. Y los tres asuntos los resolvi expeditamente, o sea creo que
no hay porque demorar las cosas.

** [2016-09-29 jue]
Hoy es un milestone en nuestras vidas. Hoy recibio su diploma de
Contadora la Rominita. Ha pasado un largo trecho desde aquella noche
de julio del 91 cuando solo en la oficina escribi un post,
lamentablemente perdido en DOS-WordStart alusivo al nacimiento de la
Romi y 25 años despues estoy escribiendo esto en una herramienta que
no difiere mucho de aquella en cierta forma, y quizas tambien
destinado a perderse.
Me alegra que ella haga algo de su vida y haga las cosas bien.
Fue un dia feliz, aunque no tenemos los musculos de la felicidad muy
entrenados en la familia, al menos en la modalidad expresividad.

*** Referencia al metodo usado en los ultimos tres dias
Constructo: Actua como un tipo normal.
Con relacion al evento (que causo mucha preocupacion anticipatoria e
innecesaria casi al nivel de la opercion de mi vieja), se planteaban
un par de todo's necesarios y urgentes que eran los que me causaban
problema. Necesitaba comprarme una camisa e ir al peluquero. Aunque
ambos temas son ridiculamente banales, representaban un problema en el
sentido de que son ambas situaciones que me incomodan, ya sea en el
sentido de ir y hacerlas y en el sentido de pensar que voy a salir
defraudado por dichas acciones. Y el constructo usado, me movilizo y
el martes volvi temprano de la oficina, me bañe rapidamente, me puse
el saco y fui a comprar la camisa en un proceso directo y normal.
Luego ayer fui al peluquero, por ahi el problema no era tanto ir a las
dos opciones, sino el patetico miedo a que no fuera satisfactorio el
resultado. Y con una ligerisima duda, fui y el resultado me parece
mejor que la ausencia de resultado, o el demorarse como lo hacia antes
con el resultado de andar desprolijo  e impresentable.
Quedaba procesar el evento, y alli el constructo fue dividirlo en dos
partes, por una parte la ceremonia, y luego el ir al lugar, y eso
quito un poco de presion, una vez en el lugar el resultado fue
bastante positivo a pesar de la situacion, (almorzar con niños en un
sitio asi, y el que Fede pobre estuviera tan dolorido y molesto).
Creo que como me pasa en la mayoria de las situaciones, alli no fue
problema de plata, ya estaba jugado, sino el pensar que podia faltarme
con lo que habia llevado.
Pero pienso que la experiencia es positiva y tiene un efecto
liberador.
Y alienta a en el futuro encarar las cosas con mas asertividad.

 
** [2016-10-10 lun]
Ayer experimente junto con la migraña otra recaida del estado animico,
lo que se manifesto principalmente durante la crisis, en la mañana de
hoy hasta volver de mi vieja y antes de la crisis migrañosa desde el
malestar animico con/contra las chicas desde la pataleta de la Cami,
pasando por la crisis de expansion de herramientas y crisis de
vacuidad o de dificultad para aprehender todo lo que leo, que en el
mismo dia de ayer procese entre dolores entre los dos cafes con la
determinacion de centrarme unicamente en dos cosas (python y orgmode).

Tambien influyen certeramente los sonidos, ya sea los sonidos lejanos
de barrio (que no son los mismos felizmente en el centro) como la
musica, los vecinos escuchando cuarteto, o folklore o simplemente el
ruido de los autos en la circunvalacion.
Todo esto te golpea pq uno esta en un estado de no-felicidad o
no-placer o insensibilidad. Aparte de la circunstancia de sentirse
mal, pq esta uno atrapado en la migraña y no tiene solucion, o no ve
la solucion o no ve que el medicamento te haga efecto, y eso te
distrae de lo que estas haciendo o te hace pensar que no podes o no
podras disfrutar de nada.
Tambien te afecta no tener objetivos o creer no tenerlos. En realidad
cuando estaba dentro de la crisis
[2016-10-08 sáb 15.00]--[2016-10-10 lun 13.00] crei no tener objetivos
o crei que mi vida no tenia sentido. Ahora lo veo distinto asi sea que
los objetivos sean insanos, -que podrian no serlos con algunos habitos
positivos intercalados- o sean atipicos. En realidad tengo un gran
objetivo, que es doble y ha veces hace que me pierda:
- Profesionalizar grandemente el negocio mediante un CMR y un conjunto
  de reglas de negocio, y un gran tablero de control
- Aprender lo que mas pueda de programacion y todos los temas
  relacionados.
Ambos objetivos que estan relacionados son importantes y son utiles.
Pq redundan en menos horas de trabajo, en mas desarrollo mental y en
posibles aplicaciones futuras que ahora desconocemos.

En el medio obviamente uno se pierde a veces.
En el medio puede que uno pierda el foco, o bien se canse y se
distraiga en forma desmedida y no sepa bien para donde ir.
O bien puede ser que los sufrimientos que te da el padecimiento de una
enfermedad (cosa de la cual nadie esta exento y menos yo, no hace
falta que de ejemplos) te hagan desepcionar o desilusionar siendo que
no tendria que ser asi.

Los avances son muchos y no deberian ser desdeñados.

** [2016-10-11 mar]
Hoy amaneci pensando un par de cosas respecto a como integrar org-mode
con mis problemas actuales.

*** Usar el diario para filosofar e ir acumulando en un solo lado
Me gusto la experiencia de ayer en el sentido de hacer un autoanalisis
-que resulta muy efectivo y barato jeje- como lo hice la ultima vez en
el cuaderno.
Lo unico que org-mode puede precisamente ayudarme a esto a org --
mode. o sea a organizarme mejor. Pq via git lo tengo en todos lados y
via org si o si fechas, y luego tenes la posibilidad de tagear y de
buscar de manera mas eficiente.
Incluso el repositorio de gitlab privado p.e. mantenido en forma
separada al codigo es un buen lugar para acumular los escritos.
*** El sentido de filosofar o la necesidad en este momento
me refiero a filosofar quiza mas en el sentido de Eric Fromm o sea el
de un personal autoanalisis para reponerse y reacomodarse.
Lo sufrido este fin de semana en el perido descripto ayer te da un
poco de miedo, respecto a la debilidad de uno mismo para ser ecuanime
y quizas mantener la cordura o las relaciones intactas. Y como ese
bajon te viene y uno no tiene herramientas para combatirlo.
Hoy (post-hecho) me alegro de haber ido a mi vieja, en vez de quedarme
a lamentarme o ponerme mas oscuro y arruinarle el dia a ih.
Tambien pienso que ponerse a hacer una actividad fisica fuerte en ese
momento de distimia puede ayudar.
*** En si el cambio empezo cuando saque el auto
alli me empezaron los pequeños planes de hacer algo con el auto y no
dejarlo arrumbado ahi, y eso en cierta forma me cambio la mentalidad.
Hay un monton de lados donde uno podria ir a pasar el rato y esa
costumbre de permanecer encerrados y lugubres dentro de esa pieza no
es buena. Pero esto lo veo ahora que estoy aca en la oficina. Hay que
estar alla. 
*** Como enfrentar los miedos
ayer las chicas se fueron a cpaz y obviamente me asaltaron un monton
de miedos y aprensiones, y las espante de forma un poco extrema
diciendome a mi mismo o a los miedos, bueno ya, que pase lo que tenga
que pasar y a la mierda que se vaya todo a la mierda. O sea recuerdo
que me dije a la bosta si las matan a las dos. se va todo a la mierda,
... pero no voy a tener miedo, o sea no voy a permitir que sufra por
anticipado por cosas que quizas no pasen nunca. Y despues recorde que
yo muchas veces habia ido cuando joven y pq ellas no pueden hacer lo
mismo. Y creo que esa es la forma general de enfrentar los miedos sino
vivis una vida patetica de aprensiones de fantasmas que te acechan y
no te dejan vivir en paz.
*** Respecto a org-mode y su aprendizaje:
Pense que ya que tengo un conocimiento basico mas o menos general que
me permite ir produciendo en el, podria comenzar tranqui y en forma
organica y sistematica ir aprendiendo con vias al mastering.
P.e. comenzando un tema, como puede ser las tablas. Y aprender todo
sobre eso y luego ir avanzando capitulo por capitulo de acuerdo al
interes que tenga.

