* Films
** The irrational man			       :profesor:filosofia:asesinato:
   [2016-10-13 jue] Cuenta la historia de un profesor de filosofia que
   viene a una facultad y el tipo esta atravesando un bajon
   existencial. La vida no le interesa y atraviesa un gran displacer,
   nada le resulta placentero. Es sombrio, oscuro y practicamente esta
   abandonado. Comienza una amistad con una alumna que intenta sin
   exito sacarlo de ese marasmo. Un dia casualmente escuchan una
   conversacion en un bar sobre un juez que estaba arruinandole la
   vida a una mujer por abuso de poder en su cargo, y repentinamente
   el profesor encuentra en el asesinar a dicho juez su razon de
   vivir. A partir de ese momento su vida renace en todos los sentidos
   que antes estaban bloqueados. Comete el asesinato, pensando que no
   iba a ser descubierto, y al poco tiempo la misma alumna con quien
   ya ha comenzado un affaire lo descubre y confronta. La situacion se
   complica cuando la chica lo obliga a confesar el crimen pq alguien
   inocente va a ser inculpado y el ya no quiere abandonar los
   placeres de esta nueva vida que acaba de conseguir y decide matar a
   la chica para cubrir su crimen, intento que casualmente le falla y
   muere accidentalmente el mismo.
   :Calificacion: 4/5
   :Actor: Joaquin Phoenix
* Series
** The Night of					    :prision:inocente:juicio:
   [2016-10-17 lun] Terminada.
   8 capitulos.
   Narra la historia de un chico pakistani en NY que le saca sin
   permiso el taxi a su padre (que a su vez lo tiene en sociedad con
   dos mas y que representa su unica fuente de ingresos que les
   permite tener una vida de clase media a pesar de ser inmigrantes)
   con la finalidad de ir a una fiesta y la cadena de sucesos lo lleva
   a conocer una chica rica drogadicta y con problemas que lo lleva a
   la casa donde tienen sexo y juegos peligrosos, luego despierta
   abajo en la cocina sin saber que paso anoche y cuando sube a la
   habitacion la chica esta muerta con un monton de puñaladas. Entra
   en panico y escapa, pero olvida las llaves del auto, cuando quiere
   entrar de nuevo a la casa tiene que romper un vidrio y eso alerta a
   los vecinos, saca las llaves, se lleva el cuchillo ensangrentado y
   sale a los piques con el taxi, y luego casualmente por doblar mal
   una esquina lo para la policia y lo detienen por ebriedad. Y cae a
   la misma comisaria donde se procesa el asesinato, donde al final lo
   detienen.
**** La vida y el trabajo del abogado
**** La vida y la historia previa de la chica
**** La vida y el entorno del chico
**** Como reacciona la familia
**** La actuacion de la abogada 
