* Notas sobre instalacion de ubuntu-budgie
** no lectura de usb
se soluciono solo cuando hacemos sudo apt update.
debe ser algo desfasado, pero se soluciona solo.
** mala experiencia con volumen encriptado en esta notebook
no arrancaba sola, necesitaba un control/alt/delete lo cual me parecia
un poco inseguro pq le podia hacer mal al hardware a la larga
tampoco fue bueno encriptar la carpeta personal, pq tiraba errores en
el arranca y lo enlentecia demas.
** para que tome la cuenta de google
hay que autorizar desde google el uso de software de terceros, y eso
permitira sincronizar calendarios y demas.

** para que no se resetee las X y se pierda todo con C-Alt-Retroceso
encima que es parecido a C-Shift-Retroceso que se usa mucho en Emacs
 en /etc/X11/xorg.config se pone:
 #+BEGIN_EXAMPLE
 Section "ServerFlags"
 Option "DontZap"  "yes"
 EndSection
 #+END_EXAMPLE
y eso deshabilita el zap

** para ver fecha con la hora en la barra del panel
en un terminal
#+BEGIN_EXAMPLE
gsettings set org.gnome.desktop.interface clock-show-date true
#+END_EXAMPLE

* Notas sobre lubuntu
agregar a panel "agente distribucion de teclado"
configurar deseleccionar Mantener las distribuciones del sistema
agregar la que falta ya sea latam o us
agregar monitor del sistema

* Antes que nada instalar con sudo apt install ...
1. emacs
2. git
3. firefox
4. vim-gtk
5. xclip
6. zathura
** syncronizar marcadores con firefox hfj024/ataraxia76
** crear clave ssh con gitlab para hacer el git clone sin contraseña


* Emacs
copiar .emacs desde ../orblok
M-x package-refresh-contens

** lo unico que falta instalar
con Mx package-install
1. org-bullets
2. ido-vertical-mode
3. smartparents
4. auto-complete

** ColorScheme usado: leuven
que se instala desde Mx list-packages y ahi lo elijo e instalo y luego
para que los colorscheme queden pongo save colorscheme.

** arregle la persistencia de la sesion anterior y de los archivos recientes
#+BEGIN_EXAMPLE
(desktop-save-mode 1)
(recentf-mode 1)
(setq recentf-max-menu-items 25)
#+END_EXAMPLE

** ag
*** instalar silver searcher 
#+BEGIN_EXAMPLE
sudo apt install silversearcher-ag
#+END_EXAMPLE
*** luego instalar ag
Mx package-install ag
** yasnippets
instalar de list-packages
luego agregar a .emacs
#+BEGIN_EXAMPLE
(add-to-list 'load-path
	     "~/.emacs.d/plugins/yasnippet")
(require 'yasnippet)
(yas-global-mode 1)
#+END_EXAMPLE

Los snippets residen en ~/.emacs.d/snippets/prog-mode/
y tengo un git en ~/.emacs.d/snippets

* instalacion de TCL
1. emacs por supuesto (no se si hace falta vim-gtk)
2. sqlite3 libsqlite3-tcl
3. tklib bwidget libtk-img tcllib
4. tk8.6-dev tcl8.6-dev
5. git

** instalar itcl /itk de la pagina
Nueva informacion: Bajar el itk4.0.4 [[https://sourceforge.net/projects/incrtcl/files/latest/download?source%3Dtyp_redirect][itk apropiado (No el 4.1.0 o
nuevo)]]
Para editar buscar "common install locations" es mas facil y alli
editamos tres veces y ponemos la ruta /usr/lib/tk8.6


./configure
make all
make test
sudo make install

editar el configure de itk y poner la ruta del /usr/lib/tk8.6/

buscar 
 # check in a few common install locations
#+BEGIN_EXAMPLE
 # check in a few common install locations
	    if test x"${ac_cv_c_tclconfig}" = x ; then
		for i in `ls -d ${libdir} 2>/dev/null` \
			`ls -d ${exec_prefix}/lib 2>/dev/null` \
			`ls -d ${prefix}/lib 2>/dev/null` \
			`ls -d /usr/local/lib 2>/dev/null` \
			`ls -d /usr/contrib/lib 2>/dev/null` \
			`ls -d /usr/lib 2>/dev/null` \
			`ls -d /usr/lib64 2>/dev/null` \
			`ls -d /usr/lib/tcl8.6 2>/dev/null` \
2497                `ls -d /usr/lib/tcl8.5 2>/dev/null` \
			`ls -d /usr/lib/tk8.6 2>/dev/null` \   <============ agregado por mi!!!!!!!!!!!!! ojo incluye tambien la barra invertida
#+END_EXAMPLE
tambien en linea 3584 
en ambas lineas hay que hacer el agregado en 2497 y 3584 de `ls -d /usr/lib/tk8.6 2>/dev/null` \
** pdf4tcl/tablelist
ultimo tablelist de nemethi

ambos a /usr/share/tcltk/

* instalacion de python
** instalar con apt python3-tk y python3-pip
** instalar modulos con pip3 install modulo
1. dateutils
2. fastnumbers
3. fpdf
4. Pmw
5. pyperclip
6. 

** poner las fuentes DejaVu / DejaVuBold en pyrx

** editar .bashrc
#+BEGIN_EXAMPLE
alias cd..='cd ..'
alias q='exit'
xmodmap ~/.Xmodmap
#+END_EXAMPLE
* instalacion de mu4e
** instalar offineimap con apt
 luego poner .offlineimaprc
#+BEGIN_EXAMPLE
[general]
# List of accounts to be synced, separated by a comma.
accounts = main

[Account main]
# Identifier for the local repository; e.g. the maildir to be synced via IMAP.
localrepository = main-local
# Identifier for the remote repository; i.e. the actual IMAP, usually non-local.
remoterepository = main-remote

[Repository main-local]
# OfflineIMAP supports Maildir, GmailMaildir, and IMAP for local repositories.
type = Maildir
# Where should the mail be placed?
localfolders = ~/Maildir

[Repository main-remote]
type = Gmail
remoteuser = romitexcba@gmail.com
remotepass = ataH3161.
folderfilter = lambda foldername: foldername not in ['[Gmail]/All Mail']
# Necessary as of OfflineIMAP 6.5.4
sslcacertfile = /etc/ssl/certs/ca-certificates.crt

#+END_EXAMPLE
** hacer mu index en Maildir para poder hacer un mu find 
** instalar mu4e de apt
** hacer mkdir dentro de Maildir de las carpetas que emacs pide
