* Justificacion del proyecto
[2016-09-21 mié] Aparte de formar parte de mi re-aprendizaje , el cual
es continuamente reforzado y complementado, creo que el proyecto se
autojustifica suficientemente. 
[2016-09-26 lun] Me resuenan las palabras de un programador que lei
casualmente donde decia que su trabajo habia sido facilitarle la vida
a los demas, y con emacs se facilitaba un poco la vida el mismo. Y me
quede con eso de que el software o la programacion como yo le digo
realmente te facilita la vida pq las cosas que haces con ella
realmente repercuten en el dia a dia. Ya sea con las tareas
repetitivas como en el ser mas productivo y ganar mas.

** Objetivos del proyecto
*** Manejo mas rapido y ergonomico de las funciones comunes
Hay funciones comunes y repetitivas que las tenemos que seguir haciendo sea
cual sea el camino que tomemos.
Por ejemplo:
- pasar ventas, pasar pagos, y gestionar los clientes.
- emision de listados y planos para cobradores
en ese sentido se mejoro muchisimo, ahora emito los listados muy rapidamente y 
gestiono todo mucho mas rapido.
La idea seria hacer extensiva toda esa operatoria a todo el negocio en todas sus
partes. Una vez programado y mantenido el sistema va a dar su fruto

Ya se ve la mejora en los tiempos de oficina y la calidad de la info y eso que esta 
en pañales
* Desarrollo del proyecto
** Ideas flotantes 
*** DONE Backup y subido a nube automatico 
CLOSED: [2016-09-22 jue 18:09]
mediante la interfase dropbox con python y backup en hot con sqlite
y tambien con el manejo de tar que hace python automaticamente
*** DONE Pasado de novedades desde la venta (fichitas)

** TabFechar
*** Muchas de las cosas implementadas serviran en otros modulos
1. cuenta y cuotas coloreadas
2. uso de checkbuttons
*** En el camino esto estoy haciendo
**** DONE [#A] hacer los checkbuttons de fechas preestablecidas
<2016-09-21 mié>
Facilitara mucho el fechamiento
**** Visualizacion de la planilla tal cual la estoy pasando
para no perder tiempo con los casos en los cuales no hay nada que hacer
**** cancelados (ya hechos)
**** pagados y cuyo pmovto automatico esta bien
**** Posiblemente achicar abajo aprovechando el sistema colores
o sea ahorrando las columnas num cuenta para poner cuotas debidas y cuotas
pagadas en el mismo sitio lado a lado y dejar mas amplitud a la "planilla"
mas ancha??
**** Gran caveat por resolver: el highlightBackground del tablelist
pq no encuentro color para hacerlo. Sin color como esta ahora confunde
quiza un color lightyellow pueda ser lo mejor. Y que la selectividad se
acentue con el bold 
*** Cosas sufridas y dejadas 
**** no pude hacer que se resalte el campo pmovto cuando este mal
ahi renegue con un error de sintaxis de sqlite date '+ 15 dias' y 
lo mismo no puedo resolverlo, pero lo abandono pq creo que no me 
sirve pq complica el proceso, me inclino por agrandar un poco el sitio
No perder de vista que es una tab para fechar y nada mas que para eso
*** Ideas a incorporar 
**** desagregado de campo nombre en apellido y nombre
**** comentarios en tabla aparte
**** intimaciones en tabla aparte 
**** acceso directo a modificadores de calle,num,zona
     SCHEDULED: <2016-10-02 dom>
     subtab para editar calle/barrio/zona al estilo del que ya tengo o
     sea la tabla entera editable, pq moverse en dichas tablas es
     bastante rapido y de paso permite ver el contexto. 
**** DONE botones de fechamiento automatizado
**** seguimiento de uso o tratamiento de los estados cargados
*** Tabla de acciones y sus correlatos
| subirseven     | proceso externo seven                      |    |
| intimar        | proceso externo intimaciones               |    |
| novendermas    | trigger a nivel tabla ponga incobrable     |    |
| llamar         | generacion de listado pendientes           |    |
| monitorear     | resaltado en planilla impresas             |    |
| espera evento  | campo evento -->generacion listado eventos |    |
| quiere comprar | generacion de listado clientes pendientes  |    |
| mudo           | cambio en la zona                          |    |
|                |                                            | sa |
|                |                                            |    |
  * Objetivos de implementacion
** TabFechar
Este tab es el mas importante del CMR Cobranzas pq alli se cargaran
todas las novedades de los clientes.
* Ideas prospectivas proyecto
** Generales
*** Impresion
Dentro de unas opciones generales del proyecto arriba.
**** poner opcion a windows
**** poner una variable impresora arriba para poner el nombre de la impresora actual
**** poner el navegador pdf por defecto arriba tambien como variable
** Modulo documentos
   DEADLINE: <2016-10-08 sáb>
una tab aparte para todo el manejo de documentos
Pienso que esta mal ponerlo como un checkbutton en fechar pq no se
sabe cual es el doc que el cliente quiere.
Se abriria una tab aparte y en ella se buscaria el cliente (salvo que 
desde fechar te la abra buscada)
Alli tendriamos que tener un sistema de busqueda de clientes (muy
similar en todos lados como en el F13) o sea full text search y alli
desplegado las cuentas cuyos documentos podrian quererse y alli si con
un doble-click y/o con una letra se toggearia entre doc a traer o no
traer, cuyo campo logico debe residir en la tabla ventas.
Y abajo un tbl general de documentos/pedidos procesados. (boton ver
todos) boton ver faltantes boton ver no retirados
alli desplegaria un tbl cuya tabla base seria adhoc y tendria los
campos idvta/fechapedido/fechatraido/fechadevuelto/quienlodevolvio/
comentarios.
Y se generaria un pdf con un listado de doc a traer con sus datos y
con los doc traidos se actualizaria el tbls idem cuando uno le
entregue a algun cobrador para que lo devuelva
** Modulo intimaciones
*** indicar en el tbs de fichas seleccionadas las fichas intimables
ya que la decision de intimar se toma cuando uno fecha y lo pone alli,
cuando seleccionamos la zona los reg intimables se resaltan diferentes
y se agregara un boton alli que imprima las intimaciones.
*** registro de intimaciones 
    DEADLINE: <2016-10-01 sáb>
tabla base adhoc con campos idcliente/fecha/tipo
intimacion/comentarios
No descarto que tenga que usar notebook dentro de los tabs p.e para
poder mostrar las tbls que quiero mostrar como comentarios o
intimaciones o visitas que quiero manejar en tablas aparte, salvo que
use el mismo tbls con botones de llenado. p.e. en principio mostrar
las visitas y con un boton ver las intimaciones o comentarios.
Eso achicaria los campos textuales y quizas podemos poner entrys.
** Modulo seven
El modulo seven tiene tbls que muestran los que estan en capilla y
permite procesar los que queremos enviar.
tambien debe mostrar los que estan ya en el seven.
** Tab busqueda padron
** Linkeado de parentescos en la base de datos.
** Estudio demografico sobre la clientela
al menos los basicos, tantos hombres, tantas mujeres de tales edades y
su correlacion con la compra/pago.
Y tambien un estudio de la base de datos respecto a la cantidad de
compra y tipo de articulos comprados
** agregar campo en clientes para poner la lectura de seven cuando se hace
** que en el nuevo F13 se pueda buscar por telefono en forma autonoma
** DONE Interface de actualizado de datos provenientes de la venta (fichitas)
* Reniegues varios
** funcion date(ultpago,'+ 15 days')
[2016-09-21 mié]
esta mal!!! es +15 days o sea sin espacio entre el + y el numero
** error tonto en la funcion backup
[2016-09-22 jue]
todo funciona perfecto hasta que al final quiero re-conectar
pq comienzo cerrando la con.close() para evitar errores de base de
datos y luego de hacer el backup quiero conectar de nuevo y pongo
con=conectar(db)
y me dice que la variable local con la referencio antes de su definicion 
en la sentencia con.close()
Y no entiendo nada. Busque la forma hasta dar que el error es que si 
dentro del proc por mas que con sea un nombre global, en alguna parte
de la funcion la asigno como hago con con= conectar(db) el nombre con
pasa a ser local y mas arriba a estar referenciado antes de su asignacion
borrando la "reconexion" todo funciona bien.
Pero da gusto haber encontrado el error.
** imprimir directo con lpr
usando subprocess ya sea Popen o call me daba errores por archivo o directorio
desconocido. Y sabia que era por el parseo de la opcion o sea no solo tenia
el comando lpr y el file sino la opcion.
Todo se solucionaria si el sistema CUPs me tomara la impresora como default. 
Y ahi estaba leyendo. [[https://docs.oracle.com/cd/E23824_01/html/821-1451/gllgm.html][Como administrar CUPS desde la linea de comando]]
cuando el comando de verificacion de la impresora default me dio
$ lpstat -d
destino predeterminado del sistema: Brother_HL-1200_series
O sea que ya la tenia seteada como default.
Y el cambio se vio en que imprimiendo desde zathura ya me aparecia
seteada como default
Y ese seteo lo hice indirectamente en la pagina de control de cups
[[http://localhost:631/printers/][CUPS]] en la parte Administracion, Set as Server Default, que aunque me
dio supuestamente un error la debe haber seteado igual.
En resumen pongo 
subprocess.call(["lpr","file.pdf"]) y listo.
Tengo la impresion directa, que para algunos casos es muy ergonomica y
segura, en especial cuando se imprime una sola hoja.

** poner en forma ordenada con label y entrys muchos campos
es cumbersome, y painfull. Lo resolvi en parte con un tbls con altura 1, y
selecttype='cell', muy bonito y practico, ahora abria que hacerlo editable, lo
cual no es gran dificultad.
se podria poner calle/num/barrio/zona aparte en una linea directa, ver. 

** scrollwindows y scrolledframe

* Caveats y Limites
** TabFichas
*** Resumen funciona hasta un maximo de 88 fichas 
** TabFechar
*** Ubicacion de cuenta en tbs cuentas con raton
    DEADLINE: <2016-09-30 vie>
 En el tbls de cuentas del recorrido, se actuliza automaticamente
a medida que pasamos de registro en registro <<TablelistSelect>>
pero cuando uno apunta con el raton, puede querer que se actualice
pero no lo hace. Es como si el primer puntazo seleccionara el registro
y el segundo lo disparara.
O sea que el comportamiento seria como un dobleclick.
Esto tendria que estar tambien en grandes reniegues. Le dedique casi una
hora o mas el [2016-09-24 sáb] y no obtuve resultado. No hay forma que
un simple click sobre el body del tablelist te de la row que
apuntaste.
Incluso usando el atributo y del evento y la funcion containing(y) te
entrega un posible valor pero puede dar error si le apuntas al borde
de la fila, porque en si son dibujos de filas en un text, no son filas
verdaderas.
No me queda otra solucion que usar el doble-click o bien seleccionar
con el teclado
* Bugs
*** Bug Bracamonte cta 40000

  la cuenta 40000 siempre la uso para pruebas y veia que funcionaba todo en el tabFechar
  menos el llenado del tbcli. raro.
  Analizando los datos raw del cliente vi que en el comentario tenia muchos \n\n\n
  y cuando los saque estuvo todo bien
  Lo que habria que ver es si hay otros casos, y estar prevenido.

  Ojo que trabajando sobre el levantado y el guardado de los campos text veo
  que la visualizacion del caso 40000 se distorsiona pq no se maneja los wrap
  en tbls.

  solucione mediante poner ancho fijo a las columnas y wrap=0 (explicito pq es default)
  for ct in campotexts:
              tbcli.columnconfigure(ct,maxwidth=30,wrap=0)
  pero principalmente en el guardado como es un get del texto viene con saltos de linea
  y eso te rompe el esquema

                  tx.get(1.0,END).strip()
  el metodo strip() de un str le saca todos los espacios y lo deja limpito
  ideal para construir stm limpiamente.

*** Bug tbls.insert en oficina
aca funcionaba ok el tbls con insert y alla no 
primero pense en versiones de tablelist pero actualice y nada
y al final en la parte del insert puse tuple
Es raro pero eso hizo que funcionara alla, pero aca no le afectaba
Pero como son dos SO distintos y puede que haya distintas versiones de tcl


* Comentarios al desarrollo
** Proceso quiere comprar
[2016-10-05 mié] 
Tengo un campo quierecomprar en clientes que sirve de control para con
un bind a un checkbutton saber en todo momento que ese cliente activo
el pedido.
Pero la clave esta en la tabla quequierecomprar, donde cuando activo
un pedido ingreso idcliente, fecha y articulo si es que lo dijo.
Es de esta tabla de donde saldra la guia para emitir un listado de
pendientes tanto visual como luego impreso.

Ese query lo hago con la fecha-pedido vs fecha-ultimacompra. O sea
listo todos los pedidos que tienen fecha posterior a la ultimacompra.
Entonces no cierro la row del pedido cuando el cliente compra, pq no
hace falta, pq es un sistema de pedidos informales, o sea avisos de
visita del vendedor, y se supone que si el cliente compro con
posterioridad al pedido ese pedido quedo satisfecho.

Mediante un trigger muy simple cuando se modifica la fecha ultcompra
en la tabla clientes (o sea cuando compra) saco el flag quierecomprar
y eso sirve para que no se active el checkbutton.

*** Caveats
- Era necesario llamar quequierecomprar a la tabla, no podia ser pedidos
- Se puede pensar en cerrar tambien por trigger el registro en la
  tabla quequierecomprar cuando el cliente compra. ¿Sirve para algo?

** Proceso seven
[2016-10-05 mié]
El proceso programado hoy tiene que ver con el marcado manual de gente
a subir al seven.
Luego habria que ver como seguimos para atras, si mediante la
reactivacion de las cuentas a nivel cobrador-intimacion y seguir con
el proceso manual.
Quedaria aparte el tema de los mudados que tendria que subirlos
automaticamente.
Eso podria hacerlo con un update clientes set subirseven=1 where zona=
'-mudados recientes'.

Una vez marcados con el flag subirseven, saco el listado con el select
subirseven=1 and sev=0 o sea los que no estan en el seven, y le
agregue por las dudas deuda>0.

Una vez emitido y controlado el archivo csv se procede a:
- desflagear el campo subirseven=0
- flaguear con sev=1
- poner el fecha de alta
- generar un registro en la tabla seven donde ponemos
  - idcliente
  - codigo
  - fecha


* Next Actions							       :next:
** DONE [#A] Listado impreso de gente que quiere ser visitada
** TODO [#A] Proceso de Intimaciones
** TODO Proceso de documentos

* Mejoras varias
** Adaptacion para windows
*** editor recomendado para windows
scite liviano sin necesidad de instalacion y con F5 compila y muestra errores
*** Modulos que me pidio una instalacion limpia en python
  | dateutils   | pip | ojo q se llama dateutils y me pide dateutil |
  | fastnumbers | exe | bajarlo de pypi                             |
  | winshell    | pip |                                             |
  | fpdf        | pip |                                             |
  | win32api    | exe | bajarlo de sourceforge - ojo version 3.4    |
*** Modulos tcl que me pidio
  | Bwidget   | use el de tcl aunque es dificil de encontrar  |
  | tablelist | baje de nemethi pq no lo encontre             |
  | sqlite3   | necesario para fts (ver solucion en cuaderno) |
  |           |                                               |
*** algunos reniegues de instalacion en windows
generalmente hay que poner el package que necesitamos dentro del subdirectorio tcl de python
en especial pide bwidget y tablelist, porque son ambos wrappers que funcionan en python con su
correlato en tcl y por mas que esten instalados en tcl hay que ponerlos en python. (Posiblemente
eso se arregle con un tema de path, pero hay que meterse en windows)
*** instalacion de modulos en windows
**** python -m pip install modulo
**** Pero hay modulos que no se instalan en windows
en ese caso tratar de bajar el ejecutable de pypi y ejecutarlo
Asi instale fastnumbers sino no se podia.
*** controlo el proceso mediante sys.platform
eso me permite el swich entre linux y las que no lo son
*** determino el Desktop mediante winshell
se importa facil con pip
winshell.folder("Desktop") te entrega el desktop
luego con un os.join lo armo suponiendo un directorio standard en el desktop
*** hago un proceso de vision de pdf generico sin importar lo que tiene instalado
mediante import win32api (hay que bajar la version para python3.4 de sourceforge)
win32api.ShellExecute (
  0,
  "print",
  filename,
  "",
  "",
  0)
Son 6 argumentos, el primero y el ultimo 0, los dos anteultimos "".
Poner el filename que queremos y las opciones son "print" para imprimir directo y
"open" para abrir el programa determinado de pdf.

