Arreglos dpto post-transcion
* generales
** destruir recibos
todos antiguos y nuevos
** reducir documentos
solo tendria que destinar un estante a documentos y si es posible el
dia de ma単ana llevarlos al marques donde en la cochera tendria que
tener una estanteria metalica en la cochera con todos los documentos.
** reducir espacio en general en placard
en todas las cajas, en la ropa, en los trastos. Aplicar el minimalismo
mas drastico. 
** limpiar arriba alacena para que no se peguen los frascos
* problema filtraciones
ya selle la perdida de la pileta que me molestaba a mi y elimine
posible implicaciones en el tema.
** averiguar con la portera actuaciones anteriores quinto piso
** averiguar con Simon si lo llamaron y tratar de ver el dpto
** llamar a Goio que venga
* tema cucarachas
** tirar veneno atras cocina y costado cocina para que no se vayan alli
** ir sacando elementos utiles de limpieza y pasandolos al ba単o provisoriamente
dentro del fuenton para que no se asienten de veneno
** sacar para tirar cosas que no voy a usar mas
ej lucuadora, tarros, botellas, etc. Incluso tirar el estante que esta
torcido y roto, comprar bolsas compactadoras y con dos bolsas lo saco
al frente. Comprarse guantes nuevos. 
** limpiar la barrosidad que queda y tirar veneno en todo el interior del mueble vacio
* arreglos pendientes
** cuerito canilla cocina 
* ba単o
** colocar cortina ba単o
* lavado
** tender 80cm de pared
** traer lavarropas
primero chequear que el desague funciona
luego chequear que el lavarropas funciona alla
luego traer
* living
** almohadones para el sillon
* equipamiento renovacion
** ir cambiando platos/utensilios en general
** ver los frascos que necesitamos para lo que usamos y tenerlos exactos.
