Arreglos dpto post-transcion
* generales
** destruir recibos
todos antiguos y nuevos
** reducir documentos
solo tendria que destinar un estante a documentos y si es posible el
dia de ma単ana llevarlos al marques donde en la cochera tendria que
tener una estanteria metalica en la cochera con todos los documentos.
** reducir espacio en general en placard
en todas las cajas, en la ropa, en los trastos. Aplicar el minimalismo
mas drastico. 
** limpiar arriba alacena para que no se peguen los frascos
* problema filtraciones
ya selle la perdida de la pileta que me molestaba a mi y elimine
posible implicaciones en el tema.
** averiguar con la portera actuaciones anteriores quinto piso
** averiguar con Simon si lo llamaron y tratar de ver el dpto
** llamar a Goio que venga
* tema cucarachas
** tirar veneno atras cocina y costado cocina para que no se vayan alli
** ir sacando elementos utiles de limpieza y pasandolos al ba単o provisoriamente
dentro del fuenton para que no se asienten de veneno
** sacar para tirar cosas que no voy a usar mas
ej lucuadora, tarros, botellas, etc. Incluso tirar el estante que esta
torcido y roto, comprar bolsas compactadoras y con dos bolsas lo saco
al frente. Comprarse guantes nuevos. 
** limpiar la barrosidad que queda y tirar veneno en todo el interior del mueble vacio
** entro una cuca por la ventana en el dormi
pero pienso que era por el viento posiblemente bajaba por un cable y
se avento adentro, creo que el edificio debe tener una buena cantidad
* arreglos pendientes
** cuerito canilla cocina 
* ba単o
** colocar cortina ba単o
* lavado
** tender 80cm de pared
** traer lavarropas
primero chequear que el desague funciona
luego chequear que el lavarropas funciona alla
luego traer
* living
** almohadones para el sillon
* equipamiento renovacion
** ir cambiando platos/utensilios en general
** ver los frascos que necesitamos para lo que usamos y tenerlos exactos.
* dormitorio -luego del giro
** DONE pasar enchufes de cabezera
- State "DONE"       from              [2019-02-25 lun 16:12]
** DONE poner cortina
- State "DONE"       from              [2019-02-25 lun 21:24]
** buscar bidon 6lts
** DONE encerar
- State "DONE"       from              [2019-02-25 lun 21:24]
** poner topetina
** comprar vinilo para pared
me parece muy funcional el tener un vinilo en esa pared, le veo muchas
aplicaciones, quizas no termine haciendo nada, pero a nivel fijacional
el hacer un cuadro mental de algo y verlo ahi hasta grabarlo es muy
groso, luego foto y comenzar de nuevo.
