  #+STARTUP: indent
* Org-mode							   :dpto:org:
** Historia:
Escuche la conferencia del creador de org-mode. Muy interesante
** bugs
*** Me borra escritos que ya hice. No creo que sea fossil 
** Uso
*** M-RET estando al final de un outline te abre otro al mismo nivel
*** Tab alli lo promote/demote ciclicamente a los niveles que existen
*** M-up|down sube/baja el nodo 
*** M-left|right lo promote/demote no limitado a los niveles que existen 
*** Listas ordenadas y no ordenadas se hacen con -,1.,1) y se mueven igual
*** [2016-09-21 mié] C-c . inserta una fecha del calendario
*** SM-RET inserta un TODO
*** C-c C-l inserta un link
*** C-c C-| formatea una tabla con los datos tabulares insertados en la region
*** Links *** :							  :manual:ms:
**** ((link) (descripcion)) o ((link)) en corchetes!!
***** Para Editar un link Cc-Cl en el link o borrar el ultimo corchete invisible
**** links internos ((Plan de estudios)) [[Plan de Estudios]] solo para outlines
**** Autocomplecion de lugares internos * y M-Tab [[*Acomodo del dpto]]
     Ojo funciona con [[* y M-Tab evitar que emacs te cierre los
     parentesis sino te salta directo un link.
**** Links externos
| file:fichaje.py::252 | [[file:~/py1local/fichaje.py::252]] | ir a filetext linea especifica |
| file:todo.org        | [[file:todo.org][TODO.org]]                        | otro org file                  |
| file:todo.org::DONE  | [[file:todo.org::Hacer][Hacer]]                           | otro org file search word      |
|                      |                                 |                                |
**** [[ManualesKapeluz]] Apunta a una etiqueta <<etiqueta>>
*** Tags							  :ms:manual:
*** 
**** Un tag es una clave enclosada en dos puntos
**** poniendo los primeros dos puntos y M-tab hay autocomplecion 
**** o con Cc-Cc en un headline se puede poner un tag o Cc-Cq en cualquier parte
**** Cu CcCq realinea los tags a la columna 77
**** Al poner #+TAGS: en la primer linea y hacer CcCc no cargo tags fijos								       
	Entonces habilito a hacer un listado dinamico de tags con los usados en el archivo.
	Se podria tambien hacer:
	#+TAGS: tag1(a) tag2(b) tag3(c) y siempre cargar con CcCc o 
	#+TAGS: {tag1(a) tag2(b)} tag3(c) y crear un grupo alternativo o sea tag1 o tag2 en ese caso 
**** Search tags:
***** Cc / m permite busqueda por tags tag1+tag2 tag1-tag2 tag1|tag2
***** Cc \ idem anterior pero va directo sin la m
*** checkbox
    toda lista puede ser usada con checkbox. Ojo respetar espacios sino no funciona
    - [ ] Comienzo 
    Si ponemos un checkbox en un item jerarquico superior y dentro de su checkbox
    ponemos [/] o [%] llevara la cuenta de la cantidad o porc de subitems checkados
    Con el mouse se pueden checkar o descheckar los items.

** Caracteristicas deseadas
*** poder poner un limite a la linea con un autowrap
*** Comandos para org-mode: Manejo de fechas
| C-C .        | inserta fecha del calendario                  |
|              | sobre una fecha la modifica                   |
|              | dos veces pone un rango                       |
| C-C !        | ingresa una fecha inactiva o sea no agendable |
| S-left/right | Cambia la fecha adelante/atras en un dias     |
| S- up/down   | Cambia la parte de  la fecha arriba o abajo   |
| C-C- C-D     | ingresa DEADLINE                              |
| C-C- C-S     | ingresa SCHEDULED                             |
*** [2016-09-24 sáb] soporte para uso de mouse
** DONE anexar packages
   SCHEDULED: <2016-09-26 lun>
*** tomatinho - pomodoro [[https://github.com/konr/tomatinho][descargar]]
Permite llevar el control de lo realmente producido
| <Enter>   | Forgoes the current pomodoro or leaves a break. |
| S-<Enter> | Deliberately pauses.                            |
| R         | Resets the timer.                               |
| <Tab>     | Toggles between display modes.                  |
| q         | Kills the buffer.                               |
| Q         | Turns off Tomatinho.                            |
*** org-mouse
genial manejo de org con el raton que en cierta forma ayuda un monton
pero no debe hacer que uno olvide o desaprenda lo basico para llegar a
mastering org
*** imenu
te agrega un menu con las definiciones para saltar directamente, o sea
lo que seria el minimap de funciones pero mas eficiente. Muy
interesante para lib.py p.e.[[https://www.emacswiki.org/emacs/ImenuMode#toc15][wiki sobre imenus]]
*** org-board
es un sistema de guardado de paginas con wget y de paso te queda el registro.[[https://github.com/scallywag/org-board][org-board github]]
*** helm in deep [[http://tuhdo.github.io/helm-intro.html][helm descripcion uso]]
*** org-wiki [[https://github.com/caiorss/org-wiki][wiki]]
** recursos en la web
*** [[http://tuhdo.github.io/index.html][introduccion lisp]]
*** [[http://jr0cket.co.uk/2016/09/Kanban-board-Emacs-Org-mode-to-get-work-done.html][kanban meet org]]
*** [[https://github.com/kelvinh/org-page][interesante blog hecho con org y publicado en git]]
*** [[http://orgmode.org/worg/org-blog-wiki.html][listado general de recursos de blog y wiki]]
** tables
- Cc abre un menu sobre tablas
- las tablas se crean con | y se van alineando solas
- tambien se puede sobre un csv resaltado llamar Cc |

| / | <>             | <>                      |
|   | Alt-RET        | para una nueva fila     |
|   | Alt-left-right | para mover las columnas |
|   | Alt-up-down    | para mover las filas    |
|---+----------------+-------------------------|

Poner un encabezado con / <> <> y una col vacia a la izquierda produce 
que se dibujen las lineas verticales de columna

| / | <>              | <>                       |
|   | Alt-Shift-left  | borra la columna         |
|   | Alt-Shift-right | crea una columna         |
|   | Alt-Shift-up    | borra la linea de arriba |
|   | Alt-Shift-down  | crea una fila arriba     |
|   | C-c RET         | crea una linea debajo    |
|---+-----------------+--------------------------|

Hay tambien algunos cumbersome pasos para mejorar tablas
que creo que tienen sentido si luego vamos a exportar

|   |  N | N^2 | N^3 | N^4 | sqrt(n) | sqrt[4](N) |
|---+----+-----+-----+-----+---------+------------|
| / | <> |   < |     |   > |       < |          > |
| # |  1 |   1 |   1 |   1 |       1 |          1 |
| # |  2 |   4 |   8 |  16 |  1.4142 |     1.1892 |
| # |  3 |   9 |  27 |  81 |  1.7321 |     1.3161 |
|---+----+-----+-----+-----+---------+------------|

Este ejemplo lo hice yo:
|   |  N | N**2 | N**3 |
| / | <> |    < |    > |
| # |  1 |    1 |    1 |
| # |  2 |    4 |    8 |
| # |  3 |    9 |   27 |
|---+----+------+------|

[[http://orgmode.org/worg/org-tutorials/org-spreadsheet-intro.html][Para usar las tablas como hoja de calculo]]



* Temas aprendidos
** Fechas
   DEADLINE: 2016-10-10 lun>
   :PROPERTIES:
   :ID:       acde9cc4-aca3-4d55-ae92-499929dcf9ce
   :END:
Cuando hay que introducir una fecha y sale el calendario tambien hay
un prompt en el minibuffer. Alli se puede poner una fecha relativa
p.e.
+5d, +2w siempre relativo a hoy
++5d con doble signo si la queremos referenciar a la que esta
. pone el calendario a hoy

Tambien asume que pondremos una fecha a futuro, entonces solo un
numero pone esa fecha dentro del proximo mes.

Manejo basico del calendario
| S right/left   | un dia adelante o atras     |
| S up/down      | una semana adelante o atras |
| M-S-right/left | un mes adelante o atras     |
| M-v C-v        | 3 meses adelante o atras    |
| M-S- down/up   | un año adelante o atras     |
| .              | hoy                         |

Resumen de entradas permitidas en el minibuffer
| .      | hoy                               |
| +4d    | cuatro dias desde hoy             |
| ++5    | cinco dias desde la fecha default |
| +2w    | mas dos semanas                   |
| +2mon  | dos lunes desde aca               |
| -wed   | ultimo miercoles                  |
| 14     | el proximo dia 14                 |
| mon    | el proximo lunes                  |
| oct 12 | el proximo 12 de oct              |
|        |                                   |
** checkbox [2/2] [100%]
- [X] item 1
- [X] item 2
Se pone el checkbox en un item de lista
Si hacemos M-RET nos otorga otro item de lista, pero si hacemos
M-S-RET nos otorga otro chekbox

Poniendo la cockie [/] o [%] en un item superior se lleva la cuenta de los
check tildados en los items inferiores.
** Ciclo de listas
- 
- 
- 
Poniendo cualquier lista y luego haciendo S-left/right se cicla por distintos
formatos de lista 
+ 1) 1. - 

 
** Edicion de codigo
con <s y Tab obtenemos el siguiente esquema
#+BEGIN_SRC 

#+END_SRC
ese espacio permite insertar codigo.
al lado de begin_src ponemos python y adentro el codigo que se
formateara como habitualmente se hace.



* En que estoy usando orgmode actualmente
** [2016-10-07 vie] 
O bien en que le encuentro utilidad
*** Escritura de proyectos complejos
p.e. manual de usuario o diario de proyecto
*** Agenda de proximos pagos
ahi la veo interesante por lo sencillo y a la vez segura forma de 
poner todo junto y estar tranquilo.
*** Manejo de proyectos 
poner todo lo relativo a un proyecto en el mismo lugar y despachar
las next action etc.
*** Diario
Si podemos poner a punto el date-tree, seria ideal para organizar los
escritos pasados y futuros.

Es cierto que por ahi en el proceso de aprendizaje uno se traba y
pierde mucho tiempo, o se desanima, pero en realidad es algo
apasionante y que puede ser redituable a lo largo del tiempo como
todas las cosas.

** [2016-10-11 mar]
Lo encuentro extremadamente util para el brainstorming. En forma
parecida al manejo de los proyectos, donde se busca el estado de
mente-barrida. 
Hoy hice un bs con una seccion que tengo que programar que es bastante
compleja y al ir escribiendo rapido y en forma de outline las ideas
fluyen mas rapido y luego eso queda y se puede seguir trabajando sobre
eso en forma muy comoda y flexible. 
Como p.e. reacomodar los headlines, promote, demote, ocultar
desarrollos de la idea y focalizar sobre los encabezados. 
** [2016-10-17 lun]
*** Agenda-Calendario 
   Ahora veo muy util el escribir el diario y luego exportarlo con
   org-mobile y plasmarlo en el calendario del celu, pero ahi creo que
   falta un poco de orden para que tenga mas utilidad. Por eso estoy
   rehaciendo el archivo base.
*** Diario secuencial
    el dia se ordena muy bien y me permite eventualmente volcar todos
    los cuadernos en orden
*** temas sueltos que tienen entidad propia
    como los edu, incluso con algun formato de diario en ellos
    mismos.Como aca.
*** lo de los habitos estaria muy bueno
    por la filosofia de verificar el avance.


* tablas
** Lo mejor es escribir |campo|campo|campo|campo <Tab> y el encabezado se arma solo
** un guion inmediato a pipe |- produce luego de realinear una linea horizontal
o se puede hacer Cc-Cc para realinear en el momento
** Conviene moverse entre celdas con tab-Stab para que se asuma como celdas el contenido
y eso hace que sobreescribamos lo que hay

| t | t | t  |
| j | 5 | 99 |
| j | a | f  |
|   |   |    | 
** Convertir una region en tabla
t,j,k,l,m
3,2,3,2,2
Encerrar lo anterior en una region!!! y luego Cc | lo hace tabla
| t | j | k | l | m |
| 3 | 2 | 3 | 2 | 2 | 
Pero recordar... debe estar resaltado o sea en una region!!

| a | b |  c | d | e | f |
| 1 | 2 | 43 | 4 | 5 |   |

Puede ser csv o tab 

Sin region el comando Cc | crea una tabla vacia
|   |   |   |   |   |
|---+---+---+---+---|
|   |   |   |   |   |
5x2 default pero puede darse el tamaño que uno quiera
|   |   |   |   |   |   |   |   |   |   |
|---+---+---+---+---+---+---+---+---+---|
|   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |
** Sort table
   Cc ^  sort table numeric/alphabetic/time (tambien en reversa con
   las opciones en mayuscula)
   la columna usada para el sort es la active cuando llamamos el
   comando
** Agregar una linea horizontal
   Cc -
** Mover filas o columnas
   M-left-right mueve columnas
   M-up-down mueve filas
** Borrar o agregar filas o columnas
   M-S-left borra la columna actual
   M-S-right agrega una columna en la posicion actual
   M-S-up borra la fila actual
   M-S-down agrega una fila en la posicion actual
** sumar
   C-c + suma los items de la columna activa y C-y los pastea.
   O sea si estamos en una fila totalizadora hacemos C-c + y Cy y
   tenemos la suma puesta
|  a |  b |  c |  d |
|----+----+----+----|
|  2 |  7 |  8 |  9 |
|  9 |  9 |  9 |  9 |
|  9 |  9 |  9 | 78 |
|  0 |  8 |  9 |  7 |
|----+----+----+----|
| 20 | 33 | 18 | 18 |
|    |    |    |    |
|----+----+----+----|
#+TBLFM: @6$3=@5$3+@4$3::@6$4=vsum($3)
** copiado y llenado
   Con M-RET se va copiando e incrementando los valores en una
   columna.
   Numericamente con +1 y fechas tambien con +1, letras no.
   Util si la primera columna la queremos para numeracion.

|  a | b  | fechas           |
| 11 | a1 | [2016-10-11 mar] |
| 12 | a1 | [2016-10-12 mié] |
| 13 | a1 | [2016-10-13 jue] |
| 14 | a1 | [2016-10-14 vie] |
| 15 | a1 | [2016-10-15 sáb] |
| 16 | a1 | [2016-10-16 dom] |
| 17 | a1 | [2016-10-17 lun] |
| 18 | a1 | [2016-10-18 mar] |
| 19 | a1 | [2016-10-19 mié] |

** Hoja de calculo
*** Cc } turn on numeros de fila y columnas
*** cc ? sobre una celda te muestra en buffer la direccion
*** Formulas de toda la columna o toda la fila
Cuando introducimos una formula en una celda normalmente =vsum() etc
y aparece abajo la linea de formulas,con el lado izquierdo de la
ecuacion nombrando la direccion de la celda y la derecha la formula
dada.
Si en vez de una celda dejamos una fila o una columna la formula se
aplica a toda la fila.
Aca hice que la fila 11 sea una suma de las columnas en celdas de fila
2 a 9.

|  a |   b |  c |  d |  e |
|  1 |  12 |  3 |  5 |  0 |
|  2 |  13 |  4 |  6 |  1 |
|  3 |  14 |  5 |  7 |  2 |
|  4 |  15 |  6 |  8 |  3 |
|  5 |  16 |  7 |  9 |  4 |
|  6 |  17 |  8 | 10 |  5 |
|  7 |  18 |  9 | 11 |  6 |
|  8 |  19 | 10 | 12 |  7 |
|    |     |    |    |    |
|----+-----+----+----+----|
| 36 | 124 | 52 | 68 | 28 |
#+TBLFM: @11=vsum(@2..@9)

* habits
[2016-10-17 lun]
Todavia no puedo hacerlo funcionar y que se vea la cadena de
Seinfeld. 
Pienso que faltan un par de dias para que se vea.
[2016-10-18 mar]
bingo!!!. Lo hice funcionar. El error era que en vez de scheduled
ponia deadline.
Para hacer un habito:
1. hacer un TODO cualquiera
2. schedularlo con repeticion
3. ponerle propiedad (CcCxp) STYLE:habit
y listo, luego sale en la agenda.


* modulos a experimentar luego
** learn / drill 
al M-x customize-variable RET org-modules RET vi que hay un modulo de
learn con el algorritmo supermario. para ver 
ambos dan error, no andan. que bronca.
** search
necesito un search que funcione como ag al toque pero dentro de emacs,
esta el ag pero no se baja pq debe estar roto el enlace o algo.
Bastante bien funciona el agenda-s con regexp y palabras sueltas.
** browser interno a emacs
se puede navegar dentro de emacs como con el manual???

* seteos que logran efecto deseado
** (add-hook 'org-mode-hook 'turn-on-auto-fill
el bendito auto-fill en los escritos
** (global-set-key (kbd "C-}") 'org-agenda)
el keybind para abrir agenda
** (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
que funcionen los superbullets
**  '(org-deadline-warning-days 0)
seteado con customize-variable elimina el molesto aviso de los
 proximos deadline que te llenan la agenda.
**  '(org-habit-show-habits-only-for-today t)
idem anterior, como el habito es repetitivo, te aparece todos los
dias y no te permite apreciar la agenda 
** org indent
con   #+STARTUP: indent arriba he logrado una indentacion automatica
aunque diferente en lo hecho a partir de ese momento y lo que estaba
antes. La diferencia era causada porque uno habia cargado espacios
para simular la indentacion. Pero funciona perfecto automaticamente.
SE puede hacer a nivel archivo con el startup indent/noindent o
mediante el seteo:
 '(org-startup-indented t)) pero que advierte que es lento para
grandes archivos.
* TODO cosas pendientes [0%] 
- [ ] poner que la agenda se abra en dia
- 
