* sobre los esquemas
aca se trata de descubrir cuales son los esquemas mentales erroneos
que uno puede llegar a suscribir ya sea internamente o externamente
* esquemas detectados derribados o a derribar
** tomar medicamentos sirve 
te duele, toma medicamento, te sentis mal toma medicamento, no cagas
toma gotas, tenes resfrio toma medicamentos!!, tenes miedo toma
medicamentos, etc. una sociedad empastillada, y la mayoria de los
medicamentos no sirve.
** ante un dolor de cabeza hay que tomar analgesicos
es el esquema mas poderoso que sigo, el culpable haber llegado al
abuso cronico de analgesicos, o sea pretender seguir la vida "normal"
y "sin dolor ni molestias" tomando la pastillita y que esa pastillita
funciones y sea inocua (no tenga efectos secundarios, no cause
adiccion, no deje de funcionar un dia, no cause rebote, etc).
Hay subesquemas:
*** si no tomas el analgesico el dolor se hara mucho mayor
y asi se terminas tomando muchas veces al vicio
*** el analgesico menor no sirve pq al final te lleva al mayor
eso te lleva en algun punto a quedarte solo con el migral y a tomar
migral por un dolorcito de mierda y caer en el rebote.
** ante el sufrimiento del dolor hay que retirarse
o sea el esquema que el dolor es incapacitante, o sea que hay que
parar pq sino el dolor empeora, siempre he funcionado asi con ese
esquema, y asi he caido a la toma incluso preventiva de analgesicos,
pq temia que el dolor que no era tan importante lo fuera despues, y se
dan casos como el de esta tarde que escribo esto, hace unos 45 minutos
ya estaba para retirarme a reposar en situacion de N7, ya habia
intentado tareas (utiles me decia yo, limpiado superficialmente,
planchado dos camisas, escrito el post) y me dije NO!! voy a hacer
algo mas energico para que explote!! total no tengo compromiso alguno,
y me puse a limpiar la cocina, me puse con las hornallas, y me embale
cada vez mas, creo que en pocos minutos mientras estaba en actividad
la molestia cedio mucho, a pesar de que estuve y estoy escuchando
Bruckner al maximo, y me embale en una terrible tarea que hace 3 años
que evado que es limpiar la grasitud pegada arriba de la alacena, una
labor de locos considerada para mis fuerzas, y lo hice, al terminar y
cortar ahi, pense que casi el dolor habia desaparecido, aunque creo
que queda, pero estufefactamente compruebo que haciendo todo lo
contrario que uno pensaria obtenes otro resultado. 
Lo mismo pienso cosas que habra que analizar aparte o abrir otros
items como que pasara cuando ante dolores similares no tenga similares
tareas, o una peor, cuando habia entrevisto que pudiendo llegar a
controlar mis dolores y lograr una vida sin migrañas, ¿que iba a hacer
con mi vida? pq supongamos si se me iba el dolor ahora que hacia?, pq
no tenia "Nada que hacer" y ahi creo que di en el ojo medular de
esquema mas oculto de la migraña.
*** hijo de esquemas como pq la vida es tan desgraciada con uno.
porque no habria que aguantarse un dolor, caemos en la dependencia de
los farmacos pq nos vendieron la idea de que los dolores se suprimen
sin costo con una pastilla.
y caemos en esquemas de vida malos pq no hacemos actividad fisica
(algunos) y no hacen actividad mental (otros) por vagancia, no por
otra cosa, no logrando una vida equilibrada. 
** no se debe hacer cosas sin importancia
de nuevo mientras limpiaba salio el tema que hago limpiando una cocina
en plena tarde, como si esto fuera algo bajo, indigno de mi, o que yo
tendria que hacer cosas mas importantes en mi tiempo.
Mas alla del hecho de que creo que esa limpieza me llevo media hora
digamos, y es por unica vez, y me beneficia directamente, iba a
titular un post: Nunca descubri mas esquemas que derribar que
limpiando una alacena una tarde en mi casa. Y esto empalma con el
libro Focus, que cuando estamos agobiados, o sumidos en actividades
rutinarias o nos forzamos a pe.leer, videar, o trabajar pq pensamos
que son cosas "validas" perdemos la oportunidad de hacer las
CONEXIONES.
Y es interesante que el mix entre el libro Focus y el Esquemas se haya
logrado esta tarde asi, no olvidar la base de libro Migrañas... que lo
tengo en mi haber. O sea que no esta mal, que uno alterne actividades
donde el cerebro pueda asociar. y no caer en sopores. 
Por eso aunque se que no va a pasar (lo de la baja de fibertel) me
interesaria no tener a la mano esa cantidad de material sino buscarlo
yo, o sea volver a ponerme las series que quiero ver bajandolas yo.
Este esquema es pariente del esquema "Debes trabajar como loco para
tener exito" es cierto que muchos años (2003/2018) tuve jornadas de
8hs o mas muy rutinarias y muy preocupantes entonces poco o nada te
quedaba para la creatividad o para lo que a mi me gustaba, entonces el
tener que hacer "tareas" dentro de ese escaso "tiempo libre" era mal
visto. No olvidemos que en algunos momentos cai en compulsiones, como
en el 2005 cuando llegaba a pasar 6hs luego de oficina sentado en la
compu, solo pq la compu era nueva o pq tenia una banda ancha mas veloz
para el momento. 
Eso creo que ha cambiado ahora que las exigencias de la cantidad de
horas rutinarias ha cambiado y me da la oportunidad de ver las cosas
de otra forma.
** no tengo fuerza ni energia fisica
es un esquema que uno tiene tambien, y creo que es fruto tambien de la
comodidad, y no obstante uno puede ver que si quiere puede hacer las
cosas que no es fragil ni se quiebra.
** si me curo necesariamente debo socializar de determinada manera
no necesariamente, eso inhibe la curacion, pq el miedo a esa libertad
o a ese tiempo, puede jugar en contra a querer estar enfermo y
quedarse en cama doliente, por eso propongo hacer frente al dolor con
esquemas activos para acostumbrar a la mente y al cuerpo a la
actividad como mas normal, y aprovechar los momentos normales para
hacer actividades.
Quizas pueda dejar el asunto programacion para un futuro luego que me
haya curado, o bien, que sea una actividad que se haga unicamente en
la oficina. Y nunca mas una espada de damocles que sea mi karma.
Entonces mis pequeñas aficciones como la lectura, el aprendizaje, no
necesariamente deben ser hechos en grandes periodos de tiempo.
Con la netbook ubicada y prendida, se hace de a ratos. Y con el celu
se lee en cualquier lado y de a ratos tambien. O sea no da para nada
un perfil de vida "raton de biblioteca" sino que tendria que salirse mas.
** la unica mujer de mi vida debe ser ih
** es inseguro viajar de cualquier forma
** si vas a salir de viaje tenes que ir con TODOS eso incluye a IH
** idem dos esquemas anteriores con relacion a salir a algun lado
** las salidas tienen que tener un formato determinado sino no son salidas
** el fin del mundo va a venir pronto por eso no se puede tener metas
** ya soy demasiado viejo para lo que sea
** a cierta edad necesariamente te tienen que ocurrir ciertas enfermedades
