* 2019
** 2019-01 enero
*** [2019-01-02 mié]
Lo bueno es que hace como un mes que el consumo de clonazepan termino.
Digamos desde la consulta a Dastolfo. Ahora es facil olvidar los
hechos, pero pasamos distintas etapas, una rapida muy fugaz que fue la
que nos hizo pensar que habiamos encontrado la panacea, fue cuando
esos dos o tres dias aca tome los clonagil de la ih en dosis mayor y
me senti como en una nube de algodones, y luego cuando para dormir en
mi casa me clavaba uno o dos verdes de las mias. Luego empezo la etapa
dos la del abuso-dependencia, en la cual se tomaba a cualquier hora y
en cualquier circunstancia, y despues viene la fase tres que es cuando
a pesar de tomar sin restricciones, uno se siente cada vez peor y
empiezan a aparecer sintomas fisicos, que uno atribuye a la ansiedad
original, como taquicardias, temblores, mariposas de panza, vertigos,
tartamudeos, etc. Y uno tiende a pensar que cada vez esta mas mal del
terrible "mal original" y por lo tanto tiene que tomar mas medicacion.

Alli fue providencial la charla con Dastolfo pq me doy cuenta del
ciclo y veo que los males de la tercera etapa no los tenia antes de
empezar y que se fueron disparando a medida que fui tomando la
medicacion.
Que la solucion era dejar de tomarla.
Y asi lo hice. Salvo el dia del embargo que tome un par, o el dia que
tuve que llevarlos por la operacion del Fede, pero de ahi en mas nada.
Y duermo bien sin pastillas y estoy razonablemente bien.
*** [2019-01-04 vie]
hoy lo mas grande fue que hice el grafico deflactado de venta y vi la
curva real de decrecimiento patrimonial.
esa curva me da muchas enseNanzas.
la mas importante es que no se debe perder tiempo luego de un buen
year.
pq ahi es donde nos vamos irremediablemente para abajo.
**** programar en TCL
pienso que debo documentar todo e ir pasando en limpio todo lo caotico
escrito aqui y alla, y dejar un sistema que sirva para ponerse a
programar cuando haga falta pq cuando me pongo a programar me
encuentro siempre que no tengo lo que necesito.
*** [2019-01-06 dom]
hoy se terminaron las vacaciones, y a partir del mediodia comienzo a
trabajar, o sea que chau tranquilidad.
espero simplemente no caer en nerviosismo.
y en ese nerviosismo no caer a tomar clonazepan que ya vi que no
sirve.
por lo cual desde ya y antes de que comienze todo coloco bajo mi
responsabilidad el mantener la calma.
todo depende de como se lo mire.
Puedo hacer lo que yo quiera.
solo necesito mantenerme relajado. y mantener la mente clara en mis
ideas.
la idea de que hay que seguir trabajando, el saber cual es mi trabajo
este ano y todo lo que puedo llegar a hacer.
