* instalacion
** sincronizar marcadores firefox
cuenta hfj024@gmail.com / ataraxia76
** sincronizar cuenta mega.nz
cuenta hfj024@gmail.com ataH2132**/asam3161
** clonar orgblock de bitbucker
*** entrar en bitbucker 
hfj024@gmail.com - ataraxia76
clonar via http que es la opcion directa que te da, con password
ataraxia76

** crear clave ssh en gitlab segun instrucciones
** emacs
*** Nuevo Emacs
**** crear un ln -s a init.el de orgblok
ln -s ~/orgblok/init.el ~/.emacs.d/init.el
**** instalar font: Input font for Code
sudo apt install font-manager
bajar InputMono-Regular.ttf - doble click en la font y luego install
**** troubleshoting con error: Package ‘better-defaults-’ is unavailable
     cerrar y volver a abrir.
**** packages que instale a mano despues
***** emmet
***** js2
***** evil
*** copiar .emacs de orblok/
*** mx package-refresh-contens
*** mx package-install
**** org-bullets
**** ido-vertical-mode
**** smartparents
**** auto-complete
**** ag (instalar silversearcher con apt)
*** instalar org en su ultima version
usar package-list-packages
** neovim
*** instalar neovim 
*** ln -s a init.vim
mkdir .config/nvim
ln -s ~/orgblok/init.vim ~/.config/nvim/init.vim
*** instalar Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
*** instalar vim-Plug [por el momento no]
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
*** hacer PlugInstall
*** snap
    sudo apt update
    sudo apt install snapd
    sudo snap install core
    sudo snap install nvim --clasic
** hldedger
*** install hledger con apt
sudo apt install hledger hledger-ui hledger-web
*** ln -s ~/orgblok/.hledger.journal ~/.hledger.jounal
*** alias hl='hledger'
alias cj='hl r assets:caja' en .bashrc ambos
** gnome-calculator
   sudo apt install gnome-calculator
   atajo: XF86Calculator
   modo teclado
** tcl
*** en apt
sqlite3 libsqlite3-tcl tklib bwidget libtk-img tcllib
tk8.6-dev tcl8.6-dev tcl8.6-tdbc tcl8.6-tdbc-sqlite3 mysqltcl
*** en pacman
    sqlite3 sqlite3-tcl 
*** en AUR
    tklib (incluye tcllib y tk)
    tkimg
    bwidget
    pgtcl
*** copiar itcl/itk/tablelist/pdf4tcl 
**** ubuntu
 /usr/share/tcltk
**** manjaro
/usr/bin/tcl8.6/ tablelist y pdf4tcl
/usr/bin/ itcl4.1.1 e itk4.1.0

*** tclsh
instalar con apt tcl-tclreadline
copiar de ~/orgblok .tclshrc a ~
** python necesarios
*** libsqlite3-dev
** fl3 - flask
*** venv
  sudo apt install python3-venv
  python3 -m venv venv
  
  source venv/bin/activate
  eso produce que se comience a ver (venv) antes del prompt
  
  pip install -r requeriment.txt
** Visual Studio Code 
*** hacer que un file abra en tab nueva
    "workbench.editor.enablePreview": false
*** wordwrap
     'Editor: Word Wrap'. on
*** disable mdn show
    "editor hover enabled" and disable checkbox
*** File-autosave
*** extension
**** One Monokai Theme
**** Project Manager
**** alpinejs intelisense
**** babel js
**** eslint
**** comunity material themes
**** material icon 
*** multiples cursores con Alt-click
    si no funciona puede que el S.O. este usando esa combinacion en
    caso de mint p.e. ir a preferencias/windows y sacar la tecla alt
    para mover ventanas etc. y empieza a funcionar el multiple cursor
    de inmediato.
** mint usb utilities
usb image writer
usb disk formatter 
[[http://packages.linuxmint.com/pool/main/m/mintstick/][pagina donde descargar el deb del programa mintstick]]
** python
*** python3-tk y python3-pip python3-setuptools
*** pip3 install modulos
**** dateutils
**** fastnumbers
**** fpdf
**** Pmw
**** pyperclip
*** poner las fuentes DejaVu DejaVuBold 
** heroku
*** install
    sudo snap install --classic heroku
    si no se puede usar snap (como p.e. en MX-19)
   curl https://cli-assets.heroku.com/install-ubuntu.sh | sh  
*** verificar
    heroku --version
*** heroku login
    contraseña: Ataraxia76.
*** agregar en fl5
    heroku git:remote -a rxcba1
*** hacer push 
    si ha cambiado requeriment
    hacer
    pip freeze > requirement.txt

    git push heroku main
*** entrar al psql de heroku
psql -h ec2-3-95-87-221.compute-1.amazonaws.com -p 5432 -d daq6n3vvmrg79o -U ynpqvlqqsidhga  -f lite5.sql
** LAMP
*** instalar apache
 sudo apt install apache2
 sudo ufw app list
 sudo ufw app info "Apache Full"
 sudo ufw allow in "Apache Full"
 localhost    para ver si funciona apache

 instalar mysql
*** instalar mysql
    sudo mysql; (como root)
CREATE DATABASE hero;
CREATE USER 'hero' IDENTIFIED BY 'ata';
GRANT ALL PRIVILEGES ON hero.* to hero;

mejor opcion mas general y con super:
CREATE USER '{{ username }}'@'%' IDENTIFIED BY '{{ password }}';
GRANT ALL PRIVILEGES ON *.* TO '{{ username }}'@'%' WITH GRANT OPTION;
ALTER USER 'user'@'%' IDENTIFIED WITH mysql_native_password BY 'password';

FLUSH PRIVILEGES;
exit;

entro como
mysql -p
y pongo la password
*** instalar php
 sudo apt install php libapache2-mod-php php-mysql

** instalar myphpadmin
   OJO PRIMERO LAMP
sudo apt install phpmyadmin php-mbstring php-gettext

Warning: When the prompt appears, “apache2” is highlighted, but not
selected. If you do not hit SPACE to select Apache, the installer will
not move the necessary files during installation. Hit SPACE, TAB, and
then ENTER to select Apache

Select Yes when asked whether to use dbconfig-common to set up the
database

sudo phpenmod mbstring

sudo systemctl restart apache2

*** bug de phpmyadmin 
[[https://github.com/phpmyadmin/phpmyadmin/issues/15574][pagina que explica el bug y la correccion]]
actualizar el locate (buscar en doc/linux/locate-find) para encontrar
el archivo
/usr/share/phpmyadmin/libraries/... y corregirlo
** instalar adminer
   ver--> postbird...
*** debian 10
**** sudo apt install adminer
**** crear un archivo de conf con vim
sudo nano /etc/apache2/conf-available/adminer.conf
solo ponerle esta linea:
Alias /adminer /usr/share/adminer/adminer
**** sudo a2enconf adminer
**** sudo systemctl reload apache2
*** Nueva forma de instalar para ubuntu 20.04
 [[https://www.cyberciti.biz/faq/how-to-install-adminer-on-ubuntu-20-04-lts/][Instalar Adminer en Ubuntu 20.04 LTS]]
*** Instalacion para ubuntu 18.04 OJO primero LAMP
sudo mkdir /usr/share/adminer
sudo wget "http://www.adminer.org/latest.php" -O /usr/share/adminer/latest.php
sudo ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php
echo "Alias /adminer.php /usr/share/adminer/adminer.php" | sudo tee /etc/apache2/conf-available/adminer.conf
sudo a2enconf adminer.conf
sudo systemctl reload apache2

** postgres
1. sudo apt-get install wget ca-certificates
2. wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc |
sudo apt-key add -
3 echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
1. sudo apt-get update
2. sudo apt-get install postgresql postgresql-contrib
3. sudo su - postgres psql
4. instalar libpgtcl y postgresql-pltcl-11

*** instalacion de postgres
**** entrar como postgres
$sudo -u postgres psql
**** crear usuario
$sudo -u postgres createuser hero
**** crear base de datos
$sudo -u postgres createdb hero
**** dar password al usuario
$sudo -u postgres psql
postgres=# alter user hero with encrypted password 'ata';
postgres=# alter user hero with superuser;
**** le damos privilegios a la base de datos
postgres=# grant all privileges on database hero to hero;
**** cargamos el schema dumpeado previamente
$psql -f dumppreviodeschema.sql
** instalar postbird en electron
   electronjs.org / Aplicaciones / postbird
   es ultrarapida y genial y mejor que adminer.
*** heroku in postbird
para que conecte con la uri de la base de datos agregarle al final de
la cadena ?ssl=verify-full
pq intente hacer otras cosas como modificar el pg_hba.config que le
agregue dos lineas nuevas y el postgres.config que le puse ssl of y
otra modificacion.
** instalar Rails
sudo apt-get install libpq-dev
para que no de problemas la gem pg
gem install pg
[[https://gorails.com/setup/ubuntu/20.04][tutorial para instalar Rail en ubuntu 20.04]]
** instalar pgadmin 4 
1. sudo apt-get install pgadmin4 pgadmin4-apache2
2. durante la instalacion damos mail/password
3. para acceder a pgadmin ponemos localhost/pgadmin/browser
** instalar omnidb
1. bajar en omnidb.org
2. instalar el omnidb app y establecer conexion.
** instalar pgmodeler
1. instalar qt (bajar qt opensource de www.qt.io es un archivo run 
que se le da chmod u+x y luego se ejecuta con ./qt...run y se instala,
hacer skip donde piden los datos personales) 
Instalar en /home/hero/.Qt/
2. instalar solo la version  5.9.7 de Qt para no instalar todo pq es
mucho y es lerdo (aun asi me instalo cosas de android, ver si en
futuras instalaciones se podria evitar)
1. bajar el source de pgmodeler ultimo alpha, no clonar el pgmodeler.
2. seguir las instrucciones de intalacion de pgmodeler sobre las siguientes
   1. 1: pkg­-config libxml-­2.0 --cflags --libs
      2: ­-I/usr/include/libxml2 ­-lxml2 
      si no esta la orden pkg--config pienso que habra que instalarla
      una vez me dijo que no habia tal paquete y luego se curso como
      un paquete del sistema. y me dio un mensaje de error, con ese
      mensaje de error busque y encontre una pagina que parece que
      contenia un bug de debian sobre el tema y encontre una solucion
      en los comentarios, instalando a mano libxml2 de nuevo hasta
      obtener la salida que dice en 2.
[[https://stackoverflow.com/questions/31797524/r-devtools-fails-as-package-libxml-2-0-was-not-found-in-the-pkg-config-search-p][solucionar el problema de libxml2]]
wget ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz
tar xvf libxml... 
./configure --prefix=/usr --disable-static --with-history && make
sudo make install
y ya esta solucionado el problema de libxml2
Si hay un error en el make, algo pidiendo python.h se soluciona
instalando python-dev.
   2. 1: pkg­-config libpq --cflags --libs
      2: ­I/usr/include ­L/usr/lib64/libpq.so 
      tambien da una salida erronea y encontre una solucion en otra
      pagina
      [[https://github.com/pgmodeler/pgmodeler/issues/43][solucionar dependencia libpq]]
      apt-get install libpq-dev libpq5
     
3. orden de make
/home/hero/.Qt/5.9.7/gcc_64/bin/qmake -r PREFIX=/home/hero/.pgmodeler BINDIR=/home/hero/.pgmodeler PRIVATEBINDIR=/home/hero/.pgmodeler PRIVATELIBDIR=/home/hero/.pgmodeler/lib pgmodeler.pro
4. se travo el make con un error por un libutils.so.1.0.0
   [[https://github.com/pgmodeler/pgmodeler/issues/583][solucion a libutils.so.1.0.0]]
    apt-get install libgl1-mesa-dev
5. make
6. sudo make install
7. editar el pgmodeler.vars
export QT_ROOT="/home/hero/.Qt/5.9.7/gcc_64"
export PGMODELER_ROOT="/home/hero/.pgmodeler"
8. seguir las instrucciones 
cambiarle el nombre a pgmodeler.sh y mv a /etc/profile.d
1. arrancar pgmodeler en /.pgmodeler

** instalar fzf 
   git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
   ~/.fzf/install
[[http://owen.cymru/fzf-ripgrep-navigate-with-bash-faster-than-ever-before/] 
[Pagina de fzf]]
en especial notar que en bash con C-r se busca muy eficientemente en la 
historia del bash lo cual arregla todos los problemas que uno tuvo con el bash 
en especial el tema anular touchpad con el modprobe o hacer un commit etc.

** instalar workrave
[[https://workrave.org/download/ubuntu/][instalacion especifica para mate]]
** red con ssh
*** instalar ssh en ambas maquinas
instala varios archivos
*** obtener ip con ifconfig instalar net-tools
el ip es el inet la segunda linea a la izquierda
*** conectar
ssh -X -p 22 hero@192.168.0.243
password y voile!!!
estamos adentro y viceversa.
ssh -X -p 22 fede@192.168.0.39
password 
--- No olvidar la -X pq da un extraño error que nos extraviara, siendo
que -X es esencial para poder mostrar interfaces graficas a traves de
ssh, pero da un error de tk que nos deja confundidos y empezamos a
mirar el programa en vez de error en ssh.

*** si queremos ejecutar programas graficos agregar -X en la orden
ssh -X -p 22 ...
*** en dolphin para agregar una capeta del disco compartido
iniciar knetattach que no esta en el menu y no se como llegue a el
te permite hacer una carpeta con los datos de ssh.
poniendo como usuario el usuario que vamos a acceder, no el
nombremaquina, en este caso fede, y servidor el numero obtenido por
ifconfig o sea 192.168.0.243 y el dir que queremos acceder, nos pide
password y ya esta.
*** impresoras creo que va aparte de esto pero se compartio sin problema
*** faltaria ver como se podria via ssh compartir el romitex.db solo

** instalacion de red local
*** del lado del servidor
**** sudo apt install nfs-common nfs-kernel-server
**** editar /etc/exports
/home/hero/rx  192.168.0.39/24(rw,no_subtree_check)
de donde /home/hero/rx es el directorio a compartir
y 192.168.0.39 es la direccion ip de la maquina servidor que la
sacamos de ifconfig donde dice Direc. inet
**** sudo exportfs -a    (para que export comunique lo que hicimos)


*** del lado del cliente
**** sudo apt install nfs-common
**** mount 192.168.0.39:/home/hero/rx /home/dir_destinado_al_montaje
**** hacemos la correccion en fichaje.py para que romitex.db lo lea del dir_destinado_al_montaje en vez del usual rx
*** problemas
**** al abrir o cerrar
respetar el orden abrir servidor primero, cerrar primero el cliente
**** ver si la red funciona!!!!!!
me preocupaba pq no andaba y era que el puto fibertel no andaba ese
dia.
*** automount
sudo apt install autofs
edit /etc/auto.master
insert al tope del archivo
/mnt/nfs /etc/auto.network --ghost
esto montara la red remota dentro de /mnt/nfs (habria que ver sin o
tendria que poner mi directorio ahi o sea /home/fede/rx)
Parece que habria que crear el archivo /etc/auto.network
y agregarle la linea
MyShare     -rsize=32768,wsize=32768,intr,tcp,timeo=300,rw,user
192.168.1.2:/volume1/MyShare
[[https://ferhatakgun.com/properly-mounting-network-drives-linux/][Pagina que explica el proceso]]
** instalacion de la impresora HP 1102
sudo apt install hplib 
hp-setup 
esto instalara el driver bajado por hp no el que viene por defecto que
causa problemas varios aunque anda a veces.
** otras instalaciones
*** RIBreak
*** smb4k
*** vim
**** copiar .vimrc de /orgblok
**** instalar curl y Plug
 curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
[[https://github.com/junegunn/vim-plug][Pagina de Plug]]
**** instalar los plugins con 
:PlugInstall
*** formatear usb/instalar usb
[[http://packages.linuxmint.com/pool/main/m/mintstick/][link a pagina del proyecto]]
*** sqlitebrowser
sudo snap install --edge sqlitebrowser
** instalacion impresora EPSON L380
**** [[http://www.epson-driver.com/2017/06/epson-l380-driver-download-windows-mac-linux.html][pagina de busqueda EPSON]]
**** [[http://download.ebz.epson.net/dsc/search/01/search/?OSC%3DLX][pagina especifica de drivers Linux]]
**** instalar los dos drivers que da para impresora !!
**** previamente instalar la dependencia que requiere
apt-get install lsb
**** en dialogo impresoras agregar impresora
detecta la epson y aceptar el driver que ya estara instalado
y listo.
**** el driver de scaner no me funciono
** ssh  -L 5433:127.0.0.1:5432 hero@192.168.0.243 -N
con esto hice un tunel ssh, y luego a postgres lo conecto con port
5433 y host localhost.
este tunel se crea en la maquina cliente "en vez" de iniciar conexion
ssh, pq el tunel es la conexion. te pide contraseña y te entra en
conexion pero no hace falta que las aplicaciones residan en la maquina
servidor o sea se pueden iniciar con atajos propios y dejar esa
terminal vacia. Se sale luego con exit o se cierra.
** instalar applicacion menu con kmenuedit
Alt-space (Ctrl-F2)  luego de ubicarse en la rama poner nuevo elemento
y poner el elemento.
Luego Guardar.
** agregar alias a bashrc
comit='git commit -a -m "asus" && git push && git status'
cd..='cd ..'
exit='q'
&& asegura que el segundo comando se ejecute solo si el primer comando
es exitoso.
** contactos telefonicos vcf
1. emitir csv
abrir en terminal sqlite
cd rx
sqlite3 romitex.db
.mode csv
.output contactos.csv
Opcion emitir contactos unicamente de clientes pagando: (opcion vieja
para cobrar)
select nombre,calle||' '||num,wapp,dni from clientes where wapp is not
null and deuda>0 and pmovto>date('now','-4 years');

Opcion emitir contactos de clientes pagando y clientes cancelados cuya
ultima compra fue dentro del ultimo año para que podamos vender tambien:

select nombre,calle||' '||num,wapp,dni from clientes where (wapp is
not null or wapp<>"") and ((deuda>0 and pmovto>date('now','-4 years'))
or (deuda=0 and ultcompra>date('now','-1 years')));

2. tranformar en vcf con pagina
[[http://phrogz.net/js/csv2vcard_2.html][pagina]]
cortar y pegar el contenido de contactos.csv (p.e en kate) y ponerlos
en en recuadro de Steep 1
agregar como primer fila la siguiente fila:
Nombre,Domicilio,WApp,DNI

En el Step 2 especificar el tipo segun lo indicado abajo
Specify Types
Nombre- First Name
Domicilio- StreetAdress1 (Home)
WApp Phone (Cell)
DNI Company

1. copiar el contenido de Step3 y pegar en editor y ponerle un nombre.vcf
previamente sacarle las comillas dobles con C-r " 
1. importarlo con el telefono
** solaar para mejor uso de logitech teclado y raton 
sudo apt install solaar 
desenchufar y volver a enchufar el usb
abrir solaar
** reconfigurar extensor tp-link
   bajar app tp link tether
   resetear el extensor con una aguja estando enchufado
   conectar con cable de red al modem
   buscarlo en la app y seguir los pasos
* ATAJOS A APRENDER
** control-esc show system activity
mas rapido y al acceso que ksysguard
** C-A-Esc kill app
te muestra una calaverita roja que te mata la aplicacion.
** C-A-Del logout
** maximizacion y movimiento de ventanas facil
doble-click en titulo
win-down/left/right/up primero resize a half en el sentido de la
flecha y luego mueve.
alt-boton izq mueve la ventana
alt-boton der resize 
boton izq solo en titulo o areas no inner mueve cambiandose el cursor
a la cruz de movimiento
* ruby
** rails DEPRECATED
*** instalacion
**** sudo apt install libsqlite3-dev
**** sudo gem install sqlite3
**** sudo gem install therubyracer
**** sudo gem install rails
*** rails server (problemas para inicio de webpacker)
**** install yarn
***** instalar la version 1.21.1
$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
$ sudo apt update
$ sudo apt -y install yarn
$ sudo apt -y install --no-install-recommends yarn
$ yarn --version
1.21.1
[[https://yoshikimi.com/programming/rails/6][Pagina con explicacion anterior]]
**** rails webpacker:install
***** puede que pida la version actualizada de node.js
[[https://nodejs.org/en/download/][Link para bajar el binario de node.js]]
y en la misma pagina toda la explicacion de la instalacion.
No se instala propiamente dicho, sino que se ubica en un directorio y
se hace un path.
**** yarn install --check-files
**** rails s
** rails instalacion 20.04
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update
sudo apt-get install git-core zlib1g-dev build-essential libssl-dev
libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev
libxslt1-dev libcurl4-openssl-dev software-properties-common
libffi-dev nodejs yarn

cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
exec $SHELL

rbenv install 2.7.1
rbenv global 2.7.1
ruby -v

gem install bundler

git config --global color.ui true
git config --global user.name "YOUR NAME"
git config --global user.email "YOUR@EMAIL.com"
ssh-keygen -t rsa -b 4096 -C "YOUR@EMAIL.com"

gem install rails -v 6.0.2.2
rbenv rehash
rails -v
# Rails 6.0.2.2
sudo apt install postgresql-11 libpq-dev
sudo -u postgres createuser chris -s

# If you would like to set a password for the user, you can do the following
sudo -u postgres psql
postgres=# \password chris

rails new myapp
rails new myapp -d postgresql
cd myapp
rake db:create

rails server
You can now visit http://localhost:3000 to view your new website!
[[https://gorails.com/setup/ubuntu/20.04][
Pagina original]]

** tk
*** instalacion de gem tk on ubuntu
**** primero tcl8.5-dev no 8.6 que no es compatible
sudo apt-get install tcl8.5-dev tk8.5-dev
**** luego unos ln
sudo ln -s /usr/lib/x86_64-linux-gnu/tcl8.5/tclConfig.sh /usr/lib/tclConfig.sh
sudo ln -s /usr/lib/x86_64-linux-gnu/tk8.5/tkConfig.sh /usr/lib/tkConfig.sh
sudo ln -s /usr/lib/x86_64-linux-gnu/libtcl8.5.so.0 /usr/lib/libtcl8.5.so.0
sudo ln -s /usr/lib/x86_64-linux-gnu/libtk8.5.so.0 /usr/lib/libtk8.5.so.0
**** [[https://saveriomiroddi.github.io/Installing-ruby-tk-bindings-gem-on-ubuntu/pagina%20explicativa]]
**** gem install tk
Building native extensions. This could take a while...
Successfully installed tk-0.2.0
1 gem installed
** gtk2
sudo apt install ruby-gtk2
