* procesos mentales que pueden venir de chico
** vivencia de tener que dejar mi proyecto en favor de un familiar
** vivencia de que no era dado ni siquiera desear algo
** vivencia de invisibilidad
** vivencia de no ser amado
* "necesidades" que hay que descubrir que se satisfacen con problematicidades
** necesidad de pontificar u obtener lustre indirectamente
o sea de hacerse odiar. O sea de resaltar cosas en las cuales siempre
quedamos bien parados o mejor parados que los demas. O sea es una
forma de busqueda de aprobacion externa que viene a ser buscada
indirectamente.
** necesidad de quejarse
hay un articulo perfecto en el cuaderno donde describo el ideal que
veria en ih si sirviera a proposito para mis quejas.
** necesidad de dolor de cabeza o de tomar analgesico
en especial frente a una crisis de nervios o a un imprevisto que me
saque de la rutina
** necesidad de hacer "competir" por el amor o la atencion
   con un placer perverso de mirar al que esta "perdiendo" la atencion. Este 
   recurso que es ampliamente usado en las peliculas y series.
   P.e. en serie Amor S01E03 donde Mickey ve a Gus que atrae la atencion de 
   otra chica y ella aparentemente se queda mirando de afuera. Y eso explota 
   la perversa cuestion dentro de muchos de nosotros de no solo "hacer 
   competir por el amor" sino de mirar sadicamente al perdedor como diciendo 
   mira lo que te perdiste. Esto que creo que es algo enfermo, debe provenir 
   de la infancia en una etapa en que a uno lo deben haber desplazado en un 
   contexto de amor limitado, siendo que el amor hubiera podido alcanzar para 
   todos. Y de mayor uno tiende a beneficiar mas a uno que a otro. Y a gozar 
   con sadismo de esas diferencias. 
