
Este archivo concentrara todo lo relativo al tema medico
turnos, sintomas, historial etc.

* turnos [4/6]
** DONE 16.30 MEUBRY, SOLANGE DEL VALLE traumatologia 
SCHEDULED: <2017-09-26 mar>
- State "DONE"       from "TODO"       [2017-09-26 mar 19:16]


*y* TODO 12.40 Romero William
SCHEDULED: <2017-11-08 mié>
** TODO Dra Banus Maria Victoria 18hs 
SCHEDULED: <2017-11-30 jue>
** DONE radiografias MEUBRY, SOLANGE DEL VALLE traumatologia 
DEADLINE: <2017-10-25 mié> SCHEDULED: <2017-09-30 sáb>
- State "DONE"       from "TODO"       [2017-10-25 mié 12:49]

** DONE analisis Romero William
SCHEDULED: <2017-09-30 sáb>
- State "DONE"       from "TODO"       [2017-09-29 vie 12:00]
** DONE sacar turno endocrinologia
SCHEDULED: <2017-09-27 mié>
- State "DONE"       from "TODO"       [2017-09-27 mié 19:34]
** TODO Romero William [2018-01-03 mié] 12.40hs

* sintomas
** Dolores
*** Testiculos
[2017-09-15 vie] aparecio de repente que yo pense que era premonitorio
de un gran ataque virosico y buscaba las ampollitas y me puse ac, pero
nada, luego lo tuve el sabado a la mañana y se fue.
Creo que la causa fue el boxer ajustado.
[2017-09-18 lun] hoy hace un rato vuelvo a sentir pero a nivel
varicocele en el huevo izquierdo, o como una sensacion de hernia, no
como senti el viernes como algo masivo que abarcaba todo el perineo y
casi no me dejaba sentar.
[2017-10-02 lun] en oficina senti como me apretaba el huevo derecho el
boxer y de nuevo no se si es causa o efecto, o sea si el boxer es el
causante o siento el boxer cuando tengo el dolor y lo sentiria igual
con slip
*** Implantes
[2017-09-19 mar] hoy tengo bastantes molestias en en los implantes
izquierdos en ambos, mas que todo en el de mas atras.
Creo que la causa fue un cepillado demasiado intenso en la zona
lastimada de los implantes.
*** presion en brazos
[2017-09-21 jue] siento presion en los brazos a la altura del codo de
la parte de adentro como si tuviera una banda elastica que me
oprimiera, mas que todo el derecho y muchisimo menos el izq casi nada,
asi casi como dos horas que lo tengo y casi se me irradia a dolor en
la mano derecha al escribir en el teclado. y por momentos en la
oficina senti como que los ojos no enfocaban bien y se deslumbraban
con la pantalla, pero recien me vine caminando bien hasta aca, solo
tengo esto y un poco de rareza en la cabeza.
Creo que la causa es el ejercicio de brazos.
*** Temblores
[2017-09-25 lun] si bien es cierto que hace dos años que los padezco
hoy tuve un ataque bastante feo en mano izquierda posterior a
levantarme.
Y tengo la sensacion que habia cesado el sintoma por mucho tiempo y se
volvio a complicar el ultimo tiempo.
*** retorcijones
[2017-10-02 lun] la noche anterior safe con oleo31 y a la mañana
volvieron y me tome una pastilla de carbon y no jodio mas enla
oficina.
*** cadera derecha
[2017-10-05 jue] un dolor que aparecio hace una semana y que me impide
cruzar la pierna del lado derecho y lo sospecho que es el sillon de la
oficina.
[2017-10-31 mar] este ultimo fin de semana estuvo muy inflamado la
cadera incluso me parecio que se propagaba a la otra. Pienso que se
debe en parte a que la mala postura en el marques se potencia con la notebook.
[2017-11-14 mar] hoy tuve un choque en puerta del fondo de oficina con
pie derecho que repercutio en cadera derecha inflamada y me hizo
gritar literalmente de dolor, muy feo eso. No le hacen nada los
masajes ni unguentos. Va de mal en peor.
*** espalda
[2017-10-18 mié] muy mucho dolor de espalda, toda la noche, pienso que
la culpa del dolor de anoche la tuvo el sillon. Ahoche me colgue con
tres capitulos de netflix y eso se noto a nivel espalda es peor que la
jornada de sillon con la compu.
[2017-10-31 mar] este ultimo finde tuve un pico de malestar en la
espalda hasta el punto que con oleo31 tuve masajes el domingo en
varias oportunidades y poco alivio tuve, y el domingo a la noche y el
lunes me tome un diclo para aliviar sintomas de inflamacion.
*** acidez extrema
[2017-10-18 mié] hasta el punto de tomar agua para pasar la noche, me
paso hace dos noches en el marques y hoy tome un gastromax a la mañana
como primer medicamento
*** polialquria
[2017-10-18 mié] ya a nivel molesto, tener que levantarme tantas veces
de noche siendo que hace unas cuantas noches habia logrado cierto equilibrio.
*** nerviosismo
[2017-11-02 jue] hoy me tuve que ir al dpto a buscar SL para ponerme
una y soportar la jornada, pq vengo desde ayer no soportando los
embates normales del trabajo.
* medicacion
** ibuprofeno
| Fecha            | cnt | sintomas                     |
|                  |  65 | 0                            |
|------------------+-----+------------------------------|
| [2017-09-18 lun] |   2 |                              |
| [2017-09-19 mar] |   2 | dolor molesto toda la tarde  |
| [2017-09-20 mié] |   1 | desperte con dolor           |
| [2017-09-21 jue] |   1 |                              |
| [2017-09-22 vie] |   1 | madrugada                    |
| [2017-09-23 sáb] |   0 |                              |
| [2017-09-24 dom] |   1 |                              |
| [2017-09-25 lun] |   1 | 14hs en dpto                 |
| [2017-09-26 mar] |   2 | madrugada y oficina          |
| [2017-09-27 mié] |   1 | madrugada                    |
| [2017-09-28 jue] |   2 | 12/23hs                      |
| [2017-09-29 vie] |   2 | 12hs/22hs                    |
| [2017-09-30 sáb] |   1 | 18hs                         |
| [2017-10-01 dom] |   2 |                              |
| [2017-10-02 lun] |   1 | 19hs                         |
| [2017-10-03 mar] |   2 | 8/15hs                       |
| [2017-10-04 mié] |   1 |                              |
| [2017-10-05 jue] |   1 |                              |
| [2017-10-06 vie] |   2 | 10/18hs                      |
| [2017-10-07 sáb] |   2 | 15/23                        |
| [2017-10-08 dom] |   2 | 10/17                        |
| [2017-10-09 lun] |   1 | 13                           |
| [2017-10-10 mar] |   1 | ?                            |
| [2017-10-11 mié] |   2 | 4am/15hs                     |
| [2017-10-12 jue] |   2 | 4am/22                       |
| [2017-10-13 vie] |   2 | 11.30hs/15.30hs              |
| [2017-10-14 sáb] |   2 | 12/23hs                      |
| [2017-10-15 dom] |   2 | 10/15hs                      |
| [2017-10-16 lun] |   0 |                              |
| [2017-10-17 mar] |   3 | 1.30 am/12hs/20hs            |
| [2017-10-18 mié] |   2 | 11.30/23hs                   |
| [2017-10-19 jue] |   1 | 11                           |
| [2017-10-20 vie] |   1 | 19hs                         |
| [2017-10-21 sáb] |   1 | 10hs                         |
| [2017-10-22 dom] |   2 | 9hs/17hs                     |
| [2017-10-23 lun] |   1 | 11hs                         |
| [2017-10-24 mar] |   2 | 10/23hs                      |
| [2017-10-25 mié] |   1 | 13hs                         |
| [2017-10-26 jue] |   1 | 23hs                         |
| [2017-10-27 vie] |   1 | 15hs                         |
| [2017-10-28 sáb] |   1 | 11hs                         |
| [2017-10-29 dom] |   1 | 11hs                         |
| [2017-10-30 lun] |   1 | 18hs                         |
| [2017-10-31 mar] |   1 | 11hs                         |
| [2017-11-01 mié] |   2 |                              |
| [2017-11-02 jue] |   2 |                              |
| [2017-11-03 vie] |   1 |                              |
| [2017-11-04 sáb] |   1 |                              |
| [2017-11-05 dom] |   1 |                              |
| [2017-11-06 lun] |   1 |                              |
| [2017-11-07 mar] |   1 |                              |
| [2017-11-08 mié] |   1 | 3 am                         |
| [2017-11-09 jue] |   1 |                              |
| [2017-11-10 vie] |   1 |                              |
| [2017-11-11 sáb] |   1 |                              |
| [2017-11-12 dom] |   1 |                              |
| [2017-11-13 lun] |   2 | ambos en oficina             |
| [2017-11-14 mar] |   1 | 21:45hs                      |
| [2017-11-15 mié] |   0 |                              |
| [2017-11-16 jue] |   0 |                              |
| [2017-11-17 vie] |   0 |                              |
| [2017-11-18 sáb] |   1 | 13hs                         |
| [2017-11-19 dom] |   1 | 11.30hs preventivo y espalda |
| [2017-11-20 lun] |   1 | 17hs                         |
| [2017-11-21 mar] |   0 |                              |
| [2017-11-22 mié] |   1 | 7am                          |
| [2017-11-23 jue] |   2 | 1am - 16hs                   |
| [2017-11-24 vie] |   1 | 16hs                         |
| [2017-11-25 sáb] |   1 | 11hs                         |
| [2017-11-26 dom] |   1 | 11hs                         |
| [2017-11-27 lun] |   0 |                              |
| [2017-11-28 mar] |   2 | 10hs/15hs                    |
| [2017-11-29 mié] |   1 | 15hs                         |
| [2017-11-30 jue] |   1 | 17hs                         |
| [2017-12-01 vie] |   1 | 16hs                         |
| [2017-12-02 sáb] |   0 |                              |
| [2017-12-03 dom] |   1 | tarde                        |
| [2017-12-04 lun] |   0 |                              |
| [2017-12-05 mar] |   2 | 8hs y 14hs                   |
| [2017-12-06 mié] |   1 | 12.30hs                      |
| [2017-12-07 jue] |   1 | 17hs                         |
| [2017-12-08 vie] |     |                              |
| [2017-12-09 sáb] |   1 |                              |
| [2017-12-10 dom] |   0 |                              |
| [2017-12-11 lun] |   1 | 13hs                         |
| [2017-12-12 mar] |   2 | 16hs-21hs                    |
| [2017-12-13 mié] |   2 | 10hs/15.30ha                 |
| [2017-12-14 jue] |   1 | 13.30hs                      |
| [2017-12-15 vie] |   1 | 12hs                         |
| [2017-12-16 sáb] |   1 |                              |
| [2017-12-17 dom] |   2 |                              |
| [2017-12-18 lun] |   1 | 10.30                        |
| [2017-12-19 mar] |   2 | 9 y 14hs                     |
| [2017-12-20 mié] |   1 | 23hs                         |
| [2017-12-21 jue] |   2 | 15hs-tarde                   |
| [2017-12-22 vie] |   1 | 15hs                         |
| [2017-12-23 sáb] |   1 |                              |
| [2017-12-24 dom] |   1 |                              |
| [2017-12-25 lun] |   1 |                              |
| [2017-12-26 mar] |   1 | 11hs                         |
| [2017-12-27 mié] |   0 |                              |
| [2017-12-28 jue] |   1 | 11hs                         |
| [2017-12-29 vie] |   2 | 13hs/14.45hs                 |
| [2017-12-30 sáb] |   1 |                              |
| [2017-12-31 dom] |   2 |                              |
| [2018-01-01 lun] |   1 |                              |
| [2018-01-02 mar] |   2 | 9hs y 22hs                   |
| [2018-01-03 mié] |   1 | 9hs                          |
| [2018-01-04 jue] |   1 | 13hs                         |
| [2018-01-05 vie] |   1 | 10hs                         |
| [2018-01-06 sáb] |   1 |                              |
| [2018-01-07 dom] |   1 |                              |
| [2018-01-08 lun] |   1 |                              |
| [2018-01-09 mar] |   2 |                              |
| [2018-01-10 mié] |   2 | 10hs y 19hs                  |
| [2018-01-11 jue] |   1 |                              |
| [2018-01-12 vie] |   1 |                              |
| [2018-01-13 sáb] |   1 |                              |
| [2018-01-14 dom] |   2 |                              |
| [2018-01-15 lun] |   0 |                              |
| [2018-01-16 mar] |   0 |                              |
| [2018-01-17 mié] |   0 |                              |
| [2018-01-18 jue] |   0 |                              |
| [2018-01-19 vie] |   0 |                              |
| [2018-01-20 sáb] |   0 |                              |
| [2018-01-21 dom] |   0 |                              |
| [2018-01-22 lun] |   1 | 10hs                         |
| [2018-01-23 mar] |   1 |                              |
| [2018-01-24 mié] |   1 |                              |
| [2018-01-25 jue] |   1 |                              |
| [2018-01-26 vie] |   1 |                              |
| [2018-01-27 sáb] |   1 |                              |
| [2018-01-28 dom] |   1 |                              |
| [2018-01-29 lun] |   1 |                              |
| [2018-01-30 mar] |   1 |                              |
| [2018-02-01 jue] |   1 |                              |
| [2018-02-02 vie] |   1 |                              |
| [2018-02-03 sáb] |   1 |                              |
| [2018-02-04 dom] |   1 |                              |
| [2018-02-05 lun] |   1 |                              |
| [2018-02-06 mar] |   1 |                              |
| [2018-02-07 mié] |   2 |                              |
| [2018-02-08 jue] |   1 |                              |
| [2018-02-09 vie] |   1 |                              |
| [2018-02-10 sáb] |   1 |                              |
| [2018-02-11 dom] |   1 |                              |
| [2018-02-12 lun] |   1 |                              |
| [2018-02-13 mar] |   2 |                              |
| [2018-02-14 mié] |   1 |                              |
| [2018-02-15 jue] |   1 |                              |
| [2018-02-16 vie] |   1 |                              |
| [2018-02-17 sáb] |   1 |                              |
| [2018-02-18 dom] |   2 |                              |
| [2018-02-19 lun] |   0 |                              |
| [2018-02-20 mar] |   1 |                              |
| [2018-02-21 mié] |   1 |                              |
| [2018-02-22 jue] |   1 |                              |
| [2018-02-23 vie] |   2 |                              |
| [2018-02-24 sáb] |   1 |                              |
| [2018-02-25 dom] |   1 |                              |
| [2018-02-26 lun] |   1 |                              |
| [2018-02-27 mar] |   0 |                              |
| [2018-02-28 mié] |   1 |                              |
|                  |     |                              |
#+TBLFM: @2$2=vsum(@3$2..@>$2)
** naratriptan
| Fecha            | cnt | hora     |
| [2017-09-27 mié] |   1 | 6.30hs   |
| [2017-10-13 vie] |   1 | 18.30hs  |
| [2017-10-15 dom] |   1 | 18.30hs  |
| [2017-10-18 mié] |   1 | 1.30 am  |
| [2017-10-19 jue] |   1 | 4.30 am  |
| [2017-10-20 vie] |   1 | 4.30 am  |
| [2017-10-22 dom] |   1 | 17.30hs  |
| [2017-11-06 lun] |   1 | 3.30 am  |
| [2017-11-08 mié] |   1 | 4.20 am  |
| [2017-11-10 vie] |   1 | 14.45 hs |
| [2017-11-12 dom] |   1 | 3.30 am  |
| [2017-11-13 lun] |   1 | 17.30hs  |
| [2017-11-15 mié] |   1 | 3 am     |
| [2017-11-16 jue] |   1 | 15.40hs  |
| [2017-11-17 vie] |   1 | 11.40hs  |
| [2017-11-18 sáb] |   1 | 12hs     |
| [2017-11-19 dom] |   1 | 13hs     |
| [2017-11-20 lun] |   1 | 17hs     |
** gastromax
| fecha            | cnt | horas            |
| [2017-09-27 mié] |   2 | mediodia y noche |
| [2017-10-18 mié] |   1 | mañana           |
** TODO Cabergolina
SCHEDULED: <2018-02-09 
vie .+1w>
- State "DONE"       from "TODO"       [2018-02-02 vie 20:31]
- State "DONE"       from "TODO"       [2018-01-21 dom 12:12]
- State "DONE"       from "TODO"       [2018-01-05 vie 21:20]
- State "DONE"       from "TODO"       [2017-11-23 jue 09:47]
- State "DONE"       from "TODO"       [2017-11-09 jue 09:13]
- State "DONE"       from "TODO"       [2017-11-02 jue 21:23]
- State "DONE"       from "TODO"       [2017-10-25 mié 20:17]
- State "DONE"       from "TODO"       [2017-10-17 mar 19:58]
- State "DONE"       from "TODO"       [2017-10-09 lun 18:38]
- State "DONE"       from "TODO"       [2017-10-02 lun 22:31]
- State "DONE"       from "TODO"       [2017-09-25 lun 21:25]
- State "DONE"       from "TODO"       [2017-09-18 lun 18:44]
:PROPERTIES:
:LAST_REPEAT: [2018-02-03 sáb 15:31]
:END:
** migral
| Fecha            | cnt | hora        |   |   |
| [2017-11-20 lun] |   1 | 20.23hs     |   |   |
| [2017-11-25 sáb] |   1 | 12hs        |   |   |
| [2017-11-27 lun] |   1 | 01am        |   |   |
| [2017-11-28 mar] |   1 | 16hs        |   |   |
| [2017-12-01 vie] |   1 | 16hs        |   |   |
| [2017-12-06 mié] |   1 | 13hs        |   |   |
| [2017-12-07 jue] |   1 | 15hs        |   |   |
| [2017-12-10 dom] |   1 | 4 am        |   |   |
| [2017-12-13 mié] |   1 | 16hs        |   |   |
| [2017-12-15 vie] |   1 | 15hs        |   |   |
| [2017-12-19 mar] |   1 | 15hs        |   |   |
| [2017-12-22 vie] |   1 | 15.30hs     |   |   |
| [2017-12-28 jue] |   1 | 15.30hs     |   |   |
| [2017-12-29 vie] |   1 | 16hs        |   |   |
| [2018-01-02 mar] |   1 | 23.30hs     |   |   |
| [2018-01-07 dom] |   1 | 22hs        |   |   |
| [2018-01-19 vie] |   1 | 2 am        |   |   |
| [2018-01-20 sáb] |   1 | 15hs        |   |   |
| [2018-01-22 lun] |   1 | 19hs        |   |   |
| [2018-01-25 jue] |   2 | 16 y 19hs   | l |   |
| [2018-01-28 dom] |   1 | 17hs        |   |   |
| [2018-01-31 mié] |   1 | 21hs        |   |   |
| [2018-02-03 sáb] |   1 | 11hs        |   |   |
| [2018-02-04 dom] |   1 | 23hs        |   |   |
| [2018-02-08 jue] |   1 | 01.30 hs am |   |   |
| [2018-02-11 dom] |   1 | 18.30hs     |   |   |
| [2018-02-17 sáb] |   1 | 18.30hs     |   |   |
| [2018-02-20 mar] |   1 | 16.30hs     |   |   |
| [2018-02-24 sáb] |   1 | 4.00 am     |   |   |
|                  |     |             |   |   |

** DONE VitC
SCHEDULED: <2017-09-29 vie>
- State "DONE"       from "TODO"       [2017-09-29 vie 19:59]
- State "DONE"       from "TODO"       [2017-09-28 jue 18:02]
- State "DONE"       from "TODO"       [2017-09-27 mié 19:30]
- State "DONE"       from "TODO"       [2017-09-26 mar 19:16]
- State "DONE"       from "TODO"       [2017-09-25 lun 21:25]
- State "DONE"       from "TODO"       [2017-09-24 dom 12:19]
- State "DONE"       from "TODO"       [2017-09-23 sáb 22:29]
- State "DONE"       from "TODO"       [2017-09-22 vie 17:44]
- State "DONE"       from "TODO"       [2017-09-21 jue 19:44]
- State "DONE"       from "TODO"       [2017-09-20 mié 21:58]
:PROPERTIES:
:LAST_REPEAT: [2017-09-29 vie 19:59]
:END:


* cefaleico
** [2017-09-19 mar] 
un dia feucho del dolor desde la mañana, pq desperte con dolor y tome
el primer ibu temprano. Luego el segundo en la ofi misma. Y sali
temprano de la ofi pq pensaba que iba a tener una cefalea molesta, y
luego con el disgusto-desasosiego (ver diario) pero hice lo que dice
el libro, segui con el plan con todo, como un bull, y luego me tome
unos buenos mates, y luego me perdi en la compu en mi silloncito nuevo
y en el medio hice todo el ejercicio y el dolor se limpio totalmente.
** [2017-09-20 mié]
desperte con dolor bastante feucho, tanto que pensaba que iba a
terminar en nar. Tome un ibu a las 4.30hs y luego me levante bien.
** [2017-09-22 vie]
desperte con dolor mas o menos molesto, pero pienso que fue debido a
que comi casi toda la bandeja de una tarta de pollo muy tarde y ahi al
toque me fui a dormir, tome el ibu y me dormi y se fue todo bien, me
levante joya.
** [2017-09-24 dom]
el domingo tome uno a las 12hs medio al pedo, pero por momentos
parecia que era necesario, como paso al final ahora, el lunes que
escribo esto y no lo tomas y no pasa nada. Pq transcurrio el domingo y
no paso nada. Ojo con tomar por safar de situaciones o por arreglar un
dia que parezca nefasto.
** [2017-09-26 mar]
mal desperte con dolor como costumbre luego de la cabergolina, y todo
bien, se fue, me levante y me bañe, y ahora en oficina, luego de una
mañana dificil y sin desayuno me tomo un segundo ibu pq tengo un
punzante en sien izq que espero se vaya. pero pienso que si se va a
ir.
** [2017-09-27 mié]
desperte como todas las noches de este tipo, tomo ibu con yogur, sigo
durmiendo y me despierto de nuevo con un dolor mas intenso y dormido
como estaba decido un <nar> pensando que tenia oficina, pienso que me
acuchilla los compromisos de la oficina, que estoy muy cansado por
eso.
** [2017-09-28 jue]
tuve unos dolorcitos que por momentos me hicieron pensar en tomar algo
mas fuerte o sea que por ahi te parece que se va a ir de
madre. Felizmente anoche que comi bastante y queria irme a hacer el
analisis y no tomar nada a la madrugada no jodio
** [2017-09-29 vie]
por ahi aparecen tipo puntadas de la nada esta bien que no le doy
pausa cuando estoy en la oficina y tambien tendria que tomarme un
ejercicio.
en especial que hago algo de mala postura, que tuve como una hora
poniendo la compu atras muy incomodo.
Lo mismo que ayer la puntadita, y el exceso. No descanso, y sigo y
sigo, pero como me va bien, sigo, y alterno, ejercicios, limpieza,
comida, etc, pero la puntadita sigue y la amenaza sigue y todo el
significante del migral agazapado, ese seguir hasta reventar total
tomo la pastilla y se me va o caigo reventado. no me importa.
** [2017-09-30 sáb]
tomo un ibu postsiestal y preparatorio para lo que vendra esta noche
con los nietos. Al final a pesar de que no habia traido nar, gran
olvido de mi parte, y de haber sido una noche dificil, habia comido
mucho y mal, y me habia acostado ahi nomas, y sentia como que al menos
tenia que tomar otro ibu, hasta pense que haria ante una migraña (me
iba a ir en el auto a buscar el nar), al final dormi tranquilo, no
tome el ibu y se limpio solo el dolor
** [2017-10-01 dom]
ayer pensaba nuevamente que iba a llegar al nar, y antes de acostarme
tome el segundo luego de un domingo que trabaje mucho y no disfrute pq
estuve tenso todo el dia, pq estaba enojado con el Fede a la
distancia. Y al acostarme luego de comer profusamente me agarro
retorcijon fuerte, y tuve que aplicarme profusamente oleo31. 
** [2017-10-03 mar]
molesto un poco en oficina me fui a comer a casa lasagna y volvi con
un poco de dolor.
** [2017-10-06 vie]
no parecia hoy un dia especialmente molesto, pero llegue a casa y me
tome un segundo ibu.
** [2017-10-07 sáb]
hoy tome dos ibus por los implantes
** [2017-10-08 dom]
idem ayer tome dos ibus por implantes, aunque hoy domingo pense por
momentos a la tarde que iba a tomar un nar, pq el segundo ibu en
realidad lo adelante y lo tome por cefaleico y luego se fue todo y
termine por no tomar nada.
** [2017-10-09 lun]
hoy a las 13hs fue por implantes directamente.
** [2017-10-13 vie]
hoy despues de muchos dias me molesta un poco un dolor continuo, y
creo que es la desintoxicacion del cuarto dia de licuado. Es increible
el cambio que el licuado me hizo a nivel estomacal.
Creo que termino tomando <<nar>> pq se habia generado un sistema
nervioso con relacion a la cena de graduacion de la mayra y sumado a
la detox hizo que lo tomara. Creo que si hubiera sido un dia normal en
que con el mismo proceso en marcha me hubiera podido recostar o no
hubiera tenido tension creo que no lo tomaba.
** [2017-10-14 sáb]
hoy estoy patetico he dormido bien anoche luego de un dia o dias de
tension por un compromiso que no se dio y enfrento un finde largo y no
me puedo distender pq estoy patetico para querer estar enfrascado todo
el dia metido en la compu y al final no hago nada en la compu y no me
sirve de nada el resultado pq no rindo y a la vez el cuerpo sufre peor
que en mi casa pq aca el tema posicional es ferozmente feo y ya esta
subiendo a dolor de cabeza y esta afectando a incomodidades.
Al final termine con la netbook hasta casi las 2 am, y a la noche me
tome un ibu casi preventivamente sin necesidad.
** [2017-10-15 dom]
obviamente que me iba a dar la pataleta por los desmanes que
estaba/estoy haciendo y por la comida. Hoy comi como loco y comi esa
porcion de torta de chocolate encima. Pero no tendria porque darme la
cefalea esta no se pq se da todo esto quizas sea por falta de sueño o
que. y tome un segundo ibu apenas volvi del almuerzo y luego me senti
mal cuando me acoste afuera en el futon y me tome un <<nar>> que
termino haciendo efecto bastante rapido y quedo con una leve
resaca. Ayudo que me puse a lavar a mano y colgar la ropa en el aire y
me despeje un poco tomando mates y deje un poco la compu.
Ahora voy a descansar un poco.
** [2017-10-17 mar]
ayer no tome nada pero hoy empece temprano a la una y media con un
ibu, el dia en oficina normal, y a la tarde senti como en los viejos
tiempos la presion de la cefaleica y cuando me decia que yendome a
caminar un poco se me iba a ir, y omiti tomarme un segundo (tercero en
realidad). Luego me olvide pero tome cabergolina y estoy precefaleico
asi que en un rato me tomo otro.
** [2017-10-18 mié]
anoche muy mal me desperte con intensa cefalea para <<nar>> que tome
solo con agua y segui durmiendo y fue efectivo en la noche. Me dio un
poco de miedo pq en la noche anterior habia tomado cabergolina, nunca
habia tomado tan cerca ambos medicamentos.
Pero sigo cefaleico. 
Es que tenemos problemas y tensiones en el trabajo.
** [2017-10-19 jue]
anoche me tome un ibu preventivo pq estoy cefaleico como ahora y dormi
bien hasta las 4.30am que me desperte y tome un <<nar>> y mas o menos
se fue y me levante bien y la mañana fue particularmente intensa y
nerviosa hasta el mediodia que tomo otro ibu y sigo cefaleico.
** [2017-10-20 vie]
el primer triplete desde no se si hubo. anoche a las 1.30hs ya
desperte mal. Decidi esperar total estaba con margen, y ya a las 4.30
decidi tomarlo pq tengo responsabilidad de empresa. Quizas me dije si
hubiera sido fin de semana hubiera probado no tomarlo.
Esta mañana pensando en cosas que habian cambiado, aparte de mayor
tension los ultimos dias, me surgio el licuado como factor que disparo
el tema cefaleico. La semana pasada lo atribui al movimiento
desintoxicante. Pero no logro que haya evacuacion y ello quizas sea un
factor. O quizas las almendras o el lino o la avena sean viejas y
tengan un componente dañino que me provoque migraña. pq como estoy
tomando litro y medio de licuado a la tarde/noche y luego a ciertas
horas exactas me da la migraña es raro.
Pero para tener en cuenta pq la semana pasada ya habia atribuido estar
cefaleico al licuado.
No diria al licuado sino a los ingredientes viejos, tiraria todo y
compraria nuevos por las dudas. y compraria verduras para probar si
hay desagote por otro lado. 
Por la experiencia del dia de hoy en la cual transcurrio todo el dia
bien, salvo con un pequeño brote al llegar al marques que fue sofocado
cuando me tome un ibu creo que puede ser el tema licuado. (No creo que
sea el segundo factor corregido que fue el partir la dosis de
topiramato y menos el tercer factor no corregido que fue no haber
tomado estos tres dias la sublingual)
** [2017-10-21 sáb]
felizmente anoche corte la racha, en realidad ayer se corto. me tome
un ibu ayer tarde al llegar aca y un ibu esta mañana pienso que el
problema radico en intoxicacion por licuado, o sea por elementos
viejos del licuado.
** [2017-10-22 dom]
anoche dormi nuevamente bastante normal, con un poquito de cefalea sin
haber tomado ningun preventivo y me tome un ibu solo al levantarme. La
manana transcurre normal y pinta un domingo bastante fierito de
aquellos para el olvido total.
en realidad la tarde derivo en migraña total. me tome un ibu y luego
un <<nar>> y no surtio efecto. Segui con la actividad, me vine al dpto
y estoy haciendo las cosas pq creo que si me tiro en la cama va a ser
peor, al menos estoy planchando, voy a pasar los datos y me voy a
bañar, y veo.
** [2017-10-23 lun]
es obvia la diferencia que hubo en las dos ultimas noches con relacion
a la semana pasada sin la sublingual, no solo la calidad del sueño y
descanso sino como me levanto.
** [2017-10-25 mié]
anoche me fui a dormir un poco cefaleico y pense que iba a despertar
con <<nar>> y me preguntaba que me habia llevado a eso si el exceso de
un capitulo de mas de la serie o el dia demasiado largo o que no habia
cenado pero en realidad dormi bien y limpio bien la noche la cabeza y
me desperte bien y tire hasta pasado el medio dia sin problemas eso
que estoy cagado de hambre y me fui al patio olmos a la carrera a
sacarme los rx.
** [2017-10-27 vie]
hoy el dolor nacio luego del estres en oficina, y todo el dia tuve muy
sonolento pq me falta sueno.

** [2017-10-28 sáb]
nuevamente entra el factor nervioso, y cuando hay estres viene la
necesidad de tomar un analgesico, hoy que cuando me levante no habia
tomado nada, lo termine tomando cuando el estres de la situacion subio
a cierto nivel.

** [2017-10-31 mar]
anoche pense que iba a tener que tomar un nar pq no tenia ibu, pense
en salir a comprar, y me la aguante y me fue bien al final, aunque
ahora recien tomado no he mejorado nada. Pero sali del pozo de la
semana pasada con la crisis migrañosa que me causo creo el licuado.
** [2017-11-06 lun]
de un finde en general malo y encima cene pesado anoche desperte con
un dolor turbio aunque no declarado y como tenia supercompromiso hoy
con el aviso me tome el <<nar>> sino no lo tomaba.
** [2017-11-08 mié]
anoche desperte con dolor que no cedio con el ibu, y sospecho a la
cena. Muy tarde para meterse a las 22.30hs esos ravioles la
salteña. Tome un ibu a las 3 y un <<nar>> a las 4.20 y me levante mas
o menos bien, pero no tan limpiado como el lunes.
** [2017-11-10 vie]

esta mañana tome un ibu y ahora decido un <<nar>> pq la cefalea pinta
fuerte y tengo 3.15hs de labor por delante y la oficina sin aire o a
mi me parece. Lo cual es una pelotudez mayuscula. Pero esos mas que
todo son signos panicosos. De ultima podriamos intercambiar el lugar y
vemos.
Mejoro bastante y a las dos horas se puede decir que no hay dolor a
nivel cabeza a pesar de la atmosfera cerrada y de haber seguido
trabajando.
*
** [2017-11-12 dom]
termine con un <<nar>> pienso que por estress combinando el finde con
la presentacion del yerno y el compromiso del almuerzo en casa del
fede el domingo y una cefalea refractaria a medianoche en el marques
sin saber como tratarla me decidi cortar por lo sano y tomar un nar y
antes de ir al almuerzo un ibu y anduve joya todo el domingo incluida
la noche y la mañana del lunes.
** [2017-11-13 lun]
cefalea de oficina quizas por estres todo el dia aca adentro con el
aire y extremo estress que obliga a estar templando el animo.
Cedo a <<nar>> en un momento peligroso pq es la segunda al hilo en dia
habil de oficina, a pesar de que el encierro, la claustrofofia, la
falta de aire, y el hambre  etc no se presentaron, pero el estres por el caso 765
es muy grande casi comparado al caso 747 y produce la migraña estoy
seguro mas alla de las bronquitas menores con los otros chicos. 
** [2017-11-14 mar]
hoy felizmente corte la racha del nar en oficina y el nar de ayer
logro disipar por 24hs el malestar.
No obstante los multiples otros malestares persisten pero es bueno que
se haya frenado esa racha.

** [2017-11-15 mié]
esta madrugada 3 am desperte cefaleico encerrado con aire encendido
abombado y tome un <<nar>>. Limpio bastante bien,lo unico que causo
mucho malestar estomacal luego con acidez y mucha produccion de saliva
a la media hora que casi vomito. La noche anterior comi escabeche con
yamani aderezado con mostaza, obvio ambas cosas acidas, y medio
nervioson, a pesar de que me habia acomodado un poco, que habia
logrado cierto nivel de encuadre en mi dpto y en mis planes no le di a
la cena la paz y tranquilidad que era necesario.

** [2017-11-16 jue]
decidi que no tomo mas ibuprofeno, pq habia caido en la toma
preventiva, y en todas las variantes de toma que el migral tiene, por
eso la toma diaria, y con lo malo que es el ibuprofeno no me conviene
si aparte estoy teniendo ese nivel de naratriptan, o sea que o bien
subo el topi y aguanto la tormenta con naratriptan solo o bien evito
totalmente el TACC. y otros conservantes.
veremos que pasa.
Harto!!!!! del dolorcillo y deseando que se me disparara para tomarme
el <<nar>> o se fuera, me tome el nar a 15.40 y veremos. Esta
acompañado de tension muscular cervical extrema, de gran nerviosismo y
de pensamientos suicidas. Creo que si tuviera un chumbo este seria el
momento de pegarse un cuetazo y que la sangre corriera por la
pantalla.
Una hora de tomado y no cede la gran puta y yo lideando aca con los
tipos mas pelotudos que me pueda haber tocado en suerte los ultimos
años.
Pasaron 3 horas y no se me fue el dolor cien por cien y el embole que
tengo es mayusculo, asi no se me va a ir.

** [2017-11-17 vie]
mal dos dias de <<nar>> refractario, no hace nada pero la presion es
muy grande dentro y fuera del trabajo, es indescriptible.

** [2017-11-18 sáb]
a las 24.42min me tomo otro <<nar>> a las 12.02 con fuerte jaqueca
ambos lados molleral habia dormido bien desperte normal y desayune dos
huevos con cinco almendras  y fui al mercado y eso si fueron dos horas
de gran patetismo en los pensamientos, que se dispararon ni bien
comence a caminar (que comence bien despacito y dispuesto a ejercitar
la espalda sin forzar) se disparo viendo una gente en un auto que se
iba al campo pienso y alli salto el fusible de yo-sin-auto y alli
comenzaron los malos pensamientos que no cejaron en dos horas y
patetismo de no querer comprar nada en el mercado parte por no querer
hacer cola y no esperar parte por no saber bien que comprar y parte
por no gastar, salve la jornada de pedo con una boliviana chota que
compre unos tomates chomazos y dos paltas duras casi casi peor que la
verdu frente a cañada y unos limones horribles, o sea una compra
malisima, salvo el quesillo que compre y la panceta en la
fiambreria. Menos mal que calce la mochila en ambos lados y no me
lesiono la espalda la vuelta al contrario me hizo bien, pero luego me
fui al light para comprar la bolsita red y al llegar se desato la
jaqueca mal. Y el nar fue refractario de nuevo. llevaba una hora y
alli pense que si no era problema de haber dejado el ibu. y decidi
provisionalmente volver a tomar ibu al menos hasta salir de esta
crisis total en la cual estoy, para no agregar factores que no vienen
al caso. O sea no es momento de hacerme el macho y dejar el ibu si eso
va a hacer un caos, pq estoy en un estado terminal de espalda en la
cual tengo una ventana de accion de no mas de una hora, y una ventana
de accion en cabeza de no mas de dos horas, con un nar puro que no
hace nada. al menos con los 42 ibus y los 10 nar (tomado de 14/10 a
14/11) al menos safe de la cabeza.
Ojo tambien dude de que eran los huevos que estaba consumiendo los que
habian activado la migraña feroz, pero creo que no o no esta bien
claro por los registros aun.
** [2017-11-19 dom]
se repitio practicamente el patron de ayer o sea desayune dos huevos
fritos en oliva y a las dos horas mas o menos se desato la migrana que
el <<nar>> no pudo abortar. En este caso comi igual y recien a las
tres horas o cuatro horas se limpio y eso que habia tenido un ibu
"preventivo" a las 11.30hs incluso antes de desayunar que no influyo en
nada. Pense cuando era inutil el nar en tomarme un segundo ibu pero no
lo hice por vagancia e inconveniencia del lugar y mejor pq termine
perfecto la tarde-noche sin dolor y sin un segundo ibu con una mateada
amarga con almendras, y eso lo repeti de desayuno el lunes.
Hay que notar que desde la tarde del sabado y ya desde que me levante
el domingo cedio un poco el malestar mayusculo de la columna que me
tuvo a maltraer en el dpto. Pero sigo con la dieta estricta en cierta
forma.
** [2017-11-20 lun]
hoy no desayune huevos como los ultimos dos dias y no tuve la migrana
a la misma hora y a la misma intensidad hasta ahora. Es mas ni
siquiera tome ibu. Desayune mate amargo con 15 almendras y almorce
hamburguesas y ensalada hervida. Se eleva el factor sospecha para los
huevos.
Almorce y me acoste a dormir una siestita luego de pasar unos papeles
a la notebook, no estaba muy comodo y me dormi y tipo 17 me levante
con cefalea, la trate de solventar con un ibu y una mateada amarga,
sentia una necesidad de comer algo dulce. Me comi un par de almendras
y le dije a ih que se hiciera unos pururu una posibilidad para no
salirse de la dieta sin tacc. Las siguientes dos horas mas o menos
fueron pasables y el dolor cedio y luego volvio y ahi decido irme. o
sea venirme. Me cambio pido el remi y me vengo con un N2 sin
problemas, desarmo maletas y comienzo a pasar papeles pasa una hora y
la jaqueca se va transformando en migrañosa izquierda hemicraneal
frontal palpitante y me tomo un migral luego de 30hs25min de haber
tomado el <<nar>>.
Tomo la decision de pasarme al migral pq ya esta visto que el nar no
va mas, que el incremento del dolor en esta pauta casi diaria, aun
habiendo evitado el huevo, tiene que ver quiza con desintoxicacion de
alguna manera, pq se puede decir que las ultimas 48 hs no tuve malos
pensamientos y las ultimas 72 hs no tuve estres importante, incluso el
dolor intenso de espalda cedio. 
Creo que una vez que se asiente la pauta de alimento nueva cederan los
dolores y no creo que haya tiempo para enviciarme con el migral, eso
llevaria unos dos meses. De todos modos como voy voy camino a una
crisis del naratriptan, crisis aguda pq me impediria trabajar. Ojala
que prenda el migral y corte el dolor, al menos puedo repetirlo o sea
tomar dos o tres de ultima, o sea estoy en terreno conocido, pero con
el nar no y estoy muy acotado. 
Aca yo pienso que debemos cambiar totalmente y a ello vamos asi que no
hay que tener miedo.
Para bien o para mal el migral fue efectivo, saco en tiempo y forma el
dolor y me voy a dormir con la esperanza de normalizarme lo mas pronto
posible. Espero no equivocarme de estrategia.
** [2017-11-21 mar]
me levante bien, me bañe y tenia cita con ramiro a las 10hs y luego el
plan era ir al patio olmos a ver la traumatologa que al final atendia
a la tarde, el plan b no lo hice que era comprar ropa. Me volvi pero
positivo y almorce bien, habia desayunado licuado, mientras tomaba el
primer vaso pensaba que no iba a alcanzar pq estaba muy liquido pero
ya en el final del vaso estaba saciado y el medio vaso sirvio hasta el
mediodia. El almuerzo fue bife con tomate y palta y mijo, el mijo
estuvo muy bueno. La jornada laboral tuvo optima, no senti cansancio
ni presion de ningun tipo, luego al volver previo haberme desviado por
una picardia me senti un poquito cansado y luego hice el trabajazo de
la cocina [[file:dia-general.org::*%5B2017-11-21%20mar%5D][limpie la mesada podrida]] y me hice una cena de antologia y
aqui estoy dispuesto a pasar los papeles para que no me pese mañana el
dia. 
** [2017-11-22 mié]
aunque anoche comi copiosamente el menu ya descripto dormi bien y
recien tipo 5 o 6 aparecieron las primeras molestias y decidi tomarme
tipo 7 un ibu q ya para las 8 limpio completamente la molestia, como
pasaba antes. La mañana transcurrio bien, bastante tranquila y
energica, pasando papeles me llevo mas de dos horas y fui al banco y
de alli al volver pase directo dos cuadras mas para comprar aceite de
coco y luego descanse un poquito y me hice un buen almuerzo nuevamente
con mijo sardinas y palta y me vine a la oficina.
Y las cuatro horas de la oficina trabaje mucho sin movimiento, pero
produje un monton, casi adelante todo el trabajo que me lleve a la
casa, o sea que no tengo que hacer nada en la casa y tengo hecho lo de
mañana al llegar (los recibos) y ya hice un tema de vaciamiento de mueble.
** [2017-11-23 jue]
anoche me tome un ibu puse a las 1am pero no recuerdo si fue a la 1 o
a las 3 am. y me levante bien, pero medio vago hoy con no tanta
energia como ayer, y aunque fui a rapipago y a la verduleria y me fue
bien comprando luego me tire en sillon a hablar con ih una hora y
perdi ganas de hacer cosas, luego me puse a acomodar living un rato e
hice algo pero me dolia un poco la columna y se me termino haciendo
tarde para comer y comi rico pero contrareloj apurado y aca el
ambiente tenso por culpa de los pelotuditos que vienen temprano a
rendir, cosa que se va a acabar pronto, y ahora recien me termino
tomando otro ibu eso que estoy en un ambiente mas o menos tenso, mas o
menos caldeado con 37 grados sin aire y con calor pq no prendemos el
aire hace unos tres dias.  Pero creo que la dieta va funcionando
bien. en cierta forma tiene almuerzo/cena y licuado en el medio. 
pasando las horas no fue efectivo el ibu, pienso que por el encierro
casi cinco horas de intenso calor aca sin aire, mas que aire
acondicionado creo que se necesitaria un extractor que recirculara el
aire viciado.  Pero pronto lo vamos a tener.
Llegue a mi casa y parecia crecer en virulencia la urgencia del
migral, y en cierto momento pense que emergian viejas estructuras del
migral o sea el deseo de tomar migral por tomarlo por sentir ese
alivio, lo que si estaba muy cansado, entonces me acoste a reposar un
poco y fui safando poco a poco de la necesidad de tomar migral y no
tome y tampoco ibu, y dormi bien y me levante bien y tuve una mañana
bien el viernes a la mañana y recien me tomo un ibu mas que todo pq se
me hace insoportable el dolor de espalda. 
Es que esta mañana me levante y vine a la oficina y luego cuando me
relajaba me tuve que ir al banco y luego de un breve momento venir a
la oficina y el tiron es largo pq al estar expuesto aca adelante se
hace mas tenso y cansador todo, creo que estando atras va a ser todo
mas facil.
Creo que lo que fue fundamental para el alivio de las ultimas 24hs fue
el litro de agua de lino como desinflamante no queda otra. Pq estando
yo cefaleico, tome por tomar medio vaso cada media hora mas o menos y
fui despejandome.
** [2017-11-25 sáb]
me levante bien y fui a la oficina temprano una hora y media
acomodando hasta que llegaron ellos y con el aire prendido, a las 11
tome un ibu medio preventivo y luego la cefalea fue creciendo y a las
12 decidi tomarme un migral. No se si en situacion normal lo hubiese
tomado. Creo que me apure un poco no soporte ni siquiera un cachito de
presion y al menos actuo rapido y bien aun siguiendo la actividad en
las mismas condiciones. Segui trabajando hasta las 14.30 que me vine a
comer. Me reafirmo en la dieta sin TACC y creo que debo eliminar la
avena como factor inflamante y mas cruda. Creo que una dieta sin
gluten definitiva va a ser positiva en el futuro. Y el lino como
factor desinflamante. Y el frio intenso del aire como factor que
pudiera llevar a la cefalea (estudiarlo)
** [2017-11-26 dom]
repeti el patron de ayer, en oficina luego de dormir mal anoche pq me
desperte a las 6 y no me pude volver a dormir, me tomo un ibu tipo
11hs mas que todo preventivo y luego tipo mediodia cuando se fue Fede
a eso de las 13 y pico acuciaba el dolor como para algo mas. Y me dije
seria catastrofico un segundo migral consecutivo en estas
circunstancias.
Decidi comer pq tenia hambre y me hice con todo, total pensaba lo
mismo iba terminar tomando algo, me hice dos "bifes" de mijo fritos,
idem una rodaja hervida de calabaza que me habia quedado, 4 huevitos
de codorniz, y ensalada de tomate y una palta, todo exquisito y luego
me acoste me puse una SL y dormi una siesta de mas de dos horas y
desperte con la recidiva del dolor, no hice nada me levante, tome
lino, y se fue el dolor. Me fui al disco compre, y me bañe y aca
estoy, por ahora lo saque de vista.
** [2017-11-27 lun]
al final me desperte a la una de la mañana con una cefalea importante
y no supe que hacer y tome un <<migral>> y no me causo insomnio pq
estoy tomando clonagin, esa noche tome uno y medio despues de la
despertada de las cinco, y el lunes transcurrio limpio total de ibu y
de dolor y de molestias.
** [2017-11-28 mar]
hoy me levante bien incluso con pocas molestias a nivel espalda, que
desde que hago los estiramientos van disminuyendo a pesar de que
cumplo las funciones igual (pe. lavo platos) y que camino como bestia
pq voy y vengo con esto de la oficina, fueron cuatro dias seguidos de
estar atras de la parecita. Lo que si me note en oficina muy cansado y
me tome un ibu mas que todo por el factor animico que estaba pasando y
luego que paso todo, que pinto, se fue, pague y termino una etapa, me
active y arme la compu, la hice funcionar y me vine, podria si hubiera
querido hacer mas pero me hubiera quedado sin tiempo.
aca hay olor a pintura y tensiones. algunas las voy a sacar otras van
a estar siempre. me tomo un segundo ibu a las 15hs y catastroficamente
me produce un incremento del dolor jaquecoso para los estandares del
trabajo en este ambiente cerrado y maxime con el tener que estar
lidiando con el tema 765. Y tomo un <<migral>>!!.

** [2017-11-30 jue]
ayer se repitio el patron, somnolencia, hartazgo, nerviosismo, y
encierro hicieron que tomara un ibu a las 16hs y que luego se
aumentara el riesgo de que se incrementara el dolor y terminara en
migral, pero paso.
Creo que necesito la cerradura pomo urgente para que pueda irme
automatico sin cerrar que se trabe sola y luego que se abra facil cosa
de poder irme un rato afuera cuando me sienta encerrado.
Al final el ibu me domino el dolor y pude ir a la reunion que duro
hasta las 22hs en un ambiente encerrado, sin problemas jaquecosos
luego cene liviano y dormi muy bien.

** [2017-12-01 vie]
recien a las 14.30hs tomo un ibu por cefalea de apuro, pero pienso que
se va a controlar. Y fue creciendo (hoy comi 4 huevitos de codorniz)
mas tensiones mas trabajar ahi mismo. Crecio el dolor de cabeza y me
tome un migral 
Ya a las 2hs esta bastante limpio el sistema e incluso me muestro
animoso, parte por la charla politica con la Elva que me animo a mas
lecturas y a esforzarme mas en el trabajo.

** [2017-12-04 lun]
el finde entero lo pase en el marques, fue como haber pasado un finde
en una cabaña de viernes a la noche a lunes a la mañana. Por la
tranquilidad con la que dormi, por como le dimos, vimos unas cuantas
pelis y cumpli el regimen sin tacc y sin azucar a rajatabla. No lleve
la notebook y practicamente no hable de negocios pq el tema que me
ocupaba era otro, era en realidad las lecturas de la parte alimentaria
y me distraje con las pelis. Solo me tome un ibu el domingo cuando
pense que me aumentaba el dolorcillo y me tome un par de tes de
romero. y luego desaparecio el vestigio del dolor.

** [2017-12-05 mar]
ya comence mal con la pintada. pero no quiero que me siente mal, sino
que al reves considerar que esto es parte de lo que yo quiero hacer y
parte de lo que me va a beneficiar.
Luego del suceso braian parece que los nervios se tensaron y quede
bien animicamente y lo cefaleico se fue, pero el transcurrir de las
horas termina por aburrirme y cansarme aca abajo tanto el encierro
como la postura. Pero al menos se limpio lo cefaleico.

** [2017-12-06 mié]
hoy con el tema levantarse venir a ofi etc, sentirse desgraciado, etc,
termine con una migraña. Y justo empece a contestar el aviso por wapp
y me motive y me tome un migral, que limpio el dolor, y me vine, y a
la vez fantasie con una idea mientras de ser mochilero, o sea de
vacacionar vagando, y luego comprarme el equipo y ser mochilero, pero
en el fondo me di cuenta que no lo voy a poder hacer pq no me da el
cuero para hacer eso pq no soy de esa clase de persona. Pero podria
empezar por caminar mas e incluso comprarme unas reebok de trekking
como las que marque para caminar largos trechos y meterle cada vez mas
cuadras hasta llegar en lo posible a irme caminando los fines de
semana al marques. Eso seria un buen ejercicio. Incluso con la mochila
de 40 lts encima puesta para ir preparando el cuerpo a la faena. 
Luego de esto tuve una idea genial, lo cual es una muestra de que si
uno esta libre puede encontrar soluciones a los problemas que sean
mejores que estando atado a labores rutinarias.
Un poco me hizo mal el olor a pintura, me volvi y en casa me siento
que la cefalea vuelve y me ronda siendo que es dia que ya tome un
migral y se tendria que dejar de joder por largo rato.

** [2017-12-07 jue]
tomo migral por el desborde y encima no limpia y es resciliente, creo
que es el olor a pintura y tomo ibu a la hora sobre el migral

** [2017-12-10 dom]
tome uno en plena fiesta y preventivo casi, creo que justificado, pero
me la banque muy bien eso que habia tomado bastante vino tintillo.

** [2017-12-13 mié]
ayer, anoche y esta mañana estoy en un estado cefaleico mas o menos
leve, ayer mas acentuado pero con suerte se modero con el ibu, como ha
pasado otras tardes. He aplicado el concepto de ir con calma y
dedicarme a fondo a lo que estoy haciendo en ese momento sin
preocuparme por todo lo pendiente o lo de alrededor, y ha
funcionado. P.e. ahora por lo pronto en la mañana lo unico que me
preocupa seria capacitar a las chicas en el trabajo.
Me pongo cefaleico despues de las 14 pq me agoto con el curso y no
como en mi casa y me quedo directo.
y termino con un migral, fue un dia de mierda con respecto a suspender
el tema de la regularidad alimenticia.

** [2017-12-15 vie]
hoy estoy cefaleico y lamentablemente tomo migral por una cefaleita de
morondanga pq ya el migral me gano la batalla sicologica, como me la
gano netflix, como me la va a ganar la azucar y el gluten. 
Pero noto que el nerviosismo era por las chicas nuevas, y por la
mañana agitada con lo que tenia que hacer a nivel bancario.

** [2017-12-18 lun]
Felizmente va terminando el año, pero en el fondo se renota que uno
toma ya sea ibu o algo mas fuerte cuando tiene tensiones inmanejables
y en el medio esta cefaleico.

** [2017-12-19 mar]
vengo cefaleico desde ayer, y muy agotado. hoy fui llegue a las 11
repose me bañe, comi bien, pero comi un huevo, y el olor a pintura
tambien hace lo suyo. tome el segundo ibu al pedo tomo un migral
despues de 96hs del anterior. Ojala se acabe este olor de mierda.

** [2017-12-21 jue]
anoche tome un ibu medio al vicio creo, y ahora lo tome medio
preventivo pq el olor a pintura me hace medio bosta.
y al volver a la casa me tome otro ibu para paliar el estado y me
mejore por lo menos safe de la situacion, incluso pq me acomode en
cuanto a lo que pienso hacer.

** [2017-12-22 vie]
hoy pase un poco de calor en la mañana y perdi tiempo viniendo al
centro por causa de la monica y no pude reposar bastante
tuve que tomar un migral pq no tuve paciencia en esperar el ibu y es
un dia agitado por ser el cierre del año, y eso me lleva a tomar el migral

** [2017-12-26 mar]
todo este finde navideño incluido tomar vino tinto dos veces, lo pase
sin migral y eso que animicamente no estuve del todo bien. Y no pude
comer todo lo que necesito. Esta bien que la salida de la dieta fue
minima. Solo el postre breve el 24 y la ensalada de fruta el 25 que
tenia azucar y un poco de rusa con mayonesa. El pollo que es carne no
me gusto y me cayo mal.

** [2017-12-28 jue]
hoy luego del dia de ayer que enfrente cansancio inusual y luego del
llamado del Fede en donde acomodamos lo que vamos a hacer y hoy que
pienso que va a haber estres, creo que caigo en un estado cefaleico
que el ibu no lo paro a pesar de que lo tome hace 4.30hs. 

** [2017-12-29 vie]
sin saber porque se desencadeno  una cefalea fuerte que necesito
migral a pesar que no llevo 24hs del ultimo y tuve que tomar.
No estoy nervioso, al menos por fuera, salvo que la cami se va mañana
y las cosas con ih no estan claras pero al menos se alivio un poco el
frente aca en la oficina.

** [2018-01-03 mié]
ayer el primero que me tomo antes de ir a dormir, y si descubro algo
que se ha repetido muchas veces, y es que el segundo ibu cuando el
dolor esta declarado y vamos rumbo a un migral o antes ibamos rumbo a
un nar es al pedo, no sirve de nada y recarga el estomago y el higado
pq lo mismo uno se va a tomar lo otro.

** [2018-01-07 dom]
venia bien con un ibu por dia, pero el domingo me mato la tension, la
ida al aeropuerto bien, pq a pesar del planton, el hecho que hubiera
aterrizado ahi mismo el avion fue todo joya, pero luego la tension del
quilombo, y muchisimo mas la tension que no salia la Cami, y luego la
tension de la cabina del estacionamiento y luego la tension de la casa
con la explosion de la Cami...
Y estando afuera charlando con el Fede y eso que ya se habia
distendido el tema con la Cami, me empezo una migraña que parecia
bomba y me tome un migral, y como la comida estaba ahi al toque se
aborto enseguida.

** [2018-01-10 mié]
ayer y hoy he estado cefaleico y felizmente pude safar con un segundo
ibu en casa. Hoy mande a lesta a comprar una caja a las 10hs y ahi
mismo me tome cuando me empezaba a joder en la oficina y luego se me
paso bien, y recien ahora luego de una densa siesta  de asadito de
bocado y no saber si iba a hacer algo productivo a la tarde safe y
recien tome hace un rato.

** [2018-01-14 dom]
anoche siendo que venia de un mal fin de semana y ya venia con dos
ibus y estaba al limite y habia tenido mucho de netflix y me fui a
dormir con 1.5 clonagin y me dije mejor si viene la alta migraña asi
me tomo el migral y al final me dormi y desaparecio todo, se esfumo.

** [2018-01-19 vie]
tire sin ibus de lunes a viernes y cai con migral en la madrugada del
viernes a 2 am potenciado por la responsabilidad-presion de aviso que
al final termino siendo una mierda pq no vino sino solo uno.
Pero la noche anterior es una presion, no tuve cefaleico esos cuatro
dias a pesar de todas las presiones personales que tuve, y recien
cuando se "destapo la olla o se hizo publico que yo estaba en nirvana,
cosa que hasta ese momento solo lo sabia yo solo" caigo en migraña el
viernes 2 am y luego el sabado a las 15hs

** [2018-01-20 sáb]
como adelante el sabado a pesar de mantenerme en mi postura sufre
muchos embates y nervios y a las 15hs luego de almorzar y acostarme
una siesta sufri una migraña y me tome un migral que no sirvio y me
salvo que me fui a la oficina con fede y tuve con el hasta las 20.30hs
casi.

** [2018-01-22 lun]
mal dia hoy para la cefalea, empece mal el dia pensando que no tenia
migral y me tome un ibu en oficina que me mejoro, y trabaje con gusto
en la oficina hasta las 16hs almorzando alla.
Luego me fui a poner el aviso y a comprar la camara y luego al volver
no se que mal emocionalmente me puse la cosa que al llegar a casa ya
estaba mal, y a pesar de la labor cumplida con creses cedi a la toma
del migral. Luego de un capitulo y medio de netflix, y volviendo un
poco la cefalea, me decidi urgente a cambiarme y salir a comprar un
par de cosas que necesitaba con dos salidas cosa de caminar y tomar
aire, y eso me despejo, aunque utilitariamente y no solo por placer pq
no lo haria. Y ya me canse, me faltaba ir a comprar fruta pero mejor
no pq no es buen dia hoy para eso, mejor mañana en el mercado. 

** [2018-01-25 jue]
HOY CATASTROFE PORQUE???? creo que el dia fue estresante desde las 7
am.
y vino la cami, y luego se me demoro el almuerzo, y luego todo,
contribuyo para que me tome el primero que fue resciliente pq no me
relaje.
y esto de la casa me mato mal.
Es un embole mayusculo no poderse relajar en el dpto en verano cuando
a uno le queda una puta cosa por comprar y uno viene con el puto bolso
y no puede entrar al super y entonces uno dice voy a casa y luego
compro. pq uno esta incomodo y luego o bien no baja si se cambia o
bien esta incomodo como hoy y lo mismo se tiene que bajar. La gran
puta.

** [2018-01-31 mié]
el del finde no lo recuerdo, y no lo anote, no se si fue sabado o
domingo, pero ayer tome uno no pq estuviera en crisis severa sino creo
que era constipacion. Y hartazgo y eso se disipo bastante
luteranamente hoy creo. Gracias a la fruta y a los arrozitos. Y hoy no
tome hasta ahora ibus
** [2018-02-20 mar]
ayer tome de emergencia cuando estaba con fede por una jaqueca
incisiva y se me paso, pq pense que era problematico el momento de la
incorporacion de nuevos cobradores. 
** [2018-02-24 sáb]
luego del viernes con el tema de la Sandra en oficina hasta tarde y
comiendo mal dos dias anteriores termine yendome a dormir medio
cefaleico pensando que iba a safar y lo mismo termine tomandome un
migral a la noche a las 4 y durmiendo muy mal
* historial
** migrañas
*** Diario de migrañas fuertes
**** [2016-10-09 dom]                                          :3M:fuerte:
Me tomo el primer migral a las 9hs luego de una noche con molestias y
espera a la mañana para tomar el migral.
No considero que haya sido tardio en ese momento pq no me molesto ni
subio en intensidad. Hice un poco de netbook en cama y luego me
levante y trabaje en la terraza (con viento y sol), luego cuando
llegaba la hora de la comida me puse a trabajar en el patio con la
netbook a contrareloj muy presionado por terminar una secuencia antes
que me llamaran a comer, entonces me sente a comer tensionado y con el
clima beligerante de estos dias con las chicas. En ese momento pense
que necesitaba otro migral, pero no quise arruinar el gusto de la
comida, pero no comi tan feliz como en otras ocasiones.
Justo al terminar el almuerzo me tome otro migral y me quede en el
patio en un sitio mas o menos tranquilo tomando un te y el dolor
subia. Pero no era incapacitante todavia.
Me acuesto un rato y luego decido levantarme a tomar un cafe que tome
con mucha torta y mucho dulce de leche. Y luego de una breve pausa
para dormir que no debo haber dormido mas de diez minutos, bajo a
hacerme un segundo cafe, mientras tanto sigo con la maquina y algunas
frustraciones al medio.
Dentro de esas frustraciones me planteaba el no dispersarme tanto y
focalizarme en solo dos temas.
El dolor subio y se mezclo con un bajon animico pronunciado y un
malestar generalizado.
Alli cuando me acuesto tipo 20.30 y empieza una migraña tipo 8 o 7,
incapacitante hasta para pensar (pero mas por el malestar que por el
dolor punzante). Cuando me lograba dormir me mejoraba un poco, a las
21.30 ih me subio pure de calabazas que pude probar apenas pq estaba
nauseoso. Tome reliveran a las 22.30 y en esas levantadas al baño el
dolor por el movimiento era muy importante, igual que la fotofobia.
Cuando hizo efecto el reliveran me tomo el tercer migral y en los
proximos 45 minutos no experimente ninguna mejoria, acostado sobre el
costado derecho me presionaba mucho la zona del higado, y sobre el
costado izquierdo me presionaba la cabeza donde me dolia.
Quizas una hora despues o dos, ya me mejore quedando solo la resaca
que desaparecio durante la noche.
**** [2016-10-15 sáb]                                      :3M:intermedio:
Hoy desperte a las 4am con fuerte dolor, el clasico y claro dolor
despertador que amerita un migral, tomo y me duermo, siendo
efectivo. Me levanto bien, hago las tareas que habia pensado para el
dia en forma bastante satisfactoria, salvo por dolor intenso en la
espalda pq habia limpiado la oficina. Luego de comer bien (bifes con
cebolla rucula papas), me meto en la compu para instalar un nuevo SO y
el dolor va increscendo hasta hacerse un moderado que ameritaba otro
migral y a eso de las 15hs me lo tomo, se aminora bastante y me echo
una siestita que dormi con dificultad pero dormi, la dificultad fue
por la falta de oscuridad total y por no tener hecha la cama, ya que
necesito si o si ponerme los auriculares, debo haber dormido una hora
en la misma posicion y despierto con un fuerte dolor de nuevo y me
tomo el tercer migral del dia a las 17hs, sin nauseas hasta ahora, y
no espero resolucion ni nada sino que me enfrasco en la compu, y en un
momento de relax cuando miro por la ventana de la cocina, me golpeo
fuertemente la frente, hasta el punto del sangrado, asi que ahora no
se si tengo resaca o dolor del golpe. 
Si bien es cierto que no tuvo la magnitud del domingo pasado, si
podria haberlo ubicado en un comodo 6 en el momento de levantarme que
me impediria las actividades. Y alli decidi ir al medico mañana. En
realidad comenzar a ir a todos los medicos. O sea instalarme en el hp
del patio olmos. o el central si hace falta. 
**** [2016-10-18 mar]                                          :2M:fuerte:
El domingo tomo dos migrales seguidos, me cayo un poco mal la comida
(pollo al disco) y me percato que era tipo cefaleico y cedio bastante
rapido y me bañe y me sente en la terraza y mejore bastante. 
Ayer lunes en la oficina tome dos migrales con separacion de 2 horas
mas o menos y tambien un dolor cefaleico moderado a molesto pero cedio
practicamente cuando volvia a casa. Y hoy fue diferente, tomo los 2
migrales con diferencia de una hora, y recien despues de 5 horas de
haber tomado el ultimo puedo sentarme a escribir esto mas o menos en
la cama. Me volteo, altamente incapacitante creo que a nivel 7, un
poco menos que el domingo 9 pq casi no tuve nauseas. Solo un poco en
la hora de la toma de los migrales, y repeticiones de la comida a
pesar que fue yamani con rucula y quesito. Hace un rato me tome un te
con galletas queso y miel y me fui mejorando paulatinamente. Del
cefaleico parecido a los ultimos dos dias, se fue transformando en
levemente migraico y luego cediendo.
Creo que la causa real es que ya estoy en las ultimas del migral y los
dolores son mas fuertes y descontrolados.
**** [2016-10-26 mié]                                          :2M:fuerte:
Me desperte bien, dentro del malestar que vengo teniendo de tinitus
por asi decirlo, p.e. anoche no dormi con lluvia, y tuve sueños
confusos. Me despierto con el dolorcito insidioso de siempre y me tomo
un migral a las 7 am. Y el malestar no se va y se agrava. Decido tomar
otro migral a las 8am para terminar con el asunto y se me agrava mas,
y empiezo a devenir nauseoso.
14.5/10 la presion, sin hambre, mal, nauseas, casi diria mareos o
confusion. Tenia la presion ridicula de tener que ir a la dgr
(ridicula pq como dijo dyer al final termino siendo menor que lo que
yo imaginaba).
"La catastrofe que tanto te preocupa, a menudo resulta menos horrible
en la realidad, de lo que fue en tu imaginacion"
Cuando fui, pq baje para ir a comprar los remedios y termine yendo por
ratos o cuadras me sentia mejor, pero en realidad me senti mejor que
p.e. lo que estoy ahora a las 12.30 en casa.
Me tome 10mg de corti a las 11.30hs y hasta ahora estoy peor. Me tome
a la misma hora 35 gotas de reliveran y sigo nauseoso, y de pedo tome
un te con dos galletas y queso.
*** Diario de dias 3 Migrales aunque no migrañas fuertes
**** [2016-10-13 jue]                                        :3M:moderado:
   Desperte a la 1 de la mañana y tome un migral con un trago de
   licuado. Y si bien es cierto que pude dormir lo mas bien, cada vez
   que me despertaba sentia molestia, y me decia que ojala la molestia
   no significara un segundo migral, y felizmente llegue a la
   mañana. Luego desayuno y voy a la ofi. Y alli tipo 11hs tomo un
   migral normal como hago siempre, y luego de nuevo en la ofi a la
   tarde siento que el dolor va in crescendo y tipo 16hs tomo otro
   sabiendo que tenia que quedarme hasta las 17 obligadamente. 
   Luego llego a casa en un estado raro, no queria sentarme a
   programar, me sentia saturado, y me hice una merienda frutal con
   manzana, arandanos y frutilla y medio vaso de licuado, previamente
   haberme bañado tranquila y relajadamente, todo esto mientras veia
   la mitad de la pelicula que habia dejado pendiente, y la verdad que
   me relaje bastante, luego me recoste un rato (en realidad el orden
   de estos sucesos ya los olvide pero el resultado grato lo recuerdo)
   la cosa que despues si me sente a programar y la verdad que fue
   altamente productivo el tiempo que estuve, en cierta forma como
   destrabado. Quizas sea que haya aprovechado una base que habia
   hecho en la oficina, pero si me senti como que "fluyo" el trabajo y
   me senti como que podia terminar alli mismo todo el modulo, pero me
   fui a dormir. Esta mañana crei tener un par de puntaditas de nuevo
   en el ojo, aunque no son en el ojo sino en el arco superciliar.
