
Este archivo concentrara todo lo relativo al tema medico
turnos, sintomas, historial etc.

* turnos
* sintomas
** Dolores
*** Testiculos
[2017-09-15 vie] aparecio de repente que yo pense que era premonitorio
de un gran ataque virosico y buscaba las ampollitas y me puse ac, pero
nada, luego lo tuve el sabado a la mañana y se fue.
[2017-09-18 lun] hoy hace un rato vuelvo a sentir pero a nivel
varicocele en el huevo izquierdo, o como una sensacion de hernia, no
como senti el viernes como algo masivo que abarcaba todo el perineo y
casi no me dejaba sentar.
* medicacion
** ibuprofeno
| Fecha            | cnt |
| [2017-09-18 lun] |   2 |
|                  |     |
|                  |     |
|                  |     |
|                  |     |
|                  |     |
|                  |     |
** TODO Cabergolina
SCHEDULED: <2017-09-25 lun .+1w>
- State "DONE"       from "TODO"       [2017-09-18 lun 18:44]
:PROPERTIES:
:STYLE:    habit
:LAST_REPEAT: [2017-09-18 lun 18:44]
:END:




* historial
** migrañas
*** Diario de migrañas fuertes
**** [2016-10-09 dom]                                          :3M:fuerte:
Me tomo el primer migral a las 9hs luego de una noche con molestias y
espera a la mañana para tomar el migral.
No considero que haya sido tardio en ese momento pq no me molesto ni
subio en intensidad. Hice un poco de netbook en cama y luego me
levante y trabaje en la terraza (con viento y sol), luego cuando
llegaba la hora de la comida me puse a trabajar en el patio con la
netbook a contrareloj muy presionado por terminar una secuencia antes
que me llamaran a comer, entonces me sente a comer tensionado y con el
clima beligerante de estos dias con las chicas. En ese momento pense
que necesitaba otro migral, pero no quise arruinar el gusto de la
comida, pero no comi tan feliz como en otras ocasiones.
Justo al terminar el almuerzo me tome otro migral y me quede en el
patio en un sitio mas o menos tranquilo tomando un te y el dolor
subia. Pero no era incapacitante todavia.
Me acuesto un rato y luego decido levantarme a tomar un cafe que tome
con mucha torta y mucho dulce de leche. Y luego de una breve pausa
para dormir que no debo haber dormido mas de diez minutos, bajo a
hacerme un segundo cafe, mientras tanto sigo con la maquina y algunas
frustraciones al medio.
Dentro de esas frustraciones me planteaba el no dispersarme tanto y
focalizarme en solo dos temas.
El dolor subio y se mezclo con un bajon animico pronunciado y un
malestar generalizado.
Alli cuando me acuesto tipo 20.30 y empieza una migraña tipo 8 o 7,
incapacitante hasta para pensar (pero mas por el malestar que por el
dolor punzante). Cuando me lograba dormir me mejoraba un poco, a las
21.30 ih me subio pure de calabazas que pude probar apenas pq estaba
nauseoso. Tome reliveran a las 22.30 y en esas levantadas al baño el
dolor por el movimiento era muy importante, igual que la fotofobia.
Cuando hizo efecto el reliveran me tomo el tercer migral y en los
proximos 45 minutos no experimente ninguna mejoria, acostado sobre el
costado derecho me presionaba mucho la zona del higado, y sobre el
costado izquierdo me presionaba la cabeza donde me dolia.
Quizas una hora despues o dos, ya me mejore quedando solo la resaca
que desaparecio durante la noche.
**** [2016-10-15 sáb]                                      :3M:intermedio:
Hoy desperte a las 4am con fuerte dolor, el clasico y claro dolor
despertador que amerita un migral, tomo y me duermo, siendo
efectivo. Me levanto bien, hago las tareas que habia pensado para el
dia en forma bastante satisfactoria, salvo por dolor intenso en la
espalda pq habia limpiado la oficina. Luego de comer bien (bifes con
cebolla rucula papas), me meto en la compu para instalar un nuevo SO y
el dolor va increscendo hasta hacerse un moderado que ameritaba otro
migral y a eso de las 15hs me lo tomo, se aminora bastante y me echo
una siestita que dormi con dificultad pero dormi, la dificultad fue
por la falta de oscuridad total y por no tener hecha la cama, ya que
necesito si o si ponerme los auriculares, debo haber dormido una hora
en la misma posicion y despierto con un fuerte dolor de nuevo y me
tomo el tercer migral del dia a las 17hs, sin nauseas hasta ahora, y
no espero resolucion ni nada sino que me enfrasco en la compu, y en un
momento de relax cuando miro por la ventana de la cocina, me golpeo
fuertemente la frente, hasta el punto del sangrado, asi que ahora no
se si tengo resaca o dolor del golpe. 
Si bien es cierto que no tuvo la magnitud del domingo pasado, si
podria haberlo ubicado en un comodo 6 en el momento de levantarme que
me impediria las actividades. Y alli decidi ir al medico mañana. En
realidad comenzar a ir a todos los medicos. O sea instalarme en el hp
del patio olmos. o el central si hace falta. 
**** [2016-10-18 mar]                                          :2M:fuerte:
El domingo tomo dos migrales seguidos, me cayo un poco mal la comida
(pollo al disco) y me percato que era tipo cefaleico y cedio bastante
rapido y me bañe y me sente en la terraza y mejore bastante. 
Ayer lunes en la oficina tome dos migrales con separacion de 2 horas
mas o menos y tambien un dolor cefaleico moderado a molesto pero cedio
practicamente cuando volvia a casa. Y hoy fue diferente, tomo los 2
migrales con diferencia de una hora, y recien despues de 5 horas de
haber tomado el ultimo puedo sentarme a escribir esto mas o menos en
la cama. Me volteo, altamente incapacitante creo que a nivel 7, un
poco menos que el domingo 9 pq casi no tuve nauseas. Solo un poco en
la hora de la toma de los migrales, y repeticiones de la comida a
pesar que fue yamani con rucula y quesito. Hace un rato me tome un te
con galletas queso y miel y me fui mejorando paulatinamente. Del
cefaleico parecido a los ultimos dos dias, se fue transformando en
levemente migraico y luego cediendo.
Creo que la causa real es que ya estoy en las ultimas del migral y los
dolores son mas fuertes y descontrolados.
**** [2016-10-26 mié]                                          :2M:fuerte:
Me desperte bien, dentro del malestar que vengo teniendo de tinitus
por asi decirlo, p.e. anoche no dormi con lluvia, y tuve sueños
confusos. Me despierto con el dolorcito insidioso de siempre y me tomo
un migral a las 7 am. Y el malestar no se va y se agrava. Decido tomar
otro migral a las 8am para terminar con el asunto y se me agrava mas,
y empiezo a devenir nauseoso.
14.5/10 la presion, sin hambre, mal, nauseas, casi diria mareos o
confusion. Tenia la presion ridicula de tener que ir a la dgr
(ridicula pq como dijo dyer al final termino siendo menor que lo que
yo imaginaba).
"La catastrofe que tanto te preocupa, a menudo resulta menos horrible
en la realidad, de lo que fue en tu imaginacion"
Cuando fui, pq baje para ir a comprar los remedios y termine yendo por
ratos o cuadras me sentia mejor, pero en realidad me senti mejor que
p.e. lo que estoy ahora a las 12.30 en casa.
Me tome 10mg de corti a las 11.30hs y hasta ahora estoy peor. Me tome
a la misma hora 35 gotas de reliveran y sigo nauseoso, y de pedo tome
un te con dos galletas y queso.
*** Diario de dias 3 Migrales aunque no migrañas fuertes
**** [2016-10-13 jue]                                        :3M:moderado:
   Desperte a la 1 de la mañana y tome un migral con un trago de
   licuado. Y si bien es cierto que pude dormir lo mas bien, cada vez
   que me despertaba sentia molestia, y me decia que ojala la molestia
   no significara un segundo migral, y felizmente llegue a la
   mañana. Luego desayuno y voy a la ofi. Y alli tipo 11hs tomo un
   migral normal como hago siempre, y luego de nuevo en la ofi a la
   tarde siento que el dolor va in crescendo y tipo 16hs tomo otro
   sabiendo que tenia que quedarme hasta las 17 obligadamente. 
   Luego llego a casa en un estado raro, no queria sentarme a
   programar, me sentia saturado, y me hice una merienda frutal con
   manzana, arandanos y frutilla y medio vaso de licuado, previamente
   haberme bañado tranquila y relajadamente, todo esto mientras veia
   la mitad de la pelicula que habia dejado pendiente, y la verdad que
   me relaje bastante, luego me recoste un rato (en realidad el orden
   de estos sucesos ya los olvide pero el resultado grato lo recuerdo)
   la cosa que despues si me sente a programar y la verdad que fue
   altamente productivo el tiempo que estuve, en cierta forma como
   destrabado. Quizas sea que haya aprovechado una base que habia
   hecho en la oficina, pero si me senti como que "fluyo" el trabajo y
   me senti como que podia terminar alli mismo todo el modulo, pero me
   fui a dormir. Esta mañana crei tener un par de puntaditas de nuevo
   en el ojo, aunque no son en el ojo sino en el arco superciliar.

