
Este archivo concentrara todo lo relativo al tema medico
turnos, sintomas, historial etc.

* turnos [4/6]
** DONE 16.30 MEUBRY, SOLANGE DEL VALLE traumatologia 
SCHEDULED: <2017-09-26 mar>
- State "DONE"       from "TODO"       [2017-09-26 mar 19:16]


*y* TODO 12.40 Romero William
SCHEDULED: <2017-11-08 mié>
** TODO Dra Banus Maria Victoria 18hs 
SCHEDULED: <2017-11-30 jue>
** DONE radiografias MEUBRY, SOLANGE DEL VALLE traumatologia 
DEADLINE: <2017-10-25 mié> SCHEDULED: <2017-09-30 sáb>
- State "DONE"       from "TODO"       [2017-10-25 mié 12:49]

** DONE analisis Romero William
SCHEDULED: <2017-09-30 sáb>
- State "DONE"       from "TODO"       [2017-09-29 vie 12:00]
** DONE sacar turno endocrinologia
SCHEDULED: <2017-09-27 mié>
- State "DONE"       from "TODO"       [2017-09-27 mié 19:34]
* sintomas
** Dolores
*** Testiculos
[2017-09-15 vie] aparecio de repente que yo pense que era premonitorio
de un gran ataque virosico y buscaba las ampollitas y me puse ac, pero
nada, luego lo tuve el sabado a la mañana y se fue.
Creo que la causa fue el boxer ajustado.
[2017-09-18 lun] hoy hace un rato vuelvo a sentir pero a nivel
varicocele en el huevo izquierdo, o como una sensacion de hernia, no
como senti el viernes como algo masivo que abarcaba todo el perineo y
casi no me dejaba sentar.
[2017-10-02 lun] en oficina senti como me apretaba el huevo derecho el
boxer y de nuevo no se si es causa o efecto, o sea si el boxer es el
causante o siento el boxer cuando tengo el dolor y lo sentiria igual
con slip
*** Implantes
[2017-09-19 mar] hoy tengo bastantes molestias en en los implantes
izquierdos en ambos, mas que todo en el de mas atras.
Creo que la causa fue un cepillado demasiado intenso en la zona
lastimada de los implantes.
*** presion en brazos
[2017-09-21 jue] siento presion en los brazos a la altura del codo de
la parte de adentro como si tuviera una banda elastica que me
oprimiera, mas que todo el derecho y muchisimo menos el izq casi nada,
asi casi como dos horas que lo tengo y casi se me irradia a dolor en
la mano derecha al escribir en el teclado. y por momentos en la
oficina senti como que los ojos no enfocaban bien y se deslumbraban
con la pantalla, pero recien me vine caminando bien hasta aca, solo
tengo esto y un poco de rareza en la cabeza.
Creo que la causa es el ejercicio de brazos.
*** Temblores
[2017-09-25 lun] si bien es cierto que hace dos años que los padezco
hoy tuve un ataque bastante feo en mano izquierda posterior a
levantarme.
Y tengo la sensacion que habia cesado el sintoma por mucho tiempo y se
volvio a complicar el ultimo tiempo.
*** retorcijones
[2017-10-02 lun] la noche anterior safe con oleo31 y a la mañana
volvieron y me tome una pastilla de carbon y no jodio mas enla
oficina.
*** cadera derecha
[2017-10-05 jue] un dolor que aparecio hace una semana y que me impide
cruzar la pierna del lado derecho y lo sospecho que es el sillon de la
oficina.
[2017-10-31 mar] este ultimo fin de semana estuvo muy inflamado la
cadera incluso me parecio que se propagaba a la otra. Pienso que se
debe en parte a que la mala postura en el marques se potencia con la notebook.
[2017-11-14 mar] hoy tuve un choque en puerta del fondo de oficina con
pie derecho que repercutio en cadera derecha inflamada y me hizo
gritar literalmente de dolor, muy feo eso. No le hacen nada los
masajes ni unguentos. Va de mal en peor.
*** espalda
[2017-10-18 mié] muy mucho dolor de espalda, toda la noche, pienso que
la culpa del dolor de anoche la tuvo el sillon. Ahoche me colgue con
tres capitulos de netflix y eso se noto a nivel espalda es peor que la
jornada de sillon con la compu.
[2017-10-31 mar] este ultimo finde tuve un pico de malestar en la
espalda hasta el punto que con oleo31 tuve masajes el domingo en
varias oportunidades y poco alivio tuve, y el domingo a la noche y el
lunes me tome un diclo para aliviar sintomas de inflamacion.
*** acidez extrema
[2017-10-18 mié] hasta el punto de tomar agua para pasar la noche, me
paso hace dos noches en el marques y hoy tome un gastromax a la mañana
como primer medicamento
*** polialquria
[2017-10-18 mié] ya a nivel molesto, tener que levantarme tantas veces
de noche siendo que hace unas cuantas noches habia logrado cierto equilibrio.
*** nerviosismo
[2017-11-02 jue] hoy me tuve que ir al dpto a buscar SL para ponerme
una y soportar la jornada, pq vengo desde ayer no soportando los
embates normales del trabajo.
* medicacion
** ibuprofeno
| Fecha            | cnt | sintomas                    |
|                  |  65 | 0                           |
|------------------+-----+-----------------------------|
| [2017-09-18 lun] |   2 |                             |
| [2017-09-19 mar] |   2 | dolor molesto toda la tarde |
| [2017-09-20 mié] |   1 | desperte con dolor          |
| [2017-09-21 jue] |   1 |                             |
| [2017-09-22 vie] |   1 | madrugada                   |
| [2017-09-23 sáb] |   0 |                             |
| [2017-09-24 dom] |   1 |                             |
| [2017-09-25 lun] |   1 | 14hs en dpto                |
| [2017-09-26 mar] |   2 | madrugada y oficina         |
| [2017-09-27 mié] |   1 | madrugada                   |
| [2017-09-28 jue] |   2 | 12/23hs                     |
| [2017-09-29 vie] |   2 | 12hs/22hs                   |
| [2017-09-30 sáb] |   1 | 18hs                        |
| [2017-10-01 dom] |   2 |                             |
| [2017-10-02 lun] |   1 | 19hs                        |
| [2017-10-03 mar] |   2 | 8/15hs                      |
| [2017-10-04 mié] |   1 |                             |
| [2017-10-05 jue] |   1 |                             |
| [2017-10-06 vie] |   2 | 10/18hs                     |
| [2017-10-07 sáb] |   2 | 15/23                       |
| [2017-10-08 dom] |   2 | 10/17                       |
| [2017-10-09 lun] |   1 | 13                          |
| [2017-10-10 mar] |   1 | ?                           |
| [2017-10-11 mié] |   2 | 4am/15hs                    |
| [2017-10-12 jue] |   2 | 4am/22                      |
| [2017-10-13 vie] |   2 | 11.30hs/15.30hs             |
| [2017-10-14 sáb] |   2 | 12/23hs                     |
| [2017-10-15 dom] |   2 | 10/15hs                     |
| [2017-10-16 lun] |   0 |                             |
| [2017-10-17 mar] |   3 | 1.30 am/12hs/20hs           |
| [2017-10-18 mié] |   2 | 11.30/23hs                  |
| [2017-10-19 jue] |   1 | 11                          |
| [2017-10-20 vie] |   1 | 19hs                        |
| [2017-10-21 sáb] |   1 | 10hs                        |
| [2017-10-22 dom] |   2 | 9hs/17hs                    |
| [2017-10-23 lun] |   1 | 11hs                        |
| [2017-10-24 mar] |   2 | 10/23hs                     |
| [2017-10-25 mié] |   1 | 13hs                        |
| [2017-10-26 jue] |   1 | 23hs                        |
| [2017-10-27 vie] |   1 | 15hs                        |
| [2017-10-28 sáb] |   1 | 11hs                        |
| [2017-10-29 dom] |   1 | 11hs                        |
| [2017-10-30 lun] |   1 | 18hs                        |
| [2017-10-31 mar] |   1 | 11hs                        |
| [2017-11-01 mié] |   2 |                             |
| [2017-11-02 jue] |   2 |                             |
| [2017-11-03 vie] |   1 |                             |
| [2017-11-04 sáb] |   1 |                             |
| [2017-11-05 dom] |   1 |                             |
| [2017-11-06 lun] |   1 |                             |
| [2017-11-07 mar] |   1 |                             |
| [2017-11-08 mié] |   1 | 3 am                        |
| [2017-11-09 jue] |   1 |                             |
| [2017-11-10 vie] |   1 |                             |
| [2017-11-11 sáb] |   1 |                             |
| [2017-11-12 dom] |   1 |                             |
| [2017-11-13 lun] |   2 | ambos en oficina            |
| [2017-11-14 mar] |   1 | 21:45hs                     |
| [2017-11-16 jue] |   0 |                             |
| [2017-11-16 jue] |   0 |                             |
|                  |     |                             |
#+TBLFM: @2$2=vsum(@3$2..@>$2)
** naratriptan
| Fecha            | cnt | hora     |
| [2017-09-27 mié] |   1 | 6.30hs   |
| [2017-10-13 vie] |   1 | 18.30hs  |
| [2017-10-15 dom] |   1 | 18.30hs  |
| [2017-10-18 mié] |   1 | 1.30 am  |
| [2017-10-19 jue] |   1 | 4.30 am  |
| [2017-10-20 vie] |   1 | 4.30 am  |
| [2017-10-22 dom] |   1 | 17.30hs  |
| [2017-11-06 lun] |   1 | 3.30 am  |
| [2017-11-08 mié] |   1 | 4.20 am  |
| [2017-11-10 vie] |   1 | 14.45 hs |
| [2017-11-12 dom] |   1 | 3.30 am  |
| [2017-11-13 lun] |   1 | 17.30hs  |
| [2017-11-15 mié] |   1 | 3 am     |
| [2017-11-16 jue] |   1 | 15.40hs  |
| [2017-11-17 vie] |   1 | 11.40hs  |
|                  |     |          |
** gastromax
| fecha            | cnt | horas            |
| [2017-09-27 mié] |   2 | mediodia y noche |
| [2017-10-18 mié] |   1 | mañana           |
** TODO Cabergolina
SCHEDULED: <2017-11-16 jue .+1w>
- State "DONE"       from "TODO"       [2017-11-09 jue 09:13]
- State "DONE"       from "TODO"       [2017-11-02 jue 21:23]
- State "DONE"       from "TODO"       [2017-10-25 mié 20:17]
- State "DONE"       from "TODO"       [2017-10-17 mar 19:58]
- State "DONE"       from "TODO"       [2017-10-09 lun 18:38]
- State "DONE"       from "TODO"       [2017-10-02 lun 22:31]
- State "DONE"       from "TODO"       [2017-09-25 lun 21:25]
- State "DONE"       from "TODO"       [2017-09-18 lun 18:44]
:PROPERTIES:
:LAST_REPEAT: [2017-11-13 lun 09:13]
:END:


** DONE VitC
SCHEDULED: <2017-09-29 vie>
- State "DONE"       from "TODO"       [2017-09-29 vie 19:59]
- State "DONE"       from "TODO"       [2017-09-28 jue 18:02]
- State "DONE"       from "TODO"       [2017-09-27 mié 19:30]
- State "DONE"       from "TODO"       [2017-09-26 mar 19:16]
- State "DONE"       from "TODO"       [2017-09-25 lun 21:25]
- State "DONE"       from "TODO"       [2017-09-24 dom 12:19]
- State "DONE"       from "TODO"       [2017-09-23 sáb 22:29]
- State "DONE"       from "TODO"       [2017-09-22 vie 17:44]
- State "DONE"       from "TODO"       [2017-09-21 jue 19:44]
- State "DONE"       from "TODO"       [2017-09-20 mié 21:58]
:PROPERTIES:
:LAST_REPEAT: [2017-09-29 vie 19:59]
:END:


* cefaleico
** [2017-09-19 mar] 
un dia feucho del dolor desde la mañana, pq desperte con dolor y tome
el primer ibu temprano. Luego el segundo en la ofi misma. Y sali
temprano de la ofi pq pensaba que iba a tener una cefalea molesta, y
luego con el disgusto-desasosiego (ver diario) pero hice lo que dice
el libro, segui con el plan con todo, como un bull, y luego me tome
unos buenos mates, y luego me perdi en la compu en mi silloncito nuevo
y en el medio hice todo el ejercicio y el dolor se limpio totalmente.
** [2017-09-20 mié]
desperte con dolor bastante feucho, tanto que pensaba que iba a
terminar en nar. Tome un ibu a las 4.30hs y luego me levante bien.
** [2017-09-22 vie]
desperte con dolor mas o menos molesto, pero pienso que fue debido a
que comi casi toda la bandeja de una tarta de pollo muy tarde y ahi al
toque me fui a dormir, tome el ibu y me dormi y se fue todo bien, me
levante joya.
** [2017-09-24 dom]
el domingo tome uno a las 12hs medio al pedo, pero por momentos
parecia que era necesario, como paso al final ahora, el lunes que
escribo esto y no lo tomas y no pasa nada. Pq transcurrio el domingo y
no paso nada. Ojo con tomar por safar de situaciones o por arreglar un
dia que parezca nefasto.
** [2017-09-26 mar]
mal desperte con dolor como costumbre luego de la cabergolina, y todo
bien, se fue, me levante y me bañe, y ahora en oficina, luego de una
mañana dificil y sin desayuno me tomo un segundo ibu pq tengo un
punzante en sien izq que espero se vaya. pero pienso que si se va a
ir.
** [2017-09-27 mié]
desperte como todas las noches de este tipo, tomo ibu con yogur, sigo
durmiendo y me despierto de nuevo con un dolor mas intenso y dormido
como estaba decido un <nar> pensando que tenia oficina, pienso que me
acuchilla los compromisos de la oficina, que estoy muy cansado por
eso.
** [2017-09-28 jue]
tuve unos dolorcitos que por momentos me hicieron pensar en tomar algo
mas fuerte o sea que por ahi te parece que se va a ir de
madre. Felizmente anoche que comi bastante y queria irme a hacer el
analisis y no tomar nada a la madrugada no jodio
** [2017-09-29 vie]
por ahi aparecen tipo puntadas de la nada esta bien que no le doy
pausa cuando estoy en la oficina y tambien tendria que tomarme un
ejercicio.
en especial que hago algo de mala postura, que tuve como una hora
poniendo la compu atras muy incomodo.
Lo mismo que ayer la puntadita, y el exceso. No descanso, y sigo y
sigo, pero como me va bien, sigo, y alterno, ejercicios, limpieza,
comida, etc, pero la puntadita sigue y la amenaza sigue y todo el
significante del migral agazapado, ese seguir hasta reventar total
tomo la pastilla y se me va o caigo reventado. no me importa.
** [2017-09-30 sáb]
tomo un ibu postsiestal y preparatorio para lo que vendra esta noche
con los nietos. Al final a pesar de que no habia traido nar, gran
olvido de mi parte, y de haber sido una noche dificil, habia comido
mucho y mal, y me habia acostado ahi nomas, y sentia como que al menos
tenia que tomar otro ibu, hasta pense que haria ante una migraña (me
iba a ir en el auto a buscar el nar), al final dormi tranquilo, no
tome el ibu y se limpio solo el dolor
** [2017-10-01 dom]
ayer pensaba nuevamente que iba a llegar al nar, y antes de acostarme
tome el segundo luego de un domingo que trabaje mucho y no disfrute pq
estuve tenso todo el dia, pq estaba enojado con el Fede a la
distancia. Y al acostarme luego de comer profusamente me agarro
retorcijon fuerte, y tuve que aplicarme profusamente oleo31. 
** [2017-10-03 mar]
molesto un poco en oficina me fui a comer a casa lasagna y volvi con
un poco de dolor.
** [2017-10-06 vie]
no parecia hoy un dia especialmente molesto, pero llegue a casa y me
tome un segundo ibu.
** [2017-10-07 sáb]
hoy tome dos ibus por los implantes
** [2017-10-08 dom]
idem ayer tome dos ibus por implantes, aunque hoy domingo pense por
momentos a la tarde que iba a tomar un nar, pq el segundo ibu en
realidad lo adelante y lo tome por cefaleico y luego se fue todo y
termine por no tomar nada.
** [2017-10-09 lun]
hoy a las 13hs fue por implantes directamente.
** [2017-10-13 vie]
hoy despues de muchos dias me molesta un poco un dolor continuo, y
creo que es la desintoxicacion del cuarto dia de licuado. Es increible
el cambio que el licuado me hizo a nivel estomacal.
Creo que termino tomando <<nar>> pq se habia generado un sistema
nervioso con relacion a la cena de graduacion de la mayra y sumado a
la detox hizo que lo tomara. Creo que si hubiera sido un dia normal en
que con el mismo proceso en marcha me hubiera podido recostar o no
hubiera tenido tension creo que no lo tomaba.
** [2017-10-14 sáb]
hoy estoy patetico he dormido bien anoche luego de un dia o dias de
tension por un compromiso que no se dio y enfrento un finde largo y no
me puedo distender pq estoy patetico para querer estar enfrascado todo
el dia metido en la compu y al final no hago nada en la compu y no me
sirve de nada el resultado pq no rindo y a la vez el cuerpo sufre peor
que en mi casa pq aca el tema posicional es ferozmente feo y ya esta
subiendo a dolor de cabeza y esta afectando a incomodidades.
Al final termine con la netbook hasta casi las 2 am, y a la noche me
tome un ibu casi preventivamente sin necesidad.
** [2017-10-15 dom]
obviamente que me iba a dar la pataleta por los desmanes que
estaba/estoy haciendo y por la comida. Hoy comi como loco y comi esa
porcion de torta de chocolate encima. Pero no tendria porque darme la
cefalea esta no se pq se da todo esto quizas sea por falta de sueño o
que. y tome un segundo ibu apenas volvi del almuerzo y luego me senti
mal cuando me acoste afuera en el futon y me tome un <<nar>> que
termino haciendo efecto bastante rapido y quedo con una leve
resaca. Ayudo que me puse a lavar a mano y colgar la ropa en el aire y
me despeje un poco tomando mates y deje un poco la compu.
Ahora voy a descansar un poco.
** [2017-10-17 mar]
ayer no tome nada pero hoy empece temprano a la una y media con un
ibu, el dia en oficina normal, y a la tarde senti como en los viejos
tiempos la presion de la cefaleica y cuando me decia que yendome a
caminar un poco se me iba a ir, y omiti tomarme un segundo (tercero en
realidad). Luego me olvide pero tome cabergolina y estoy precefaleico
asi que en un rato me tomo otro.
** [2017-10-18 mié]
anoche muy mal me desperte con intensa cefalea para <<nar>> que tome
solo con agua y segui durmiendo y fue efectivo en la noche. Me dio un
poco de miedo pq en la noche anterior habia tomado cabergolina, nunca
habia tomado tan cerca ambos medicamentos.
Pero sigo cefaleico. 
Es que tenemos problemas y tensiones en el trabajo.
** [2017-10-19 jue]
anoche me tome un ibu preventivo pq estoy cefaleico como ahora y dormi
bien hasta las 4.30am que me desperte y tome un <<nar>> y mas o menos
se fue y me levante bien y la mañana fue particularmente intensa y
nerviosa hasta el mediodia que tomo otro ibu y sigo cefaleico.
** [2017-10-20 vie]
el primer triplete desde no se si hubo. anoche a las 1.30hs ya
desperte mal. Decidi esperar total estaba con margen, y ya a las 4.30
decidi tomarlo pq tengo responsabilidad de empresa. Quizas me dije si
hubiera sido fin de semana hubiera probado no tomarlo.
Esta mañana pensando en cosas que habian cambiado, aparte de mayor
tension los ultimos dias, me surgio el licuado como factor que disparo
el tema cefaleico. La semana pasada lo atribui al movimiento
desintoxicante. Pero no logro que haya evacuacion y ello quizas sea un
factor. O quizas las almendras o el lino o la avena sean viejas y
tengan un componente dañino que me provoque migraña. pq como estoy
tomando litro y medio de licuado a la tarde/noche y luego a ciertas
horas exactas me da la migraña es raro.
Pero para tener en cuenta pq la semana pasada ya habia atribuido estar
cefaleico al licuado.
No diria al licuado sino a los ingredientes viejos, tiraria todo y
compraria nuevos por las dudas. y compraria verduras para probar si
hay desagote por otro lado. 
Por la experiencia del dia de hoy en la cual transcurrio todo el dia
bien, salvo con un pequeño brote al llegar al marques que fue sofocado
cuando me tome un ibu creo que puede ser el tema licuado. (No creo que
sea el segundo factor corregido que fue el partir la dosis de
topiramato y menos el tercer factor no corregido que fue no haber
tomado estos tres dias la sublingual)
** [2017-10-21 sáb]
felizmente anoche corte la racha, en realidad ayer se corto. me tome
un ibu ayer tarde al llegar aca y un ibu esta mañana pienso que el
problema radico en intoxicacion por licuado, o sea por elementos
viejos del licuado.
** [2017-10-22 dom]
anoche dormi nuevamente bastante normal, con un poquito de cefalea sin
haber tomado ningun preventivo y me tome un ibu solo al levantarme. La
manana transcurre normal y pinta un domingo bastante fierito de
aquellos para el olvido total.
en realidad la tarde derivo en migraña total. me tome un ibu y luego
un <<nar>> y no surtio efecto. Segui con la actividad, me vine al dpto
y estoy haciendo las cosas pq creo que si me tiro en la cama va a ser
peor, al menos estoy planchando, voy a pasar los datos y me voy a
bañar, y veo.
** [2017-10-23 lun]
es obvia la diferencia que hubo en las dos ultimas noches con relacion
a la semana pasada sin la sublingual, no solo la calidad del sueño y
descanso sino como me levanto.
** [2017-10-25 mié]
anoche me fui a dormir un poco cefaleico y pense que iba a despertar
con <<nar>> y me preguntaba que me habia llevado a eso si el exceso de
un capitulo de mas de la serie o el dia demasiado largo o que no habia
cenado pero en realidad dormi bien y limpio bien la noche la cabeza y
me desperte bien y tire hasta pasado el medio dia sin problemas eso
que estoy cagado de hambre y me fui al patio olmos a la carrera a
sacarme los rx.
** [2017-10-27 vie]
hoy el dolor nacio luego del estres en oficina, y todo el dia tuve muy
sonolento pq me falta sueno.

** [2017-10-28 sáb]
nuevamente entra el factor nervioso, y cuando hay estres viene la
necesidad de tomar un analgesico, hoy que cuando me levante no habia
tomado nada, lo termine tomando cuando el estres de la situacion subio
a cierto nivel.

** [2017-10-31 mar] 
anoche pense que iba a tener que tomar un nar pq no tenia ibu, pense
en salir a comprar, y me la aguante y me fue bien al final, aunque
ahora recien tomado no he mejorado nada. Pero sali del pozo de la
semana pasada con la crisis migrañosa que me causo creo el licuado.
** [2017-11-06 lun] 
de un finde en general malo y encima cene pesado anoche desperte con
un dolor turbio aunque no declarado y como tenia supercompromiso hoy
con el aviso me tome el <<nar>> sino no lo tomaba.
** [2017-11-08 mié]
anoche desperte con dolor que no cedio con el ibu, y sospecho a la
cena. Muy tarde para meterse a las 22.30hs esos ravioles la
salteña. Tome un ibu a las 3 y un <<nar>> a las 4.20 y me levante mas
o menos bien, pero no tan limpiado como el lunes.
** [2017-11-10 vie]

esta mañana tome un ibu y ahora decido un <<nar>> pq la cefalea pinta
fuerte y tengo 3.15hs de labor por delante y la oficina sin aire o a
mi me parece. Lo cual es una pelotudez mayuscula. Pero esos mas que
todo son signos panicosos. De ultima podriamos intercambiar el lugar y
vemos.
Mejoro bastante y a las dos horas se puede decir que no hay dolor a
nivel cabeza a pesar de la atmosfera cerrada y de haber seguido
trabajando.
*
** [2017-11-12 dom]
termine con un <<nar>> pienso que por estress combinando el finde con
la presentacion del yerno y el compromiso del almuerzo en casa del
fede el domingo y una cefalea refractaria a medianoche en el marques
sin saber como tratarla me decidi cortar por lo sano y tomar un nar y
antes de ir al almuerzo un ibu y anduve joya todo el domingo incluida
la noche y la mañana del lunes.
** [2017-11-13 lun]
cefalea de oficina quizas por estres todo el dia aca adentro con el
aire y extremo estress que obliga a estar templando el animo.
Cedo a <<nar>> en un momento peligroso pq es la segunda al hilo en dia
habil de oficina, a pesar de que el encierro, la claustrofofia, la
falta de aire, y el hambre  etc no se presentaron, pero el estres por el caso 765
es muy grande casi comparado al caso 747 y produce la migraña estoy
seguro mas alla de las bronquitas menores con los otros chicos. 
** [2017-11-14 mar]
hoy felizmente corte la racha del nar en oficina y el nar de ayer
logro disipar por 24hs el malestar.
No obstante los multiples otros malestares persisten pero es bueno que
se haya frenado esa racha.

** [2017-11-15 mié]
esta madrugada 3 am desperte cefaleico encerrado con aire encendido
abombado y tome un <<nar>>. Limpio bastante bien,lo unico que causo
mucho malestar estomacal luego con acidez y mucha produccion de saliva
a la media hora que casi vomito. La noche anterior comi escabeche con
yamani aderezado con mostaza, obvio ambas cosas acidas, y medio
nervioson, a pesar de que me habia acomodado un poco, que habia
logrado cierto nivel de encuadre en mi dpto y en mis planes no le di a
la cena la paz y tranquilidad que era necesario.

** [2017-11-16 jue]
decidi que no tomo mas ibuprofeno, pq habia caido en la toma
preventiva, y en todas las variantes de toma que el migral tiene, por
eso la toma diaria, y con lo malo que es el ibuprofeno no me conviene
si aparte estoy teniendo ese nivel de naratriptan, o sea que o bien
subo el topi y aguanto la tormenta con naratriptan solo o bien evito
totalmente el TACC. y otros conservantes.
veremos que pasa.
Harto!!!!! del dolorcillo y deseando que se me disparara para tomarme
el <<nar>> o se fuera, me tome el nar a 15.40 y veremos. Esta
acompañado de tension muscular cervical extrema, de gran nerviosismo y
de pensamientos suicidas. Creo que si tuviera un chumbo este seria el
momento de pegarse un cuetazo y que la sangre corriera por la
pantalla.
Una hora de tomado y no cede la gran puta y yo lideando aca con los
tipos mas pelotudos que me pueda haber tocado en suerte los ultimos
años.
Pasaron 3 horas y no se me fue el dolor cien por cien y el embole que
tengo es mayusculo, asi no se me va a ir.

** [2017-11-17 vie]
mal dos dias de <<nar>> refractario, no hace nada pero la presion es
muy grande dentro y fuera del trabajo, es indescriptible.

* historial
** migrañas
*** Diario de migrañas fuertes
**** [2016-10-09 dom]                                          :3M:fuerte:
Me tomo el primer migral a las 9hs luego de una noche con molestias y
espera a la mañana para tomar el migral.
No considero que haya sido tardio en ese momento pq no me molesto ni
subio en intensidad. Hice un poco de netbook en cama y luego me
levante y trabaje en la terraza (con viento y sol), luego cuando
llegaba la hora de la comida me puse a trabajar en el patio con la
netbook a contrareloj muy presionado por terminar una secuencia antes
que me llamaran a comer, entonces me sente a comer tensionado y con el
clima beligerante de estos dias con las chicas. En ese momento pense
que necesitaba otro migral, pero no quise arruinar el gusto de la
comida, pero no comi tan feliz como en otras ocasiones.
Justo al terminar el almuerzo me tome otro migral y me quede en el
patio en un sitio mas o menos tranquilo tomando un te y el dolor
subia. Pero no era incapacitante todavia.
Me acuesto un rato y luego decido levantarme a tomar un cafe que tome
con mucha torta y mucho dulce de leche. Y luego de una breve pausa
para dormir que no debo haber dormido mas de diez minutos, bajo a
hacerme un segundo cafe, mientras tanto sigo con la maquina y algunas
frustraciones al medio.
Dentro de esas frustraciones me planteaba el no dispersarme tanto y
focalizarme en solo dos temas.
El dolor subio y se mezclo con un bajon animico pronunciado y un
malestar generalizado.
Alli cuando me acuesto tipo 20.30 y empieza una migraña tipo 8 o 7,
incapacitante hasta para pensar (pero mas por el malestar que por el
dolor punzante). Cuando me lograba dormir me mejoraba un poco, a las
21.30 ih me subio pure de calabazas que pude probar apenas pq estaba
nauseoso. Tome reliveran a las 22.30 y en esas levantadas al baño el
dolor por el movimiento era muy importante, igual que la fotofobia.
Cuando hizo efecto el reliveran me tomo el tercer migral y en los
proximos 45 minutos no experimente ninguna mejoria, acostado sobre el
costado derecho me presionaba mucho la zona del higado, y sobre el
costado izquierdo me presionaba la cabeza donde me dolia.
Quizas una hora despues o dos, ya me mejore quedando solo la resaca
que desaparecio durante la noche.
**** [2016-10-15 sáb]                                      :3M:intermedio:
Hoy desperte a las 4am con fuerte dolor, el clasico y claro dolor
despertador que amerita un migral, tomo y me duermo, siendo
efectivo. Me levanto bien, hago las tareas que habia pensado para el
dia en forma bastante satisfactoria, salvo por dolor intenso en la
espalda pq habia limpiado la oficina. Luego de comer bien (bifes con
cebolla rucula papas), me meto en la compu para instalar un nuevo SO y
el dolor va increscendo hasta hacerse un moderado que ameritaba otro
migral y a eso de las 15hs me lo tomo, se aminora bastante y me echo
una siestita que dormi con dificultad pero dormi, la dificultad fue
por la falta de oscuridad total y por no tener hecha la cama, ya que
necesito si o si ponerme los auriculares, debo haber dormido una hora
en la misma posicion y despierto con un fuerte dolor de nuevo y me
tomo el tercer migral del dia a las 17hs, sin nauseas hasta ahora, y
no espero resolucion ni nada sino que me enfrasco en la compu, y en un
momento de relax cuando miro por la ventana de la cocina, me golpeo
fuertemente la frente, hasta el punto del sangrado, asi que ahora no
se si tengo resaca o dolor del golpe. 
Si bien es cierto que no tuvo la magnitud del domingo pasado, si
podria haberlo ubicado en un comodo 6 en el momento de levantarme que
me impediria las actividades. Y alli decidi ir al medico mañana. En
realidad comenzar a ir a todos los medicos. O sea instalarme en el hp
del patio olmos. o el central si hace falta. 
**** [2016-10-18 mar]                                          :2M:fuerte:
El domingo tomo dos migrales seguidos, me cayo un poco mal la comida
(pollo al disco) y me percato que era tipo cefaleico y cedio bastante
rapido y me bañe y me sente en la terraza y mejore bastante. 
Ayer lunes en la oficina tome dos migrales con separacion de 2 horas
mas o menos y tambien un dolor cefaleico moderado a molesto pero cedio
practicamente cuando volvia a casa. Y hoy fue diferente, tomo los 2
migrales con diferencia de una hora, y recien despues de 5 horas de
haber tomado el ultimo puedo sentarme a escribir esto mas o menos en
la cama. Me volteo, altamente incapacitante creo que a nivel 7, un
poco menos que el domingo 9 pq casi no tuve nauseas. Solo un poco en
la hora de la toma de los migrales, y repeticiones de la comida a
pesar que fue yamani con rucula y quesito. Hace un rato me tome un te
con galletas queso y miel y me fui mejorando paulatinamente. Del
cefaleico parecido a los ultimos dos dias, se fue transformando en
levemente migraico y luego cediendo.
Creo que la causa real es que ya estoy en las ultimas del migral y los
dolores son mas fuertes y descontrolados.
**** [2016-10-26 mié]                                          :2M:fuerte:
Me desperte bien, dentro del malestar que vengo teniendo de tinitus
por asi decirlo, p.e. anoche no dormi con lluvia, y tuve sueños
confusos. Me despierto con el dolorcito insidioso de siempre y me tomo
un migral a las 7 am. Y el malestar no se va y se agrava. Decido tomar
otro migral a las 8am para terminar con el asunto y se me agrava mas,
y empiezo a devenir nauseoso.
14.5/10 la presion, sin hambre, mal, nauseas, casi diria mareos o
confusion. Tenia la presion ridicula de tener que ir a la dgr
(ridicula pq como dijo dyer al final termino siendo menor que lo que
yo imaginaba).
"La catastrofe que tanto te preocupa, a menudo resulta menos horrible
en la realidad, de lo que fue en tu imaginacion"
Cuando fui, pq baje para ir a comprar los remedios y termine yendo por
ratos o cuadras me sentia mejor, pero en realidad me senti mejor que
p.e. lo que estoy ahora a las 12.30 en casa.
Me tome 10mg de corti a las 11.30hs y hasta ahora estoy peor. Me tome
a la misma hora 35 gotas de reliveran y sigo nauseoso, y de pedo tome
un te con dos galletas y queso.
*** Diario de dias 3 Migrales aunque no migrañas fuertes
**** [2016-10-13 jue]                                        :3M:moderado:
   Desperte a la 1 de la mañana y tome un migral con un trago de
   licuado. Y si bien es cierto que pude dormir lo mas bien, cada vez
   que me despertaba sentia molestia, y me decia que ojala la molestia
   no significara un segundo migral, y felizmente llegue a la
   mañana. Luego desayuno y voy a la ofi. Y alli tipo 11hs tomo un
   migral normal como hago siempre, y luego de nuevo en la ofi a la
   tarde siento que el dolor va in crescendo y tipo 16hs tomo otro
   sabiendo que tenia que quedarme hasta las 17 obligadamente. 
   Luego llego a casa en un estado raro, no queria sentarme a
   programar, me sentia saturado, y me hice una merienda frutal con
   manzana, arandanos y frutilla y medio vaso de licuado, previamente
   haberme bañado tranquila y relajadamente, todo esto mientras veia
   la mitad de la pelicula que habia dejado pendiente, y la verdad que
   me relaje bastante, luego me recoste un rato (en realidad el orden
   de estos sucesos ya los olvide pero el resultado grato lo recuerdo)
   la cosa que despues si me sente a programar y la verdad que fue
   altamente productivo el tiempo que estuve, en cierta forma como
   destrabado. Quizas sea que haya aprovechado una base que habia
   hecho en la oficina, pero si me senti como que "fluyo" el trabajo y
   me senti como que podia terminar alli mismo todo el modulo, pero me
   fui a dormir. Esta mañana crei tener un par de puntaditas de nuevo
   en el ojo, aunque no son en el ojo sino en el arco superciliar.

