| [2019-02-18 lun] | 1M-12hs | i600-17hs |
| [2019-02-19 mar] | 1M-03hs | i600-12hs |
|                  |         |           |
|                  |         |           |
|                  |         |           |
* [2019-02-18 lun]   
tomo el migral tipo 13hs mas por evitar el rebote que por necesidad
real, y luego me doy cuenta que al rato la molestia sube, pero lo
mismo era un dia complicado pq tenia un compromiso y grande a la
tarde, pero todo termino bien con solo un ibu de refuerzo.
* [2019-02-19 mar] 
no pude llegar al mediodia. Me deperte a las 3 am con un N6 y tuve que
tomarme un migral, fue efectivo en unos cuarenta minutos, y me volvi a
dormir a las dos horas, luego comence el dia con normalidad.
Tipo mediodia se empezo a arruinar el dia y me tome un ibu, y ahi note
la diferencia de la falta de ambiente para enfrentar un cambio o al
menos tolerar y darle batalla a una reduccion en la toma de
analgesicos aguantandose el dolor. Pq no pude retirarme y pq mi casa
es la oficina o no tengo casa. Me vine para hacerme un arroz, el cual
fue demorado y ya no puedo comer mas en la cocina pq me da asco y me
retire al dormitorio, y bastante bien, pero me hizo mal el agregado de
la pasta de aceituna que la estoy repitiendo hasta ahora (quien dice
que no tenga un aditivo) y luego no puedo sustraerme y ya estoy casi
en un N5 como para estar reposado comodo intentando dormir.
Y tengamos en cuenta que tengo un desfasaje de sueño pq el migral
nocturno me dejo sin dormir y tendria que haber tenido una siesta.
