* [2018-10-29] :ataquemigraña:
:PROPERTIES:
:migrales: 3
:horas:    7
:nivel incapacidad: total
:lugar:    marques
:clonazepan: 3 SL
:nausea:   no
:vomito:   no
:CREADO:   [2018-10-29 Mon 18:55]
:END:

Posible causa ansiedad extrema producida por la mezcla del trabajo en la casa y la delegacion de la oficina y el compromiso de la Romu. O bien esas tres circunstancias fueron el caldo para q creciera una migraña q se iba gestando sola por como venian de precarios los dias previos en salud de base.
El nivel crecia y dormitando con 2 sl arriba baje a N4 pero me agarro un tipo calambre estomacal eso q habia comido solo arroz xon queso safe con oleo31 y seguí dormitando y se tufo la pieza pq estaban los albañiles y sali al patio con N4 en cinco minutos subio a N6 y me acoste y tome 3er migral y 3er SL y de a poco calmo

* [2018-10-30] :ataquemigraña:
:PROPERTIES:
:CREADO:   [2018-10-30 Tue 18:38]
:migrales: 2
:nivel incapacidad: 8
:lugar:    marques
:END:

Tipo 15.30 me meto en la pieza encerrado y me veo dos series de media hora y me agarra. De a poco me tomo medio luego medio al rato y tipo 18 uno mas.con te pq el dolor es insoportable y ya me había puesto una sl y ahora va otra pq si estoy cargado de ansiedad mas q todo la impotencia de estar tan estúpidamente mal justo cuando puedan necesitar preguntarme algo. ahora tengo un poco de náuseas y el dolor casi igual q  ayer increíblemente
pero lo atribuyo al dia de albañiles un dia de mierda  que por abuso de celu y postura y ansiedad y encierro y ruido y preocupación da por resultado esto


* [2018-10-31]
:PROPERTIES:
:CREADO:   [2018-10-31 Wed 11:40]
:END:

Por ahora solo incipiente. Y seguro tomare el segundo SL. Y motivos no faltan y se van agregando
Dormi hermoso y luego de dwspertar escalo. Tome migral y 4mg de cortypiren y me voy a comprar cosas antes q empeore
El problema es q aparenta ser marca camión.
A pesar de q me vine a comprar por las dudas migral y cosas
Pero es hachazo destornillador clavado.
Tome un cafe con galletas y aca estoy parece cedido. Pero no sin antes haberme pasado por la mente ansiedades varias ya sea producidas por las canciones de Ulises o por los compromisos fallados q en este caso seria el lolo


