| [2019-02-18 lun] | MIG-12hs  | i600-17hs    |               |
| [2019-02-19 mar] | MIG-03hs  | i600-12hs    | MIG-23hs      |
| [2019-02-20 mié] | i600-15hs | M-15.45hs    | C10mg-16.30hs |
| [2019-02-21 jue] | C20m-8hs  |              |               |
| [2019-02-22 vie] | C20m-8hs  |              |               |
| [2019-02-23 sáb] | C20m-8hs  | Nx-18hs      | Nx-22.30hs    |
| [2019-02-24 dom] | C20m-8hs  | Nx-22.30hs   | MIG-00hs      |
| [2019-02-25 lun] | C20m-8hs  | i600-23.30hs |               |
| [2019-02-26 mar] | C20m-8hs  |              |               |

* [2019-02-18 lun]   
tomo el migral tipo 13hs mas por evitar el rebote que por necesidad
real, y luego me doy cuenta que al rato la molestia sube, pero lo
mismo era un dia complicado pq tenia un compromiso y grande a la
tarde, pero todo termino bien con solo un ibu de refuerzo.
* [2019-02-19 mar] 
no pude llegar al mediodia. Me deperte a las 3 am con un N6 y tuve que
tomarme un migral, fue efectivo en unos cuarenta minutos, y me volvi a
dormir a las dos horas, luego comence el dia con normalidad.
Tipo mediodia se empezo a arruinar el dia y me tome un ibu, y ahi note
la diferencia de la falta de ambiente para enfrentar un cambio o al
menos tolerar y darle batalla a una reduccion en la toma de
analgesicos aguantandose el dolor. Pq no pude retirarme y pq mi casa
es la oficina o no tengo casa. Me vine para hacerme un arroz, el cual
fue demorado y ya no puedo comer mas en la cocina pq me da asco y me
retire al dormitorio, y bastante bien, pero me hizo mal el agregado de
la pasta de aceituna que la estoy repitiendo hasta ahora (quien dice
que no tenga un aditivo) y luego no puedo sustraerme y ya estoy casi
en un N5 como para estar reposado comodo intentando dormir.
Y tengamos en cuenta que tengo un desfasaje de sueño pq el migral
nocturno me dejo sin dormir y tendria que haber tenido una siesta.
Tipo 15.30 Fede amablemente se va pq yo llegue al limite de aguantar
con un N4 levantado, y me dispuse a acostarme relajado, y el problema
no era tanto el dolor, pq ya estaba libre para relajarme y tenia mucho
sueño, sino que no podia tumbarme para ningun costado, era enorme la
presion, mas que ninguna otra vez pero sin puntada, y cuando me
levantaba salia el aire. El dolor fue en aumento, en todo momento
estuve incapacitado, creo que llegamos a N7 (en oscuridad, ni siquiera
pensar solo dormir o intentar). Puedo dormitar una hora, y la molestia
deviene ya con nausea, y un asco total por la repeticion continua de
la pasta de aceituna (ya la otra vez me habia pasado en el marques),
crei que vomitando aliviaria pero no hubo modo, solo tome agua, y mas
agua y aguante, tipo diez de la noche luego de dormirme cada vez por
mas tiempo, parecia que me mejoraba y no.
En realidad el dolor bifronte, como si me levantaran la mollera desde
adelante para sacarme el cuero cabelludo con una cuchara de albañil se
transformo en una hemicraneal limpita de lado derecho no totalmente
intensa pero si un N5 con vias a aumentar. Eran las 23hs y no habia
comido, estaba debil y no creia que podia aguantar una migraña
verdadera durante la noche, entonces me tomo 1 Migral a esa hora, es
efectivo en una hora desaparece el dolor, en el mismo momento molesto
como estaba me hice el licuado, y lave los platos por las cucarachas
de la cocina, me tome solo vaso y medio de licuado y me dormi. No muy
comodamente, pero bastante mejor que la tarde.
* [2019-02-20 mié]
A la mañana me levanto debil, tembloroso, iba a decir como tension
baja, me tomo un vaso de licuado, y me compro facturas, y desayuno un
cafe, con dos facturas dulces, que como con ganas, y un beroca que
tambien paso sin dificultad, no mejoro, pero pasable, y me voy a pagar
boletas, maso.
Me mido la tension y me da 12/6 o sea si baja.
segunda medida ya cinco minutos despues de estar sentado: 
12.3/ 6.8 y 98 ppm. 
Voy al neurologo y tengo que esperar dos horas que me atienda. Ya me
habia mejorado bastante el sintoma de baja tension, y tenia una
jaqueca creciente pero no era todavia amenzante. 
Luego almuerzo en el hp bien, en un ambiente agradable y al final del
almuerzo tomo un ibu, y al llegar aca me va creciendo la jaqueca y no
lo pienso mas y me tomo el migral para abortar cualquier problema.
Luego de 45 minutos de migral solamente se agrava la migraña, esta
bien que la situacion hace que no pueda salirme de la situacion y me
tomo un C10mg y felizmente el fede me compra lo que me hace falta de
viveres minimos para sobrevivir y ya daremos por terminada la jornada
y me podre acostar.
Creo que faltan solo dos dias para finalizar esta tortura. Pero creo
que la pauta que me dio el doc puede aliviar el status migrañoso.
Me acuesto finalmente pero no me hizo efecto alguno el migral, el
dolor fue mayor que el dia anterior creo que facil un N7 concentrado
en la frente, bifronte, lo unico que con menos sintomas
nauseosos. Pero llegado un momento me levanto al baño e intento por un
lado evacuar con la enorme dificultad del dolor de cabeza, y por otro
lado la nausea, y al desistir y levantarme espontaneamente y sin
provocarlo vomito moderadamente parte del almuerzo muy poco, con un
fuerte olor al saborizante de la gaseosa y desde ahi me empiezo a
mejorar y en poco cede el dolor. Me veo una pelicula en cama y solo
ceno un te con dos medialunas que tenia compradas y duermo mucho
(quizas por la flu) y me levanto normal. Y comienzo la cortiterapia.
* [2019-02-21 jue]
tome el c20mg a las 8hs y el dia no fue muy facil que digamos pero
tampoco abuse y creo que lo administre bien, abuso hubiera sido si a
las 12hs iba yo al banco con el calor que hacia unos 38 grados y me
tiraba al albur de comer "afuera" a un sitio desconocido, buscando
emular la experiencia de ayer, en vez de eso puse a hervir arroz y fue
el Fede al banco y yo me quede, comi tranquilo en el fresco y descanse
un rato, y luego el Fede se fue y aprovechando que no me dolia la
cabeza (aunque si tenia otras molestias fisicas pero las ignore, como
cansansio e incipiente dolor articular), me puse a adelantar trabajo y
despejar mi escritorio preparando el cambio de oficina. Ahi me di
cuenta que si influye el ambiente en el malestar general, pq una tarde
de extremo calor como esta, donde tenes un aire que no te da abasto pq
le abris la cocina o la ventana y encima le metes humo de cigarrillo
adentro te hace mas miserable el tener que estar con esta rutina que
de por si es fea. Y creo que en ese sentido la oficina nueva va a
mejorar mucho. o sea el ambiente, no solo dando mas luminosidad que
aca que es poca o mucha de mas (salvo los pocos dias nublados), y
espacio, sino el aire mucho mayor con ausencia de humo.

Volviendo al tema tratamiento, creo que hay que esperar, a ver que
sintomas aparecen y que pasa cuando empiece el rebote.

La tarde y noche transcurrio bien sin sintomas molestos de ningun tipo.
* [2019-02-22 vie]
duermo bien nuevamente aunque voy despertando desde tipo 5am con un
incipiente y me voy preguntando como abordarlo, pq era chico como para
tomar un migral, y tenia miedo que tomando un ibu se arruinara,
entonces segui durmiendo y no tuve problemas.
En la hora de levantada la distraccion hace que uno no sea muy
consciente de la molestia y ya tome el C20m.
Aunque estoy consciente que es el segundo dia y puede haber rebote,
pero siendo como es el dia de hoy complicado no creo que dude en tomar
un migral. y veremos que pasa. 
Lo que noto es sueño y cansancio, a pesar de haber dormido mucho, pq
ya a las 22 me dormi, estoy muy cansado y debilitado, quizas sea por
el corticoide.
Como vengo notando la proclividad para dormir, la cual es bienvenida
pq me hace innecesaria la toma de cualquier otra porqueria que tampoco
quisiera tomar, me la da la flu.
Este viernes era un dia particularmente dificil, lo describo pq uno
pierde la memoria rapidamente, habia que mudar la oficina sin parar de
trabajar y el dia era bochornosamente calido, era el final de una
semana de tremendo calor. Se me habia ocurrido ayer que podia llevarse
la mesa de vidrio con un operativo coordinado FAbian/Osver/Kangoo/Fede
en el medio de la atencion, pero tenia que ser muy coordinado. El
viernes le recuerdo al Fede por las dudas que lo haga asi pq yo como
estaba no iba a poder ayudarle. Entonces el dice que si que le demos
para adelante, y encintamos la mesa y cuando llegan los muchachos
bajan las cosas y cargan, primera prueba de estres, felizmente pasada.
Sigo atendiendo y pasando papeles aca yo solo. Felizmente Fede toma la
iniciativa de llamar a la Cami para que lo ayude a el en la mudanza y
se hacen cajitas de mudanza y solos se las apañan para trasladarse y
acomodarse sin interferir conmigo, incluso pude hacerme un arroz y
comerlo en tiempo y forma en el medio.
Pero ... en el medio de todo lo anterior se descarga la bomba atomica
no esperada en "ese preciso momento" (o sea justo en el momento en que
estabamos mudando la oficina en el medio de la atencion de la gente, y
yo en el segundo dia de corticoides), ih me llama, no diciendome que
me acordara de comprarle el lavarropas, sino con un berrinche de
adolescente diciendo que estaba en Garbarino con la tarjeta en la mano
decidiendo entre dos modelos que no sabia cual era cual, en fin,
describir el alcance y el desastre de la situacion excede lo que este
post requiere. Felizmente no me saque de quicio, sino que segui en lo
mio, la llamo en 5 minutos, y me dice que ya se volvia, que estaba
manejando que lo comprara yo, entonces agende en el medio de ese dia
ya de por si dificil comprar un lavarropas. 
Con el calor que hacia, con ciertas coordinaciones bien hechas pude ir
a Fravega comprar, retirar, llevar.
Podria haberme quedado, pero quise estar presente cuando lo
llevabamos, asimismo la cara de culo la tuvo igual por mas que le
lleve ese lavarropas. Pero luego el calor, la incomodidad de la casa,
el aire que no es muy benigno alla cuando hace calor, la comida
pesada, el problema que el lavarropas no centrifugaba bien, y como
broche de oro que se trabara la pileta y pum!!! viene la Carla, ahi
decidi venirme.
Asimismo el viernes increiblemente siendo el segundo dia de WD y
siendo que toco por suerte asi un dia de mierda climatologicamente y
por compromisos no tuve ninguna molestia ni tuve necesidad de tomar
nada.
* [2019-02-23 sáb] N6
el sabado luego de venirme me dedico a comprar las cosas para el
licuado y verduleria y arreglar pileta.
Ese fue el factor principal que necesitaba hacer sino quizas me
hubiera quedado, pq si no arreglaba la pileta se me complicaba el otro
tema que anda rondando y es que el problema de la humedad del 5°C, y
yo con la pileta que pierde, no es bueno que venga el plomero a ver
eso. Felizmente analizo el problema y decido que no voy a sacar los
caños de pvc, es bueno informarse por youtube donde hay tutoriales
profesionales de todo tipo y uno aprende un monton, ahi vi que
despegar un caño de pvc es un trabajo enorme, entonces decidi
poxilina. Y sello bien.
El dolor ya era incipiente a ese momento. Un poco molesto, pero
pasable, luego de comer, mijo con calabazas, decido tomar un
analgesico. Pense en un ibu, pero me decante por un naprux. Y el dolor
seguia a cierta hora pero no era incapacitante, entonces tenia dos
opciones o tirarme o ponerme a trabajar, y me puse a limpiar, limpie
los vidrios del living, barri, encere, y en ese momento llego ih y
Fede, trajeron la mesa, armamos, y terminamos de limpiar el living,
luego se fueron y termine de acomodar y me tire en la cama en el aire.
El dolor crecio un poco pero nunca fue muy fuerte. Pense que podia
incluso ver una serie y comence a ver Perros de Berlin, pero al ver
que tenia mucho parpadeo de luz lo deje, luego alternando dormidas con
toma de agua, con una taza de licuado, mas dormidas, en ningun momento
me senti mal del estomago, me tomo los remedios de la noche, y a las
22.30 me tomo otro naprux como rescate y me duermo, y a medida que la
noche transcurrio, se fue diluyendo el dolor, pero nunca deje de
dormir. Si tuviera que evaluar el nivel alcanzado diria que fue un N6
en general considerando que aunque fue sabado tuve en el medio el tema
de tener que hacer cosas y estar en tension, no es lo mismo haber
transcurrido en un sabado cualquiera con la heladera bien llenita sin
problemas de traslados, ni mudanzas, ni canillas, ni cucarachas y el
dptito bien limpito, y la ropita lavadita y planchadita para el lunes.
* [2019-02-24 dom] N8
despierto libre de dolor, con el despertador de las 8 para el
corticoide, lo tomo y sigo durmiendo y asi hasta las 11hs, luego me
levanto desayuno te con galletas, se me plantea tomer un naprux
preventivo, y decido esperar, lavo dos camisas y todo ok solo siento
el esfuerzo fisico como si fuera mas de lo que hago, como el doble o
triple, pero me distrae o me saca en este caso la atencion a la
cabeza, no tengo hambre aun.
Son las 15hs he tratado de hacer actividades, y la voy llevando, con
algo de cansancio y aburrimiento, como estoy solo no como si no tengo
hambre y no tengo hambre. Solo cansancio, por eso me tomo un
beroca. Lo mismo me gustaria comer algo mas tardar 15.30 para no
desarticular tanto las comidas y tratar de hacer una siestita. No
viene mal el dia de relax de todos modos.
...
El domingo llegaba a su fin, lo que tocaba era el aburrimiento ya. En
eso giro la cama, y me gusta.
Pero en los primeros momentos de adaptacion me daba el aire frio muy
de golpe quizas no se. 
Yo ya habia apagado todo, luego activo de nuevo wifi, la Cami me
pregunta si le pago un delivery, y luego ih me pide que le compre un
tv, eso me enoja y le contesto mal, no es que eso haya disparado una
emocion violenta en mi interiormente perceptible, pero desde ese
momento se disparo una migraña total. Previo a esto unas dos horas
antes me habia tomado un Naprux quizas como preventivo para
incipientes, o pq estaba en el fondo nervioso pq al dia siguiente
tenia oficina, aunque en ese momento no era consciente del compromiso.
La migraña crecio de golpe, muy rapido y se agravo con el nerviosismo
de la incomodidad que me dio el lugar nuevo, y me vino a la mente que
yo DEBIA estar en la oficina hoy por la mañana pq no habiamos probado
la impresora y Fede tenia que imprimir todo de frente y encima
soportar un primer dia de adaptacion a una nueva oficina, y no podia
faltar, entonces decido tomar un migral.
Felizmente hizo efecto y dormi bien y me levanto bien para seguir con
el WD.
* [2019-02-25 lun] N7
me levanto mas o menos normal, desayuno enteramente licuado, y tomo el
C20 puntual a las 8hs. Voy a la oficina, y no llevo nada ni licuado ni
remedios.
Y alli un poco nervioson empiezo a sentirme mal. Y le pregunto al Fede
si no tenia Ibu, quizas me hubiera tomado uno, entonces me hice un
cafe cargado de dos cucharadas con dos de azucar que me parecio muy
rico y me puse bien, fui al banco trabaje hasta las 12 y volvi, me
hice el arroz, lo comi con mucho hambre (me quede casi corto y eso que
hice 6+1 mas un tomate), y a cada momento me parece que se me
congestiona la frente-sien con una especie de parestesia-contraccion
que en el fondo se hace esponjosa y propensa al dolor con alguna que
otra puntadita que se va mas adentro.
Dormi una siesta de una hora o menos con sueños y todo, y luego no fui
a la oficina, sino que me quede e hice muchas cosas en el dpto,
incluso me fui a pagar los audifonos que compre, luego me puse a
cocinar y comi, hasta ahora las 21.30 todo bien , solo que comi mucho
aunque vegetales mayormente, voy a esperar un rato para acostarme.
Solo un poco de dolor de espalda.

A la noche me vino una migraña hemicraneal pero mas manejable, decidi
probar con ibu600 solo para ver, que onda por las dudas pero no paso
nada, ni para bien ni para mal, salvo que haya sido el causal de la
suavizacion de la migraña con respecto a la del domingo noche.
Tambien puede haber influido el acomodo de la pieza, acomodo la musica
con un musiquero nuevo que sirva para toda la noche y me dispongo
comodamente sin aire por la temperatura (eso tambien fue positivo) y
lo bueno fue que pude dormir!!!.
Cuando me despertaba para ir al baño notaba que el dolor era intenso
en el desacomodo, pero luego de acomodarse permitia volver a dormirse,
y pensaba que iba reduciendose pero no, a la mañana lo siento igual,
me planteo que no podre ir a trabajar, pero estoy todavia en duda,
noto una cierta disminucion, aunque estoy con un nivel de migraña muy
superior a lo aceptable para salir de casa.  Seria romper los esquemas
y ver que pasa, quizas el movimiento sea positivo, al menos voy y
hablo con el Fede en persona si no puedo me vuelvo.
Lo bueno es haberse animado a no tomar migral y a recomenzar nuevamente.
