* WD fallido descripcion
UM el sabado 22/2 a las 2 am, decido empezar la cortiterapia con casi
35 hasta esa altura del mes, pero empiezo tarde tomo a las 10.25 la
primera dosis de 20mg, pensando repetir la pauta del 2019 o sea dosis
unicas matinales de 20mg. 
A las 20hs tengo mucho dolor articular de cadera, hombros y codos y
tomo un ibu 800mg y puedo "llegar" a la mañana siguiente al proximo
cy.
El domingo 23/2 a las 8hs tomo 20mg y reporto dolor cefaleico desde
las 8hs en adelante persistente N3/N4 que luego llego a N6. 

decido "abortar" el tratamiento pq encima estaba encuadrado en unas
circunstancias vitales muy estresantes y peligrosas (el final incierto
de la obra y su pago final, y no habia quedado de acuerdo con el Fede
de poder tomarme una o dos semanas de franco). y entontes tomo un
migral a las 13:24hs  ya nauseoso. no paso nada, sigo sufriendo tirado
en la pieza recluido en el oscuro, intentando dormir, y cuando mas o
menos se van haciendo las 6hs permitidas para repetir migral tomo otro
a las 19:30 reportando un dolor intenso tipo N6/N7 toda la tarde
ininterrumpido. me tomo una SL y me tomo un tercer migral a las 1.30
menos nauseoso y puedo dormir mejor y me levanto el lunes con una
resaca del N2/N3
Teniendo en cuenta que lunes y martes era feriado.
a las 12hs del lunes la resaca habia subido a N4/5.
tomo SL a las 13hs
otro migral a las 17hs muy dolorido punzante N7 sigo lugo con N6
persistente. 
a las 19hs ante la inutilidad del migral tomo 10mg de Cortypiren como
ayuda. amagando a un estatus migrañoso y luego a partir del martes se
estabilizo nuevamente en una situacion ""normal"" de dos migrales por
dia.
Pude trabajar el resto de la semana con dos migrales por dia, hasta
que decidi hacer un nuevo WD pero con el doble de la dosis.
* WD 2020 - 29/02/20
Pauta posible:
10 dias 20+20
5 dias 20
5 dias 10
5 dias 5
total 575  (WD19 390 WD17 1668)

UM-28/02/20 23:30hs
** [2020-02-29 sáb]
comienzo bien a horario 8hs y 20hs 20mg cada dosis.
18.30hs tomo Naprux con mucha dificultad gastrica y no fue efectivo
tipo 20hs incipiente N5 y molesto un N3/N5 toda la noche
** Marzo 7

*** [2020-03-01 dom]
dosis idem 
18.30hs tomo Naprux por un incipiente N4 y fue efectivo
*** [2020-03-02 lun]
dosis idem
se "agrego una sobredosis" de 10mg de refuerzo a media tarde para
intentar conjurar un N6 al vicio pq no funciono.
9hs ya empezamos con el Naprux con un N3 que rapidamente escalo a un
N6
fue el primer dia de trabajo en el tratamiento a pesar de que era en
la casa. pero estuve dolorido, fue el tercer y ultimo naprux de la
serie llegando a la conclusion que no me hace nada y que es
gastricamente muy malo. y a la tarde "probe" con agrandar al dosis de
cortipiren pero no altero en nada el curso del dolor.
*** [2020-03-03 mar]
dosis idem
dia esplendido sin ningun sintoma
*** [2020-03-04 mié]
dosis idem
nuevamente decido a las 15hs "reforzar" la dosis con 10mg pq arreciaba
un N5/6 y luego de la siesta cedio
*** [2020-03-05 jue]
dosis idem
dia esplendido
*** [2020-03-06 vie]
dosis idem
N3/4 durante la jornada que se fue subiendo luego de las 17hs a un
N8, no cediendo y descansando relajado por un clonazepan 0.5 luego
casi digamos que llega a niveles de N9 pero me logro dormir y a las
23hs mas o menos ya habia cedido.
*** [2020-03-07 sáb]
dosis idem
N3/4 a las 14hs - N5/6 a las 17hs
me levanto de la siesta con clonazepan con N6 y baja a N0 "con
episodio de pintura en el patio" (ver descripcion en conclusiones)
vuelve N5 a la noche que durante la noche baja a N1
*** [2020-03-08 dom]
dosis idem
dia normal
*** [2020-03-09 lun]
N2 12hs N4 12.45hs N5 15hs
me levanto de la siesta con un N5 y se baja a N0 con tareas de cocina
(similar al sabado ver descripcion en conclusiones)
*** [2020-03-10 mar]
20 mg C 8hs - hoy comienza la reduccion o sea a la tarde no se tomara
la segunda dosis
N0 durante el dia, a la noche se desarrollo un nivel de N3/N5/N2
fluctuante que duro toda la noche que aunque permitio dormir (es para
anotar tambien que tuve que montar guardia pq habian quedado cosas en
el jardin y dormi con la ventana levantada y mirando para afuera cada
vez que me despertaba)
*** [2020-03-11 mié] MIG
dosis idem
el nivel N5/N3/N4 sigue fluctuando y permitiendome hacer las cosas sin
problemas. Tipo 12 se incremento hasta N6/7 impidiendo la lectura y
debiendo recluirme en el oscuro, incluso en horario del almuerzo me
mostre nauseoso y tuve que tomar reliveran antes de comer. Despues de
comer siento una marcada mejora.
Probe con Oleo31 y despues de una leve mejoria de cinco minutos los
sintomas volvieron.
luego de las 16 se fue incrementando la migraña hasta llegar a un
nivel de N9.
quise reposar con clonazepan y tranquilidad y no consegui ninguna
mejoria, y decidi tomar MIG que fue efectivo en 30 minutos sin resaca.
Luego pude retomar actividad normal por el resto de la tarde.
*** [2020-03-12 jue]
dosis idem (casi me demoro y la tome a las 8.24)
mañana transcurrio bien, tipo 12 comenzo un N2 atipico como diferente,
y luego del almuerzo que fue muy bueno se transformo en N4, como es un
dia de gran tension (final de obra de pintura, con beligerancias
varias que van disminuyendo al paso de las horas, sumado a un jueves
negro en venta, segundo dia de caida de operaciones en la semana) no
lo puedo manejar bien. Decido probar con un Naprux, (tuve 1:3 de
efectividad) y relax (que se vio interrumpida) y apoyo con un
cafe-recargado (100mm 4cc+2azucar) con la finalidad que no se escape y
pueda terminar la jornada aciaga. Fue efectivo el Naprux y/o supercafe
para bajar de N5-N0 y cumplir con la obligacion de esta tarde.
Luego de lo cual quede relajado y levantado
*** [2020-03-13 vie]
dosis idem
este fue el dia mas desafiante del tratamiento. Y transcurrio
totalmente en estado N0 felizmente de punta a punta.
Me levanto, hago las series, tomo el cortipiren, hago desayuno con
dosis grande, y avisa Mayra que Fede esta descompuesto mal con dolor
en el pecho y vomitos. Ahi nomas me cambio y me dispongo a ir a la
oficina.
Primer desafio: volver a la oficina despues de 9 dias de ausencia,
yendo tarde en remis, y haciendome cargo de la salida.
Me avisa ih que habian llamado a emergencias, o sea que la cosa no era
para nada simple, aunque yo no temia que fuera un infarto por el
sintoma del vomito, pero podria haber sido, porque no? si el puede
tener ya el perfil de salud para eso.
Segundo desafio, encarar la atencion contrareloj: voy mandando
mensajes por wassapp encima un chofer pelotudo me hablaba de
Ronaldinho.
Llego bien a la oficina y no estaban amontonados los nuevos que era lo
que yo temia pq todos ya habian sido mandados a la zona de antemano,
eso fue una gran suerte solo estaba Coco liso, lo atiendo, ahi viene
Pablo, lo atiendo, y viene el Ale con la Stefi, los atiendo y viene el
Osver, ya me saque el equipo de venta, y viene el Nir. Todo ok.
Tercer desafio: permanecer en la oficina vaya a saber hasta que hora
sin saber si me iba a estallar la migraña.
Me puse a pasar los papeles ordenadamente, primero los recibos, luego
los devueltos, luego las ventas, luego vinieron mas cobradores hasta
que se hizo las 13hs y no habia llevado nada para comer ni beber y no
queria gastar ni en un baggio. Entonces bajo y me compro un paquete de
galletas tia maruca pepitas y tomo con un cafe normal, las galletas me
parecieron muy grasosas pero comibles y era lo unico que habia (una
lastima de prevision pq en un minuto hubiera armado el bolso con los
dos tupper nuevos y el hielo con comida y mijo, el termo con leche de
avena y el set amarillo de cubierto y el de jabon)
Luego de comer esas galletas y el cafe me anime bastante y le meti
otro tiron, segui pasando papeles decidido a terminar. luego vinieron
los otros.
Faltaba la olorosa. A las 15hs prendo el coco, y temo que el olor a
mierda me desequilibre, como el olor a la pastina del 2019 me habia
generado una migraña, luego me habla el Fede y me dice que la chica no
venia, gran alivio apago el coco, atiendo los tres que vinieron a la
tarde, termino los papeles, cuento la plata, pago la tarjeta y el
cable me tomo un taxi y me vuelvo.
Hasta alli todo muy bien.
pero no termino ahi el dia.
Vine con la decision tomada de frenar la obra. Y habia que avisarle al
Matias, entonces le llamo no me contesta y le dejo mensaje y luego el
me iba a llamar o sea que tenia que quedar a la espera. Luego el me
llamo hablamos y suspendimos la obra.
Tambien vino el vidriero y pusimos las ventanas y lo tuve que atender
yo pq la ih lo habia ido a ver al Fede.
A todo esto aunque me habia cambiado, no me pude ir a dormir o a
relajar, sino estar ahi atento.
y en el fondo yo sabia que venia el CUARTO desafio: que el Fede no
habia ido al medico e iba a hacer eclosion a la noche. Dicho y hecho,
no podia conciliar el sueño, luego de cenar bien me recuesto y me
pongo una SL, no quise un 0.5 pq presentia que tenia que llevarlos. 
Tipo 23 el FEde llama que no puede estar y que le compremos un
corticoide inyectable y le llevemos. Vamos y lo llevamos al HP. Y
permanezco alla hasta las 2.30am y luego hasta que viene ih no se si
me dormi a las 3.30am. Dormi lo que se dice muy poco.
Todo cursado normal con energia y N0.
*** [2020-03-14 sáb]
dosis idem
Me desperto el despertador de las 8hs para el corticoide del sabado, y
me senti en ese segundo destruido. Pero me levante e hice la rutina de
levantado con series incluidas con una gran energia y luego solo pude
dormitar durante un par de horas pero no dormi mas.
Almorce bien y al intentar dormir la siesta estalla un N4
puntiagudo. Lo encaro con Naprux+cafe y una actividad absorvente y no
obtengo resultado. Si puedo luego bajarlo luego a N0 con actividad
normal. 
*** [2020-03-15 dom]
dosis idem (tomada por situacion especial a las 7am y por situacion
especial no empece la segunda reduccion a 10mg)
Hoy tenia que llevar a las chicas a la terminal bien temprano y me
levante 6.45 y tome a las 7. El dia fue largo y tensionado por todo el
tema de la pandemia y el riesgo economico sobre la empresa. Me costo
volver a dormirme, pero luego de paciencia pude dormir una siesta y
recuperarme.
El dia transcurrio totalmente en N0.
*** [2020-03-16 lun]
dosis idem (sigo con la prolongacion de la dosis de 20mg por situacion
especial)
hoy era el primer dia de reintegro en oficina y no podia arriesgarme a
bajar la dosis.
Transcurri normal hasta las 12.15 cuando un N3 empezo a notarse, y
decidi tomar un Naprux+Cafe, que con absorsion en actividad parece
estar haciendo efecto. Paliando el efecto corrosivo del naprux con
leche de avena. Pude soportar bien el dia laboral y luego el resto del
dia sin problemas en un estado de N0
*** [2020-03-17 mar]
10 mg C 8hs - hoy empiezo la reduccion a 10, demorada dos dias.
me tomo licencia para ver que pasa.
Hasta esta hora (12hs) todo normal.
Tome un naprux solo sin cafe con gran molestia gastrica solo con un N2
incipiente, y me arrepiento, como si lo hubiera tomado preventivamente
para que no se desarrollara algo mas, o sea algo muy estupido.
Lo cierto es que no paso nada, transcurrio el tiempo en el mismo N2 y
por ahi ahora dos horas despues tengo un N4 y ya tome y no queda
ningun shot que probar.
Creo que el naprux ya debe ser descartado como politica de accion, por
infeficia probada. Y por los potenciales riesgos gastricos que tiene.
Se me aumenta a N5, tomo un cafe fuerte y sigo levantado a ver que
pasa. puedo seguir leyendo y viendo tele a la vez con una molestia
moderada. Para no caer en tener que dormirme.
Admito que el WD cayo en una crisis lamentablemente externa con esto
del coronavirus y no se como se sigue de ahora en mas, salvo que cese
la actividad y se pueda enfrentar uno con tranquilidad a luchar contra
el dolor.
*** [2020-03-18 mié]
dosis idem
dia normal con N0
*** [2020-03-19 jue]
dosis idem
dia normal con N0
*** [2020-03-20 vie]
dosis idem
dia muy complicado (dia para ir a buscar a las chicas a la terminal)
tuve N0 hasta el mediodia durante la salida critica a la calle por
suerte, habia llevado baggio y pastillas pero no las use. luego a la
tarde N2/N4/N5 tomo cafe, galletas, dleche sube a N7 pienso en tomar
mig y luego de media hora baja a N0 solo.
*** [2020-03-21 sáb] MIG
dosis idem - fin de cortyterapia - 
dia similar, por la mañana bien y a la tarde N2/N4/N6/N7 siesta N9 MIG
a las 18hs recupero en 1.30hs.
*** [2020-03-22 dom] MIG
similar al dia anterior mañana bien y a la tarde N2/N4/N7/N8 MIG
18.30hs 40m recupero
*** [2020-03-23 lun]
similar al dia anterior solo que cuando comienza un N2 a media tarde
tomo un naprux con cafe y no duermo siesta sino que paso la siesta
mirando series, y me mantengo estacionario sin migraña.
*** [2020-03-24 mar]
N0 todo el dia
*** [2020-03-25 mié]
N2/N4 napro mas cafe, luego baño prolongado y felizmente domo el dolor
*** [2020-03-26 jue] MIG
cuando aumenta la molestia N2/N3/N4 tomo naprux con cafe, (me alegro
que sea el ultimo de la caja, - no compro mas-) y no hace ningun
efecto es mas aumenta a N6/N7 y tomo migral que si hace efecto.
*** [2020-03-27 vie]
cuando empieza como todos los dias el N4/N5 tomo cafe y eso lo alivio
*** [2020-03-28 sáb] MIG MIG
como siempre comienza a molestar tipo N4/N5 y decido probar
Paracetamol Raffo 1gr con cafe, pero una hora despues tengo que tomar
migral y no fue util y una hora y media despues tome otro migral que
si fue util.
*** [2020-03-29 dom]
N0 todo el dia
*** [2020-03-30 lun] MIG
dia normal pero a la tarde se puso en nivel N4/N5 y decidi ir directo
al migral y no limpio inmediatamente sino que demoro unas dos o tres
horas en limpiar totalmente
*** [2020-03-31 mar]
todo bien con cafe desayuno y un cafe triple a la siesta, toda la
siesta viendo netflix hasta las 19 con un N2/N3 continuo hasta ahi
nomas por ahora
** Abril

*** [2020-04-01 mié] MIG MIG
nefasto dia de migral a la 1.30hs tuve que levantarme a la madrugada,
y luego en el dia a las 17.15hs otro con N5.
*** [2020-04-02 jue]
N0 todo el dia
*** [2020-04-03 vie] MIG MIG
nefasto dia pq me levanto luego de una noche con dolor leve pero que
cada vez me molestaba mas y al levantarme a las 10hs decido tomarme un
migral, luego de un dia largo de lecturas varias buscando una solucion
de plataforma para la romi, me entra un destornillador en la mollera y
tomo otro a las 19hs felizmente eficiente
*** [2020-04-04 sáb] MIG
solo un mig a las 16.30hs
*** [2020-04-05 dom] MIG
solo un mig a las 15.30hs
*** [2020-04-06 lun] MIG MIG
a las 14.30hs pruebo por primera vez un Ibu400 luego de leer un
articulo que decia que no hacia nada en caso del covid19 por eso no lo
queria tomar yo, y no me hizo absolutamente nada, tal como habia sido
el paracetamol los otros dias, y a la hora tomo un migral, a la hora
siguiente ya tenia un N8, aguanto una hora y tomo otro,
15.30/16.30/17.30
*** [2020-04-07 mar]
el dia transcurrio con N0 pero creo que tiro una inercia a que el dia
siguiente empezara a las 7.30hs.
*** [2020-04-08 mié] MIG MIG
altamente nefasto dia pero que termino con una pequeña victoria,
comenzo con un migral seminocturno en las circunstancias actuales de
dormir hasta las 10hs, pq lo tome a las 7.30hs y segui durmiendo y fue
efectivo solo un poco de acidez por la granola. Luego el dia presenta
la malefica rutina que vengo teniendo una toma tipo 17hs que no es
efectiva por un N5 y un agravamiento a N8 a la hora, solo que decidi
no tomarme el tercer migral, y me quede levantado hablando tomando un
cafe, caminando no prestandole atencion, pq habia pensado acostarme
hasta que pasara, y pude bajarlo a N0 como si me hubiera tomado el tercero.

*** [2020-04-09 jue] MIG MIG 
dia nefasto me agarra un N5 como todos los dias luego de ver un par de
horas series y tomo un migral que lejos de hacer efecto parece que
agravara los sintomas produciendo un N8, entonces a la hora y media
tomo otro que a duras penas me reduce el martirio y me saca el
dolor. Esto se produjo a 17/18.30hs.
*** [2020-04-10 vie] MIG
17hs migral N4, 18hs N6, 19hs N8 y decido no cenar y no tomarme un
segundo migral sino irme a la cama y dormirme y conjurarlo con dormida
y tuve exito.
*** [2020-04-11 sáb]
N0
*** [2020-04-12 dom] MIG
tome mig a 12hs y fue suficiente el resto del dia sin molestias
*** [2020-04-13 lun] MIG
tome un mig a las 13.30hs con un incipiente N3 y luego de comer me
aumento a N5 y decidi irme a dormir la siesta o a soportar el dolor en
vez de tomar un segundo migral, y dormi una siesta hermosa. Debo decir
que cuando me fui a acostar tenia un N8, y cuando me levante un N1. No
todas las dormidas produciran ese efecto pero esta fue asi.
*** [2020-04-14 mar]
N0
*** [2020-04-15 mié] MIG
16hs tomo migral y no resuelve totalmente esta bien que fue una tarde
muy full con series, sentado sin pausa, con cafe, merienda con cafe, y
me decido a no tomar otro, luego viene Fede, luego viene la cena, y
queda pendiente aplicar el remedio de irse a dormir, y va pivoteando
un N4 en promedio digamos con un pico de N5 a veces. Luego permitio
ponerse a jugar a las cartas bastante confortablemente, y luego de las
cartas me puse a ver una peli con ih, y luego me fue a acostar y ya
estaba en N0. sin haber tomado un segundo.
*** [2020-04-16 jue]
N0
*** [2020-04-17 vie] MIG MIG
como el dia anterior no tome me levante con un poco de resaca incluso
no me permitio dormir bien la segunda parte de la noche. y a las 10.30
tome un migral que me fue barbaro. Sin embargo tengo un registro de
otro migral a las 20hs que no recuerdo pero esta anotado
*** [2020-04-18 sáb] MIG
migral unico a las 15.30hs
*** [2020-04-19 dom] 
N0 todo el dia
*** [2020-04-20 lun] MIG MIG
mal mal el dia, me levanto con resaca de la noche, tipico de una noche
posterior a un dia N0 y desayuno practicamente con migral, y a las
6hs, ya estoy con un N5 casi N6 tomando un segundo, esta bien que la
actividad ha sido ininterrumpida y poco proclive a que no me otro
cuetazo.
*** [2020-04-21 mar] MIG  Sibelium
tomo 15.30hs
*** [2020-04-22 mié] MIG
tomo 15.30hs y resulta efectivo en la hora siguiente
*** [2020-04-23 jue] MIG
tomo 15.30hs y resulta efectivo
*** [2020-04-24 vie] MIG MIG
tomo 13hs casi de urgencia dia de mucho y excesivo calor fuera de
tiempo ya, mientras estaba en el patio con el fede, y no fue efectivo,
tomo otro a las 16.30hs que tampoco es efectivo luego tipo 17.30 me
tomo una siesta que es efectiva a medias y luego una minimerienda que
termina corrigiendo el problema y se me pasa.
*** [2020-04-25 sáb]
nada
*** [2020-04-26 dom] MIG MIG
dia malisimo pq me levanto con resaca del dia anterior que no habia
tenido nada pero lo mismo no tomo nada y recien lo tomo en el almuerzo
en un momento de nerviosismo y me pongo a ver tele, luego de un par de
horas que no fue efectivo me tomo otro y no es efectivo y decido
acostarme para ver si mejoraba y la "acostada" no fue efectiva para
nada y termine sin cenar y varias horas dolorido hasta que pude
dormirme y tranquilisarme.
* conclusiones WD 2020
** Ni el Naprux ni "reforzar" la dosis sirviron para aplacar los rebotes
de los tres naprux tomados uno solo parecio ser efectivo, y las dos
dosis de refuerzo no sirvieron de nada. Solo el descansar con relax
(musica,tranquilidad,clonazepan si es posible) parece ser mejor.
El Oleo31 no sirve de nada, es solo un paleativo de uso externo para
crear un momentaneo momento de confort pero no tiene efecto real.
Tampoco esta sirviendo el clonazepan 0.5 como inductor del sueño en
siestas para reposo con mayor profundidad y efectividad. Me recargo
del farmaco al vicio y los resultados son malos.
** carga laboral-estresores 2019vs2020
esta vez no trabaje en toda la semana. solo hice mi teletrabajo que me
resulto bastante llevadero, salvo en algun que otro momento de los
dias en que estaba cursando rebotes fuertes no tuve problemas. Al
comienzo de la semana pensaba que podia estar beligerante con la gente
o tener nerviosismo agregado por el tener que rechazar ventas o cosas
asi, pero felizmente la semana transcurrio muy buena en ese sentido y
muy satisfactoria de modo que no afecto para nada el tratamiento, al
contrario le dio un poco de actividad, pq tambien creo que no seria
bueno el excederse en el estar sin hacer nada.
Por el resto del negocio me preocupe cero, y por el tema de la obra,
decidi levantarme temprano a las 7hs cuando venian los pintores el
jueves y viernes y estar presente y fui a las pinturerias a comprar lo
que hacia falta sin ninguna dificultad. No se si el estres de ayer
viernes en el transito por ir a Alem 1666 internamente me causo el N9
de la tarde, eso es algo que desconozco, pero en el momento no me
senti nervioso de mas ni nada. 
No me surgieron cuestiones dificultosas de llevar como en el
WD2019. Menos mal pq eso ayudo a que pueda transitarlo en forma mas
tranquila.
** otros sintomas anexos
no he notado dolor articular esta semana, ni cansansio excesivo salvo
el usual de siempre, ni cambios en el apetito.
las series las pude hacer todos los dias del tratamiento creo que un
solo dia me resulto un poco mas dificil  hacerlas pq ya estaba con un
N4 mientras las hacia.
El unico sintoma que puedo aportar es el aura en el ojo izquierdo que
dura unos 5 minutos, que generalmente se da cuando me pongo a ver el
tv del living y luego se va, no necesariamente precedio migrañas, Y
este sintoma calculo que lo he tenido hasta ahora tres veces.
En este WD no experimente ningun nivel de "inteligencia" extra que me
habia parecido tener en el pasado con otros WD.
Tampoco trastornos de sueño.
Tampoco parestesias.
Si ciertas cualidades imaginativas libres que la mente desarrolla en
sus dialogos internos en la noche cuando me levanto, que se evidencian
mayormente en los personajes usados como que fueran mas vividos y se
prestaran al dialogo literario. Nada loco, sino como mas fluido.
Un sintoma muy marcado que veo es la voz, la veo muy afectada muy
cascada en los audios.
Y tambien un poco de "maradonismo" en los audios o sea como signo de
una lentitud mental que no se condice con lo que observo a nivel
pensamiento y escritura.
** cambio de dieta en medio del tratamiento
desde el viernes 6/3 me paso a una dieta de almidon (vegana) sin
productos artificiales con el objetivo de ver si son los productos
quimicos los que me afectan en la migraña. 
** reduccion de jaquecas leves con actividad
tuve dos episodios de levantarme de una siesta (incluso con toma de
clonazepan 0.5 para inducir dopacion mas profunda) que no fueron
efectivos para aplacar sino al contrario agravaron cuadros, pasando a
veces de N4 a N6.
Uno el sabado [2020-03-07 sáb] que salgo al patio y me pongo a
pintarle el mueble a la Cami y luego me siento en el patio, y demas y
el N5/6 pasa a N0.
y el otro el [2020-03-09 lun] que me levanto con N5 y me pongo a hacer
tareas de cocina, haciendo la leche de avena, moliendo sesamo y demas
y tambien paso de un N5 a un N0.
O sea en ambos casos no se trato de tareas hiperactivas como las
referidas en el 2019 con la limpieza de la cocina sino de distraccion,
o hacer otra cosa quiza que no sea estar acostado.
** uso del MIG para migraña extrema
que bueno seria tener la opcion de tener un medicamento de rescate
para un verdadero N9 y que te responda a los 30minutos. El problema
reside en que se lo arruina con el sobreuso.
** WD malogrado por el COVID-19
creo que si bien es cierto que estoy relevado de tener que ir a
trabajar la situacion que se vive no es muy propicia tampoco para
recuperarse por la gran preocupacion que causa y por la excesiva
cantidad de actividad nociva que causa (ver tele mas que todo) y el
progresivo debilitamiento.
** nefasto comienzo de Abril
en cuatro dias cuatro migrales dos por dia dia por medio dando un
promedio de uno por dia.
** patron abril
se evidencia un patron de dolor tipo N5 entre las 15.30 y las 17hs,
que con suerte se resuelve con un migral y sino rebota a un N8 a la
hora y requiere otro migral para resolverse, y a veces no es tan
limpia la resolucion.
Pero es notable que esta cursando con mucha serie a la siesta entre
cuatro y cinco horas a veces.
** achatamiento de la curva
evitamiento de un segundo migral mediante irse a dormir directamente y
padecer, total no tenemos nada que hacer, salvo que en ese
padecimiento tengamos largas horas de impiadoso N9 podriamos querer
tomar otro, pero sino estariamos gastando muchos migrales en prolongar
actividad innecesaria como seguir viendo horas y horas de series en
una dinamica circular viciosa como fue en años anteriores cuando
tomaba migral para seguir programando y esa misma programacion me daba
migraña.
En ese sentido aprovechar la cuarentena.
* consultas Dr Romero
** [2020-04-20 lun] telefonica por covid
me dio que tome 8mg de cortypiren dia por medio por un periodo largo,
pero quedo pendiente a la proxima consulta cuando yo le dije si era
conveniente inmunosuprimirse frente al Covid-19. 
alternativamente probaremos nuevamente con Silbelium 10mg.
