| [2019-02-18 lun] | MIG-12hs       | i600-17hs        |               |   |   |
| [2019-02-19 mar] | MIG-03hs       | i600-12hs        | MIG-23hs      |   |   |
| [2019-02-20 mié] | i600-15hs      | MIG-15.45hs      | C10mg-16.30hs |   |   |
| [2019-02-21 jue] | C20m-8hs       |                  |               |   |   |
| [2019-02-22 vie] | C20m-8hs       |                  |               |   |   |
| [2019-02-23 sáb] | C20m-8hs       | Nx-18hs          | Nx-22.30hs    |   |   |
| [2019-02-24 dom] | C20m-8hs       | Nx-22.30hs       | MIG-00hs      |   |   |
| [2019-02-25 lun] | C20m-8hs       | i600-23.30hs     |               |   |   |
| [2019-02-26 mar] | C20m-8hs       |                  |               |   |   |
| [2019-02-27 mié] | C20m-8hs       |                  |               |   |   |
| [2019-02-28 jue] | C20m-8hs       |                  |               |   |   |
| [2019-03-01 vie] | C20m-8hs       |                  |               |   |   |
| [2019-03-02 sáb] | C20m-8hs       |                  |               |   |   |
| [2019-03-03 dom] | C20m-8hs       | Dic50m-15hs      | MIG-19hs      |   |   |
| [2019-03-04 lun] | C20m-8hs       |                  |               |   |   |
| [2019-03-05 mar] | C20m-8hs       |                  |               |   |   |
| [2019-03-06 mié] | C10m-8hs       |                  |               |   |   |
| [2019-03-07 jue] | C10m-8hs       |                  |               |   |   |
| [2019-03-08 vie] | C10m-8hs       | FIN cortiterapia |               |   |   |
| [2019-03-09 sáb] |                |                  |               |   |   |
| [2019-03-10 dom] | Dic50m-7hs     |                  |               |   |   |
| [2019-03-11 lun] |                |                  |               |   |   |
| [2019-03-12 mar] |                |                  |               |   |   |
| [2019-03-13 mié] |                |                  |               |   |   |
| [2019-03-14 jue] |                |                  |               |   |   |
| [2019-03-15 vie] |                |                  |               |   |   |
| [2019-03-16 sáb] | Dic50m-4hs     |                  |               |   |   |
| [2019-03-17 dom] | Dic75m-16hs    |                  |               |   |   |
| [2019-03-18 lun] | Dic50m-14hs    |                  |               |   |   |
| [2019-03-19 mar] | Dic50m-16hs    |                  |               |   |   |
| [2019-03-20 mié] |                |                  |               |   |   |
| [2019-03-21 jue] | Dic50m-14hs    |                  |               |   |   |
| [2019-03-22 vie] | Dic75m-19hs    |                  |               |   |   |
| [2019-03-23 sáb] |                |                  |               |   |   |
| [2019-03-24 dom] |                |                  |               |   |   |
| [2019-03-25 lun] |                |                  |               |   |   |
| [2019-03-26 mar] |                |                  |               |   |   |
| [2019-03-27 mié] | Dic50m-19hs    |                  |               |   |   |
| [2019-03-28 jue] | Dic50m-8hs     |                  |               |   |   |
| [2019-03-29 vie] | Naprux-8hs     | Naprux-16hs      | MIG-17hs      |   |   |
| [2019-03-30 sáb] |                |                  |               |   |   |
| [2019-03-31 dom] | Naprux-19hs    |                  |               |   |   |
| [2019-04-01 lun] |                |                  |               |   |   |
| [2019-04-02 mar] | Naprux-18hs    |                  |               |   |   |
| [2019-04-03 mié] | Naprux-18hs    |                  |               |   |   |
| [2019-04-04 jue] | Naprux-18hs    |                  |               |   |   |
| [2019-04-05 vie] |                |                  |               |   |   |
| [2019-04-06 sáb] | Diclo50m-8hs   |                  |               |   |   |
| [2019-04-07 dom] |                |                  |               |   |   |
| [2019-04-08 lun] | Diclo50m-15hs  |                  |               |   |   |
| [2019-04-09 mar] | Naprux-16hs    |                  |               |   |   |
| [2019-04-10 mié] |                |                  |               |   |   |
| [2019-04-11 jue] |                |                  |               |   |   |
| [2019-04-12 vie] |                |                  |               |   |   |
| [2019-04-13 sáb] | Naprux -18hs   |                  |               |   |   |
| [2019-04-14 dom] | Diclo75m-8hs   | Naprux - 14hs    | MIG-17hs      |   |   |
| [2019-04-15 lun] |                |                  |               |   |   |
| [2019-04-16 mar] |                |                  |               |   |   |
| [2019-04-17 mié] |                |                  |               |   |   |
| [2019-04-18 jue] | Diclo50m-16hs  |                  |               |   |   |
| [2019-04-19 vie] |                |                  |               |   |   |
| [2019-04-20 sáb] |                |                  |               |   |   |
| [2019-04-21 dom] | Diclo 50m-15hs |                  |               |   |   |
| [2019-04-22 lun] |                |                  |               |   |   |
|                  |                |                  |               |   |   |

* [2019-02-18 lun]   
tomo el migral tipo 13hs mas por evitar el rebote que por necesidad
real, y luego me doy cuenta que al rato la molestia sube, pero lo
mismo era un dia complicado pq tenia un compromiso y grande a la
tarde, pero todo termino bien con solo un ibu de refuerzo.
* [2019-02-19 mar] 
no pude llegar al mediodia. Me deperte a las 3 am con un N6 y tuve que
tomarme un migral, fue efectivo en unos cuarenta minutos, y me volvi a
dormir a las dos horas, luego comence el dia con normalidad.
Tipo mediodia se empezo a arruinar el dia y me tome un ibu, y ahi note
la diferencia de la falta de ambiente para enfrentar un cambio o al
menos tolerar y darle batalla a una reduccion en la toma de
analgesicos aguantandose el dolor. Pq no pude retirarme y pq mi casa
es la oficina o no tengo casa. Me vine para hacerme un arroz, el cual
fue demorado y ya no puedo comer mas en la cocina pq me da asco y me
retire al dormitorio, y bastante bien, pero me hizo mal el agregado de
la pasta de aceituna que la estoy repitiendo hasta ahora (quien dice
que no tenga un aditivo) y luego no puedo sustraerme y ya estoy casi
en un N5 como para estar reposado comodo intentando dormir.
Y tengamos en cuenta que tengo un desfasaje de sueño pq el migral
nocturno me dejo sin dormir y tendria que haber tenido una siesta.
Tipo 15.30 Fede amablemente se va pq yo llegue al limite de aguantar
con un N4 levantado, y me dispuse a acostarme relajado, y el problema
no era tanto el dolor, pq ya estaba libre para relajarme y tenia mucho
sueño, sino que no podia tumbarme para ningun costado, era enorme la
presion, mas que ninguna otra vez pero sin puntada, y cuando me
levantaba salia el aire. El dolor fue en aumento, en todo momento
estuve incapacitado, creo que llegamos a N7 (en oscuridad, ni siquiera
pensar solo dormir o intentar). Puedo dormitar una hora, y la molestia
deviene ya con nausea, y un asco total por la repeticion continua de
la pasta de aceituna (ya la otra vez me habia pasado en el marques),
crei que vomitando aliviaria pero no hubo modo, solo tome agua, y mas
agua y aguante, tipo diez de la noche luego de dormirme cada vez por
mas tiempo, parecia que me mejoraba y no.
En realidad el dolor bifronte, como si me levantaran la mollera desde
adelante para sacarme el cuero cabelludo con una cuchara de albañil se
transformo en una hemicraneal limpita de lado derecho no totalmente
intensa pero si un N5 con vias a aumentar. Eran las 23hs y no habia
comido, estaba debil y no creia que podia aguantar una migraña
verdadera durante la noche, entonces me tomo 1 Migral a esa hora, es
efectivo en una hora desaparece el dolor, en el mismo momento molesto
como estaba me hice el licuado, y lave los platos por las cucarachas
de la cocina, me tome solo vaso y medio de licuado y me dormi. No muy
comodamente, pero bastante mejor que la tarde.
* [2019-02-20 mié]
A la mañana me levanto debil, tembloroso, iba a decir como tension
baja, me tomo un vaso de licuado, y me compro facturas, y desayuno un
cafe, con dos facturas dulces, que como con ganas, y un beroca que
tambien paso sin dificultad, no mejoro, pero pasable, y me voy a pagar
boletas, maso.
Me mido la tension y me da 12/6 o sea si baja.
segunda medida ya cinco minutos despues de estar sentado: 
12.3/ 6.8 y 98 ppm. 
Voy al neurologo y tengo que esperar dos horas que me atienda. Ya me
habia mejorado bastante el sintoma de baja tension, y tenia una
jaqueca creciente pero no era todavia amenzante. 
Luego almuerzo en el hp bien, en un ambiente agradable y al final del
almuerzo tomo un ibu, y al llegar aca me va creciendo la jaqueca y no
lo pienso mas y me tomo el migral para abortar cualquier problema.
Luego de 45 minutos de migral solamente se agrava la migraña, esta
bien que la situacion hace que no pueda salirme de la situacion y me
tomo un C10mg y felizmente el fede me compra lo que me hace falta de
viveres minimos para sobrevivir y ya daremos por terminada la jornada
y me podre acostar.
Creo que faltan solo dos dias para finalizar esta tortura. Pero creo
que la pauta que me dio el doc puede aliviar el status migrañoso.
Me acuesto finalmente pero no me hizo efecto alguno el migral, el
dolor fue mayor que el dia anterior creo que facil un N7 concentrado
en la frente, bifronte, lo unico que con menos sintomas
nauseosos. Pero llegado un momento me levanto al baño e intento por un
lado evacuar con la enorme dificultad del dolor de cabeza, y por otro
lado la nausea, y al desistir y levantarme espontaneamente y sin
provocarlo vomito moderadamente parte del almuerzo muy poco, con un
fuerte olor al saborizante de la gaseosa y desde ahi me empiezo a
mejorar y en poco cede el dolor. Me veo una pelicula en cama y solo
ceno un te con dos medialunas que tenia compradas y duermo mucho
(quizas por la flu) y me levanto normal. Y comienzo la cortiterapia.
* [2019-02-21 jue]
tome el c20mg a las 8hs y el dia no fue muy facil que digamos pero
tampoco abuse y creo que lo administre bien, abuso hubiera sido si a
las 12hs iba yo al banco con el calor que hacia unos 38 grados y me
tiraba al albur de comer "afuera" a un sitio desconocido, buscando
emular la experiencia de ayer, en vez de eso puse a hervir arroz y fue
el Fede al banco y yo me quede, comi tranquilo en el fresco y descanse
un rato, y luego el Fede se fue y aprovechando que no me dolia la
cabeza (aunque si tenia otras molestias fisicas pero las ignore, como
cansansio e incipiente dolor articular), me puse a adelantar trabajo y
despejar mi escritorio preparando el cambio de oficina. Ahi me di
cuenta que si influye el ambiente en el malestar general, pq una tarde
de extremo calor como esta, donde tenes un aire que no te da abasto pq
le abris la cocina o la ventana y encima le metes humo de cigarrillo
adentro te hace mas miserable el tener que estar con esta rutina que
de por si es fea. Y creo que en ese sentido la oficina nueva va a
mejorar mucho. o sea el ambiente, no solo dando mas luminosidad que
aca que es poca o mucha de mas (salvo los pocos dias nublados), y
espacio, sino el aire mucho mayor con ausencia de humo.

Volviendo al tema tratamiento, creo que hay que esperar, a ver que
sintomas aparecen y que pasa cuando empiece el rebote.

La tarde y noche transcurrio bien sin sintomas molestos de ningun tipo.
* [2019-02-22 vie]
duermo bien nuevamente aunque voy despertando desde tipo 5am con un
incipiente y me voy preguntando como abordarlo, pq era chico como para
tomar un migral, y tenia miedo que tomando un ibu se arruinara,
entonces segui durmiendo y no tuve problemas.
En la hora de levantada la distraccion hace que uno no sea muy
consciente de la molestia y ya tome el C20m.
Aunque estoy consciente que es el segundo dia y puede haber rebote,
pero siendo como es el dia de hoy complicado no creo que dude en tomar
un migral. y veremos que pasa. 
Lo que noto es sueño y cansancio, a pesar de haber dormido mucho, pq
ya a las 22 me dormi, estoy muy cansado y debilitado, quizas sea por
el corticoide.
Como vengo notando la proclividad para dormir, la cual es bienvenida
pq me hace innecesaria la toma de cualquier otra porqueria que tampoco
quisiera tomar, me la da la flu.
Este viernes era un dia particularmente dificil, lo describo pq uno
pierde la memoria rapidamente, habia que mudar la oficina sin parar de
trabajar y el dia era bochornosamente calido, era el final de una
semana de tremendo calor. Se me habia ocurrido ayer que podia llevarse
la mesa de vidrio con un operativo coordinado FAbian/Osver/Kangoo/Fede
en el medio de la atencion, pero tenia que ser muy coordinado. El
viernes le recuerdo al Fede por las dudas que lo haga asi pq yo como
estaba no iba a poder ayudarle. Entonces el dice que si que le demos
para adelante, y encintamos la mesa y cuando llegan los muchachos
bajan las cosas y cargan, primera prueba de estres, felizmente pasada.
Sigo atendiendo y pasando papeles aca yo solo. Felizmente Fede toma la
iniciativa de llamar a la Cami para que lo ayude a el en la mudanza y
se hacen cajitas de mudanza y solos se las apañan para trasladarse y
acomodarse sin interferir conmigo, incluso pude hacerme un arroz y
comerlo en tiempo y forma en el medio.
Pero ... en el medio de todo lo anterior se descarga la bomba atomica
no esperada en "ese preciso momento" (o sea justo en el momento en que
estabamos mudando la oficina en el medio de la atencion de la gente, y
yo en el segundo dia de corticoides), ih me llama, no diciendome que
me acordara de comprarle el lavarropas, sino con un berrinche de
adolescente diciendo que estaba en Garbarino con la tarjeta en la mano
decidiendo entre dos modelos que no sabia cual era cual, en fin,
describir el alcance y el desastre de la situacion excede lo que este
post requiere. Felizmente no me saque de quicio, sino que segui en lo
mio, la llamo en 5 minutos, y me dice que ya se volvia, que estaba
manejando que lo comprara yo, entonces agende en el medio de ese dia
ya de por si dificil comprar un lavarropas. 
Con el calor que hacia, con ciertas coordinaciones bien hechas pude ir
a Fravega comprar, retirar, llevar.
Podria haberme quedado, pero quise estar presente cuando lo
llevabamos, asimismo la cara de culo la tuvo igual por mas que le
lleve ese lavarropas. Pero luego el calor, la incomodidad de la casa,
el aire que no es muy benigno alla cuando hace calor, la comida
pesada, el problema que el lavarropas no centrifugaba bien, y como
broche de oro que se trabara la pileta y pum!!! viene la Carla, ahi
decidi venirme.
Asimismo el viernes increiblemente siendo el segundo dia de WD y
siendo que toco por suerte asi un dia de mierda climatologicamente y
por compromisos no tuve ninguna molestia ni tuve necesidad de tomar
nada.
* [2019-02-23 sáb] N6
el sabado luego de venirme me dedico a comprar las cosas para el
licuado y verduleria y arreglar pileta.
Ese fue el factor principal que necesitaba hacer sino quizas me
hubiera quedado, pq si no arreglaba la pileta se me complicaba el otro
tema que anda rondando y es que el problema de la humedad del 5°C, y
yo con la pileta que pierde, no es bueno que venga el plomero a ver
eso. Felizmente analizo el problema y decido que no voy a sacar los
caños de pvc, es bueno informarse por youtube donde hay tutoriales
profesionales de todo tipo y uno aprende un monton, ahi vi que
despegar un caño de pvc es un trabajo enorme, entonces decidi
poxilina. Y sello bien.
El dolor ya era incipiente a ese momento. Un poco molesto, pero
pasable, luego de comer, mijo con calabazas, decido tomar un
analgesico. Pense en un ibu, pero me decante por un naprux. Y el dolor
seguia a cierta hora pero no era incapacitante, entonces tenia dos
opciones o tirarme o ponerme a trabajar, y me puse a limpiar, limpie
los vidrios del living, barri, encere, y en ese momento llego ih y
Fede, trajeron la mesa, armamos, y terminamos de limpiar el living,
luego se fueron y termine de acomodar y me tire en la cama en el aire.
El dolor crecio un poco pero nunca fue muy fuerte. Pense que podia
incluso ver una serie y comence a ver Perros de Berlin, pero al ver
que tenia mucho parpadeo de luz lo deje, luego alternando dormidas con
toma de agua, con una taza de licuado, mas dormidas, en ningun momento
me senti mal del estomago, me tomo los remedios de la noche, y a las
22.30 me tomo otro naprux como rescate y me duermo, y a medida que la
noche transcurrio, se fue diluyendo el dolor, pero nunca deje de
dormir. Si tuviera que evaluar el nivel alcanzado diria que fue un N6
en general considerando que aunque fue sabado tuve en el medio el tema
de tener que hacer cosas y estar en tension, no es lo mismo haber
transcurrido en un sabado cualquiera con la heladera bien llenita sin
problemas de traslados, ni mudanzas, ni canillas, ni cucarachas y el
dptito bien limpito, y la ropita lavadita y planchadita para el lunes.
* [2019-02-24 dom] N8    MIG
despierto libre de dolor, con el despertador de las 8 para el
corticoide, lo tomo y sigo durmiendo y asi hasta las 11hs, luego me
levanto desayuno te con galletas, se me plantea tomer un naprux
preventivo, y decido esperar, lavo dos camisas y todo ok solo siento
el esfuerzo fisico como si fuera mas de lo que hago, como el doble o
triple, pero me distrae o me saca en este caso la atencion a la
cabeza, no tengo hambre aun.
Son las 15hs he tratado de hacer actividades, y la voy llevando, con
algo de cansancio y aburrimiento, como estoy solo no como si no tengo
hambre y no tengo hambre. Solo cansancio, por eso me tomo un
beroca. Lo mismo me gustaria comer algo mas tardar 15.30 para no
desarticular tanto las comidas y tratar de hacer una siestita. No
viene mal el dia de relax de todos modos.
...
El domingo llegaba a su fin, lo que tocaba era el aburrimiento ya. En
eso giro la cama, y me gusta.
Pero en los primeros momentos de adaptacion me daba el aire frio muy
de golpe quizas no se. 
Yo ya habia apagado todo, luego activo de nuevo wifi, la Cami me
pregunta si le pago un delivery, y luego ih me pide que le compre un
tv, eso me enoja y le contesto mal, no es que eso haya disparado una
emocion violenta en mi interiormente perceptible, pero desde ese
momento se disparo una migraña total. Previo a esto unas dos horas
antes me habia tomado un Naprux quizas como preventivo para
incipientes, o pq estaba en el fondo nervioso pq al dia siguiente
tenia oficina, aunque en ese momento no era consciente del compromiso.
La migraña crecio de golpe, muy rapido y se agravo con el nerviosismo
de la incomodidad que me dio el lugar nuevo, y me vino a la mente que
yo DEBIA estar en la oficina hoy por la mañana pq no habiamos probado
la impresora y Fede tenia que imprimir todo de frente y encima
soportar un primer dia de adaptacion a una nueva oficina, y no podia
faltar, entonces decido tomar un migral.
Felizmente hizo efecto y dormi bien y me levanto bien para seguir con
el WD.
* [2019-02-25 lun] N7
me levanto mas o menos normal, desayuno enteramente licuado, y tomo el
C20 puntual a las 8hs. Voy a la oficina, y no llevo nada ni licuado ni
remedios.
Y alli un poco nervioson empiezo a sentirme mal. Y le pregunto al Fede
si no tenia Ibu, quizas me hubiera tomado uno, entonces me hice un
cafe cargado de dos cucharadas con dos de azucar que me parecio muy
rico y me puse bien, fui al banco trabaje hasta las 12 y volvi, me
hice el arroz, lo comi con mucho hambre (me quede casi corto y eso que
hice 6+1 mas un tomate), y a cada momento me parece que se me
congestiona la frente-sien con una especie de parestesia-contraccion
que en el fondo se hace esponjosa y propensa al dolor con alguna que
otra puntadita que se va mas adentro.
Dormi una siesta de una hora o menos con sueños y todo, y luego no fui
a la oficina, sino que me quede e hice muchas cosas en el dpto,
incluso me fui a pagar los audifonos que compre, luego me puse a
cocinar y comi, hasta ahora las 21.30 todo bien , solo que comi mucho
aunque vegetales mayormente, voy a esperar un rato para acostarme.
Solo un poco de dolor de espalda.

A la noche me vino una migraña hemicraneal pero mas manejable, decidi
probar con ibu600 solo para ver, que onda por las dudas pero no paso
nada, ni para bien ni para mal, salvo que haya sido el causal de la
suavizacion de la migraña con respecto a la del domingo noche.
Tambien puede haber influido el acomodo de la pieza, acomodo la musica
con un musiquero nuevo que sirva para toda la noche y me dispongo
comodamente sin aire por la temperatura (eso tambien fue positivo) y
lo bueno fue que pude dormir!!!.
Cuando me despertaba para ir al baño notaba que el dolor era intenso
en el desacomodo, pero luego de acomodarse permitia volver a dormirse,
y pensaba que iba reduciendose pero no, a la mañana lo siento igual,
me planteo que no podre ir a trabajar, pero estoy todavia en duda,
noto una cierta disminucion, aunque estoy con un nivel de migraña muy
superior a lo aceptable para salir de casa.  Seria romper los esquemas
y ver que pasa, quizas el movimiento sea positivo, al menos voy y
hablo con el Fede en persona si no puedo me vuelvo.
Lo bueno es haberse animado a no tomar migral y a recomenzar
nuevamente.
* [2019-02-26 mar]
me levanto y voy a la oficina, en el proceso de 7 a 8.30 ya disminuye
mucho la intensidad del dolor, sin ninguna nota punzante, ni opresiva
grave, quedaba un resto que todo indicaba iba a desaparecer, y asi
fue, lo que iba a ser ir por ir se termino por convertir en una mañana
gigante, o sea pase los recibos hasta las 11.10, y corte ahi pq me
cagaba y me fui al banco, y pase por dpto, alli fui al baño y me tome
una bolella casi de licuado y volvi a la oficina a pasar todas las
ventas hasta casi las 14hs que me volvi, desensille y me hice un
espectacular arroz con calabaza incorporada, con rabanitos, y no le
puse queso, luego me tire y tuve una experiencia sensorial unica en la
siesta pq quedo trabada un tema de mozart que se repitio y se repitio
y me dormi profundamente como ayer, quizas mas de una hora, y me
desperte bien, con dificultad como si fuera de mañana, por obligacion,
pq tenia que tomar la posta de las autorizaciones, y tenia que
despabilarme, y en unos minutos me sobrevino este N7 mas o menos que
no me permite nada agradable. 
Para no tirarme en la cama, decidi ponerme a hacer cosas utiles, como
diciendo para sufrir en la cama, sufro mientras hago y de paso a lo
mejor se me pasa, limpie con blem todo el living, todo!, y barri,
limpie con blem el dormitorio, y me planche dos camisas mc, pero el N7
luego de planchar subio!.
No creo que sea arreglable con ningun tipo de analgesico. Solo queda
soportar y ver cuantas horas me lleva. 
El del domingo fue abortado por migral, el lunes llevo toda la noche y
se corto a la mañana a lo macho, y parece haber vuelto a las 16.30 y
el del sabado duro toda la noche. 
El sabado tome dos naprux, el lunes un ibu, veo ahora en estas 8hs
hasta las 12 de la noche que pasa sin tomar nada. 
Estoy repitiendo el rabanito!!, le puse a lo que comi una cucharada de
tahini. (tampoco en exceso)
 
Tampoco debo asombrarme de las diferencias entre el WD17 con el actual
pq en 6 dias tome 120mg y en el 17 en 6 dias tome 560mg o sea casi 6
veces mas. Y asi mismo se registran molestias de rebote que
sobrepasaron el umbral del corticoide. 
No se como funcionara el mecanismo de rebote en el cuerpo, pero lo
cierto es que en los ultimos 7 dias al cuerpo le ingresaron 2 migrales
cuando estaba acostumbrado a tener 12. 
O sea que no creo que vaya a cumplirse detalladamente lo que esta en
el cuaderno. 
Aparte el error gravisimo del 17 fue la pauta muy larga de corticoide,
ni hablar del 15, casi suplanto una dependencia sicologica por otra,
esto permite lidiar con el dolor desde ahora.
A nivel de que hay que cambiar los procesos de vida que llevan a tener
dolor. Que no se puede tener el esquema mental de que surge dolor-tomo
pastilla y se va dolor. No hay pastilla que se lleve dolor.
El esquema ahora es surge dolor - aguantar dolor. Por eso hay que
decidir si aguantar el dolor, hacer frente al dolor, seguir con la
vida, reposar, dormir, comer, etc. Pero no hay pastilla, que vamos a
hacer. Cuando caes en una pastilla que crees que sirve (como paso en
el 17/18 con el ibu) caes en el sobreuso y eso tambien es malo. 

Luego se produjo un cuasimilagro que esta descripto en esquemas.org me
puse a limpiar arriba de la mesada y baje de un N7 a un N2, luego me
dispongo a acostarme y la puta me parecia que se me posaba la bicha, y
entonces me dije rapido antes que reine le gano de mano, y corri, y me
fui a poner las zapas viejas, busque el agua y me hice 15 min de
bici!!! a gran velocidad (35!!) todo el recorrido, y me puse a hervir
el mijo, y creo que estoy mejor que cuando me acoste o sea ahi estaba
en un N3+ y ahora estoy en un N2 estable, o sea que el ejercicio me
hizo bien  aparte estoy levantado y tengo mas energia. 

Luego me dispongo a domir y se produce una especie de milagro nuevo,
se produce una noche de ensueño como casi nunca he tenido en este
dpto, puse el aire en sleep y me tape con la sabana a veces con el
palette, y alternaba entre esos pero con comodidad sin haber tenido
que apagar el aire, y con una sensacion de confort total, y la musica
de mozart toda la noche, que sonaba bajita casi imperceptible y que
estaba ahi a lo lejos, y el tacto de las sabanas arco iris, y tambien
que me habia puesto en frente y nuca lavanda en crema, dormi toda la
noche sin dolor en absoluto, y sin sobresaltos. tome agua cada vez que
me levante. 
* [2019-02-27 mié]
despues de la buena noche de anoche me levante a las 7, tome agua,y me
puse a hacer dos series de los ejercicios de brazos que me costaron un
monton como si estuviera muy oxidado y abri la ventana y me puse en la
bici 10 minutos, luego me bañe, y me tome el licuado y sali fenomeno a
la calle. Lleno de energia.
O sea que hoy sali a la calle con 10 min de bici, y dos series y baño
con el mismo tiempo de siempre. 
El dia transcurre bien, solo que mas cansado, pq va haciendo mella en
mi, el no haber dormido la siesta y el haber tenido gimnasia mi
dia. Pero sigo igual. Y estuve clavado con esto de las autorizaciones.
Se podria cambiar eso en el futuro y limitarlo a cierto horario. 
* [2019-02-28 jue]
ahoche una noche diriamos casi igual o igual que anoche, con profundas
dormidas, muy comodo, pero al despertar para ir al baño tenia un leve,
y vi la hora faltaban 5 para levantarse entonces me levanto, y hago
los ejercicios, y me pongo a la bici, y me puse con energias y ganas,
y dije voy a hacer 15!!! y mierda hice 15 pero con tramos de alta
velocidad (mas de 40) y levantado a veces, casi termino acalambrado
pero bien. Muy bien la rutina asi. 
La mañana curso con algunas molestias intermitentes hasta el momento,
que no le llevo atencion, sin siesta pero con descanso y relax, no
llegan al N2, sigo leyendo con profundo focus, y en oficina es mas
facil al menos de mañana que desaparezcan con la actividad.
Luego de una ajetreada tarde que fue desde irme a la oficina, cerrar,
ir en la kangoo con el Fede, tomar un cafe a las apuradas, con un N2,
atender al Andres, ir rapido a Dastolfo, ponerme las protesis, salir
de Dastolfo y pasar una linda tarde con las chicas, fui llegando
cansado pero a un estado N0. Me vuelvo y me cocino una quinoa para
comer algo y dormir.
* [2019-03-01 vie] N9
este dia sufri la primer gran migraña del proceso y la trascurri pura
sin medicacion.
El dia empezo bien, fue el primer dia que lleve la botellita, entonces
no sufri hambre y perdi la nocion del tiempo, cuando eran como las 14
me digo me voy, y surgio el tema de la mesa de impresora, ahi el fede
dice vamos a verla, vamos y la compramos la traemos y ahi sufri un
poco de estres, y comida distanciada, cuando llego a mi casa a las
14.30 como apurado lo que habia, y ni bien termino de comer, llega el
plomero, empieza a hacer la tarea y emite un olor muy intenso de
pastina en el dpto que se fue concentrando hacia el lugar donde yo
estaba pq el aire lo absorvia. Y yo que estaba tratando de pasar el
tiempo no podia concentrarme pq ya me empezaba un dolorcillo y no
podia combatirlo ni con relax ni con actividad, ni con nada, entonces
me puse a programar algo lo cual me enrollo aun mas y cuando termino
el hombre el olor era muy intenso y solo atine a juntar mis cosas e
irme, alli el dolor ya era considerable.
Me voy a la oficina, y dejo el bolso y me voy a comprar la
calculadora, decido ir lejos ya con la idea de conjurar el dolor con
actividad, hacia calor, mucha luminosidad, mucha gente y el dolor era
grande, y todo bien, luego kangoo, y al llegar a casa, amiguita de la
Cami que viene y yo con ih en el patio, o sea todo muy negativo para
decir que ayude a solucionar el tema (p.e. sin eso ultimo podria haber
desensillado y hecho gimnasia supongamos). 
A pesar de mis esfuerzos de permanecer normal, a pesar del set de
herramientas reducidas a mi favor, se me fue agravando la cosa,
aprovecho que ih se fue a visitar los nietos, y las chicas se fueron a
comprar criollos, y me voy al baño, ya estaba nauseoso y no tuve
vomitos ni quise esforzarme mucho por provocarmelos, pero estaba ya
migrañoso.
Me acoste, a partir de alli empezo una migraña real, hemicraneal,
fotofobica, muy nauseosa, constante, tipo N8 intensa pero permitia
dormir con gran dificultad por el tema nauseoso, y agravaba con el
movimiento.
No comi nada ni tome la medicacion de la noche, ni agua tomaba.
empece a tomar traguitos de a poco.
como a las 23 descubro reliveran vencido del 2017 y tomo y eso me
alivia un poco las nauseas, lo cual lo repito a las 4 am. Tomo la
medicacion a mitad de la noche, y voy alimentandome con licuado de
apoco durante la noche, pero la migraña no cedia ni un poquito, pero
al disminuir la nausea ya podia dormir de mejores formas.
Solo pensaba que al llegar las 8hs podria tomar el corticoide y una
hora despues cederia, o bien por el tiempo ya asi fue, tipo 9/9.30 me
levante y desayune normal.
* [2019-03-02 sáb] N9
hoy luego de la migraña de ayer quede con cierta resaca menor, que se
manifesto a la siesta, a pesar de todo segui adelante, y cuando tipo
19hs me empezaba un dolorcillo a molestar me pongo a hacer las 3
series, que aunque parezcan que son poco no lo son, y saque el aparato
de la romi, que no es lindo como la bici pero algo es y lo use
bastante y tuvo el efecto de por una parte limpiarme 100% el
dolorcillo base que rondaba y por otra animarme fisicamente lo que
estaba un poco caiducho o en cierta forma fusilado por el mal dormir
de anoche, pq fue como una biaba que me pego la bosta.
Luego de esta experiencia donde se me fue cien por cien la resaca,
incluso pense estar bien, la Cami planteaba salir y yo pensaba poder
llevarla, incluso esperarla en el centro para traerla a la madrugada,
y felizmente se frustro la salida.
Tipo 23 o 00 se dispara una migraña identica a la noche anterior, que
yo supongo es la misma que vuelve, pero mas pura y mas punzante mas
incisiva, o bien yo mas cansado para soportarla, no obstante menos
problemas nauseosos, pero no pude mas que dormir de a trechitos de no
mas de 45 min una hora, y levantandome mayormente al baño, comerme una
ciruela y seguir durmiendo, incluso ni siquiera podia dormir del lado
de la migraña.
Cuando faltaban dos horas para las 8, ya casi me volvia loco, y solo
queria esperar al corti.
Pero creo que en esa hora claudico, pq no fue como ayer, que despues
del corti tuve que esperar una hora mas, aca casi como que fue casi
instantaneo, o sea fue mas como vencimiento del plazo, pero fue muy fuerte.
* [2019-03-03 dom]      MIG
hoy ya no es como ayer, no se si el acumulado de dos dias de mal
dormir, o que el dia me parece muy luminoso, tengo fotofobia desde el
dia, y a la siesta misma me parecia in crescendo las molestias,
entonces a las 15 decidi probar con un diclo 50 a modo de paliativo de
la resaca migrañosa, pero llevo casi 45 min ya y no tengo agravamiento
pero tampoco mejora total.
No me duermo y tengo esta debilidad/cansansio fruto de haber dormido
mal, prefiero guardar el sueño para la noche.
A la tarde no iba en mejora, y luego de un poco de compu, en donde
alterne los descansos con las 3 series, vi que no habia ningun tipo de
solucion, y decidi tipo 19hs tomar un MIG, en el medio de la toma el
dolor llego a N9.25 y cedio en unos 20minutos ya. Y me levanto
enseguida y en razon de una hora ya estaba normalizado, cene bien y
luego dormi bien hasta las 6hs. que me desvele, y espere el
corty. Luego del cual no quede tan bien como estaba de madrugada, pero
ya me levante.
* [2019-03-04 lun]
* [2019-03-05 mar]
anoche dormi bien salvo por el episodio de gases cursado con dos
factor ag, y hoy levanto temprano a pesar del feriado por el tener que
estar con la obra en la casa y luego fui al easy, aparentaba iniciarse
un proceso pero quedo ahi.
* [2019-03-06 mié]
hoy levante bien despues de dormir bastante bien tipo 6.30. Hice 3
series y bici sin dificultad pero no exultante, luego quede un poco
mal parado. Tome el licuado y no es que quede cien por cien, pero fui
a la oficina digamos 95/100.
A los pocos minutos me llama ih para que vaya a la casa por el tema
constructivo, y alla tuve varias situaciones de estres que maneje muy
bien y con normalidad, cuando luego de comer pense que iba a derivar
en situacion de jaquecosidad, preferi relajar con aire y me acoste,
luego llama Fede y me libera de tareas, no obstante al rato me vuelvo.
Cuando llego al centro, veo que puedo ir a la oficina, tomo un cafe de
3cdas+1 y eso elimina toda jaquecosidad remanenente y quedo pila pila
para seguir con la eficiencia que habia tenido en esa horita de tarde,
y me voy en una gran caminata contra el tiempo de 17.30/18hs y compre
el raton y puse el aviso, luego a la vuelta disminui el ritmo pero el
calor se hizo sentir, todo bien no obstante.
Una vez en la oficina todo joya, puse el teclado y reposo aca se puede
decir, es un placer trabajar aca, con aire musica y tranquilidad. 
* [2019-03-07 jue]
noche joya. primera noche que duermo 4 ciclos sin almohada, solo con
la bajita, y me parecia estar mas comodo, casi natural en especial
sobre mi derecho. Solo en el quinto ciclo que se trabo un poco puse la
inteligente luego no concilie, la saque y la volvi  a poner y me
dormi.
Esta vez me desperte mejor fisicamente, y la gimnasia me dejo un poco
tembleque pero del esfuerzo, bienvenido que voy incrementando.
Creo que aparte de la gimnasia, la comida a la noche, la disciplina
del sueño es importante pq uno no sabia nada de sueño.
Anoche desde que me dispuse a dormir, solo me alumbre con el celu para
abajo en modo byn que lo programe de 21 a 6hs. Eso tambien marca
diferencia.
* [2019-03-08 vie]
nada para decir, un dia redondito de los que tengo que repetir y
potenciar en mi casa, con la mezcla de buen administrar el sueño
nocturno una siesta corta muy bien aprovechada y la jornada excelente,
solo a la noche empezo una leve molestia a nivel subinicial digamos un
N0.25 que obviamente no es tomado en cuenta y termine la jornada en
calma y felicidad.
* [2019-03-09 sáb] N4 (noche)
dia sin ninguna toma de nada que transcurrio con un N0.5 de a ratos,
limpio muy bien hacia la tarde-noche.
El dia planteaba muy dificil.
de por si veniamos de una previa con salida de la Cami sola con la
amiga y venia en remi sola, aunque habia dormido bien o mas o menos
bien considerando que no me adapto cien por cien aca.
me levanto a las 7am y hago gimnasia en el patio fresco, luego me
pongo a limpiar el patio con energia que la tenia, todo para limpiar
el 0.50. Luego desayuno el licuado, luego programo, luego almuerzo muy
bien, comida con mucha carne (bife a la criolla) hacia mucho que no
comia carne, luego siesta corta controlada pero buena, luego
programacion, luego actividad, luego viene Fede, todo bien, ahi limpie
total, comi como un cerdo, nunca habia comido tanta carne en un asado
en mi vida. 
tomando solamente agua y de ensalada rucula.
tomo un te de boldo y la postcena, aunque me resulto beneficiosa pq
baje la carne pues cuando me acoste no me molesto para nada dormir de
ningun costado, el ruido enloquecedor de la hablada, los chicos, el
humo etc, fueron haciendo mella, y el cansancio.
Me duermo ya con un quizas N2.
Voy despertando en los primeros ciclos con N2, hasta que sube a un
comodo N4.
En cierto ciclo observo que la relajacion me ayuda un monton, y el
sacar la almohada tambien.
Pero creo que se habia diferenciado una migraña clara y crei
racionalizar la idea de que podria tomarme un migral por "esa" migraña
dado "que habia ya aguantado unas 4 horas de un N4", entonces tipo 7
me levanto con el bolso a tomarme el migral y noto que no, que la
migraña no estaba como pensaba (no habia una hemicraneal, no habia un
agravamiento con el movimiento, no habia un dolor que superara el N7 y
no habia nauseas), entonces como tenia un intenso dolor de cintura
aproveche a probar con un diclo, y tome un diclo en 45 min parecio que
el N4 paso a un N2 y me levante.
* [2019-03-10 dom]
el diclo limpio totalmente la N4 en 45 minutos a N2 trabajable y luego
de trabajar en el aviso de visita puedo decir que limpio completamente
Felizmente hasta las 15hs sigo bien y me dispongo a dormir la siesta
solo estoy destruido de la espalda.
La noche bien, lo que los 5 ciclos parece que no tienen tiempo para
completarse y a la hora de levantarme no estoy repuesto cien por cien,
en especial el ultimo ciclo que parece que lo paso en vela pq no me
puedo dormir de nuevo.
hago lo mismo las series y la bici. y salgo con ganas de empezar la
semana luego del receso.
* [2019-03-11 lun]
lunes transcurrio tranquilo solo con un N0.5-0.75 de a ratos, que
termino limpiandose a la tarde en oficina cuando limpie.
Lo cual viene a demostrar una vez mas que el ejercicio mas que todo
cuando es distractivo limpia los procesos acordes. Todo
correlacionado, o sea no se puede hacer recetas pq no es una pastilla,
o sea no se puede llevar ni tener una pauta de ejercicio o tarea
disponible a mano cuando lo necesites.
* [2019-03-12 mar]
anoche el sueño fue muy cortado
| 1 | 56m |
| 2 | 39m |
| 3 | 38m |
| 4 | 61m |
| 5 | 72m |
| 6 | 93m |
| 7 | 67m |
| 8 | 45m |
|   |     |
el ultimo "ciclo" lo hice con ventana abierta y tapones puestos por el
ruido y no dormi. Si me atengo a los ciclos de 90 minutos entra solo
uno.
Creo que tendria que probar con no tomar liquidos pasada cierta hora
para ver que pasa. 
Desde las 6.15 mas o menos me quede despierto y luego a las 7 me
levante e hice la rutina habitual. 
* [2019-03-13 mié]
anoche dormi bien pq estuve muy cansado pq trabaje como negro en el
local.
De un trabajo que pensaba hacer superficial termine haciendo un
trabajo global que hubiera asustado a cualquiera. Creo que es la
combinacion del tratamiento y de la gimnasia.
| 1 | 70m  |
| 2 | 58m  |
| 3 | 65m  |
| 4 | 83m  |
| 5 | 77m  |
| 6 | 118m |
| 7 | 64m  |
La noche fue mas larga y tuvo un ciclo mas largo y fue suficiente para
restaurar el cansancio.
Me levante y pude hacer la rutina normal, las tres series y la bici
con energia.
Cuando me acoste tuve como un N0.2 sobre la frente como asentamiento
del destornillador pero me dormi y se limpio solo durante la noche no
senti nada. Al amanecer de nuevo pero no pasa nada.
* [2019-03-15 vie] 
ayer un dia exigente al maximo, irme al marques contrarejoj pq tenia
que ir a comprar la ventana. Eso hizo que me quedara mas tiempo en la
oficina y alterara el horario del almuerzo, encima eso hizo que
saltaran innecesariamente unas chispas en la oficina, no obstante
ambos temas no creo que hayan influido en nada.
Llego a dpto, almuerzo quinoa negra y lentejas, siesta y me voy a
marques, de inmediato voy a ferrocons y compro ventana para oficina,
ahi todo salio barbaro, como habia imaginado, incluso el lugar donde
estaba la ventana. Luego vengo y como facturas y todo bien, salvo unos
roces con las chicas, tambien innecesarias. Un poco me embolo que la
Romi no se ponga las pilas en su parte en la reparacion del local. Lo
mismo le ayude a cortar el pasto mas para evitar el riesgo de que
tenga la puerta abierta. 
Me duermo y tenia que llevar a la mañana temprano a la Cami a rendir.
a la madrugada me despierto con un N2, y me digo que si persiste estoy
autorizado a tomarme un MIG por la enormidad de la situacion.
Y baje la almohada y me puse en relajacion y eso limpio a N0.25 me
levanto bien y la llevo joya.
Luego llego a las 7am al dpto y ahi viene el otro "milagro", tenia un
waiver implicito de los habitos por lo que habia dormido mal, pero me
dije lo hago igual, y comence y lo hice, las tres series, y ahi
observe que se mostraron doloridas masas musculares nuevas por el
pushup. pero las hice espectacularmente bien. Y luego hice muy bien la
bici, incluso vestido para venir a la ofi, o sea la fuerza del habito,
fue lo suficientemente fuerte como para impulsarme a hacerlo sin
esfuerzo.
O sea que a pesar del compromiso extra que supuso el jueves tarde ir a
comprar la ventana, y el viernes a la mañana llevar a Cami, pude hacer
la rutina de habitos igualmente. 
Ahora tengo un N1 rotando y dando vueltas pero no le llevo el apunte
mayormente.
* [2019-03-16 sáb]
siguiendo lo complicado que habia sido la tarde jueves noche viernes
mañana, luego se recomplico el viernes.
Resulta que con el auto en la cochera el Fede estaba cabreado y yo sin
licuado, pensaba que me iba a volver a almorzar con ih, incluso
mediamañana le pregunto por lo que iba a cocinar, pero me dice que se
vuelve la Cami con la chica y que iban a ir a bailar. Luego influyo el
tema del Fede, y eso alargo la jornada de mañana, y el hecho relevante
es que cayo una tormenta descomunal que me aprisiono en la oficina
"sin comida!!!!! y sin licuado!!!!" o sea justo una mañana sin licuado
vengo a quedarme sin almorzar. Me estiro con te con lincoln y tipo 4
de la tarde para la lluvia y me puedo ir al dpto y encuentro una
quinoa semidura que le echo aceite y dos minitomates podridos y como
algo salado, y me acuesto a reposar (me habia levantado a las 5 y
media). Ahi decido que no voy a ir al marques ahi nomas pq no iba a
descansar, aca duermo un poco y me levanto y me voy alla, comemos una
pizza delivery y me acuesto.
O sea un dia muy trabado, lejos de lo que se dice un dia normal,
relajado. 
Aparte vengo viendo que en los ultimos dias no puedo relajarme en el
propio trabajo en las pausas, la mayoria las paso por alto, incluso
aca en la casa, y en la casa. Y para dar una pauta de lo que esta
semana supuso en alteraciones de tiempo puedo ver que no pude ir a
comprar nada para mi p.e. lentejas.

Yendo a los especifico migra luego de este preambulo dire que a la
noche empezo un N2, que hacia las 4 habia subido a un N4 semimolesto,
ahi paso como la otra vez pienso en el migral de ultima, pero pienso
que teniendo la excusa para un diclo (la otra vez tenia un intenso
dolor de espalda esta vez tenia la pinsa en el hombro que me habia
ocasionado con la gimnasia) lo tomo y veo, y hacia las 7 tenia solo el
molesto N2, tan molesto que hacia inconfortable seguir durmiendo, y me
levanto, me voy al baño y ahi no mas se limpio el N2, ya cuando tome
el cafe estaba limpio total, y asi segui durante la mañana, que
resulto hasta las 9 muy movidita pq tuve que hacer gran esfuerzo
llevando la ventana y principalmente llevando el material hacia la
oficina.
* [2019-03-17 dom]
seguimos con el alto requerimiento. Anoche dormi muy profundamente con
N0.
pero desperte muy temprano y me levante tipo 7. Hice ejercicios y
fuimos al centro con gran tension (eutres pienso). Resolvimos lo del
contenedor y la salida de la Romi, pasamos por dpto y luego por local,
pero el cansancio se sumo, luego hicimos siesta antes de comer hasta
las 15hs, ahi me levanto con un N2 casi entero basado en parte
huesitos posteriores, y accedo a tomar un diclo que podria y debia
haber sido de 50 o directamente no haber sido.
Almorzamos y eso me mejoro inmediatamente luego fuimos al Fede, y
volvimos aca a tomar mates y aunque bien se nota el cansancio, y no
poder relajarse pq en el fondo pienso que el Andres vendra a
cobrar. Pero pienso que mejor pq asi dormire mejor a la noche.
* [2019-03-18 lun]
hoy el dia fue muy largo y muy intenso, duermo bien muy bien con N0, y
me voy despertando bien temprano.
Me levanto tipo 6.30. llego al centro 7.15 y hago con cierta
dificultad las primeras series, luego me siento bien, cuando las
termino, y hago la bici. Luego me voy a la oficina y cumplo bien la
funcion de la mañana.
y ya se perfila un N2, pero de tipo huesito. Entonces a las 13.30 con
el almuerzo me tomo un diclo, y luego me tiro una siesta y me duermo
muy bien, luego en oficina estoy bien pero va subiendo un N1 N1.5 voy
a ver el local, y a comprarle los libros al fede, y luego vuelvo al
local. 
y me vuelvo. 
Tengamos en cuenta que hice el tema de la cabaña, y el tema aviso y el
tema ir ver el local, y todo se junto, y a la tarde estoy agotado y ya
con N2, y entonces pienso que tengo que descansar, he caminado mucho,
pienso que a nivel ejercicio ando bien con esto. 
me acoste a dormitar hasta las 9 con un N2 dando vueltas y me puse a
hervir un arroz mientras pensaba que una de las mejores conquistas que
tenia era el ejercicio, y entonces me vino el animo para hacer el
pushup que estaba programado para hoy, precalente y lo hice en sus
tres intensas series, y me bañe. Luego comi, y baje el N2 a N0. Ahora
que me va bajando el sueño me voy a dormir.
* [2019-03-19 mar]
fue un dia normal con N1/N2 rotando segun presion del momento y
"autojustificandome" la toma de diclo por situaciones especiales.
Es verdad que ayer un dia frio en exceso que me agarro mal abrigado y
que no volvi a comer a casa, que no hice siesta, que me fui a cortar
el pelo, que volvi al marques en el auto, que tenia que comprar los
ceramicos, o sea todas cosas que se salen de mi rutina normal, y
decidi tomar un diclo, y todo ok, luego dormi mas que bien, eso que
comi un guisito recalentado de fideos.
* [2019-03-20 mié]
hoy interesantemente empalma igual que ayer, el dia sin compromisos
como los de ayer, pero se presenta intenso, cansador, sin la gimnasia
de la mañana despues de muchos dias, y sin licuado, y sin irme a casa,
y sin siesta. Voy a pagar todas las cuentas, y sigo aca trabajando, ya
el aire no es agradable pq esta embotado y la carga de trabajo es tan
grande que ya no hay relajo. Entonces estamos sembrando el terreno
propicio para entrar en un sistema de cultivar el dolor.
Me sobrepaso casi todos los stops de RSBreak, no solo los cortos que
son facilicimos de hacer, los grandes todos, y no me levanto del
sillon.
Y tengo el diclo ahi arriba.
Y me dije que macana pq ya el 5to dia de diclo es una tendencia, y es
una mala señal.
Y al final no lo necesite. Y al final decidi tomarme el rsbreak y pude
hacer dos series y el mover la sangre me sento barbaro y creo que eso
es la clave de todo o sea el movimiento y parar un poco la bocha.
* [2019-03-21 jue]
anoche dormi espectacularmente, pense agregar a mi kit de
recuperacion, el balde (futuro sofisticarlo) pq ir al baño supone
exponerse a cambio de temperatura que me puede despertar mas. 
y me costo un poco la gimnasia esta mañana, pero en el medio pense que
no tengo vicios ni sustancias en mi fisico por lo tanto tengo que
exigirme a tener mas fuerza pq no puedo amesetarme en eso.
Es mas a la tarde p.e. hoy me hice ya dos series hechas con mas
energia y rapidez que las series de la mañana que las hago como si me
fuera a desarmar. Y estas serian la 4ª y 5º serie del dia. 
Lo mismo hoy no se si como resultado del estres de la mañana, ni por
causa de la falta de ejercicio o que, aunque la mañana no duro mas que
cuatro horas, me fui con un N2 de huesitos, y al almuerzo lindo y
variado me tome un diclo. Y dormi una siesta muy buena, con tapones
fue espectacular, y costo despertarme.
me vine y dos cafes fue necesario para despabilarme.
persistio un N1.
Luego al correr la tarde se fue todo sintoma y con la gimnasia me voy
de la oficina a las 19.30hs con N0 y con energia plena.
* [2019-03-22 vie]
el viernes fue un dia complicado tambien y termino yendome al marques
llevando el bolso desde la siesta de aca y guardando en kangoo y
yendome con el Fede. Fue particularmente estresante el camino con el
Fede y luego en la casa, pq estaba todo el tema de ir a buscar los
ceramicos y luego descargarlos a la noche, ese era el tema del dia,
que era un tema gigante y amargador de por si. Yo estaba iracible
incluso no queria hablar con ih, y me sente en la cocina a comer uvas
callado para sosegarme, y ahi me tome un diclo de ih cuando ella se
fue a buscar unas cosas a su amiga.
Luego fuimos a buscar las cosas lo cual fue bastante sencillo salvo
por la mala onda del Fede por tener q ayudar en algo que segun el le
correspondia a la Romi.
Al final decidi no ir a descargar esa noche y me fui a dormir.
* [2019-03-23 sáb]
con poco presueño de celu, solo un poco de cuaderno y a dormir, pero a
la noche me despierto con un N3/N4 y me planteo tomarme otro diclo
quizas. Pero alli recuerdo que me dije que podia soportar durmiendo ya
que habia soportado durmiendo hasta N7/N8 el dia de la migraña sin
tratar. La noche se me hacia larga y yo queria que la mañana viniera y
pudiera hacer gimnasia y tomarme un cafe. Y levantarme. Es que en mi
cabeza esas tres cosas son los sinonimos del nodolor, al contrario de
acostarse, reposar o dormir que van en contra.
Y funciono asi, pude seguir durmiendo sin problemas, y practicamente
no hizo falta la gimnasia, -aunque la hice y con gusto-, porque habia
llegado a N0 antes de levantarme, o sea que limpio al amanecer.
Y ese sabado si que fue una concatenacion de circunstancias que
podrian ser consideradas pro-situacion: la amiga de la cami instalada
en la casa, hacer un asado en la casa con los chicos y empezarlo yo
con 28 grados y a pleno sol, atravesar la siesta hasta las 6 de la
tarde, dormir la siesta largamente, y luego a la noche ir a llevar los
ceramicos con la tension que significo la ida y la vuelta, y la
situacion, y todo con una cena tempranera de picada de salame y queso.
Y todo se atraveso con N0
* [2019-03-24 dom]
el domingo igual me levanto un poco mas tarde hago la gimnasia igual
aunque un poco menos energicamente, y tomo mates con salame, luego a
la tarde vienen los chicos, hacemos actividad en el jardin con ellos
sumamente divertidos y me quedo en la casa y todo redondeado un
domingo que puede considerarse duro de sobrellevar con N0
* [2019-03-25 lun]
hoy arranco con cafe pq me salgo totalmente de rutina, ya que no tuve
ni gimnasia matutina ni bici, ni licuado pq dormi afuera, y desayune
cafe con dos medialunas, y tuve que dirimir cuestiones importantes,
pero las lleve sin estres, y luego me fui a horario correcto de
almuerzo me hice fideos con salsa y no tuve siesta a pata ancha pero
dormi mi media hora, luego pude huevear en paz en el dpto por la
lluvia, hice al menos la gimnasia y capaz salvo el licuado. Luego de
la minisiesta y el hueveo, me puse a ver una peli netflix cosa que no
hacia desde que comenzo el tratamiento y me vino un N2 que resolvi con
los ejercicios y un cafe con galletitas y suculenta pasta de mani y
queso. y ahora sigo hueveando escribiendo esta bitacora.
* [2019-03-26 mar]
entre ayer y hoy fue la batalla del habito del ejercicio. Ayer a la
tarde empece con dificultad a hacer las series, y lo hice parte para
combatir un incipiente N2. Luego deje para mas tarde el pushup y
cuando me parecia imposible de hacer lo logre con resultados
fenomenales, tanto animicos como directamente en el N. Y en el H. No
hay debilidad mas que la debilidad mental. Uno piensa o se hace la
idea que no va a poder. Y esta mañana tambien, pq dormi muy bien y
mucho, pense que no iba a hacer la rutina de gimnasia y la maquina
racionalizadora me indicaba que podia estar perdonado "porque estaba
cansado de un fin de semana intenso", y lo mismo luego de no querer
fallarle a H me puse a la bici, y lo hice bien, y con gusto, dejando
al menos las S para la tarde que se pueden hacer bien. 
Vengo a concluir que la gimnasia es muy fuerte para combatir los N y
la fuerza del H como motivador para seguir la secuencia. O sea no es
lo mismo un habito seguido por H que una actividad que no se controla.
* [2019-03-27 mié]
nuevamente durmiendo muy bien a la noche y costandome levantarme a la
mañana  ya no es como antes que tengo insomio de 6 en adelante, casi
como que me despierto con el despertador. Sera el fresco.
Y hago fiaca y dejo las series para la tarde y peligra la bici que
termina haciendose solo como fuerza del habito.
* [2019-03-28 jue]
anoche dormi desde temprano y cai rendido full, como un tronco, lei
dos lineas apague y mori.
a cierta hora supongo tipo 4 me empezo a molestar cierto tipo N4, que
trabaje como siempre. Cuando ya me resultaba molesto eran las 6.50 y
me puse contento, me desperte y con furia y energia hice las series,
todo bien mientras hacia el licuado pero se habia transformado en N5.
Luego me sentia nauseoso, tome reliveran.
hice la bici todo con ventana abierta y desayune cafe, y licuado con
galletas y queso y casi supongo que habia reducido a N4. Los fantasmas
interiores aparecieron en la forma de pensar que durante el finde se
podria ir todo a la mierda, y que hoy tenia un compromiso, - el ir a
pagar el local el albañil-, me pongo un migral en el bolsillo, pienso
que el finde me autorizo a los migrales como excepcion. LLego a
oficina, tomo un cafe superfuerte, y comienzo la jornada normal,
digamos que bajo a N2 quizas a N1, todo ok por ser quizas un N5
nauseoso.
Lo unico que me llama la atencion es la nauseosidad que fue provocada
por un yamani.
Al final termine la mañana desarrollando todas las actividades
requeridas con un N1 de fondo.
Casualmente ayer pensaba que habia cambiado la bocha de ser que todas
las circunstancias adversas del dia conspiraban juntas para producir
Ns, a una en que todas esas circunstancias no pueden voltear los Hs.
* [2019-03-29 vie] N6 con MIG
anoche dormi mal pq ya al acostarme tenia un N3.
durante la noche molesto bastante en forma de mal dormir incluso con
pesadillas o sueños malos y aunque me dormia enseguida, tenia
confusion mental.
cuando se hace las 7am, tenia lo que yo pensaba era un N5 pero no
nauseoso como el dia anterior. Y pensaba que iba derechito a un MIG
para cortarlo pq pensaba que era una migraña de baja potencia que se
habia extendido por dos dias.
Y me levanto con buen nivel de energia insusitada para una mañana con
Ns y hago las tres series y me preparo un cafe, riego las plantas y
hago el licuado, tomo el cafe, y un naprux.
Luego hago la bici con fuerza. Mientras hago las series observo que se
va notando a nivel hombros y cuello los treinta dias de esfuerzo y que
puedo aumentar un poco la intensidad de las series.
Y la bici la hago con mas energia que de costumbre y ya al desayunar
tenia otro animo, totalmente distino y ya casi estaba en N0, y a pesar
de que la mañana fue movidita hasta ahora estoy bien y no tuve que
tomar nada mas que el nx.
La tarde fue otra historia:
la mañana fue beligerancia total, el aire se cortaba con cutter en la
oficina no se porque devino el pie de guerra total. Yo mientras pasaba
ventas pensaba pq estaba animoso y fuerte que podia animarme a
aventuras de plan b ya sea solo o en sociedad como local anexo, salir
a vender o directamente independizarme.
Tipo 12 salgo a caminar para ver el local y hablar y de paso ver el
menu de la bodeguita. El local estaba alquilado. El menu era apto.
Ahi cometo el error que es invitarlo al Fede a comer el menu. Ya en el
comedor sigue la discusion no pudiendo distenderme como queria.
Dentro de todo la comida muy rica y yo tenia hambre comi con gusto y
me olvide un poco de la discusion. Luego en la oficina seguimos
trabajando un rato hasta las tres. Ahi luego de un cafecito decido ir
al local para hablar con el Andres. Y una vez en mi dpto decidi
descansar un rato, me dormito y me va subiendo el dolor de cabeza, me
tomo un segundo nx y no haciendome nada y mas que todo aprisionandome
el horario de cierre de la jornada y de la semana y del mes, me tomo
un migral aun sabiendo que dificilmente iba a tener efecto
instantaneo.
Ya hace una hora cuarenta de la toma y aunque hice muchas cosas para
mantenerme levantado y no caer en irme a dormir y agravar la cuestion
tengo aun una resaca tipo N2. (Aun asi prepare el bolso, lave las
ultimas cosas del dpto y me preparo para irme). Pero no pude terminar
la jornada ni ir al local.
La lastima de haber tomado un migral dentro del mes que venia muy
bien, pero pienso que administre muy mal la estrategia. Hoy tendria
que haberme ido en sentido contrario al toxico, o sea haberme recluido
en mi dpto a comer mijo, o bien haber ido a comer solo y tranquilo.
* [2019-04-02 mar]
luego de cuatro dias de cabaña pienso que el tema se porto bien. No
tuve molestias de ningun tipo y eso que no tuve medidas sanas de
ningun tipo.
** dormi de mas
empece de a poco, parte por la paz y silencio y luego para evadirme y
luego por la costumbre y termino este martes con una siesta brutal ya
en marques que me dejo un N5 casi con destornillador que conjure con
cafe, naprux y baño y me volvi al centro donde no pienso cenar y
pienso empezar la detox.
** comi de todo
comimos de todo, choripan, salame, asado de chanco, morcilla, pollo al
disco, guiso de lentejas, pizza, guiso de fideos, manteca, cafe a
mansalva, gaseosa todos los dias. Cero fruta, cero verdura, Cero agua,
Ninguna comida que se pueda considerar sana.
** ruido y condiciones de aburrimiento que fungen como estresores
a pesar de estar en relax y que fue bueno, este post es analizador
frio de la implicancia sobre la migraña y bien pudo ese cambio de
actividad sumado a la falta de incentivos y la monotonia ser
estresores proNs. 
** actividad moderada a baja
las series las hice en forma descendente, pero no faltaron ningun dia,
y solo un dia hice una actividad de caminata de unas 35/40 cuadras, y
nada mas.
** conclusion
para todas esas condiciones no muy sanas creo que se porto bien. El
fisico acuso un cansancio pienso debido a exceso de sueño por falta de
actividad quizas debida a la falta de incentivos.
* [2019-04-03 mié]
reinicio de actividades con bastante cansancio y un dia muy luminoso
de mas, caluroso para la fecha y con mucha fiaca para ponerme a
comprar cosas, encima estoy incomodo pq no tengo ropa adecuada de
semifajina acorde a la temperatura, cosa que no vale la pena
solucionar dado lo avanzado de la fecha.
Un N2 molestito dando vueltas lo soluciono con un naprux y sigo
adelante.
* [2019-04-04 jue]
anoche dormi mal, a pesar de que estoy con un masazo en la cabeza de
sueño desde que volvi de la cabaña, me fui despertando con un N5, y me
dije que no daba tomar nada ni hacer nada, aparte me tranquilice a mi
mismo diciendome que a la mañana iba a tomarme un migral si hacia
falta, pq la perspectiva de remontar con gimnasia y cafe me hubiera
agitado pq estaba cansado. Y solo quedaba seguir durmiendo, y como
paso ya en otras ocasiones cuando me desperte, ya tenia un N0.5,
prorrogue el reloj a 7.30 cancelando la bici mas por el agotamiento
que por la resaca, me levante bien, un poco desconexo (episodio de
buscar la media perdida que tenia puesta) y lo mismo hice dos series
mientras hacia el licuado, tome dos vasos y vine bien, luego tomo un
cafe breve para completar y/o despertarme mejor.
El dia evoluciono joya en el sentido Ns. Incluso dormi siesta y me
levante joya, y ahora estoy tomando un cafecito.
Lamentablemente la tarde postoficina no fue buena a pesar de no haber
habido problemas, me aboque a la programacion, hice la primera pausa,
baje a comprar facturas y me hice un cafe con facturas y tome un
naprux con cafe, luego en la segunda pausa hice una serie mas con
dificultad y luego esquive la siguiente pausa, y en general el cuerpo
nota el esfuerzo de maquina, y el esfuerzo de gimnasia o el estar
duro, y un N2/3 esta latente a pesar del naprux con puntaditas en el
ceño.
Ahora cierro y descanso, labor cumplida pq me fue bien en la
programacion.
No estaba en una situacion N0. estaba molestito como decia N2/3 y me
tome un te con un pancito integral mani y queso y dormi profundamente
hasta el punto que me costo levantarme a la mañana y tuve que pasarme
por alto la bici y desperte N0.
* [2019-04-05 vie]
dia de N0 hasta ahora siendo que fue un dia durisimo en actividad
fisica pq tuve que ir de aca para alla. Tuve que estar hasta las 13hs
en la oficina, previo haberme venido a buscar un papel mediamañana y
estar en ofi sin licuado. Y luego apenas comi, casi con la comida en
la boca, me fui al local y trabaje como un enano boliviano, y me volvi
tipo 18.30 con todos los musculos doloridos.
* [2019-04-06 sáb]
luego de un dia perfecto sin Ns me levanto luego de dormir sin
molestias, pero no bien ni placenteramente, o sea sin molestias de Ns,
pero no dormi con placer a eso me refiero, quizas pq estaba muy
cansado y sigo cansado al levantarme, me levanto con un N3 punzante
izquierdo y me tomo de desayuno nomas diclo con resto de licuado y voy
directo a la programacion sin ejercicio por ahora.
Me dio por acostarme tipo 18.30 para recordar viejos tiempos, pero me
puse a repasar los habitos y me entro una energia para por lo menos
poner series, y como habian sido dispersas las de la mañana me dije
que al menos dos enteras, y me hice tres perfectas series, y vi como
la energia me entro, tanto que si hubiera estado en mi casa hacia el
pushup.
* [2019-04-07 dom]
dormi bien y me levante a las 10. Desayune mucho y me puse a programar
un poco, intercalando series. 
* [2019-04-08 lun]
anoche dormi mal, decididamente mal, y es que todos los tips y buenas
costumbres relativas a preparar el sueño y dormir bien no las aplique
mal y se cobro el resultado en dormir mal. (la cama sin hacer con
sabanas sin cambiar de hace mucho, no respetar la hora de la cena, ni
la hora del WD tecnologico, ni la hora del WD luminico, tambien con
relacion a la parte ejercicio en general durante la semana, al reducir
la cantidad de ejercicio la calidad de sueño se ve afectada.)
aunque me habia levantado bien e ido al banco y a pagar el alquiler,
luego a dormir una minisiesta, el ambiente tenso de la oficina termino
siendo nocivo para el dolor de cabeza, decido venirme a programar a la
oficina en vez de quedarme en mi casa y me termino tomando un diclo.
* [2019-04-09 mar]
hoy transcurrio el dia muy bien, mañana, banco, almuerzo, siesta, un
poco somñolenta y me costo levantarme el plan era programar, estaba
pautado y arreglado, no habia problema con eso, y luego de un par de
horas tipo 16 me invadio un destornillador, al que me rehuse como no,
y aunque me tome un naprux, hice todo tipo de actividad, de mixtura
con la programacion, pero segui en la misma absorvido y se limpio el
martillo, casi a N0.
* [2019-04-10 mié]
hoy no fue como ayer, no tuve tan buen resultado en la programacion en
las primeras horas, incluso tuve momentos de furia, y sin embargo no
tuve molestias Ns, felizmente, pero me costo hacer las series que
debia de la mañana, y la limpiecita que la hice en las pausitas.
Incluso me plantie el ir a comprar viveres y estuve a punto de
cancelarlo y vivir como un montañez extremo, y felizmente fui, y eso
me despejo un poco, y la idea que estaba pergeñando se hizo mas
grande, y aunque no me aboco a ella, la dejo bien planteada para
encararla mañana o los proximos dias, pq es grande de verdad. Un dia
puede estar momentaneamente trabado pero termina bien despues.
* [2019-04-11 jue]
esplendido, todo, incluso no tuve siesta como ayer tampoco la tuve,
pero tengamos en cuenta que estuve muy motivado por un proyecto de
programacion que me ha dejado un poco entablillado, pero contento y
feliz.
De todos modos hice las dos series que me falta, y la limpiecita.
Me faltaria hacer el pushup para ponerme al dia.
* [2019-04-12 vie]
otro dia joyita igual que los anteriores dos, sin siesta y con mate me
dedico a programar y a cumplir los habitos y a estar bien conmigo
mismo.
Lo bueno es que en ciertos momentos de la semana parece que fueras a
sosobrar y luego cuando has cumplido con todas las expectativas te
encontras optimo y eso esta bueno.
* [2019-04-13 sáb]
fin de semana aciago en familia. el sabado hicimos tarea monumental de
limpieza de la cochera, pero tenia en el fondo la presion por el
cumpleaños del Fede, pq no sabia que iba a resultar ser en familia
como resulto. Y en el medio se suscito un altercado con la Cami que
tomo dimensiones mayusculas todo pq yo le hable con dureza sobre la
inconveniencia de traspasar las fronteras de la indiscresion. El
sabado termine tomandome un naprux seminecesariamente y me fui a
dormir, y a la noche ya tuve episodios de dolor, que los resolvi con
el protocolo de siempre, diferir hasta levantarme y ver que se puede
hacer.
Me levante a las 7, me tome un diclo, un cafe, y unas masitas de
avena, con un N5 y me dormi una hora mas y se me paso.
* [2019-04-14 dom] N8 MIG
ya en domingo y sabiendo que el fede venia a comer asado, mateamos con
la isabel tranquilos, y comienzo a hacer el asado, y un poco sufro
estres por el humo y el calor, pero no demasiado, luego el fede
termina el asado, y comemos, mucho calor pero comemos adentro, y creo
que comi tenso pq la Cami continuamente amenazaba con irse de boca y
yo imaginaba un escenario de disgusto generalizado. Luego cuando
comenzamos a hablar de negocios la charla fue distendida y
ambientalmente correcta y ya me habia tomado un naprux, pq me habia
empezado a doler la cabeza y el dolor no cedio sino que fue en aumento
hasta que luego de un par de horas tuve que tomer un migral y no hizo
efecto, llegando a un estado de descompostura que si bien es cierto
que no era tan aguda, se vio agudizada por la indisponibilidad de
retiro, o sea como suele pasar cuando estoy alla y no puedo disponer
de la posibilidad de salirme de servicio.
seria teniendo en cuenta las circunstancias equivalente a un N8.
Me pude retirar y me dormi rapidamente, y a las dos horas seguia
fuertemente afectado, me levanto y tomo un te, y alli me mejoro en
unos quince minutos hasta tal punto que puedo venirme y dormir en mi
cama y comenzar la semana desde mi casa.
* [2019-04-15 lun]
dormi bien anoche y me levante normal
* [2019-04-16 mar]
otro dia normal
* [2019-04-17 mié]
consulta al medico otro dia normal
* [2019-04-18 jue]
nuevamente un dolor de cabeza que sobreviene cuando venimos al
marques, esta vez por causa de estres en el horario del almuerzo por
causa de venirme con el Fede y ahorrarme el taxi, hicieron que tipo
16hs tuviera un N5 que cedio luego de una siesta tranquila y
prolongada y un cafe fuerte con galletas  y dulce de leche y ponerme a
conversar.
Felizmente se fue quedo una leve resaca y no tuve que padecer grandes
problemas remanentes, y luego me puse a la compu.
y me esta bajando sueño.
* [2019-04-19 vie]
dificil es estar bien con las condiciones de vida un dia feriado aca,
hasta las 19 estoy N0 pareciera que pueda haber algo next. pero varia
mucho un dia normal de esto aca, siesta prolongadisima, incomodidad
extrema para hacer algo en la compu, malas posturas, desgano para
ejercicios, -casi no puedo completar las series- , mala situacion con
las hijas, peleas en el ambiente, aburrimiento, etc, comidas pesadas.
en el fondo me justifico diciendo en el finde no puedo mantener la
rutina y si me duele la cabeza es por culpa del finde.
* [2019-04-20 sáb]
a pesar de ser un dia con gran frustracion pq a pesar de que fue un
fin de largo sin grandes presiones, ya que no me obligue a nada, y el
sabado mas que todo lo ocupe en ir a comprar la compu, pasar por mi
dpto y luego enfrente una gran frustracion por no poder instalar
kubuntu en la compu nueva quizas por falla en la misma y tener que ir
a cambiarla posiblemente el lunes, encare esto con gran tolerancia a
la frustracion. El ambiente negativo con las chicas toco momentos
cumbres en el finde a la tarde con el episodio de los criollos cuando
innecesariamente se volvio a foja cero en una situacion de separacion
que cada vez se hace mas fea y podria haber causado Ns, pero
felizmente curso bien. Cene una sopa espectacular y dormi.
A la noche nuevamente siento un N4 que curso con sueño o sea dejarlo
que curse, y despertar normal, un shot de ejercicios fuerte, y un
cafe, y comenzar la rutina del dia. 
* [2019-04-21 dom]
hasta ahora bien, termine tomando un diclo para frenar una jaqueca que
mas que dolor de cabeza era dolor de corazon, pq visto para atras en
ese fangoso fin de semana interminable de semana santa varado ahi sin
tener nada que hacer frustrado como estaba por la compu mal comprada y
fallada, empece a sacar mierda con ih que es el peor de los planes pq
al fin y al cabo eso no resuelve nada, sino que lo lleva a uno a picos
de melancolia peores, y en medio de toda esa maroma imposible me tome
un diclo para aliviar el dolor que como digo no era para nada de
cabeza.
* [2019-04-22 lun]
mayormente bien.
Como dije ayer que iba a empezar a medir el animo, hoy bien pq a pesar
de una agenda jodida en realidad termino bien, y no me puedo quejar en
lo absoluto, pq se encamino bien ambas cosas, por un lado el reclamo
de la compu ya esta y la compu esta andando y mejor que mejor en
window para la cami con la impresora con cartucho y todo, y el aviso
en marcha con nueve citados en el primer dia para mañana, lo cual es
muy importante pq un citado fresco o sea un citado de lunes es un
citado con mas chance de posibilidades, Mañana por la mañana las
carpetas y a las 15hs el curso.


* CONCLUSIONES
** CONCLUSIONES PROVISORIAS DEL WD
El WD duro 13 dias de 20mg y 3 dias de 10mg o sea un total de 290mg de
cortypyren.
Estuve muy bien primer y segundo dia, no tuve el rebote clasico del
segundo dia, si un poco de molestias el tercer dia, pero no mayores
las cuales curse con dos naproxeno (pueden haber sido tambien por
efecto de haber "esperado el rebote"). A medida que tomaba confianza
en el tratamiento reducido, y pensaba en que el rebote no se iba a dar
llego un dia clave que fue el domingo 24 a la noche, donde justo se me
presenta una jaqueca fuerte a medianoche y al dia siguiente tenia que
estar en la oficina nueva en su dia inagural, como no sabia como iba a
cursar el rebote no me pude arriesgar y tome un  migral. Hasta ahi
estaba dispuesto a pasar horas y horas soportarndo el dolor en aras al
WD como lo habia hecho el dia 2 y 3. 
El migral surte efecto cumplo con el trabajo, aguanto a la tarde otro
rebote pero no vuelvo a tomar nada.

Ya decido que no voy a tomar analgesicos, nada, ni ibuprofeno. Pq veo
que no alteran el resultado de la evolucion del dolor, que si se ve
afectado por factores externos como actividad, comidas, bebidas,
actitudes. 

El viernes 1 todos los planetas se me alinean en contra y me producen
una situacion que me termina generando una migraña de grandes
proporciones, y me la aguanto sin tomar nada, sufriendo en carne
propia viernes noche y luego sabado noche, y luego parte del domingo
hasta que tome un migral el domingo. 
Desde alli el sistema se equilibro.

O sea que en resumen:
Un migral tomado el domingo 24 por quizas apuro de situacion, si no
hubiera tenido ese compromiso me la aguantaba.
Un migral para abortar una migraña que ya llevaba dos dias matandome
(y felizmente fue efectiva!! pq estaba dispuesto a meterle hasta 6
migrales).
Haber comprobado que analgesicos menores no hacen nada por uno. 

Desde el punto del WD vi:
que una cortyterapia breve de 20mg fue altamente efectiva para cortar
una racha de 45MIG. con bajos niveles de rebote. 

Efectos observados del cortypiren: alta irritabilidad como en
tratamientos anteriores, parestesias en la cara solo uno o dos dias al
retirar, no hinchazon de articulaciones, no cansancio, no note
hinchazon de cara, si note un incremento de "Inteligencia" como las
otras veces.

Conclusion: creo que antes se le pedia al cortipiren no solo que que
hiciera el WD sino que fungiera como sustituto del MIG o sea que
supliera la etapa intermedia.
Si uno ve el cuaderno con la xp del WD17 ve que luego de la terrible
etapa inicial, terrible por lo alta, es similar a esta, casi calcada,
o sea pocos dolores, dias libres de todo, y cuando uno va reduciendo
van apareciendo dolores menores que uno ya empieza a manejarlos con
ibu (al que llegamos por descarte luego de haber probado todos) en
forma creciente y caemos en MIG tambien para las migrañas que parece
que siguen existiendo, y a su vez nos aferramos al cortipyren pq
pensamos que "previene" o "sostiene al KRAKEN" en su guarida para que
no salga. Pero no es asi, o sea la migraña esta supongamos
"predestinada" a salir con o sin COR y lo unico que podra reducirla es
el TOPI, si podemos pasar de 4 a 2 o a 1 episodio por mes, y lo
podriamos manejar con migral no hay problema, el tema es la jaqueca,
que si es tensional pq la producimos por nuestras creencias, o nuestro
sistema de vida en donde nos autoflagelamos, (no dormimos bien, no
comemos bien, no hacemos ejercicio, tenemos malas posturas, no
descansamos entre tareas, excedemos las pautas, y un largo etc.). Si
esa jaqueca la tratamos con ibu, nos vamos a 30/40 ibu por mes lo cual
es malo tambien, y luego caemos en el autoengaño del esquema falso de
decirnos "es mejor tomar migral directamente que tomar ibu y despues
migral".
O sea 
1. EXTENDER CORTITERAPIA PARA "PREVENIR" MIGRAñAS --- MAL
2. TOMAR IBU PARA ELIMINAR CUALQUIER DOLORCILLO ----- MAL
3. TOMAR MIGRAL PARA CUALQUIER DOLOR ---------------- muy MAL

empieza el problema con la BTF y el bajo umbral de dolor, o sea
tenemos un bajo umbral de dolor, entonces creemos en el fondo del alma
pq asi nos hemos criado que tomando la pastillita nos vamos a aliviar.
Y asi parece. Pero no es asi. Es un engaño como todo engaño.
Como el engaño del clonazepan, como el engaño de ser empleado.
¿Cual es engaño del empleado?. Vos naciste emprendedor, todos nacemos
emprendedores, es la condicion natural del ser humano, entonces viene
alguien de afuera, llamese sociedad, llamese medios, llamese familia,
llamese mama, que exagerando y manipulando datos te dice que "te
conviene" NO ser emprendedor, te conviene ser empleado. Y eso que es?
Pregunta uno. Es trabajar para otro emprendedor. Y porque no puede ser
al reves que el otro trabaje para mi? NO nene vos no tenes lo que el
otro tiene. Ahh entonces a mi me falta algo. Primera herida al ego,
soy menos, debo ser inseguro, me conviene ser empleado. Aparte tendras
ventajas.
Cuales? Nunca te faltara la plata? En serio mama? y porque vos y el pa
siempre se pelean por la plata? ... Bueno eso es otra cosa... La cosa
que te convencen que tenes que ser empleado porque es mas seguro y es
mas comodo. Obviamente te van a pagar menos, pq el que te contrata va
a ganar sobre lo que vos hagas.
Pero hay una consecuencia mucho mas grande, como ser empleado es mas
facil que ser emprendedor, te sobrara mucho tiempo mental y tendras
que ser "entretenido" y ese entretenimiento te lo regalaran
(venderan?) con todo gusto pq en el medio te adoctrinaran en la forma
que ellos quieran. Ellos quienes? los que necesitan que hayan
suficientes tipos como vos.
** CONCLUSIONES SOBRE EL POST-WD
veo que se debe ir cambiando la forma en que se hacen las cosas si
queremos cambiar el resultado p.e.
1. atender las pausas de 10 seg y 2 minutos sino terminaremos con
   rigideces de cuello y hombros que luego producen estados jaquecosos
2. seguir cuidando el sueño tanto con la suspencion tecnologica
   despues de las 21hs como respetando las rutinas de siesta y
   cantidad de horas
3. respetar las comidas principalmente al mediodia, tanto en
   regularidad como en calidad, no volver a la comida chatarra ya sea
   por cansancio o por falta de compras o por falta de innovacion.
4. evitar caer en la creencia de que se puede dejar generar el dolor
   total lo "matamos" con un diclo o de ultima con un migral, la sola
   idea de matar el dolor con un farmaco debe ser erradicada.
5. evitar estar en estado de tension, ya sea por enojos o por
   preocupacion o por disgusto o por sobrecarga de trabajo, o por lo
   que sea. [sino ver dia viernes 29]
6. Evitar el "encierro" del nuevo local o sea la situacion en la cual
   nos metemos ahi dentro y nos sometemos a una toxicidad que no
   sirve.
   O sea es una mezcla de toxicidad por enojos y enconos y
   enfrentamientos y falta de aire, aire viciado, falta de movimiento
   y compensacion via cafeina. Porque todo eso termina generando
   situaciones que no convienen a nivel dolor.
7. Casi completando el primer mes del postWD con 16 aines y un mig
   pienso que es mucho aine. Maxime que muchos de ellos fueron al
   vicio y se podrian haber obviado para no caer nuevamente en un
   consumo cada vez mas alto que nos traiga otro tipo de problemas,
   p.e. digestivos. (naprux y diclo son fuertes en ese sentido)
8. de acuerdo al Dr Williams Romero en la visita del 17 de Abril 2019
   el exito del tratamiento se debe en un 50/50 a los factores
   profilacticos antes descriptos.


