| [2019-02-18 lun] | 1M-12hs   | i600-17hs |               |
| [2019-02-19 mar] | 1M-03hs   | i600-12hs | 1M-23hs       |
| [2019-02-20 mié] | i600-15hs | M-15.45hs | C10mg-16.30hs |
| [2019-02-20 mié] |           |           |               |
|                  |           |           |               |
* [2019-02-18 lun]   
tomo el migral tipo 13hs mas por evitar el rebote que por necesidad
real, y luego me doy cuenta que al rato la molestia sube, pero lo
mismo era un dia complicado pq tenia un compromiso y grande a la
tarde, pero todo termino bien con solo un ibu de refuerzo.
* [2019-02-19 mar] 
no pude llegar al mediodia. Me deperte a las 3 am con un N6 y tuve que
tomarme un migral, fue efectivo en unos cuarenta minutos, y me volvi a
dormir a las dos horas, luego comence el dia con normalidad.
Tipo mediodia se empezo a arruinar el dia y me tome un ibu, y ahi note
la diferencia de la falta de ambiente para enfrentar un cambio o al
menos tolerar y darle batalla a una reduccion en la toma de
analgesicos aguantandose el dolor. Pq no pude retirarme y pq mi casa
es la oficina o no tengo casa. Me vine para hacerme un arroz, el cual
fue demorado y ya no puedo comer mas en la cocina pq me da asco y me
retire al dormitorio, y bastante bien, pero me hizo mal el agregado de
la pasta de aceituna que la estoy repitiendo hasta ahora (quien dice
que no tenga un aditivo) y luego no puedo sustraerme y ya estoy casi
en un N5 como para estar reposado comodo intentando dormir.
Y tengamos en cuenta que tengo un desfasaje de sueño pq el migral
nocturno me dejo sin dormir y tendria que haber tenido una siesta.
Tipo 15.30 Fede amablemente se va pq yo llegue al limite de aguantar
con un N4 levantado, y me dispuse a acostarme relajado, y el problema
no era tanto el dolor, pq ya estaba libre para relajarme y tenia mucho
sueño, sino que no podia tumbarme para ningun costado, era enorme la
presion, mas que ninguna otra vez pero sin puntada, y cuando me
levantaba salia el aire. El dolor fue en aumento, en todo momento
estuve incapacitado, creo que llegamos a N7 (en oscuridad, ni siquiera
pensar solo dormir o intentar). Puedo dormitar una hora, y la molestia
deviene ya con nausea, y un asco total por la repeticion continua de
la pasta de aceituna (ya la otra vez me habia pasado en el marques),
crei que vomitando aliviaria pero no hubo modo, solo tome agua, y mas
agua y aguante, tipo diez de la noche luego de dormirme cada vez por
mas tiempo, parecia que me mejoraba y no.
En realidad el dolor bifronte, como si me levantaran la mollera desde
adelante para sacarme el cuero cabelludo con una cuchara de albañil se
transformo en una hemicraneal limpita de lado derecho no totalmente
intensa pero si un N5 con vias a aumentar. Eran las 23hs y no habia
comido, estaba debil y no creia que podia aguantar una migraña
verdadera durante la noche, entonces me tomo 1 Migral a esa hora, es
efectivo en una hora desaparece el dolor, en el mismo momento molesto
como estaba me hice el licuado, y lave los platos por las cucarachas
de la cocina, me tome solo vaso y medio de licuado y me dormi. No muy
comodamente, pero bastante mejor que la tarde.
* [2019-02-20 mié]
A la mañana me levanto debil, tembloroso, iba a decir como tension
baja, me tomo un vaso de licuado, y me compro facturas, y desayuno un
cafe, con dos facturas dulces, que como con ganas, y un beroca que
tambien paso sin dificultad, no mejoro, pero pasable, y me voy a pagar
boletas, maso.
Me mido la tension y me da 12/6 o sea si baja.
segunda medida ya cinco minutos despues de estar sentado: 
12.3/ 6.8 y 98 ppm. 
Voy al neurologo y tengo que esperar dos horas que me atienda. Ya me
habia mejorado bastante el sintoma de baja tension, y tenia una
jaqueca creciente pero no era todavia amenzante. 
Luego almuerzo en el hp bien, en un ambiente agradable y al final del
almuerzo tomo un ibu, y al llegar aca me va creciendo la jaqueca y no
lo pienso mas y me tomo el migral para abortar cualquier problema.
Luego de 45 minutos de migral solamente se agrava la migraña, esta
bien que la situacion hace que no pueda salirme de la situacion y me
tomo un C10mg y felizmente el fede me compra lo que me hace falta de
viveres minimos para sobrevivir y ya daremos por terminada la jornada
y me podre acostar.
Creo que faltan solo dos dias para finalizar esta tortura. Pero creo
que la pauta que me dio el doc puede aliviar el status migrañoso.
