* WD fallido descripcion
UM el sabado 22/2 a las 2 am, decido empezar la cortiterapia con casi
35 hasta esa altura del mes, pero empiezo tarde tomo a las 10.25 la
primera dosis de 20mg, pensando repetir la pauta del 2019 o sea dosis
unicas matinales de 20mg. 
A las 20hs tengo mucho dolor articular de cadera, hombros y codos y
tomo un ibu 800mg y puedo "llegar" a la mañana siguiente al proximo
cy.
El domingo 23/2 a las 8hs tomo 20mg y reporto dolor cefaleico desde
las 8hs en adelante persistente N3/N4 que luego llego a N6. 

decido "abortar" el tratamiento pq encima estaba encuadrado en unas
circunstancias vitales muy estresantes y peligrosas (el final incierto
de la obra y su pago final, y no habia quedado de acuerdo con el Fede
de poder tomarme una o dos semanas de franco). y entontes tomo un
migral a las 13:24hs  ya nauseoso. no paso nada, sigo sufriendo tirado
en la pieza recluido en el oscuro, intentando dormir, y cuando mas o
menos se van haciendo las 6hs permitidas para repetir migral tomo otro
a las 19:30 reportando un dolor intenso tipo N6/N7 toda la tarde
ininterrumpido. me tomo una SL y me tomo un tercer migral a las 1.30
menos nauseoso y puedo dormir mejor y me levanto el lunes con una
resaca del N2/N3
Teniendo en cuenta que lunes y martes era feriado.
a las 12hs del lunes la resaca habia subido a N4/5.
tomo SL a las 13hs
otro migral a las 17hs muy dolorido punzante N7 sigo lugo con N6
persistente. 
a las 19hs ante la inutilidad del migral tomo 10mg de Cortypiren como
ayuda. amagando a un estatus migrañoso y luego a partir del martes se
estabilizo nuevamente en una situacion ""normal"" de dos migrales por
dia.
Pude trabajar el resto de la semana con dos migrales por dia, hasta
que decidi hacer un nuevo WD pero con el doble de la dosis.
* WD 2020 - 29/02/20
Pauta posible:
10 dias 20+20
5 dias 20
5 dias 10
5 dias 5
total 575  (WD19 390 WD17 1668)

UM-28/02/20 23:30hs
** [2020-02-29 sáb]
comienzo bien a horario 8hs y 20hs 20mg cada dosis.
18.30hs tomo Naprux con mucha dificultad gastrica y no fue efectivo
tipo 20hs incipiente N5 y molesto un N3/N5 toda la noche
** [2020-03-01 dom]
dosis idem 
18.30hs tomo Naprux por un incipiente N4 y fue efectivo
** [2020-03-02 lun]
dosis idem
se "agrego una sobredosis" de 10mg de refuerzo a media tarde para
intentar conjurar un N6 al vicio pq no funciono.
9hs ya empezamos con el Naprux con un N3 que rapidamente escalo a un
N6
fue el primer dia de trabajo en el tratamiento a pesar de que era en
la casa. pero estuve dolorido, fue el tercer y ultimo naprux de la
serie llegando a la conclusion que no me hace nada y que es
gastricamente muy malo. y a la tarde "probe" con agrandar al dosis de
cortipiren pero no altero en nada el curso del dolor.
** [2020-03-03 mar]
dosis idem
dia esplendido sin ningun sintoma
** [2020-03-04 mié]
dosis idem
nuevamente decido a las 15hs "reforzar" la dosis con 10mg pq arreciaba
un N5/6 y luego de la siesta cedio
** [2020-03-05 jue]
dosis idem
dia esplendido
** [2020-03-06 vie]
dosis idem
N3/4 durante la jornada que se fue subiendo luego de las 17hs a un
N8, no cediendo y descansando relajado por un clonazepan 0.5 luego
casi digamos que llega a niveles de N9 pero me logro dormir y a las
23hs mas o menos ya habia cedido.
** [2020-03-07 sáb]
dosis idem
N3/4 a las 14hs - N5/6 a las 17hs
me levanto de la siesta con clonazepan con N6 y baja a N0 "con
episodio de pintura en el patio" (ver descripcion en conclusiones)
vuelve N5 a la noche que durante la noche baja a N1
** [2020-03-08 dom]
dosis idem
dia normal
** [2020-03-09 lun]
N2 12hs N4 12.45hs N5 15hs
me levanto de la siesta con un N5 y se baja a N0 con tareas de cocina
(similar al sabado ver descripcion en conclusiones)
** [2020-03-10 mar]
20 mg C 8hs - hoy comienza la reduccion o sea a la tarde no se tomara
la segunda dosis
N0 hasta ahora.


* conclusiones WD 2020
** Ni el Naprux ni "reforzar" la dosis sirviron para aplacar los rebotes
de los tres naprux tomados uno solo parecio ser efectivo, y las dos
dosis de refuerzo no sirvieron de nada. Solo el descansar con relax
(musica,tranquilidad,clonazepan si es posible) parece ser mejor.
** carga laboral-estresores 2019vs2020
esta vez no trabaje en toda la semana. solo hice mi teletrabajo que me
resulto bastante llevadero, salvo en algun que otro momento de los
dias en que estaba cursando rebotes fuertes no tuve problemas. Al
comienzo de la semana pensaba que podia estar beligerante con la gente
o tener nerviosismo agregado por el tener que rechazar ventas o cosas
asi, pero felizmente la semana transcurrio muy buena en ese sentido y
muy satisfactoria de modo que no afecto para nada el tratamiento, al
contrario le dio un poco de actividad, pq tambien creo que no seria
bueno el excederse en el estar sin hacer nada.
Por el resto del negocio me preocupe cero, y por el tema de la obra,
decidi levantarme temprano a las 7hs cuando venian los pintores el
jueves y viernes y estar presente y fui a las pinturerias a comprar lo
que hacia falta sin ninguna dificultad. No se si el estres de ayer
viernes en el transito por ir a Alem 1666 internamente me causo el N9
de la tarde, eso es algo que desconozco, pero en el momento no me
senti nervioso de mas ni nada. 
No me surgieron cuestiones dificultosas de llevar como en el
WD2019. Menos mal pq eso ayudo a que pueda transitarlo en forma mas
tranquila.
** otros sintomas anexos
no he notado dolor articular esta semana, ni cansansio excesivo salvo
el usual de siempre, ni cambios en el apetito.
las series las pude hacer todos los dias del tratamiento creo que un
solo dia me resulto un poco mas dificil  hacerlas pq ya estaba con un
N4 mientras las hacia.
El unico sintoma que puedo aportar es el aura en el ojo izquierdo que
dura unos 5 minutos, que generalmente se da cuando me pongo a ver el
tv del living y luego se va, no necesariamente precedio migrañas, Y
este sintoma calculo que lo he tenido hasta ahora tres veces.
En este WD no experimente ningun nivel de "inteligencia" extra que me
habia parecido tener en el pasado con otros WD.
Tampoco trastornos de sueño.
Tampoco parestesias.
Si ciertas cualidades imaginativas libres que la mente desarrolla en
sus dialogos internos en la noche cuando me levanto, que se evidencian
mayormente en los personajes usados como que fueran mas vividos y se
prestaran al dialogo literario. Nada loco, sino como mas fluido.
** cambio de dieta en medio del tratamiento
desde el viernes 6/3 me paso a una dieta de almidon (vegana) sin
productos artificiales con el objetivo de ver si son los productos
quimicos los que me afectan en la migraña. 
** reduccion de jaquecas leves con actividad
tuve dos episodios de levantarme de una siesta (incluso con toma de
clonazepan 0.5 para inducir dopacion mas profunda) que no fueron
efectivos para aplacar sino al contrario agravaron cuadros, pasando a
veces de N4 a N6.
Uno el sabado [2020-03-07 sáb] que salgo al patio y me pongo a
pintarle el mueble a la Cami y luego me siento en el patio, y demas y
el N5/6 pasa a N0.
y el otro el [2020-03-09 lun] que me levanto con N5 y me pongo a hacer
tareas de cocina, haciendo la leche de avena, moliendo sesamo y demas
y tambien paso de un N5 a un N0.
O sea en ambos casos no se trato de tareas hiperactivas como las
referidas en el 2019 con la limpieza de la cocina sino de distraccion,
o hacer otra cosa quiza que no sea estar acostado.
