"los que quieran que el futuro sea diferente del pasado deben estudiar
el pasado" .-- Spinoza
"Si en todo oficio no se pone consciencia no se puede prosperar". --
Shakespeare


CAMPO II ETAPA
* tomo I 13-04-13 a 30-06-13
...14-04 luego vere que proyectos se consolidan y cuales quedan en la
nada y se olvidan.

...primera noche...sino tuviera un año de experiencia durmiendo aca
estaria cagadazo, pero todo ok.

...es muy loco volver a la misma cabaña pero mejor pq ya conozco como
son las cosas.

...el dia estuvo tramado por la preocupacion de reorganizar el negocio
(de tener que).

...no hay dpto o casa que se compare a esto aca. El viaje es lo de
menos, y la soledad tambien la tenemos alla.

...hoy cuando pensaba a la ida que podria cambiar el tjo para hacer lo
que me gustaria rapidamente volvi a la sensatez (por peaje), pq no voy
a ganar esto sentado en ofi por mas que crea que es alienante o
hartante.

...el nivel basico de vta para funcionar cubriendo costos seria 50k y
en Ago12 estaba 60k con plan simple y con faltante de vta.

...El concepto que tengo de la cabaña es que es un lugar propio para
vivir que yo elijo, el viaje no me interesa igual que el manejo. Sino
el vivir bien y mejorar los habitos alimenticios. Cabaña no es
contrario a tener buena pilcha sino le agrega fuerza y naturaleza.

...18-4 hay algunas rutinas que por ahora me hacen bien, p.e. hamaca
vespertina, el comer sano, comer fruta.
Tengo muchas cosas todavia por hacer tanto tareas como proyectos como
distracciones. Viene a ser tmb como pasar el tiempo pero de otra
forma. La idea es cambiar de habitos y buscar otro horizonte de vida
que no sea el encierro en cuatro paredes y la tele.
quiero 1gfpc.
la vida es filosofia y hay que saber vivir contento con lo que uno
tiene.

...sali hice una linea del bancal. Dos misterios: que no me picaron
los jejenes y que la tierra este tan mojada.

...23-04 mal mal de salud creo que una migraña (voy 3 Mig) 7am-14y
17hs.

...24-4 nuevamente a las 20hs en el sobre, ya un habito, jeje, pero no
siesta y actividad a la tarde.

...El campo queda en un contexto bien organizado como una eleccion por
la salud, por el movimiento y por el aire puro o al menos mas puro que
en la ciudad. Una eleccion de estado minimalista y filosofica. Pero
habria que buscar salida a la presion que se genere para no caer en
decepcion y contraciclo.

... las rutinas son importantes pq son las que marcan lo que sentis
respecto a como vivis.

...sabado 27-04-13
seria un dia arduo, de gran prueba si no hubiera tenido a la mañana el
condimento del wapp.(1er wpp de Vdez)

...la gran falacia es visualizar variedad en el centro (ojo que tmb
hay en ag) y creer (lo creia antes, ya no) que el centro te daba la
posibilidad de obtener alguna cuota de ese mercado. 
pero la realidad es que no, parte pq los musculos envueltos no estan
desarrollados (y una vez desarrollados se podrian ejercer en ag si
quisiera), y parte pq la vida en la ciudad me quita el sentirme bien
que es fundamental para encarar todo con vigor y salud.

...hoy tengo de nuevo una migraña de 3 a pesar de haber estado en casa
y me siento mal como mareado y tomo consciencia que estoy con
semblante viejo muy demacrado y poco nivel de fuerza realista.

...olvidarme de todo pq quiero una gfpc no una palomita de la virgen.

...hoy venia para aca y venia mal pq estaba embroncado pq estoy solo
pq sali de la casa en un momento critico y despues el FEde termino
yendose y yo quede offside por el cambio.
y decia bueno ya estoy debo ahora apechugar ya lograre equilibrarme.
...Creo que la ataraxia, la alimentacion sana, el movimiento, son
proyectos basicos pero pueden caer en el vacio del nihilismo. Por eso
la gente se pierde en lo cotidieana en lo superficial y en querer
poseer cosas.

...que el bajon no te impida apreciar esto o sea la naturaleza.
En este sentido el libro de Robin (sobre los venenos) pateo en contra
justo en un momento bajon pq cai en una desazon planetaria ya no
sistemica, al estilo Charton Heston en planeta de los simios cuando
vio restos de la estatua de la libertad como desazon final de que todo
esta perdido. 

... Entonces sumado a la desazon de no ver el entorno, de estar muerto
ante lo intelectual (anoche inexplicablemente me dormi literalmente a
las 20hs y por 13hs) y de la imposibilidad de permanecer hasta cierta
hora hacen un coctail malsano. acuesto de tarde, me duermo rapido, me
levanto tarde, me duele la espalda, hago poco, decepciono ante falta
de fuerza y proyectos.

...Como parte del periodo de desazon esta el miedo al futuro por la
total indefension siendo que todavia tengo gente a cargo por diez años
mas.
pero lo bueno es que al venir aca plantie un cambio de vida, hacia una
postura mas sana, filosofica y minimalista de la vida, o sea lejos del
exito mundano caracterizado en 2008 y que volvio al menos en relato
estos ultimos seis meses.
Como se manifiesta el cambio de actitud?
1. la idea es trabajar en forma continua para vivir sencillamente y
   asegurar el futuro retiro
2. vida sencilla es conservar el auto o cambiar por una chata de
   similar valor - pasar a considerar el auto como un medio de tte no
   como ninguna otra cosa. No derroches en gastos de ningun tipo
   incluidos gastos de ropa.
3. vida sana. Como prioridad de vida y acomodamiento de valores
   incluyendo la ataraxia y la filosofia pq no hay forma de vivir o
   soportar la vida.
4. como objetivo secundario una gfpc no hay incompatibilidad con el
   tipo de vida planteado.
Esta actitud cauta puede llevar a un sistema sustentable de unos 10
años vista. No olvidar que tecnicamente me quedan 17 años para el
retiro.
Si dedicara estos 17 años a una sola cosa la cosas seria diferente,
p.e. en focalizar, repensar, y generar una teoria util que sirva a los
propositos utiles.
MAYORMENTE ESTA VIDA QUE LLEVO TIENE MUCHO DE TIEMPO LIBRE Y ESO
CUESTA ADMINISTRARLO.

...en estos dias de exceso de tiempo libre y en el campo solo son
recurrentes los malos recuerdos, los pensamientos nefastos.
El otro dia escuche en la radio que el ser humano recuerda a
diferencia de otras especies y eso le juega en contra cuando o porque
los malos recuerdos son los que predominan.

... El hecho es que yo aca o alla o en un dpto me siento mal y estoy
igual o sea no genero soluciones.

...Puede ser que estoy procesando el embole de que Fede se fue y
cambio todo, pq podria estar tranqui alla con la flia, ojo no me
engaño queria irme pero ante el riesgo del trabajo preferiria no tener
el costo extra y eso me mata, me emperne en un costo al pedo y ahora
tengo que cortar clavos la p.m.

... 36 migrales en 20 dias!!!
del 14/4 al 4/5 posibles causas:
1. alto estres!!
2. cambio de habitos de sueño, dormir mucho, muchas horas acostado.
3. cambio alimentario
4. agua!!
5. enalapril

...8-5-13 hoy me cuestiono todo no solo el campo sino tambien toda mi
vida. Pero pq tengo que vivir esta vida rara y dura?.

...SOLUCION NEGOCIO EXTREMA
entrego yo las ventas. traigo toda la marcaderia al campo y/o marques,
ahi saco el tema mas importante dejo solo un minimo simbolico para
cobradores.

...Esto es energizante y generador de alto nivel de resultado y
trabajo. Y me acerca muchisimo al LMM y LMMplus 1 y 2 (clientes/calle)
con movilidad y cubrimiento de costo o sea olvidar inmovilidad.
Sacarse la distancia y la inmovilidad dyeriana, con movimiento,
trabajo, normalidad, relacion, optimismo.
Es solo reparto no tiene que haber desasosiego.

...Como correlato a un problema que es las consecuencias reales de los
juicios laborales caigo en la cuenta que no puedo exponer mercaderia
alla y luego de la crisis de un minuto caigo en la cuenta de que puedo
repartir yo y alli se abre todo un panorama general muy importante:
1. no solo aseguro el local - saco mercaderias
2. sino potencio la promocion pudiendo generar 100k o mas yo solo o
   sea sin depender del Fede.

Sigue la valoracion de la independencia, mi sitio y cosas pq he sido
muy ninguneado y estos meses aguante muchas cosas.

...Resumen
1. Estuve sometido a un gran estres aunque no lo haya aceptado, el
   cambio de casa, el cambio de tjo.
2. considero superado el primer bajon de vivir aca, respecto a los
   proyectos me los replanteo
3. me corrijo un poco de posturas apocalipticas extremas, yendo a un
   punto intermedio mas realista. Debo luchar contra el apocaliptismo
   que me lleva a la depresion
4. el 8/5 nacio una nueva idea de negocio, la mejor de los ultimos
   años.
5. puede que trabaje 8hs pero gano 40k
6. agrego LMM anexo en avisos idem
7. paso papeles en cabaña mejor todavia agrega mas seguridad - compu
   vacia, pendrive 

... veo que el estado de salud en general es bastante peor que hace
dos años.

...es obvio que sufri un estres impresionante desde el llamado, el
proceso ida y vuelta, el quedarme solo, en el medio el cambio de casa,
quede en el medio entre el susto de los mayores costos y la desazon de
la futilidad de caer de nuevo en un 2011. Luego el dia de la
notificacion y previo el estres de juntarle la plata al Fede. Total
estres afecto a la somatoforme y al malestar.

...Hay un cambio de paradigma que se manifiesta en la vestimenta y en
el rol.
en los 90 era el empresario, gerente, usaba traje etc. en el 04 en
adelante era el formal dentro del sport pero asumia ciertas
convenciones y transmitia ciertas cuestiones (Ej transmitir ciertos
usos culturales y facetas personales como acercamiento a la gente como
donde vivis. etc.)
y por ultimo en los tiempos del 2008 asumia un rol equis desde el que
no me pude mover.
Ahora hubo una rotura de esquema. Que se plasma en salir a la
calle. Hay incluso una resistencia de parte de la familia (en especial
el fede) como que estoy fuera de posicion.

...27-05-13 (a 43 dias)
No se porque extraña razon termine volviendo al mismo campo que antes.

...en el ultimo tiempo el eje de la "fortaleza" se movio de la
experiencia campo a la "experiencia" laboral, tanto el extasis de la
calle (el poder hacer una funcion sin desasosiego conquistando el
mayor miedo) y eso hace que los proyectos hayan quedado al margen o se
hayan diluido mucho.

...que lleven a una discrecion o a un cepo comunicativo (o a la
apertura de otros interlocutores y en otros terminos - eje Romi, mi
vieja y la discrecion total frente a ih, fede y los empleados)
¿Cuanto hace que no vivo la sensacion de estar generando un sistema
propio sin necesidad de contar ni rendir cuentas? ¿Ni de estar con la
sensacion de deberle algo a alguien?

La realidad es que ya no quiero transferir lo instranferible ni
delegar lo que puedo hacer yo. Ni tampoco quiero contar lo que a nadie
interesa como si yo me alimentara del acto de compartir y por lo tanto
necesitara contar.
Uno esta escencialmente solo y lo que vive o siente como vivencia
cultural es intransferible principalmente lo exultante o cultural.

...el clima , los colores, sonido, viento, pajaros remanentes,
actividad humana difusa, molienda de piedras, autos etc crean un
paisaje de un momento magico unico e irrepetible muy lindo y
energizante pq no hace frio y esta ventoso y seminublado de tierra y
es otoño pleno, todo se esta secando...

...1-6-13 resumen mensual
1. tremenda experiencia, cambio todo el panorama laboral. Es cierto
   eso de que enfrentando  el mayor miedo se obtiene la mayor fuerza.
2. reacomodo brutal del negocio en especial a la relacion de fuerzas
   (con promos, con cobradores, con Fede, con el sistema).
3. venta entregada por mi totalmente. Es andar en la calle, pero veo
   todo, soy ahora el panoptico y al menos puedo dirigir la operatoria
   en general
4. mas profesionalismo con los clientes atendiendo cambios y
   devoluciones asertivamente.
5. menor tiempo fijo en oficina
6. pasado papeles on pendrive!!! brutal
7. oficina liberada de papeles y mercaderias sin riesgo de embargos
8. sin estress.

...no preocuparse por la vida en el campo ya que los ingresos
permitiran arreglos que tendrian que aliviar la experiencia, sino
directamente el 30/9 rescindimos y punto.

...Tema de reflexion: Pq voy alla? ¿que me lleva a insistir con ih en
su variante de odio o que me lleva a aceptar sucedaneos?
ok esta el temor a la soledad, el plantearme qeu ele finde sera largo
y aburrido o la comodidad de que otro haga de comer o como dice arriba
el sucedaneo, el conformarse con migajas de una relacion adulta.
Uno de los temas recurrentes para atras es la pregunta ¿en que se
pasaron tantos años? lo cual es una pregunta falaz. Porque obviamente
vivimos dia por dia (no estuve en un coma inconsciente) entonces el
tema es ¿como vivi? o sea cual fue la forma de organzizar mi tiempo,
mi jornada, mis dias y obviamente ellos se articularon en familia con
ih, no importa donde estuve. Con cosas que me gustan y otras que odio,
y otras que odio pero que me gustan (?) sic.

Como hay falta de reflexion de ahi provienen las decisiones
equivocadas y la falta de objetivos.

El sistema de salir-yo-a-repartir siempre estuvo solo que yo no lo
veia, o no lo veia viable o no me animaba. Paralelamente puede haber
esquemas ocultos hoy que solucionen mi vida personal y simplemente
estan ahi. 

...el finde, famoso y temido finde. pq el dia de semana esta todo ok
pero el finde pudre todo y a la vez hay un millon de cosas que no se
hacen pq no hay tiempo.

...8-6-13 hable con Fede y le gusto un plan unipersonal puro de minimo
25k con esperanza a mas. Liceo/Remedios/Boulevares/Fragueiro.

...Sindrome de otoño: sensacion de incomodidad fisica ocasionada por
el frio, la suciedad ambiente, la sequedad de la piel etc. Aca se
magnifica por la sequedad de las manos, la suciedad del auto, la
tierra por todos lados. Pero ese sindrome me pasa en todos lados no
solo aca y aca se morigera con la fagina.

...No entiendo mi completa ignorancia politica de los ultimos 10
años. Crego que haber ignorado totalmente un proceso historico como el
que hubo hasta hace poco tiempo es muy llamativo. Y comparte la
sensacion que tengo de no "haber vivido" o haber estado en un proceso
de evasion de la realidad. O sea de un "pasar" el tiempo
brutal. ¿Donde se fue el tiempo?
El tiempo intelectual tuvo sus momentos
1. transformacion de conocimientos (tcl/sqlite/linux/arch/etc 2009
   betty mysql/sqlite/python 2010 vim/tcl/tk arch 2011...2012 paso a
   otro nivel con itcl y base datos y con arch xmonad)
2. desde la filosofia y el barro de la historia con JPF avance otro
   proceso que en filosofia habia sido erratico entre el 2003 y el
   2009

Curioso es que el 2009 fue un año bisagra en los conocimientos
generales con JPF y con linux/sqlite/python aunque en ese año no fui
conciente del punto de inflexion que se estaba dando en ese momento.

Obviamente hay un sufrir descarnado en todo el periodo 2003/2010 que
es el doloroso proceso de separacion. La ruptura con la familia y el
dolor que me causo la soledad y el no poder manejarla y el no poder
hallar un sistema viable para resociabilizar fuera del trabajo y fuera
de la familia.
Aun hoy siento que no puedo encontrar una forma de vivir feliz
solo. Porque me siento triste o aterrado frente a la disolucion del
silencio absoluto y el desgarro incapaz de dar solucion al problema
parte por no poder planificarlo-quererlo y parte por no poder hacerlo.

Hoy quizas el recurso mas valioso sea este cuaderno y tenga que buscar
en el las repuestas (que es otra forma de decir que buscarlas en mi
mismo).
Otro gran tema que nace en 2010 fue el alimentario que evoluciono y se
quedo.

...tuve los siguientes procesos campo-trabajo
1. Utopico: 14-4 - se va!! que cagada. pensaba gozar del tiempo libre
   sin grandes preocupaciones con posibilidades de tener para gastar y
   mejorar mi salud,etc.
2. Temor: x-4 - 8-5: efecto pobreza, bronca por haber alquilado siendo
   que si me quedaba alla eran menos los gastos.
3. recupero autonomia: 8-5 --> descubriendo una actividad directa que
   me genera mas dominio de situacion pero la vuelta del Fede la
   empaña.
4. aseguro autonomia 10-6 --> habiendo hablado con Fede que no unamos todo
5. autarquia 25-6 con el pago total de la deuda al fede. La idea del
   fede hasta ayer a las 19hs era una comunion de todo no una
   separatividad.

...Ojo que tambien no conocer las calles en los circuitos tan
transitados es parte del proceso, muchas "vueltas" me como por no
conocer bien los barrios.

...spot de crisis existenciales, cuando estoy en medio de la
faena. Pensando yo tendria que estar en ...(pero no se donde, pq la
referencia a la oficina se cayo.)

...14-06-13 hoy doy por terminada mi experiencia con ARCH linux. Hasta
otra oportunidad. Se han vuelto demasiado freaky para mi gusto. Me voy
a otra cosa. Es un desastre cada seis meses, no una
actualizacion. Ademas que voy yendo hacia los contenidos y no las
formas, asi que chau arch, y casi chau linux.

...tengo un efecto pobreza o de falta de entusiasmo inmerecido o
injustificado pq hay esperanza de lograr el objetivo de venta, de
formar grupo, de cobrar y no hay problemas de repago de la deuda, pero
caigo en la inconducencia de la nada. A pesar de que con filosofia de
campo vengo viendo cuales son los problemas.

Soy toxico? Soy pesado? soy denso? mayormente soy denso cuando pienso
o hago un proceso decisorio, sopesador, deliberativo en publico,
interactivo, ahi soy insano. el cuaderno no se queja y sirve
mejor. debo despejar o plantear las dudas solo. no molestar a los
otros en el proceso.

...Le Monde te abre los ojos a una realidad mundial y te da una vision
profesional de temas ignorados completamente... Vuelvo a la idea de
que estoy atrasado en mis lecturas.

...19-06- hoy fue muy duro volver a la cabaña de noche, totalmente
solo, sabiendo que no me esperaba nadie, luego de un dia de trabajo
duro sin ninguna alegria fuera del trabajo que compense.

...Resumen de la problematica actual
1. problemas de salud que "creo" posible corregir (pero no lo hago)
   como HT, acidez, espalda, falta de estado.
2. dependencia situacional dia a dia con ih a pesar del rechazo.
3. escasos resultados economicos.

...La bocha es ser independiente o ser un pelele.
si no soy independiente a mi edad mejor matarse.
yo articule mi vida alrededor de ih como un satelite que gira. Mis
separaciones, mis dptos, eran un permiso precario de salida por un
tiempo determinado segun pautas establecidas que no se podian obviar y
ella mandaba sopena del exilio definitivo al otro lado del rio estigio
en la zona tenebrosa del destierro.
¿que es estar desterrado? ¿que es esa sensacion insoportable de no
tener a nada y a nadie del otro lado? esa sensacion de soledad total.
yo me preocupaba por la felicidad de los otros primero de mi vieja y
mis hermanos cuando quedamos solos y luego por ih y las chicas, por
eso cuando me vine y quedaba FEde "safaba" pq era necesario safar. 
obvio que yo voy y ella ve que es al reves que soy yo el que necesito
ir alla. y es verdad hubo fines de semana que no me anime a atravesar,
ni siquiera a pensar en el tema.
aunque pensara someramente que una situacion de solo total luego de
todas las cosas por hacer pendientes me iba a levantar e iba a empezar
de nuevo. como lo hice con el reparto luego que el Fede se fue y me
dejo solo. primero me parecio duro comenzar de nuevo pero luego
renacio la fe en la independencia y me siento mas solido en ese
sentido.

... se que soy toxico para ih y las chicas y mi vieja y de Fede. Soy
un tipo toxico lamentablemente.
pq no proceso mis frustraciones asertivamente y las reparto via
conversacion alrededor.

La simbiosis con ih es la necesidad de aferrarse a la comunidad con
alguien para hacer mas soportable la vida. Es la "Ilusion" de ser
entendido, comprendido, conocido por alguien. Mayormente la simbiosis
es toxica y es un defecto como muchos que puede haber.

Tengamos en cuenta que los eventos que se describen en este cuaderno
transcurren con una alta toma de migral, aproximadamaente 50 migral
por mes. frecuentisimos dias de dos, dias de tres una o dos veces por
semana, 14/4 al 30/4 29 Migrales Mayo 48 migrales junio 51 migrales
y aparentemente una gran preocupacion por la HT, con tomas de la
tension y su anotacion durante todo el periodo casi todos los dias, lo
que evidencia una obsesion, y tomando propanolol y previo a el otro
antihipertensivo., muy frecuentes tensiones de 14/14.5.

merece expresar el debil intento pero unico al fin y al cabo de
caminata que fue ese mes con 5 sesiones que completaron 200 minutos
entre el 20 y el 30 de junio.

un periodo muy tramado por el deseo de marcar mi independencia, de
dejar de ir (NOIR), de dejar de depender, de haber encontrado en el
coraje del reparto el camino para independizarme y no querer volver a
depender del Fede de nuevo.
Por momentos parece que hubo un deseo de venganza muy grande que duro
demasiado tiempo (casi dos años), pero que permitio lograr una
independencia en ese momento.


