* Agosto 2015
...grupo de venta en dia "abierto". (Debe ser en el dia para estar con
la gente, darle la muestra y controlar y abierto para no caer en la
rigidez y en la dependencia a unos pocos y los mismos).

... cortina 5x135 - costo 170

...es muy lineal tambien la relacion entre los elementos sanos y el
efecto sano (p.e. dos cucharadas de lino bien procesado - remojado y
licuado- tomado ayer y anteayer desembocan hoy en un sorete de
40cm). Me gustaria ver el efecto de 10 dias de un lts de lino a
7minutos (gelatinoso) y malta por infusion (no te, no mate, no cafe,
no gaseosa) en la acidez estomacal y asi sucesivamente. El licuado
venia muy flaco ultimamente y ahora lo potencie un poco y le falta
levadura, maca, espirulina.

* Octubre 2015
... y en zona en la venta me agarra la apatia lo cual es feo y no
logro enchufarme salvo momentos como hoy, pero como adormecido. Y hoy
lo descifraba bastante bien en la calle lo que sufro es desamor. Un
continuo y persistente desamor de pareja. Y lo tapo poniendole onda a
una seudorelacion que no lleva a nada.

* Noviembre 2015

...ayer hago un raconto, muchos o pocos o algunos temas recuperados de
mis pequeños goces solitarios: ver una buena serie, escuchar buena
musica, retomar alguna lectura, escuchar radio, hacerme una buena
sopa...

...Estos dias he demostrado una capacidad de recuperacion rapida y
grande pq logre 24 cortinas vendidas con 4 promotores y luego 14 con
precio nuevo el segundo dia.

...necesito fortalecer el grupo para vender un minimo de 15cxd.

...Hay sintomas como
1. el extremo debilidad de sentadilla (que produjo hernia y produce
   dificultad de sentarse en asientos bajos)
2. el adormecimiento de pies en breve tiempo de estar sentado
3. el bailoteo de los tendones de las manos que no se si lo causa el
   topiramato o son aparte.
4. es obvio que muchos migrales tomados son tomados no en procesos de
   migraña sino en procesos ansiosos en los que no se soporta una
   cefalea comun y uno cree que el migral la corta (y a veces no es
   asi)

[2015-11-09 lun] hoy es un dia aciago pq desaparecio michifuz. Mucha
pena. Mucho dolor. Menos mal que di salida a ese dolor y estoy mas
aliviado.

...Para que es la sociedad uno se plantea?. Para cuidarse las
espalas. Para apoyarse mutuamente. Para estar cuando al otro le haga
falta. En ese sentido somos mas fuertes unidos que separados.

...[2015-11-20 vie] y lo peor de todo es este parate de venta actual
producto de la situacion eleccionaria. Si habia efecto pobreza hoy hay
efecto catastrofe.

...Por empezar me atreveria a poner un principio:
No contrates la venta que puedas hacer vos: O sea mientras haya venta
mediante tus clientes para que contratarla aparte.

...Lo que observo es una falta de entusiasmo atroz. No me entusiasma
el proyecto y no me da ganas nada ni lo veo en forma epica ni en forma
diaria, directamente no lo veo. Me resulta una obligacion gravosa.

* Diciembre 2015
...hacer CM ... planillas de control impresas ... resumenes o
refundicion de temas para editar el escrito historico sedimentario y
olvidado.

...Creo que en estos ultimos dias de la semana pasada se dio el punto
de inflexion del año en el cual creo que no me importan las vacaciones
o creo que no necesito vacaciones pq creo que todo pasa por dentro de
uno. O bien me paso lo de siempre que cuando algo se me acomoda dentro
de mi se me antoja que la rutina es lo que pone bien y la sacada de
rutina es lo que me altera o me molesta.

... Concepto: pensar si algo vale la pena hacerlo en funcion de un
plazo de un año o un medio plazo, entonces muchas cosas adquieren
mucho valor: p.e. el programa pushup a un año puede ser muy grosso.

Cuando uno vive continuamente en el corto plazo en la inmediatez todo
se pierde y no hay logros pq no se producen los cambios. 

...limpiar todo, tirar todo, dejar todo mas facil de limpiar, y
organizado.

...Larga charla con ih...

...20/12 ataque de minimalismo ganas de simplificar todo.
ganas de profundizar los proyectos mas a fondo para lograr una mas
rapida recuperacion o rehabilitacion.

...estoy cambiando adiccion a diarios y noticias por libros y estoy
leyendo uno solo "alguien volo sobre el nido del cuco"

...22/12 creo qu el punto de crisis fue cuando ih me dice que me vaya
a vivir alla, eso me mueve todo el panorama por una sencilla razon: no
quiero ir pq se como es el tema, que me voy a sentir encerrado y mal y
no voy a poder estar como quiero estar yo lo cual no implica que sepa
como seguir aca ni como arreglarmelas aca. Lo que pasa es que venia de
un proceso de exteriorizacion de broncas hacia todo lados en especial
hacia el negocio por la frustracion que me habia causado el freno del
negocio y el parate y el no poder volcarlo a algo positivo. Ahi me
caigo y cuando comienzo a generar algo positivo cuyo eje es el pushup
y me quiero comprar la cama/mesa de luz etc viene esa bomba que
interrumpe todo.

...Debo ir mas rapido en los experimentos para hacer la diferencia
mientras pueda pq puede que no pueda para siempre seguir solo.

23/12 comprar colchoneta ... jaja


* Enero 2016
...excurso asi como vamos con ih, suavecito, tranquilitos hacemos 15k
y llegamos sin estridencias a las 300 lucas y eso que no tenemos cosas
raras o sea mercaderia nueva ni especial que podriamos usar para
vender mas. Y la cuestion es seguir todo el año pq asi lo tenemos que
hacer y asi lo hicimos con el deivi en el 2014.

...22/1 plan campo nuevo
ayer fuimos a AG con ih y me gusto en lineas generales mas que
Cordoba, la idea seria:
1. cambiar el auto por una amarok 2012 
2. comprar lote en anizacate
3. construir cabaña
4. desarrollar zona sur y en el futuro ag
zona suficiente para vender 300k por mes 
puedo permutar el local por un lote y empezar a construir con lo que
tengo para retirar de la sociedad.

...Plan Fenix F
1. he visto que la cortina es el unico articulo que puede ser vendido
   Delta 4 sin problemas de precio final
2. tengo la experiencia de la venta dirigida en grupo que produce
   venta continua y la superviso yo mismo
3. la innovacion vendria por el lado de acortar el plazo por un plan
   semanal de 12 semanas=3mes aumentar la comision del cobrador al 20%
   para un recupero mas rapido de la venta.
4. la futura innovacion vendria por el material vendido siempre en el
   rubro cortinas traido de bsas.
5. dispongo de 4 cobradores y de capital para hacerlo y de casi toda
   la zona sur para hacerlo con tranquilidad.
6. costo 25 cobr 18 vta 10 inc 10 tot 63 sneto 37
creo que el sistema es muy potable y similar al que tuve en el pasado
solo que habria que solucionar el tema de la captacion de promotores
para no tener el grupo vacio y no tener que llevar a la lesta.
pq casa por casa uno a veces no toca ni 4 o 5 clientes en 15 o 20
cortinas y a veces son de otros años o sea si uno vive del cxc no se
hace problema del cliente. 


* Febrero 2016
4/2 una oficina como la cristina y formar un grupo de 4 como tuve con
el deivi pero sin lesta y sin meli o sea sin nabos que salga de la
oficina y vamos en auto y vendemos 15cxd.

...excurso ¿todo tiempo pasado fue mejor?
ahora en la complejidad del momento actual pese a su aparente y
engañosa solvencia extraño o bien a la cabaña o la simpleza de los
esquemas deivi 2014 o grupo 2015 (no asi los sistemas del 2013 pq
fueron mas estresantes y se parecen a la actualidad) por lo demas
parece que todo sigue igual.

Si no fuera por los 3 ejes que en los ultimos dias se me desdibujan
(el push se me cae, la lect se me afloja y la invade el twiter y la
comida se complica o sea estoy amesetado) estoy igualito a antes o
peor. ¿Como salir de esto?...

...Tarde de relectura de la bitacora del campo y es como volver al
campo virtualmente por un tiempo y ver la diferencia que paso y
reflexionar en tiempo presente pq se plantea el mismo problema dos
años despues.

...Alerta ver que el tiempo pasa y uno basicamente esta igual. Ahi en
mayo de 2013 digo que me faltan 17 años para ahorrar para mi retiro y
han pasado casi tres años y no hice nada!!. Es mas casi estoy igual
con quizas mas problemas que antes y no hay solucion facil a la vista.

... Tema margen: veo que en 2013 se hablaba con naturalidad de 30/35%
de margen y ahora se da por sentado el margen en 40% ¿Donde esta el
error?.

...Y es verdad lo que lei ayer sobre que solo en los breves momentos
en los cuales mi mente esta limpia de elucubraciones (venganzas, iras,
preocupaciones, etc.) es altamente creativa, sino no. y caigo en el
marasmo y el resto del tiempo la fuerzo para nada y caigo en el
embotamiento, en el hastio, en la toxicidad (desparramada si estoy con
otros) y en la vuelta a comenzar repotenciando el circulo vicioso.

sobre lo que me llevo a la "solucion" 2015
el denso y agobiante cuaderno 2 esconde una crisis de produccion,
producida por la caida de venta y la necesidad de producir estando
mitad en la calle y mitad en la oficina. El vaiven es denso y cansador
del relato.
Y la solucion del nudo gordiano me acuerdo vino cuando leia una de las
revistas tipo LeMOnde en el marques que hablaba de subcontrataciones
agropecuarias y alli lo relacione con subcontratar a alguien para
llevar al lado y entrega y/o vender (aunque creo que habia hecho calle
un poco con 572 mientras Fede estaba en el escort el tema de llevar a
alguien era tema tabu) y fue luego se vera lo que por fin - la gran pm
q lo r1000p hizo que llegara a las 100 famosas lucas en ese mismo
julio, y luego vendiera bien en ago/set/oct, el resto es otra
historia.
[lo que se da por sentado hoy como normal en ese entonces no lo era y
fue ese clic, ese momento en que cayo la ficha de realizar la idea lo
que posibilito el cambio. Recuerdo haber intentado convencerlo al fede
antes de la sociedad para que el se pusiera un subcontratado para
obligarse a vender mas y no habia caso, era un tema tabu.]

[2016-02-15 lun] conectaron la luz en el local: recuperamos la luz
luego de haber expresado con claridad la necesidad de un local para
captar unas semanas antes. Lo hicimos. Esta vez la realidad fue menor
al miedo, tanto en el tramite como en el proceso de limpiar la mugre
que habia y tirar la basura que habia atras. Ahora falta ver como
organizamos un esquema de captacion y grupo.

...Creo en lineas generales por lo que veo que no debo engañarme por
lo visto
1. no parece muy facil o potable o esperanzador la formacion de un
   grupo de ventas a traves de aviso
2. vivir en cabaña potenciara la soledad, la desarticulacion y el cansancio
3. los unicos cambios verdaderos son los que se transforman en habitos
   y son aquellos que por ahi solucionan o le buscan la vuelta a las
   necesidades o anhelos que siempre se han tenido
4. no  parece que se pueda lograr avances en grandes metas si se
   mezclan al medio otros problemas que distraen o si no hay grandes
   metas.

... Cuando este en el campo quejandome de algun ruido, o de las
avionetas del aeroclub, o de alguna motosierra, o de un vecino
escuchando musica, recordar este transito incesante que no te deja
respirar ni mantener una conversacion a ninguna hora ¿Cuanto smog
estare respirando aca en Patricios??.




