* Mayo
** 12 arreglo con Sorpresa.
Congelar la deuda y compro-pago con descuentos. Esto facilita y
clarifica el futuro.
** los timbreros
Bernardo dice que los timbreros quedaran afuera pq el costo de mano de
obra cada vez sera mas alta.
** campo
hoy pienso que estar en el campo me dio la perspectiva y la claridad
para buscar la solucion.
Buscar el minimalismo y el estoicismo.
Tambien el campo tiene una mayor actividad fisica.
Hoy 18/5 conecte la salamandra y funciona!!
Necesitaria media sombra verde para Pucho!!
Cada cosa mal hecha sirve de experiencia hoy no pude prender la
salamandra. No basta con el tiraje hacen falta leñitas blandas.
El guisado lento sin carne terminado en la salamandra puede ser un
recurso exquisito.
Hoy sali a tomar aire de noche y las estrellas se caen, se ven las
constelaciones y el vientito mueve los eucaliptus y se sienten los
perros que ladran a lo lejos y la soledad absoluta surcada por las
motos y los autos anonimos y PUcho y los gatos jugando alrededor.
Ahora pienso que este campo es un gran acierto pq configura mi
"pasion" y da coherencia a mi vida. Todo concuerda, mi independencia
laboral, el anticapitalismo, vida suburbana, salud proactiva. No creo
que esto atente o produzca soledad, al contrario.

El anclaje inicial de alimento vitalizante es el licuado (c/leche
vegetal) mas el guisado natural mas kefir.

"Hoy Pucho respondio a los cascotazos y se escondio bajo la cama de
las chicas y despues estando afuera le ladro a un ovejero de la tapera
que se acercaba hasta la casilla del agua y lo saque cagando. Me fui a
cerrar la tranquera y se quedo en la cochera. 
Si no fuera por las moscas que estan molestas el ambiente esta
perfecto, la salamandra funciona a pleno, gaturro arriba de los
troncos para que Pucho no joda y el silencio brutal"
** negocio
hoy 24/5 fracaso el sistema de captacion de 900x40.
Y en general no hay sistema.
Debo barajar y dar de nuevo.
Barajo el 25/5 y veo que el problema es de expectativas.
Nunca funciono un sistema a porcentaje para captar. Siempre que tuve a
porcentaje fue pasado desde otro sistema.
Asimismo con sueldo fijo real no se puede estar y es al pedo total.
¿Se puede captar con virtual?
Hay que hacerlo bien. Creo que el error fue presentarlo desvinculado
del mes. Cuando digo ganas x pesos cada 40 ventas, en vez de tenes un
sueldo de x pesos por mes.

Perdi mucho con las "viejas" a comision. Las viejas 144 nacieron de
otra forma. Nacieron con un esquema de cobrador con basico y con
aporte de venta de promocion y luego con reventa en frio. O sea no
nacieron con aviso de porcentaje. (Como se intento en estas semanas)

El error fue no haber vuelto a lo que dio resultado siempre o sea al
promotor puro que venta casa x casa y luego hacer cobrar como sea.
* Junio
** 6/6 cumpleaños en soledad
Hoy cumplo años y estoy mas solo que Pucho. Pero mejor asi ya me
festejaron ayer el cumple.
Hoy pienso que todo esto es un error, incluso Pucho, luego sali afuera
y estaba en Romulana al 50 detras del gato de mierda y lo lleve a la
veterinaria a su vacuna.
Esta vida es la que elegi yo y no me arrepiento.
Hay dos elementos que son muy procampo, uno la filo y la otra la dieta
(y el ejercicio), al menos tendria que hacer plan un año.
** plan campo 1 año
aprovechar que estoy aca y que no puedo rescindir ya mismo para estar
un año y en ese año hacer todo el research y el cambio de habitos:
alimentario y demas. Tratar tambien de hacer la sintesis de todo y
despues ver.
** 8/6 el campo me pesa
me pesa el viaje y el transito, me pesa la carga de Pucho, el tener
que hacer tantas cosas. Pero como contraparte estoy mas activo, ando
mas en la calle, y me hago la cena.

Se pondra cada vez peor y cada vez veo mas incomodidad de la cabaña o
sea su precariedad. Y no salto lo peor todavia o sea el pasto.
PUCHO ES TOTALMENTE UN ELEFANTE DE SIAM QUE ME DIO IH.
No estoy ligado afectivamente pero me embola tener un perro que haya
que cuidar, no a nivel perro sino como articulo de valor.

Otra vez caigo en los mismos errores o sea venirme al campo pero
crearme obligaciones que molestan (perros y pollos en la Betty y
perros y gatos aca).
Hoy estoy decidido a solucionar el tema animales y no creo que siga en
el campo o al menos no en esta casa.
Pero si me mudara no tengo que ir al centro. Quiza lo queria era una
casa confortable y punto.
Mas que todo veo que pierdo tiempo.
¿Se pierde tiempo? ¿Como?
¿Como maneja el tiempo la gente?

Cuando el 6/5 dije "apurar extremos" o el 6/6 plan campo 1 año me
refiero a un CAMBIO REAL. p.e. en el tema alimentario realmente
cambiar a fondo y crear los habitos necesarios para cambiar como hago
con el licuado/leche vegetal.
Ahora quiero darle mucha pila a la filosofia con Feinmann para
realmente aprender.

Pucho esta mas activo, pasaban dos chiquitas y el las siguio pero no
se salio poner mediasombra urgente!!.
** plan de estudios
fundamentalmente investigar dos temas Filo y alimentos
Profundizar las lecturas.
1-filosofia
2-alimentacion
3-plan negocios
** negocio
Cuando sali despues del fracaso del aviso pense en liquidar todo y
poder vivir rehumilde haciendo algo que me guste... pero ¿que me
gusta? No se...

La vision que tengo es tener una orga especifica: vender cortinas (los
22 colores) en TODOS LADOS a presion en todos los barrios por medio de
un sistema de venta. No distraerme trayendo otras cosas ni nada y
siendo muy habil para cobrar.

Hoy ganar 30k netos ¿se lograra con un negocio? Capaz pero trabajando
toda la familia 10/12hs por dia y yo pienso hacerlo solo hasta las
16hs.
** 16/6 campo positivo
hoy en dia siento gran atraccion por el campo no importa el clima
siendo tambien los extremos lindos. Y por el silencio y
tranquilidad. Aunque no arranco todavia con ejercicio fisico. Pienso
que el punto de pivot es el cambio alimentario y como se logra ya con
lo organizado que estoy.
quiero tener habitos ya firmes de consumo para tener la seguridad que
no cambian mas.
** 21/6 tarde bucolica
una tarde bucolica perfecta, vine bajo la lluvia leve, prendi la
salamandra, me frite 4 empanadas en grasa y me acuesto una siesta a
leer con ventana abierta y el ruidito de la lluvia. Como esta frio
estos dias pienso que la actividad se reduce al minimo y hay mas
tiempo adentro.

En este momento el unico proyecto que tengo mas o menos es la
alimentacion incluso mas que campo. Al campo lo padezco y aguanto y
por ahi me gusta pero fuera de esto nada.
** 22/6 la noche mas larga
son las 18.40 y ya es de noche y cae una persistente lluvia sobre
Anizacate y se bajo la luz quedando la lampara rojiza dando una
penumbra sugestiva de puta madre. No creo que la luz alcance el resto
de la noche. Tengo un poco de humo adentro pero la salamandra esta a
full y estoy cocinando los porotos. Probe el kefir con otra azucar
para ver si esta vez sale.
* Julio
** 2/7
en 2010 cuando "estaba enfermo" posiblemente estaba somatizando las
dificultades vitales del negocio. La inopia en que cai, esa anemia
espiritual, ese vaciamiento de la praxis, y esas dificultades
alimentarias me hicieron caer en una falta de energia y debilidad
general y posiblemente un avance de la prolactina hizo el resto. 
Sino no se explica el bajon y la perdida de una oportunidad historica
para resurgir.
Nadie le da bola a la importancia de la alimentacion en los males que
padecemos.
** campo
al campo no hay que analizarlo mas. Lo que importa es como llevo mi
vida y como fortalezco mis ideas y valores. Aparte el campo es el dia
a dia y sabemos que va a ir cambiando el clima y el invierno es la
peor temporada. Posiblemente llegue a otro nivel de confort en el
futuro.
* Diciembre
El problema N°1 es el negocio. Y dentro del negocio es la venta. Para
vender hace falta captar y eso es lo que frena.
Al no tener idea clara en el 2011 se fue el tiempo. Idem en el pasado.
Hubo variaciones de un punto al otro. P.e. desde 514/516 (Sras onda
144s para vta y cobranza) visitando a clientes a grupo promo
supervisado con muchos problemas a SF, a SV y comision.
En articulos desde MT cortinas, a todo a MT manteles!!.
En plan desde semanal a mensual con seña y sin seña.
Permanencia de gente: CERO.
La mayoria solo trabajo un mes, con excepcion de 544 que trabajo 3
meses.
Dificultad para captar: alta. Termine en aviso de mujeres unicamente y
un par de meses SRAS con muy bajo nivel de exito.
La bocha seria hacer un plan de trabajo racional que intente cambiar
la inercia pero tampoco sea utopico. (Evaluar el nivel de experiencia
ya obtenido.)
Es notable la gran improvisacion que tuvimos siempre.
Muy comun hacer carpetas despues de los cursos a las apuradas, buscar
zonas las mañanas al salir la gente, legislar a posteriori,no tener
reglamento, tener un plan facil vulnerable, etc.
Balance de fin de año:
Fines de año, tiempo de balance desde siempre.Mas profundos cuando mas
mal me iba.
Y ahora no puede irme peor.

Cuando estoy solo necesito justificarme o sea cumplir objetivos/
tareas/ metas/ planes para que valga la pena estar solo o para que
pague el precio de romper el esquema general (lactico). La
contradiccion mayor es que al no profundizar el frikismo lo padezco
con dudas y creo remolinos de desasosiego, cuando a lo mejor dandome
permiso para ser yo mismo la cosa cambiaria.

-- [Muchas veces en mis escritos esta este tema o sea el darme permiso,
el encarar el xt, aunque sea por x tiempo, y ser a fondo asi freaky,
sin "ese" condicionante que creo que se refiere al mandato de tener
que ser normal, en otras partes a rehuirle a la soledad y no plantarle
cara, pq para ser xt hay que enfrentar la soledad y en otras partes
que el tiempo libre corro a gastarlo como todo el mundo lo gasta, o
sea en peliculas y demas para no pensar y no enfrentarse a sus miedos]

... Estoy resistiendo el impulso de decirme que emprenda un plan de
estudios o cosa similar.

Lo primero es ubicarse en que tipo de negocio uno esta. Como quiere
currar. Esto es tipo StringBill no es un curro legal.
Cuando crei que esto se podia hacer de forma normal ahi la
palme. Igual cuando no supe/pude sacar las ganancias y dejar de
comprar, para estar mas libre.

Un sistema debe ser RPCZ tener Reglamento, hoja de Promo, Contrato y
Zonas, antes de comenzar, y eso requiere pensarlo bien.

ih es un costumbrismo que se mata con el ejercicio de la soledad.

El ejercicio de la soledad: es la practica voluntaria  de enfrentar
con solvencia y hasta con gusto el terrorifico fin de semana, sin
temores y sin desasosiegos provenientes de la presion por ir. Sin
molestias por el que diran.

El problema de la cobranza:
la venta esmerila en 2/3meses salvo gente especial como 154 pero
tienen la verga de damocles por el culo.
Con propuestas mezquinas los vendedores duran 1 o 3 meses como mucho.
El PC deja de ser tal cuando
1. tenes cobradores puros que ganan mucho y te cubre mucha zona.
2. tenes venta para mantener esas zonas y a nivel general.
3. si tenes una propuesta para promotores que prenda y podes vender
   (cantidad de jornales por mes J=120 o mas)


...la tarde bastante soportable y luego tormenta electrica sin lluvia
hasta ahora.
El pajaro negro ataco la militud pq se pensaba en peligro.
Ahora se largo a llover y me tengo que refugiar en la galeria sur que
esta ocupada por la hermana de Gisel. La tormenta fue un pedo y quedo
todo igual, seco sin agua. Voy a regar...

...20-12-11 el mayor calor sufrido desde que estoy aca, los perros
estaban sin agua, tomaron agua cinco minutos seguidos, una tortura por
pasar un estupido dia en la casa...
** Teoria X-Treme
Significa un tiempo de x duracion donde busque cambios mas extremos
sin el continuo cuestionamiento que me hace dudar, ni la necesidad de
compartir o contar o predicar el asunto.
Cuestionamientos: comienzo yo mismo a cuestionarme en el sentido de
que me alejo aun mas de la teoria lactica o le doy la espalda (como si
estuviera a mi mano tenerla ya mismo).
Compartir:(contada) cuando cuento un pequeño avance, o la pequeña idea
o teoria o lo que sea la debilito y queda alli mismo reducida a algo
insignificante. Y aparte se debilita pq pasa a ser palabra y no
accion.
Poca profundizacion: como las horas de soledad se las trata de mitigar
o "pasar" con elementos similares al comun (video lectura compu) no se
profundiza en los aspectos del cambio. Porque un cambio real y extremo
es a largo plazo y con gran dosis de pensar.
Candidatos a entrar
*** alimentacion
la base de todo y el mas avanzado. Require mayor produccion de
elementos propios (huerta) y de elaborados (germinados, hierba,
chucrut, encurtidos). 
a su vez necesita un aprendizaje mayor de posibilidades de cocinar,
organizarse para preparar.
1. cuaderno de huerta
2. mejorar la cocina comprar un mueble mas grande y seguro
3. aprendizaje (semillas, germinacion etc.)
4. complementos como los del A15 (algarroba, maca, levadura, etc.)
5. control negativo o sea no consumir lo negativo lo que hace mal
*** negocio
en la medida de acer una organizacion cientifica de ventas, donde todo
este pensado y controlado en su detalle minimo. Y sea algo nuevo y
distinto a todo lo hecho hasta ahora.
*** ejercicio
un cambio de habitos en movimiento. Ej idea: antes de pensar en
imposibles ver como cambiar el estado fisico con una serie de
ejercicios controlados conocidos (Caivano, hombros, cuello, espalda)
luego agregar abd y pectorales y despues comprar algunos aparatos.
*** pensamiento
analisis, metodo, relectura, realizacion, cambio real en la forma de
procesar todo. Con mas dedicacion. Mayor cantidad de lecturas. Pero si
no hay cambio no sirve.
*** accion-conducta
evitar las conductas pateticas y ridiculas que muchas veces son las
que se apartan de lo asertivo.
*** estudio
no pudo dejar en una opcion xt de poner el estudio.
*** la base del xtreme es el ejercicio de la soledad
al quitar el vinculo simbioticoveo que puedo crecer en otras
dimensiones desmitificando lo que la union simbiotica representaba. O
sea comprension, empatia, intimidad. Al tenerlo "fijado" en ih y
volverse simbiotico, llegaba a un radio corto de desarrollo.
Siguiente paso: no necesitar exponer las ideas pq tambien chocamos con
ese limite.
Preguntarse ¿para que?








* Comentarios de transcripcion
[2019-07-23 mar]
veo que la experiencia de campo si bien es cierto que salpicada por
algunas expresiones bucolicas era negativa, fundamentalmente por las
molestias que me ocasionaba la atencion al perro, al menos los
primeros meses que se relatan aca, y que la principal baza de la
experiencia era la ALIMENTACION. y no mucho mas. Por eso que luego en
las argumentaciones nocampo al final se decide dejarlo. Porque manejar
dos horas por dia, con el riesgo que ello ocasiona y la perdida de
tiempo para terminar en lo mismo que aca.
Aca en el centro si quisiera podria tener el mejor menu alimenticio
natural que se me ocurriera, falta ponerse freeky en eso y decidirse a
gastar y hacer. 
** la gran persistencia en formar un equipo de ventas
me lo repetia todos los dias, formaba parte del dia a dia, probe y
descarte numerosos planes, que no transcribi y termine tirando a la
basura pq no vienen al caso, solo deje algunos detalles minimos, pero
si vemos la cifra de ventas de esos meses
| may-2011 | 21170 |
| jun-2011 | 13717 |
| jul-2011 | 36746 |
| ago-2011 | 39474 |
| set-2011 | 29697 |
| oct-2011 | 49942 |
| nov-2011 | 43837 |
la mayor virulencia planificadora la vi en junio el mes que toque
fondo, pero el semestre siguiente todo ese analisis dio su fruto pq se
le encontro la vuelta a un nivel de productividad que permitio ir para
adelant
