"los que quieran que el futuro sea diferente del pasado deben estudiar
el pasado" .-- Spinoza
"Si en todo oficio no se pone consciencia no se puede prosperar". --
Shakespeare


CAMPO II ETAPA
* tomo I 13-04-13 a 30-06-13
...14-04 luego vere que proyectos se consolidan y cuales quedan en la
nada y se olvidan.

...primera noche...sino tuviera un año de experiencia durmiendo aca
estaria cagadazo, pero todo ok.

...es muy loco volver a la misma cabaña pero mejor pq ya conozco como
son las cosas.

...el dia estuvo tramado por la preocupacion de reorganizar el negocio
(de tener que).

...no hay dpto o casa que se compare a esto aca. El viaje es lo de
menos, y la soledad tambien la tenemos alla.

...hoy cuando pensaba a la ida que podria cambiar el tjo para hacer lo
que me gustaria rapidamente volvi a la sensatez (por peaje), pq no voy
a ganar esto sentado en ofi por mas que crea que es alienante o
hartante.

...el nivel basico de vta para funcionar cubriendo costos seria 50k y
en Ago12 estaba 60k con plan simple y con faltante de vta.

...El concepto que tengo de la cabaña es que es un lugar propio para
vivir que yo elijo, el viaje no me interesa igual que el manejo. Sino
el vivir bien y mejorar los habitos alimenticios. Cabaña no es
contrario a tener buena pilcha sino le agrega fuerza y naturaleza.

...18-4 hay algunas rutinas que por ahora me hacen bien, p.e. hamaca
vespertina, el comer sano, comer fruta.
Tengo muchas cosas todavia por hacer tanto tareas como proyectos como
distracciones. Viene a ser tmb como pasar el tiempo pero de otra
forma. La idea es cambiar de habitos y buscar otro horizonte de vida
que no sea el encierro en cuatro paredes y la tele.
quiero 1gfpc.
la vida es filosofia y hay que saber vivir contento con lo que uno
tiene.

...sali hice una linea del bancal. Dos misterios: que no me picaron
los jejenes y que la tierra este tan mojada.

...23-04 mal mal de salud creo que una migraña (voy 3 Mig) 7am-14y
17hs.

...24-4 nuevamente a las 20hs en el sobre, ya un habito, jeje, pero no
siesta y actividad a la tarde.

...El campo queda en un contexto bien organizado como una eleccion por
la salud, por el movimiento y por el aire puro o al menos mas puro que
en la ciudad. Una eleccion de estado minimalista y filosofica. Pero
habria que buscar salida a la presion que se genere para no caer en
decepcion y contraciclo.

... las rutinas son importantes pq son las que marcan lo que sentis
respecto a como vivis.

...sabado 27-04-13
seria un dia arduo, de gran prueba si no hubiera tenido a la mañana el
condimento del wapp.(1er wpp de Vdez)

...la gran falacia es visualizar variedad en el centro (ojo que tmb
hay en ag) y creer (lo creia antes, ya no) que el centro te daba la
posibilidad de obtener alguna cuota de ese mercado. 
pero la realidad es que no, parte pq los musculos envueltos no estan
desarrollados (y una vez desarrollados se podrian ejercer en ag si
quisiera), y parte pq la vida en la ciudad me quita el sentirme bien
que es fundamental para encarar todo con vigor y salud.

...hoy tengo de nuevo una migraña de 3 a pesar de haber estado en casa
y me siento mal como mareado y tomo consciencia que estoy con
semblante viejo muy demacrado y poco nivel de fuerza realista.

...olvidarme de todo pq quiero una gfpc no una palomita de la virgen.

...hoy venia para aca y venia mal pq estaba embroncado pq estoy solo
pq sali de la casa en un momento critico y despues el FEde termino
yendose y yo quede offside por el cambio.
y decia bueno ya estoy debo ahora apechugar ya lograre equilibrarme.
...Creo que la ataraxia, la alimentacion sana, el movimiento, son
proyectos basicos pero pueden caer en el vacio del nihilismo. Por eso
la gente se pierde en lo cotidieana en lo superficial y en querer
poseer cosas.

...que el bajon no te impida apreciar esto o sea la naturaleza.
En este sentido el libro de Robin (sobre los venenos) pateo en contra
justo en un momento bajon pq cai en una desazon planetaria ya no
sistemica, al estilo Charton Heston en planeta de los simios cuando
vio restos de la estatua de la libertad como desazon final de que todo
esta perdido. 

... Entonces sumado a la desazon de no ver el entorno, de estar muerto
ante lo intelectual (anoche inexplicablemente me dormi literalmente a
las 20hs y por 13hs) y de la imposibilidad de permanecer hasta cierta
hora hacen un coctail malsano. acuesto de tarde, me duermo rapido, me
levanto tarde, me duele la espalda, hago poco, decepciono ante falta
de fuerza y proyectos.

...Como parte del periodo de desazon esta el miedo al futuro por la
total indefension siendo que todavia tengo gente a cargo por diez años
mas.
pero lo bueno es que al venir aca plantie un cambio de vida, hacia una
postura mas sana, filosofica y minimalista de la vida, o sea lejos del
exito mundano caracterizado en 2008 y que volvio al menos en relato
estos ultimos seis meses.
Como se manifiesta el cambio de actitud?
1. la idea es trabajar en forma continua para vivir sencillamente y
   asegurar el futuro retiro
2. vida sencilla es conservar el auto o cambiar por una chata de
   similar valor - pasar a considerar el auto como un medio de tte no
   como ninguna otra cosa. No derroches en gastos de ningun tipo
   incluidos gastos de ropa.
3. vida sana. Como prioridad de vida y acomodamiento de valores
   incluyendo la ataraxia y la filosofia pq no hay forma de vivir o
   soportar la vida.
4. como objetivo secundario una gfpc no hay incompatibilidad con el
   tipo de vida planteado.
Esta actitud cauta puede llevar a un sistema sustentable de unos 10
años vista. No olvidar que tecnicamente me quedan 17 años para el
retiro.
Si dedicara estos 17 años a una sola cosa la cosas seria diferente,
p.e. en focalizar, repensar, y generar una teoria util que sirva a los
propositos utiles.
MAYORMENTE ESTA VIDA QUE LLEVO TIENE MUCHO DE TIEMPO LIBRE Y ESO
CUESTA ADMINISTRARLO.

...en estos dias de exceso de tiempo libre y en el campo solo son
recurrentes los malos recuerdos, los pensamientos nefastos.
El otro dia escuche en la radio que el ser humano recuerda a
diferencia de otras especies y eso le juega en contra cuando o porque
los malos recuerdos son los que predominan.

... El hecho es que yo aca o alla o en un dpto me siento mal y estoy
igual o sea no genero soluciones.

...Puede ser que estoy procesando el embole de que Fede se fue y
cambio todo, pq podria estar tranqui alla con la flia, ojo no me
engaño queria irme pero ante el riesgo del trabajo preferiria no tener
el costo extra y eso me mata, me emperne en un costo al pedo y ahora
tengo que cortar clavos la p.m.

... 36 migrales en 20 dias!!!
del 14/4 al 4/5 posibles causas:
1. alto estres!!
2. cambio de habitos de sueño, dormir mucho, muchas horas acostado.
3. cambio alimentario
4. agua!!
5. enalapril

...8-5-13 hoy me cuestiono todo no solo el campo sino tambien toda mi
vida. Pero pq tengo que vivir esta vida rara y dura?.

...SOLUCION NEGOCIO EXTREMA
entrego yo las ventas. traigo toda la marcaderia al campo y/o marques,
ahi saco el tema mas importante dejo solo un minimo simbolico para
cobradores.

...Esto es energizante y generador de alto nivel de resultado y
trabajo. Y me acerca muchisimo al LMM y LMMplus 1 y 2 (clientes/calle)
con movilidad y cubrimiento de costo o sea olvidar inmovilidad.
Sacarse la distancia y la inmovilidad dyeriana, con movimiento,
trabajo, normalidad, relacion, optimismo.
Es solo reparto no tiene que haber desasosiego.

...Como correlato a un problema que es las consecuencias reales de los
juicios laborales caigo en la cuenta que no puedo exponer mercaderia
alla y luego de la crisis de un minuto caigo en la cuenta de que puedo
repartir yo y alli se abre todo un panorama general muy importante:
1. no solo aseguro el local - saco mercaderias
2. sino potencio la promocion pudiendo generar 100k o mas yo solo o
   sea sin depender del Fede.

Sigue la valoracion de la independencia, mi sitio y cosas pq he sido
muy ninguneado y estos meses aguante muchas cosas.

...Resumen
1. Estuve sometido a un gran estres aunque no lo haya aceptado, el
   cambio de casa, el cambio de tjo.
2. considero superado el primer bajon de vivir aca, respecto a los
   proyectos me los replanteo
3. me corrijo un poco de posturas apocalipticas extremas, yendo a un
   punto intermedio mas realista. Debo luchar contra el apocaliptismo
   que me lleva a la depresion
4. el 8/5 nacio una nueva idea de negocio, la mejor de los ultimos
   años.
5. puede que trabaje 8hs pero gano 40k
6. agrego LMM anexo en avisos idem
7. paso papeles en cabaña mejor todavia agrega mas seguridad - compu
   vacia, pendrive 

... veo que el estado de salud en general es bastante peor que hace
dos años.

...es obvio que sufri un estres impresionante desde el llamado, el
proceso ida y vuelta, el quedarme solo, en el medio el cambio de casa,
quede en el medio entre el susto de los mayores costos y la desazon de
la futilidad de caer de nuevo en un 2011. Luego el dia de la
notificacion y previo el estres de juntarle la plata al Fede. Total
estres afecto a la somatoforme y al malestar.

...Hay un cambio de paradigma que se manifiesta en la vestimenta y en
el rol.
en los 90 era el empresario, gerente, usaba traje etc. en el 04 en
adelante era el formal dentro del sport pero asumia ciertas
convenciones y transmitia ciertas cuestiones (Ej transmitir ciertos
usos culturales y facetas personales como acercamiento a la gente como
donde vivis. etc.)
y por ultimo en los tiempos del 2008 asumia un rol equis desde el que
no me pude mover.
Ahora hubo una rotura de esquema. Que se plasma en salir a la
calle. Hay incluso una resistencia de parte de la familia (en especial
el fede) como que estoy fuera de posicion.

...27-05-13 (a 43 dias)
No se porque extraña razon termine volviendo al mismo campo que antes.

...en el ultimo tiempo el eje de la "fortaleza" se movio de la
experiencia campo a la "experiencia" laboral, tanto el extasis de la
calle (el poder hacer una funcion sin desasosiego conquistando el
mayor miedo) y eso hace que los proyectos hayan quedado al margen o se
hayan diluido mucho.

...que lleven a una discrecion o a un cepo comunicativo (o a la
apertura de otros interlocutores y en otros terminos - eje Romi, mi
vieja y la discrecion total frente a ih, fede y los empleados)
¿Cuanto hace que no vivo la sensacion de estar generando un sistema
propio sin necesidad de contar ni rendir cuentas? ¿Ni de estar con la
sensacion de deberle algo a alguien?

La realidad es que ya no quiero transferir lo instranferible ni
delegar lo que puedo hacer yo. Ni tampoco quiero contar lo que a nadie
interesa como si yo me alimentara del acto de compartir y por lo tanto
necesitara contar.
Uno esta escencialmente solo y lo que vive o siente como vivencia
cultural es intransferible principalmente lo exultante o cultural.

...el clima , los colores, sonido, viento, pajaros remanentes,
actividad humana difusa, molienda de piedras, autos etc crean un
paisaje de un momento magico unico e irrepetible muy lindo y
energizante pq no hace frio y esta ventoso y seminublado de tierra y
es otoño pleno, todo se esta secando...

...1-6-13 resumen mensual
1. tremenda experiencia, cambio todo el panorama laboral. Es cierto
   eso de que enfrentando  el mayor miedo se obtiene la mayor fuerza.
2. reacomodo brutal del negocio en especial a la relacion de fuerzas
   (con promos, con cobradores, con Fede, con el sistema).
3. venta entregada por mi totalmente. Es andar en la calle, pero veo
   todo, soy ahora el panoptico y al menos puedo dirigir la operatoria
   en general
4. mas profesionalismo con los clientes atendiendo cambios y
   devoluciones asertivamente.
5. menor tiempo fijo en oficina
6. pasado papeles on pendrive!!! brutal
7. oficina liberada de papeles y mercaderias sin riesgo de embargos
8. sin estress.

...no preocuparse por la vida en el campo ya que los ingresos
permitiran arreglos que tendrian que aliviar la experiencia, sino
directamente el 30/9 rescindimos y punto.

...Tema de reflexion: Pq voy alla? ¿que me lleva a insistir con ih en
su variante de odio o que me lleva a aceptar sucedaneos?
ok esta el temor a la soledad, el plantearme qeu ele finde sera largo
y aburrido o la comodidad de que otro haga de comer o como dice arriba
el sucedaneo, el conformarse con migajas de una relacion adulta.
Uno de los temas recurrentes para atras es la pregunta ¿en que se
pasaron tantos años? lo cual es una pregunta falaz. Porque obviamente
vivimos dia por dia (no estuve en un coma inconsciente) entonces el
tema es ¿como vivi? o sea cual fue la forma de organzizar mi tiempo,
mi jornada, mis dias y obviamente ellos se articularon en familia con
ih, no importa donde estuve. Con cosas que me gustan y otras que odio,
y otras que odio pero que me gustan (?) sic.

Como hay falta de reflexion de ahi provienen las decisiones
equivocadas y la falta de objetivos.

El sistema de salir-yo-a-repartir siempre estuvo solo que yo no lo
veia, o no lo veia viable o no me animaba. Paralelamente puede haber
esquemas ocultos hoy que solucionen mi vida personal y simplemente
estan ahi. 

...el finde, famoso y temido finde. pq el dia de semana esta todo ok
pero el finde pudre todo y a la vez hay un millon de cosas que no se
hacen pq no hay tiempo.

...8-6-13 hable con Fede y le gusto un plan unipersonal puro de minimo
25k con esperanza a mas. Liceo/Remedios/Boulevares/Fragueiro.

...Sindrome de otoño: sensacion de incomodidad fisica ocasionada por
el frio, la suciedad ambiente, la sequedad de la piel etc. Aca se
magnifica por la sequedad de las manos, la suciedad del auto, la
tierra por todos lados. Pero ese sindrome me pasa en todos lados no
solo aca y aca se morigera con la fagina.

...No entiendo mi completa ignorancia politica de los ultimos 10
años. Crego que haber ignorado totalmente un proceso historico como el
que hubo hasta hace poco tiempo es muy llamativo. Y comparte la
sensacion que tengo de no "haber vivido" o haber estado en un proceso
de evasion de la realidad. O sea de un "pasar" el tiempo
brutal. ¿Donde se fue el tiempo?
El tiempo intelectual tuvo sus momentos
1. transformacion de conocimientos (tcl/sqlite/linux/arch/etc 2009
   betty mysql/sqlite/python 2010 vim/tcl/tk arch 2011...2012 paso a
   otro nivel con itcl y base datos y con arch xmonad)
2. desde la filosofia y el barro de la historia con JPF avance otro
   proceso que en filosofia habia sido erratico entre el 2003 y el
   2009

Curioso es que el 2009 fue un año bisagra en los conocimientos
generales con JPF y con linux/sqlite/python aunque en ese año no fui
conciente del punto de inflexion que se estaba dando en ese momento.

Obviamente hay un sufrir descarnado en todo el periodo 2003/2010 que
es el doloroso proceso de separacion. La ruptura con la familia y el
dolor que me causo la soledad y el no poder manejarla y el no poder
hallar un sistema viable para resociabilizar fuera del trabajo y fuera
de la familia.
Aun hoy siento que no puedo encontrar una forma de vivir feliz
solo. Porque me siento triste o aterrado frente a la disolucion del
silencio absoluto y el desgarro incapaz de dar solucion al problema
parte por no poder planificarlo-quererlo y parte por no poder hacerlo.

Hoy quizas el recurso mas valioso sea este cuaderno y tenga que buscar
en el las repuestas (que es otra forma de decir que buscarlas en mi
mismo).
Otro gran tema que nace en 2010 fue el alimentario que evoluciono y se
quedo.

...tuve los siguientes procesos campo-trabajo
1. Utopico: 14-4 - se va!! que cagada. pensaba gozar del tiempo libre
   sin grandes preocupaciones con posibilidades de tener para gastar y
   mejorar mi salud,etc.
2. Temor: x-4 - 8-5: efecto pobreza, bronca por haber alquilado siendo
   que si me quedaba alla eran menos los gastos.
3. recupero autonomia: 8-5 --> descubriendo una actividad directa que
   me genera mas dominio de situacion pero la vuelta del Fede la
   empaña.
4. aseguro autonomia 10-6 --> habiendo hablado con Fede que no unamos todo
5. autarquia 25-6 con el pago total de la deuda al fede. La idea del
   fede hasta ayer a las 19hs era una comunion de todo no una
   separatividad.

...Ojo que tambien no conocer las calles en los circuitos tan
transitados es parte del proceso, muchas "vueltas" me como por no
conocer bien los barrios.

...spot de crisis existenciales, cuando estoy en medio de la
faena. Pensando yo tendria que estar en ...(pero no se donde, pq la
referencia a la oficina se cayo.)

...14-06-13 hoy doy por terminada mi experiencia con ARCH linux. Hasta
otra oportunidad. Se han vuelto demasiado freaky para mi gusto. Me voy
a otra cosa. Es un desastre cada seis meses, no una
actualizacion. Ademas que voy yendo hacia los contenidos y no las
formas, asi que chau arch, y casi chau linux.

...tengo un efecto pobreza o de falta de entusiasmo inmerecido o
injustificado pq hay esperanza de lograr el objetivo de venta, de
formar grupo, de cobrar y no hay problemas de repago de la deuda, pero
caigo en la inconducencia de la nada. A pesar de que con filosofia de
campo vengo viendo cuales son los problemas.

Soy toxico? Soy pesado? soy denso? mayormente soy denso cuando pienso
o hago un proceso decisorio, sopesador, deliberativo en publico,
interactivo, ahi soy insano. el cuaderno no se queja y sirve
mejor. debo despejar o plantear las dudas solo. no molestar a los
otros en el proceso.

...Le Monde te abre los ojos a una realidad mundial y te da una vision
profesional de temas ignorados completamente... Vuelvo a la idea de
que estoy atrasado en mis lecturas.

...19-06- hoy fue muy duro volver a la cabaña de noche, totalmente
solo, sabiendo que no me esperaba nadie, luego de un dia de trabajo
duro sin ninguna alegria fuera del trabajo que compense.

...Resumen de la problematica actual
1. problemas de salud que "creo" posible corregir (pero no lo hago)
   como HT, acidez, espalda, falta de estado.
2. dependencia situacional dia a dia con ih a pesar del rechazo.
3. escasos resultados economicos.

...La bocha es ser independiente o ser un pelele.
si no soy independiente a mi edad mejor matarse.
yo articule mi vida alrededor de ih como un satelite que gira. Mis
separaciones, mis dptos, eran un permiso precario de salida por un
tiempo determinado segun pautas establecidas que no se podian obviar y
ella mandaba sopena del exilio definitivo al otro lado del rio estigio
en la zona tenebrosa del destierro.
¿que es estar desterrado? ¿que es esa sensacion insoportable de no
tener a nada y a nadie del otro lado? esa sensacion de soledad total.
yo me preocupaba por la felicidad de los otros primero de mi vieja y
mis hermanos cuando quedamos solos y luego por ih y las chicas, por
eso cuando me vine y quedaba FEde "safaba" pq era necesario safar. 
obvio que yo voy y ella ve que es al reves que soy yo el que necesito
ir alla. y es verdad hubo fines de semana que no me anime a atravesar,
ni siquiera a pensar en el tema.
aunque pensara someramente que una situacion de solo total luego de
todas las cosas por hacer pendientes me iba a levantar e iba a empezar
de nuevo. como lo hice con el reparto luego que el Fede se fue y me
dejo solo. primero me parecio duro comenzar de nuevo pero luego
renacio la fe en la independencia y me siento mas solido en ese
sentido.

... se que soy toxico para ih y las chicas y mi vieja y de Fede. Soy
un tipo toxico lamentablemente.
pq no proceso mis frustraciones asertivamente y las reparto via
conversacion alrededor.

La simbiosis con ih es la necesidad de aferrarse a la comunidad con
alguien para hacer mas soportable la vida. Es la "Ilusion" de ser
entendido, comprendido, conocido por alguien. Mayormente la simbiosis
es toxica y es un defecto como muchos que puede haber.

Tengamos en cuenta que los eventos que se describen en este cuaderno
transcurren con una alta toma de migral, aproximadamaente 50 migral
por mes. frecuentisimos dias de dos, dias de tres una o dos veces por
semana, 14/4 al 30/4 29 Migrales Mayo 48 migrales junio 51 migrales
y aparentemente una gran preocupacion por la HT, con tomas de la
tension y su anotacion durante todo el periodo casi todos los dias, lo
que evidencia una obsesion, y tomando propanolol y previo a el otro
antihipertensivo., muy frecuentes tensiones de 14/14.5.

merece expresar el debil intento pero unico al fin y al cabo de
caminata que fue ese mes con 5 sesiones que completaron 200 minutos
entre el 20 y el 30 de junio.

un periodo muy tramado por el deseo de marcar mi independencia, de
dejar de ir (NOIR), de dejar de depender, de haber encontrado en el
coraje del reparto el camino para independizarme y no querer volver a
depender del Fede de nuevo.
Por momentos parece que hubo un deseo de venganza muy grande que duro
demasiado tiempo (casi dos años), pero que permitio lograr una
independencia en ese momento.
* tomo II 30-06-13 a 30-08-13

...hoy hago una pausa en cualquier tipo de requerimiento pq estoy
"burned". Hoy dia de relax, estar tirado al pedo y haciendo lo que me
gusta (leer, estar en la hamaca, escribir, prender el fuego, ver
MadMen o Roma, etc.)

...habria que analizar si realmente vivo sin relacion o sea solo
(bancandome esa vida) o si la relacion oficial es ih aunque vivamos en
casas separadas. Al no haber entrado terceros en ambas partes la
relacion sigue (analizarlo a la luz de ZB Amor Liquido) "es la ilusion
de ser entendido, comprendido y conocido por alguien"

...se nota la experiencia acumulada: van casi 200 entregas...

...hoy no tengo ganas de hacer nada, pero no reniego ni de la cabaña,
ni de la soledad ni del campo ni del clima ni de la vida. Al
contrario.

...7-7-13 ¿por que tarde tanto en volver a la calle?
tendria que haber vuelto en 2005 en vez de encanutarme en la
oficina. Y me hubiera evitado todos los dolores de cabeza y quien sabe
me hubiera ido mejor.
Todos los años perdidos y los problemas sufridos que todavia me
alcanzan ni hablar de la oportunidad perdida, todo por evitar la
calle.
No fue casual, la calle antes se me presentaba como un lugar hostil
para mi, ahora es al reves, me encuentro muy a gusto en la calle, me
gusta y veo que se puede hacer guita o al menos mas que desde la
oficina y con mas libertad. 
Aunque todavia no se nota esa libertad pq no estoy organizado al 100%
bajo ese paradigma libre.

...Teoria de la mierda:
la mierda mental invade la mente con pensamientos nocivos. En ese
estado no se crea, no se ocurren ideas positivas y se generan
problemas, cosas malas, maldades, bajezas, lo que conocemos como
venganzas, iras, depresion, desasosiego.
Normalmente son cosas que deberian ser olvidadas pero permanecen y
vuelven a molestar.
cuando la mente esta libre de mierda piensa y todo es mas positivo y
surgen cosas asombrosas. 
a su vez el estado creativo mantiene la mierda a raya.

...No olvidar que tengo que hacer multiples tareas:
1. atender clientes, seven, telefono
2. atender proveedor, banco
3. pagar cuentas
4. atender cobradores
o sea tengo poco tiempo o sea un esquema de alta venta en poco tiempo
me conviene.

...9/7/13 estoy muy embolado con todo. en especial conmigo mismo y
esta cabaña de mierda. O no?
Hoy declaro el fin de la ignominia. Bañarse aca es bochornoso, es un
asco. Como lavar el auto.
Lo del auto es un defecto mio: 1. pienso que me lo van a
estropear 2. me da fiaca llevarlo o ... 3. no quiero gastar (atavico
pero real) [hoy sufri como un pelotudo prendiendo fuego sin alcohol
como lo hago siempre y lo hago bien, todo porque? pq el Sr no compro
un alcohol puro en el Disco pq costaba 20 mangos (en realidad
16!!!!) No se puede creer] 

...tratando de dejar todas las elucubraciones a nivel cuaderno pq asi
no tengo emacho en cambiar de hipotesis.

...lo bueno es que con YOREPARTO di con un esquema de negocio que
puede vender 100/150k al 40% sin necesidad de tener la mercaderia en
el local, pero necesitas promotoras o sea aviso.

...Cuando en 2010 decidi curarme la migraña y buscar OTRO Negocio, no
lo encontre pero este esta bueno pq vendemos ganamos y arriesgamos
real poco (y puede ser considerado otro negocio distinto al que hacia
en el 2010)

...parte tambien esta especie de autocierre de comidas o sea falta de
ganas de cocinarme o tener variedad adecuada para una buena nutricion
aparte del K/A15/AV/SEM
y lo que pensaba esta mañana con la falta que hace el ejercicio para
desentumeserse del todo pq no puede ser que tenga dificultad para
vestirme.

...14/7 creo que el problema mayor es la crisis existencial. Que me
coloca en una situacion de eterna disputa, eterna disquisicion y
termino "pasando el tiempo" muchas veces con reiteraciones continuas o
diversiones idiotizantes.
1. la CE continua no me deja ejecutar un plan de accion (que a su vez
   de resultados reales objetivos y construya los cambios, rutinas y
   habitos) que hagan el presente transformador que cambie el futuro.
2. esa CE se articula sobre una virtual pelea con el tiempo que se
   escapa pero a la vez no se puede retener. el "plan de salud" con
   sus contradicciones brutales (inexistencia en la practica) de
   venirse aca para conjurar el deterioro fisico. Pero sigue siendo CE
   por eso cuando me increpan mis allegados que me quieren y ven que
   estando solo la paso mal no tengo solidez en la repuesta.
3. Por eso cuando escucho al chavon de tortuga el sabado sobre "cambio
   de vida" y si realmente queres cambiar comparto en un 100% pero
   tengo momentos de crisis como los que digo "me pesa el campo" o que
   hago aca y pretendo echarle la culpa de manejar 10hs por semana
   para vivir aca.
4. ayer me pregunte ¿por que no me cocino? y vi una receta y la hice
   (poroto negro/cebada MB Mfacil) algo curioso, ver la receta escrita
   es muy facil en esos momentos.
5. no puede ser que el negocio ocupe TODO el tiempo, todos nuestros
   horizontes hasta el punto de no haberme dejado ningun proyecto
   viable paralelo.


...Tips para armar un plan de accion personal
1. carpeta A4 para auxilio cuadernos (papeles varios, impresiones,
   planillas, etc, resumenes, calculos graficos CM!!)
2. hacer algo con la comida. recetas en A4 con ingredientes abajo
   lista en A4 de comidas hechas y comidas registro para ver el
   patetismo.
3. ejercicio idem en A4 para ver la ignominia
4. registros en A4 de migral y demas
5. registros en A4 de lecturas y peliculas
6. agresivo plan lectura / CM / estudio articulado en libros.


...15/7/13 hoy lleve el auto a cerro y camine 8km por primera vez en
la vida.

...Tarde de cabaña:
tuve que salir para describir o intentar describir lo que es esta
tarde de invierno con frio y algo de viento o brisa y un sol piadoso y
calido y un silencio matizado por los pajaros, la avioneta y el
transito y el olor a leña de la salamandra que acabo de prender y la
vista para todos lados de ese paisaje seco invernal que no por eso es
menos lindo, muy bueno, con la cabaña acomodada, fria pero prendi la
sala, funcional y cosas para hacer muchas.

...un dia de omnibus tambien te hace valorar el auto y todo lo que uno
tiene.

...no negar que el problema judicial sigue su curso y un esquema de
uso intensivo de oficina es problematico en el Local 4 y
caro/engorroso en dpto anexo. [pasaron 6 años y no paso nada relevante
como para haber seguido con uso intensivo de esa oficina.]

...22-07-13 hoy hace tanto frio que creo voy a dormir en el futon con
el fuego prendido toda la noche, capaz que haga -10°C esta noche y
tengo miedo de morir congelado.
A la mañana -8°C.

...23-07-13 debo instalar windows seven y ponerme a aprender a
programar en android, linux ya fue, la bocha es lograr un F13 en
android.

...29-07-13 hoy caigo en la cuenta qeu mi vida actual no tiene
sentido. Estoy solo, dolorosamente solo y todos mis hobbies solo tapan
por momentos la tristeza de sentirse mal y de estar envejeciendo
solo. yo estoy aca porque me gusta el lugar y me siento cada vez peor,
sin margen proyecto ni nada. Solo la claridad de pensamiento que me da
el campo pero ante la cruel realidad de la lejania y el paso del
tiempo.
la salud se deteriora pq no le damos bola, pq perdi habitos sanos y me
desorganice.

...31-07-13 tendria que estar feliz por haber llegado a 100k, me
emocione en B° Rosedal cuando llegue a 100k hoy pero nadie me felicito
el logro.

...4/08/13 ayer corte todo vinculo con el Fede y ahora solo me queda
seguir adelante. Con poco capital en cierta forma pero creo que
probable.

...veo que me descuido fisicamente
1. no voy al dentista
2. no como sano
3. no hago ejercicio (en especial espalda)

...la frustracion de haber fracasado y estar pobre, viejo y enfermo,
sin casa, sin muebles, sin trabajo ni mujer y eso sin tener vicios
mayores y es mas siendo un buen tipo me da por las pelotas pq no
merezco estar asi. no tendria que estar asi y van dos ejemplos
1. ih dice llorando que la mai y la elsa tienen razon que va a
   quedarse al final conmigo y eso no quiere. ¿quien carajo se cree
   esta pelotuda? yo deje la vida entera para la familia, siempre
   quise hacer lo correcto y esta pelotuda llora pq el destino la
   dejara a mi lado, que tengo yo lepra? que se vaya a la mierda YO NO
   quiero estar con ella
2. el Fede se va a la casa y me manda un wassap mangando una
   mesa. ¿por que no se va al carajo? me saco mas de la mitad de lo
   mio en los ultimos 7 años por no decir siempre, me arruino, me hizo
   perder tiempo y la tranquilidad, no me permitio ser equitativo con
   las hijas y ahora quiere una mesa, un patadon en el culo le voy a
   dar. que se vaya a la mierda y que no joda mas.

No se donde voy a vivir en el futuro, no se ni creo que cambie mucho
mi percepcion de vida. Puede ser una casa, un dpto, o dpto-cabaña o la
cabaña. No se. Ya estoy aca y tengo que resolverme en funcion de lo
que es, no de lo que podria haber sido.

...hoy debo aferrarme a crear esa alternativa no local-dependiente,
sino mas bien generar venta real hoy. El local obviamente no sirvio
para generar venta pq no ayudo a poner 100k de vta. Lo hice en julio
saliendo a la calle y todavia perdiendo tiempo de oficina.

...no hay que olvidar que la Notificacion del mes pasado altero todo
el animo de salida del local, y eso influyo indirectamente en el
manejo del grupo. Mas alla que ahora con el esquema de encuentro en
calle es al pedo arriesgarse con gente cotideana por la mañana en la
oficina.

...hoy tengo 3200 clientes visitables (y mas para atras) por eso no
necesito la promocion por un buen tiempo. Pero si la necesitara puedo
poner 4 o 5 chicos como en el 2002 encontrados en calle dia a dia con
la oficina atendida de tarde [13-08-13]

... es durisimo ver Funes un dia como hoy y estar vacio total. No da
mas esto (la situacion, no la cabaña.)

...15-08 veo que cuando me voy alla no descanso, al reves, duermo mal
y todo es feo, no se pq voy. Y luego se hace despelotada mi vida aca.
pq el quilombo viene por no venir todos los dias aca, sino me hago de
comer aca(la paradoja de la alimentacion sana que no hay alla).
al no estar todos los dias aca NO RECARGO COMO DEBO ACA y se me
desacomoda la vida aca y caigo en estres por agotamiento.

No es tan lineal que la culpa la tiene la cabaña. La culpa la tiene ir
alla y sentirme vacio por ir alla. Sentirme sin esperanzas en irme
alla, sentir que no siento nada. 

...Lo que no puedo hacer es que el tiempo vivido solo me sirva para
algo, que pueda lograr un cambio o mejora o una vivencia que haga que
valga la pena.

...Hoy me hice un par de preguntas esteparias ¿Cuando se pudrio todo?
¿Cuando se me fue la juventud? ¿Cuando se fue todo al carajo? Cuando
me agote en una busqueda vana por nada?.

...25-08 domingo ayer fue un dia patetico.
tengo problemas reales e imaginarios.
reales son los problemas de salud, de trabajo, de soledad e
imaginarios todo lo demas.
Y los problemas reales tienen causas concretas, mayormente desidia o
errores.
p.e. problema de salud: tengo 50 pirulos (fact) y no voy al medico ni
al dentista y eso me llevara al caño. pienso que una vida sana me
salvara y termino no llevandola - ahora pq es invierno pero la excusa
es todo el año-, y el deterioro se ve mes a mes, año a año. El
anquilosamiento es notable.
el dolor de cabeza es un problema y puede haber influido en el ataque
antitodo que tuve.

...Ayer (27/08/13) termine de hacer la famosa RECONVERSION EXTREMA del
negocio que le dije esa vez a 75-695: salgo yo a la calle a vender y a
cobrar y los echo a todos a la mierda.

...Esa increible reconversion vino por un fact que es - mas alla de
los problemas de oficina - la improductividad de la gente frente a la
posibilidad de producir visitando nosotros a la gente.

...incluso deberia poner un ojo al sistema de SMS instantaneo pq
podria poner aviso para ese sistema a % y desde calle buscando alguien
apto que quiera sabiendo que hacen falta solo un par para vender bien.
y que la tecnologia espectacular que es el SMS pueda ser aprovechada
para un sistema supereficiente.

...la bocha hoy es el SMS y la venta ZONAL E INMEDIATA NO MAS ENTREGAR
VTA.
LA BOCHA ES SMS NO EL LISTADO

...ya con la xp del 75 hoy hasta da pie para traer a la 154 a hacer
esto pq la bocha da de 10 a 14.45hs entregar 10k es muy groso!!!.

...cierro tranquera, noche despejada y calida y siento qeu es tremenda
pelotudez estar solo pq al menos creo que comeria algo y charlaria
algo con alguien, ademas de buscar a alguien con quien compartir la
vida.
Ese seguro de qeu cuando estaba con ih podia soportar cualquier cosa o
no tener miedo a nada se me fue y quedo la costumbre el habito.

...ESTE ES EL SISTEMA DEL 2002 recupero con un parentesis de 10 putos
años hacer en 4horas 10k por dia.

...la bocha estaria entregar yo solo ... que manden al celu de ih y
ella verifique tanto Romitex como seven.

... Vendedores: 723-619 -- Seniors
                703-697 -- Juniors
                615-572 -- rompe pelotas
                154        posibles
[jaja ver que 572 estaba dentro de las rompepelotas]




** Comentarios a la transcripcion
*** mucho dia a dia del negocio
este cuaderno tiene mucho dia a dia del negocio. Hasta el
agobio. incluso da gracia que en elucubraciones mas o menos teoricas
como la de la CE en el punto 5 hable de la presencia global del
negocio y luego el punto 6,7,8,9 sean puntos del dia a dia del
negocio.
Obviamente en una relectura a seis años como esta hecha en setiembre
del 2019 todo ese dia a dia ya carece de importancia salvo para hacer
notar su preponderancia a un nivel 5 a 1, o sea 5 hojas de negocio 1
hoja de personal y lo personal queda muy light y muy diluido como
restos luego de una gran tormenta.
*** disquisiciones sobre la compra de una tablet (que al final luego compre)
detalladisimos analisis sobre todas las cosas que supuestamente iba a
hacer con la tablet, leer libros, afiches, panfletos, ver videos,
peliculas, escuchar musica, etc, etc, la realidad es qeu no hice nada
de todo eso, la tablet fue de lo mas inutil y muy pronto deje de
usarla y termine deshaciendome de ella.
y nunca se la uso como pensaba, quizas pq pronto fue reemplazada por
el moto g y su practicidad que vino a duplicar funciones (todo lo que
en su momento hacia la tablet no hacia el BlackBerry)
Incluso produce cierta nostalgia como parte de las posibles funciones
las que pensaba iban a ser posibles usabilidades de negocio previas a
la aparicion de androwish y su revolucion, o sea el tener el pdf con
los datos de los clientes y esas cosas.

