"los que quieran que el futuro sea diferente del pasado deben estudiar
el pasado" .-- Spinoza
"Si en todo oficio no se pone consciencia no se puede prosperar". --
Shakespeare


CAMPO II ETAPA
* tomo I 13-04-13 a 30-06-13
...14-04 luego vere que proyectos se consolidan y cuales quedan en la
nada y se olvidan.

...primera noche...sino tuviera un año de experiencia durmiendo aca
estaria cagadazo, pero todo ok.

...es muy loco volver a la misma cabaña pero mejor pq ya conozco como
son las cosas.

...el dia estuvo tramado por la preocupacion de reorganizar el negocio
(de tener que).

...no hay dpto o casa que se compare a esto aca. El viaje es lo de
menos, y la soledad tambien la tenemos alla.

...hoy cuando pensaba a la ida que podria cambiar el tjo para hacer lo
que me gustaria rapidamente volvi a la sensatez (por peaje), pq no voy
a ganar esto sentado en ofi por mas que crea que es alienante o
hartante.

...el nivel basico de vta para funcionar cubriendo costos seria 50k y
en Ago12 estaba 60k con plan simple y con faltante de vta.

...El concepto que tengo de la cabaña es que es un lugar propio para
vivir que yo elijo, el viaje no me interesa igual que el manejo. Sino
el vivir bien y mejorar los habitos alimenticios. Cabaña no es
contrario a tener buena pilcha sino le agrega fuerza y naturaleza.

...18-4 hay algunas rutinas que por ahora me hacen bien, p.e. hamaca
vespertina, el comer sano, comer fruta.
Tengo muchas cosas todavia por hacer tanto tareas como proyectos como
distracciones. Viene a ser tmb como pasar el tiempo pero de otra
forma. La idea es cambiar de habitos y buscar otro horizonte de vida
que no sea el encierro en cuatro paredes y la tele.
quiero 1gfpc.
la vida es filosofia y hay que saber vivir contento con lo que uno
tiene.

...sali hice una linea del bancal. Dos misterios: que no me picaron
los jejenes y que la tierra este tan mojada.

...23-04 mal mal de salud creo que una migraña (voy 3 Mig) 7am-14y
17hs.

...24-4 nuevamente a las 20hs en el sobre, ya un habito, jeje, pero no
siesta y actividad a la tarde.

...El campo queda en un contexto bien organizado como una eleccion por
la salud, por el movimiento y por el aire puro o al menos mas puro que
en la ciudad. Una eleccion de estado minimalista y filosofica. Pero
habria que buscar salida a la presion que se genere para no caer en
decepcion y contraciclo.

... las rutinas son importantes pq son las que marcan lo que sentis
respecto a como vivis.

...sabado 27-04-13
seria un dia arduo, de gran prueba si no hubiera tenido a la mañana el
condimento del wapp.(1er wpp de Vdez)

...la gran falacia es visualizar variedad en el centro (ojo que tmb
hay en ag) y creer (lo creia antes, ya no) que el centro te daba la
posibilidad de obtener alguna cuota de ese mercado. 
pero la realidad es que no, parte pq los musculos envueltos no estan
desarrollados (y una vez desarrollados se podrian ejercer en ag si
quisiera), y parte pq la vida en la ciudad me quita el sentirme bien
que es fundamental para encarar todo con vigor y salud.

...hoy tengo de nuevo una migraña de 3 a pesar de haber estado en casa
y me siento mal como mareado y tomo consciencia que estoy con
semblante viejo muy demacrado y poco nivel de fuerza realista.

...olvidarme de todo pq quiero una gfpc no una palomita de la virgen.

...hoy venia para aca y venia mal pq estaba embroncado pq estoy solo
pq sali de la casa en un momento critico y despues el FEde termino
yendose y yo quede offside por el cambio.
y decia bueno ya estoy debo ahora apechugar ya lograre equilibrarme.
...Creo que la ataraxia, la alimentacion sana, el movimiento, son
proyectos basicos pero pueden caer en el vacio del nihilismo. Por eso
la gente se pierde en lo cotidieana en lo superficial y en querer
poseer cosas.

...que el bajon no te impida apreciar esto o sea la naturaleza.
En este sentido el libro de Robin (sobre los venenos) pateo en contra
justo en un momento bajon pq cai en una desazon planetaria ya no
sistemica, al estilo Charton Heston en planeta de los simios cuando
vio restos de la estatua de la libertad como desazon final de que todo
esta perdido. 

... Entonces sumado a la desazon de no ver el entorno, de estar muerto
ante lo intelectual (anoche inexplicablemente me dormi literalmente a
las 20hs y por 13hs) y de la imposibilidad de permanecer hasta cierta
hora hacen un coctail malsano. acuesto de tarde, me duermo rapido, me
levanto tarde, me duele la espalda, hago poco, decepciono ante falta
de fuerza y proyectos.

...Como parte del periodo de desazon esta el miedo al futuro por la
total indefension siendo que todavia tengo gente a cargo por diez años
mas.
pero lo bueno es que al venir aca plantie un cambio de vida, hacia una
postura mas sana, filosofica y minimalista de la vida, o sea lejos del
exito mundano caracterizado en 2008 y que volvio al menos en relato
estos ultimos seis meses.
Como se manifiesta el cambio de actitud?
1. la idea es trabajar en forma continua para vivir sencillamente y
   asegurar el futuro retiro
2. vida sencilla es conservar el auto o cambiar por una chata de
   similar valor - pasar a considerar el auto como un medio de tte no
   como ninguna otra cosa. No derroches en gastos de ningun tipo
   incluidos gastos de ropa.
3. vida sana. Como prioridad de vida y acomodamiento de valores
   incluyendo la ataraxia y la filosofia pq no hay forma de vivir o
   soportar la vida.
4. como objetivo secundario una gfpc no hay incompatibilidad con el
   tipo de vida planteado.
Esta actitud cauta puede llevar a un sistema sustentable de unos 10
años vista. No olvidar que tecnicamente me quedan 17 años para el
retiro.
Si dedicara estos 17 años a una sola cosa la cosas seria diferente,
p.e. en focalizar, repensar, y generar una teoria util que sirva a los
propositos utiles.
MAYORMENTE ESTA VIDA QUE LLEVO TIENE MUCHO DE TIEMPO LIBRE Y ESO
CUESTA ADMINISTRARLO.




