* Mayo
** 12 arreglo con Sorpresa.
Congelar la deuda y compro-pago con descuentos. Esto facilita y
clarifica el futuro.
** los timbreros
Bernardo dice que los timbreros quedaran afuera pq el costo de mano de
obra cada vez sera mas alta.
** campo
hoy pienso que estar en el campo me dio la perspectiva y la claridad
para buscar la solucion.
Buscar el minimalismo y el estoicismo.
Tambien el campo tiene una mayor actividad fisica.
Hoy 18/5 conecte la salamandra y funciona!!
Necesitaria media sombra verde para Pucho!!
Cada cosa mal hecha sirve de experiencia hoy no pude prender la
salamandra. No basta con el tiraje hacen falta leñitas blandas.
El guisado lento sin carne terminado en la salamandra puede ser un
recurso exquisito.
Hoy sali a tomar aire de noche y las estrellas se caen, se ven las
constelaciones y el vientito mueve los eucaliptus y se sienten los
perros que ladran a lo lejos y la soledad absoluta surcada por las
motos y los autos anonimos y PUcho y los gatos jugando alrededor.
Ahora pienso que este campo es un gran acierto pq configura mi
"pasion" y da coherencia a mi vida. Todo concuerda, mi independencia
laboral, el anticapitalismo, vida suburbana, salud proactiva. No creo
que esto atente o produzca soledad, al contrario.

El anclaje inicial de alimento vitalizante es el licuado (c/leche
vegetal) mas el guisado natural mas kefir.

"Hoy Pucho respondio a los cascotazos y se escondio bajo la cama de
las chicas y despues estando afuera le ladro a un ovejero de la tapera
que se acercaba hasta la casilla del agua y lo saque cagando. Me fui a
cerrar la tranquera y se quedo en la cochera. 
Si no fuera por las moscas que estan molestas el ambiente esta
perfecto, la salamandra funciona a pleno, gaturro arriba de los
troncos para que Pucho no joda y el silencio brutal"
** negocio
hoy 24/5 fracaso el sistema de captacion de 900x40.
Y en general no hay sistema.
Debo barajar y dar de nuevo.
Barajo el 25/5 y veo que el problema es de expectativas.
Nunca funciono un sistema a porcentaje para captar. Siempre que tuve a
porcentaje fue pasado desde otro sistema.
Asimismo con sueldo fijo real no se puede estar y es al pedo total.
¿Se puede captar con virtual?
Hay que hacerlo bien. Creo que el error fue presentarlo desvinculado
del mes. Cuando digo ganas x pesos cada 40 ventas, en vez de tenes un
sueldo de x pesos por mes.

Perdi mucho con las "viejas" a comision. Las viejas 144 nacieron de
otra forma. Nacieron con un esquema de cobrador con basico y con
aporte de venta de promocion y luego con reventa en frio. O sea no
nacieron con aviso de porcentaje. (Como se intento en estas semanas)

El error fue no haber vuelto a lo que dio resultado siempre o sea al
promotor puro que venta casa x casa y luego hacer cobrar como sea.
* Junio
** 6/6 cumpleaños en soledad
Hoy cumplo años y estoy mas solo que Pucho. Pero mejor asi ya me
festejaron ayer el cumple.
Hoy pienso que todo esto es un error, incluso Pucho, luego sali afuera
y estaba en Romulana al 50 detras del gato de mierda y lo lleve a la
veterinaria a su vacuna.
Esta vida es la que elegi yo y no me arrepiento.
Hay dos elementos que son muy procampo, uno la filo y la otra la dieta
(y el ejercicio), al menos tendria que hacer plan un año.
** plan campo 1 año
aprovechar que estoy aca y que no puedo rescindir ya mismo para estar
un año y en ese año hacer todo el research y el cambio de habitos:
alimentario y demas. Tratar tambien de hacer la sintesis de todo y
despues ver.
** 8/6 el campo me pesa
me pesa el viaje y el transito, me pesa la carga de Pucho, el tener
que hacer tantas cosas. Pero como contraparte estoy mas activo, ando
mas en la calle, y me hago la cena.

Se pondra cada vez peor y cada vez veo mas incomodidad de la cabaña o
sea su precariedad. Y no salto lo peor todavia o sea el pasto.
PUCHO ES TOTALMENTE UN ELEFANTE DE SIAM QUE ME DIO IH.
No estoy ligado afectivamente pero me embola tener un perro que haya
que cuidar, no a nivel perro sino como articulo de valor.

Otra vez caigo en los mismos errores o sea venirme al campo pero
crearme obligaciones que molestan (perros y pollos en la Betty y
perros y gatos aca).
Hoy estoy decidido a solucionar el tema animales y no creo que siga en
el campo o al menos no en esta casa.
Pero si me mudara no tengo que ir al centro. Quiza lo queria era una
casa confortable y punto.
Mas que todo veo que pierdo tiempo.
¿Se pierde tiempo? ¿Como?
¿Como maneja el tiempo la gente?

Cuando el 6/5 dije "apurar extremos" o el 6/6 plan campo 1 año me
refiero a un CAMBIO REAL. p.e. en el tema alimentario realmente
cambiar a fondo y crear los habitos necesarios para cambiar como hago
con el licuado/leche vegetal.
Ahora quiero darle mucha pila a la filosofia con Feinmann para
realmente aprender.

Pucho esta mas activo, pasaban dos chiquitas y el las siguio pero no
se salio poner mediasombra urgente!!.
** plan de estudios
fundamentalmente investigar dos temas Filo y alimentos
Profundizar las lecturas.
1-filosofia
2-alimentacion
3-plan negocios
** negocio
Cuando sali despues del fracaso del aviso pense en liquidar todo y
poder vivir rehumilde haciendo algo que me guste... pero ¿que me
gusta? No se...

La vision que tengo es tener una orga especifica: vender cortinas (los
22 colores) en TODOS LADOS a presion en todos los barrios por medio de
un sistema de venta. No distraerme trayendo otras cosas ni nada y
siendo muy habil para cobrar.

Hoy ganar 30k netos ¿se lograra con un negocio? Capaz pero trabajando
toda la familia 10/12hs por dia y yo pienso hacerlo solo hasta las
16hs.
** 16/6 campo positivo
hoy en dia siento gran atraccion por el campo no importa el clima
siendo tambien los extremos lindos. Y por el silencio y
tranquilidad. Aunque no arranco todavia con ejercicio fisico. Pienso
que el punto de pivot es el cambio alimentario y como se logra ya con
lo organizado que estoy.
quiero tener habitos ya firmes de consumo para tener la seguridad que
no cambian mas.
** 21/6 tarde bucolica
una tarde bucolica perfecta, vine bajo la lluvia leve, prendi la
salamandra, me frite 4 empanadas en grasa y me acuesto una siesta a
leer con ventana abierta y el ruidito de la lluvia. Como esta frio
estos dias pienso que la actividad se reduce al minimo y hay mas
tiempo adentro.

En este momento el unico proyecto que tengo mas o menos es la
alimentacion incluso mas que campo. Al campo lo padezco y aguanto y
por ahi me gusta pero fuera de esto nada.
** 22/6 la noche mas larga
son las 18.40 y ya es de noche y cae una persistente lluvia sobre
Anizacate y se bajo la luz quedando la lampara rojiza dando una
penumbra sugestiva de puta madre. No creo que la luz alcance el resto
de la noche. Tengo un poco de humo adentro pero la salamandra esta a
full y estoy cocinando los porotos. Probe el kefir con otra azucar
para ver si esta vez sale.
* Julio
** 2/7
en 2010 cuando "estaba enfermo" posiblemente estaba somatizando las
dificultades vitales del negocio. La inopia en que cai, esa anemia
espiritual, ese vaciamiento de la praxis, y esas dificultades
alimentarias me hicieron caer en una falta de energia y debilidad
general y posiblemente un avance de la prolactina hizo el resto. 
Sino no se explica el bajon y la perdida de una oportunidad historica
para resurgir.
Nadie le da bola a la importancia de la alimentacion en los males que
padecemos.
** campo
al campo no hay que analizarlo mas. Lo que importa es como llevo mi
vida y como fortalezco mis ideas y valores. Aparte el campo es el dia
a dia y sabemos que va a ir cambiando el clima y el invierno es la
peor temporada. Posiblemente llegue a otro nivel de confort en el
futuro.
* Diciembre
El problema N°1 es el negocio. Y dentro del negocio es la venta. Para
vender hace falta captar y eso es lo que frena.
Al no tener idea clara en el 2011 se fue el tiempo. Idem en el pasado.
Hubo variaciones de un punto al otro. P.e. desde 514/516 (Sras onda
144s para vta y cobranza) visitando a clientes a grupo promo
supervisado con muchos problemas a SF, a SV y comision.
En articulos desde MT cortinas, a todo a MT manteles!!.
En plan desde semanal a mensual con seña y sin seña.
Permanencia de gente: CERO.
La mayoria solo trabajo un mes, con excepcion de 544 que trabajo 3
meses.
Dificultad para captar: alta. Termine en aviso de mujeres unicamente y
un par de meses SRAS con muy bajo nivel de exito.
La bocha seria hacer un plan de trabajo racional que intente cambiar
la inercia pero tampoco sea utopico. (Evaluar el nivel de experiencia
ya obtenido.)
Es notable la gran improvisacion que tuvimos siempre.
Muy comun hacer carpetas despues de los cursos a las apuradas, buscar
zonas las mañanas al salir la gente, legislar a posteriori,no tener
reglamento, tener un plan facil vulnerable, etc.
Balance de fin de año:
Fines de año, tiempo de balance desde siempre.Mas profundos cuando mas
mal me iba.
Y ahora no puede irme peor.

Cuando estoy solo necesito justificarme o sea cumplir objetivos/
tareas/ metas/ planes para que valga la pena estar solo o para que
pague el precio de romper el esquema general (lactico). La
contradiccion mayor es que al no profundizar el frikismo lo padezco
con dudas y creo remolinos de desasosiego, cuando a lo mejor dandome
permiso para ser yo mismo la cosa cambiaria.

-- [Muchas veces en mis escritos esta este tema o sea el darme permiso,
el encarar el xt, aunque sea por x tiempo, y ser a fondo asi freaky,
sin "ese" condicionante que creo que se refiere al mandato de tener
que ser normal, en otras partes a rehuirle a la soledad y no plantarle
cara, pq para ser xt hay que enfrentar la soledad y en otras partes
que el tiempo libre corro a gastarlo como todo el mundo lo gasta, o
sea en peliculas y demas para no pensar y no enfrentarse a sus miedos]

... Estoy resistiendo el impulso de decirme que emprenda un plan de
estudios o cosa similar.

Lo primero es ubicarse en que tipo de negocio uno esta. Como quiere
currar. Esto es tipo StringBill no es un curro legal.
Cuando crei que esto se podia hacer de forma normal ahi la
palme. Igual cuando no supe/pude sacar las ganancias y dejar de
comprar, para estar mas libre.

Un sistema debe ser RPCZ tener Reglamento, hoja de Promo, Contrato y
Zonas, antes de comenzar, y eso requiere pensarlo bien.

ih es un costumbrismo que se mata con el ejercicio de la soledad.

El ejercicio de la soledad: es la practica voluntaria  de enfrentar
con solvencia y hasta con gusto el terrorifico fin de semana, sin
temores y sin desasosiegos provenientes de la presion por ir. Sin
molestias por el que diran.

El problema de la cobranza:
la venta esmerila en 2/3meses salvo gente especial como 154 pero
tienen la verga de damocles por el culo.
Con propuestas mezquinas los vendedores duran 1 o 3 meses como mucho.
El PC deja de ser tal cuando
1. tenes cobradores puros que ganan mucho y te cubre mucha zona.
2. tenes venta para mantener esas zonas y a nivel general.
3. si tenes una propuesta para promotores que prenda y podes vender
   (cantidad de jornales por mes J=120 o mas)


...la tarde bastante soportable y luego tormenta electrica sin lluvia
hasta ahora.
El pajaro negro ataco la militud pq se pensaba en peligro.
Ahora se largo a llover y me tengo que refugiar en la galeria sur que
esta ocupada por la hermana de Gisel. La tormenta fue un pedo y quedo
todo igual, seco sin agua. Voy a regar...

...20-12-11 el mayor calor sufrido desde que estoy aca, los perros
estaban sin agua, tomaron agua cinco minutos seguidos, una tortura por
pasar un estupido dia en la casa...
...23-12-11 hoy hace una tarde perfecta. Ni imaginada puede ser
mejor. Fresquita, nublada con viento que sopla, suena el cencerro, de
vacaciones, solo, sin un pedo que hacer, ni una puta condicion ni
siquiera una autocondicion.
...se puso muy fresco con la luz cortada un buen rato.
...27-12 hoy estoy solo y posiblemente me termine aburriendo pq las
condiciones climaticas son adversas para todo tipo de tarea en el
campo. Hace mucho calor y la siesta se hace larga y calurosa, lo mismo
la noche.
El objetivo: hacer mas minimalista el sitio, para evitar la sensacion
de casa revuelta enquilombada.
...28-12-11 despierto solo un dia miercoles de vacaciones y no quiero
caer en la variante del utilitarismo, o sea ver estos dias como que
tengo que hacer algo util. Aca no hay nada que hacer.
Sobre el estudio x-treme: el estudio xt no significa retroceso sino al
contrario, significaria el paso a otro nivel.
Si eliminara o me librara de las remoras del pensamiento en forma
consciente quiza la cosa seria distinta.
Remora 1: el dialoguismo virtual.
Remora 2: el aplicacionismo.
Remora 3: el diletantismo (la baja concentracion y la baja
dedicacion).
Tambien si evitara el tiempo perdido en "matar el tiempo" o pasarlo. Y
la absorsion en el seno familiar. Y me librara de la gran remora, la
castracion quimica. 
¿Por que estoy en el campo? me pregunte hoy y respondi para cambiar la
bocha de los alimentos un cambio groso que requiere aislarse un poco y
volverse un poco radical. Y para pensar. Para pensar a fondo y
descubrir el meollo de la cuestion.
...Noto un alto grado de precariedad y rusticidad en este campo, tanto
adentro como afuera. Un afuera extenso y castigado por la sequia y un
interior muy sucio y desordenado. De todos modos voy a persistir ya
que no me queda otra posibilidad de cambio en lo inmediato...

...sobre el pensar
1. que la ignorancia es muy grande
2. que la percepcion de la verdadera realidad es muy escasa y/o equivocada
3. que mayormente no actuamos solo seguimos en pasividad las rutinas
   (y no pensamos, reusamos lo pensado)
4. que solo "matamos el tiempo" y sea solo o en compañia y eso
   conspira contra el cambio.
5. que solo somos diletantes al leer por encima y zapear y seguir
   cuando quizas el avance se da con la relectura y el mayor tiempo pensado
6. que no hay transformacion real por el facilismo de dejarse llevar y
   lo odioso de aprender
7. que hay vicios ocultos como el dialoguismo, la contada, el
   compartir o tener que contar, la pontificacion o el ataque.

* Enero 2012
...9-1 el campo esta extremo de calor tierra y sequia, pero esta
tranquilo y silencioso. La quinta se achica. Creo que se puede avanzar
en la minimalizacion.
...Creo que voy derechito a PLAN B
Dadas las caracteristicas unicas de esta cabaña (su rusticidad,
aislacion, extension) y el precio bajo relativamente puedo irme al
centro sin dejar el campo, incluso puedo organizarme para venir a
dormir 3 noches por semana.
El marasmo citadino era consecuencia del marasmo fisico, intelectual,
espiritual y animico-filosofico. Hay cosas inexplicables como la falta
de ejercicio y la falta de interaccion. Creo que el desvario de
pensamiento de 08/09/10/11 tiene que cambiar, ahora las ideas las
aislo.

Filosofia del pesado:
pesado es el diletante qeu ni bien lee algo lo comunica o cuenta a sus
sufridos interlocutores. Puede que sepa algunas cosas interesantes
pero generalmente aburre o choca pq a  la gente no le gustan esas
cosas y se la cosa se cruza termina pontificando y chocando de una.
El problema es compartir cosas que no se conocen bien, las cuales
podemos llegar a robarlas o completarlas o citarlas muy
frecuentemente. Lo mejor seria preguntarse ¿quiere el interlocutor oir
mi historia? o la padece?.
En la oficina seria el "des-cubrimiento" de si mismo, una puesta en
valor pero termina siendo unicamente un lustre al ego cuando el que
escucha no es un objetivo (516/572) o es un grupo (151 y cia).
Lamentablemente muchos de los temas siempre derivan en una toma de
posisiones o en el choque o en la pontificacion cuando se analizan
tendencias o conductas de la gente en general en la cual uno esta
incluido y comete los mismos errores.
1. evitar posturas chocantes
2. evitar ser pulpo emocional con no-objetivos
3. evitar el referente confesor
4. evitar la necesidad de catarsis
5. evitar la hablada sobre temas ya agotados o ya pensados.

Analisis 2011 y rezagos del 2010
1. increible lo frusco frente a dos perlitas como ? y ?.
2. marasmo: la situacion no solo era economica sino agobiante en 2010
   pero en el 2011 no se pudo remontar rapido pq segui con los mismos elementos.
3. migraña: es patetico leer el diario de situacion de lucha con el
   micranil por eso decido meterle con las enzimas y que sea mas leve.
4. frikismo: el peor es el computacional por muchos motivos. El
   frikismo se olvida cuando no ataca. VIM???.
5. IH dominante: la mina es dominante y quiere imponer que las cosas
   se hagan a su gusto (pe. con relacion a las visitas de las chicas y
   al Fede)
6. el findesemanismo: esa dependencia sicologica proveniente de como
   pasar el finde da para toda una filosofia.
7. actitud victima: o sea sufria pq tal cosa p.e. no tener la netbook
   o no tener una relacion con equis persona. hoy la actitud
   cambio. Digamos que hay identidad.
8. compulsionismo: ¿Pq si son hobbies me causan problemas?... Creo que
   eran una forma de "matar el tiempo".
9. carencia de plan: el 11/1/11 no tenia la mas puta idea de lo que
   tenia que hacer y en vez de estar pensando un plan estaba friky
   compulsivo con Vim y golpeado por la migraña.
10. plan de trabajo a enero 2011:
    Sras para visitar clientes
    luego me desilusiono de ese perfil y pongo avisos pero mal
    promotores-cobradores y me enojo pq optan por la cobranza.
    Increible que con la experiencia del 2010 en venta de cortinas cxc
    no haya intentado de una recuperar esa experiencia y en cambio me
    haya desviado por tantos caminos.

Resumen lectura 2011:
Ese periodo esta signado por:
1. el negocio: para el cual no tenia ningun plan ni idea nueva
2. la salud: en especial la lucha con la migraña y levemente el
   descubrimiento de lo nuevo en alimentacion
3. la soledad: y la imposibilidad de solucionarla son comunes los
   estados de aburrimiento y depresion. El dpto es disonante por su
   tamaño y poco disfrute. 
Luego el campo surge como idea relampago y despierta innumerables
vectores que van a rescatarme de ese marasmo y a activarme un poco
mas.
Pero no le pude encontrar la vuelta a la captacion o sea a la venta y
termine un año muy ajustado. Solo paliado en parte por un buen
desempeño de los cobradores y de las ideas que me alientan desde fin
de año.

...El campo es el resultado de una situacion puntual a Febrero
de 2011. Ya vi con analisis como pensaba y que revoltijo de
pensamientos me secundaban.
...Dentro de toda la situacion que experimento hoy creo que me deslizo
por la tangente de la "evasion" cuando me pierdo en la lectura
maratonica y me salgo de un esquema coherente de vida.
... Estoy aca porque en cierto momento lo decidi. ¿Elegiria hoy esto?
¿Es la lectura una evasion?. 
... Rifo/rifare mi independencia o mis ideas nuevamente. No he podido
reservarlas siempre compartiendo. Ya sea a nivel negocio o por causa
de la migraña o la soledad. O sea caida en la dependencia.
... Sino fuera por este puto dolor de cabeza pensaria diferente.
La pregunta es si no lo genero al dolor con las posturas del dia en
vez de hacer ejercicios durante toda la jornada?
Ya lo dispare a las 19hs con el migral pero ¿que paso de 7 a 19? toda
la mañana tenso sin ejercicios, el viaje, el encierro en la siesta
larga por demas.
...No entiendo que autoconspiracion me trajo hasta aca y que falla
mental me hizo dentro  de esa situacion meterme con los perros
los gatos, la quinta etc. Llego a ser prisionero de las cosas, encima
cosas sin sentido que no me aportan nada y me alejan de lo que tendria
que hacer.
Cada vez me cuesta mas identificarme a nivel identidad o como
extravagancia con esta vida, de modo que sobrepase las molestias
ocasionadas. No puedo culpar a nadie pq yo solo cause mis males.
...27-01-12 compre impulsivamente el ereader pero estoy conforme.
...Sobre el volverme los hechos demostraron que:
1. no corri, no hice ejercicios etc.
2. no me beneficio el tener perejil de lo que es el sistema mejorado
   de comidas
3. estoy atascado en general y no hay crecimiento
4. estoy escondido
5. tengo el agobio del viaje a diario
...hoy pensaba que un dpto puede tener muchas inconveniencias pq
volvemos al ruido externo que te molesta todo tipo de concentracion. O
podria ser que represente riesgos muy grandes [a nivel volver al
marasmo, el encierro, la inmovilidad, la casita de ken]...

...30-01-12 MOCO MAYUSCULO: salia una tormenta mayuscula sin volverme
a la cochera cubierta. muy pelotudo. Ahora safe sin rotura de vidrios,
vere la chapa y estoy varado en la inundacion.

...Analisis de los pro-del campo
1. SILENCIO: nada igualara el silencio del campo, salvo por el gato,
   los ruidos del techo, y la heladera.
2. AIRE PURO, NATURALEZA, PAISAJE
3. EXTERNALIDAD, USO DEL AUTO, DESENSIMISMARSE: los dptos son para
   estar adentro ensimismado.
4. PROCLIVIDAD ALIMENTACION SANA Y EJERCICIO
5. INDEPENDENCIA: porque es algo atipico y elegido por mi.
6. LEJOS IH: para facilitar las cosas

* Febrero 2012
La soledad o estar solo (es mejor esta frase "el estar-solo" pq es una
frase presente no una condicion final o un dictamen final) es una
oportunidad en vez de una carencia.
La oportunidad de pensar, de leer, meditar, aprender, recordar,
analizar y de hacer cosas.
Cuando uno se desprende de la tirania mental proconcebida de la
socieda de que ES (estar solo) es malo perse y lo asume o lo enfrenta
ocurren cosas grandiosas (y por lo tanto incomprensibles para los
demas).
1. deja de tener miedo a ES. No lo ve como algo terrible sino como
   algo deseable.
2. se torna mas productivo: indudablemente solo podes hacer un monton
   de cosas que no harias si estuvieras con alguien mas, pq se impone
   "la compañia" o sea el estar juntos compartiendo lo mismo.
Obviamente personas que producen han tenido que estar solos una gran
cantidad de tiempo. (p.e. Sto tomas de aquino SIC). Increible que
cuando se piensa esto salta el tema celibato, cuando nada obsta para
salir cuando quiera. Pero siempre vi las relaciones como
entorpecedoras de la libertad y en el ES el sumun de la libertad o sea
la libertad de hacer y de pensar lo que quiera sin peleas cotideanas
estupidas o cambiar un Ibsen por una conversacion repetida y censurada
sobre topicos comunes.

...Creo que me equivoque a principios de año con el plan pq crei que
podia imponer un 1CM de entrada y no fue facil. No todo es achacable
al mes sino parte a la dificultad del plan. Para hacer un plan KISS
tambien tendria que ser vendible y alli viene cortinas en PS. 

...Me asombra la dinamica de push-up. Estar haciendo 3x12 al toque
casi sin esfuerzo es algo muy grosso. quizas sea el videito que te
instala la rutina (pero al hacerlo sin el video imaginando el dibujo
va todo ok). Tengo que ir para la 2° rutina y llegar pronto a la tres,
como metodo puede ser alentador...

...tambien me asombra el resultado de la lectura en el ereader tanto
en la dinamica como en la biblioteca encontrada y como se
interrelacionan los temas y se hacen conexiones.

...11/2/12 vine luego de estar hasta las 16hs con ih merende lei
(termine La Peste) y corte el pasto bastante. Me lleve el tele a la
pieza, estoy bajon pero no importa. Creo que la causa es el fracaso
del negocio y la insipidez de ih.

...Excurso sobre mi trabajo:
me invadio un par de veces estos dias la decepcion en el sentido de
que es un trabajo de mierda pq no tenia resultado.
Si hay venta me gusta y es pocas horas y es comodo y me deja hacer lo
qeu quiero, el problema es la noventa.
El famoso 400cxm que tengo que alcanzar. Obviamente si hoy estuviera
embolsando 36k estaria muy contento. 

...el otro eje es la separacion:
son etapas que voy a quemar.
lo primero muy importante es no necesitar la compañia de la familia
para atravesar los fines de semana aca en el campo. Esto me da la
independencia para decidir que hacer.
lo segundo seria no necesitar contar cosas o pensamientos o ideas.
lo tercero seria no necesitarla para nada.

...Este domingo solo encontre la paz. Ese equilibrio justo de
actividad-descanso que te hace apreciar la naturaleza sin ningun tipo
de tension (no tengo que ir alla, no tengo que volver, no tengo que
hacer nada en especial). A la vez fue muy positivo haber limpiado y
acomodado el dormitorio. Ya otras veces la accion te saca del marasmo
y uno resulta mucho mas fuerte de lo que cree. Tambien no comer mal
sino comer comida sana.

...error pensar que la gente entiende el SV: se mandan y una vez
adentro aceptan sin discusion las reglas.

...Excurso: percepcion del propio patetismo: Con mis MBs que son cosas
simples pero valiosas como ir adaptando el sistema a pura filosofia o
las rutinas de alimento ya establecidas o la rutina de 3 series
bastante establecidas y otras chocan con autopercepcion del patetismo
propio cuando me veo frente a lo grande o espectacular (caso p.e. via
lectura) Pero esta es mi vida y me gusta asi como es. Esto es muy
importante pq la aceptacion de uno mismo es fundamental para ... uno
mismo.

...18/2/12 lindo dia vientito calor pero no muy mucho por
ahora. Disfruto enormemente el ES es como un hedonismo total en el
cual uno se basta con su compañia y pasa el dia haciendo lo que a uno
le gusta (o evitando lo que le disgusta) p.e. no me gusta salir pq me
da fiaca, pq salir no me aporta nada que me interese, -ese es el quid-
si me interesaria un sitio como este pero mas sombreado pe. pero no
creo que hiciera la gran diferencia o tener una heladera y plantear
mas y mejor cocina (no obstante he tenido siempre heladera y he comido
mierda o nada).
Pero interesarme ir a un lugar multitudinario no me interesa ya que lo
unico que rescataria seria ver algunas (no todas) mujeres, pero como
ya las veo gratis en el centro tampoco eso me aporta nada.
sentarme a hablar con ih esta bien de vez en cuando, pero cada vez
menos pq nos hemos apartado divergentemente en el plano mental y
fisico. prefiero estar solo con mis animales, disfrutar la naturaleza
en sus cuatro estaciones y disfrutar de mi pensamiento de mis
lecturas, mis analisis y tambien de la mayor actividad fisica que
tengo aun sea para cumplir las obligaciones cotideanas.
y tambien me queda hacer cebo, pq merezco estar al pedo siendo que
cumplo con mis obligaciones mas de lo debido. los mantengo sin chistar
y soy un referente cuando me necesitan y a la vez no los jodo con mi
vida.
por eso pienso que atizbos de melancolia, vacuidad, zozobra o
aburrimiento solo en grado minusculos que puedan aparecer de vez en
cuando son costumbrismos - viejos habitos - que saltan solos y no son
dignos de ser tenidos en cuenta, o bien hay que cambiarlos.

** Teoria X-Treme
Significa un tiempo de x duracion donde busque cambios mas extremos
sin el continuo cuestionamiento que me hace dudar, ni la necesidad de
compartir o contar o predicar el asunto.
Cuestionamientos: comienzo yo mismo a cuestionarme en el sentido de
que me alejo aun mas de la teoria lactica o le doy la espalda (como si
estuviera a mi mano tenerla ya mismo).
Compartir:(contada) cuando cuento un pequeño avance, o la pequeña idea
o teoria o lo que sea la debilito y queda alli mismo reducida a algo
insignificante. Y aparte se debilita pq pasa a ser palabra y no
accion.
Poca profundizacion: como las horas de soledad se las trata de mitigar
o "pasar" con elementos similares al comun (video lectura compu) no se
profundiza en los aspectos del cambio. Porque un cambio real y extremo
es a largo plazo y con gran dosis de pensar.
Candidatos a entrar
*** alimentacion
la base de todo y el mas avanzado. Require mayor produccion de
elementos propios (huerta) y de elaborados (germinados, hierba,
chucrut, encurtidos). 
a su vez necesita un aprendizaje mayor de posibilidades de cocinar,
organizarse para preparar.
1. cuaderno de huerta
2. mejorar la cocina comprar un mueble mas grande y seguro
3. aprendizaje (semillas, germinacion etc.)
4. complementos como los del A15 (algarroba, maca, levadura, etc.)
5. control negativo o sea no consumir lo negativo lo que hace mal
*** negocio
en la medida de acer una organizacion cientifica de ventas, donde todo
este pensado y controlado en su detalle minimo. Y sea algo nuevo y
distinto a todo lo hecho hasta ahora.
*** ejercicio
un cambio de habitos en movimiento. Ej idea: antes de pensar en
imposibles ver como cambiar el estado fisico con una serie de
ejercicios controlados conocidos (Caivano, hombros, cuello, espalda)
luego agregar abd y pectorales y despues comprar algunos aparatos.
*** pensamiento
analisis, metodo, relectura, realizacion, cambio real en la forma de
procesar todo. Con mas dedicacion. Mayor cantidad de lecturas. Pero si
no hay cambio no sirve.
*** accion-conducta
evitar las conductas pateticas y ridiculas que muchas veces son las
que se apartan de lo asertivo.
*** estudio
no pudo dejar en una opcion xt de poner el estudio.
*** la base del xtreme es el ejercicio de la soledad
al quitar el vinculo simbioticoveo que puedo crecer en otras
dimensiones desmitificando lo que la union simbiotica representaba. O
sea comprension, empatia, intimidad. Al tenerlo "fijado" en ih y
volverse simbiotico, llegaba a un radio corto de desarrollo.
Siguiente paso: no necesitar exponer las ideas pq tambien chocamos con
ese limite.
Preguntarse ¿para que?








* Comentarios de transcripcion
[2019-07-23 mar]
veo que la experiencia de campo si bien es cierto que salpicada por
algunas expresiones bucolicas era negativa, fundamentalmente por las
molestias que me ocasionaba la atencion al perro, al menos los
primeros meses que se relatan aca, y que la principal baza de la
experiencia era la ALIMENTACION. y no mucho mas. Por eso que luego en
las argumentaciones nocampo al final se decide dejarlo. Porque manejar
dos horas por dia, con el riesgo que ello ocasiona y la perdida de
tiempo para terminar en lo mismo que aca.
Aca en el centro si quisiera podria tener el mejor menu alimenticio
natural que se me ocurriera, falta ponerse freeky en eso y decidirse a
gastar y hacer. 
** la gran persistencia en formar un equipo de ventas
me lo repetia todos los dias, formaba parte del dia a dia, probe y
descarte numerosos planes, que no transcribi y termine tirando a la
basura pq no vienen al caso, solo deje algunos detalles minimos, pero
si vemos la cifra de ventas de esos meses
| may-2011 | 21170 |
| jun-2011 | 13717 |
| jul-2011 | 36746 |
| ago-2011 | 39474 |
| set-2011 | 29697 |
| oct-2011 | 49942 |
| nov-2011 | 43837 |
la mayor virulencia planificadora la vi en junio el mes que toque
fondo, pero el semestre siguiente todo ese analisis dio su fruto pq se
le encontro la vuelta a un nivel de productividad que permitio ir para
adelant
** la contradiccion del x-treme
siempre se plantea la contradiccion sobre el deseo de hacer un xtreme
como justificacion ultima de la falta de normalidad o de la
imposibilidad de la normalidad, pero se reconoce que hay trabas a un
perfecto xtreme causadas por los esfuerzos o los anhelos de
normalidad, los pruritos de normalidad, que si hubiera un pacto de
xtreme limitado en el tiempo, -p.e. xtreme por un año- en el cual se
olvidara la pretension de normalidad se podria lograr un cambio
bastante importante.
A hoy habiendo pasado estos años que al final sin xtreme de por medio
lo mismo me aleje de la normalidad y perdi totalmente la posibilidad
de reinsersion en la normalidad. 
Pero el debate sigue, imperceptiblemente, en el subsuelo sigue, en el
aburrimiento, en el no saber que hacer, en el querer trabajar mas, en
el querer volver a esquemas del pasado y no aprovechar las ventajas de
los esquemas actuales.
pero el razonamiento sigue abierto aun, si dejo en suspenso la
pretencion de normalidad y me sumerjo en el frikismo del xtreme,
aunque sea con una clausula temporal puedo lograr un resultado o sea
un cambio. 
** la gran similitud del marasmo 2011 precampo con hoy
[2019-07-29 lun]
la descripcion del marasmo 2011 bien puede ser confundida con una
descripcion de la actualidad. Quizas ahora un poco peor, pq se pierde
el tono muscular que daba la lucha de la vida, se pierde la privacidad
que daba el local propio, se pierde la interaccion continua que daba
el aviso y esa posibilidad latente de algo, ahora tenes todo
dinamitado. Tenes mas años, tenes mas tiempo, tenes menos comodidades,
pq ni tele tengo y alli estoy diciendo mucho

