* 2021
** Agosto
*** [2021-08-19 Thu]
    Hoy abro este nuevo archivo continuador de ali.org en un formato
    nuevo multiproposito y multiregistro.
*** [2021-08-23 Mon] 
    hoy es el primer dia de estar solo en la mañana pq ih se fue a
    trabajar con el Fede, y eso me produce una sensacion rara, por una
    parte me permite mayor concentracion, por otra me da una sensacion
    de vacuidad o sea el pensar que lo que yo hago no tiene sentido,
    que es todo banal y ahora se nota mas. 
*** [2021-08-24 Tue]    
    se puede decir que si que me afecta en cierta forma que salgan a
    trabajar ellos dos y yo no haga nada y eso me afecta en la
    capacidad de concentracion. O en la motivacion. 
* registro de sintomas (tabla)
| Fecha            | migraña | oido | meteo | depr |   |   |   |   |   |   |
|------------------+---------+------+-------+------+---+---+---+---+---+---|
| [2021-08-19 Thu] | alta    |      |       |      |   |   |   |   |   |   |
| [2021-08-21 Sat] |         | der  | mucho |      |   |   |   |   |   |   |
| [2021-08-25 Wed] |         |      |       | alta |   |   |   |   |   |   |
* registro de sintomas (explain)
** [2021-08-19 Thu] migraña
   tuve toda la tarde con dolor intermedio un dia con dos migrales uno
   a las 5am y uno a las 5pm, y a las 8pm me acuesto y a las 9pm el
   dolor era grande nivel 7 (impedia leer o cualquier actividad pero
   no era terrible, era posible dormirse), y dormi toda la noche con
   dolor, Me tome un 10mg tipo 10pm y recien mejore un poco a las 5am,
   y no estoy del todo bien.
** [2021-08-21 Sat] oido tapado
   desde ayer siento una sensacion de ruido, y hoy me puse gotas de
   cerumax y no me resultaron de alivio, no esta tapado como la otra
   vez pero siento molestias.
   [2021-08-23 Mon]
   la molestia siguio ayer un poco y me eche cerumax y no cambio nada,
   hoy lunes me eche cerumax temprano y luego ih me echo gotas oticas
   que entraron mas, y parece que lavaron un poco pero sigo sintiendo
   la sensacion. 
   [2021-08-24 Tue]
   no me puse gotas hoy, no siento tapon pero siento picor y molestias.
   sentia dolorcitos y me puse una gota de otosporin, y senti como si
   abriera algo, pero no pude estar tranquilo un rato para que hiciera
   efecto.
   Desde que me puse esa gota no me molesto mas parece.
** [2021-08-21 Sat] meteorismo
   Como y siento una sensacion de molestia en el estomago, distension
   y movimientos raros dentro, ruidos, sensacion que me viene un
   diarreion, pero voy al baño y solo son gases, muchos gases. Leyendo
   veo que es meteorismo. 
   [2021-08-22 Sun]
   pruebo desayunar mate cocido sin azucar y tostadas sin manteca ni
   dulce para evitar azucares y lacteos y ver la reaccion y por lo
   menos parece que las reacciones extremas descriptas antes no se dieron.
   [2021-08-23 Mon]
   ayer no senti la molestia explosiva, ruidosa y doliente que
   describia al principio. Hoy en el desayuno tampoco. Hasta ahora lo
   unico que deje fue el "licuado de avena cruda".
   Despues de comer me agarro un momentaneo dolor de "panza" y termine
   yendo al baño pensaba que era diarreico pero no. Al rato
   paso. (Comi pastel de papas con mucho pure recalentado, bastante
   caliente con un vaso grande de agua y comi apurado, despues del
   dolor me tome un boldo)
   [2021-08-24 Tue]
   hoy desayune mate cocido con torta y me olvide, pq no tuve ningun
   sintoma.
   merende tarde y me fui a acostar, pero un par de horas despues me
   dio hambre y tome un te con tres tostadas con queso. Me hicieron
   muy mal, me hicieron doler la panza toda la noche y mayormente eran
   gases.
** [2021-08-25 Wed] depresion
   hace un par de dias que me desaparecio la alegria por las mañanas,
   y me puse bajon. 
   es algo involuntario que no lo puedo manejar. 
   cuando fui a encargar los lentes pienso que anduve bien o actue
   bien, pero luego cuando estoy en la casa me decaigo.
   
