* 2021
** Agosto
*** [2021-08-19 Thu]
    Hoy abro este nuevo archivo continuador de ali.org en un formato
    nuevo multiproposito y multiregistro.
*** [2021-08-23 Mon] 
    hoy es el primer dia de estar solo en la mañana pq ih se fue a
    trabajar con el Fede, y eso me produce una sensacion rara, por una
    parte me permite mayor concentracion, por otra me da una sensacion
    de vacuidad o sea el pensar que lo que yo hago no tiene sentido,
    que es todo banal y ahora se nota mas. 
*** [2021-08-24 Tue]    
    se puede decir que si que me afecta en cierta forma que salgan a
    trabajar ellos dos y yo no haga nada y eso me afecta en la
    capacidad de concentracion. O en la motivacion. 
** Setiembre
*** [2021-09-09 Thu]
    hoy es el segundo dia de arroz yamani con amaranto y esta vez le
    puse un sofrito de cebollita de verdeo que le dio sabor pero me
    hizo un poquito pesado pero sin caerme mal como la comida normal,
    o sea sin acidez y sin problemas digestivos y eso que
    lamentablemente la comi apurado, no se pq, quizas tenia mucho
    hambre.
    pienso que si desayuno dos huevos con cebolla, y almuerzo arroz, y
    ceno alguna otra cosa que no me haga mal, puedo mejorar un poco el
    estomago.
*** [2021-09-10 Fri]
    hoy desayune mijo con pasas de uva y manzana cruda, medio plato,
    bien sin acidez pero me duele un poquito la panza, no se si debido
    al mijo o que me senti demasiado mal desde anoche por la ingesta
    de sandwich con glutamato que no me dejaron dormir. 
*** [2021-09-13 Mon]
    me siento con mucho bajon y mucho sueño, ya llevo dos migrales y
    no me siento muy bien. Lo peor que no tengo ganas de hacer
    nada. Nada en ningun sentido de la palabra. 
    encima unos pocos minihabitos alimentarios que habia iniciado se
    ven interrumpido pq estoy en asistencia a ih y no puedo hacerlo
    por ahora. Pero eso no tiene nada que ver con el hecho de que no
    tengo voluntad para nada.
*** [2021-09-15 Wed]
    mucho sueño ayer y hoy, me cuesta levantarme a las 9, tengo que
    dormirme una siesta y estoy soñolento

*** [2021-09-19 Sun]
    tengo una situacion catastrofica, me duele la rodilla izquierda, tengo
    sensacion de falta de aire y arritmia, me cuesta hacer las series a la 
    mañana, no duermo bien. 
    Aparte estoy estancado en lo que hago, no programo, el ingles esta estan-
    cado, la lectura esta para atras, y estoy monotematico, o sea no puedo ver
    ni disfrutar nada que no sea lo que estoy haciendo de rutina.
    Una idea es hacer un cambio de rumbo general basado en alimento y en acti-
    vidad y salida.
    Para hacerlo sencillo:
    1. rutina diaria aunque sea minima de bici fija
    2. rutina diaria de mijo/yamani/frutas/verduras para cambiar el estomago
    3. salir a comprar lo necesario ya sea a la dietetica como a la verduleria

*** [2021-09-20 Mon]
    anoche dormi un poco mejor pero mucho. y ahi puedo quizas explicar la 
    falta de aire del ejercicio de la mañana.
    el problema principal que manejo es el no saber que hacer, o sea tengo mis 
    rutinas para levantarme, hasta que llega el momento de sentarse en la 
    compu y alli no se sabe que hacer. Todo pq he acomododado muchas cosas 
    para hacer acostado (p.e. leer en la tablet, buscar palabras para activar 
    una leccion, incluso practicar palabras, o escuchar un video) y el 
    problema es que estoy llegando a la cama y no lo hago, entonces me siento 
    doblemente mal, o sea no "hice" nada en la compu y no hago nada en la 
    practica en la cama, por eso lo de los quantums de cosas que pueden ser 
    hechas de dia en la compu para mantenerme levantado cosa de no caer en la 
    cama ni en la desesperanza y a la vez cuando vaya a la cama este mas 
    motivado y haga la practica aunque sea basica.
    Mucho lo que me desmotiva es lo laboral, pero no nos va tan mal 
    relativamente, y la llave para que nos vaya mejor esta en que se forme el 
    segundo grupo con Fede, no que abramos una oficina. Creo que la 
    administracion del sistema y los papeles, y atender a Fabian es mi tarea.
    Tengo que pensar como administrarme bien en los proximos diez años para 
    que en los años siguientes a ello podamos sobrevivir.
    Por el momento debo sobrevivir animicamente y fisicamente el momento 
    critico actual.
*** [2021-09-21 Tue]
    pienso que si yo estoy en crisis laboral, Fede esta en doble crisis 
    laboral, pq el es joven y necesita que esto arranque de una manera 
    diferente. Que avance y se queda durmiendo.

*** [2021-09-22 Wed]
    Tengo una guia basica de habits para hacer, que voy cumpliendo con el 
    incentivo que te da el llevar la cuenta en la app. Los mas dificiles son 
    los alimentarios el mijo del desayuno y el arroz del mediodia, y la bici. 
    Pero si lo analizas nada es cosa del otro mundo, y correctamente motivado 
    los haces.
    Luego con respecto a mantenerse levantado y no echado, haciendo cosas en 
    la compu, ayer por lo menos me ha funcionado el concepto de los quantums, 
    al menos ha transcurrido el dia y solo me eche a la tarde pasada las seis.
    Hoy hice la tercera sesion de bici y eso es lo mas importante, pq el 
    movimiento es lo que me faltaba o estaba en grave falencia. Mas alla de la 
    cronicidad del migral, o de otros deterioros generales, era imperativo 
    empezar una rutina de movilidad que me lleve a un registro perceptible en 
    algun plazo futuro.
    Es feo lo que pasa aca en la casa, ih tiene frustraciones y se las agarra 
    conmigo pq piensa que yo quiero sacarla de la casa. Y nada que ver me da 
    lo mismo pero me pone mal que el Fede no reaccione y no salga a trabajar, 
    vuelvo a pensar lo mismo que los ultimos meses, es como si esperara que yo 
    tome la delantera en algun tipo de esquema de trabajo, mientras tanto el 
    no tiene iniciativa para nada.

*** [2021-09-23 Thu]
    el gran problema de hoy es el trabajo que esta en situacion peligrosa pq 
    el Fede no trabaja o sea no aporta extra, pero principalmente pq gasta de 
    mas, y eso estresa la economia.
    Eso hace el panorama mas incierto pq hace peligrar la fuente de ingresos.
    Pero no voy a caer en la preocupacion.

*** [2021-09-24 Fri] charla con Fede estado de la Empresa
    hoy tuve una muy fecunda y efectiva charla con el Fede, una toma de 
    conciencia total de que no es que estemos fundidos, sino que estamos en la 
    cornisa, pq no tenemos ahorro, y no ganamos lo suficiente.
    Esperemos que esto lo motive a cambiar y a arrancar lo suficiente.
    [2021-09-28 Tue] arranco el lunes a duras penas y a pesar de que vendieron 
    bastante bien, el martes ya echo el faltaso.

* registro de sintomas (explain)
** [2021-08-19 Thu] migraña
   tuve toda la tarde con dolor intermedio un dia con dos migrales uno
   a las 5am y uno a las 5pm, y a las 8pm me acuesto y a las 9pm el
   dolor era grande nivel 7 (impedia leer o cualquier actividad pero
   no era terrible, era posible dormirse), y dormi toda la noche con
   dolor, Me tome un 10mg tipo 10pm y recien mejore un poco a las 5am,
   y no estoy del todo bien.

** [2021-08-21 Sat] oido tapado
   desde ayer siento una sensacion de ruido, y hoy me puse gotas de
   cerumax y no me resultaron de alivio, no esta tapado como la otra
   vez pero siento molestias.
   [2021-08-23 Mon]
   la molestia siguio ayer un poco y me eche cerumax y no cambio nada,
   hoy lunes me eche cerumax temprano y luego ih me echo gotas oticas
   que entraron mas, y parece que lavaron un poco pero sigo sintiendo
   la sensacion. 
   [2021-08-24 Tue]
   no me puse gotas hoy, no siento tapon pero siento picor y molestias.
   sentia dolorcitos y me puse una gota de otosporin, y senti como si
   abriera algo, pero no pude estar tranquilo un rato para que hiciera
   efecto.
   Desde que me puse esa gota no me molesto mas parece.
** [2021-08-21 Sat] meteorismo
   Como y siento una sensacion de molestia en el estomago, distension
   y movimientos raros dentro, ruidos, sensacion que me viene un
   diarreion, pero voy al baño y solo son gases, muchos gases. Leyendo
   veo que es meteorismo. 
   [2021-08-22 Sun]
   pruebo desayunar mate cocido sin azucar y tostadas sin manteca ni
   dulce para evitar azucares y lacteos y ver la reaccion y por lo
   menos parece que las reacciones extremas descriptas antes no se dieron.
   [2021-08-23 Mon]
   ayer no senti la molestia explosiva, ruidosa y doliente que
   describia al principio. Hoy en el desayuno tampoco. Hasta ahora lo
   unico que deje fue el "licuado de avena cruda".
   Despues de comer me agarro un momentaneo dolor de "panza" y termine
   yendo al baño pensaba que era diarreico pero no. Al rato
   paso. (Comi pastel de papas con mucho pure recalentado, bastante
   caliente con un vaso grande de agua y comi apurado, despues del
   dolor me tome un boldo)
   [2021-08-24 Tue]
   hoy desayune mate cocido con torta y me olvide, pq no tuve ningun
   sintoma.
   merende tarde y me fui a acostar, pero un par de horas despues me
   dio hambre y tome un te con tres tostadas con queso. Me hicieron
   muy mal, me hicieron doler la panza toda la noche y mayormente eran
   gases.
** [2021-08-25 Wed] depresion
   hace un par de dias que me desaparecio la alegria por las mañanas,
   y me puse bajon. 
   es algo involuntario que no lo puedo manejar. 
   cuando fui a encargar los lentes pienso que anduve bien o actue
   bien, pero luego cuando estoy en la casa me decaigo.
   [2021-08-27 Fri]
   ayer senti que estuve mejor, aunque un poco beligerante con ih,
   quizas sea una reaccion pq ella este trabajando, pero la verdad que
   me gusta estar un par de horas solo.
   [2021-09-09 Thu]
   me cuesta levantarme y no me levanto con alegria como antes. Aunque
   la jornada luego mejoro bastante.
   [2021-09-22 Wed] 
   no digo que estoy alegre, pero tampoco estoy pesimiesta ni estoy triste, ni 
   estoy problematico, es mas estoy en el medio de una serie de minihabitos y 
   rutinas para cambiar el estado. En realidad veo que otros a mi alrededor 
   tienen problemas como ih que tiene problematicidades que las transmite a 
   los demas. 
** [2021-09-09 Thu] dolor rodilla izquierda
   empezo a molestar estando sentado, me puse la faja a media mañana y
   sigue molestando.
   [2021-09-21 Tue] desde ayer con la practica de la bici se ha acentuado el 
   dolor de la rodilla izquierda.
   [2021-09-22 Wed] a pesar del dolor que tuve ayer todo el dia, hice igual 
   bici, y durante la bici no me molesto, ni despues de la bici, que me saque 
   la faja. Sigue sin molestias incluso despues de la tercera sesion de bici.

** [2021-09-17 Fri] soñolencia
   el miercoles anote que tenia soñolencia, pero hoy es abuso, desde las 12hs del
   mediodia que tengo ganas de acostarme y no puedo pq me llama a cada rato Fabian
   me tome un cafe recargado y lo mismo tengo pesadez, me obligo a hacer cosas, como
   practicar las palabras, o leer, pero lo mismo estoy muy pesado.
   [2021-09-22 Wed] mucha soñolencia hoy, a pesar de estar durmiendo facil 
   unas 10hs por noche. Y hoy me dormi una siesta aparte, pero en ciertos 
   momentos tuve soñolencia a pesar de varios cafes que me tomo en el dia.
** [2021-09-19 Sun] arritmia dific. respiratoria
   hago las series con dificultad y me agito mucho, y quedo en arritmia unos
   segundos. Aunque la tension me da bien (11/8) y el oximetro (95) tambien.
   [2021-09-20 Mon] es como que luego de la primera actividad de la mañana
   quedo extenuado, sin aire. Luego me parecia que no podia permanecer en pie.
   Y tome las pastillas, con cierta dificultad. Pero luego cuando barri la 
   habitacion no quede tan extenuado, casi que ya me iba animando a mas.
   Tener en cuenta que dormi casi 10 horas, y llevo acostado 12hs, y me 
   levanto y ahi nomas hago las series. 
   [2021-09-21 Tue] ni ayer con los 10minutos de bici, ni esta mañana senti el 
   problema respiratorio de ayer.
   [2021-09-22 Wed] idem hoy, hice las series normal, con dificultad solamente 
   por el esfuerzo en alguna parte de la serie final, pero nada que ver con 
   anteayer. Los doce minutos de bici, los hago sin ningun tipo de molestia 
   cardiaca ni durante ni despues de la actividad.
   [2021-09-23 Thu] molestias anoche para dormir, pienso que por la cena, pero 
   nada mas

** [2021-09-20 Mon] hernia
   me molesto un poco ayer y hoy.
   [2021-09-21 Tue] anoche me molesto mucho y me puse el bolero y eso lo 
   contuvo un poco. De vez en cuando me da como una puntada pero nada muy 
   doloroso. Recien sin darme cuenta hice fuerza sacando al patio tres macetas 
   moderadamente pesadas y no senti ningun dolor ni problema.
   [2021-09-22 Wed] ya desde anoche no use el bolero y no senti mayormente 
   molestias. Hoy uso un boxer elastizado y veo.
   Molestias menores que las de ayer, esporadicas, pero trascurre el dia sin 
   bolero.
   [2021-09-23 Thu] cero molestias

** [2021-09-28 Tue] mareo
   estando en la compu normal, senti un movimiento de sillon lateral como si 
   fuera un temblor, me levante a ver a SAnchez si se movia, y no, luego me 
   senti mareado como vertigoso como unos 10 minutos.

** [2021-09-28 Tue] malestar a la toma del migral
   hace rato que siento malestar general a la toma del migral, o sea a veces 
   trato de esperar para no tomar al vicio o con demasiada antelacion, pero me 
   refiero a los malestares extra-migrañosos que siento al tomar el migral, 
   siento como que la cabeza se me vacia o se me llena de aire o me mareara. 
   Es un malestar que dura un rato y luego se va. A veces me tomo la tension y 
   la tengo normal. (como ahora 12.3/7.8). 
** [2021-09-28 Tue] brumosidad en el muslo izquierdo
   siento en el muslo izq a la altura del bolsillo un temblor como si fuera el 
   celu pero no tengo el celu es muscular como si fuera una vena tapada y 
   hubiera rumorosidad.
   [2021-09-29 Wed] acostado no senti el sintoma, pero al llegar al hora de 
   levantarme vuelvo a sentirlo. No es constante. 
   [2021-09-30 Thu] hoy que fui al hp dispuesto a hacerme ver y
   comence la cortiterapia no senti nada mas en ese tema.
** [2021-09-29 Wed] tensiones durante el dormir
   esta madrugada me desperte muy tensionado, y me obligue a relajar y pude 
   seguir durmiendo confortablemente.
* cortiterapia 2021
  UM: [2021-09-29 Wed] 16hs

** Comentarios:
   decido implementar la prescripcion del 2019, o sea 12 dias de 20mg
   a las 8hs y topiramato+silbelium, y migral de rescate si hace
   falta.

    
** [2021-09-30 Thu] 8hs 20mg
    tome un paracetamol 1gr a las 14hs. Mucho dolor de cintura, cadera y de hombros 
    menos, dolor oseo, tipico del corticoide. E incipiente dolor de cabeza.
    por la siesta y tarde el dolor de cabeza se hizo presente en forma
    mas o menos constante y molesta pero sin ser muy fuerte, pude
    dormitar mientras atendia fabian, y luego no pude dormir muy bien
    una siesta.
    Cuando me puse a leer el dolor parecia estacionarse o estancarse y
    luego de un rato largo de estar leyendo se fue. Luego cene y me
    puse bien. Mientras que antes estaba esperando que se hagan las
    20hs para tomar la otra dosis, cuando las 20hs llego no me dolia
    nada y decidi no tomar la segunda dosis y me dormi a las
    22hs. Dormi bastante normal, no bien, ni mal.
    Desperte con dolor articular de mandibula que se fue al ratito de
    levantado.
** [2021-10-01 Fri] 7hs 20mg
    Luego de las actividades por hora y media de la salida de ih de
    viaje no me dolio nada ese dolor de base que tenia cuando estaba
    despertando.
