* 2021
** Agosto
*** [2021-08-19 Thu]
    Hoy abro este nuevo archivo continuador de ali.org en un formato
    nuevo multiproposito y multiregistro.
*** [2021-08-23 Mon] 
    hoy es el primer dia de estar solo en la mañana pq ih se fue a
    trabajar con el Fede, y eso me produce una sensacion rara, por una
    parte me permite mayor concentracion, por otra me da una sensacion
    de vacuidad o sea el pensar que lo que yo hago no tiene sentido,
    que es todo banal y ahora se nota mas. 
*** [2021-08-24 Tue]    
    se puede decir que si que me afecta en cierta forma que salgan a
    trabajar ellos dos y yo no haga nada y eso me afecta en la
    capacidad de concentracion. O en la motivacion. 
** Setiembre
*** [2021-09-09 Thu]
    hoy es el segundo dia de arroz yamani con amaranto y esta vez le
    puse un sofrito de cebollita de verdeo que le dio sabor pero me
    hizo un poquito pesado pero sin caerme mal como la comida normal,
    o sea sin acidez y sin problemas digestivos y eso que
    lamentablemente la comi apurado, no se pq, quizas tenia mucho
    hambre.
    pienso que si desayuno dos huevos con cebolla, y almuerzo arroz, y
    ceno alguna otra cosa que no me haga mal, puedo mejorar un poco el
    estomago.
*** [2021-09-10 Fri]
    hoy desayune mijo con pasas de uva y manzana cruda, medio plato,
    bien sin acidez pero me duele un poquito la panza, no se si debido
    al mijo o que me senti demasiado mal desde anoche por la ingesta
    de sandwich con glutamato que no me dejaron dormir. 
*** [2021-09-13 Mon]
    me siento con mucho bajon y mucho sueño, ya llevo dos migrales y
    no me siento muy bien. Lo peor que no tengo ganas de hacer
    nada. Nada en ningun sentido de la palabra. 
    encima unos pocos minihabitos alimentarios que habia iniciado se
    ven interrumpido pq estoy en asistencia a ih y no puedo hacerlo
    por ahora. Pero eso no tiene nada que ver con el hecho de que no
    tengo voluntad para nada.
*** [2021-09-15 Wed]
    mucho sueño ayer y hoy, me cuesta levantarme a las 9, tengo que
    dormirme una siesta y estoy soñolento

*** [2021-09-19 Sun]
    tengo una situacion catastrofica, me duele la rodilla izquierda, tengo
    sensacion de falta de aire y arritmia, me cuesta hacer las series a la 
    mañana, no duermo bien. 
    Aparte estoy estancado en lo que hago, no programo, el ingles esta estan-
    cado, la lectura esta para atras, y estoy monotematico, o sea no puedo ver
    ni disfrutar nada que no sea lo que estoy haciendo de rutina.
    Una idea es hacer un cambio de rumbo general basado en alimento y en acti-
    vidad y salida.
    Para hacerlo sencillo:
    1. rutina diaria aunque sea minima de bici fija
    2. rutina diaria de mijo/yamani/frutas/verduras para cambiar el estomago
    3. salir a comprar lo necesario ya sea a la dietetica como a la verduleria

*** [2021-09-20 Mon]
    anoche dormi un poco mejor pero mucho. y ahi puedo quizas explicar la 
    falta de aire del ejercicio de la mañana.
    el problema principal que manejo es el no saber que hacer, o sea tengo mis 
    rutinas para levantarme, hasta que llega el momento de sentarse en la 
    compu y alli no se sabe que hacer. Todo pq he acomododado muchas cosas 
    para hacer acostado (p.e. leer en la tablet, buscar palabras para activar 
    una leccion, incluso practicar palabras, o escuchar un video) y el 
    problema es que estoy llegando a la cama y no lo hago, entonces me siento 
    doblemente mal, o sea no "hice" nada en la compu y no hago nada en la 
    practica en la cama, por eso lo de los quantums de cosas que pueden ser 
    hechas de dia en la compu para mantenerme levantado cosa de no caer en la 
    cama ni en la desesperanza y a la vez cuando vaya a la cama este mas 
    motivado y haga la practica aunque sea basica.
    Mucho lo que me desmotiva es lo laboral, pero no nos va tan mal 
    relativamente, y la llave para que nos vaya mejor esta en que se forme el 
    segundo grupo con Fede, no que abramos una oficina. Creo que la 
    administracion del sistema y los papeles, y atender a Fabian es mi tarea.
    Tengo que pensar como administrarme bien en los proximos diez años para 
    que en los años siguientes a ello podamos sobrevivir.
    Por el momento debo sobrevivir animicamente y fisicamente el momento 
    critico actual.
*** [2021-09-21 Tue]
    pienso que si yo estoy en crisis laboral, Fede esta en doble crisis 
    laboral, pq el es joven y necesita que esto arranque de una manera 
    diferente. Que avance y se queda durmiendo.

*** [2021-09-22 Wed]
    Tengo una guia basica de habits para hacer, que voy cumpliendo con el 
    incentivo que te da el llevar la cuenta en la app. Los mas dificiles son 
    los alimentarios el mijo del desayuno y el arroz del mediodia, y la bici. 
    Pero si lo analizas nada es cosa del otro mundo, y correctamente motivado 
    los haces.
    Luego con respecto a mantenerse levantado y no echado, haciendo cosas en 
    la compu, ayer por lo menos me ha funcionado el concepto de los quantums, 
    al menos ha transcurrido el dia y solo me eche a la tarde pasada las seis.
    Hoy hice la tercera sesion de bici y eso es lo mas importante, pq el 
    movimiento es lo que me faltaba o estaba en grave falencia. Mas alla de la 
    cronicidad del migral, o de otros deterioros generales, era imperativo 
    empezar una rutina de movilidad que me lleve a un registro perceptible en 
    algun plazo futuro.
    Es feo lo que pasa aca en la casa, ih tiene frustraciones y se las agarra 
    conmigo pq piensa que yo quiero sacarla de la casa. Y nada que ver me da 
    lo mismo pero me pone mal que el Fede no reaccione y no salga a trabajar, 
    vuelvo a pensar lo mismo que los ultimos meses, es como si esperara que yo 
    tome la delantera en algun tipo de esquema de trabajo, mientras tanto el 
    no tiene iniciativa para nada.

*** [2021-09-23 Thu]
    el gran problema de hoy es el trabajo que esta en situacion peligrosa pq 
    el Fede no trabaja o sea no aporta extra, pero principalmente pq gasta de 
    mas, y eso estresa la economia.
    Eso hace el panorama mas incierto pq hace peligrar la fuente de ingresos.
    Pero no voy a caer en la preocupacion.

*** [2021-09-24 Fri] charla con Fede estado de la Empresa
    hoy tuve una muy fecunda y efectiva charla con el Fede, una toma de 
    conciencia total de que no es que estemos fundidos, sino que estamos en la 
    cornisa, pq no tenemos ahorro, y no ganamos lo suficiente.
    Esperemos que esto lo motive a cambiar y a arrancar lo suficiente.
    [2021-09-28 Tue] arranco el lunes a duras penas y a pesar de que vendieron 
    bastante bien, el martes ya echo el faltaso.
** Octubre
*** [2021-10-01 Fri]
    hoy por hoy lo mas importante es sacar adelante la cortyterapia o
    mas bien el withdrall. Estoy bastante asustado por los efectos que
    me puede causar el migral, y no quiero tomar mas migral en forma
    desenfrenada como hasta ahora.
*** [2021-10-02 Sat]
    desafortunadamente a pesar de que los dos ultimos withdrall los
    curse con emacs-orgmode no tengo un registro claro al cual acudir
    como el que estoy haciendo ahora.
*** [2021-10-04 Mon]
    hoy me levante temprano y bien, fui a pagar las boletas, la lleve
    a ih, y luego pase los asientos de la tarjeta, delibere sobre irme
    a la pieza y conclui que no puedo por el tema debian-wifi, y probe
    un sistema de hacer todo la parte js de un html por separado y no
    funciono en forma facil y clara, son las doce y aca estoy.
    almorce y la lleve a la Romi al cerro, muchisimo transito, y luego
    las lleve a las chicas al Fede. Decidi descansar un poco. Al menos
    acostarme a leer un poco.
*** [2021-10-09 Sat]
    tengo muchos conflictos existenciales que derivan en caidas de
    animo, luego cuando tenes un chispaso como el de esta tarde te
    pones de otro animo o pensas que podes lograr otras cosas, por mas
    que la meta este muy lejana. Me refiero a que me sente a las 5 y
    ya son las 8.30 casi y estoy en la maquina, con sus
    correspondientes descansos logicos, y programe y practique ingles
    y escribi un poco y todo bien. 
    El tema es si "el estudio" me aleja o acerca a una normalizacion,
    o sea ha sido un factor que ha ocupado mucho mi mente ultimamente
    y me ha sacado muchos pensamientos negativos. Un poco me frustra
    la falta de avance en la cantidad de tiempo dedicada y/o absorvida
    en el tema cosa que me parece el mayor problema. Como el gran
    problema de la mañana cuando terminas la rutina de levantarte y te
    sentas a la maquina y no tenes ganas de hacer nada, tiene que
    haber algo que rompa esa rutina y te haga empezar con algo util.
*** [2021-10-11 Mon]
    no considero que esta forma de vivir y [no] trabajar sea mala pq
    trato de hacer cosas que me mejoren y me mantengan mentalmente
    activo. 
    En particular estos diez dias he atravesado la cortyterapia en una
    forma totalmente desatendida en lo personal, pq ih ha estado
    doblemente comprometida, por su lesion y por su compromiso de ir
    todos los dias a cuidar los chicos, y ya pasaron los diez primeros
    dias y tengo que empezar la retirada, aunque visto como fue este
    WD es la parte mas facil, no siempre fue asi, y la toma de cy es
    complicada pq da sintomas dificiles como soñolencia y cansancio. 
    Ademas que me voy a preocupar yo si el que tiene que salir a
    vender es el Fede. Otra cosa mas que lo que hago no creo que pueda
    o tenga que hacer.
* arreglos habitacionales
  [2021-10-07 Thu] anoche se me ocurrieron varias cosas por hacer para
  ir limpiando y minimizando un poco.
** TODO ropa de invierno 
   separar la ropa de invierno usable en los esquemas actuales y esa
   poner en las cajas azules y hacer una bolsa de plastico sorpresa
   encintada correctamente y subirla al entrepiso. Ahi tambien iria el
   contenido de la caja de arriba del placard y los pantalones grandes
   que no uso.
** DONE libros - mesa de computacion
   poner la mesa de computacion en su sitio con los libros acomodados
   en la base, lo que permitira barrer y pasar la mopa cuando vengan
   los alacranes.
   Hecho [2021-10-07 Thu]. Se acomodaron los libros, quedan las
   maquinas arriba para su acomodo en su momento, pero es limpiable el
   sitio de otra manera.
** TODO computadoras
   o bien ponerlas en el entrepiso forradas con bolsa de plastico y
   encintada o arriba del placard en el lugar que deje la caja idem.
** TODO cajas arriba del placard
   las de computacion al entrepiso y la de recuerdos abajo del placard.
** TODO romper recibos y tirar
   tirar los recibos que saque al patio, puede ser mojandolos y
   poniendolos en bolsa un poco cada dia como hacia en el centro
** TODO escritorio de-cluttered
   desocupar el cajon de abajo de las boletas de pago, filtrar, tirar,
   nepakear, y guardar en el placard o en el entrepiso.
** TODO centro del placard papeles importantes
   revisar y acomodar esos papeles y guardar los importantes en el
   placard dejando libre esa parte para ropa.
** TODO acomodar el primer cajon del placard
** TODO purgar y reacomodar las cajas de chucherias
* registro de sintomas (explain)
** [2021-08-19 Thu] migraña
   tuve toda la tarde con dolor intermedio un dia con dos migrales uno
   a las 5am y uno a las 5pm, y a las 8pm me acuesto y a las 9pm el
   dolor era grande nivel 7 (impedia leer o cualquier actividad pero
   no era terrible, era posible dormirse), y dormi toda la noche con
   dolor, Me tome un 10mg tipo 10pm y recien mejore un poco a las 5am,
   y no estoy del todo bien.

** [2021-08-21 Sat] oido tapado
   desde ayer siento una sensacion de ruido, y hoy me puse gotas de
   cerumax y no me resultaron de alivio, no esta tapado como la otra
   vez pero siento molestias.
   [2021-08-23 Mon]
   la molestia siguio ayer un poco y me eche cerumax y no cambio nada,
   hoy lunes me eche cerumax temprano y luego ih me echo gotas oticas
   que entraron mas, y parece que lavaron un poco pero sigo sintiendo
   la sensacion. 
   [2021-08-24 Tue]
   no me puse gotas hoy, no siento tapon pero siento picor y molestias.
   sentia dolorcitos y me puse una gota de otosporin, y senti como si
   abriera algo, pero no pude estar tranquilo un rato para que hiciera
   efecto.
   Desde que me puse esa gota no me molesto mas parece.
** [2021-08-21 Sat] meteorismo
   Como y siento una sensacion de molestia en el estomago, distension
   y movimientos raros dentro, ruidos, sensacion que me viene un
   diarreion, pero voy al baño y solo son gases, muchos gases. Leyendo
   veo que es meteorismo. 
   [2021-08-22 Sun]
   pruebo desayunar mate cocido sin azucar y tostadas sin manteca ni
   dulce para evitar azucares y lacteos y ver la reaccion y por lo
   menos parece que las reacciones extremas descriptas antes no se dieron.
   [2021-08-23 Mon]
   ayer no senti la molestia explosiva, ruidosa y doliente que
   describia al principio. Hoy en el desayuno tampoco. Hasta ahora lo
   unico que deje fue el "licuado de avena cruda".
   Despues de comer me agarro un momentaneo dolor de "panza" y termine
   yendo al baño pensaba que era diarreico pero no. Al rato
   paso. (Comi pastel de papas con mucho pure recalentado, bastante
   caliente con un vaso grande de agua y comi apurado, despues del
   dolor me tome un boldo)
   [2021-08-24 Tue]
   hoy desayune mate cocido con torta y me olvide, pq no tuve ningun
   sintoma.
   merende tarde y me fui a acostar, pero un par de horas despues me
   dio hambre y tome un te con tres tostadas con queso. Me hicieron
   muy mal, me hicieron doler la panza toda la noche y mayormente eran
   gases.
** [2021-08-25 Wed] depresion
   hace un par de dias que me desaparecio la alegria por las mañanas,
   y me puse bajon. 
   es algo involuntario que no lo puedo manejar. 
   cuando fui a encargar los lentes pienso que anduve bien o actue
   bien, pero luego cuando estoy en la casa me decaigo.
   [2021-08-27 Fri]
   ayer senti que estuve mejor, aunque un poco beligerante con ih,
   quizas sea una reaccion pq ella este trabajando, pero la verdad que
   me gusta estar un par de horas solo.
   [2021-09-09 Thu]
   me cuesta levantarme y no me levanto con alegria como antes. Aunque
   la jornada luego mejoro bastante.
   [2021-09-22 Wed] 
   no digo que estoy alegre, pero tampoco estoy pesimiesta ni estoy triste, ni 
   estoy problematico, es mas estoy en el medio de una serie de minihabitos y 
   rutinas para cambiar el estado. En realidad veo que otros a mi alrededor 
   tienen problemas como ih que tiene problematicidades que las transmite a 
   los demas. 
** [2021-09-09 Thu] dolor rodilla izquierda
   empezo a molestar estando sentado, me puse la faja a media mañana y
   sigue molestando.
   [2021-09-21 Tue] desde ayer con la practica de la bici se ha acentuado el 
   dolor de la rodilla izquierda.
   [2021-09-22 Wed] a pesar del dolor que tuve ayer todo el dia, hice igual 
   bici, y durante la bici no me molesto, ni despues de la bici, que me saque 
   la faja. Sigue sin molestias incluso despues de la tercera sesion de bici.

** [2021-09-17 Fri] soñolencia
   el miercoles anote que tenia soñolencia, pero hoy es abuso, desde las 12hs del
   mediodia que tengo ganas de acostarme y no puedo pq me llama a cada rato Fabian
   me tome un cafe recargado y lo mismo tengo pesadez, me obligo a hacer cosas, como
   practicar las palabras, o leer, pero lo mismo estoy muy pesado.
   [2021-09-22 Wed] mucha soñolencia hoy, a pesar de estar durmiendo facil 
   unas 10hs por noche. Y hoy me dormi una siesta aparte, pero en ciertos 
   momentos tuve soñolencia a pesar de varios cafes que me tomo en el dia.
** [2021-09-19 Sun] arritmia dific. respiratoria
   hago las series con dificultad y me agito mucho, y quedo en arritmia unos
   segundos. Aunque la tension me da bien (11/8) y el oximetro (95) tambien.
   [2021-09-20 Mon] es como que luego de la primera actividad de la mañana
   quedo extenuado, sin aire. Luego me parecia que no podia permanecer en pie.
   Y tome las pastillas, con cierta dificultad. Pero luego cuando barri la 
   habitacion no quede tan extenuado, casi que ya me iba animando a mas.
   Tener en cuenta que dormi casi 10 horas, y llevo acostado 12hs, y me 
   levanto y ahi nomas hago las series. 
   [2021-09-21 Tue] ni ayer con los 10minutos de bici, ni esta mañana senti el 
   problema respiratorio de ayer.
   [2021-09-22 Wed] idem hoy, hice las series normal, con dificultad solamente 
   por el esfuerzo en alguna parte de la serie final, pero nada que ver con 
   anteayer. Los doce minutos de bici, los hago sin ningun tipo de molestia 
   cardiaca ni durante ni despues de la actividad.
   [2021-09-23 Thu] molestias anoche para dormir, pienso que por la cena, pero 
   nada mas

** [2021-09-20 Mon] hernia
   me molesto un poco ayer y hoy.
   [2021-09-21 Tue] anoche me molesto mucho y me puse el bolero y eso lo 
   contuvo un poco. De vez en cuando me da como una puntada pero nada muy 
   doloroso. Recien sin darme cuenta hice fuerza sacando al patio tres macetas 
   moderadamente pesadas y no senti ningun dolor ni problema.
   [2021-09-22 Wed] ya desde anoche no use el bolero y no senti mayormente 
   molestias. Hoy uso un boxer elastizado y veo.
   Molestias menores que las de ayer, esporadicas, pero trascurre el dia sin 
   bolero.
   [2021-09-23 Thu] cero molestias

** [2021-09-28 Tue] mareo
   estando en la compu normal, senti un movimiento de sillon lateral como si 
   fuera un temblor, me levante a ver a SAnchez si se movia, y no, luego me 
   senti mareado como vertigoso como unos 10 minutos.

** [2021-09-28 Tue] malestar a la toma del migral
   hace rato que siento malestar general a la toma del migral, o sea a veces 
   trato de esperar para no tomar al vicio o con demasiada antelacion, pero me 
   refiero a los malestares extra-migrañosos que siento al tomar el migral, 
   siento como que la cabeza se me vacia o se me llena de aire o me mareara. 
   Es un malestar que dura un rato y luego se va. A veces me tomo la tension y 
   la tengo normal. (como ahora 12.3/7.8). 
** [2021-09-28 Tue] brumosidad en el muslo izquierdo
   siento en el muslo izq a la altura del bolsillo un temblor como si fuera el 
   celu pero no tengo el celu es muscular como si fuera una vena tapada y 
   hubiera rumorosidad.
   [2021-09-29 Wed] acostado no senti el sintoma, pero al llegar al hora de 
   levantarme vuelvo a sentirlo. No es constante. 
   [2021-09-30 Thu] hoy que fui al hp dispuesto a hacerme ver y
   comence la cortiterapia no senti nada mas en ese tema.
** [2021-09-29 Wed] tensiones durante el dormir
   esta madrugada me desperte muy tensionado, y me obligue a relajar y pude 
   seguir durmiendo confortablemente.
** [2021-10-04 Mon] perdida de la voz
   siento como si hubiera esforzado la voz un monton y no pudiera
   hablar a volumen normal. 
** [2021-10-06 Wed] destellos de luz
   media mañana cuando estaba pasando los papeles no podia fijar la
   vista en la pantalla pq se me formaban aureolas muy pronunciadas
   romboides que me dificultaban la fijacion de la vista, tanto con
   lentes como sin lentes, me recuesto en oscuridad un rato, pq en el
   medio me llamo Fabian como tres veces, y al rato descubri que se
   habia ido, Habra durado una media hora.
   [2021-10-09 Sat] estando todavia acostado y sin haber visto
   pantalla todavia me empezo el destello en forma romboidal grande,
   duro unos minutos y se fue.
** [2021-10-10 Sun] mordida de lengua
   se producen con una dentellada violenta y unica sin relacion a lo
   que estas soñando, mas cerca de la hora de levantarse, en este caso
   a posteriori de tomar el corti y acostarme de nuevo. (Ya he tenido
   casos, ahora los voy a registrar)
** [2021-10-12 Tue] gases extremos
   gases extremos que se meten debajo del diafragma y no solo no te
   dejan dormir sino que te hacen doler, te oprimen y te obligan a
   pararte. La ultima vez que recuerdo me paso fue un año nuevo en
   herrera que se quedo el Rodri y habia comido una torta helada y me
   cayo malisimo y no podia estar. Aca me cayeron mal dos sandwiches
   de richione que habia jurado un dia olvidado ya que no iba a
   comerlos mas. Me tuve que tomar dos factor ag casi consecutivos
   pero lo mismo no me hizo ningun efecto inmediato.
   [2021-10-13 Wed] tambien tuve sintomas, y eso que habia cenado
   porotos negros con ensalada, tome un factor ag pero fue muchisimo
   menos que la noche anterior.
* cortiterapia 2021
  UM: [2021-09-29 Wed] 16hs

| Fecha            | Cy | Mig | Dur  | otros medicamentos            |   |
| [2021-09-30 Thu] | 20 | si  | 4hs  | paracetamol 1gr               |   |
| [2021-10-01 Fri] | 40 | si  | 13hs | naproxeno 500 / reliveran     |   |
| [2021-10-02 Sat] | 40 | si  | 8hs  | naproxeno 500 / clonazepan SL |   |
| [2021-10-03 Sun] | 40 | no  |      |                               |   |
| [2021-10-04 Mon] | 40 | si  | 4hs  | ibuprofeno 600                |   |
| [2021-10-05 Tue] | 40 | si  | 2hs  |                               |   |
| [2021-10-06 Wed] | 40 | si  | 2hs  |                               |   |
| [2021-10-07 Thu] | 40 |     |      |                               |   |
| [2021-10-08 Fri] | 40 | si  | 2hs  |                               |   |
| [2021-10-09 Sat] | 20 |     |      |                               |   |
| [2021-10-10 Sun] | 40 | si  | 4hs  |                               |   |
| [2021-10-11 Mon] | 20 |     |      |                               |   |
| [2021-10-12 Tue] | 20 |     |      |                               |   |
| [2021-10-13 Wed] | 20 | si  | 4hs  |                               |   |
| [2021-10-14 Thu] | 20 |     |      |                               |   |
| [2021-10-15 Fri] | 20 | si  | 1hs  |                               |   |
| [2021-10-16 Sat] | 20 |     |      |                               |   |
|                  |    |     |      |                               |   |
** Comentarios:
   decido implementar la prescripcion del 2019, o sea 12 dias de 20mg
   a las 8hs y topiramato+silbelium, y migral de rescate si hace
   falta.
   Cambio sobre la marcha, y decido agregar los 20mg de la tarde, y en
   lo posible evitar el migral de rescate por ahora.

    
** [2021-09-30 Thu] 8hs 20mg
   :Paracetamol:
    tome un paracetamol 1gr a las 14hs. Mucho dolor de cintura, cadera y de hombros 
    menos, dolor oseo, tipico del corticoide. E incipiente dolor de cabeza.
    por la siesta y tarde el dolor de cabeza se hizo presente en forma
    mas o menos constante y molesta pero sin ser muy fuerte, pude
    dormitar mientras atendia fabian, y luego no pude dormir muy bien
    una siesta.
    Cuando me puse a leer el dolor parecia estacionarse o estancarse y
    luego de un rato largo de estar leyendo se fue. Luego cene y me
    puse bien. Mientras que antes estaba esperando que se hagan las
    20hs para tomar la otra dosis, cuando las 20hs llego no me dolia
    nada y decidi no tomar la segunda dosis y me dormi a las
    22hs. Dormi bastante normal, no bien, ni mal.
    Desperte con dolor articular de mandibula que se fue al ratito de
    levantado.
** [2021-10-01 Fri] 7hs 20mg 18hs 20mg
   :Naproxeno:Paracetamol:Reliveran:Clonazepan:
    Luego de las actividades por hora y media de la salida de ih de
    viaje no me dolio nada ese dolor de base que tenia cuando estaba
    despertando.
    10hs tomo paracetamol 1 gr. Comienzo a sentir los dolores de cadera y una 
    incipiente migraña lateral izquierda en la frente por ahora de nivel muy 
    bajo.
    me quede reposo toda la mañana durmiendo mayormente y no se
    desarrollo ninguna migraña, me levante a almorzar y todo bien,
    pero estoy bastante flojito de fuerzas, en especial de fuerza de
    voluntad.
    Luego del almuerzo siguen leves molestias.
    Aguante hasta las cuatro que se fue Fabian alli ya senti molestias
    mas grandes y me acoste. La Romu me trajo naproxeno y me tome un
    naproxeno 500 que no me hizo ningun efecto.
    Se me fue desarrollando una migraña izquierda bien determinada
    pero soportable que al menos me dejaba dormir y no estaba
    acompañada de sintomas oseos. Pero si de nauseas, y tome 40 gotas
    de reliveran.
    Me levante unos minutos cuando vinieron los chicos y luego me
    acoste, y luego se fueron de la casa y me acoste bien, y no cene
    nada pq seguia la nausea, tome las pastillas de la noche y un poco
    de agua, y recien tipo 5am fue aflojando el dolor, quedando solo
    una resaca.
** [2021-10-02 Sat] 7hs 20mg 18hs 20mg
   :Naproxeno:Clonazepan:
   Me levanto a tomar el corticoide, y trato de quedarme levantado o
   sea de hacer toda la rutina del levantarse, no ir a tomarlo y
   acostarse de nuevo. La resaca parecia estar alli y no se iba y
   amenazaba con mas.
   Me fui a comprar pan con el auto. Barri toda la casa, y cuando iba
   a intentar hacer una tarea mas grande me di cuenta que el dolor
   habia aumentado ya. Me tome un naproxeno 500 que resulto inutil
   como el del dia anterior.
   Al principio parecia una jaqueca muy fuerte mas no una migraña bien
   determinada con preponderancia a un costado sino que abarcaba como
   una especie de banda toda la cabeza en derredor a la altura de la
   terminacion del cuero cabelludo, pero luego surgiron algunas notas
   del lado izquierdo no muy determinadas como ayer pero surgieron.
   Pude dormir felizmente todo el dia, desde las diez hasta las doce
   que me levante a comer y luego me tome un clonazepan SL para seguir
   durmiendo toda la siesta y dormi hasta las 18hs.
   A esta hora estoy casi sin dolor solo con una resaca a nivel
   izquierdo, pero quien sabe como puede evolucionar.
** [2021-10-03 Sun] 7.30hs 20mg 20hs 20mg
   dormi toda la noche sin dolor alguno, en forma totalmente normal.
   Ahora veremos al levantarme que tengo que pasar los papeles que pasa.
   Bueno todos los papeles pasados bien. son casi las 10hs y sigo
   bien, pero estoy muy cansado.
   El cansancio se me fue, fui al Fede y me volvi no por cansancio ni
   por dolor sino por el aburrimiento de siempre. Aca me acoste a leer
   y lei 3hs el tutorial, entre otras cosas. Luego no me podia
   dormir. Pero no me dolio nada de nada, ni tampoco durante la noche.
** [2021-10-04 Mon] 8hs 20mg 17hs 20mg
   :Ibuprofeno:
   me levanto optimo, con energia y optimismo sin dolores por el
   momento.
   estuve muy bien hasta las 15hs. La lleve a la Romi al cerro a
   buscar la tarjeta con un trafico intenso, quizas eso me causo mucho
   estres.
   Fui un rato al Fede despues. 
   Y se me desarrollo un dolor, tome un ibuprofeno que no me hizo
   ningun efecto y me dormi una siesta y como hacia las
   cinco era una migraña izquierda completa, adelante la toma del
   segundo y tome un te. 
   A la hora mas o menos estaba leyendo y puedo leer unas cuantas
   horas ya sin dolor el resto del dia.
** [2021-10-05 Tue] 8hs 20mg 17hs 20mg
   dormi bien anoche, sin dolor, y me costo levantarme pq tenia mas
   sueño que dias anteriores.
   iba a quedarme en la cama hasta las 9 pero decidi levantarme y
   empezar a pasar los papeles para luego ir al banco y poner al dia
   mis obligaciones.
   Equilibre el levantarme temprano con un mal desayuno con un cafe y
   tostadas con queso, y me fui al banco sacandome ya un peso de
   encima.
   pasando papeles siento cansansio general y un poco de soñolencia
   pero esa sensacion de que has dormido poco en la noche.
   Como sintoma de la cortyterapia pongo perdida de la voz.
   Haciendo una tarea rutinaria normal como colgar la ropa siento
   cansancio inusual, me voy a reposar un poquito. 
   tipo 14hs me comienza una migraña izq. y me tomo una SL y me duermo
   una siesta.
   Resulto muy leve y aunque adelante la toma del cort. no sufri
   demasiado ni tampoco a la noche.
** [2021-10-06 Wed] 8hs 20mg 17hs 20mg
   me levante tome y me acoste desayune mijo en la cama, y luego me
   dormi una hora y media mas. Me levante bien, aunque tengo una
   ligera molestia basica no llega a nada.
   Cuando me levantaba pensaba en una carencia de willpower, pero hice
   las series excepcionalmente energicas.
   la mañana transcurre bien, sin contar con el destello de luz, y
   despues de comer tipo 13hs comienza de a poco la jaqueca.
   Lo mismo lleve a ih al Fede, y al volver me puse a la compu estas
   dos horas estudiando quebrando asi la falta de willpower, pero ya
   me duele un poco mas.
   dormi un poco la siesta, tome adelantado el segundo y luego me puse
   a leer hasta las 20hs que fui a cenar al Fede.
** [2021-10-07 Thu] 8.30hs 20mg 16hs 20mg
   dormi normal anoche y me levanto bien de energia y animos, en el
   trasfondo parece que tuviera una molestia pero no pasa a mayor por
   ahora.
   el mismo proceso que los ultimos dias, una jaqueca tardera que se
   va acumulando a estas horas a veces antes a veces despues, no muy
   fuerte pero te impide el estudio, en especial si es intenso. A las
   16.30 que termine el segundo pomodoro python, la lleve a ih a la
   nevi a que vendiera sus cosas, y luego compre pan y otras cosas,
   pero termine con dolor de cabeza.
** [2021-10-08 Fri] 8hs 20mg 16hs 20mg
   bien en general solo con una ligera molestia que no perturba la
   lectura ni nada pero esta ahi. Lo mismo ayer me pase la tarde-noche
   acostado mas en plan de vago-lectura que otra cosa. 
   muy vago hoy, quizas influyera el ambiente de dia feriado, que me
   levante a las 10.30hs, que tenia sueño a las 12hs etc. La cosa que
   me dormi la siesta un hora y pico y me desperte al borde de las
   16hs con jaqueca, y "tenia la dosis por delante", no me volvi a
   dormir sino que practique anki y lei un capitulo de js, y se me fue
   el dolor, la pregunta es si hubiera pasado igual sin dosis, y que
   pasara dentro de dos dias cuando ya baje la dosis.
** [2021-10-09 Sat] 7.30hs 20mg
   dormi bien anoche a pesar de la preocupacion y luego del corti
   dormi bastante. Me agarro un destello que se fue a los diez
   minutos. y me levante bien.
   Estoy tratando de ver que pasa hasta donde se puede llegar a
   manifestar si se manifiesta dolor y que relacion tiene con la
   segunda dosis.
   Al final transcurrio tarde noche y no tome segunda dosis, y
   desperte bien.
** [2021-10-10 Sun] 8hs 20mg 16hs 20mg
   me levante muy contracturado para hacer las series pq dormi hasta
   muy tarde, las 10.30hs. Pero bien. 
   comi a las 13hs y luego una siesta pero ya se adelantaba un dolor
   basico pero molesto, como el dia no es tranquilo, le puse la
   segunda dosis, y me quede levantado y cambiado, paso una hora y
   solo quedo estacionario.
   Sin hacerle mas caso al dolor, fui al Fede y me quede hasta la
   noche y el dolor se termino olvidando practicamente.
** [2021-10-11 Mon] 8hs 20mg
   me fui a dormir luego del corti pq es feriado, sin culpa y dormi
   hasta las 10.30hs pesadisimo dificil de levantarme, hinchado, pero
   sin dolor al menos hasta ahora.
** [2021-10-12 Tue] 7hs 20mg
   hoy adelante la toma del ct pq ya creia que me empezaba el dolor
   luego de una noche de mucho malestar por gases. 
   por suerte no me duele la cabeza por el momento pero tengo/tuve
   esta mañana mucho mal humor o enojo y mucha vagancia no solo ganas
   de dormir la siesta sino ni siquiera de leer en la cama.
** [2021-10-13 Wed] 7.30hs 20mg
   me levanto bien, un poco dormi muy recortado, pq nuevamente tuve
   sintoma de gases, y me dormi luego de la toma del ct.
   dolor incipiente a moderado-bajo, por el momento puedo seguir en la
   compu en actividad esperando el milagro que se me pase.
   como a las 18hs prendi de nuevo la compu pq estaba Fede y se puso
   aburrido y me entretuve instalando i3 y luego programando en vscode
   y se me fue yendo bastante el dolor de base.
** [2021-10-14 Thu] 7hs 20mg
   dormi bien y me levante bien.
** [2021-10-15 Fri] 7hs 20mg
   dormi bien y me levante bien.

   despues del mediodia se me desarrollo un dolor bastante incipiente
   que pensaba me iba a tirar a la cama despues de las 4 de la tarde y
   pense en tomar un naproxeno, y me dije que no que si se me iba el
   dolor lo iba a atribuir falsamente a la pastilla y si no se iba la
   toma era al vicio, y me acoste en "reparacion intensa" unos minutos
   y se me fue el dolor, luego de haber comido un poco de mijo.
** [2021-10-16 Sat] 7hs 20mg
   dormi con un ligero dolor toda la noche. Ya al levantarme desaparecio.
