* TODO [2019-10-01 mar] segmentacion fault en rbospg.tcl
sospecha de que el no cerrar la coneccion antes de cerrar la ventana
hace el core dumped fault.
No le afecta en nada.
Separando la carga de un tree y haciendo que se cargue a demanda hago
que que no todas las aperturas den fault.
Lo llamativo es que buscador tiene tree y no da fault.
y rbos dan fault ambas tree tanto la de zona como la de asientos.
en buscadorpg abriendo individualmente los pivot devolucion no da
problemas pero si se abren los tres juntos se rompe y son pivots
simples.

* DONE [2019-10-01 mar] algo me borra la tabla cuotas 
- State "DONE"       from "TODO"       [2019-10-02 mié 10:42]
era un drop table cuotas en buscadorpg.tcl que lo usaba en un proc
generarcuotas, podria usar cualquier otro nombre y uso ese borrandome
mi tabla cuotas.
* TODO [2019-10-03 jue] problemas con pivots que involucran columnas fecha o index agrupados por fecha
basicamente no me sirve pq no se produce la consulta ya que pg no
procesa la consulta pq el campo fecha no esta en la clausula group by,
y no puedo ponerla al lado del index pq no genera un pivot en forma
adecuada.
Tendre que investigar pivots en postgres de otra forma.
no parece haber buenas chances en pivots de postgres y menos obtener
la riqueza de opciones que tengo con sqlite. quizas me convenga hacer
un traspaso de datos postgres/sqlite y calcular el pivot localmente.
** solucion via transformpgsql
ya tengo el proc para pasar un sel en un segundo a una base memory db
de ahi puedo usar esa tabla ya como la temp table del pivot de sqlite
y dibujarla como pivot tradicional sin muchas variantes.
