* diario
** [2019-06-21 vie] inicio de estudio de php con videos
desde cero
** [2019-06-26 mié] forms conectado a cloud para insersion y busqueda con tabla
*** funciona la conexion a cloud
solo cambio la ip de fibertel en el dpto y por eso no abria
*** formularios basicos y de buen aspecto logrados
al menos los controles basicos en una grilla de tabla se puede lograr
*** forms y tabla juntos
forms para submit y tabla debajo de repuesta, cosa de hacer un select
por ejemplo y que salgan los datos en la tabla
*** detalles css en la tabla
**** border-collapse: collapse;
**** border: 1px solid black;
**** tr:nth-child(odd){background:bisque}
para el efecto stripebackground
**** padding: 5px;
**** th {text-align: left;} 
para alinear el encabezado a la izquierda
*** detalles html de tabla
**** encabezado
saque el encabezado por pg_ y con un array_keys obtuve los cols y
luego con un foreach arme el encabezado
*** igualacion de mysql=pg 
siguiendo el curso y practicando con mi propia base de datos y
haciendo todo en pg. 
** [2019-06-27 jue] inicio javascript
hoy inicie con todo (un poco anoche) el estudio de javascript. para
mezclar un poco y desaburrirme del punto a donde habia llegado y para
ir teniendo mas herramientas de desarrollo de lo que voy a ir
necesitando para armar lo que necesito. pq creo que la conexion php-pg
no es mucho mas que lo visto pero falta la interface y eso es mas
html/css/js/boostrap. Por eso creo que js es fundamental. Hasta ahora
todo ok pq es aburridamente igual a php, pero ya empezamos a ver eventos
*** eventos de raton sobre botones
onclick p.e. onmouseover
*** regreso a visual studio code como entorno de programacion.
** [2019-06-29 sáb] comienzo a ver jquery
luego de la frustracion que el viernes no se aprovecho casi por el
caos aca (me vine a las 14hs del centro y entre ir a ver el lote y
retirar los sillones, el partido y el caos que habia aca no hubo
tiempo de estudiar). Hoy sabado un poco de confusion, por no saber por
donde seguirle a javascript. Y decidi seguirle un poco a pildoras todo
lo mas que pueda, en especial que tiene unos diez videos de jquery que
comence hoy y unos diez de formularios. Y luego ir redondeando yo
mismo buscando otros cursos y otros materiales. 
Creo que vamos avanzando pq con los cursos por video por lo menos se
va escribiendo codigo y se va practicando con la maquina a diferencia
de la lectura.
creo que el estado de frustracion continuo que se experimenta pq
parece que lo que se avanza es poco y no va a servir para nada se va a
ir disipando con el tiempo. cuando lleve un par de meses de estudio
puro de videos creo que ya aprendere lo suficiente como para producir
algun resultado visible.
El tema es seguir siendo capaz de lograr dominar esos temas. 
* doc
** constantes
van en mayusculas sin signo delante y no se pueden cambiar de valor.
son globales en su ambito.
se definen con la funcion define
define() tiene tres argumentos, el nombre de la constante entre
comillas, el valor, y un tercero opcional que es case insensitive.
