* Plurals:
three bananas
two newspapers
four girls
two telephones
three cameras
six spoons
four pencils
three birds
four chairs
three cups

** words ending in consonants + y: change y + es

One baby -> two babies

** Words ending in ch, x, sh, ss, s: add es.

a match -> two matches
a box   -> two boxes
a brush -> two brushes
a glass -> two glasses
a bus   -> two buses

** Words ending en o

a potato -> two potatoes
a tomato -> two tomatoes

** Irregular plural

a man  two men
a woman two women
a child two children
a person two people
a foot two feet
a tooth two teeth


Practice
lorries
waitresses
secretaries
sandwiches
children
matches
flowers
vegetables
families
dictionaries
eyes
bags
boxes
schools
lunches
cities
hotels
watches
animals
flies
buses
men
oranges
people
churches
eggs
apples
days
boys
glasses
dishes
beaches
dresses
feet

* Articles: a before consonant and an before vocal

Are you a student?
Britain is an island.
They're at a restaurant.
He's a waiter.
It's an ugly house.
Here's a ticket for the play.
He's a gook worker.
It's not an easy language.

* There is - There are

Is there a train to Manchester?
There's a new disco near the college.
Is there a good restaurant in this street?
There are two hospitals in town.
Are there a lot of children in the pool?
There are three families in that house.
Is there a television in the flat?
There's a big grey cloud over there.

* Subject/Object pronouns
Can you help us with these bags?
We usually see them at the weekend.
How did you teach him to read?
I write to her once a month.
He loved her very much be she didn't love him.
Why did you ask them to come? I don't like them.
I don't think she understands me.
Please don't wait for us.
Did they tell her the news?
Would you like to come with me?


I can't open this door. Could you open it for mi, please?
Those shoes are really nice. I'd like to buy them.
Did you see Jonathon last night? No, I phoned him but he wasn't there.
I can't do this homework. Can you help me?
I asked you a question but you didn't answer me.
We're not ready. Please give us some more time.
She speaks very quickly. I can't understand her.
I'm sorry about your birthday. I'm afraid I forgot about it.
Jill's a very nice woman. Do you know her?
My parent are coming this weekend. Would you like to meet them?
They're not married now. She left him a year ago.
'Where's your passport?' I don't know. I can't find it.
My mother writes to me every week but I don't write to her very often.
Were you at the meeting last night? I didn't see you there.
We want to help you. Please tell us about your problems.

* Adjectives:
usually come before nouns
can also come after the verb to be

1. The rooms are small. They're small rooms.
2. It's not a long story. The story's not long.
3. The children are happy. They're happy children.
4. It's a dirty restaurant. The restaurant is dirty.
5. The books are heavy. They're heavy books.
6. The house is cold. It's a cold house.
7. The village is quiet. It's a quiet village.
8. The clothes aren't cheap. They aren't cheap clothes.
9. The garden is pretty. It's a pretty garden.
10. The language is difficult. It's a difficult language.

** Possessive adjectives:
That's my daughter.
Is this your book?.
This is her office.
I've got their phone numbers.

1. Alison is doing her homework.
2. Do you live with your parents?
3. We love our new house.
4. He's in his office.
5. The children are with their grandmother.
6. I like MY new job.
7. Are you and you sister enjoying YOUR English class?
8. Amsterdam is famous for its canals.
9. She's with her boyfriend.
10. They haven't got their umbrellas.
11. She's in her bedroom.
12. He's looking for his shoes.
13. I like visiting MY friends at the weekend.
14. Are the teachers having their meeting now?
15. Have you got your passport?

** The possessive with 's

This is Derek's bike.
Anne's paintings are beautiful.
The doctor's surgery is in that street.
That's the cat's bowl.

After a singular name or noun, the possessive is always 's:
This is Sue's bag.
These are Sue's bags.

When the name is plural and ends in s, add ':
My parents' flat is quite small.
The girls' bedroom is upstairs.

When the name is plural but does no end in s, add 's:
The children's coats are here.
The men's toilets are closed.
Emma and Paul's car is outside.

We also use 's with time words:
A week's holiday, today's weather, yesterday's newspaper
And we use s' with plural time words:
Two weeks' holiday

1. These are Anne's books.
2. Where is Andrew's coat?
3. Is that your brother's car?
4. It's on the teacher's desk.
5. The dog's dinner is here.
6. Judy's children are at school now.
7. It's my wife's idea.
8. That bird's leg is broken.
9. Jeff's new bike is really good.
10. Here's the doctor's telephone number.

1. These are Susan's keys.
2. I like your husband's haircut.
3. Those are Robert and Sarah's children
4. There is a teacher's meeting on Mondays.
5. Are the children's coats in the car?
6. The men's clothes are upstairs.
7. Alice's mother is very ill.
8. We have a month's holiday in the summer.
9. The students' exams start next week.
10. This is my mother's dress.

** Other possessives

The bank is at the end of the road.
There is a cafe at the top of the hill.

Possession for things: noun + of + noun.

After the front, back, side, top, bottom, end, beginning, we always
use of + noun.

It's in the front of the car.
NOT It's in the car front.

Have you got the car keys?
Can you close the bathroom door?

With common nouns (e.g. car, school, town, garden, kitchen, bedroom, sea,
country, hotel) of is not necessary. We usually say the bathroom door and NOT
the door "of" the bathroom.

1. Have you got my car keys?
2. There's a chair at the top of the garden.
3. Can you close the bedroom window?.
4. The money is in my hotel room.
5. I met Sarah at the school gates.
6. They live at the bottom of hill.
7. There's an old tree at the side of house.
8. Where's the bathroom light?
9. We always meet at the town clock.
10. The sea air is very good for you.


* This, that, these, those: demonstrative adjectives and pronouns:

This book is really good.
That house is beautiful.
These chips are cold.
What are those bird?

This is my mother.
That's the bathroom.
These are my cases.
Those are my glasses.

This is singular. It is used with something that is here, next to the speaker.
That is singular. It is used with something that is there, no next to the
speaker. Perhaps the speaker is looking at it or pointing to it.

These is plural. It is used with things that are here, next to the speaker.
Those is plural. It is used with things that are there, not next to the speaker.


* Taller than...: comparative adjectives with er:

Pam is taller than Helen.
Pam's hair is longer than Helen's.
Helen's heavier than Pam.
Helen's stronger than Pam.

USE:
To compare two things:

FORM:
One-syllable adjectives add er
adjective + er:
old -> older
tall -> taller

Two-syllable adjectives ending in y, change y -> i and add er.
Happy -> happier
easy -> easier

When a one-syllable adjective ends with a vowel and a consonant, double
the consonant before er.
Big -> bigger
fat -> fatter
thin -> thinner
For adjectives ending in e, add r.
nice -> nicer

Irregular comparative adjectives:
good -> better
bad -> worse

10a
fast faster
easy easier
slow slower
strong stronger
dirty dirtier
small smaller
bad worse
happy happier
cold colder
fat fatter
thin thinner
nice nicer
heavy heavier
old older
big bigger
angry angrier
long longer
good better
clean cleaner
short shorter

10b
Vegetables are cheaper than meat.
This bag of potatoes is heavier than this bag of tomatoes.
Spain is colder than England.
This new car is faster than my old car.
Sarah is older than her brother.
The coast road to the town is longer than the mountain road.
Her bedtime is earlier than her older sister's.
My father is younger than my mother.

1. English is easier than Japanese.
2. Karen is shorter than her twelve-year-old son.
3. My suitcase is heavier than your suitcase.
4. My father is older than my mother.
5. Boats are slower than planes.
6. The Mississippi is longer than the Nile.
7. The Atlantic is colder than the Mediterranean.
8. Wool is warmer than cotton.
9. Trains are faster than buses.
10. The Empire State Building is taller the Statue of Liberty.

* Verbs
** am, is, are: Present Simple tense of verb to be
We can always use the positive short form after pronouns (I'm, you're, she's,
he's, it's, you're, we're, they're) but we cannot always use it after nouns.

11a
1. It is a lovely day. It's a lovely day.
2. We are not students. We aren't students.
3. I am sorry. I'm sorry.
4. She is not here today. She isn't here today.
5. They are in the garden. They're in the garden.
6. It is not very warm. It isn't very warm.
7. He is American. He's American.
8. I am not very well. I'm not very well.
9. You are very cold. You're very cold.
10. We are late. We're late.

11b.
1. She is in my class.
2. They are not in my office.
3. I am from Spain.
4. He is a good teacher.
5. How are you?
6. Is she coming?
7. Are they at home?
8. The book is here.
9. The class is very big.
10. The books are on my desk.
11. My sister and I are leaving.
12. I is not my pen.
13. Is English very difficult?
14. Am I right?


** 12 has, have got

Possession:
She's got three cats.
Have you got a car?
We've got three children.
He hasn't got many friends.

Illnesses:
I've got a bad cold.
Has he got a headache?

Descriptions:
He's got brown hair, blue eyes and long nose.

We can also use "have" for possession:
They have a big house.
Do you have a job?
I don't have enough money.

But in British English have got is more common than have for possession.

12a
1. She's got a beautiful bedroom.
2. You've got a very nice bike.
3. He's got very long hair.
4. They've got two houses.
5. David's got a bad foot.
6. We've got a lot of problems.
7. Sarah's got a new car.
8. I've got a terrible headache.
9. The dog's got a broken leg.
10. Alison's got a very good job.
11. He's got a lot of friends.
12. Julie's got a beautiful hair.

12b
1. Jill hasn't got a glass of water. Jenny's got a glass of water.
2. Jill's got a fork. Jenny hasn't got a fork.
3. Jill's got a napkin. Jenny hasn't got a napkin.
4. Jill hasn't got a menu. Jenny's got a menu.
5. Jill hasn't got a bag. Jenny's got a bag.
6. Jill's got a coat. Jenny hasn't got a coat.
7. Jill's got a lighter. Jenny hasn't got a lighter.
8. Jill's got a watch. Jenny hasn't got a watch.
9. Jill hasn't got a newspaper. Jenny's got a newspaper.
10. Jill hasn't got a ring. Jenny's got a ring.

12c
1. Have you got your swimming costume? Yes, I have.
2. Have you got your umbrella? No, I haven't.
3. Have you got your travel clock? Yes, I have.
4. Have you got your camera? No, I haven't.
5. Have you got your French phrase book? Yes, I have.
6. Have you got your passport? Yes. I have.
7. Have you got your address book? Yes, I have.
8. Have you got your ticket? Yes, I have.
9. Have you got your French francs? Yes, I have.
10. Have you got your sunglasses? No, I haven't.

12d
1. Has she got a sister? No she hasn't.
2. Have you got a telephone? Yes I have.
3. Have we got the tickets? Yes we have.
4. Has the town got a theatre? No it hasn't.
5. Has he got a job? No he hasn't.
6. Have your friends got some good music? Yes they have.
7. Have I got time for a cup of coffee? Yes you have.
8. Has your son got a cold? Yes he has.
9. Have they got a garden? No they haven't.
10. Have you got a good hotel room? Yes we have.

** 13 I walk to school: Present Simple tense: positive
   She, he, it add s to the verb.

   Verbs ending in sh, ch, ss, o or x, e.g. teach, wash, watch, go: add es
   to the verb after she, he, it.

   I/you/we/they teach. She/he/it teaches.

   Verbs ending in consonant + y, e.g carry, study, cry: change y->i and add es
   after she, he, it.

   I/you/we/they study. She/he studies.

*** USE
    1. To give a general description of a person or thing. Not for an activity
    happening now.
    2. With think, know, understand, agree, want (verbs that are not activities)
    3. With sometimes, often, always, usually, never, occasionally (adverbs of
    frequency). These adverbs usually go before the present simple verb:
    She often goes there.
    He doesn't often go there.
    Do you sometimes go there?.
    4. With repeated times, e.g. every Saturday, in the evening (=every evening),
    at 8 o'clock(= at 8 o'clock every day), in the summer( every summer ).

*** 13a
    1. Children ask a lot of questions.
    2. I love classical music.
    3. You always forget my birthday.
    4. She never listens to me.
    5. They usually drink coffee after their evening meal.
    6. I drive to work when the weather's cold.
    7. My parents usually come to our house on Sundays.
    8. They learn two languages at school.
    9. The village shop opens at 8 o'clock in the morning.
    10. We give her a diary every year.
    11. He often flights with his brother.
    12. You never help me with my homework.
    13. Big dogs like a lot of exercise.
    14. He understands Arabic.
    15. Lessons start at 9 o'clock every morning.

*** 13b
    1. She goes to college on her bike.
    2. A lot of birds fly south in the winter.
    3. She studies very hard at the weekends.
    4. My father watches television most evenings.
    5. I often cry at the cinema.
    6. She does a lot of homework in the evenings.
    7. A mother cat washes her kittens.
    8. You teach language very well.
    9. He carries the shopping for his grandmother.
    10. He's very naughty- he pushes other children.

*** 13c
    1. She always listens to the radio in the mornings.
    2. He takes the dog for a walk every day.
    3. She usually buys all the food.
    4. She teaches history and Latin.
    5. He walks to the office every day.
    6. She never washes the car.
    7. He opens the building every morning.
    8. He occasionally writes letters to my old school friend.
    9. He drinks a lot of tea with his breakfast.
    10. She watches the football on television every Saturday.

*** 13d
    1. Mr Pierre Moulin comes from France.
    2. He lives in Paris.
    3. He works in a shopping.
    4. He often paints and listens to music.
    5. He speaks some English and a litle Italian.

    1. Ms Deniz Ulgen comes from Turkey.
    2. She lives in Ankara.
    3. She works in a hotel.
    4. She often plays chess and goes to concerts.
    5. She speaks English and German.

    1. Ms Maria Protopapas comes from Greece.
    2. She lives in Athens.
    3. She works in a scholl.
    4. She often goes for a long walks and plays voleyball.
    5. She speaks fluent English and some Arabic.

** Presente Simple Tense: questions
   Form:
   Do I/you/we/they live...?
   Does he/she/it live...?

   Question form: do, does + subject + infinitive.
   There is no s at the end of the verb in questions:
   She lives...but Does she live...?

   Short answers:
   Yes, I/you/we/they do.
   No, I/you/we/they do not (don't).

   Yes, he/she/it does.
   No, he/she/it does not (doesn't).

*** 14a
    1 Does she live with her parents? Yes she does.
    2 Do you like your job? No I don't.
    3 Do I speak Italian well? Yes you do.
    4 Do you drive to work? No I don't.
    5 Do they work hard at university? Yes, they do.
    6 Does Alan smoke? No he doesn't.
    7 Does your sister visit you very often? Yes she does.
    8 Do we usually give her a birthday present? No we don't.
    9 Do you write to your parents very often? No I don't.
    10 Does he help you very much? Yes he does.

*** 14b
    1 The shop closes at 5 o'clock.
      Does the shop close at 5 o'clock?
    2 They go swimming every weekend.
      Do they go swimming every weekend?
    3 She speaks English well.
      Does she speak English well?
    4 It rains a lot here in winter.
      Does it rain a lot here in winter?
    5 You drink a lot of tea.
      Do you drink a lot of tea?
    6 I eat too much, doctor.
      Do I eat too much, doctor?
    7 Tony often plays golf at the weekends.
      Does Tony often play golf at the weekends?
    8 His friends visit him most evenings.
      Do his friends visit him most evenings?

*** 14c
    1 Where do you work?
    2 What does she do?
    3 Where does he live?
    4 What music does your husband like?
    5 When does she do her homework?
    6 Why do we learn Latin?
    7 Who does she teach?
    8 How do I turn on the television?

** Present Simple tense: negatives
   Form:
   I/you/we/they do not (don't) like...
   She/he/it does not (doesn't) like...

   Negative form: Subject + do not, does not + infinitive.
   Note: There is no s at the end of the verb in the negative:
   She likes ...but She doesn't like...

*** 15
    1 She works very hard.
      She doesn't work very hard.
    2 It usually snows here in the winter.
      It doesn't usually snow here in the winter.
    3 I like a big breakfast every morning.
      I don't like a big breakfast every morning.
    4 The film starts very early.
      The film doesn't start very early.
    5 He swims every morning.
      He doesn't swim every morning.
    6 They always open the windows at night.
      They don't always open the windows at night.
    7 We often see our neighbours in the garden.
      We don't often see our neighbours in the garden.
    8 Chris goes on holiday every year.
      Chris doesn't go on holiday every year.
    9 You drive very fast.
      You don't drive very fast.
    10 These young children learn very quickly.
       These young children don't learn very quickly.

*** 16a
    I work. I don't work. Do I work? Yes, I do. No, I don't.
    You work. You don't work. Do you work? Yes, you do. No, you don't.
    She works. She doesn't work. Does she work? Yes, she does. No, she doesn't.
    He works. He doesn't work. Does he work? Yes, he does. No, he doesn't.
    It works. It doesn't work. Does it work? Yes, it does. No, it doesn't.
    We work. We don't work. Do we work? Yes, we do. No, we don't.
    They work. We don't work. Do they work? Yes, they do. No, they don't.


