#+FILETAGS: proyecto minimalizacion
#+TODO: TODO(t) BUG IDEA IMPROV NEXT | DONE(d!) FIXED DESISTIDO



* Minimalizar la vida                                                 :title:
Hacer la vida mas simple, minimalista.
* Vision del proyecto                                                :vision:
El objetivo es lograr un nivel de mente vacia o mente limpia, porque
uno confia en un sistema de archivo y/o de organizacion en el cual va
volcando todas las ideas las va trabajando y va sacando las
next-actions para agendar. Y asi va avanzando. Pero no se pierde nada.
En este caso el proyecto sera como un meta-proyecto, en el cual el
objetivo seria limpiar o minimizar, como para no tener distintos
proyectos o muchos proyectos abiertos al mismo tiempo, la idea es
tener este que tenga como objetivo el descomplicar la vida.
* Justificacion del proyecto						:why:
* Brainstorming						      :brain:
** me quejo de la comida pero podria llevar licuado y comida sana a la oficina
podria volver a los licuados, tener una buena mochila, llevar fruta,
fruta seca, llevar arroz, en si podria hacer mucho por mi dieta
directamente.
Uno de los problemas mas graves que tengo seamos realistas es el pagar
o gastar en verdura/fruta en verdulerias hasta un punto casi
patologico que hace que esta temporada los primeros y unicos arandanos
que comi fueron unos que me dio ih hace dos semanas. Y yo estoy
gastando unos 1600 x mes en delivery y llegue a gastar 2400 y como muy
mal ese es el problema. Podria llevarme un par de frutas y diversas
cosas y hacerme un box de comidas atras como hice el otro dia.
Yo antes con licuado (dos botellas) y una bolsita de nueces tiraba
hasta las 16 que volvia a la cabaña sin necesidad de ningun tipo de
comida. Y ahora me podria llevar algo.
El problema nace aca en el dpto:
**** el desayuno:
inexistente pq ya perdi el licuado, pq no lo varie, pq no le puse
ingredientes. Y tampoco tengo un desayuno tradicional solido. Entonces
llego alla cagado de hambre y entonces a las 12 estoy desesperado por
el almuerzo pero luego me viene y no lo puedo comer bien, salvo excepciones.
**** las compras:


** me gustaria pasar los cuadernos a formato digital
no quiero perderlos pero tampoco quiero tenerlos asi para siempre.
Cuanto tiempo me daria para pasar las cosas.
Vale la pena pasar todas las cosas?
Eso es algo que tendria que considerar.
Quizas hacer una prueba de tiempo, o sea pasar un par de hojas y ver.
** tener el dpto minimalizado
eso basicamente seria que tenga seguridad nivel adecuado para
interactuar con alguien sin problemas (me da la sensacion que tengo
muchas cosas encima y justamente me gustaria ver si vale la pena
tenerlas o bien habria que tenerlas de otra forma)
*** caja fuerte
si o si el dpto tiene que tener caja fuerte. Esos fondos tienen que
estar en una caja oculta en un estante dificil de acceso con una
cajita fuerte. 
*** boletas de pagos
es caotico el tema boletas
** tener la oficina minimalizada
o sea apta para que otra persona este alli
*** caja fuerte
*** seguridad informatica
sobre el apartado seguridad informatica en general se plantea el
separar los escritos personales de los estrictamente personales, en
ese sentido p.e. salidamercaderia.org y bugs.org incluso
age-programacion.org y hasta documentacion.org todo puede estar en el
servidor  de desarrollo de la empresa, pero todos los otros org que
son personales tendrian que estar separados.
Considerar un par de dias manejar los orkblocks en pendrive. El
pendrive con luke es crytoseguro con una clave que es separada de la
familia es personal, es un espacio personal. Por lo tanto no hay
problema de ir y venir con un pendrive. y manejarse asi. Es una prueba
de todos modos. pq no voy a estar tranquilo con todos estos escritos.

*** stock contado
* Plan de accion						       :plan:
* Next Action							       :next:

