* proyecto de venta de PB desde oficina                             :ARCHIVE:
** idea venta PB con primer cuota
*** consideraciones teoricas
**** plan de negocios nuevo Pierre Balmain
algunos numeros:
de detvta globales con like *pierre*
| sum(costo) | delta | costo unitario |
|    1058660 |  3.17 | 314            |
|            |       |                |
de ventas
con like *pierre* y fecha< date('now','- 7 months') para que no salgan
los que estan pagando ahora y refleje los incobrables reales
| vendido |  saldo |  cnt | P.Unit | incobrabilidad |
| 3163642 | 213037 | 4095 |   772  |           6.7% |

O sea unos buenos numeros esta bien que casi todo a clientes, pero un
buen nivel.
Ahora esta visto que se le puede sacar un delta de 3.32 en la calle a
6x220 considerando el precio de shuby a 400 de costo.

El plan de negocios seria vender solo sabanas de lujo, basicamente pb
y el anexo queen y king y puro algodon 180 hilos para quien pida y
pague.

Todo bien logrado.

***
** Tema reparto
puede ser que entreguen ellos mismos o bien que reparta yo o a traves
de alguien independiente.
El tema es que para lograr un nivel optimo estariamos hablando de 400
sabanas mensuales o sea de 100 sabanas por semana. O sea 20 por dia.

Monica p.e. te puede repartir 3 o 4 sabanas por dia si se las llevas y
se las dejas en la casa. una vez por semana. Y asi podria tener un
sistema distribuido a traves de toda la geografia por medio de la cual
el cobrador lleve las sabanas en un ritmo adecuado y a un costo
adecuado.
(como era en el 2005)
p.e. coco liso va siempre a mosconi y puede llevar tres sabanas por
vez que va (las lleva en la mochila). Pq la sabana se venderia por
foto bien determinado el color por carpeta.  y con una mochila grande
te lleva tres o cuatro sabanas y a razon de 30 por unidad le conviene,
igual ramiro. Y asi con un grupo de cobradores te tengo repartido 20
sabanas por dia, que me las hago traer directamente a la oficina para
no renegar.

Ejemplo: 8 cobradores con sus respectivas mochilas a la mañana se
llevan 24 sabanas para repartir que les deja casi 100 mangos a cada
uno (guita nada despreciable) y conseguimos las siguientes ventajas:
****** no salgo de la oficina (no tengo que salir ni necesito auto, ni costo)
****** me hago traer la mercaderia por copar al local directamente
por lo cual no necesito depender del marques, puedo seguir viviendo en
el centro, puedo tener un auto nuevo, no necesito tener un auto de
reparto, no tengo limite a la gente que tenga etc.
****** puedo mandar a los promotores separadamente
eso les quita el efecto grupo, hace que los barrios se hagan mejor,
que no se quemen etc.
****** el cobrador entrega el mismo con su mochila
se gana unos pesos extras que no son pocos, supongamos en una magali
lo que incidiria unos 2000 mas, logramos que el cobrador vea la casa y
se responsabilice de lo que hace, pq el tendra que cobrar, hacemos que
el vendedor no sea el que entregue, cortamos ahi los fraudes, y a la
vez no complicamos el sistema con el vendedor sabiendo que los chicos
en su deseperacion echan moco.
****** el costo dentro de todo es reducido
pq es un monto fijo por venta que se carga a un trabajador que hace
otra cosa, si no se entrega vuelve con las cosas y tiene otro trabajo,
que es la cobranza. El riesgo de robo es acotado a esa mochila con 4,
3, 2 o 1 sabana o sea no es tanto y no hay gastos fijos, como los que
tendria yo si tengo que mover el auto. O poner un Fabian. Incluso el
costo tiempo tambien es menor, pq es una extension a la cobranza pq es
una precobranza.
****** pasaria a ser obligatorio para todo cobrador pq asi sera el sistema

**** primer cuota
***** idea de plan con primer cuota
ya que el reparto seria hecho con los cobradores en zonas fijas y esas
zonas se pueden abastecer en cualquier momento pq se visitan dia por
medio, incluso se puede determinar el dia que se visita dicha zona.
Se podria vender con primer cuota y no asi como vendemos, lo cual
incidiria mucho en la liberalidad con que venderiamos.
****** no es acaso lo mismo vender sin cuota
en cierta forma si, pero si vamos al caso podriamos usar un pedido
impreso por imprenta bien hecho, por duplicado con carbonico, numerado
con el cual comprometamos mejor y sea todo mas serio. Luego con la
secretaria podemos avisar por whatapp o sms que vamos a ir. 
El riesgo asumido baja de 400+125+30=555 a 555-220=335 o sea se hace
mucho mas potable. Y el promotor tiene el deber de asumir que esa
venta que esta haciendo no se va a caer pq en teoria lo que el esta
haciendo esta bien hecho. Y el tiene la obligacion de hacer bien las
cosas. 
****** posibilidad de vender delta 3
| costo |   33% |
| inc   |   10% |
| vta   |   10% |
| cobr  | 13.5% |
| total | 66.5% |
| NETO  | 33 %  |

precios probables
| pb1  | 150 |  900 |  90 |
| pb2  | 200 | 1200 | 120 |
| king | 250 | 1500 | 150 |
o sea que un promedio superior a 100 lo cual podria ser factible que
se aprobara una venta por articulo. Total es con primer cuota.
****** posibilidad de que los promotores rindieran al otro dia
eso brindaria menos desgaste en horario de la tarde. Algo que desgasta
mucho es la salida y la vuelta el mismo dia. Si vamos al caso el
embole del baño p.e. o la interrupcion continua en el trabajo o el
flujo de trabajo por el retorno escalonado de los promotores. Y en
cierta forma ya habia llegado a la conclusion de que no hacia falta la
vuelta desde el punto de vista motivacional sino que era solo pq
necesitabamos procesar los datos.
Pero en un sistema de venta con primer cuota en el cual la entrega se
cursa no al dia siguiente sino p.e. a los dos dias se puede entregar
el dato a la mañana siguiente y eso ahorraria un monton de tiempo. 
****** el vender sin primer cuota no hace falta para vender mas
en un esquema anexo de venta en el cual uno no tiene que vender para
vivir sino que debe buscar agregar clientes, no necesitamos tener un
sistema que sea facilongo pq paradojicamente termina siendo inutil
igual. Veamos: con este sistema que visto desde cualquier epoca es
recontrafacil con articulos de 125,145 pesos sin anticipo y variedad
de articulos, y entrega al dia siguiente en movil con vendedores con
seguimiento e insistencia, hay promotores que se vinieron abajo y
cayeron en la impotencia de no vender, casos rodolfo, maxi, walter,
miguel, el propio dario, y los que se fueron pq entraron con otras
expectativas o pensaron que era mas facil.
Entonces no vale la pena tener un sistema facil. Sino mas bien un
sistema que "parezca" facil. Pq al final los unicos perjudicados somos
nosotros.
Aca la clave es que no necesitamos la venta. 
*** proyecto
**** carpetas
***** impresora color
**** contrato
**** aviso
**** curso
**** pedido
***** diseno
***** imprenta
**** zonas
**** definicion de tareas con secretaria
**** adecuacion computadora extra oficina
***** seguridad
****** firewall -red
****** usb-storage
***** red
