* DONE cambios a .emacs
** DONE poner subir linea bajar linea
** DONE duplicate linea
** DONE copy y cut linea entera
** DONE next-buffer previous-buffer
* DONE atajos de org-mode
** insertar timestamp inactive que lo hago mucho
[2016-10-22 sáb]
** clock in - clock out
:LOGBOOK:
CLOCK: [2016-10-22 sáb 16:10]--[2016-10-22 sáb 16:25] =>  0:15
:END:

* minuta de programacion
:LOGBOOK:
CLOCK: [2016-10-22 sáb 16:26]--[2016-10-22 sáb 16:27] =>  0:01
:END:
orgfile de relato o minuta de todos los items que vamos trabajando
durante el trabajo con clock. entonces cumple una funcion doble es una
lista de todos los items programados y las fechas.
me saca la duda o sensacion de que carajo hice cada dia, en especial
ahora que dedico la mañana y a la vez cuanto me lleva programar.
hacer chunks de estudio y visitar el diario de desarrollo estarian
incluidos en la tarea de programar, pq estarian dentro del mismo tema.
se diferencia del diario de desarrollo que en el se debate lo que se
va a hacer, y este registra lo que se hace, muy claramente en vim.
ver si el clockeado en subtree se suma arriba
* clockear dia-general
para tener una idea del tiempo pasado alli
* dividir momentaneamente el dia-general
en recupero de cuadernos y escrito fresco cosa de clockear eso y ver
cuanto le vamos dedicando.

