* programacion
** sobre postgres/sqlite
[2019-03-04 lun]
como no se puede demorar el ritmo de programacion, se debe seguir y
rapido desarrolando en sqlite, y no debe considerarse inseguro hacerlo
en esa base de datos. Lo unico que todas las tablas nuevas o
modificaciones de tablas deben ser mapeadas a pgmodeler y su
correspondiente mapeo a postgres para ir manteniendo compatibilidad y
en lo posible ir manteniendo en los ratos libres la compatibilidad del
buscadorpg
** recuperar los datos de visitas de clientes
[2019-03-04 lun]
aunque sea un poco tedioso seria bueno contar con esa informacion
aunque sea grosso modo a partir de comienzo de a単o para fines
estadisticos.
Renegue bastante. Pero ya esta. Al final un problema en las fechas
levantadas con el volcado da csv pero lo pude limpiar al final
unicamente con el kdevelop, en forma ultrarapida, poniendo que los
finales de linea no sean DOS sino linux.
** programar todo sqlite-tcl ya para optimizacion total
cosa de no esperar mas y perder tiempo en paralelismos y luego
recuperar la base de postgres desde ahora. Lo que no quita que en los
tiempos libres siga jugando con lo logrado hasta ahora.
La bocha seria tener un sistema de programacion que fuera agnostico de
base de datos cosa que llegado el momento se haga el cambio
* sistemas
** sistema 4 en linea arrancando con elementos viejos desde ya
[2019-03-04 lun]
ya estaria preparado el sistema para arrancar.
no solo se basa en elementos viejos. Y no solo en 4 en linea.
*** el sistema se parece mas al 2013
o sea reunion en zona, division de zona por manzanas y pulmon para
repechaje.
luego mandan autorizacion a la central y el repartidor esta
repartiendo continuamente. 
*** no es el clasico 4 en linea
el 4 en linea dos y dos, viene pq el llamado es visual, y el avance
tiene que ser parejo pq la asignacion de zona no se da desde la
ma単ana, y la distribucion de trabajo del repartidor no viene de una
central sino de los mismos chicos.
*** ventajas del sistema 2013
1. podes tener mas chicos. No necesitas ce単irte a los 4 exactos.
2. podes manejar mas cosas desde la oficina, como la asignacion de zona
3. menos dependencia de los individuos, lo cual puede hacer que se
   caigan solos.
*** simplificacion de la cuota
tener todos los packs al mismo precio tambien puede simplificar
tambien la operatoria.
* nuevo esquema cobranza modular
un esquema de cobradores limitados estandarizados
** detalles del sistema
1. sin asignacion de zona fija
2. se le asigna un recorrido por dia de unas 40 fichas o menos segun
   el tipo de fichas
3. se dan 15 recibos
4. se rinde a la vuelta y se puede repetir (primer viatico 80, segundo
   si hay 40 - para sacar un segundo recorrido hay que venir a rendir
   el primero antes de las 14hs con los 15 recibos completos).
5. flexibilidad de dias en el mes
** ventajas del sistema 
*** riesgo acotado general a 6000 promedio
como nadie tiene porque llevar mas de 15 recibos no tiene porque haber
un riesgo mayor
*** mayor facilidad de contratacion
por riesgo acotado tendremos mas facilidad para tomar riesgo, y por no
tener que asignar zona tendremos mas flexibilidad a la hora de tomar
pq los mandamos a cualquier lado. 
*** contratacion continua
tener avisos continuamente como rutina, tener gente entrevistada y
gente probada y poner gente que realmente sirva. Siempre tener lista
de espera
*** manipular los recorridos
uno en el fondo sabe cual recorrido es cada cual y puede manipular los
recorridos para ir dando los que uno quiera a quien quiera a los fines
de controlar o desgastar.
*** mejor control y prevencion
al no tener zona fija es dificil cubrir la cagada pq al otro dia va
otro.
*** mayor eficiencia
pq no jugamos el destino de una zona en la mano de uno sino en las de
varios, supongamos primero de mayo en vez de apostar a uno, podemos
mandar 3 o 4 distintos, es raro que el factor cobrador influya en la
zona.
*** quitamos el peso de encima de cuanto ganaras
al no ser proporcional a la zona que te asignemos, sino a los
recorridos que seas capaz de gestionar dimos vuelta la cuchara y lo
que ganes va a ser culpa tuya y no nuestra. Si haces mas recorridos
ganas mas, seas quien seas. (lo de la diferencia entre recorridos es
una sutileza, aparte los recibos son 15 para todo el mundo)
** esquemas mentales viejos que sostienen las desventajas
*** a la gente no le gusta que vayan cobradores distintos cada vez
es cierto, pero que importa y desde cuando nos importa lo que diga la
gente.
las ventajas para nosotros superan en mucho lo que la gente quiera y
la justificacion nuestra sera que lo hacemos por motivos de seguridad
y que nosotros nunca le dijimos que le ibamos a mandar un mismo cobrador
*** el cobrador es mas eficiente cuando tiene una zona a su cargo
mentira. siempre tuvimos ese sistema y la eficiencia brillo por su
ausencia. La eficiencia se pierde. Prefiero que pierdan una hora de
mas buscando las calles por primera vez que tener gente en la misma
zona, otra vez, las ventajas para nosotros superan la ventaja para el
cobrador.
*** la gente paga mejor cuando viene el mismo cobrador
mentira. paga peor. pq al ser conocido lo cagan mejor. pasaba con la
elba. en el caso de que al que mandemos no le paguen, ma単ana mandamos
otro y pasado otro y asi sucesivamente.
