* programacion
** sobre postgres/sqlite
[2019-03-04 lun]
como no se puede demorar el ritmo de programacion, se debe seguir y
rapido desarrolando en sqlite, y no debe considerarse inseguro hacerlo
en esa base de datos. Lo unico que todas las tablas nuevas o
modificaciones de tablas deben ser mapeadas a pgmodeler y su
correspondiente mapeo a postgres para ir manteniendo compatibilidad y
en lo posible ir manteniendo en los ratos libres la compatibilidad del
buscadorpg
** recuperar los datos de visitas de clientes
[2019-03-04 lun]
aunque sea un poco tedioso seria bueno contar con esa informacion
aunque sea grosso modo a partir de comienzo de año para fines
estadisticos.
Renegue bastante. Pero ya esta. Al final un problema en las fechas
levantadas con el volcado da csv pero lo pude limpiar al final
unicamente con el kdevelop, en forma ultrarapida, poniendo que los
finales de linea no sean DOS sino linux.
** programar todo sqlite-tcl ya para optimizacion total
cosa de no esperar mas y perder tiempo en paralelismos y luego
recuperar la base de postgres desde ahora. Lo que no quita que en los
tiempos libres siga jugando con lo logrado hasta ahora.
La bocha seria tener un sistema de programacion que fuera agnostico de
base de datos cosa que llegado el momento se haga el cambio
* sistemas
** sistema 4 en linea arrancando con elementos viejos desde ya
[2019-03-04 lun]
ya estaria preparado el sistema para arrancar.
no solo se basa en elementos viejos. Y no solo en 4 en linea.
*** el sistema se parece mas al 2013
o sea reunion en zona, division de zona por manzanas y pulmon para
repechaje.
luego mandan autorizacion a la central y el repartidor esta
repartiendo continuamente. 
*** no es el clasico 4 en linea
el 4 en linea dos y dos, viene pq el llamado es visual, y el avance
tiene que ser parejo pq la asignacion de zona no se da desde la
mañana, y la distribucion de trabajo del repartidor no viene de una
central sino de los mismos chicos.
*** ventajas del sistema 2013
1. podes tener mas chicos. No necesitas ceñirte a los 4 exactos.
2. podes manejar mas cosas desde la oficina, como la asignacion de zona
3. menos dependencia de los individuos, lo cual puede hacer que se
   caigan solos.
*** simplificacion de la cuota
tener todos los packs al mismo precio tambien puede simplificar
tambien la operatoria.

