* TODO comprar antipolillas :dpto:

[2018-10-10 mié 10:33]

* TODO limpiar estantes vestidor :dpto:

[2018-10-10 mié 10:34]

* DONE encarpetar documentos pendientes :dpto:oficina:
- State "DONE"       from "TODO"       [2018-10-12 vie 14:05]
[2018-10-10 mié 10:35]

* TODO llevar todos los recibos y doc viejos al marques :dpto:oficina:

[2018-10-10 mié 10:35]

* TODO facilidades fechadoras :IDEA:

Se podrían hacer múltiples. bind en tablet list para allá en facilitación del fechado por ejemplo poner números y que eso sean interpretados inteligentemente Cómo fechas tal cual ya habíamos hecho en una función de python y letras correspondiente a los días de semana incluso teniendo en cuenta cuando se trata de no la semana que viene si no la otra también se podría tener en cuenta más inteligentemente el teclas o mes siguiente que no sea tan irritante en los casos qué en vez de pasar por ejemplo para el día 10 del mes siguiente pase para el día 9 del mes siguiente porque este mes tenga 31 días.

* TODO Edicion en ventana aparte del fechar :IDEA:
:PROPERTIES:
:CREADO:   [2018-10-26 Fri 16:02]
:END:

Podría ser que cuando se va bajando en el fechar renglón por renglón y uno pusiera o apretar a un botón decisión que tú ir incrustado en el tablero y se abrir una ventana emergente donde estuvieran todos los campos editable y uno atrás de otro con un encabezado fijo de los datos del cliente editar con los datos fijos y todos los campos editables que suelen surgir cuando uno está editando el estado que hay podría hacer editar una dirección editor teléfono y ello tener digamos acceso a la Macro de guardar a ex dirección y a su vez que podamos evitar digamos todo lo que es aclaración horarios mensaje al cobrador y comentarios y poner tag de gestión tag mudado tarde bueno todo lo otro está que todavía no están programados como tag de no vender más tarde a la venta s13 tras subir al se deben emitir intimaciones ese te lo deseo todo el trabajo del cliente que se haga en una ventanita en forma más segura una que se terminó con el cliente se pone guardar eso se pliega Y si sigue con el cliente entonces esa sería una forma muy eficiente porque se trabajaría sobre un listado sobre una planilla pero al aves se abriría una ventana donde estarían todas las facilidades de trabajo dentro de esa ventana que no sería muy grande sino que sería más o menos compacta para que no oculte del todo el listado que esté abajo

* Algunas cosas q se cruzan
:PROPERTIES:
:CREADO:   [2018-10-26 Fri 16:41]
:END:

Matetes
De como me cambio la vida quedarme sin auto y eso no se compensó con haber comprado la casa ni haber vivido en dpto
Que haber tenido q vivir en jujuy me mato por el ruido
Que la oficina me mato por la falta de tiempo en q me sumio
Que retirarme ahora supuestamente a descansar es un peligro para mi pq cedo la unica porcion de poder q me queda
Que creo q me tengo q recuperar en silencio de a poco. 
Pero los problemas q basicamente tengo no van a desaparecer.
Quizas veo todo muy malo pq estoy cansado.


* Planes de pago :IDEA:
:PROPERTIES:
:CREADO:   [2018-10-27 Sat 11:55]
:END:

condonar la cuenta
crear una "venta" nueva con los vtos y el monto nuevo.
el tema seria no afectar las estadísticas de venta reales con estas ventas fictas por lo cual se debe buscar una solucion.
O bien nuevos campos en tabla venta 
Planpago logico
Ccpp int
icpp int
Primerapp date
Y reescribir los procesos virtuales q producen on the fly el cuotaje y el pagaje que cuando ventas.planpago=1 tome los campos pp en vez de los normales y tome los pagos hechos posteriores al plan de pago. A su vez la info permanece intacta y se puede visualizar.

Como se haria con los casos en q son dos las cuentas. Para no partir el plan de pagos y siendo q nace de un acuerdo se podria condonar una la mas chica y poner el plan en la mas grande y anotar esa circunstancias. Para q salga una ficha unificada.
El tema es q saldria de x la cuenta y (la z estaria condonada) y generaria p.e 3 cuotas de 300 q es lo q acordo el cliente.  Y se iria cobrando eso incluso se puede marcar como plan de pago pero sin cuota a las q son hijas de un mismo pp.
Podria haber una tbl de plan de pago q genere un id q lo cargue en tbl ventas en los registros afectados y en solo uno cargue las cuotas. Luego registre toda la otra info del pp. 

* Primer dia :retiro:estadoAnimico:
:PROPERTIES:
:CREADO:   [2018-10-27 Sat 18:56]
:END:

Vine rapido y bien.
Charla breve y fluida.
Almuerzo bueno y sin sobresaltos con las chicas
Larga siesta.
Solo el dia esta tramado por la obligacion de ir al evento que tengo llevar a la Cami.
Fui a llevarla facilmente pq era cerca y no habia transito pero fue muy larga la espera y luego la noche fue caotica mas que lo comun.
Mas alla de ello en este primer dia tuve expresiones bastante desafortunadas que pienso q provienen de la desesperanza y la depresión y la ira mas q todo pq el estado de agotamiento de los últimos dias no me permitio explicarme claramente en mis propositos.
Nadie sabe q quiero hacer y como yo necesito descansar mas q nada y no veo por momentos la posibilidad de un espacio fisico de tranquilidad para hacerlo entonces me pongo agresivo.

* Nueva programación :programacion:IDEA:
:PROPERTIES:
:CREADO:   [2018-10-27 Sat 23:03]
:END:

~Como debe ser lo nuevo:
- documentado: en extremo asi como se esta haciendo el nuevo buscador
- ordenado: guardar convenciones logicas para los nombres de los widgets variables y procs
- estructura
createWidgets
createBindings
Procedimientos primero luego dos proc q contienen la UI que se instancia despues a lo python
- uso de namespace eval para guardar variables privadamente y no mezclar con lo global

namespace eval tClip {
    variable on_top    false
    variable word_wrap none
    variable selected  ""
    variable cliplist  [list]
    variable theme     [ttk::style theme use]
    variable type      [expr {[tk windowingsystem] eq "x11" ? "UTF8_STRING" : "STRING"}]
}
- se podria documentar cada script en forma unificada o similar o siguiendo la misma estructura para q sea facil de leer.
P.e. tener una parte q diga q tablas usa y q campos necesita

* Arreglo de tablas :programacion:IDEA:insomnio:
:PROPERTIES:
:CREADO:   [2018-10-28 Sun 10:07]
:END:

Una vez q arregle app por app dando de baja cada aplicación vieja pq ya TODAS las funciones ya fueron incluidas (como quiero hacer con F13+fichaje.py/ver -->buscador.tcl) voy a anotar las tablas y los campos q realmente uso. Deberia agregar el campo q quiera con el nombre q quiera. Y no reusar campos obsoletos. Y anotar las consultas q uso si es q uso alguna y los triggers.
Luego en un script reescribir el traspaso de tablas a su nuevo schema y hacer un test bien groso sobre todas las aplicaciones oficiales a partir de ese momento.
Y ahi se hara la limpieza de la base de datos del pasado y se hara el paso definitivo a una nueva version de los programas q supere toda la tanda de los actuales y quiza sea incompatible con ellos. Pero el tamaño de la db sera menor y el schema mejor.

* Buscador :programacion:
:PROPERTIES:
:CREADO:   [2018-10-28 Sun 10:30]
:END:

Creo q el camino de crear virtualmente en el arranque una tabla cuotas de todas las cuentas y luego hacer un proceso de llenado de recibos no sirve.

Creo q tendria q avanzar teniendo un buscador con todo lo q tienen ambos predecesores.

En todo caso si un proceso permitiria crear los datos q quiero hay q hacerlos cliente por cliente. O sea al llenardatoscliente hago tabla cuotas del cliente con su proceso pago desde su set de recibos con idcliente x. La carga de tjo es 30000 veces menos y es mas rapida. 
O bien se podria usar namespace o una class para mantener abiertas distintas tabs como queria yo.
O sea q haya un buscador en un 20% de la pantalla y luego el resultado abajo por tabs cosa q podamos tener varios clientes abiertos en paralelo. Al estilo Firefox. Esta idea es genial.

Entonces bajo la parafernalia de labels de info no editable y algunos entrys editables vendra un tbls de ventas por orden coloreadas tageadas (cancelada devuelta condonada pagando) que con un tree se abrira y se calculara el cuotaje.

Se podra imprimir resumen de cuenta de cuentas canceladas con menu como f13


* Exportar contactos a telefono :programacion:
:PROPERTIES:
:CREADO:   [2018-10-28 Sun 16:09]
:END:

Tener por script la posibilidad de exportar los contactos en formato vcf p.e.
Entonces producimos el romitex.vcf con digamos 5000 contactos y de ahi lo importamos con un gestor eficiente de contactos y de ahi a whatapp web o un bot o wrapper futuro

* tclshrc :LEER:
:PROPERTIES:
:CREADO:   [2018-10-28 Sun 17:48]
:END:

https://wiki.tcl-lang.org/page/tclshrc

La idea seria poner todo lo necesario para tjar en el proyecto
Package require etc.


* Ayuda de eGuard 2 - eggdrop.es :LEER:
:PROPERTIES:
:CREADO:   [2018-10-28 Sun 23:48]
:END:

http://eggdrop.es/ayuda/script/eguard2/

* TODO [#A] Ver cuentas :oficina:
DEADLINE: <2018-10-31 Wed>
:PROPERTIES:
:CREADO:   [2018-10-29 Mon 09:20]
:END:

Llevar doc 70037 de la devolución
Analizar 69965

* Segundo dia :retiro:estadoAnimico:ansiedad:
:PROPERTIES:
:CREADO:   [2018-10-29 Mon 11:39]
:END:

El domingo estuvo tramado por no haber podido dormir bien la noche anterior y por los compromisos inflados q tenia
- correr los muebles
- ir a la oficina
Y luego todo se esfumo. El corrimiento de muebles fue 5 minutos y el ir a la oficina no fue tan grave. Pero lo mismo no dormi bien por los gatos pienso en especial el escli y pq el lunes empezaba la obra

* Tercer dia :retiro:migraña:hijas:
:PROPERTIES:
:CREADO:   [2018-10-29 Mon 11:44]
:END:

Hoy al final me levanté a las 9. Salude a los albañiles. Pedi el contenedor. Todo fluido.
Y fuimos a ver a los bancos de la Romi
Muy lindos y muy contento q se vaya para arriba y q la pueda ayudar
Una migraña de 2 migrales antes de las 12hs me molesta pero no es por ansiedad.
Medio a la madrugada. Medio al levantarme y uno al volver de ver los bancos.
Otra tarea q estaba agendada y ya la hicimos.
Hasta las 19.15 sigo con migraña.

* TODO Acomodar el celu :actividad:retiro:
:PROPERTIES:
:CREADO:   [2018-10-29 Mon 19:24]
:END:

- [ ] anotar todas las apk q voy borrando cuanto las tuve si las use mucho poco o nada para q la instale que funcion buscaba y con cual la reemplace.
- [ ] borrar obviamente la apk
- [ ] reacomodar las pantallas dejar solo 3

* Pin para app romitex :programacion:IDEA:
:PROPERTIES:
:CREADO:   [2018-10-29 Mon 19:29]
:END:

Poner pin de seguridad a dni.tcl para q en caso de q roben el celu podas proteger la app si fallan el pin mas de 5 veces seguidas se borra la base de datos y los programas. 

