* dump restore
pg_dump dbname | gzip > filename.gz

Reload with:

gunzip -c filename.gz | psql dbname
* DONE solucion a expandpg {[pivotpg]}
- State "DONE"       from "TODO"       [2019-10-01 mar 19:16]
cuando queremos poner un pivot dentro del expand, nos da error de
lectura de la variable $con, pq a diferencia de sqlite que
referenciamos la conexion en forma absoluta como db, aca lo usamos
como variable.
La unica solucion que encontre es usar el handle directo que entrega
la conexion esperando que sea estable siempre, en este caso fue
pgsql7, en cada programa asume un numero distinto.
* DONE BUG se borra el tbls al hacer focus
- State "DONE"       from "TODO"       [2019-09-29 dom 15:55]
se borra el tbls y su source -pq no hace recalc- tanto al hacer focus
con teclado o con raton, y al hacer focus en el mismo o en el tbls del
costado, pero en el bodytag no en los encabezados de columna. Y al
recargar nuevamente el tbls anda perfecto. Los otros tbls andan
fenomeno. Pone en la col id Total en bold que no es la misma forma que
Total de Totalizar y saca un campo. 
O sea que es una combinacion muy rara de cosas. Es la primera vez que
veo un bug de esta naturaleza con tbls.
encontre la solucion pasando en limpio paso a paso la planilla con
otro nombre. habia un bind en un entry de otro tab que actuaba sobre
las planillas haciendolas llenar y totalizar y eso daba los errores.
* TODO BUG core dumped segment fault
cuando luego de usar los tbls-tree cierro el programa
* TODO resignficar los pivot y cuadros con etiquetas
ya sea titulo con labels o etiquetas triples de colores con los campos
de un pivot es mucho mas explicativo el saber lo que tenemos en un
cuadro que despues de un tiempo lo dejamos de ver.
