#+TAGS: INICIO MEDIO ALTO
#+TAGS: EMACS ORG ELIPS TCL TABLELIST SQLITE PYTHON UBUNTU LINUX VIM PRINT SOLUS
* Documentacion general
que es la teoria? es el lugar donde acumularemos todo lo que sea
aprendizaje o documentacion. en vez de tener uno por tema aca vendran
todos juntos
* emacs
** ver diff llamando C-x vD sobre un dired                           :emacs:
[2018-10-12 vie 19:08]
para ver todas las diferencias generadas se llama sobre el dired y se
ven las diferencias claramente.
| proximo hunk   | Tab |
| anterior hunk  | p   |
| ir a la fuente | o   |
| proximo file   | {  |
| anterior file  | }   |
* org-mode                                                              :ORG:
** Solucion al no funcionamiento de los Capture Template           :Capture:
[2018-10-09 mar 19:44]

Capture Template programados en otra maquina y que funcionaban bien en
la oficina no funcionaban o lo hacian parcialmente, en especial no
andaba el de jornal que tenia datatree+olp.
La version que tenia de org era la 8.algo que incluso actualizandola
via apt no obtuve gran diferencia, cosa que si habia logrado en el
dpto pq ese xubuntu es 2018 y el de aca es 2016. Entonces se me
ocurrio hacer un package-list y buscar org directamente e instalar
desde alli, y lo instalo de una y ahora la version indica 9.1.14 y ese
parece ser el problema de que no funcione el template.
** problema con org-agenda-files                                    :Agenda:
[2018-10-12 vie 19:24]
se puede poner un directorio, y yo pongo usualmente ~/orgblok y todo
anda bien, pero detecte que no levanta los orgfiles que empiezan con
punto o sea los dotfiles. y yo tengo varios que tendria que renombrar
y solucionar ese problema pq si quiero mover el .emacs frecuentemente
se incompatibiliza con las distintas maquinas si no lo toma
automaticamente a los dotfiles que puedo crear.

** Archivamiento interno                                          :Archivar:
[2018-10-14 dom 12:51]
Internal Archiving
poniendo el tag :ARCHIVE: a un heading (que se hereda) el tree se
archiva en el lugar, o sea no se traslada a ninguna parte. 
Las consecuencias de este tipo de archivamiento son:
1. no participa del ciclo de visibilidad (solo con Ctrl-Tab) o bien
   existe una variable para activarlo (pero no tiene sentido)
2. no participa en los sparse tree y tambien hay una variable que los
   activa: org-sparse-tree-open-archived-trees (esta la active pq si
   me parece que tiene sentido)
3. en la construccion de las vistas de agenda no participan. Tambien
   hay variable (no tiene sentido aplicarla me parece pq para eso uno
   archiva para que todos los TODO que pueda tener un archivo obsoleto
   no te aparezcan en agenda p.e. pythonbug.org) Pero en agenda uno
   puede poner v a para que aparezcan
4. no se exportan
5. no se ven en las column-view (tambien hay variable)

** Archivamiento externo                                          :Archivar:
[2018-10-14 dom 13:00]
mover un tree a un archivo externo de archivamiento:
C-c $ org-archive-subtree
el archivo tiene el mismo nombre con la terminacion _archive
ej. habitos.org habitos.org_archive

* tcl                                                                   :TCL:
** enviar señal break
  con un proc enviar señal de break
  return -code break

** freezar columnas en el tablelist
  tbls configure -titlecolumns 4

** hacer que una columna sea numerica o muestrenumeros
  tbls columnconfigure n -showlinenumbers yes (o 1)

** regsub
  regsub {^0} [funcion] {} var
  saco el 0 inicial del resultado de una funcion que me entregaba valores del 
  dia de una fecha y algunos eran rechazados como octales p.e. 09 08 y por eso 
  le saco el cero inicial y luego pongo el valor de var en su reemplazo que es 
  el regsub.
  O sea 1ro la regexp a buscar luego el texto, tercero la expr para cambiar y 
  cuarto la variable que contendra el texto cambiado, y regsub responde 1 o 0 
  segun tuvo o no tuvo exito.

* tablelist
* sqlite
* python
** comandos interesantes pycharm                                    :PYTHON:
[2018-10-10 mié 18:33]
| S-F6  | refactorizar-rename | rename all ocurrences symbol |
| C-F12 | buscar symbol       |                              |
| C-F11 | add-bookmark        | numero o letra               |
| S-F11 | ir a bookmark       |                              |
| F11   | toggle bookmark     |                              |
|       |                     |                              |

* instalacion ubuntu
* vim                                                                   :VIM:
** Vim - mejorado
*** Busqueda
**** Busqueda de palabra bajo el cursor (*|#)
Esa caracteristica viene out the box y es inigualable, y me resulta
impresindible y en emacs no la puedo lograr asi de una.
Incluso el resaltado (o subrayado) queda hasta que expresamente lo
saques. Y lo buscado queda linkado para seguirlo usando.
**** Esta la busqueda al toque con / y sus repetidos n|N
**** Busqueda global en el proyecto con Acw
Eso es genial pq te muestra en ventana aparte las ocurrencias de lo
que buscas y podes ir directamente alli sin perder la ventana de
busqueda.
Incluso funciona aun fuera del proyecto indicandole el directorio.
**** Reemplazo eficiente y seguro con :%s//
:%s/buscar/reemplazar/gc   o sea % busca en todo, g global y c
confirma y tambien se podria hacer en un area :5,25s/busca/reemplaza
lo cual habria que acostumbrarse a usarlo pq es muy util cuando
queremos hacer un reemplazo sobre una parte del archivo.
*** Files
**** apertura normal
la apertura out the box es muchisimo mas rapida que en emacs. 
:e y al toque escribis la ruta con autocompletado y ahora con el
wildmode ves los resultados en la barra los cuales podes moverlos con
teclas de movimiento. 
**** ctrlP
con ese plugin abris cualquier archivo en el directorio actual (el
cual genialmente te lo cambia de acuerdo al archivo que tengas por
delante) y te moves facilmente dentro de el
**** NERDTree que lo tengo linkeado a F3
Lo unico que no logre que me funcione el toggle o una forma de
cerrarlo.
Es un explorer ahi en tu area de trabajo. Falta aprenderlo nomas.
*** Movimientos
**** Entre buffers ultrarapido Ctrl up|down bn|bp
Con ese linkeado me muevo como luz entre buffers. Si tuviera muchos
abiertos ctrlp tiene busqueda sobre buffers.
**** Entre tabs con Ctrl right|left
idem anterior.
**** Entre ventanas Ctrl j|k l|h
La facilidad enorme de abrir split con 
| :sp         | abre split horizontal                  |
| :vsp        | abre split vertical                    |
| :30sp       | se le puede dar un tamaño              |
| Ctrl w _    | maximice el ancho de la ventana actual |
| Ctrl w pipe | maximice el alto de la ventana actual  |
| Ctrl W =    | restaura el dibujo original            |
| Ctrl W o    | cerrar todas menos la actual           |
| Ctrl W t    | abrir la actual en nueva pestaña       |
| Ctrl W R    | swap ventanas                          |
|             |                                        |
Y con los bindkey echos a Ctrl jklh saltas de ventana en ventana en un
tris.
**** :jump history Ctrl i/ Ctrl o
Esa caracteristica out the box es genial y yo nunca la use. Es algo
muy util al programar pq a veces te moves en distintos lugares de un
archivo y estos mostros te guardan 100 lugares donde estuviste. (Creo
que hace innecesario las marcas, o los inusables bookmarks de atom).
**** :changes S-left S-right
es mucho mas util que jump

*** Auxiliares de programacion
**** Autocompletado con jedi
Ya habia notado antes que vim con jedi que funciona bastante bien te
permite programar facilmente, pq instrospecciona las clases y te
muestra practicamente la ayuda en linea, en mayor o menor medida, en
especial para tus propias clases y argumentos necesarios.
**** Tagbar
con un simple F4 tengo al lado la ventana de navegacion, en la cual
ves el esquema y te moves en el.
**** superTab
parece que viene en auxilio de jedi en las autocompleciones anodinas
que son las que mas causan error.
**** En realidad he podido prescindir de jedi
parte pq en la netbook me enlentece demasiado y parte pq es invasivo a
nivel pantalla
*** boton medio pegar clipboard



** comandos recuperados                                             
[2018-10-14 dom 13:21]
** Comandos descubiertos o redescubiertos

| C   | Cambia el resto de la linea | emacs C-k |
| S   | Sustituye la entera linea   | ?         |
| D   | Delete hasta eol            |           |
| U   | en visual Upper case        |           |
| ciw | change integer word         |           |


** Nuevos atajos
| e            | enclose word con quote |
| s            | commenting a line      |
| S-left-right | ir al ant-pos change   |
|              |                        |



** Comandos que siempre he usado y son utiles  

| cw | cambia la palabra | emacs M-d | 
|    |                   |           | 

** Aspectos que no conocia
*** :changes 
te lleva adelante o atras a los cambios reales hechos en el archivo e
incluso permanece tras cerrar el archivo. Ideal para volver donde
estabamos.
*** C-r en insersion mode
   te aparece unas comillas y alli puedes poner el numero de registro que 
   quieres insertar.
   se puede ver en :reg
   es de destacar el . (dot) que es todo lo ultimo insertado

** Aspectos que son interesantes
*** un undo y redo separado e ilimitado.
Incluso con horario que lo vas viendo. En emacs te confunde un poco el
que mezcle undos y redos.


   
** arreglos en vim para mayor eficiencia
*** buffer previo y next con [ ]
*** apertura rapida de archivos usados frecuentes con ;6 ;7 etc
*** apertura de orgblock ;9  Explore
*** reinicio de pomodoro con ;0 
*** magit facil
   inicio con :Magit
   stash con S
   commit con CC



*** nuevos plugins
**** CtrlP
    busqueda de archivos en general con C-b o C-b cambio el tipo de busqueda 
    en tres posibles: mru files buf o sea archivos recientes files o buf
    una vez buscamos el archivo introduciendo el nombre, el path lo tenemos a 
    la derecha en la barra, y es el dir presente tenemos tres opciones:
    C-t abre en otro tab C-v C-x abre en split vertical o en split horizontal

    tip de busqueda: p.e. para buscar age-programacion-tcl.org poner age-tcl 
    no asi agetcl.

    para ir al directorio padre usar ..

**** superyank
    usar Alt-p o Shift-Alt-p para ciclar entre el reg de yanks
**** tagbar
    instalar desde el apt exuberant ctags
    en el directorio correr ctags files en este caso en tcl1 ctags *.tcl
    luego con tagbar (keybindeado a F4) te aparece el resumen de proc o clases 
    y metodos. Interesante en proyectos complejos

    
*** insertar fecha emulando fecha inactiva de orgmode
:put =strftime('[%F %a]')
put =strftime('[%F %a]')
**** [2018-03-07 mié]
    entrada del dia 
***** [2018-03-07 mié]
     entrada del dia
        
***** 
** vimorg    
*** movimiento de subtrees
   al final tanto lio y se logra con delete y pegado te borra y pega el tree 
   completo mas intuitivo que emacs


* linux
** crear un usb con una distro con dd                                :LINUX:
[2018-10-10 mié 21:18]
con lsblk averiguamos la letra de asignada al usb.
No desmontar como dicen por ahi
sudo dd if=/home/... ubic del iso of=/dev/sdb bs=1M

* SOLUS                                                         :instalacion:
** instalacion de TCL en solus                                       :SOLUS:
[2018-10-10 mié 23:14]
ningun archivo de tcl esta. 
Entonces instale ActiveState en un directorio de Home para luego
borrarlo y fui moviendo subdirectorios a pedido de acuerdo a lo que
demandaban los programas.
*** pdf4tcl
que lo instale desde el backup mio
*** tablelist 
que baje la ultima version
*** tcllib1.18
pq F13.tcl me pedia snit para que funcionara pdf4tcl
*** bwidget
*** Img
*** itcl y itk
alli vino el problema pq me daba un error que yo asumi que era una
gran incompatibilidad y luego cuando lei bien decia algo como que: 
Error in startup script: Can't find a usable itk.tcl in the following directories:
    /usr/lib64/itk4.1.0 /usr/bin/../lib/itk4.1.0 /usr/bin/../library /usr/bin/../../library /usr/bin/../../itk/library
This probably means that Itcl/Itk weren't installed properly.
o sea que no encontraba el directorio de itk directamente en /usr/lib
no dentro de tcl8.6 como estan todos, entonces lo copie directo a
/usr/lib  y anduvo perfecto.
*** directorio en solus para tcl /usr/lib/tcl8.6/
** problema con los modulos python                                   :SOLUS:
[2018-10-10 mié 23:51]
no tiene pip3, entonces se instalan con pip, de una, y hay que hacerlo
con sudo.
y luego hay que copiarlos de la ubicacion del modulo en python2.7 a
3.6
hero@hero /usr/lib64/python2.7/site-packages $ sudo cp -r pypercl*
/usr/lib64/python3.6/site-packages/
Uso asteriscos porque pueden ser varias cosas y uso -r pq pueden ser
directorios con dateutils paso asi.

No obstante se me trabo fastnumbers que no anda y parece un bug que
hasta esta en la web, asi que voy a ver si lo desinstalo.



** instalacion de hp1102 en solus                                    :SOLUS:
[2018-10-11 jue 15:00]
1) instalar en solus HPLIP
2) en un terminal poner hp-setup y seguir las indicaciones
3) desde configuracion de impresion hacerla predeterminada
nada mas que eso. Y se soluciono el problema de la cola de impresion,
que tenia un dia atras en xubuntu aparentemente, pq anda bien, lo
unico que con otras fuentes se imprimen los listados
** problema con hibernacion                                          :SOLUS:
[2018-10-11 jue 15:04]
tuve dos casos de que luego de equis minutos la maquina no respondia,
y tuve que resetearla, pienso que es pq la configuracion de energia
esta para entrar en hibernacion y esta maquina de escritorio queda en
estado loco. Lo desactive. veremos que pasa. 
* impresoras
** impresora hp no anda luego de cambio toner
[2018-10-10 mié 16:01]
da retenido y no arranca, resetie maquina y nada, cambie usb de lugar
y nada, borre impresora y nada, cuando prendia no se instalaba sola
como acostumbraba.
Luego la instalo desde el menu que te ofrece y tampoco andaba.
la borro, insisto pero esta vez la instalo como impresora usb y
anduvo.
Pero no quedo como antes, sino que cuando le mando varios trabajos no
los hace. incluso si es muy grande no lo procesa y a la segunda vez
que se lo mando lo procesa. 
es como si estuviera rota la cola de impresion.
* otras bases de datos
** postgres 
*** superusuario por defecto postgres
El super usuario predeterminado de PostgreSQL se llama
postgres. Deberá ingresar con este usuario la primera vez.

sudo su postgres
password de linux para sudo 

postgres@herohp: asi es el prompt
*** creacion de un user nuevo
createuser --createdb --username postgres --no-createrole--pwprompt hero
alli creo el usuario hero que tiene la capacidad de crear database
pero no de crear usuarios (roles) y me pide password 
*** crear database
las cree con pgAdmin en forma grafica 
*** ir a una database concreta y salir de ella
postgres@herohp: psql romitex
romitex#  create table calles(id int,calle varchar(80));
CREATE TABLE
romitex# \q  ---> salir de la database
*** copiar datos desde un CSV 
con esto migro facilmente los datos

COPY calles FROM '/home/hero/rx/calles.csv' CSV HEADER;
y alli copia todo.


* Refile
