* [2022-10-17 Mon] base16-gruvbox-dark-hard
y compania -medium -pale -light. bastantes buenos y suaves.
* [2022-10-19 Wed] ef-dark doom-opera-light
doom-opera-light para el dia parecido al modus-theme muy delicado.
Y ef-dark para la noche impactante. Todo con el cambio de font a iosevka-comfy
* [2022-10-20 Thu] ef-night
le gana al ef-dark a la noche, en el dia siguio el doom-opera-light
* [2022-10-21 Fri] ef-spring
para el dia.
* [2022-10-23 Sun] nano light y dark
* [2022-10-25 Tue] doom-nord
* [2022-10-27 Thu] sanytyinc-tomorrow-night
* [2022-10-30 Sun] doom-nord-aurora
* [2022-11-02 Wed] doom-nord y ef-frost
* [2022-11-04 Fri] ef-cyprus - ef-bio
* [2022-11-05 Sat] base16-tokyo-city-dark
* [2022-11-08 Tue] ef-bio  (uso de themes-dark aun de dia)
* [2022-11-12 Sat] base16-gruvbox-dark-hard (input font)
* [2022-11-13 Sun] lambda-light-faded y lambda-dark-faded
no he tenido hasta ahora un tema mas lindo que este. Es la combinacion
perfecta con la font input mono.
Es el mejor theme que hay para org-mode. No tanto para programar en
webmode.
El uso del light/dark ha sido 95/5 de forma tal que vuelvo a cambiar a
mi preferido el-bio por ahora.
* [2022-11-15 Tue] lambda-light-faded el-bio
* [2022-11-16 Wed] lambda-light-faded lambda-dark
* [2022-11-22 Tue] kaolin-ocean
