* Comandos descubiertos o redescubiertos

| C   | Cambia el resto de la linea | emacs C-k |
| S   | Sustituye la entera linea   | ?         |
| D   | Delete hasta eol            |           |
| U   | en visual Upper case        |           |
| ciw | change integer word         |           |


* Nuevos atajos
| e            | enclose word con quote |
| s            | commenting a line      |
| S-left-right | ir al ant-pos change   |
|              |                        |



* Comandos que siempre he usado y son utiles  

| cw | cambia la palabra | emacs M-d | 
|    |                   |           | 

* Aspectos que no conocia
** :changes 
te lleva adelante o atras a los cambios reales hechos en el archivo e
incluso permanece tras cerrar el archivo. Ideal para volver donde
estabamos.
** C-r en insersion mode
   te aparece unas comillas y alli puedes poner el numero de registro que 
   quieres insertar.
   se puede ver en :reg
   es de destacar el . (dot) que es todo lo ultimo insertado

* Aspectos que son interesantes
** un undo y redo separado e ilimitado.
Incluso con horario que lo vas viendo. En emacs te confunde un poco el
que mezcle undos y redos.


   
* arreglos en vim para mayor eficiencia
** buffer previo y next con [ ]
** apertura rapida de archivos usados frecuentes con ;6 ;7 etc
** apertura de orgblock ;9  Explore
** reinicio de pomodoro con ;0 
** magit facil
   inicio con :Magit
   stash con S
   commit con CC



** nuevos plugins
*** CtrlP
    busqueda de archivos en general con C-b o C-b cambio el tipo de busqueda 
    en tres posibles: mru files buf o sea archivos recientes files o buf
    una vez buscamos el archivo introduciendo el nombre, el path lo tenemos a 
    la derecha en la barra, y es el dir presente tenemos tres opciones:
    C-t abre en otro tab C-v C-x abre en split vertical o en split horizontal

    tip de busqueda: p.e. para buscar age-programacion-tcl.org poner age-tcl 
    no asi agetcl.

    para ir al directorio padre usar ..

*** superyank
    usar Alt-p o Shift-Alt-p para ciclar entre el reg de yanks
*** tagbar
    instalar desde el apt exuberant ctags
    en el directorio correr ctags files en este caso en tcl1 ctags *.tcl
    luego con tagbar (keybindeado a F4) te aparece el resumen de proc o clases 
    y metodos. Interesante en proyectos complejos

    
** insertar fecha emulando fecha inactiva de orgmode
:put =strftime('[%F %a]')
put =strftime('[%F %a]')
*** [2018-03-07 mié]
    entrada del dia 
**** [2018-03-07 mié]
     entrada del dia
        
* vimorg    
** movimiento de subtrees
   al final tanto lio y se logra con delete y pegado te borra y pega el tree 
   completo mas intuitivo que emacs

