* DONE buscador no busca ciertos casos
- State "DONE"       from "TODO"       [2019-04-09 mar 18:17]
descubri que habia que sacar la mencion a mjecobr en el armado de la
base de busqueda

#+BEGIN_SRC
.resultados.tbls insertlist end [tabule "select distinct 
    case
	when subirseven=1 then 'SUBE'
	when deuda=0 and sev=1 then 'BAJA'
	when sev=1 then 'SEV'
	when incobrable=1 then 'INC'
	when mudo=1 then 'MUD'
	when deuda>0 and clientes.pmovto<date('now','-4 months') then 'MORA'
	when deuda>0 and clientes.pmovto>=date('now','-4 months') then 'DEBE'
	when deuda=0 and baja!='' and alta!='' then 'exSEV'
	else '' END as tag,
         dni,nombre,
         calle,num,tel,zona,acla,barrio from clientes where
          tag||dni||nombre||calle||num||tel||barrio||zona||acla like '$cadbuscar'" db]

    }
#+END_SRC
En la ultima linea ||acla||mjecobr se armaba con los datos de mjecobr
y eso hacia que esos registros desaparecieran.
Habria que estar atentos que no haya otro bug parecido o que el bug se
replique en el autorizador.
* DONE problema de atravesado de combos
- State "DONE"       from "TODO"       [2019-04-16 mar 18:08]
el problema es que los combos no se pueden atravesar con <Enter> pq si
tienen valores similares se abren en vez de ser atravesados obligando
al uso de TAB lo cual es engorroso. Ejemplo en zona Cabildo/Ampliacion
Cabildo, como los dos valores contienen la palabra Cabildo si tenes
como valor Cabildo te lo abre con las dos. 
Lo solucione agregando en la deficion de clase un bind extra para
KP_Enter que pasara al elemento siguiente. 

#+BEGIN_SRC
bind $itk_interior.cb.e <<Enter>> "$this filtravalores" 
#filtracion automatica de valores por lista
bind $itk_interior.cb.e <KP_Enter> {+tk::TabToWindow [tk_focusNext %W]}
#+END_SRC

El problema de esta solucion es que hay formularios que si necesitan
que la funcion del combo este atada al KP_Enter como recibos.tcl. que
queda total inutil con estos cambios. Por lo cual opte por una
solucion a la inversa o sea poner el bind en particular luego de cada
combo que queremos atravesar por KP_Enter.

